import type { CritProcDisplayInfo } from "../index";
import { COLOR } from "../../../palette";

export const ADVENTURERS_CRIT_INFO = {
  alchemyAtDusk: {
    label: "Alchemy at Dusk",
    color: COLOR.purple,
    icon: "alchemyAtDusk",
    description: "Six free upgrades on this floor",
  },
  astropathAlleycat: {
    label: "Astropath Alleycat",
    color: COLOR.nightShiftIndigo,
    icon: "astropathAlleycat",
    description: "Eight payouts on every unlocked floor",
  },
  bardOfTheBrokenLyre: {
    label: "Bard of the Broken Lyre",
    color: COLOR.peppermintPink,
    icon: "bardOfTheBrokenLyre",
    description: "Seven instant payouts on this floor",
  },
  battleStandardBobcat: {
    label: "Battle Standard Bobcat",
    color: COLOR.red,
    icon: "battleStandardBobcat",
    description: "Ten free upgrades on this floor",
  },
  cathedralStarship: {
    label: "Cathedral Starship",
    color: COLOR.blue,
    icon: "cathedralStarship",
    description: "Twelve payouts on every unlocked floor",
  },
  cursedCrownHunt: {
    label: "Cursed Crown Hunt",
    color: COLOR.fullHouseCrimson,
    icon: "cursedCrownHunt",
    description: "Fifteen free upgrades on this floor",
  },
  dreadnoughtWhisker: {
    label: "Dreadnought Whisker",
    color: COLOR.unionBossSlate,
    icon: "dreadnoughtWhisker",
    description: "Twenty free upgrades on this floor",
  },
  elixirUnderMoonlight: {
    label: "Elixir Under Moonlight",
    color: COLOR.silverTicketGray,
    icon: "elixirUnderMoonlight",
    description: "One tier promotion and seven upgrades here",
  },
  frostbiteTracker: {
    label: "Frostbite Tracker",
    color: COLOR.frozenIceBlue,
    icon: "frostbiteTracker",
    description: "Nine payouts from the highest-earning floor",
  },
  ironpawVanguard: {
    label: "Ironpaw Vanguard",
    color: COLOR.gold,
    icon: "ironpawVanguard",
    description: "Eleven free upgrades on every unlocked floor",
  },
  lastStandLionheart: {
    label: "Last Stand Lionheart",
    color: COLOR.red,
    icon: "lastStandLionheart",
    description: "Fourteen free upgrades on this floor",
  },
  meowchineBerserker: {
    label: "Meowchine Berserker",
    color: COLOR.orange,
    icon: "meowchineBerserker",
    description: "Eight free upgrades on this floor",
  },
  meowtallicanGunner: {
    label: "Meowtallican Gunner",
    color: COLOR.silverTicketGray,
    icon: "meowtallicanGunner",
    description: "Ten payouts from the highest-earning floor",
  },
  midnightMonsterContract: {
    label: "Midnight Monster Contract",
    color: COLOR.nightShiftIndigo,
    icon: "midnightMonsterContract",
    description: "Six free upgrades on the lowest-level floor",
  },
  moonlitWyvernHunt: {
    label: "Moonlit Wyvern Hunt",
    color: COLOR.blue,
    icon: "moonlitWyvernHunt",
    description: "Thirteen payouts on this floor",
  },
  orbitalPounce: {
    label: "Orbital Pounce",
    color: COLOR.cyan,
    icon: "orbitalPounce",
    description: "Five free upgrades on every unlocked floor",
  },
  plasmaPurrgeon: {
    label: "Plasma Purrgeon",
    color: COLOR.blue,
    icon: "plasmaPurrgeon",
    description: "Nine free upgrades on this floor",
  },
  relicbladeRonin: {
    label: "Relicblade Ronin",
    color: COLOR.fullHouseCrimson,
    icon: "relicbladeRonin",
    description: "Sixteen free upgrades on this floor",
  },
  seaMonsterSlayer: {
    label: "Sea Monster Slayer",
    color: COLOR.cyan,
    icon: "seaMonsterSlayer",
    description: "Ten instant payouts on this floor",
  },
  silverclawSentinel: {
    label: "Silverclaw Sentinel",
    color: COLOR.silverTicketGray,
    icon: "silverclawSentinel",
    description: "Seven free upgrades on this floor",
  },
  starBastionCaptain: {
    label: "Star Bastion Captain",
    color: COLOR.blue,
    icon: "starBastionCaptain",
    description: "Twelve free upgrades on this floor",
  },
  tavernTactician: {
    label: "Tavern Tactician",
    color: COLOR.autumnSaleAmber,
    icon: "tavernTactician",
    description: "Eight payouts on every unlocked floor",
  },
  theAntlerwoodStalker: {
    label: "The Antlerwood Stalker",
    color: COLOR.moneyGreen,
    icon: "theAntlerwoodStalker",
    description: "One tier promotion and five upgrades here",
  },
  theCataclysmicChaplain: {
    label: "The Cataclysmic Chaplain",
    color: COLOR.fullHouseCrimson,
    icon: "theCataclysmicChaplain",
    description: "Fifteen free upgrades on this floor",
  },
  theGriffinContract: {
    label: "The Griffin Contract",
    color: COLOR.gold,
    icon: "theGriffinContract",
    description: "Nine payouts on the highest-earning floor",
  },
  theSiegeScratcher: {
    label: "The Siege Scratcher",
    color: COLOR.red,
    icon: "theSiegeScratcher",
    description: "Eighteen free upgrades on this floor",
  },
  theWarpwayWatcher: {
    label: "The Warpway Watcher",
    color: COLOR.purple,
    icon: "theWarpwayWatcher",
    description: "Six payouts on every unlocked floor",
  },
  theWhiteWhisker: {
    label: "The White Whisker",
    color: COLOR.white,
    icon: "theWhiteWhisker",
    description: "Ten free upgrades on the highest floor",
  },
  toxinclawInfiltrator: {
    label: "Toxinclaw Infiltrator",
    color: COLOR.dressCodeGreen,
    icon: "toxinclawInfiltrator",
    description: "Seven instant payouts on this floor",
  },
  voidclawVeteran: {
    label: "Voidclaw Veteran",
    color: COLOR.nightShiftIndigo,
    icon: "voidclawVeteran",
    description: "Thirteen free upgrades on this floor",
  },
  voidshieldTemplar: {
    label: "Voidshield Templar",
    color: COLOR.blue,
    icon: "voidshieldTemplar",
    description: "Eight free upgrades on every unlocked floor",
  },
  wolfmarkWanderer: {
    label: "Wolfmark Wanderer",
    color: COLOR.silverTicketGray,
    icon: "wolfmarkWanderer",
    description: "Eleven payouts from the highest-earning floor",
  },
  wolfpackFarewell: {
    label: "Wolfpack Farewell",
    color: COLOR.peppermintPink,
    icon: "wolfpackFarewell",
    description: "Six free upgrades on every unlocked floor",
  },
  bloodlineOmen: {
    label: "Bloodline Omen",
    color: COLOR.fullHouseCrimson,
    icon: "bloodlineOmen",
    description: "Seventeen free upgrades on this floor",
  },
  candleclawCatacomb: {
    label: "Candleclaw Catacomb",
    color: COLOR.nightShiftIndigo,
    icon: "candleclawCatacomb",
    description: "Fourteen instant payouts on this floor",
  },
  emberPawPatrol: {
    label: "Ember Paw Patrol",
    color: COLOR.orange,
    icon: "emberPawPatrol",
    description: "Fourteen free upgrades on every unlocked floor",
  },
  whiskerCoastSurvivor: {
    label: "Whisker Coast Survivor",
    color: COLOR.cyan,
    icon: "whiskerCoastSurvivor",
    description: "Seventeen payouts from the highest-earning floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
