import type { CritProcDisplayInfo } from "../index";
import { COLOR } from "../../../palette";

export const BAKERY_CRIT_INFO = {
  butterCroissant: {
    label: "Butter Croissant",
    color: COLOR.gold,
    icon: "butterCroissant",
    description: "Thirty-nine free upgrades on this floor",
  },
  almondEncore: {
    label: "Almond Encore",
    color: COLOR.amberMuted,
    icon: "almondEncore",
    description: "Thirty-six instant payouts on this floor",
  },
  babkaRhapsody: {
    label: "Babka Rhapsody",
    color: COLOR.chairGiveawayBrown,
    icon: "babkaRhapsody",
    description: "Forty free upgrades on alternating floors",
  },
  bagelBoulevard: {
    label: "Bagel Boulevard",
    color: COLOR.goldenParachuteMarigold,
    icon: "bagelBoulevard",
    description: "Thirty-eight payouts on every unlocked floor",
  },
  baguetteBaton: {
    label: "Baguette Baton",
    color: COLOR.supplyRunTan,
    icon: "baguetteBaton",
    description: "Thirty-nine upgrades on the lowest-level floor",
  },
  briocheBonanza: {
    label: "Brioche Bonanza",
    color: COLOR.sunshineGold,
    icon: "briocheBonanza",
    description: "Forty-four free upgrades on this floor",
  },
  breadWinner: {
    label: "Bread Winner",
    color: COLOR.goldenHandshakeGold,
    icon: "breadWinner",
    description: "Twenty-two upgrades and twenty payouts on the top earner",
  },
  challahCharm: {
    label: "Challah Charm",
    color: COLOR.amber,
    icon: "challahCharm",
    description: "One tier promotion and twenty-two upgrades here",
  },
  chouxBusiness: {
    label: "Choux Business",
    color: COLOR.red,
    icon: "chouxBusiness",
    description: "Twenty upgrades and eighteen payouts on this floor",
  },
  cinnamonSpin: {
    label: "Cinnamon Spin",
    color: COLOR.headhunterRust,
    icon: "cinnamonSpin",
    description: "Thirty upgrades here and on the lowest-level floor",
  },
  icingOnTheBun: {
    label: "Icing on the Bun",
    color: COLOR.teaBreakBrown,
    icon: "icingOnTheBun",
    description: "Thirty-seven payouts on alternating floors",
  },
  cruffinSummit: {
    label: "Cruffin Summit",
    color: COLOR.fullHouseCrimson,
    icon: "cruffinSummit",
    description: "Forty-six upgrades on the highest unlocked floor",
  },
  custardCrown: {
    label: "Custard Crown",
    color: COLOR.goldenTicketYellow,
    icon: "custardCrown",
    description: "Two tier promotions and twenty upgrades here",
  },
  danishDaydream: {
    label: "Danish Daydream",
    color: COLOR.grandOpeningRose,
    icon: "danishDaydream",
    description: "Forty-three instant payouts on this floor",
  },
  eclairFlair: {
    label: "Eclair Flair",
    color: COLOR.peppermintPink,
    icon: "eclairFlair",
    description: "Forty-seven free upgrades on this floor",
  },
  focacciaFiesta: {
    label: "Focaccia Fiesta",
    color: COLOR.payoutOlive,
    icon: "focacciaFiesta",
    description: "Forty-two upgrades on every unlocked floor",
  },
  jamSession: {
    label: "Jam Session",
    color: COLOR.redActive,
    icon: "jamSession",
    description: "Thirty-five payouts on every unlocked floor",
  },
  sconeWithTheWind: {
    label: "Scone With the Wind",
    color: COLOR.springSalePink,
    icon: "sconeWithTheWind",
    description: "Forty upgrades on the cheapest floor to upgrade",
  },
  knotYourAverage: {
    label: "Knot Your Average",
    color: COLOR.espressoShotBrown,
    icon: "knotYourAverage",
    description: "Thirty-eight upgrades here and on the highest floor",
  },
  naanStop: {
    label: "Naan Stop",
    color: COLOR.luckyCloverGreen,
    icon: "naanStop",
    description: "Forty-four payouts on every unlocked floor",
  },
  palmierParade: {
    label: "Palmier Parade",
    color: COLOR.autumnSaleAmber,
    icon: "palmierParade",
    description: "Forty-five upgrades marching down the floors below",
  },
  pistachioPalace: {
    label: "Pistachio Palace",
    color: COLOR.suppliesGiveawayLime,
    icon: "pistachioPalace",
    description: "Forty-eight upgrades on the highest unlocked floor",
  },
  pitaPocketPayday: {
    label: "Pita Pocket Payday",
    color: COLOR.coinGold,
    icon: "pitaPocketPayday",
    description: "Forty-six instant payouts on this floor",
  },
  ryeOnThePrize: {
    label: "Rye on the Prize",
    color: COLOR.mysticTeal,
    icon: "ryeOnThePrize",
    description: "Thirty-nine payouts from the highest-earning floor",
  },
  shokupanCloud: {
    label: "Shokupan Cloud",
    color: COLOR.secondWindSky,
    icon: "shokupanCloud",
    description: "Thirty-eight upgrades on this floor and every floor below",
  },
  sourdoughSunrise: {
    label: "Sourdough Sunrise",
    color: COLOR.summerSaleOrange,
    icon: "sourdoughSunrise",
    description: "Forty payouts on the lowest-level floor",
  },
  strudelCuddle: {
    label: "Strudel Cuddle",
    color: COLOR.roundUpOrange,
    icon: "strudelCuddle",
    description: "Twenty-four upgrades and sixteen payouts on the lowest floor",
  },
  appleOfMyEye: {
    label: "Apple of My Eye",
    color: COLOR.fireDrillRed,
    icon: "appleOfMyEye",
    description: "Forty-three payouts on alternating floors",
  },
  turnoverTreasure: {
    label: "Turnover Treasure",
    color: COLOR.bonusRoundGold,
    icon: "turnoverTreasure",
    description: "Forty-nine instant payouts on this floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
