import type { CritProcDisplayInfo } from "../index";
import { COLOR } from "../../../palette";

export const CANDY_CRIT_INFO = {
  chocolateFountainOfYouth: {
    label: "Chocolate Fountain of Youth",
    color: COLOR.autumnSaleAmber,
    icon: "chocolateFountainOfYouth",
    description: "Twenty instant payouts on this floor",
  },
  gummyBearMarket: {
    label: "Gummy Bear Market",
    color: COLOR.red,
    icon: "gummyBearMarket",
    description: "Ten free upgrades on every unlocked floor",
  },
  jawbreaker: {
    label: "Jawbreaker",
    color: COLOR.purple,
    icon: "jawbreaker",
    description: "Eighteen free upgrades on this floor",
  },
  licoriceLaces: {
    label: "Licorice Laces",
    color: COLOR.fullHouseCrimson,
    icon: "licoriceLaces",
    description: "Nine free upgrades on the lowest-level floor",
  },
  lollipopGuild: {
    label: "Lollipop Guild",
    color: COLOR.peppermintPink,
    icon: "lollipopGuild",
    description: "Twelve payouts on alternating floors, from the ground",
  },
  marshmallowMountain: {
    label: "Marshmallow Mountain",
    color: COLOR.white,
    icon: "marshmallowMountain",
    description: "Eight free upgrades on the highest unlocked floor",
  },
  sugarHigh: {
    label: "Sugar High",
    color: COLOR.starYellow,
    icon: "sugarHigh",
    description: "Five upgrades and five payouts on every unlocked floor",
  },
  bubblegumBalloon: {
    label: "Bubblegum Balloon",
    color: COLOR.springSalePink,
    icon: "bubblegumBalloon",
    description: "Fifteen instant payouts on this floor",
  },
  candyCaneClimber: {
    label: "Candy Cane Climber",
    color: COLOR.red,
    icon: "candyCaneClimber",
    description: "Twelve free upgrades on the highest unlocked floor",
  },
  sherbetSherpa: {
    label: "Sherbet Sherpa",
    color: COLOR.easterSalePink,
    icon: "sherbetSherpa",
    description: "Eight instant payouts on every unlocked floor",
  },
  toffeeTrap: {
    label: "Toffee Trap",
    color: COLOR.autumnSaleAmber,
    icon: "toffeeTrap",
    description: "Seven free upgrades on this floor",
  },
  cottonCandyCloud: {
    label: "Cotton Candy Cloud",
    color: COLOR.peppermintPink,
    icon: "cottonCandyCloud",
    description: "Eleven instant payouts on this floor",
  },
  fudgeIt: {
    label: "Fudge It",
    color: COLOR.autumnSaleAmber,
    icon: "fudgeIt",
    description: "Fourteen free upgrades on this floor",
  },
  gobstopperGetaway: {
    label: "Gobstopper Getaway",
    color: COLOR.orange,
    icon: "gobstopperGetaway",
    description: "Thirteen free upgrades on the highest floor",
  },
  jellyBeanJamboree: {
    label: "Jelly Bean Jamboree",
    color: COLOR.springSalePink,
    icon: "jellyBeanJamboree",
    description: "Ten payouts on alternating floors, from the ground",
  },
  rockCandyQuarry: {
    label: "Rock Candy Quarry",
    color: COLOR.cyan,
    icon: "rockCandyQuarry",
    description: "One tier promotion and seven upgrades here",
  },
  sprinkleStorm: {
    label: "Sprinkle Storm",
    color: COLOR.blue,
    icon: "sprinkleStorm",
    description: "Six free upgrades on every unlocked floor",
  },
  candyCastle: {
    label: "Candy Castle",
    color: COLOR.peppermintPink,
    icon: "candyCastle",
    description: "Thirty-six payouts on every unlocked floor",
  },
  caramelApple: {
    label: "Caramel Apple",
    color: COLOR.autumnSaleAmber,
    icon: "caramelApple",
    description: "Twenty-eight free upgrades on this floor",
  },
  moonlitMint: {
    label: "Moonlit Mint",
    color: COLOR.moneyGreen,
    icon: "moonlitMint",
    description: "Twenty-six payouts on alternating floors",
  },
  gumdropGazillionaire: {
    label: "Gumdrop Gazillionaire",
    color: COLOR.bonusRoundGold,
    icon: "gumdropGazillionaire",
    description: "Forty-one upgrades on every unlocked floor",
  },
  candyCornCornucopia: {
    label: "Candy Corn Cornucopia",
    color: COLOR.autumnSaleAmber,
    icon: "candyCornCornucopia",
    description: "Forty-one payouts on every unlocked floor",
  },
  butterscotchBuyout: {
    label: "Butterscotch Buyout",
    color: COLOR.goldStandardAmber,
    icon: "butterscotchBuyout",
    description: "Forty-two upgrades on the cheapest floor to upgrade",
  },
  sourStrawSprint: {
    label: "Sour Straw Sprint",
    color: COLOR.fastForwardBlue,
    icon: "sourStrawSprint",
    description: "Thirty-six upgrades here and on the highest floor",
  },
  pralinePremium: {
    label: "Praline Premium",
    color: COLOR.amberMuted,
    icon: "pralinePremium",
    description: "One tier promotion and twenty-eight upgrades here",
  },
  fizzyFortune: {
    label: "Fizzy Fortune",
    color: COLOR.cyan,
    icon: "fizzyFortune",
    description: "Forty-eight payouts on the lowest-level floor",
  },
  marzipanMogul: {
    label: "Marzipan Mogul",
    color: COLOR.peppermintPink,
    icon: "marzipanMogul",
    description: "Fifty instant payouts on this floor",
  },
  gummyWormWealth: {
    label: "Gummy Worm Wealth",
    color: COLOR.bullMarketGreen,
    icon: "gummyWormWealth",
    description: "Forty-four upgrades on the lowest-level floor",
  },
  chocolateCoinCartel: {
    label: "Chocolate Coin Cartel",
    color: COLOR.coinGold,
    icon: "chocolateCoinCartel",
    description: "Nineteen upgrades and twenty-five payouts on the top earner",
  },
  honeycombHustle: {
    label: "Honeycomb Hustle",
    color: COLOR.amber,
    icon: "honeycombHustle",
    description: "Thirty-six free upgrades on alternating floors",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
