import type { CritProcDisplayInfo } from "../index";
import { COLOR } from "../../../palette";

export const COMFORT_FOOD_CRIT_INFO = {
  breadyOrNot: {
    label: "Bready or Not",
    color: COLOR.goldenHandshakeGold,
    icon: "breadyOrNot",
    description: "Eleven upgrades on this floor and every floor below",
  },
  eggcellentWork: {
    label: "Egg-cellent Work",
    color: COLOR.sunshineGold,
    icon: "eggcellentWork",
    description: "One tier promotion and eight upgrades here",
  },
  holyGuacamole: {
    label: "Holy Guacamole",
    color: COLOR.dressCodeGreen,
    icon: "holyGuacamole",
    description: "Nineteen instant payouts on every unlocked floor",
  },
  loafActually: {
    label: "Loaf Actually",
    color: COLOR.espressoShotBrown,
    icon: "loafActually",
    description: "Twelve free upgrades on every unlocked floor",
  },
  pastaLaVista: {
    label: "Pasta La Vista",
    color: COLOR.orange,
    icon: "pastaLaVista",
    description: "Sixteen payouts on alternating floors, from the ground",
  },
  souperStar: {
    label: "Souper Star",
    color: COLOR.amberMuted,
    icon: "souperStar",
    description: "Sixteen payouts from the highest-earning floor",
  },
  tacoBoutIt: {
    label: "Taco 'Bout It",
    color: COLOR.autumnSaleAmber,
    icon: "tacoBoutIt",
    description: "Four upgrades here and four on the lowest-level floor",
  },
  theGreatPancakeStack: {
    label: "The Great Pancake Stack",
    color: COLOR.supplyRunTan,
    icon: "theGreatPancakeStack",
    description: "Twenty-one upgrades here and every floor below",
  },
  wokAndRoll: {
    label: "Wok and Roll",
    color: COLOR.summerSaleOrange,
    icon: "wokAndRoll",
    description: "Twenty-four free upgrades on the highest floor",
  },
  avocardio: {
    label: "Avocardio",
    color: COLOR.bullMarketGreen,
    icon: "avocardio",
    description: "Fifteen free upgrades on this floor",
  },
  butterBelieveIt: {
    label: "Butter Believe It",
    color: COLOR.sunshineGold,
    icon: "butterBelieveIt",
    description: "Eighteen instant payouts on this floor",
  },
  cheesePullChampion: {
    label: "Cheese Pull Champion",
    color: COLOR.goldenHandshakeGold,
    icon: "cheesePullChampion",
    description: "Six upgrades and six payouts on this floor",
  },
  grillSergeant: {
    label: "Grill Sergeant",
    color: COLOR.red,
    icon: "grillSergeant",
    description: "Twenty free upgrades on every unlocked floor",
  },
  noodleNap: {
    label: "Noodle Nap",
    color: COLOR.autumnSaleAmber,
    icon: "noodleNap",
    description: "Twenty-two payouts on alternating floors, from the ground",
  },
  picklePredicament: {
    label: "Pickle Predicament",
    color: COLOR.dressCodeGreen,
    icon: "picklePredicament",
    description: "Eight free upgrades on the lowest-level floor",
  },
  hotPotato: {
    label: "Hot Potato",
    color: COLOR.roundUpOrange,
    icon: "hotPotato",
    description: "Eighteen instant payouts on this floor",
  },
  brunchBoss: {
    label: "Brunch Boss",
    color: COLOR.supplyRunTan,
    icon: "brunchBoss",
    description: "Seven upgrades and seven payouts on this floor",
  },
  curryFavour: {
    label: "Curry Favour",
    color: COLOR.halloweenSalePurple,
    icon: "curryFavour",
    description: "Fourteen payouts from the highest-earning floor",
  },
  dimSumDynasty: {
    label: "Dim Sum Dynasty",
    color: COLOR.goldenHandshakeGold,
    icon: "dimSumDynasty",
    description: "Fifteen free upgrades on every unlocked floor",
  },
  soupDumplingSurgeon: {
    label: "Soup Dumpling Surgeon",
    color: COLOR.teaBreakBrown,
    icon: "soupDumplingSurgeon",
    description: "Five upgrades and ten payouts on this floor",
  },
  cheeseWheel: {
    label: "Cheese Wheel",
    color: COLOR.gold,
    icon: "cheeseWheel",
    description: "Thirty-four instant payouts on this floor",
  },
  honeyToast: {
    label: "Honey Toast",
    color: COLOR.goldenTicketYellow,
    icon: "honeyToast",
    description: "Twenty-three free upgrades on the lowest-level floor",
  },
  sushiPlatter: {
    label: "Sushi Platter",
    color: COLOR.red,
    icon: "sushiPlatter",
    description: "Twenty-six payouts on alternating floors",
  },
  comfortFood: {
    label: "Comfort Food",
    color: COLOR.moneyGreen,
    icon: "comfortFood",
    description: "Twenty-four free upgrades on the lowest-level floor",
  },
  pickleParade: {
    label: "Pickle Parade",
    color: COLOR.suppliesGiveawayLime,
    icon: "pickleParade",
    description: "Twenty-five upgrades on the lowest-level floor",
  },
  ramenCrown: {
    label: "Ramen Crown",
    color: COLOR.goldenHandshakeGold,
    icon: "ramenCrown",
    description: "Thirty-five payouts on every unlocked floor",
  },
  thunderNachos: {
    label: "Thunder Nachos",
    color: COLOR.orange,
    icon: "thunderNachos",
    description: "Twenty-eight free upgrades on every unlocked floor",
  },
  loadedBurger: {
    label: "Loaded Burger",
    color: COLOR.orange,
    icon: "loadedBurger",
    description: "Twenty-four free upgrades on this floor",
  },
  tacoFeast: {
    label: "Taco Feast",
    color: COLOR.red,
    icon: "tacoFeast",
    description: "Twenty-two instant payouts on every unlocked floor",
  },
  pizzaSupreme: {
    label: "Pizza Supreme",
    color: COLOR.sunshineGold,
    icon: "pizzaSupreme",
    description: "Twenty-six free upgrades on this floor",
  },
  sushiPlatter2: {
    label: "Sushi Deluxe",
    color: COLOR.blue,
    icon: "sushiPlatter2",
    description: "Twenty-eight instant payouts on this floor",
  },
  sushiPlatter3: {
    label: "Sushi Surge",
    color: COLOR.luckyCloverGreen,
    icon: "sushiPlatter3",
    description: "Twenty-three free upgrades on this floor",
  },
  sushiPlatter4: {
    label: "Sushi Royal",
    color: COLOR.starYellow,
    icon: "sushiPlatter4",
    description: "Thirty instant payouts on every unlocked floor",
  },
  ramenBowl: {
    label: "Ramen Bowl",
    color: COLOR.teaBreakBrown,
    icon: "ramenBowl",
    description: "Twenty-seven free upgrades on this floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
