import type { CritProcDisplayInfo } from "../index";
import { COLOR } from "../../../palette";

export const DRINKS_CRIT_INFO = {
  berrySmoothie: {
    label: "Berry Smoothie",
    color: COLOR.peppermintPink,
    icon: "berrySmoothie",
    description: "Thirty-two payouts from the highest-earning floor",
  },
  spicedChai: {
    label: "Spiced Chai",
    color: COLOR.autumnSaleAmber,
    icon: "spicedChai",
    description: "Thirty-five instant payouts on this floor",
  },
  mochaFroth: {
    label: "Mocha Froth",
    color: COLOR.teaBreakBrown,
    icon: "mochaFroth",
    description: "Twenty-eight instant payouts on this floor",
  },
  treasureTeapot: {
    label: "Treasure Teapot",
    color: COLOR.gold,
    icon: "treasureTeapot",
    description: "Thirty-four payouts from the highest-earning floor",
  },
  berrySmoothie2: {
    label: "Berry Blast",
    color: COLOR.springSalePink,
    icon: "berrySmoothie2",
    description: "Twenty-nine instant payouts on this floor",
  },
  berrySmoothie3: {
    label: "Berry Velvet",
    color: COLOR.blue,
    icon: "berrySmoothie3",
    description: "Twenty-five free upgrades on this floor",
  },
  berrySmoothie4: {
    label: "Berry Royale",
    color: COLOR.luckyCloverGreen,
    icon: "berrySmoothie4",
    description: "Thirty-one instant payouts on every unlocked floor",
  },
  icedCoffee: {
    label: "Iced Coffee",
    color: COLOR.teaBreakBrown,
    icon: "icedCoffee",
    description: "Eighteen instant payouts on this floor",
  },
  tropicalLemonade: {
    label: "Tropical Lemonade",
    color: COLOR.sunshineGold,
    icon: "tropicalLemonade",
    description: "Twenty free upgrades on this floor",
  },
  tropicalLemonade2: {
    label: "Citrus Fizz",
    color: COLOR.luckyCloverGreen,
    icon: "tropicalLemonade2",
    description: "Twenty-four instant payouts on this floor",
  },
  hotChocolate: {
    label: "Hot Chocolate",
    color: COLOR.teaBreakBrown,
    icon: "hotChocolate",
    description: "Nineteen free upgrades on this floor",
  },
  hotChocolate2: {
    label: "Marshmallow Melt",
    color: COLOR.gold,
    icon: "hotChocolate2",
    description: "Twenty-one instant payouts on every unlocked floor",
  },
  sunsetMargarita: {
    label: "Sunset Margarita",
    color: COLOR.orange,
    icon: "sunsetMargarita",
    description: "Seventeen free upgrades on this floor",
  },
  blueLagoonCocktail: {
    label: "Blue Lagoon",
    color: COLOR.blue,
    icon: "blueLagoonCocktail",
    description: "Twenty-two free upgrades on this floor",
  },
  blueLagoonCocktail2: {
    label: "Lagoon Fizz",
    color: COLOR.blue,
    icon: "blueLagoonCocktail2",
    description: "Twenty-three instant payouts on this floor",
  },
  blueLagoonCocktail3: {
    label: "Azure Splash",
    color: COLOR.springSalePink,
    icon: "blueLagoonCocktail3",
    description: "Twenty-five free upgrades on this floor",
  },
  strawberryDaiquiri: {
    label: "Strawberry Daiquiri",
    color: COLOR.springSalePink,
    icon: "strawberryDaiquiri",
    description: "Twenty-seven instant payouts on this floor",
  },
  mangoMojito: {
    label: "Mango Mojito",
    color: COLOR.sunshineGold,
    icon: "mangoMojito",
    description: "Twenty-four free upgrades on this floor",
  },
  mangoMojito2: {
    label: "Mango Mint",
    color: COLOR.luckyCloverGreen,
    icon: "mangoMojito2",
    description: "Twenty-six instant payouts on this floor",
  },
  espressoMartini: {
    label: "Espresso Martini",
    color: COLOR.teaBreakBrown,
    icon: "espressoMartini",
    description: "Thirty-two instant payouts on every unlocked floor",
  },
  beerBelly: {
    label: "Beer Belly",
    color: COLOR.amber,
    icon: "beerBelly",
    description: "Twenty-three instant payouts on this floor",
  },
  bottomsUp: {
    label: "Bottoms Up",
    color: COLOR.teaBreakBrown,
    icon: "bottomsUp",
    description: "Twenty-five free upgrades on this floor",
  },
  wineCountry: {
    label: "Wine ",
    color: COLOR.fullHouseCrimson,
    icon: "wineCountry",
    description: "Twenty-seven instant payouts on every other floor",
  },
  ponyKeg: {
    label: "Pony Keg",
    color: COLOR.chairGiveawayBrown,
    icon: "ponyKeg",
    description: "Twenty-eight payouts on the lowest-level floor",
  },
  vodkaWhiskers: {
    label: "Top Shelf",
    color: COLOR.pairBlue,
    icon: "vodkaWhiskers",
    description: "Thirty-one free upgrades on the highest unlocked floor",
  },
  emptyGlass: {
    label: "On the Rocks",
    color: COLOR.snowdayFrost,
    icon: "emptyGlass",
    description: "Nineteen instant payouts on this floor",
  },
  amberSpritz: {
    label: "Amber Spritz",
    color: COLOR.summerSaleOrange,
    icon: "amberSpritz",
    description: "Twenty instant payouts on this floor",
  },
  copperMugMule2: {
    label: "Mule Kick",
    color: COLOR.roundUpOrange,
    icon: "copperMugMule2",
    description: "Twenty-one instant payouts on this floor",
  },
  negroniNightfall2: {
    label: "Bitter Bounty",
    color: COLOR.fullHouseCrimson,
    icon: "negroniNightfall2",
    description: "Twenty-four instant payouts on this floor",
  },
  blackberryBramble: {
    label: "Blackberry Bramble",
    color: COLOR.purple,
    icon: "blackberryBramble",
    description: "Twenty-two free upgrades on this floor",
  },
  blackberryBramble2: {
    label: "Bramble Bounty",
    color: COLOR.halloweenSalePurple,
    icon: "blackberryBramble2",
    description: "Twenty-one free upgrades on every other floor",
  },
  singaporeSling: {
    label: "Singapore Sling",
    color: COLOR.springSalePink,
    icon: "singaporeSling",
    description: "Twenty-five instant payouts on every other floor",
  },
  derbyDayJulep: {
    label: "Derby Day Julep",
    color: COLOR.luckyCloverGreen,
    icon: "derbyDayJulep",
    description: "Twenty-seven free upgrades on this floor",
  },
  derbyDayJulep2: {
    label: "Frostcup Julep",
    color: COLOR.silverTicketGray,
    icon: "derbyDayJulep2",
    description: "Twenty-six payouts on the lowest-level floor",
  },
  hurricaneHour: {
    label: "Hurricane Hour",
    color: COLOR.red,
    icon: "hurricaneHour",
    description: "Twenty-eight free upgrades on this floor",
  },
  cosmoCashout: {
    label: "Cosmo Cashout",
    color: COLOR.peppermintPink,
    icon: "cosmoCashout",
    description: "Twenty-nine free upgrades on this floor",
  },
  frenchSeventyFive: {
    label: "French Seventy-Five",
    color: COLOR.sunshineGold,
    icon: "frenchSeventyFive",
    description: "Twenty-six free upgrades on every other floor",
  },
  sidecarSurge: {
    label: "Sidecar Surge",
    color: COLOR.amber,
    icon: "sidecarSurge",
    description: "Twenty-seven upgrades on the highest unlocked floor",
  },
  hurricaneHour2: {
    label: "Eye of the Storm",
    color: COLOR.grandOpeningRose,
    icon: "hurricaneHour2",
    description: "Thirty-one instant payouts on every other floor",
  },
  copperMugMule: {
    label: "Copper Mug Mule",
    color: COLOR.goldenParachuteMarigold,
    icon: "copperMugMule",
    description: "Thirty free upgrades on every unlocked floor",
  },
  pineappleParadise: {
    label: "Pineapple Paradise",
    color: COLOR.sunshineGold,
    icon: "pineappleParadise",
    description: "Thirty-one upgrades on this floor and every floor below",
  },
  negroniNightfall: {
    label: "Negroni Nightfall",
    color: COLOR.redActive,
    icon: "negroniNightfall",
    description: "Thirty upgrades here and on the highest floor",
  },
  oldFashionedFortune: {
    label: "Old Fashioned Fortune",
    color: COLOR.goldStandardAmber,
    icon: "oldFashionedFortune",
    description: "Thirty-four payouts from the highest-earning floor",
  },
  tikiZombie: {
    label: "Tiki Zombie",
    color: COLOR.chairGiveawayBrown,
    icon: "tikiZombie",
    description: "Thirty-three instant payouts on every unlocked floor",
  },
  tikiZombie2: {
    label: "Tiki Torch",
    color: COLOR.orange,
    icon: "tikiZombie2",
    description: "Twenty upgrades, then twenty payouts on this floor",
  },
  longIslandLandslide: {
    label: "Long Island Landslide",
    color: COLOR.teaBreakBrown,
    icon: "longIslandLandslide",
    description: "Thirty-six instant payouts on every unlocked floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
