import type { CritProcDisplayInfo } from "../index";
import { COLOR } from "../../../palette";

export const GAMER_LIFE_CRIT_INFO = {
  dungeonAccountant: {
    label: "Dungeon Accountant",
    color: COLOR.nightShiftIndigo,
    icon: "dungeonAccountant",
    description: "Nine free upgrades on this floor",
  },
  lootGoblin: {
    label: "Loot Goblin",
    color: COLOR.bullMarketGreen,
    icon: "lootGoblin",
    description: "Sixteen instant payouts on this floor",
  },
  inventoryFull: {
    label: "Inventory Full",
    color: COLOR.gold,
    icon: "inventoryFull",
    description: "Twelve free upgrades on this floor",
  },
  sideQuestSalary: {
    label: "Side Quest Salary",
    color: COLOR.heavenlyGold,
    icon: "sideQuestSalary",
    description: "Seven payouts from the highest-earning floor",
  },
  minMaxManager: {
    label: "Min-Max Manager",
    color: COLOR.cyan,
    icon: "minMaxManager",
    description: "Ten free upgrades on the lowest-level floor",
  },
  criticalKnit: {
    label: "Critical Knit",
    color: COLOR.peppermintPink,
    icon: "criticalKnit",
    description: "Six payouts on alternating floors, from the ground",
  },
  savePointSavings: {
    label: "Save Point Savings",
    color: COLOR.blue,
    icon: "savePointSavings",
    description: "One tier promotion and five upgrades here",
  },
  achievementUnlocked: {
    label: "Achievement Unlocked",
    color: COLOR.starYellow,
    icon: "achievementUnlocked",
    description: "One tier promotion and eight upgrades here",
  },
  newGamePlus: {
    label: "New Game Plus",
    color: COLOR.orange,
    icon: "newGamePlus",
    description: "Twenty free upgrades on this floor",
  },
  speedrunPayroll: {
    label: "Speedrun Payroll",
    color: COLOR.red,
    icon: "speedrunPayroll",
    description: "Fifteen instant payouts on every unlocked floor",
  },
  lagCompensation: {
    label: "Lag Compensation",
    color: COLOR.silverTicketGray,
    icon: "lagCompensation",
    description: "Nine instant payouts on this floor",
  },
  patchNotesPayday: {
    label: "Patch Notes Payday",
    color: COLOR.moneyGreen,
    icon: "patchNotesPayday",
    description: "Eleven free upgrades on the highest floor",
  },
  biggerOnTheInside: {
    label: "Bigger on the Inside",
    color: COLOR.blue,
    icon: "biggerOnTheInside",
    description: "Ten instant payouts on every unlocked floor",
  },
  cacheMeOutside: {
    label: "Cache Me Outside",
    color: COLOR.orange,
    icon: "cacheMeOutside",
    description: "Eight free upgrades on the lowest-level floor",
  },
  itCompiles: {
    label: "It Compiles!",
    color: COLOR.moneyGreen,
    icon: "itCompiles",
    description: "Fifteen free upgrades on this floor",
  },
  magicalPayrollGirl: {
    label: "Magical Payroll Girl",
    color: COLOR.peppermintPink,
    icon: "magicalPayrollGirl",
    description: "One tier promotion and ten upgrades here",
  },
  mechaMiddleManagement: {
    label: "Mecha Middle Management",
    color: COLOR.red,
    icon: "mechaMiddleManagement",
    description: "Twelve free upgrades on every unlocked floor",
  },
  mergeConflict: {
    label: "Merge Conflict",
    color: COLOR.fullHouseCrimson,
    icon: "mergeConflict",
    description: "Seven upgrades and seven payouts on this floor",
  },
  mintCondition: {
    label: "Mint Condition",
    color: COLOR.cyan,
    icon: "mintCondition",
    description: "Eighteen payouts from the highest-earning floor",
  },
  stackOverflowing: {
    label: "Stack Overflowing",
    color: COLOR.gold,
    icon: "stackOverflowing",
    description: "Nine free upgrades on the highest floor",
  },
  oneMoreRound: {
    label: "One More Round",
    color: COLOR.sunshineGold,
    icon: "oneMoreRound",
    description: "Eight upgrades and eight payouts on this floor",
  },
  couchCoOpCapital: {
    label: "Couch Co-Op Capital",
    color: COLOR.blue,
    icon: "couchCoOpCapital",
    description: "Nine free upgrades on every unlocked floor",
  },
  hardCarry: {
    label: "Hard Carry",
    color: COLOR.orange,
    icon: "hardCarry",
    description: "Fourteen free upgrades on the highest floor",
  },
  readyCheck: {
    label: "Ready Check",
    color: COLOR.moneyGreen,
    icon: "readyCheck",
    description: "Six free upgrades on every unlocked floor",
  },
  queueRoyalty: {
    label: "Queue Royalty",
    color: COLOR.heavenlyGold,
    icon: "queueRoyalty",
    description: "Twelve instant payouts on this floor",
  },
  rankedAndBanked: {
    label: "Ranked and Banked",
    color: COLOR.gold,
    icon: "rankedAndBanked",
    description: "Eleven free upgrades on this floor",
  },
  victoryPose: {
    label: "Victory Pose",
    color: COLOR.starYellow,
    icon: "victoryPose",
    description: "Eighteen free upgrades on this floor",
  },
  emoteEconomy: {
    label: "Emote Economy",
    color: COLOR.peppermintPink,
    icon: "emoteEconomy",
    description: "Eight payouts on every unlocked floor",
  },
  checkpointChampion: {
    label: "Checkpoint Champion",
    color: COLOR.cyan,
    icon: "checkpointChampion",
    description: "Ten free upgrades on the highest floor",
  },
  fishingForFunds: {
    label: "Fishing for Funds",
    color: COLOR.moneyGreen,
    icon: "fishingForFunds",
    description: "Thirteen instant payouts on this floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
