import type { CritProcDisplayInfo } from "../index";
import { COLOR } from "../../../palette";

export const GEAR_CRIT_INFO = {
  annaNyavarre: {
    label: "Anna Nyavarre",
    color: COLOR.red,
    icon: "annaNyavarre",
    description: "Twenty-three payouts from the highest-earning floor",
  },
  batteryCell: {
    label: "Battery Life",
    color: COLOR.internSkyBlue,
    icon: "batteryCell",
    description: "Sixteen free upgrades on the lowest-level floor",
  },
  blackBlade: {
    label: "Black Blade",
    color: COLOR.royalFlushPurple,
    icon: "blackBlade",
    description: "Thirty-one free upgrades on this floor",
  },
  boneFlute: {
    label: "Bone Solo",
    color: COLOR.springCleaningMint,
    icon: "boneFlute",
    description: "Twenty payouts on alternating floors",
  },
  coldSteel: {
    label: "Cold Steel",
    color: COLOR.pairBlue,
    icon: "coldSteel",
    description: "Thirty-three free upgrades on this floor",
  },
  commando: {
    label: "Commando",
    color: COLOR.dressCodeGreen,
    icon: "commando",
    description: "Twenty-seven free upgrades on this floor",
  },
  corvidCrown: {
    label: "Corvid Crown",
    color: COLOR.shareholdersGreen,
    icon: "corvidCrown",
    description: "Two tier promotions and ten upgrades here",
  },
  daedalynx: {
    label: "Daedalynx",
    color: COLOR.cyan,
    icon: "daedalynx",
    description: "Twenty-four payouts on every unlocked floor",
  },
  dataCube: {
    label: "Read The Emails",
    color: COLOR.threeOfAKindGreen,
    icon: "dataCube",
    description: "Twelve upgrades on this floor and every floor below",
  },
  dropTuned: {
    label: "Drop Tuned",
    color: COLOR.supplyRunTan,
    icon: "dropTuned",
    description: "Thirteen upgrades on alternating floors",
  },
  eternalFlame: {
    label: "Eternal Flame",
    color: COLOR.roundUpOrange,
    icon: "eternalFlame",
    description: "Twenty-eight instant payouts on this floor",
  },
  forgeAhead: {
    label: "Forge Ahead",
    color: COLOR.headhunterRust,
    icon: "forgeAhead",
    description: "Thirty free upgrades on every unlocked floor",
  },
  guntherHairman: {
    label: "Gunther Hairman",
    color: COLOR.unionBossSlate,
    icon: "guntherHairman",
    description: "Twenty-eight free upgrades on this floor",
  },
  heliopaws: {
    label: "Heliopaws",
    color: COLOR.gold,
    icon: "heliopaws",
    description: "Twenty-six free upgrades on every unlocked floor",
  },
  hornsUp: {
    label: "Horns Up",
    color: COLOR.espressoShotBrown,
    icon: "hornsUp",
    description: "Twenty-two upgrades on the highest unlocked floor",
  },
  ironKey: {
    label: "Iron Key",
    color: COLOR.supplyRunTan,
    icon: "ironKey",
    description: "Nineteen free upgrades on the lowest-level floor",
  },
  lastCall: {
    label: "Last Call",
    color: COLOR.bonusRoundGold,
    icon: "lastCall",
    description: "Twenty-nine instant payouts on this floor",
  },
  nanoBlade: {
    label: "Wrist Work",
    color: COLOR.goldenHandshakeGold,
    icon: "nanoBlade",
    description: "Twenty-nine free upgrades on this floor",
  },
  peltCloak: {
    label: "Pelt Cloak",
    color: COLOR.teaBreakBrown,
    icon: "peltCloak",
    description: "Fourteen upgrades on alternating floors",
  },
  pigIron: {
    label: "Pig Iron",
    color: COLOR.unionBossSlate,
    icon: "pigIron",
    description: "Thirty-one free upgrades on every unlocked floor",
  },
  praxisKit: {
    label: "Level Up",
    color: COLOR.goldStandardAmber,
    icon: "praxisKit",
    description: "One tier promotion and fourteen upgrades here",
  },
  quickSilver: {
    label: "Quicksilver",
    color: COLOR.silverTicketGray,
    icon: "quickSilver",
    description: "Twenty-one payouts on alternating floors",
  },
  runicAmulet: {
    label: "Runic Amulet",
    color: COLOR.halloweenSalePurple,
    icon: "runicAmulet",
    description: "Two tier promotions and eleven upgrades here",
  },
  scaledGrip: {
    label: "Scaled Grip",
    color: COLOR.redActive,
    icon: "scaledGrip",
    description: "Thirty-two free upgrades on this floor",
  },
  securityTurret: {
    label: "Friendly Fire",
    color: COLOR.luckyCloverGreen,
    icon: "securityTurret",
    description: "Eighteen payouts on the highest unlocked floor",
  },
  shoulderSpikes: {
    label: "Shoulder Spikes",
    color: COLOR.unionBossSlate,
    icon: "shoulderSpikes",
    description: "Twenty-nine free upgrades on every unlocked floor",
  },
  shredMetal: {
    label: "Shred Metal",
    color: COLOR.orange,
    icon: "shredMetal",
    description: "Twenty-one upgrades on the highest unlocked floor",
  },
  signetOfSkulls: {
    label: "Signet of Skulls",
    color: COLOR.silverTicketGray,
    icon: "signetOfSkulls",
    description: "One tier promotion and fifteen upgrades here",
  },
  stormFork: {
    label: "Storm Fork",
    color: COLOR.fastForwardBlue,
    icon: "stormFork",
    description: "Twenty-five payouts on every unlocked floor",
  },
  studdedBelt: {
    label: "Studded Belt",
    color: COLOR.nightOwlIndigo,
    icon: "studdedBelt",
    description: "Eighteen free upgrades on the lowest-level floor",
  },
  swashbuckler: {
    label: "Swashbuckler",
    color: COLOR.autumnSaleAmber,
    icon: "swashbuckler",
    description: "Nineteen payouts on alternating floors",
  },
  tempered: {
    label: "Tempered",
    color: COLOR.silverTicketGray,
    icon: "tempered",
    description: "Twenty-five upgrades on the highest unlocked floor",
  },
  theCure: {
    label: "The Cure",
    color: COLOR.pairBlue,
    icon: "theCure",
    description: "Twenty-seven instant payouts on this floor",
  },
  titaniumGrip: {
    label: "Titanium Grip",
    color: COLOR.fancyFridayIndigo,
    icon: "titaniumGrip",
    description: "Twenty-four payouts from the highest-earning floor",
  },
  wardingSigil: {
    label: "Warding Sigil",
    color: COLOR.fullHouseCrimson,
    icon: "wardingSigil",
    description: "Thirteen upgrades on this floor and every floor below",
  },
  potionCommotion: {
    label: "Potion Commotion",
    color: COLOR.teal,
    icon: "potionCommotion",
    description: "Thirty payouts on this floor",
  },
  lifelineLoot: {
    label: "Lifeline Loot",
    color: COLOR.red,
    icon: "lifelineLoot",
    description: "Twenty-two free upgrades on this floor",
  },
  moonCloak: {
    label: "Moon Cloak",
    color: COLOR.nightShiftIndigo,
    icon: "moonCloak",
    description: "Twenty upgrades on this floor and every floor below",
  },
  platinumRing: {
    label: "Platinum Ring",
    color: COLOR.silverTicketGray,
    icon: "platinumRing",
    description: "Thirty-two free upgrades on this floor",
  },
  sapphireOrbit: {
    label: "Sapphire Orbit",
    color: COLOR.silverTicketGray,
    icon: "sapphireOrbit",
    description: "One tier promotion and twenty upgrades here",
  },
  stormBoots: {
    label: "Storm Boots",
    color: COLOR.blue,
    icon: "stormBoots",
    description: "Eighteen upgrades on alternating floors",
  },
  thornmailGlove: {
    label: "Thornmail Glove",
    color: COLOR.dressCodeGreen,
    icon: "thornmailGlove",
    description: "One tier promotion and nineteen upgrades here",
  },
  catnipSatchel: {
    label: "Catnip Satchel",
    color: COLOR.moneyGreen,
    icon: "catnipSatchel",
    description: "Twenty-nine payouts from the highest-earning floor",
  },
  silverLaurel: {
    label: "Silver Laurel",
    color: COLOR.silverTicketGray,
    icon: "silverLaurel",
    description: "Twenty-nine payouts from the highest unlocked floor",
  },
  potion: {
    label: "Vial of Ventures",
    color: COLOR.cyan,
    icon: "potion",
    description: "Twenty-four free upgrades on every other floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
