import type { CritProcDisplayInfo } from "../index";
import { COLOR } from "../../../palette";

export const MYTHIC_CREATURES_CRIT_INFO = {
  golem: {
    label: "Golem",
    color: COLOR.unionBossSlate,
    icon: "golem",
    description: "Thirty-five free upgrades on the highest floor",
  },
  emberwingDragon: {
    label: "Emberwing Dragon",
    color: COLOR.red,
    icon: "emberwingDragon",
    description: "Eighteen free upgrades on this floor",
  },
  moonlitKirin: {
    label: "Moonlit Kirin",
    color: COLOR.silverTicketGray,
    icon: "moonlitKirin",
    description: "Ten payouts from the highest-earning floor",
  },
  pocketPhoenix: {
    label: "Pocket Phoenix",
    color: COLOR.sunshineGold,
    icon: "pocketPhoenix",
    description: "Seven free upgrades on this floor",
  },
  crystalGriffin: {
    label: "Crystal Griffin",
    color: COLOR.blue,
    icon: "crystalGriffin",
    description: "Eight payouts on every unlocked floor",
  },
  velvetManticore: {
    label: "Velvet Manticore",
    color: COLOR.halloweenSalePurple,
    icon: "velvetManticore",
    description: "One tier promotion and nine upgrades here",
  },
  frostfangYeti: {
    label: "Frostfang Yeti",
    color: COLOR.frozenIceBlue,
    icon: "frostfangYeti",
    description: "Eleven free upgrades on every unlocked floor",
  },
  lanternKitsune: {
    label: "Lantern Kitsune",
    color: COLOR.orange,
    icon: "lanternKitsune",
    description: "Six instant payouts on this floor",
  },
  coralSeaSerpent: {
    label: "Coral Sea Serpent",
    color: COLOR.cyan,
    icon: "coralSeaSerpent",
    description: "Twelve payouts on this floor",
  },
  clockworkMinotaur: {
    label: "Clockwork Minotaur",
    color: COLOR.gold,
    icon: "clockworkMinotaur",
    description: "Thirteen free upgrades on this floor",
  },
  starryCerberus: {
    label: "Starry Cerberus",
    color: COLOR.nightShiftIndigo,
    icon: "starryCerberus",
    description: "Eight free upgrades on alternating floors, from the ground",
  },
  goldenSphinx: {
    label: "Golden Sphinx",
    color: COLOR.heavenlyGold,
    icon: "goldenSphinx",
    description: "Ten free upgrades on the highest floor",
  },
  mossbackTreant: {
    label: "Mossback Treant",
    color: COLOR.moneyGreen,
    icon: "mossbackTreant",
    description: "Five free upgrades on every unlocked floor",
  },
  rainbowAlicorn: {
    label: "Rainbow Alicorn",
    color: COLOR.peppermintPink,
    icon: "rainbowAlicorn",
    description: "Nine payouts from the highest-earning floor",
  },
  bogWitchFamiliar: {
    label: "Bog Witch Familiar",
    color: COLOR.dressCodeGreen,
    icon: "bogWitchFamiliar",
    description: "Six free upgrades on this floor",
  },
  pearlHippocampus: {
    label: "Pearl Hippocampus",
    color: COLOR.silverTicketGray,
    icon: "pearlHippocampus",
    description: "Seven instant payouts on this floor",
  },
  thunderbirdChick: {
    label: "Thunderbird Chick",
    color: COLOR.blue,
    icon: "thunderbirdChick",
    description: "Nine free upgrades on this floor",
  },
  obsidianBasilisk: {
    label: "Obsidian Basilisk",
    color: COLOR.fullHouseCrimson,
    icon: "obsidianBasilisk",
    description: "Twenty free upgrades on this floor",
  },
  cloudNymph: {
    label: "Cloud Nymph",
    color: COLOR.winterSaleIceBlue,
    icon: "cloudNymph",
    description: "Five payouts on every unlocked floor",
  },
  glassWyvern: {
    label: "Glass Wyvern",
    color: COLOR.cyan,
    icon: "glassWyvern",
    description: "Thirty payouts from the highest-earning floor",
  },
  mossbackManticore: {
    label: "Mossback Manticore",
    color: COLOR.dressCodeGreen,
    icon: "mossbackManticore",
    description: "Thirty payouts on every unlocked floor",
  },
  emberwingDragon2: {
    label: "Emberwing Dragon Hoard",
    color: COLOR.gold,
    icon: "emberwingDragon2",
    description: "Thirty instant payouts on this floor",
  },
  alicorn: {
    label: "Aurora Alicorn",
    color: COLOR.peppermintPink,
    icon: "alicorn",
    description: "Thirty-six payouts from the highest-earning floor",
  },
  alicorn2: {
    label: "Starfall Alicorn",
    color: COLOR.starYellow,
    icon: "alicorn2",
    description: "Forty-one free upgrades on this floor",
  },
  crystallineDragon: {
    label: "Crystalheart Dragon",
    color: COLOR.cyan,
    icon: "crystallineDragon",
    description: "Forty-seven free upgrades on every unlocked floor",
  },
  dragonWithEgg: {
    label: "Dragon's Nest Egg",
    color: COLOR.gold,
    icon: "dragonWithEgg",
    description: "Two tier promotions and twenty upgrades here",
  },
  griffin: {
    label: "Skyvault Griffin",
    color: COLOR.blue,
    icon: "griffin",
    description: "Forty payouts on every unlocked floor",
  },
  hippocampus: {
    label: "Pearlwater Hippocampus",
    color: COLOR.silverTicketGray,
    icon: "hippocampus",
    description: "Thirty-eight instant payouts on this floor",
  },
  hydra: {
    label: "Hydra Headcount",
    color: COLOR.red,
    icon: "hydra",
    description: "Forty-four free upgrades on alternating floors",
  },
  kirin: {
    label: "Cloudbell Kirin",
    color: COLOR.moneyGreen,
    icon: "kirin",
    description: "Thirty-seven upgrades on the lowest-level floor",
  },
  kitsune: {
    label: "Nine-Tail Fortune",
    color: COLOR.orange,
    icon: "kitsune",
    description: "Forty-two instant payouts on this floor",
  },
  manticore: {
    label: "Sunmane Manticore",
    color: COLOR.sunshineGold,
    icon: "manticore",
    description: "Forty-three free upgrades on this floor",
  },
  manticore2: {
    label: "Stormtail Manticore",
    color: COLOR.blue,
    icon: "manticore2",
    description: "Thirty-nine payouts on every unlocked floor",
  },
  manticore3: {
    label: "Goldclaw Manticore",
    color: COLOR.heavenlyGold,
    icon: "manticore3",
    description: "Forty-six upgrades on the highest unlocked floor",
  },
  pegasus: {
    label: "Cloudrunner Pegasus",
    color: COLOR.cyan,
    icon: "pegasus",
    description: "Thirty-five free upgrades on alternating floors",
  },
  phoneix: {
    label: "Ember Rebirth",
    color: COLOR.redActive,
    icon: "phoneix",
    description: "Forty-one instant payouts on every unlocked floor",
  },
  puppyPosey: {
    label: "Posey's Mythic Paws",
    color: COLOR.peppermintPink,
    icon: "puppyPosey",
    description: "Forty-eight free upgrades on this floor",
  },
  salamander: {
    label: "Ember Salamander",
    color: COLOR.orange,
    icon: "salamander",
    description: "Thirty-four payouts on this floor",
  },
  salamander2: {
    label: "Cinder Salamander",
    color: COLOR.red,
    icon: "salamander2",
    description: "Forty-two free upgrades on every unlocked floor",
  },
  salamander3: {
    label: "Molten Salamander",
    color: COLOR.gold,
    icon: "salamander3",
    description: "Forty-five payouts from the highest-earning floor",
  },
  seaSerpet: {
    label: "Abyssal Sea Serpent",
    color: COLOR.blue,
    icon: "seaSerpet",
    description: "Thirty-eight free upgrades on this floor",
  },
  thunderbird: {
    label: "Thunderbird's Roar",
    color: COLOR.starYellow,
    icon: "thunderbird",
    description: "Forty-four payouts on every unlocked floor",
  },
  treant: {
    label: "Rootbound Treant",
    color: COLOR.moneyGreen,
    icon: "treant",
    description: "Forty upgrades on every unlocked floor",
  },
  unicorn: {
    label: "Starlit Unicorn",
    color: COLOR.peppermintPink,
    icon: "unicorn",
    description: "Thirty-six payouts on this floor",
  },
  velvetManticore2: {
    label: "Velvet Manticore's Charm",
    color: COLOR.halloweenSalePurple,
    icon: "velvetManticore2",
    description: "Two tier promotions and twenty-two upgrades here",
  },
  velvetManticore3: {
    label: "Velvet Manticore's Fortune",
    color: COLOR.purple,
    icon: "velvetManticore3",
    description: "Forty-nine free upgrades on this floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
