import type { CritProcDisplayInfo } from "../index";
import { COLOR } from "../../../palette";

export const RICHES_CRIT_INFO = {
  adamWhiskersen: {
    label: "Adam Whiskersen",
    color: COLOR.goldStandardAmber,
    icon: "adamWhiskersen",
    description: "Two tier promotions and eight upgrades here",
  },
  bankroll: {
    label: "Bankroll",
    color: COLOR.paydayEmerald,
    icon: "bankroll",
    description: "Twenty-five free upgrades on this floor",
  },
  billBlizzard: {
    label: "Bill Blizzard",
    color: COLOR.shareholdersGreen,
    icon: "billBlizzard",
    description: "Twenty-three payouts on every unlocked floor",
  },
  bobPawge: {
    label: "Bob Pawge",
    color: COLOR.nightShiftIndigo,
    icon: "bobPawge",
    description: "Twenty-four free upgrades on every unlocked floor",
  },
  bullionStack: {
    label: "Bullion Brigade",
    color: COLOR.gold,
    icon: "bullionStack",
    description: "Twenty-four free upgrades on this floor",
  },
  cashCannon: {
    label: "Cash Cannon",
    color: COLOR.bonusRoundGold,
    icon: "cashCannon",
    description: "Ten upgrades on alternating floors",
  },
  fairExchange: {
    label: "Fair Exchange",
    color: COLOR.mergerGold,
    icon: "fairExchange",
    description: "Eighteen payouts on alternating floors",
  },
  gemMine: {
    label: "Gem Mine",
    color: COLOR.pairBlue,
    icon: "gemMine",
    description: "Ten upgrades on this floor and every floor below",
  },
  goldMine: {
    label: "Gold Mine",
    color: COLOR.supplyRunTan,
    icon: "goldMine",
    description: "Fifteen payouts on the highest unlocked floor",
  },
  goldenChalice: {
    label: "Golden Chalice",
    color: COLOR.sunshineGold,
    icon: "goldenChalice",
    description: "Two tier promotions and seven upgrades here",
  },
  goldenGoose: {
    label: "Golden Goose",
    color: COLOR.goldenTicketYellow,
    icon: "goldenGoose",
    description: "Twenty-one payouts on every unlocked floor",
  },
  goldenStag: {
    label: "Golden Stag",
    color: COLOR.heavenlyGold,
    icon: "goldenStag",
    description: "Twenty-two payouts from the highest-earning floor",
  },
  handsomeJake: {
    label: "Handsome Jake",
    color: COLOR.orange,
    icon: "handsomeJake",
    description: "Eighteen upgrades on the highest unlocked floor",
  },
  jcDentclaw: {
    label: "JC Dentclaw",
    color: COLOR.nightOwlIndigo,
    icon: "jcDentclaw",
    description: "Twenty-six free upgrades on this floor",
  },
  liquidAssets: {
    label: "Liquid Assets",
    color: COLOR.goldenHandshakeGold,
    icon: "liquidAssets",
    description: "Twenty-one payouts from the highest-earning floor",
  },
  midasTouch: {
    label: "Midas Touch",
    color: COLOR.goldStandardAmber,
    icon: "midasTouch",
    description: "One tier promotion and thirteen upgrades here",
  },
  moneyPrinter: {
    label: "Money Printer",
    color: COLOR.bullMarketGreen,
    icon: "moneyPrinter",
    description: "Twenty-three free upgrades on every unlocked floor",
  },
  moneyTree: {
    label: "Money Tree",
    color: COLOR.moneyGreen,
    icon: "moneyTree",
    description: "Twenty-two payouts on every unlocked floor",
  },
  nuggetAvalanche: {
    label: "Nugget Avalanche",
    color: COLOR.amber,
    icon: "nuggetAvalanche",
    description: "Seventeen instant payouts on this floor",
  },
  pennyJar: {
    label: "Penny Jar",
    color: COLOR.headhunterRust,
    icon: "pennyJar",
    description: "Fifteen free upgrades on the lowest-level floor",
  },
  purrDenton: {
    label: "Purr Denton",
    color: COLOR.fastForwardBlue,
    icon: "purrDenton",
    description: "Seventeen free upgrades on the lowest-level floor",
  },
  strikeItRich: {
    label: "Strike It Rich",
    color: COLOR.goldenParachuteMarigold,
    icon: "strikeItRich",
    description: "Sixteen upgrades on the highest unlocked floor",
  },
  vaultDoor: {
    label: "Vault Door",
    color: COLOR.unionBossSlate,
    icon: "vaultDoor",
    description: "Twenty-two free upgrades on every unlocked floor",
  },
  wishingWell: {
    label: "Wishing Well",
    color: COLOR.rainCheckBlue,
    icon: "wishingWell",
    description: "Twenty-three instant payouts on this floor",
  },
  youKnowWhatStallion: {
    label: "You Know What, Stallion",
    color: COLOR.royalFlushPurple,
    icon: "youKnowWhatStallion",
    description: "Eleven upgrades on alternating floors",
  },
  goldBar: {
    label: "Gold Bar",
    color: COLOR.gold,
    icon: "goldBar",
    description: "Thirty-one payouts on every unlocked floor",
  },
  silverCoin: {
    label: "Silver Coin",
    color: COLOR.silverTicketGray,
    icon: "silverCoin",
    description: "Twenty-five payouts on alternating floors",
  },
  gildedCache: {
    label: "Gilded Cache",
    color: COLOR.gold,
    icon: "gildedCache",
    description: "Thirty-five free upgrades on every unlocked floor",
  },
  brassBanker: {
    label: "Brass Banker",
    color: COLOR.gold,
    icon: "brassBanker",
    description: "Thirty-four free upgrades on the lowest-level floor",
  },
  citrusCoin: {
    label: "Citrus Coin",
    color: COLOR.sunshineGold,
    icon: "citrusCoin",
    description: "Thirty-three payouts on alternating floors",
  },
  coinCascade: {
    label: "Coin Cascade",
    color: COLOR.gold,
    icon: "coinCascade",
    description: "Thirty-eight payouts on every unlocked floor",
  },
  coinrootGrove: {
    label: "Coinroot Grove",
    color: COLOR.moneyGreen,
    icon: "coinrootGrove",
    description: "Twenty free upgrades on every unlocked floor",
  },
  allowance: {
    label: "Allowance",
    color: COLOR.moneyGreen,
    icon: "allowance",
    description: "Thirty payouts on the lowest-level floor",
  },
  allowance2: {
    label: "Rainy Day Fund",
    color: COLOR.paydayEmerald,
    icon: "allowance2",
    description: "Thirty-two free upgrades on every unlocked floor",
  },
  lootBags: {
    label: "Bagged and Tagged",
    color: COLOR.payoutOlive,
    icon: "lootBags",
    description: "Thirty-eight upgrades on the highest unlocked floor",
  },
  pocketMoney2: {
    label: "Petty Cash",
    color: COLOR.bullMarketGreen,
    icon: "pocketMoney2",
    description: "Thirty-seven instant payouts on every unlocked floor",
  },
  liquidAssets2: {
    label: "Fluid Capital",
    color: COLOR.espressoShotBrown,
    icon: "liquidAssets2",
    description: "Forty-four payouts from the highest-earning floor",
  },
  pocketMoney: {
    label: "Pocket Money",
    color: COLOR.coinGold,
    icon: "pocketMoney",
    description: "One tier promotion and fifteen upgrades here",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
