import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const CANDY_CRITS = {
  chocolateFountainOfYouth: {
    label: "Chocolate Fountain of Youth",
    color: COLOR.autumnSaleAmber,
    image: "crits/candy/chocolateFountainOfYouth.webp",
    description: "Twenty instant payouts on this floor",
  },
  gummyBearMarket: {
    label: "Gummy Bear Market",
    color: COLOR.red,
    image: "crits/candy/gummyBearMarket.webp",
    description: "Ten free upgrades on every unlocked floor",
  },
  jawbreaker: {
    label: "Jawbreaker",
    color: COLOR.purple,
    image: "crits/candy/jawbreaker.webp",
    description:
      "Raises the lowest-level floor to half the building's top level",
  },
  licoriceLaces: {
    label: "Licorice Laces",
    color: COLOR.fullHouseCrimson,
    image: "crits/candy/licoriceLaces.webp",
    description: "Cuts every price in this building by 1.2%",
  },
  lollipopGuild: {
    label: "Lollipop Guild",
    color: COLOR.peppermintPink,
    image: "crits/candy/lollipopGuild.webp",
    description: "Free office chairs for this floor",
  },
  marshmallowMountain: {
    label: "Marshmallow Mountain",
    color: COLOR.white,
    image: "crits/candy/marshmallowMountain.webp",
    description: "Boosts this floor's workers for 22s",
  },
  sugarHigh: {
    label: "Sugar High",
    color: COLOR.starYellow,
    image: "crits/candy/sugarHigh.webp",
    description: "Boosts this floor's workers for 24s",
  },
  bubblegumBalloon: {
    label: "Bubblegum Balloon",
    color: COLOR.springSalePink,
    image: "crits/candy/bubblegumBalloon.webp",
    description:
      "Repeats the crit on the floor above, 11% chance to keep climbing",
  },
  candyCaneClimber: {
    label: "Candy Cane Climber",
    color: COLOR.red,
    image: "crits/candy/candyCaneClimber.webp",
    description: "Unlocks the next floor for free",
  },
  sherbetSherpa: {
    label: "Sherbet Sherpa",
    color: COLOR.easterSalePink,
    image: "crits/candy/sherbetSherpa.webp",
    description: "Eight instant payouts on every unlocked floor",
  },
  toffeeTrap: {
    label: "Toffee Trap",
    color: COLOR.autumnSaleAmber,
    image: "crits/candy/toffeeTrap.webp",
    description: "Seven free upgrades on this floor",
  },
  cottonCandyCloud: {
    label: "Cotton Candy Cloud",
    color: COLOR.peppermintPink,
    image: "crits/candy/cottonCandyCloud.webp",
    description: "Eleven instant payouts on this floor",
  },
  fudgeIt: {
    label: "Fudge It",
    color: COLOR.autumnSaleAmber,
    image: "crits/candy/fudgeIt.webp",
    description: "Arms this floor's next click as an x5 crit",
  },
  gobstopperGetaway: {
    label: "Gobstopper Getaway",
    color: COLOR.orange,
    image: "crits/candy/gobstopperGetaway.webp",
    description: "Thirteen free upgrades on the highest floor",
  },
  jellyBeanJamboree: {
    label: "Jelly Bean Jamboree",
    color: COLOR.springSalePink,
    image: "crits/candy/jellyBeanJamboree.webp",
    description: "Ten payouts on alternating floors, from the ground",
  },
  rockCandyQuarry: {
    label: "Rock Candy Quarry",
    color: COLOR.cyan,
    image: "crits/candy/rockCandyQuarry.webp",
    description: "One tier promotion and seven upgrades here",
  },
  sprinkleStorm: {
    label: "Sprinkle Storm",
    color: COLOR.blue,
    image: "crits/candy/sprinkleStorm.webp",
    description:
      "Repeats the crit on the floor below, 12% chance to keep falling",
  },
  candyCastle: {
    label: "Candy Castle",
    color: COLOR.peppermintPink,
    image: "crits/candy/candyCastle.webp",
    description: "Arms this floor's next click as an x25 crit",
  },
  caramelApple: {
    label: "Caramel Apple",
    color: COLOR.autumnSaleAmber,
    image: "crits/candy/caramelApple.webp",
    description: "Arms the highest floor's next click as an x5 crit",
  },
  moonlitMint: {
    label: "Moonlit Mint",
    color: COLOR.moneyGreen,
    image: "crits/candy/moonlitMint.webp",
    description: "Hires 2 free workers on this floor",
  },
  gumdropGazillionaire: {
    label: "Gumdrop Gazillionaire",
    color: COLOR.bonusRoundGold,
    image: "crits/candy/gumdropGazillionaire.webp",
    description: "Cuts every price in this building by 16.2%",
  },
  candyCornCornucopia: {
    label: "Candy Corn Cornucopia",
    color: COLOR.autumnSaleAmber,
    image: "crits/candy/candyCornCornucopia.webp",
    description: "Forty-one payouts on every unlocked floor",
  },
  butterscotchBuyout: {
    label: "Butterscotch Buyout",
    color: COLOR.goldStandardAmber,
    image: "crits/candy/butterscotchBuyout.webp",
    description: "Cuts every price in this building by 4.5%",
  },
  sourStrawSprint: {
    label: "Sour Straw Sprint",
    color: COLOR.fastForwardBlue,
    image: "crits/candy/sourStrawSprint.webp",
    description: "Boosts every worker for 33s",
  },
  pralinePremium: {
    label: "Praline Premium",
    color: COLOR.amberMuted,
    image: "crits/candy/pralinePremium.webp",
    description: "One tier promotion and twenty-eight upgrades here",
  },
  fizzyFortune: {
    label: "Fizzy Fortune",
    color: COLOR.cyan,
    image: "crits/candy/fizzyFortune.webp",
    description: "Adds 43.3% of your total income",
  },
  marzipanMogul: {
    label: "Marzipan Mogul",
    color: COLOR.peppermintPink,
    image: "crits/candy/marzipanMogul.webp",
    description: "Adds 150s of your company's income",
  },
  gummyWormWealth: {
    label: "Gummy Worm Wealth",
    color: COLOR.bullMarketGreen,
    image: "crits/candy/gummyWormWealth.webp",
    description: "Adds 75s of your company's income",
  },
  chocolateCoinCartel: {
    label: "Chocolate Coin Cartel",
    color: COLOR.coinGold,
    image: "crits/candy/chocolateCoinCartel.webp",
    description: "Adds 35% of your total income",
  },
  honeycombHustle: {
    label: "Honeycomb Hustle",
    color: COLOR.amber,
    image: "crits/candy/honeycombHustle.webp",
    description: "Boosts every worker for 33s",
  },
  candyComet: {
    label: "Candy Comet",
    color: COLOR.peppermintPink,
    image: "crits/candy/candyComet.webp",
    description: "Fifty-seven upgrades rolling down the floors below",
  },
  taffyTornado: {
    label: "Taffy Tornado",
    color: COLOR.amber,
    image: "crits/candy/taffyTornado.webp",
    description: "Repeats the crit above and below, 61% chance to keep spreading",
  },
  candyGrudge: {
    label: "Candy Grudge",
    color: COLOR.roundUpOrange,
    image: "crits/candy/candyGrudge.webp",
    description: "Cuts every price in this building by 2%",
  },
  caramelCascade: {
    label: "Caramel Cascade",
    color: COLOR.summerSaleOrange,
    image: "crits/candy/caramelCascade.webp",
    description: "Repeats the crit on the floor below, 10% chance to keep falling",
  },
  chocolateComet: {
    label: "Chocolate Comet",
    color: COLOR.chairGiveawayBrown,
    image: "crits/candy/chocolateComet.webp",
    description: "Boosts every worker for 20s",
  },
  mintyFreshStart: {
    label: "Minty Fresh Start",
    color: COLOR.fastForwardBlue,
    image: "crits/candy/mintyFreshStart.webp",
    description: "One tier promotion and nine upgrades here",
  },
  nougatNap: {
    label: "Nougat Nap",
    color: COLOR.fullHouseCrimson,
    image: "crits/candy/nougatNap.webp",
    description: "Adds 41s of your company's income",
  },
  sourPower: {
    label: "Sour Power",
    color: COLOR.sunshineGold,
    image: "crits/candy/sourPower.webp",
    description: "Cuts every price in this building by 1%",
  },
  truffleShuffle: {
    label: "Truffle Shuffle",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/candy/truffleShuffle.webp",
    description: "Raises every floor below this one to its level",
  },
  chocBlockJumble: {
    label: "Choc Block Jumble",
    color: COLOR.fullHouseCrimson,
    image: "crits/candy/chocBlockJumble.webp",
    description: "Spreads 162 free upgrades over the lowest-level floors",
  },
  pinwheelPile: {
    label: "Pinwheel Pile",
    color: COLOR.fullHouseCrimson,
    image: "crits/candy/pinwheelPile.webp",
    description: "Grows this floor's level by 19.5% in free upgrades",
  },
  twistWrapTumble: {
    label: "Twist Wrap Tumble",
    color: COLOR.fullHouseCrimson,
    image: "crits/candy/twistWrapTumble.webp",
    description: "Spreads 163 free upgrades over the lowest-level floors",
  },
} as const satisfies Record<string, FeaturedCritData>;
