import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const DUO_GROUP_SCENES_CRITS = {
  ballroomSnapshot: {
    label: "Ballroom Snapshot",
    color: COLOR.doubleDownCrimson,
    image: "crits/duoGroupScenes/ballroomSnapshot.webp",
    description: "Adds 157s of your company's income",
  },
  blackTieBall: {
    label: "Black Tie Ball",
    color: COLOR.nightShiftIndigo,
    image: "crits/duoGroupScenes/blackTieBall.webp",
    description: "Adds 160s of your company's income",
  },
  cocktailHour: {
    label: "Cocktail Hour",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/cocktailHour.webp",
    description: "Adds 165s of your company's income",
  },
  discoDiva: {
    label: "Disco Diva",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/discoDiva.webp",
    description: "Adds 167s of your company's income",
  },
  photoBooth: {
    label: "Photo Booth",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/photoBooth.webp",
    description: "Adds 61.2% of your total income",
  },
  promenade: {
    label: "Promenade",
    color: COLOR.nightShiftIndigo,
    image: "crits/duoGroupScenes/promenade.webp",
    description: "Adds 61.7% of your total income",
  },
  purpleReign: {
    label: "Purple Reign",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/purpleReign.webp",
    description: "Adds 61.9% of your total income",
  },
  blueSteelRedHot: {
    label: "Blue Steel Red Hot",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/blueSteelRedHot.webp",
    description: "Adds 161s of your company's income",
  },
  fuchsiaFortress: {
    label: "Fuchsia Fortress",
    color: COLOR.fullHouseCrimson,
    image: "crits/duoGroupScenes/fuchsiaFortress.webp",
    description: "Adds 60.1% of your total income",
  },
  jadeGiantess: {
    label: "Jade Giantess",
    color: COLOR.dressCodeGreen,
    image: "crits/duoGroupScenes/jadeGiantess.webp",
    description: "Adds 60.5% of your total income",
  },
  mermaidTail: {
    label: "Mermaid Tail",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/mermaidTail.webp",
    description: "Adds 60.9% of your total income",
  },
  navyShimmer: {
    label: "Navy Shimmer",
    color: COLOR.nightOwlIndigo,
    image: "crits/duoGroupScenes/navyShimmer.webp",
    description: "Adds 61% of your total income",
  },
  offTheShoulder: {
    label: "Off The Shoulder",
    color: COLOR.nightShiftIndigo,
    image: "crits/duoGroupScenes/offTheShoulder.webp",
    description: "Adds 61.1% of your total income",
  },
  bodiceBulk: {
    label: "Bodice Bulk",
    color: COLOR.nightOwlIndigo,
    image: "crits/duoGroupScenes/bodiceBulk.webp",
    description: "Adds 162s of your company's income",
  },
  pixieCuts: {
    label: "Pixie Cuts",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/pixieCuts.webp",
    description: "Adds 61.3% of your total income",
  },
  ponytailPride: {
    label: "Ponytail Pride",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/ponytailPride.webp",
    description: "Adds 61.4% of your total income",
  },
  sunnyCurls: {
    label: "Sunny Curls",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/sunnyCurls.webp",
    description: "Adds 62.5% of your total income",
  },
  candyHairCrew: {
    label: "Candy Hair Crew",
    color: COLOR.teal,
    image: "crits/duoGroupScenes/candyHairCrew.webp",
    description: "Promotes 40.5% of this floor's workers two perma tiers",
  },
  bobSquad: {
    label: "Bob Squad",
    color: COLOR.cyan,
    image: "crits/duoGroupScenes/bobSquad.webp",
    description: "Promotes 40% of this floor's workers two perma tiers",
  },
  sweatbandSquad: {
    label: "Sweatband Squad",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/sweatbandSquad.webp",
    description: "Promotes 41.5% of this building's workers one perma tier",
  },
  leotardLineup: {
    label: "Leotard Lineup",
    color: COLOR.fastForwardBlue,
    image: "crits/duoGroupScenes/leotardLineup.webp",
    description: "Promotes 23.5% of this building's workers one perma tier",
  },
  earringGlint: {
    label: "Earring Glint",
    color: COLOR.nightOwlIndigo,
    image: "crits/duoGroupScenes/earringGlint.webp",
    description: "Adds 64% of your total income",
  },
  primAndProper: {
    label: "Prim And Proper",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/primAndProper.webp",
    description: "Promotes 37.5% of this building's workers one perma tier",
  },
  eclipseBuns: {
    label: "Eclipse Buns",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/eclipseBuns.webp",
    description: "Promotes 13% of this building's workers one perma tier",
  },
  bangsAndBlues: {
    label: "Bangs And Blues",
    color: COLOR.nightOwlIndigo,
    image: "crits/duoGroupScenes/bangsAndBlues.webp",
    description: "Adds 158s of your company's income",
  },
  jadeAndNavy: {
    label: "Jade And Navy",
    color: COLOR.nightOwlIndigo,
    image: "crits/duoGroupScenes/jadeAndNavy.webp",
    description: "Adds 64.1% of your total income",
  },
  pinkGloves: {
    label: "Pink Gloves",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/pinkGloves.webp",
    description: "Adds 64.2% of your total income",
  },
  rainbowHem: {
    label: "Rainbow Hem",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/rainbowHem.webp",
    description: "Adds 62% of your total income",
  },
  matchingTrims: {
    label: "Matching Trims",
    color: COLOR.nightOwlIndigo,
    image: "crits/duoGroupScenes/matchingTrims.webp",
    description: "Adds 60.7% of your total income",
  },
  tallAndTiny: {
    label: "Tall And Tiny",
    color: COLOR.overflowBlue,
    image: "crits/duoGroupScenes/tallAndTiny.webp",
    description: "Adds 62.6% of your total income",
  },
  jewelTones: {
    label: "Jewel Tones",
    color: COLOR.doubleDownCrimson,
    image: "crits/duoGroupScenes/jewelTones.webp",
    description: "Adds 60.6% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
