import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const ELEMENTS_CRITS = {
  californiumCrescendo: {
    label: "Californium Crescendo",
    color: COLOR.blue,
    image: "crits/elements/californiumCrescendo.webp",
    description: "98 upgrades here and 98 payouts on the highest floor",
  },
  einsteiniumEpiphany: {
    label: "Einsteinium Epiphany",
    color: COLOR.purple,
    image: "crits/elements/einsteiniumEpiphany.webp",
    description: "99 upgrades here and 99 payouts on the highest floor",
  },
  fermiumFormula: {
    label: "Fermium Formula",
    color: COLOR.cyan,
    image: "crits/elements/fermiumFormula.webp",
    description: "Free office chairs for every unlocked floor",
  },
  mendeleviumMajesty: {
    label: "Mendelevium Majesty",
    color: COLOR.gold,
    image: "crits/elements/mendeleviumMajesty.webp",
    description: "One tier promotion and 17 upgrades here",
  },
  nobeliumLaureate: {
    label: "Nobelium Laureate",
    color: COLOR.starYellow,
    image: "crits/elements/nobeliumLaureate.webp",
    description: "Arms this floor's next click as an x25 crit",
  },
  lawrenciumLightspeed: {
    label: "Lawrencium Lightspeed",
    color: COLOR.moneyGreen,
    image: "crits/elements/lawrenciumLightspeed.webp",
    description: "Boosts every worker for 35s",
  },
  rutherfordiumReach: {
    label: "Rutherfordium Reach",
    color: COLOR.mysticTeal,
    image: "crits/elements/rutherfordiumReach.webp",
    description: "Free office supplies for every unlocked floor",
  },
  seaborgiumSwell: {
    label: "Seaborgium Swell",
    color: COLOR.silverTicketGray,
    image: "crits/elements/seaborgiumSwell.webp",
    description: "Boosts every worker for 46s, counting as 1 extra worker",
  },
  bohriumSummit: {
    label: "Bohrium Summit",
    color: COLOR.red,
    image: "crits/elements/bohriumSummit.webp",
    description: "Unlocks the next 2 floors for free",
  },
  hassiumMeteor: {
    label: "Hassium Meteor",
    color: COLOR.peppermintPink,
    image: "crits/elements/hassiumMeteor.webp",
    description: "Boosts every worker for 47s, counting as 1 extra worker",
  },
  meitneriumMarvel: {
    label: "Meitnerium Marvel",
    color: COLOR.blue,
    image: "crits/elements/meitneriumMarvel.webp",
    description: "Boosts every worker for 47s, counting as 1 extra worker",
  },
  darmstadtiumDowntown: {
    label: "Darmstadtium Downtown",
    color: COLOR.purple,
    image: "crits/elements/darmstadtiumDowntown.webp",
    description: "Cuts every price in this building by 6.1%",
  },
  roentgeniumRevelation: {
    label: "Roentgenium Revelation",
    color: COLOR.cyan,
    image: "crits/elements/roentgeniumRevelation.webp",
    description: "Raises every floor below this one to its level",
  },
  coperniciumCarousel: {
    label: "Copernicium Carousel",
    color: COLOR.gold,
    image: "crits/elements/coperniciumCarousel.webp",
    description: "Raises every floor below this one to its level",
  },
  nihoniumDaybreak: {
    label: "Nihonium Daybreak",
    color: COLOR.starYellow,
    image: "crits/elements/nihoniumDaybreak.webp",
    description: "Cuts every price in this building by 6.3%",
  },
  fleroviumFortress: {
    label: "Flerovium Fortress",
    color: COLOR.moneyGreen,
    image: "crits/elements/fleroviumFortress.webp",
    description: "Raises every floor below this one to its level",
  },
  moscoviumMosaic: {
    label: "Moscovium Mosaic",
    color: COLOR.mysticTeal,
    image: "crits/elements/moscoviumMosaic.webp",
    description: "115 upgrades here and 115 payouts on the highest floor",
  },
  livermoriumLightning: {
    label: "Livermorium Lightning",
    color: COLOR.silverTicketGray,
    image: "crits/elements/livermoriumLightning.webp",
    description: "Boosts every worker for 49s, counting as 1 extra worker",
  },
  tennessineTwinkle: {
    label: "Tennessine Twinkle",
    color: COLOR.red,
    image: "crits/elements/tennessineTwinkle.webp",
    description: "Raises every floor below this one to its level",
  },
  oganessonOdyssey: {
    label: "Oganesson Odyssey",
    color: COLOR.peppermintPink,
    image: "crits/elements/oganessonOdyssey.webp",
    description: "Hires 1 free worker on every unlocked floor",
  },
  osmiumRegalia: {
    label: "Osmium Regalia",
    color: COLOR.silverTicketGray,
    image: "crits/elements/osmiumRegalia.webp",
    description: "One tier promotion and 17 upgrades on the lowest-level floor",
  },
  iridiumAegis: {
    label: "Iridium Aegis",
    color: COLOR.cyan,
    image: "crits/elements/iridiumAegis.webp",
    description: "Cuts every price in this building by 4%",
  },
  mercuryFlow: {
    label: "Mercury Flow",
    color: COLOR.blue,
    image: "crits/elements/mercuryFlow.webp",
    description: "Raises the lowest-level floor to the building's top level",
  },
  thalliumThrive: {
    label: "Thallium Thrive",
    color: COLOR.moneyGreen,
    image: "crits/elements/thalliumThrive.webp",
    description: "81 upgrades here and 81 payouts on the highest floor",
  },
  leadLode: {
    label: "Lead Lode",
    color: COLOR.gold,
    image: "crits/elements/leadLode.webp",
    description: "Cuts every price in this building by 4.1%",
  },
  bismuthBastion: {
    label: "Bismuth Bastion",
    color: COLOR.peppermintPink,
    image: "crits/elements/bismuthBastion.webp",
    description:
      "Repeats the crit on the floor above, 51% chance to keep climbing",
  },
  poloniumPrism: {
    label: "Polonium Prism",
    color: COLOR.red,
    image: "crits/elements/poloniumPrism.webp",
    description: "Hires 1 free worker on alternating floors",
  },
  astatineAurora: {
    label: "Astatine Aurora",
    color: COLOR.mysticTeal,
    image: "crits/elements/astatineAurora.webp",
    description: "Cuts every price in this building by 4.1%",
  },
  radonRipple: {
    label: "Radon Ripple",
    color: COLOR.silverTicketGray,
    image: "crits/elements/radonRipple.webp",
    description:
      "Repeats the crit on the floor below, 51% chance to keep falling",
  },
  franciumFortune: {
    label: "Francium Fortune",
    color: COLOR.cyan,
    image: "crits/elements/franciumFortune.webp",
    description: "Adds 11.9% of your total income",
  },
  radiumRhythm: {
    label: "Radium Rhythm",
    color: COLOR.blue,
    image: "crits/elements/radiumRhythm.webp",
    description: "Unlocks the next floor for free",
  },
  actiniumArc: {
    label: "Actinium Arc",
    color: COLOR.moneyGreen,
    image: "crits/elements/actiniumArc.webp",
    description: "89 upgrades here and 89 payouts on the highest floor",
  },
  thoriumThrone: {
    label: "Thorium Throne",
    color: COLOR.gold,
    image: "crits/elements/thoriumThrone.webp",
    description: "One tier promotion and 16 upgrades here",
  },
  protactiniumOrbit: {
    label: "Protactinium Orbit",
    color: COLOR.peppermintPink,
    image: "crits/elements/protactiniumOrbit.webp",
    description: "Cuts every price in this building by 4.2%",
  },
  neptuniumNova: {
    label: "Neptunium Nova",
    color: COLOR.red,
    image: "crits/elements/neptuniumNova.webp",
    description: "93 upgrades here and 93 payouts on the highest floor",
  },
  americiumAlarm: {
    label: "Americium Alarm",
    color: COLOR.mysticTeal,
    image: "crits/elements/americiumAlarm.webp",
    description: "95 upgrades here and 95 payouts on the highest floor",
  },
  plutoniumPulse: {
    label: "Plutonium Pulse",
    color: COLOR.orange,
    image: "crits/elements/plutoniumPulse.webp",
    description:
      "Repeats the crit on the floor above, 54% chance to keep climbing",
  },
  curiumCrucible: {
    label: "Curium Crucible",
    color: COLOR.silverTicketGray,
    image: "crits/elements/curiumCrucible.webp",
    description: "96 upgrades here and 96 payouts on the highest floor",
  },
  berkeliumBreakthrough: {
    label: "Berkelium Breakthrough",
    color: COLOR.cyan,
    image: "crits/elements/berkeliumBreakthrough.webp",
    description: "Cuts every price in this building by 4.4%",
  },
  hydrogenHype: {
    label: "Hydrogen Hype",
    color: COLOR.blue,
    image: "crits/elements/hydrogenHype.webp",
    description: "Boosts this floor's workers for 20s",
  },
  heliumHighrise: {
    label: "Helium Highrise",
    color: COLOR.cyan,
    image: "crits/elements/heliumHighrise.webp",
    description: "2 upgrades here and 2 payouts on the highest floor",
  },
  lithiumLift: {
    label: "Lithium Lift",
    color: COLOR.moneyGreen,
    image: "crits/elements/lithiumLift.webp",
    description: "Unlocks the next floor for free",
  },
  berylliumBrilliance: {
    label: "Beryllium Brilliance",
    color: COLOR.gold,
    image: "crits/elements/berylliumBrilliance.webp",
    description: "4 upgrades here and 4 payouts on the highest floor",
  },
  carbonCrown: {
    label: "Carbon Crown",
    color: COLOR.red,
    image: "crits/elements/carbonCrown.webp",
    description: "One tier promotion and 10 upgrades on the lowest-level floor",
  },
  nitrogenNimbus: {
    label: "Nitrogen Nimbus",
    color: COLOR.peppermintPink,
    image: "crits/elements/nitrogenNimbus.webp",
    description: "Boosts this floor's workers for 20s",
  },
  oxygenOverdrive: {
    label: "Oxygen Overdrive",
    color: COLOR.silverTicketGray,
    image: "crits/elements/oxygenOverdrive.webp",
    description: "Boosts this floor's workers for 20s",
  },
  fluorineFlash: {
    label: "Fluorine Flash",
    color: COLOR.mysticTeal,
    image: "crits/elements/fluorineFlash.webp",
    description: "Hires 1 free worker on this floor",
  },
  sodiumSprinkle: {
    label: "Sodium Sprinkle",
    color: COLOR.blue,
    image: "crits/elements/sodiumSprinkle.webp",
    description:
      "Raises the lowest-level floor to half the building's top level",
  },
  magnesiumMagnificence: {
    label: "Magnesium Magnificence",
    color: COLOR.cyan,
    image: "crits/elements/magnesiumMagnificence.webp",
    description: "Free office chairs for this floor",
  },
  aluminumAllStar: {
    label: "Aluminum All-Star",
    color: COLOR.moneyGreen,
    image: "crits/elements/aluminumAllStar.webp",
    description: "13 upgrades here and 13 payouts on the highest floor",
  },
  siliconSpark: {
    label: "Silicon Spark",
    color: COLOR.gold,
    image: "crits/elements/siliconSpark.webp",
    description: "Boosts this floor's workers for 21s",
  },
  phosphorusFlare: {
    label: "Phosphorus Flare",
    color: COLOR.red,
    image: "crits/elements/phosphorusFlare.webp",
    description:
      "Raises the lowest-level floor to half the building's top level",
  },
  sulfurSunshine: {
    label: "Sulfur Sunshine",
    color: COLOR.peppermintPink,
    image: "crits/elements/sulfurSunshine.webp",
    description: "16 upgrades here and 16 payouts on the highest floor",
  },
  chlorineConfetti: {
    label: "Chlorine Confetti",
    color: COLOR.silverTicketGray,
    image: "crits/elements/chlorineConfetti.webp",
    description: "17 upgrades here and 17 payouts on the highest floor",
  },
  argonAfterglow: {
    label: "Argon Afterglow",
    color: COLOR.mysticTeal,
    image: "crits/elements/argonAfterglow.webp",
    description: "18 upgrades here and 18 payouts on the highest floor",
  },
  potassiumPop: {
    label: "Potassium Pop",
    color: COLOR.blue,
    image: "crits/elements/potassiumPop.webp",
    description: "Free office supplies for this floor",
  },
  calciumCornerstone: {
    label: "Calcium Cornerstone",
    color: COLOR.cyan,
    image: "crits/elements/calciumCornerstone.webp",
    description:
      "Raises the lowest-level floor to half the building's top level",
  },
  scandiumStronghold: {
    label: "Scandium Stronghold",
    color: COLOR.moneyGreen,
    image: "crits/elements/scandiumStronghold.webp",
    description: "Hires 1 free worker on this floor",
  },
  titaniumTakeoff: {
    label: "Titanium Takeoff",
    color: COLOR.gold,
    image: "crits/elements/titaniumTakeoff.webp",
    description:
      "Raises the lowest-level floor to half the building's top level",
  },
  vanadiumVoltage: {
    label: "Vanadium Voltage",
    color: COLOR.red,
    image: "crits/elements/vanadiumVoltage.webp",
    description: "Boosts this floor's workers for 24s",
  },
  chromiumGleam: {
    label: "Chromium Gleam",
    color: COLOR.peppermintPink,
    image: "crits/elements/chromiumGleam.webp",
    description: "Free office chairs for this floor",
  },
  manganeseMomentum: {
    label: "Manganese Momentum",
    color: COLOR.silverTicketGray,
    image: "crits/elements/manganeseMomentum.webp",
    description: "Arms this floor's next click as an x5 crit",
  },
  ironEmpire: {
    label: "Iron Empire",
    color: COLOR.mysticTeal,
    image: "crits/elements/ironEmpire.webp",
    description:
      "Raises the lowest-level floor to half the building's top level",
  },
  cobaltCharge: {
    label: "Cobalt Charge",
    color: COLOR.blue,
    image: "crits/elements/cobaltCharge.webp",
    description: "Boosts this floor's workers for 24s",
  },
  nickelNestEgg: {
    label: "Nickel Nest Egg",
    color: COLOR.cyan,
    image: "crits/elements/nickelNestEgg.webp",
    description:
      "Repeats the crit on the floor above, 16% chance to keep climbing",
  },
  copperCurrent: {
    label: "Copper Current",
    color: COLOR.moneyGreen,
    image: "crits/elements/copperCurrent.webp",
    description: "Free office supplies for this floor",
  },
  zincZing: {
    label: "Zinc Zing",
    color: COLOR.gold,
    image: "crits/elements/zincZing.webp",
    description: "30 upgrades here and 30 payouts on the highest floor",
  },
  galliumGlitter: {
    label: "Gallium Glitter",
    color: COLOR.red,
    image: "crits/elements/galliumGlitter.webp",
    description: "31 upgrades here and 31 payouts on the highest floor",
  },
  germaniumGenius: {
    label: "Germanium Genius",
    color: COLOR.peppermintPink,
    image: "crits/elements/germaniumGenius.webp",
    description: "32 upgrades here and 32 payouts on the highest floor",
  },
  arsenicAlchemy: {
    label: "Arsenic Alchemy",
    color: COLOR.silverTicketGray,
    image: "crits/elements/arsenicAlchemy.webp",
    description: "Cuts every price in this building by 1.5%",
  },
  seleniumSunburst: {
    label: "Selenium Sunburst",
    color: COLOR.mysticTeal,
    image: "crits/elements/seleniumSunburst.webp",
    description: "34 upgrades here and 34 payouts on the highest floor",
  },
  bromineBounty: {
    label: "Bromine Bounty",
    color: COLOR.blue,
    image: "crits/elements/bromineBounty.webp",
    description: "Adds 10s of your company's income",
  },
  kryptonKeepsake: {
    label: "Krypton Keepsake",
    color: COLOR.cyan,
    image: "crits/elements/kryptonKeepsake.webp",
    description: "36 upgrades here and 36 payouts on the highest floor",
  },
  rubidiumRadiance: {
    label: "Rubidium Radiance",
    color: COLOR.moneyGreen,
    image: "crits/elements/rubidiumRadiance.webp",
    description:
      "Raises the lowest-level floor to half the building's top level",
  },
  strontiumSpectacle: {
    label: "Strontium Spectacle",
    color: COLOR.gold,
    image: "crits/elements/strontiumSpectacle.webp",
    description:
      "Repeats the crit on the floor above, 26% chance to keep climbing",
  },
  yttriumYield: {
    label: "Yttrium Yield",
    color: COLOR.red,
    image: "crits/elements/yttriumYield.webp",
    description:
      "Raises the lowest-level floor to half the building's top level",
  },
  zirconiumZenith: {
    label: "Zirconium Zenith",
    color: COLOR.peppermintPink,
    image: "crits/elements/zirconiumZenith.webp",
    description: "Hires a free manager for this floor",
  },
  niobiumNexus: {
    label: "Niobium Nexus",
    color: COLOR.silverTicketGray,
    image: "crits/elements/niobiumNexus.webp",
    description: "Cuts every price in this building by 2.1%",
  },
  molybdenumMachine: {
    label: "Molybdenum Machine",
    color: COLOR.mysticTeal,
    image: "crits/elements/molybdenumMachine.webp",
    description: "42 upgrades here and 42 payouts on the highest floor",
  },
  technetiumTimebank: {
    label: "Technetium Timebank",
    color: COLOR.blue,
    image: "crits/elements/technetiumTimebank.webp",
    description: "Adds 5.2% of your total income",
  },
  rutheniumRiches: {
    label: "Ruthenium Riches",
    color: COLOR.cyan,
    image: "crits/elements/rutheniumRiches.webp",
    description: "Adds 11s of your company's income",
  },
  rhodiumReflection: {
    label: "Rhodium Reflection",
    color: COLOR.moneyGreen,
    image: "crits/elements/rhodiumReflection.webp",
    description: "Free office chairs and supplies for this floor",
  },
  palladiumPilot: {
    label: "Palladium Pilot",
    color: COLOR.gold,
    image: "crits/elements/palladiumPilot.webp",
    description: "Cuts every price in this building by 2.1%",
  },
  silverMoonrise: {
    label: "Silver Moonrise",
    color: COLOR.red,
    image: "crits/elements/silverMoonrise.webp",
    description: "Hires 2 free workers on this floor",
  },
  cadmiumCatalyst: {
    label: "Cadmium Catalyst",
    color: COLOR.peppermintPink,
    image: "crits/elements/cadmiumCatalyst.webp",
    description: "48 upgrades here and 48 payouts on the highest floor",
  },
  indiumInsight: {
    label: "Indium Insight",
    color: COLOR.silverTicketGray,
    image: "crits/elements/indiumInsight.webp",
    description: "49 upgrades here and 49 payouts on the highest floor",
  },
  tinTreasure: {
    label: "Tin Treasure",
    color: COLOR.mysticTeal,
    image: "crits/elements/tinTreasure.webp",
    description: "Adds 5.8% of your total income",
  },
  antimonyAscension: {
    label: "Antimony Ascension",
    color: COLOR.blue,
    image: "crits/elements/antimonyAscension.webp",
    description: "Unlocks the next floor for free",
  },
  telluriumTreasurelight: {
    label: "Tellurium Treasurelight",
    color: COLOR.cyan,
    image: "crits/elements/telluriumTreasurelight.webp",
    description: "Adds 15s of your company's income",
  },
  iodineIridescence: {
    label: "Iodine Iridescence",
    color: COLOR.moneyGreen,
    image: "crits/elements/iodineIridescence.webp",
    description: "Cuts every price in this building by 2.7%",
  },
  xenonSpotlight: {
    label: "Xenon Spotlight",
    color: COLOR.gold,
    image: "crits/elements/xenonSpotlight.webp",
    description: "Hires a free manager for this floor",
  },
  cesiumClockwork: {
    label: "Cesium Clockwork",
    color: COLOR.red,
    image: "crits/elements/cesiumClockwork.webp",
    description: "Cuts every price in this building by 2.8%",
  },
  bariumBeacon: {
    label: "Barium Beacon",
    color: COLOR.peppermintPink,
    image: "crits/elements/bariumBeacon.webp",
    description: "56 upgrades here and 56 payouts on the highest floor",
  },
  lanthanumLuster: {
    label: "Lanthanum Luster",
    color: COLOR.silverTicketGray,
    image: "crits/elements/lanthanumLuster.webp",
    description: "Free office chairs and supplies for this floor",
  },
  ceriumShine: {
    label: "Cerium Shine",
    color: COLOR.mysticTeal,
    image: "crits/elements/ceriumShine.webp",
    description: "Cuts every price in this building by 2.8%",
  },
  praseodymiumPrism: {
    label: "Praseodymium Prism",
    color: COLOR.blue,
    image: "crits/elements/praseodymiumPrism.webp",
    description: "Hires 2 free workers on this floor",
  },
  neodymiumNorthstar: {
    label: "Neodymium Northstar",
    color: COLOR.cyan,
    image: "crits/elements/neodymiumNorthstar.webp",
    description: "Cuts every price in this building by 2.9%",
  },
  promethiumPulse: {
    label: "Promethium Pulse",
    color: COLOR.moneyGreen,
    image: "crits/elements/promethiumPulse.webp",
    description: "Hires a free manager for this floor",
  },
  samariumSanctuary: {
    label: "Samarium Sanctuary",
    color: COLOR.gold,
    image: "crits/elements/samariumSanctuary.webp",
    description: "Free office chairs and supplies for this floor",
  },
  europiumEncore: {
    label: "Europium Encore",
    color: COLOR.red,
    image: "crits/elements/europiumEncore.webp",
    description: "Repeats the crit on the floor below, 52% chance to keep falling",
  },
  gadoliniumGlance: {
    label: "Gadolinium Glance",
    color: COLOR.peppermintPink,
    image: "crits/elements/gadoliniumGlance.webp",
    description: "64 upgrades here and 64 payouts on the highest floor",
  },
  terbiumTempo: {
    label: "Terbium Tempo",
    color: COLOR.silverTicketGray,
    image: "crits/elements/terbiumTempo.webp",
    description: "Hires 2 free workers on this floor",
  },
  dysprosiumDirection: {
    label: "Dysprosium Direction",
    color: COLOR.mysticTeal,
    image: "crits/elements/dysprosiumDirection.webp",
    description: "66 upgrades here and 66 payouts on the highest floor",
  },
  holmiumHalo: {
    label: "Holmium Halo",
    color: COLOR.blue,
    image: "crits/elements/holmiumHalo.webp",
    description: "Hires a free manager for this floor",
  },
  erbiumElegance: {
    label: "Erbium Elegance",
    color: COLOR.cyan,
    image: "crits/elements/erbiumElegance.webp",
    description: "Free office chairs and supplies for this floor",
  },
  thuliumThaw: {
    label: "Thulium Thaw",
    color: COLOR.moneyGreen,
    image: "crits/elements/thuliumThaw.webp",
    description: "Hires 2 free workers on this floor",
  },
  ytterbiumHourglass: {
    label: "Ytterbium Hourglass",
    color: COLOR.gold,
    image: "crits/elements/ytterbiumHourglass.webp",
    description: "Hires a free manager for this floor",
  },
  lutetiumLimelight: {
    label: "Lutetium Limelight",
    color: COLOR.red,
    image: "crits/elements/lutetiumLimelight.webp",
    description: "Free office chairs and supplies for this floor",
  },
  hafniumHorizon: {
    label: "Hafnium Horizon",
    color: COLOR.peppermintPink,
    image: "crits/elements/hafniumHorizon.webp",
    description: "Hires 2 free workers on this floor",
  },
  tantalumTrove: {
    label: "Tantalum Trove",
    color: COLOR.silverTicketGray,
    image: "crits/elements/tantalumTrove.webp",
    description: "Free office chairs for every unlocked floor",
  },
  tungstenTriumph: {
    label: "Tungsten Triumph",
    color: COLOR.mysticTeal,
    image: "crits/elements/tungstenTriumph.webp",
    description: "74 upgrades here and 74 payouts on the highest floor",
  },
  rheniumRocket: {
    label: "Rhenium Rocket",
    color: COLOR.blue,
    image: "crits/elements/rheniumRocket.webp",
    description: "Unlocks the next floor for free",
  },
  platinumPodium: {
    label: "Platinum Podium",
    color: COLOR.cyan,
    image: "crits/elements/platinumPodium.webp",
    description: "Free office supplies for every unlocked floor",
  },
  goldenAtom: {
    label: "Gold Atom",
    color: COLOR.moneyGreen,
    image: "crits/elements/goldenAtom.webp",
    description: "Adds 23s of your company's income",
  },
  uraniumUplift: {
    label: "Uranium Uplift",
    color: COLOR.gold,
    image: "crits/elements/uraniumUplift.webp",
    description: "Unlocks the next floor for free",
  },
  heavyElement: {
    label: "Heavy Element",
    color: COLOR.silverTicketGray,
    image: "crits/elements/heavyElement.webp",
    description: "Hires 1 free worker on this floor",
  },
  nucleusDividend: {
    label: "Nucleus Dividend",
    color: COLOR.cyan,
    image: "crits/elements/nucleusDividend.webp",
    description: "Adds 7s of your company's income",
  },
  quicksilverDrop: {
    label: "Quicksilver Drop",
    color: COLOR.overflowBlue,
    image: "crits/elements/quicksilverDrop.webp",
    description: "Adds 41.4% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
