import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const FANTASY_FEET_CRITS = {
  magentaScaleSoles: {
    label: "Magenta Scale Soles",
    color: COLOR.grandOpeningRose,
    image: "crits/fantasyFeet/magentaScaleSoles.webp",
    description: "Cuts every price in this building by 17.4%",
  },
  rubyWyrmSoles: {
    label: "Ruby Wyrm Soles",
    color: COLOR.redActive,
    image: "crits/fantasyFeet/rubyWyrmSoles.webp",
    description: "Boosts every worker for 128s, counting as 3 extra workers",
  },
  azureDrakeToes: {
    label: "Azure Drake Toes",
    color: COLOR.overflowBlue,
    image: "crits/fantasyFeet/azureDrakeToes.webp",
    description: "Repeats the crit on the floor above, 83% chance to keep climbing",
  },
  emberHeelHoard: {
    label: "Ember Heel Hoard",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyFeet/emberHeelHoard.webp",
    description: "Adds 14.5% of your total income",
  },
  pinkPadWyvern: {
    label: "Pink Pad Wyvern",
    color: COLOR.overflowBlue,
    image: "crits/fantasyFeet/pinkPadWyvern.webp",
    description: "Boosts every worker for 129s, counting as 3 extra workers",
  },
  midnightSoles: {
    label: "Midnight Soles",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyFeet/midnightSoles.webp",
    description: "Cuts every price in this building by 18.4%",
  },
  crimsonCapeSoles: {
    label: "Crimson Cape Soles",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyFeet/crimsonCapeSoles.webp",
    description: "Adds 51s of your company's income",
  },
  tenderTuskRub: {
    label: "Tender Tusk Rub",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyFeet/tenderTuskRub.webp",
    description: "Boosts every worker for 147s, counting as 3 extra workers",
  },
  tuskedToeTrade: {
    label: "Tusked Toe Trade",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyFeet/tuskedToeTrade.webp",
    description: "Adds 20.5% of your total income",
  },
  tusksAndToes: {
    label: "Tusks And Toes",
    color: COLOR.luckyCloverGreen,
    image: "crits/fantasyFeet/tusksAndToes.webp",
    description: "Boosts every worker for 148s, counting as 3 extra workers",
  },
  warbandWiggles: {
    label: "Warband Wiggles",
    color: COLOR.luckyCloverGreen,
    image: "crits/fantasyFeet/warbandWiggles.webp",
    description: "Cuts every price in this building by 19.2%",
  },
  warchiefPedicure: {
    label: "Warchief Pedicure",
    color: COLOR.disabledGray,
    image: "crits/fantasyFeet/warchiefPedicure.webp",
    description: "Adds 20.6% of your total income",
  },
  barefootRangers: {
    label: "Barefoot Rangers",
    color: COLOR.amberMuted,
    image: "crits/fantasyFeet/barefootRangers.webp",
    description: "Boosts every worker for 162s, counting as 3 extra workers",
  },
  bloodBank: {
    label: "Blood Bank",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyFeet/bloodBank.webp",
    description: "Cuts every price in this building by 20.5%",
  },
  cryptKeeper: {
    label: "Crypt Keeper",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyFeet/cryptKeeper.webp",
    description: "Boosts every worker for 163s, counting as 3 extra workers",
  },
  fangShui: {
    label: "Fang Shui",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyFeet/fangShui.webp",
    description: "Cuts every price in this building by 20.6%",
  },
  ghostOfAChance: {
    label: "Ghost Of A Chance",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyFeet/ghostOfAChance.webp",
    description: "Boosts every worker for 164s, counting as 3 extra workers",
  },
  redVelvetCape: {
    label: "Red Velvet Cape",
    color: COLOR.nightShiftIndigo,
    image: "crits/fantasyFeet/redVelvetCape.webp",
    description: "Cuts every price in this building by 20.8%",
  },
  theCountess: {
    label: "The Countess",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyFeet/theCountess.webp",
    description: "Adds 22.2% of your total income",
  },
  woodlandWanderers: {
    label: "Woodland Wanderers",
    color: COLOR.amberMuted,
    image: "crits/fantasyFeet/woodlandWanderers.webp",
    description: "Boosts every worker for 166s, counting as 3 extra workers",
  },
  goblinGrins: {
    label: "Goblin Grins",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyFeet/goblinGrins.webp",
    description: "Spreads 99 free upgrades over the lowest-level floors",
  },
  armbandGoblinLounge: {
    label: "Armband Goblin Lounge",
    color: COLOR.bullMarketGreen,
    image: "crits/fantasyFeet/armbandGoblinLounge.webp",
    description: "Pays 132 times this floor's upgrade price in cash",
  },
  cobaltCropGoblin: {
    label: "Cobalt Crop Goblin",
    color: COLOR.moneyGreen,
    image: "crits/fantasyFeet/cobaltCropGoblin.webp",
    description: "Grows every unlocked floor's level by 7.4% in free upgrades",
  },
  goblinKneeSqueeze: {
    label: "Goblin Knee Squeeze",
    color: COLOR.moneyGreen,
    image: "crits/fantasyFeet/goblinKneeSqueeze.webp",
    description: "Spreads 143 free upgrades over the lowest-level floors",
  },
  plumBunGoblin: {
    label: "Plum Bun Goblin",
    color: COLOR.disabledGray,
    image: "crits/fantasyFeet/plumBunGoblin.webp",
    description: "Pays 133 times this floor's upgrade price in cash",
  },
  tealTopGoblin: {
    label: "Teal Top Goblin",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyFeet/tealTopGoblin.webp",
    description: "Grows every unlocked floor's level by 7.5% in free upgrades",
  },
  beanCounterPaws: {
    label: "Bean Counter Paws",
    color: COLOR.gold,
    image: "crits/fantasyFeet/beanCounterPaws.webp",
    description: "Cuts every price in this building by 7.4%",
  },
  kittyToeCapital: {
    label: "Kitty Toe Capital",
    color: COLOR.fastForwardBlue,
    image: "crits/fantasyFeet/kittyToeCapital.webp",
    description: "Adds 5.7% of your total income",
  },
  pawprintProfits: {
    label: "Pawprint Profits",
    color: COLOR.amberMuted,
    image: "crits/fantasyFeet/pawprintProfits.webp",
    description: "Repeats the crit above and below, 68% chance to keep spreading",
  },
  toeBeanTreasury: {
    label: "Toe Bean Treasury",
    color: COLOR.gold,
    image: "crits/fantasyFeet/toeBeanTreasury.webp",
    description: "Two tier promotions and thirty-one upgrades here",
  },
  whiskerWalk: {
    label: "Whisker Walk",
    color: COLOR.amberMuted,
    image: "crits/fantasyFeet/whiskerWalk.webp",
    description: "Cuts every price in this building by 7.8%",
  },
} as const satisfies Record<string, FeaturedCritData>;
