import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const FARM_FRESH_CRITS = {
  watermelonWindfall: {
    label: "Watermelon Windfall",
    color: COLOR.fullHouseCrimson,
    image: "crits/farmFresh/watermelonWindfall.webp",
    description: "Boosts every worker for 68s, counting as 2 extra workers",
  },
  papayaPayroll: {
    label: "Papaya Payroll",
    color: COLOR.talentScoutOrange,
    image: "crits/farmFresh/papayaPayroll.webp",
    description: "Thirty-four payouts on every unlocked floor",
  },
  kiwiKickback: {
    label: "Kiwi Kickback",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/farmFresh/kiwiKickback.webp",
    description: "Unlocks the next 3 floors for free",
  },
  topBanana: {
    label: "Top Banana",
    color: COLOR.starYellow,
    image: "crits/farmFresh/topBanana.webp",
    description: "Boosts every worker for 45s, counting as 1 extra worker",
  },
  cherryOnTop: {
    label: "Cherry on Top",
    color: COLOR.doubleDownCrimson,
    image: "crits/farmFresh/cherryOnTop.webp",
    description: "Cuts every price in this building by 4.7%",
  },
  peachPerfect: {
    label: "Peach Perfect",
    color: COLOR.grandOpeningRose,
    image: "crits/farmFresh/peachPerfect.webp",
    description: "One tier promotion and twenty-seven upgrades here",
  },
  plumJob: {
    label: "Plum Job",
    color: COLOR.royalFlushPurple,
    image: "crits/farmFresh/plumJob.webp",
    description: "Cuts every price in this building by 4.3%",
  },
  dragonfruitDynasty: {
    label: "Dragonfruit Dynasty",
    color: COLOR.easterSalePink,
    image: "crits/farmFresh/dragonfruitDynasty.webp",
    description: "Cuts every price in this building by 4.3%",
  },
  grapeExpectations: {
    label: "Grape Expectations",
    color: COLOR.halloweenSalePurple,
    image: "crits/farmFresh/grapeExpectations.webp",
    description: "Thirty-eight free upgrades on alternating floors",
  },
  pomegranatePortfolio: {
    label: "Pomegranate Portfolio",
    color: COLOR.fireDrillRed,
    image: "crits/farmFresh/pomegranatePortfolio.webp",
    description: "Thirty-two upgrades here and on the lowest-level floor",
  },
  calciumCapital: {
    label: "Calcium Capital",
    color: COLOR.overflowBlue,
    image: "crits/farmFresh/calciumCapital.webp",
    description: "One tier promotion and nine upgrades here",
  },
  creamOfTheCrop: {
    label: "Cream Of The Crop",
    color: COLOR.chairGiveawayBrown,
    image: "crits/farmFresh/creamOfTheCrop.webp",
    description: "Adds 5.4% of your total income",
  },
  dairyDividend: {
    label: "Dairy Dividend",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/farmFresh/dairyDividend.webp",
    description: "Arms the lowest-level floor's next click as an x5 crit",
  },
  gotMilk: {
    label: "Got Milk",
    color: COLOR.amber,
    image: "crits/farmFresh/gotMilk.webp",
    description: "Raises the lowest-level floor to the building's top level",
  },
  lactoseTycoon: {
    label: "Lactose Tycoon",
    color: COLOR.fastForwardBlue,
    image: "crits/farmFresh/lactoseTycoon.webp",
    description: "Unlocks the next 5 floors for free",
  },
  milkMoney: {
    label: "Milk Money",
    color: COLOR.orange,
    image: "crits/farmFresh/milkMoney.webp",
    description: "Cuts every price in this building by 1.1%",
  },
  milkshakeMogul: {
    label: "Milkshake Mogul",
    color: COLOR.overflowBlue,
    image: "crits/farmFresh/milkshakeMogul.webp",
    description: "Boosts every worker for 20s",
  },
  mooJuice: {
    label: "Moo Juice",
    color: COLOR.amberMuted,
    image: "crits/farmFresh/mooJuice.webp",
    description: "Free office chairs for this floor",
  },
  skimProfits: {
    label: "Skim Profits",
    color: COLOR.amberMuted,
    image: "crits/farmFresh/skimProfits.webp",
    description: "Repeats the crit on the floor below, 17% chance to keep falling",
  },
  udderSuccess: {
    label: "Udder Success",
    color: COLOR.sameBoatCoral,
    image: "crits/farmFresh/udderSuccess.webp",
    description: "One tier promotion and six upgrades here",
  },
  wholeMilkHustle: {
    label: "Whole Milk Hustle",
    color: COLOR.overflowBlue,
    image: "crits/farmFresh/wholeMilkHustle.webp",
    description: "Adds 22s of your company's income",
  },
  bottleService: {
    label: "Bottle Service",
    color: COLOR.amberMuted,
    image: "crits/farmFresh/bottleService.webp",
    description: "Repeats the crit on the floor below, 37% chance to keep falling",
  },
  creameryCredit: {
    label: "Creamery Credit",
    color: COLOR.doubleDownCrimson,
    image: "crits/farmFresh/creameryCredit.webp",
    description: "One tier promotion and seven upgrades here",
  },
  milkRun: {
    label: "Milk Run",
    color: COLOR.red,
    image: "crits/farmFresh/milkRun.webp",
    description: "Raises alternating floors to the building's top level",
  },
  pintSizedProfits: {
    label: "Pint Sized Profits",
    color: COLOR.redActive,
    image: "crits/farmFresh/pintSizedProfits.webp",
    description: "Unlocks the next 2 floors for free",
  },
  milkMustacheDrake: {
    label: "Milk Mustache Drake",
    color: COLOR.springCleaningMint,
    image: "crits/farmFresh/milkMustacheDrake.webp",
    description: "Adds 14.9% of your total income",
  },
  bottleChugWyvern: {
    label: "Bottle Chug Wyvern",
    color: COLOR.rainCheckBlue,
    image: "crits/farmFresh/bottleChugWyvern.webp",
    description: "Boosts every worker for 134s, counting as 3 extra workers",
  },
  jadeGlassGuzzle: {
    label: "Jade Glass Guzzle",
    color: COLOR.moneyGreen,
    image: "crits/farmFresh/jadeGlassGuzzle.webp",
    description: "Repeats the crit on the floor below, 85% chance to keep falling",
  },
  calciumCrusher: {
    label: "Calcium Crusher",
    color: COLOR.overflowBlue,
    image: "crits/farmFresh/calciumCrusher.webp",
    description: "Cuts every price in this building by 18%",
  },
  glassHalfFull: {
    label: "Glass Half Full",
    color: COLOR.internSkyBlue,
    image: "crits/farmFresh/glassHalfFull.webp",
    description: "Adds 46s of your company's income",
  },
} as const satisfies Record<string, FeaturedCritData>;
