import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const FEET_CRITS = {
  ankleAsset: {
    label: "Ankle Asset",
    color: COLOR.springSalePink,
    image: "crits/feet/ankleAsset.webp",
    description: "Unlocks the next 2 floors for free",
  },
  archEnemyAssets: {
    label: "Arch Enemy Assets",
    color: COLOR.redActive,
    image: "crits/feet/archEnemyAssets.webp",
    description: "Boosts every worker for 38s",
  },
  barefootBanker: {
    label: "Barefoot Banker",
    color: COLOR.supplyRunTan,
    image: "crits/feet/barefootBanker.webp",
    description: "Hires 2 free workers and a manager on every unlocked floor",
  },
  bestFootForward: {
    label: "Best Foot Forward",
    color: COLOR.teaBreakBrown,
    image: "crits/feet/bestFootForward.webp",
    description: "Repeats the crit above and below, 62% chance to keep spreading",
  },
  coldFeetCash: {
    label: "Cold Feet Cash",
    color: COLOR.coinGold,
    image: "crits/feet/coldFeetCash.webp",
    description: "One tier promotion and seven upgrades here",
  },
  footInTheDoor: {
    label: "Foot In The Door",
    color: COLOR.coinGold,
    image: "crits/feet/footInTheDoor.webp",
    description: "Cuts every price in this building by 1.1%",
  },
  heelTurnHaul: {
    label: "Heel Turn Haul",
    color: COLOR.peppermintPink,
    image: "crits/feet/heelTurnHaul.webp",
    description: "Boosts this floor's workers for 29s",
  },
  pedicurePayout: {
    label: "Pedicure Payout",
    color: COLOR.supplyRunTan,
    image: "crits/feet/pedicurePayout.webp",
    description: "Arms every floor's next click as an x5 crit",
  },
  sockItAway: {
    label: "Sock It Away",
    color: COLOR.teamBuildingCoral,
    image: "crits/feet/sockItAway.webp",
    description: "Boosts every worker for 19s",
  },
  soleProprietor: {
    label: "Sole Proprietor",
    color: COLOR.overflowBlue,
    image: "crits/feet/soleProprietor.webp",
    description: "Hires 1 free worker on alternating floors",
  },
  stepUpStocks: {
    label: "Step Up Stocks",
    color: COLOR.overflowBlue,
    image: "crits/feet/stepUpStocks.webp",
    description: "Repeats the crit on the floor above, 25% chance to keep climbing",
  },
  tenToeTreasury: {
    label: "Ten Toe Treasury",
    color: COLOR.fastForwardBlue,
    image: "crits/feet/tenToeTreasury.webp",
    description: "One tier promotion and eight upgrades here",
  },
  tippyToeTycoon: {
    label: "Tippy Toe Tycoon",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/feet/tippyToeTycoon.webp",
    description: "Unlocks the next 5 floors for free",
  },
  toeRingRiches: {
    label: "Toe Ring Riches",
    color: COLOR.amberMuted,
    image: "crits/feet/toeRingRiches.webp",
    description: "Cuts every price in this building by 2.1%",
  },
  toeTally: {
    label: "Toe Tally",
    color: COLOR.fullHouseCrimson,
    image: "crits/feet/toeTally.webp",
    description: "Adds 44s of your company's income",
  },
  beanCounterPaws: {
    label: "Bean Counter Paws",
    color: COLOR.gold,
    image: "crits/feet/beanCounterPaws.webp",
    description: "Cuts every price in this building by 7.4%",
  },
  kittyToeCapital: {
    label: "Kitty Toe Capital",
    color: COLOR.fastForwardBlue,
    image: "crits/feet/kittyToeCapital.webp",
    description: "Adds 5.7% of your total income",
  },
  pawprintProfits: {
    label: "Pawprint Profits",
    color: COLOR.amberMuted,
    image: "crits/feet/pawprintProfits.webp",
    description: "Repeats the crit above and below, 68% chance to keep spreading",
  },
  toeBeanTreasury: {
    label: "Toe Bean Treasury",
    color: COLOR.gold,
    image: "crits/feet/toeBeanTreasury.webp",
    description: "Two tier promotions and thirty-one upgrades here",
  },
  whiskerWalk: {
    label: "Whisker Walk",
    color: COLOR.amberMuted,
    image: "crits/feet/whiskerWalk.webp",
    description: "Cuts every price in this building by 7.8%",
  },
  doubleSoleMoo: {
    label: "Double Sole Moo",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/doubleSoleMoo.webp",
    description: "Cuts every price in this building by 16.5%",
  },
  magentaScaleSoles: {
    label: "Magenta Scale Soles",
    color: COLOR.grandOpeningRose,
    image: "crits/feet/magentaScaleSoles.webp",
    description: "Cuts every price in this building by 17.4%",
  },
  rubyWyrmSoles: {
    label: "Ruby Wyrm Soles",
    color: COLOR.redActive,
    image: "crits/feet/rubyWyrmSoles.webp",
    description: "Boosts every worker for 128s, counting as 3 extra workers",
  },
  azureDrakeToes: {
    label: "Azure Drake Toes",
    color: COLOR.overflowBlue,
    image: "crits/feet/azureDrakeToes.webp",
    description: "Repeats the crit on the floor above, 83% chance to keep climbing",
  },
  emberHeelHoard: {
    label: "Ember Heel Hoard",
    color: COLOR.doubleDownCrimson,
    image: "crits/feet/emberHeelHoard.webp",
    description: "Adds 14.5% of your total income",
  },
  pinkPadWyvern: {
    label: "Pink Pad Wyvern",
    color: COLOR.overflowBlue,
    image: "crits/feet/pinkPadWyvern.webp",
    description: "Boosts every worker for 129s, counting as 3 extra workers",
  },
  midnightSoles: {
    label: "Midnight Soles",
    color: COLOR.doubleDownCrimson,
    image: "crits/feet/midnightSoles.webp",
    description: "Cuts every price in this building by 18.4%",
  },
  crimsonCapeSoles: {
    label: "Crimson Cape Soles",
    color: COLOR.doubleDownCrimson,
    image: "crits/feet/crimsonCapeSoles.webp",
    description: "Adds 51s of your company's income",
  },
  bigHoopHustle: {
    label: "Big Hoop Hustle",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/bigHoopHustle.webp",
    description: "Repeats the crit on the floor below, 88% chance to keep falling",
  },
  bubblegumTwins: {
    label: "Bubblegum Twins",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/bubblegumTwins.webp",
    description: "Cuts every price in this building by 18.6%",
  },
  cooldownStretch: {
    label: "Cooldown Stretch",
    color: COLOR.luckyCloverGreen,
    image: "crits/feet/cooldownStretch.webp",
    description: "Adds 53s of your company's income",
  },
  cuddleClanComfort: {
    label: "Cuddle Clan Comfort",
    color: COLOR.luckyCloverGreen,
    image: "crits/feet/cuddleClanComfort.webp",
    description: "Boosts every worker for 142s, counting as 3 extra workers",
  },
  hotPinkPads: {
    label: "Hot Pink Pads",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/hotPinkPads.webp",
    description: "Adds 54s of your company's income",
  },
  kickBackCapital: {
    label: "Kick Back Capital",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/kickBackCapital.webp",
    description: "Boosts every worker for 143s, counting as 3 extra workers",
  },
  lazySundaySoles: {
    label: "Lazy Sunday Soles",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/lazySundaySoles.webp",
    description: "Repeats the crit on the floor below, 89% chance to keep falling",
  },
  lemonSole: {
    label: "Lemon Sole",
    color: COLOR.coinGold,
    image: "crits/feet/lemonSole.webp",
    description: "Cuts every price in this building by 18.8%",
  },
  logLoungeSoles: {
    label: "Log Lounge Soles",
    color: COLOR.luckyCloverGreen,
    image: "crits/feet/logLoungeSoles.webp",
    description: "Adds 55s of your company's income",
  },
  mirrorImageSoles: {
    label: "Mirror Image Soles",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/mirrorImageSoles.webp",
    description: "Boosts every worker for 145s, counting as 3 extra workers",
  },
  muscleToeMogul: {
    label: "Muscle Toe Mogul",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/muscleToeMogul.webp",
    description: "Repeats the crit on the floor above, 90% chance to keep climbing",
  },
  overallProfits: {
    label: "Overall Profits",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/overallProfits.webp",
    description: "Adds 56s of your company's income",
  },
  punkRockPedicure: {
    label: "Punk Rock Pedicure",
    color: COLOR.gold,
    image: "crits/feet/punkRockPedicure.webp",
    description: "Boosts every worker for 146s, counting as 3 extra workers",
  },
  scrapyardSoles: {
    label: "Scrapyard Soles",
    color: COLOR.bullMarketGreen,
    image: "crits/feet/scrapyardSoles.webp",
    description: "Repeats the crit on the floor below, 90% chance to keep falling",
  },
  soleSpotlight: {
    label: "Sole Spotlight",
    color: COLOR.luckyCloverGreen,
    image: "crits/feet/soleSpotlight.webp",
    description: "Cuts every price in this building by 19%",
  },
  sunnySoleSisters: {
    label: "Sunny Sole Sisters",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/sunnySoleSisters.webp",
    description: "Adds 57s of your company's income",
  },
  tenderTuskRub: {
    label: "Tender Tusk Rub",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/tenderTuskRub.webp",
    description: "Boosts every worker for 147s, counting as 3 extra workers",
  },
  tickleTax: {
    label: "Tickle Tax",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/tickleTax.webp",
    description: "Repeats the crit on the floor above, 91% chance to keep climbing",
  },
  tuskedToeTrade: {
    label: "Tusked Toe Trade",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/tuskedToeTrade.webp",
    description: "Adds 20.5% of your total income",
  },
  tusksAndToes: {
    label: "Tusks And Toes",
    color: COLOR.luckyCloverGreen,
    image: "crits/feet/tusksAndToes.webp",
    description: "Boosts every worker for 148s, counting as 3 extra workers",
  },
  twinBraidTreads: {
    label: "Twin Braid Treads",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/twinBraidTreads.webp",
    description: "Repeats the crit on the floor below, 91% chance to keep falling",
  },
  warbandWiggles: {
    label: "Warband Wiggles",
    color: COLOR.luckyCloverGreen,
    image: "crits/feet/warbandWiggles.webp",
    description: "Cuts every price in this building by 19.2%",
  },
  warchiefPedicure: {
    label: "Warchief Pedicure",
    color: COLOR.disabledGray,
    image: "crits/feet/warchiefPedicure.webp",
    description: "Adds 20.6% of your total income",
  },
  barefootRangers: {
    label: "Barefoot Rangers",
    color: COLOR.amberMuted,
    image: "crits/feet/barefootRangers.webp",
    description: "Boosts every worker for 162s, counting as 3 extra workers",
  },
  bloodBank: {
    label: "Blood Bank",
    color: COLOR.doubleDownCrimson,
    image: "crits/feet/bloodBank.webp",
    description: "Cuts every price in this building by 20.5%",
  },
  cryptKeeper: {
    label: "Crypt Keeper",
    color: COLOR.doubleDownCrimson,
    image: "crits/feet/cryptKeeper.webp",
    description: "Boosts every worker for 163s, counting as 3 extra workers",
  },
  fangShui: {
    label: "Fang Shui",
    color: COLOR.doubleDownCrimson,
    image: "crits/feet/fangShui.webp",
    description: "Cuts every price in this building by 20.6%",
  },
  feelingBlue: {
    label: "Feeling Blue",
    color: COLOR.overflowBlue,
    image: "crits/feet/feelingBlue.webp",
    description: "Adds 22% of your total income",
  },
  ghostOfAChance: {
    label: "Ghost Of A Chance",
    color: COLOR.doubleDownCrimson,
    image: "crits/feet/ghostOfAChance.webp",
    description: "Boosts every worker for 164s, counting as 3 extra workers",
  },
  oddCouple: {
    label: "Odd Couple",
    color: COLOR.gold,
    image: "crits/feet/oddCouple.webp",
    description: "Adds 22.1% of your total income",
  },
  onTheBall: {
    label: "On The Ball",
    color: COLOR.amberMuted,
    image: "crits/feet/onTheBall.webp",
    description: "Boosts every worker for 165s, counting as 3 extra workers",
  },
  redVelvetCape: {
    label: "Red Velvet Cape",
    color: COLOR.nightShiftIndigo,
    image: "crits/feet/redVelvetCape.webp",
    description: "Cuts every price in this building by 20.8%",
  },
  theCountess: {
    label: "The Countess",
    color: COLOR.doubleDownCrimson,
    image: "crits/feet/theCountess.webp",
    description: "Adds 22.2% of your total income",
  },
  woodlandWanderers: {
    label: "Woodland Wanderers",
    color: COLOR.amberMuted,
    image: "crits/feet/woodlandWanderers.webp",
    description: "Boosts every worker for 166s, counting as 3 extra workers",
  },
  legUpLedger: {
    label: "Leg Up Ledger",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/legUpLedger.webp",
    description: "Adds 22.8% of your total income",
  },
  pixieCutPayday: {
    label: "Pixie Cut Payday",
    color: COLOR.nightShiftIndigo,
    image: "crits/feet/pixieCutPayday.webp",
    description: "Adds 22.9% of your total income",
  },
  sunsetSoleSavings: {
    label: "Sunset Sole Savings",
    color: COLOR.rainCheckBlue,
    image: "crits/feet/sunsetSoleSavings.webp",
    description: "Adds 23% of your total income",
  },
  flexiblePricing: {
    label: "Flexible Pricing",
    color: COLOR.fullHouseCrimson,
    image: "crits/feet/flexiblePricing.webp",
    description: "Cuts every price in this building by 21.3%",
  },
  goldenBeltGrind: {
    label: "Golden Belt Grind",
    color: COLOR.overflowBlue,
    image: "crits/feet/goldenBeltGrind.webp",
    description: "Boosts every worker for 170s, counting as 3 extra workers",
  },
  highKickMarkdown: {
    label: "High Kick Markdown",
    color: COLOR.nightShiftIndigo,
    image: "crits/feet/highKickMarkdown.webp",
    description: "Cuts every price in this building by 21.4%",
  },
  petticoatPriceCut: {
    label: "Petticoat Price Cut",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/petticoatPriceCut.webp",
    description: "Cuts every price in this building by 21.5%",
  },
  pinkCarpetKickoff: {
    label: "Pink Carpet Kickoff",
    color: COLOR.fullHouseCrimson,
    image: "crits/feet/pinkCarpetKickoff.webp",
    description: "Boosts every worker for 171s, counting as 3 extra workers",
  },
  rainbowRuffleRally: {
    label: "Rainbow Ruffle Rally",
    color: COLOR.fastForwardBlue,
    image: "crits/feet/rainbowRuffleRally.webp",
    description: "Boosts every worker for 172s, counting as 3 extra workers",
  },
  redCarpetClearance: {
    label: "Red Carpet Clearance",
    color: COLOR.doubleDownCrimson,
    image: "crits/feet/redCarpetClearance.webp",
    description: "Cuts every price in this building by 21.6%",
  },
  tightLacedTeam: {
    label: "Tight Laced Team",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/tightLacedTeam.webp",
    description: "Boosts every worker for 173s, counting as 3 extra workers",
  },
  faceValue: {
    label: "Face Value",
    color: COLOR.amberMuted,
    image: "crits/feet/faceValue.webp",
    description: "Adds 23.1% of your total income",
  },
  heelDeal: {
    label: "Heel Deal",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/feet/heelDeal.webp",
    description: "Eight instant payouts on this floor",
  },
  soleCustody: {
    label: "Sole Custody",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/soleCustody.webp",
    description: "Adds 23.2% of your total income",
  },
  splitTheProfits: {
    label: "Split the Profits",
    color: COLOR.chairGiveawayBrown,
    image: "crits/feet/splitTheProfits.webp",
    description: "Adds 23.3% of your total income",
  },
  emeraldToeEarnings: {
    label: "Emerald Toe Earnings",
    color: COLOR.paydayEmerald,
    image: "crits/feet/emeraldToeEarnings.webp",
    description: "Adds 24.1% of your total income",
  },
  footTheBill: {
    label: "Foot the Bill",
    color: COLOR.amberMuted,
    image: "crits/feet/footTheBill.webp",
    description: "Thirty-six instant payouts on this floor",
  },
  greenToeGreenbacks: {
    label: "Green Toe Greenbacks",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/greenToeGreenbacks.webp",
    description: "Thirty-seven instant payouts on this floor",
  },
  lyingLowLedger: {
    label: "Lying Low Ledger",
    color: COLOR.amberMuted,
    image: "crits/feet/lyingLowLedger.webp",
    description: "Adds 24.2% of your total income",
  },
  toeToToeTrade: {
    label: "Toe to Toe Trade",
    color: COLOR.teaBreakBrown,
    image: "crits/feet/toeToToeTrade.webp",
    description: "Fifty-two free upgrades on this floor",
  },
  daisyDuel: {
    label: "Daisy Duel",
    color: COLOR.threeOfAKindGreen,
    image: "crits/feet/daisyDuel.webp",
    description: "Pays 17 times this floor's upgrade price in cash",
  },
  goblinGrins: {
    label: "Goblin Grins",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/goblinGrins.webp",
    description: "Spreads 99 free upgrades over the lowest-level floors",
  },
  toeTussle: {
    label: "Toe Tussle",
    color: COLOR.gold,
    image: "crits/feet/toeTussle.webp",
    description: "Grows every unlocked floor's level by 2.2% in free upgrades",
  },
  toeGrip: {
    label: "Toe Grip",
    color: COLOR.amberMuted,
    image: "crits/feet/toeGrip.webp",
    description: "Spreads 12 free upgrades over the lowest-level floors",
  },
  toePyramid: {
    label: "Toe Pyramid",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/toePyramid.webp",
    description: "Pays 18 times this floor's upgrade price in cash",
  },
  armsWideKiss: {
    label: "Arms Wide Kiss",
    color: COLOR.coinGold,
    image: "crits/feet/armsWideKiss.webp",
    description: "Pays 22 times every unlocked floor's upgrade price in cash",
  },
  bandanaSmooch: {
    label: "Bandana Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/bandanaSmooch.webp",
    description: "Grows this floor's level by 5.6% in free upgrades",
  },
  bicepBunKiss: {
    label: "Bicep Bun Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/bicepBunKiss.webp",
    description: "Spreads 57 free upgrades over the lowest-level floors",
  },
  blueBuzzCutKiss: {
    label: "Blue Buzz Cut Kiss",
    color: COLOR.amberMuted,
    image: "crits/feet/blueBuzzCutKiss.webp",
    description: "Pays 100 times this floor's upgrade price in cash",
  },
  blueLeggingsPeck: {
    label: "Blue Leggings Peck",
    color: COLOR.fastForwardBlue,
    image: "crits/feet/blueLeggingsPeck.webp",
    description: "Grows this floor's level by 5.7% in free upgrades",
  },
  blueManeSmooch: {
    label: "Blue Mane Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/blueManeSmooch.webp",
    description: "Spreads 58 free upgrades over the lowest-level floors",
  },
  bluePolishPucker: {
    label: "Blue Polish Pucker",
    color: COLOR.amberMuted,
    image: "crits/feet/bluePolishPucker.webp",
    description: "Pays 101 times this floor's upgrade price in cash",
  },
  bobCutSmooch: {
    label: "Bob Cut Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/bobCutSmooch.webp",
    description: "Grows this floor's level by 5.8% in free upgrades",
  },
  bothFeetPucker: {
    label: "Both Feet Pucker",
    color: COLOR.amberMuted,
    image: "crits/feet/bothFeetPucker.webp",
    description: "Spreads 59 free upgrades over the lowest-level floors",
  },
  brickShortsPucker: {
    label: "Brick Shorts Pucker",
    color: COLOR.amberMuted,
    image: "crits/feet/brickShortsPucker.webp",
    description: "Pays 102 times this floor's upgrade price in cash",
  },
  closeUpKiss: {
    label: "Close Up Kiss",
    color: COLOR.amberMuted,
    image: "crits/feet/closeUpKiss.webp",
    description: "Grows this floor's level by 5.9% in free upgrades",
  },
  coralSoleSmooch: {
    label: "Coral Sole Smooch",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/coralSoleSmooch.webp",
    description: "Spreads 60 free upgrades over the lowest-level floors",
  },
  coralToeCurl: {
    label: "Coral Toe Curl",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/coralToeCurl.webp",
    description: "Pays 103 times this floor's upgrade price in cash",
  },
  crimsonCropPucker: {
    label: "Crimson Crop Pucker",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/crimsonCropPucker.webp",
    description: "Grows this floor's level by 6% in free upgrades",
  },
  crouchKiss: {
    label: "Crouch Kiss",
    color: COLOR.amberMuted,
    image: "crits/feet/crouchKiss.webp",
    description: "Spreads 61 free upgrades over the lowest-level floors",
  },
  curlyManeMwah: {
    label: "Curly Mane Mwah",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/curlyManeMwah.webp",
    description: "Pays 104 times this floor's upgrade price in cash",
  },
  doubleBunPucker: {
    label: "Double Bun Pucker",
    color: COLOR.coinGold,
    image: "crits/feet/doubleBunPucker.webp",
    description: "Grows this floor's level by 6.1% in free upgrades",
  },
  fingerPointPeck: {
    label: "Finger Point Peck",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/feet/fingerPointPeck.webp",
    description: "Spreads 62 free upgrades over the lowest-level floors",
  },
  flatTopPucker: {
    label: "Flat Top Pucker",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/flatTopPucker.webp",
    description: "Pays 105 times this floor's upgrade price in cash",
  },
  flexAndPucker: {
    label: "Flex And Pucker",
    color: COLOR.starYellow,
    image: "crits/feet/flexAndPucker.webp",
    description: "Grows this floor's level by 6.2% in free upgrades",
  },
  flexPosePeck: {
    label: "Flex Pose Peck",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/flexPosePeck.webp",
    description: "Spreads 63 free upgrades over the lowest-level floors",
  },
  frontKickPucker: {
    label: "Front Kick Pucker",
    color: COLOR.coinGold,
    image: "crits/feet/frontKickPucker.webp",
    description: "Pays 106 times this floor's upgrade price in cash",
  },
  giantArchDare: {
    label: "Giant Arch Dare",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/giantArchDare.webp",
    description: "Grows this floor's level by 6.3% in free upgrades",
  },
  goldWristbandKiss: {
    label: "Gold Wristband Kiss",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/goldWristbandKiss.webp",
    description: "Spreads 64 free upgrades over the lowest-level floors",
  },
  greenToenailTease: {
    label: "Green Toenail Tease",
    color: COLOR.amberMuted,
    image: "crits/feet/greenToenailTease.webp",
    description: "Pays 107 times this floor's upgrade price in cash",
  },
  handOnHipKiss: {
    label: "Hand On Hip Kiss",
    color: COLOR.amberMuted,
    image: "crits/feet/handOnHipKiss.webp",
    description: "Grows this floor's level by 6.4% in free upgrades",
  },
  hoopEarringSmooch: {
    label: "Hoop Earring Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/hoopEarringSmooch.webp",
    description: "Pays 108 times this floor's upgrade price in cash",
  },
  hotPinkStreak: {
    label: "Hot Pink Streak",
    color: COLOR.coinGold,
    image: "crits/feet/hotPinkStreak.webp",
    description: "Grows this floor's level by 13.4% in free upgrades",
  },
  kneePadKiss: {
    label: "Knee Pad Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/kneePadKiss.webp",
    description: "Spreads 66 free upgrades over the lowest-level floors",
  },
  leanInKiss: {
    label: "Lean In Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/leanInKiss.webp",
    description: "Pays 109 times this floor's upgrade price in cash",
  },
  lemonArchKiss: {
    label: "Lemon Arch Kiss",
    color: COLOR.starYellow,
    image: "crits/feet/lemonArchKiss.webp",
    description: "Grows this floor's level by 13.5% in free upgrades",
  },
  leotardKiss: {
    label: "Leotard Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/leotardKiss.webp",
    description: "Spreads 67 free upgrades over the lowest-level floors",
  },
  magentaPantsMwah: {
    label: "Magenta Pants Mwah",
    color: COLOR.coinGold,
    image: "crits/feet/magentaPantsMwah.webp",
    description: "Pays 110 times this floor's upgrade price in cash",
  },
  maroonShortsMwah: {
    label: "Maroon Shorts Mwah",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/maroonShortsMwah.webp",
    description: "Grows this floor's level by 13.6% in free upgrades",
  },
  messyBunMwah: {
    label: "Messy Bun Mwah",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/messyBunMwah.webp",
    description: "Spreads 121 free upgrades over the lowest-level floors",
  },
  muscleQueenSmooch: {
    label: "Muscle Queen Smooch",
    color: COLOR.teamBuildingCoral,
    image: "crits/feet/muscleQueenSmooch.webp",
    description: "Pays 111 times this floor's upgrade price in cash",
  },
  neonPantsPeck: {
    label: "Neon Pants Peck",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/neonPantsPeck.webp",
    description: "Grows this floor's level by 13.7% in free upgrades",
  },
  paleArchPeck: {
    label: "Pale Arch Peck",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/paleArchPeck.webp",
    description: "Spreads 122 free upgrades over the lowest-level floors",
  },
  peachShortsPucker: {
    label: "Peach Shorts Pucker",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/peachShortsPucker.webp",
    description: "Pays 112 times this floor's upgrade price in cash",
  },
  peekabooSole: {
    label: "Peekaboo Sole",
    color: COLOR.coinGold,
    image: "crits/feet/peekabooSole.webp",
    description: "Grows this floor's level by 13.8% in free upgrades",
  },
  pinkHeadbandPointer: {
    label: "Pink Headband Pointer",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/pinkHeadbandPointer.webp",
    description: "Spreads 123 free upgrades over the lowest-level floors",
  },
  pinkHeelPeck: {
    label: "Pink Heel Peck",
    color: COLOR.coinGold,
    image: "crits/feet/pinkHeelPeck.webp",
    description: "Pays 113 times this floor's upgrade price in cash",
  },
  pinkNailPointer: {
    label: "Pink Nail Pointer",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/pinkNailPointer.webp",
    description: "Grows this floor's level by 13.9% in free upgrades",
  },
  pinkSleevePucker: {
    label: "Pink Sleeve Pucker",
    color: COLOR.fastForwardBlue,
    image: "crits/feet/pinkSleevePucker.webp",
    description: "Spreads 124 free upgrades over the lowest-level floors",
  },
  pinkStripePucker: {
    label: "Pink Stripe Pucker",
    color: COLOR.amberMuted,
    image: "crits/feet/pinkStripePucker.webp",
    description: "Pays 114 times this floor's upgrade price in cash",
  },
  pocketPucker: {
    label: "Pocket Pucker",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/pocketPucker.webp",
    description: "Grows this floor's level by 14% in free upgrades",
  },
  pointDownPucker: {
    label: "Point Down Pucker",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/pointDownPucker.webp",
    description: "Spreads 125 free upgrades over the lowest-level floors",
  },
  rainbowLeggingsPucker: {
    label: "Rainbow Leggings Pucker",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/rainbowLeggingsPucker.webp",
    description: "Pays 115 times this floor's upgrade price in cash",
  },
  redHotSole: {
    label: "Red Hot Sole",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/redHotSole.webp",
    description: "Grows this floor's level by 14.1% in free upgrades",
  },
  redTopSmooch: {
    label: "Red Top Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/redTopSmooch.webp",
    description: "Spreads 126 free upgrades over the lowest-level floors",
  },
  rustShortsSmooch: {
    label: "Rust Shorts Smooch",
    color: COLOR.amberMuted,
    image: "crits/feet/rustShortsSmooch.webp",
    description: "Pays 116 times this floor's upgrade price in cash",
  },
  salmonSoleSmooch: {
    label: "Salmon Sole Smooch",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/salmonSoleSmooch.webp",
    description: "Grows this floor's level by 14.2% in free upgrades",
  },
  salmonToesTease: {
    label: "Salmon Toes Tease",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/salmonToesTease.webp",
    description: "Spreads 127 free upgrades over the lowest-level floors",
  },
  shortCropKiss: {
    label: "Short Crop Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/shortCropKiss.webp",
    description: "Pays 117 times this floor's upgrade price in cash",
  },
  sidePointSmooch: {
    label: "Side Point Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/sidePointSmooch.webp",
    description: "Grows this floor's level by 14.3% in free upgrades",
  },
  silverBuzzFlex: {
    label: "Silver Buzz Flex",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/silverBuzzFlex.webp",
    description: "Spreads 128 free upgrades over the lowest-level floors",
  },
  spikyHairSmooch: {
    label: "Spiky Hair Smooch",
    color: COLOR.teamBuildingCoral,
    image: "crits/feet/spikyHairSmooch.webp",
    description: "Pays 118 times this floor's upgrade price in cash",
  },
  tangerineToes: {
    label: "Tangerine Toes",
    color: COLOR.orange,
    image: "crits/feet/tangerineToes.webp",
    description: "Grows this floor's level by 14.4% in free upgrades",
  },
  tealCropKiss: {
    label: "Teal Crop Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/tealCropKiss.webp",
    description: "Spreads 129 free upgrades over the lowest-level floors",
  },
  thunderThighSmooch: {
    label: "Thunder Thigh Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/thunderThighSmooch.webp",
    description: "Pays 119 times this floor's upgrade price in cash",
  },
  topBunToes: {
    label: "Top Bun Toes",
    color: COLOR.amberMuted,
    image: "crits/feet/topBunToes.webp",
    description: "Grows this floor's level by 14.5% in free upgrades",
  },
  topknotTiptoe: {
    label: "Topknot Tiptoe",
    color: COLOR.amberMuted,
    image: "crits/feet/topknotTiptoe.webp",
    description: "Spreads 130 free upgrades over the lowest-level floors",
  },
  tropicToesKiss: {
    label: "Tropic Toes Kiss",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/tropicToesKiss.webp",
    description: "Pays 120 times this floor's upgrade price in cash",
  },
  waggingFingerKiss: {
    label: "Wagging Finger Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/waggingFingerKiss.webp",
    description: "Grows this floor's level by 14.6% in free upgrades",
  },
  whiteCropKiss: {
    label: "White Crop Kiss",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/feet/whiteCropKiss.webp",
    description: "Spreads 131 free upgrades over the lowest-level floors",
  },
  yellowHeelPeck: {
    label: "Yellow Heel Peck",
    color: COLOR.coinGold,
    image: "crits/feet/yellowHeelPeck.webp",
    description: "Pays 121 times this floor's upgrade price in cash",
  },
  bigSoleSpread: {
    label: "Big Sole Spread",
    color: COLOR.coinGold,
    image: "crits/feet/bigSoleSpread.webp",
    description: "Grows this floor's level by 14.7% in free upgrades",
  },
  blondeBallUp: {
    label: "Blonde Ball Up",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/blondeBallUp.webp",
    description: "Spreads 132 free upgrades over the lowest-level floors",
  },
  bumblebeeLegs: {
    label: "Bumblebee Legs",
    color: COLOR.amberMuted,
    image: "crits/feet/bumblebeeLegs.webp",
    description: "Pays 122 times this floor's upgrade price in cash",
  },
  bunTopPike: {
    label: "Bun Top Pike",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/bunTopPike.webp",
    description: "Grows this floor's level by 14.8% in free upgrades",
  },
  butterflySplit: {
    label: "Butterfly Split",
    color: COLOR.starYellow,
    image: "crits/feet/butterflySplit.webp",
    description: "Spreads 133 free upgrades over the lowest-level floors",
  },
  candyLeggingsKick: {
    label: "Candy Leggings Kick",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/candyLeggingsKick.webp",
    description: "Pays 123 times this floor's upgrade price in cash",
  },
  cobaltBobKick: {
    label: "Cobalt Bob Kick",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/cobaltBobKick.webp",
    description: "Grows this floor's level by 14.9% in free upgrades",
  },
  crisscrossBun: {
    label: "Crisscross Bun",
    color: COLOR.amberMuted,
    image: "crits/feet/crisscrossBun.webp",
    description: "Pays 124 times this floor's upgrade price in cash",
  },
  frogSitFlex: {
    label: "Frog Sit Flex",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/frogSitFlex.webp",
    description: "Grows every unlocked floor's level by 6.6% in free upgrades",
  },
  goldenLocksLegUp: {
    label: "Golden Locks Leg Up",
    color: COLOR.starYellow,
    image: "crits/feet/goldenLocksLegUp.webp",
    description: "Spreads 135 free upgrades over the lowest-level floors",
  },
  huggedStilts: {
    label: "Hugged Stilts",
    color: COLOR.amberMuted,
    image: "crits/feet/huggedStilts.webp",
    description: "Pays 125 times this floor's upgrade price in cash",
  },
  kneeHugHuddle: {
    label: "Knee Hug Huddle",
    color: COLOR.amberMuted,
    image: "crits/feet/kneeHugHuddle.webp",
    description: "Grows every unlocked floor's level by 6.7% in free upgrades",
  },
  lowFadeFootrest: {
    label: "Low Fade Footrest",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/feet/lowFadeFootrest.webp",
    description: "Spreads 136 free upgrades over the lowest-level floors",
  },
  mintShortsLift: {
    label: "Mint Shorts Lift",
    color: COLOR.summerSaleOrange,
    image: "crits/feet/mintShortsLift.webp",
    description: "Pays 126 times this floor's upgrade price in cash",
  },
  patchworkPantsHug: {
    label: "Patchwork Pants Hug",
    color: COLOR.fastForwardBlue,
    image: "crits/feet/patchworkPantsHug.webp",
    description: "Grows every unlocked floor's level by 6.8% in free upgrades",
  },
  pinkCropPowerhouse: {
    label: "Pink Crop Powerhouse",
    color: COLOR.amberMuted,
    image: "crits/feet/pinkCropPowerhouse.webp",
    description: "Spreads 137 free upgrades over the lowest-level floors",
  },
  pinkShortsSlant: {
    label: "Pink Shorts Slant",
    color: COLOR.amberMuted,
    image: "crits/feet/pinkShortsSlant.webp",
    description: "Pays 127 times this floor's upgrade price in cash",
  },
  ponytailVSplit: {
    label: "Ponytail V Split",
    color: COLOR.fastForwardBlue,
    image: "crits/feet/ponytailVSplit.webp",
    description: "Grows every unlocked floor's level by 6.9% in free upgrades",
  },
  rainbowShortsSprawl: {
    label: "Rainbow Shorts Sprawl",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/feet/rainbowShortsSprawl.webp",
    description: "Spreads 138 free upgrades over the lowest-level floors",
  },
  reclineRaise: {
    label: "Recline Raise",
    color: COLOR.amberMuted,
    image: "crits/feet/reclineRaise.webp",
    description: "Pays 128 times this floor's upgrade price in cash",
  },
  redheadCrossover: {
    label: "Redhead Crossover",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/redheadCrossover.webp",
    description: "Grows every unlocked floor's level by 7% in free upgrades",
  },
  redTankRaise: {
    label: "Red Tank Raise",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/feet/redTankRaise.webp",
    description: "Spreads 139 free upgrades over the lowest-level floors",
  },
  sidewaysSoles: {
    label: "Sideways Soles",
    color: COLOR.sameBoatCoral,
    image: "crits/feet/sidewaysSoles.webp",
    description: "Pays 129 times this floor's upgrade price in cash",
  },
  soleSandwich: {
    label: "Sole Sandwich",
    color: COLOR.coinGold,
    image: "crits/feet/soleSandwich.webp",
    description: "Grows every unlocked floor's level by 7.1% in free upgrades",
  },
  victoryVSoles: {
    label: "Victory V Soles",
    color: COLOR.starYellow,
    image: "crits/feet/victoryVSoles.webp",
    description: "Pays 131 times this floor's upgrade price in cash",
  },
  cherryBobBundle: {
    label: "Cherry Bob Bundle",
    color: COLOR.teamBuildingCoral,
    image: "crits/feet/cherryBobBundle.webp",
    description: "Grows every unlocked floor's level by 7.3% in free upgrades",
  },
  toeStackLean: {
    label: "Toe Stack Lean",
    color: COLOR.amberMuted,
    image: "crits/feet/toeStackLean.webp",
    description: "Spreads 142 free upgrades over the lowest-level floors",
  },
  armbandGoblinLounge: {
    label: "Armband Goblin Lounge",
    color: COLOR.bullMarketGreen,
    image: "crits/feet/armbandGoblinLounge.webp",
    description: "Pays 132 times this floor's upgrade price in cash",
  },
  cobaltCropGoblin: {
    label: "Cobalt Crop Goblin",
    color: COLOR.moneyGreen,
    image: "crits/feet/cobaltCropGoblin.webp",
    description: "Grows every unlocked floor's level by 7.4% in free upgrades",
  },
  goblinKneeSqueeze: {
    label: "Goblin Knee Squeeze",
    color: COLOR.moneyGreen,
    image: "crits/feet/goblinKneeSqueeze.webp",
    description: "Spreads 143 free upgrades over the lowest-level floors",
  },
  plumBunGoblin: {
    label: "Plum Bun Goblin",
    color: COLOR.disabledGray,
    image: "crits/feet/plumBunGoblin.webp",
    description: "Pays 133 times this floor's upgrade price in cash",
  },
  tealTopGoblin: {
    label: "Teal Top Goblin",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/feet/tealTopGoblin.webp",
    description: "Grows every unlocked floor's level by 7.5% in free upgrades",
  },
} as const satisfies Record<string, FeaturedCritData>;
