import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const FIGHTERS_CRITS = {
  blackBeltBiscuit: {
    label: "Black Belt Biscuit",
    color: COLOR.coinGold,
    image: "crits/fighters/blackBeltBiscuit.webp",
    description: "Cuts every price in this building by 15.7%",
  },
  dojoWink: {
    label: "Dojo Wink",
    color: COLOR.sameBoatCoral,
    image: "crits/fighters/dojoWink.webp",
    description: "Adds 12.6% of your total income",
  },
  boStaffBoots: {
    label: "Bo Staff Boots",
    color: COLOR.orange,
    image: "crits/fighters/boStaffBoots.webp",
    description: "Boosts every worker for 80s, counting as 2 extra workers",
  },
  karateKittyChop: {
    label: "Karate Kitty Chop",
    color: COLOR.orange,
    image: "crits/fighters/karateKittyChop.webp",
    description: "Repeats the crit above and below, 91% chance to keep spreading",
  },
  kendoKitten: {
    label: "Kendo Kitten",
    color: COLOR.nightShiftIndigo,
    image: "crits/fighters/kendoKitten.webp",
    description: "Cuts every price in this building by 15.8%",
  },
  kungFuWhiskers: {
    label: "Kung Fu Whiskers",
    color: COLOR.red,
    image: "crits/fighters/kungFuWhiskers.webp",
    description: "Adds 12.7% of your total income",
  },
  muayThaiMeow: {
    label: "Muay Thai Meow",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fighters/muayThaiMeow.webp",
    description: "Boosts every worker for 81s, counting as 2 extra workers",
  },
  jabTabby: {
    label: "Jab Tabby",
    color: COLOR.redActive,
    image: "crits/fighters/jabTabby.webp",
    description: "Repeats the crit above and below, 92% chance to keep spreading",
  },
  tigerTeepKick: {
    label: "Tiger Teep Kick",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fighters/tigerTeepKick.webp",
    description: "Cuts every price in this building by 15.9%",
  },
  ninjaPounce: {
    label: "Ninja Pounce",
    color: COLOR.sunshineGold,
    image: "crits/fighters/ninjaPounce.webp",
    description: "Adds 12.9% of your total income",
  },
  samuraiScratch: {
    label: "Samurai Scratch",
    color: COLOR.redActive,
    image: "crits/fighters/samuraiScratch.webp",
    description: "Boosts every worker for 83s, counting as 2 extra workers",
  },
  shogunWhiskers: {
    label: "Shogun Whiskers",
    color: COLOR.redActive,
    image: "crits/fighters/shogunWhiskers.webp",
    description: "Repeats the crit above and below, 94% chance to keep spreading",
  },
  senseiWhiskers: {
    label: "Sensei Whiskers",
    color: COLOR.teaBreakBrown,
    image: "crits/fighters/senseiWhiskers.webp",
    description: "Cuts every price in this building by 16.1%",
  },
  shaolinPurr: {
    label: "Shaolin Purr",
    color: COLOR.roundUpOrange,
    image: "crits/fighters/shaolinPurr.webp",
    description: "Adds 13% of your total income",
  },
  sumoChonk: {
    label: "Sumo Chonk",
    color: COLOR.springCleaningMint,
    image: "crits/fighters/sumoChonk.webp",
    description: "Boosts every worker for 84s, counting as 2 extra workers",
  },
  bellyBumpBanzai: {
    label: "Belly Bump Banzai",
    color: COLOR.coinGold,
    image: "crits/fighters/bellyBumpBanzai.webp",
    description: "Repeats the crit above and below, 95% chance to keep spreading",
  },
  tailWhipKick: {
    label: "Tail Whip Kick",
    color: COLOR.amberMuted,
    image: "crits/fighters/tailWhipKick.webp",
    description: "Cuts every price in this building by 16.3%",
  },
  tigerClawStance: {
    label: "Tiger Claw Stance",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fighters/tigerClawStance.webp",
    description: "Adds 13.2% of your total income",
  },
  goldenFurFury: {
    label: "Golden Fur Fury",
    color: COLOR.starYellow,
    image: "crits/fighters/goldenFurFury.webp",
    description: "Promotes 60.5% of this building's workers one perma tier",
  },
  spikyBlueCat: {
    label: "Spiky Blue Cat",
    color: COLOR.fastForwardBlue,
    image: "crits/fighters/spikyBlueCat.webp",
    description: "Promotes 83.5% of this floor's workers two perma tiers",
  },
  spikyManeKitty: {
    label: "Spiky Mane Kitty",
    color: COLOR.orange,
    image: "crits/fighters/spikyManeKitty.webp",
    description: "Promotes 61% of this building's workers one perma tier",
  },
  streetSquad: {
    label: "Street Squad",
    color: COLOR.teal,
    image: "crits/fighters/streetSquad.webp",
    description: "Repeats the crit on the floor below, 65% chance to keep falling",
  },
  divaTrio: {
    label: "Diva Trio",
    color: COLOR.gold,
    image: "crits/fighters/divaTrio.webp",
    description: "Two tier promotions and forty upgrades here",
  },
  squadGoals: {
    label: "Squad Goals",
    color: COLOR.fastForwardBlue,
    image: "crits/fighters/squadGoals.webp",
    description: "Cuts every price in this building by 11.2%",
  },
  hypeCrew: {
    label: "Hype Crew",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fighters/hypeCrew.webp",
    description: "Adds 10.7% of your total income",
  },
  girlGangBadge: {
    label: "Girl Gang Badge",
    color: COLOR.overflowBlue,
    image: "crits/fighters/girlGangBadge.webp",
    description: "Boosts every worker for 63s, counting as 1 extra worker",
  },
  leopardLineup: {
    label: "Leopard Lineup",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fighters/leopardLineup.webp",
    description: "Repeats the crit on the floor above, 66% chance to keep climbing",
  },
  bleacherCheer: {
    label: "Bleacher Cheer",
    color: COLOR.amberMuted,
    image: "crits/fighters/bleacherCheer.webp",
    description: "Adds 41.8% of your total income",
  },
  carpoolCool: {
    label: "Carpool Cool",
    color: COLOR.coffeeRunTeal,
    image: "crits/fighters/carpoolCool.webp",
    description: "Adds 41.9% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
