import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const FOOT_KISSES_CRITS = {
  armsWideKiss: {
    label: "Arms Wide Kiss",
    color: COLOR.coinGold,
    image: "crits/footKisses/armsWideKiss.webp",
    description: "Pays 22 times every unlocked floor's upgrade price in cash",
  },
  bicepBunKiss: {
    label: "Bicep Bun Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/bicepBunKiss.webp",
    description: "Spreads 57 free upgrades over the lowest-level floors",
  },
  blueBuzzCutKiss: {
    label: "Blue Buzz Cut Kiss",
    color: COLOR.amberMuted,
    image: "crits/footKisses/blueBuzzCutKiss.webp",
    description: "Pays 100 times this floor's upgrade price in cash",
  },
  blueManeSmooch: {
    label: "Blue Mane Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/blueManeSmooch.webp",
    description: "Spreads 58 free upgrades over the lowest-level floors",
  },
  bobCutSmooch: {
    label: "Bob Cut Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/bobCutSmooch.webp",
    description: "Grows this floor's level by 5.8% in free upgrades",
  },
  bothFeetPucker: {
    label: "Both Feet Pucker",
    color: COLOR.amberMuted,
    image: "crits/footKisses/bothFeetPucker.webp",
    description: "Spreads 59 free upgrades over the lowest-level floors",
  },
  closeUpKiss: {
    label: "Close Up Kiss",
    color: COLOR.amberMuted,
    image: "crits/footKisses/closeUpKiss.webp",
    description: "Grows this floor's level by 5.9% in free upgrades",
  },
  coralSoleSmooch: {
    label: "Coral Sole Smooch",
    color: COLOR.sameBoatCoral,
    image: "crits/footKisses/coralSoleSmooch.webp",
    description: "Spreads 60 free upgrades over the lowest-level floors",
  },
  crouchKiss: {
    label: "Crouch Kiss",
    color: COLOR.amberMuted,
    image: "crits/footKisses/crouchKiss.webp",
    description: "Spreads 61 free upgrades over the lowest-level floors",
  },
  curlyManeMwah: {
    label: "Curly Mane Mwah",
    color: COLOR.sameBoatCoral,
    image: "crits/footKisses/curlyManeMwah.webp",
    description: "Pays 104 times this floor's upgrade price in cash",
  },
  doubleBunPucker: {
    label: "Double Bun Pucker",
    color: COLOR.coinGold,
    image: "crits/footKisses/doubleBunPucker.webp",
    description: "Grows this floor's level by 6.1% in free upgrades",
  },
  fingerPointPeck: {
    label: "Finger Point Peck",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/footKisses/fingerPointPeck.webp",
    description: "Spreads 62 free upgrades over the lowest-level floors",
  },
  flatTopPucker: {
    label: "Flat Top Pucker",
    color: COLOR.sameBoatCoral,
    image: "crits/footKisses/flatTopPucker.webp",
    description: "Pays 105 times this floor's upgrade price in cash",
  },
  flexAndPucker: {
    label: "Flex And Pucker",
    color: COLOR.starYellow,
    image: "crits/footKisses/flexAndPucker.webp",
    description: "Grows this floor's level by 6.2% in free upgrades",
  },
  handOnHipKiss: {
    label: "Hand On Hip Kiss",
    color: COLOR.amberMuted,
    image: "crits/footKisses/handOnHipKiss.webp",
    description: "Grows this floor's level by 6.4% in free upgrades",
  },
  lemonArchKiss: {
    label: "Lemon Arch Kiss",
    color: COLOR.starYellow,
    image: "crits/footKisses/lemonArchKiss.webp",
    description: "Grows this floor's level by 13.5% in free upgrades",
  },
  messyBunMwah: {
    label: "Messy Bun Mwah",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/messyBunMwah.webp",
    description: "Spreads 121 free upgrades over the lowest-level floors",
  },
  muscleQueenSmooch: {
    label: "Muscle Queen Smooch",
    color: COLOR.teamBuildingCoral,
    image: "crits/footKisses/muscleQueenSmooch.webp",
    description: "Pays 111 times this floor's upgrade price in cash",
  },
  paleArchPeck: {
    label: "Pale Arch Peck",
    color: COLOR.sameBoatCoral,
    image: "crits/footKisses/paleArchPeck.webp",
    description: "Spreads 122 free upgrades over the lowest-level floors",
  },
  pinkSleevePucker: {
    label: "Pink Sleeve Pucker",
    color: COLOR.fastForwardBlue,
    image: "crits/footKisses/pinkSleevePucker.webp",
    description: "Spreads 124 free upgrades over the lowest-level floors",
  },
  pointDownPucker: {
    label: "Point Down Pucker",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/pointDownPucker.webp",
    description: "Spreads 125 free upgrades over the lowest-level floors",
  },
  redTopSmooch: {
    label: "Red Top Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/redTopSmooch.webp",
    description: "Spreads 126 free upgrades over the lowest-level floors",
  },
  salmonSoleSmooch: {
    label: "Salmon Sole Smooch",
    color: COLOR.sameBoatCoral,
    image: "crits/footKisses/salmonSoleSmooch.webp",
    description: "Grows this floor's level by 14.2% in free upgrades",
  },
  shortCropKiss: {
    label: "Short Crop Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/shortCropKiss.webp",
    description: "Pays 117 times this floor's upgrade price in cash",
  },
  sidePointSmooch: {
    label: "Side Point Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/sidePointSmooch.webp",
    description: "Grows this floor's level by 14.3% in free upgrades",
  },
  spikyHairSmooch: {
    label: "Spiky Hair Smooch",
    color: COLOR.teamBuildingCoral,
    image: "crits/footKisses/spikyHairSmooch.webp",
    description: "Pays 118 times this floor's upgrade price in cash",
  },
  tealCropKiss: {
    label: "Teal Crop Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/tealCropKiss.webp",
    description: "Spreads 129 free upgrades over the lowest-level floors",
  },
  thunderThighSmooch: {
    label: "Thunder Thigh Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/thunderThighSmooch.webp",
    description: "Pays 119 times this floor's upgrade price in cash",
  },
  waggingFingerKiss: {
    label: "Wagging Finger Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/waggingFingerKiss.webp",
    description: "Grows this floor's level by 14.6% in free upgrades",
  },
  whiteCropKiss: {
    label: "White Crop Kiss",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/footKisses/whiteCropKiss.webp",
    description: "Spreads 131 free upgrades over the lowest-level floors",
  },
  cuddleClanComfort: {
    label: "Cuddle Clan Comfort",
    color: COLOR.luckyCloverGreen,
    image: "crits/footKisses/cuddleClanComfort.webp",
    description: "Boosts every worker for 142s, counting as 3 extra workers",
  },
  leanInKiss: {
    label: "Lean In Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/footKisses/leanInKiss.webp",
    description: "Pays 109 times this floor's upgrade price in cash",
  },
} as const satisfies Record<string, FeaturedCritData>;
