import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const GYM_TEAMS_CRITS = {
  spottersWink: {
    label: "Spotter's Wink",
    color: COLOR.goldStandardAmber,
    image: "crits/gymTeams/spottersWink.webp",
    description: "Fifty payouts here and on the cheapest floor",
  },
  spotOn: {
    label: "Spot On",
    color: COLOR.red,
    image: "crits/gymTeams/spotOn.webp",
    description: "Boosts every worker for 21s",
  },
  tillTheCowsComeHome: {
    label: "Till the Cows Come Home",
    color: COLOR.chairGiveawayBrown,
    image: "crits/gymTeams/tillTheCowsComeHome.webp",
    description: "One tier promotion and eight upgrades here",
  },
  purrFectPair: {
    label: "Purr-fect Pair",
    color: COLOR.fastForwardBlue,
    image: "crits/gymTeams/purrFectPair.webp",
    description: "Two tier promotions and thirty-two upgrades here",
  },
  doubleTrouble: {
    label: "Double Trouble",
    color: COLOR.coinGold,
    image: "crits/gymTeams/doubleTrouble.webp",
    description: "Cuts every price in this building by 10.1%",
  },
  copycats: {
    label: "Copycats",
    color: COLOR.amberMuted,
    image: "crits/gymTeams/copycats.webp",
    description: "Adds 6.2% of your total income",
  },
  gymBuddyBudget: {
    label: "Gym Buddy Budget",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/gymTeams/gymBuddyBudget.webp",
    description: "Adds 24.3% of your total income",
  },
  backToBackBonus: {
    label: "Back to Back Bonus",
    color: COLOR.amberMuted,
    image: "crits/gymTeams/backToBackBonus.webp",
    description: "Fifty-eight instant payouts on this floor",
  },
  backupPlan: {
    label: "Backup Plan",
    color: COLOR.amberMuted,
    image: "crits/gymTeams/backupPlan.webp",
    description: "Fifty-five free upgrades on this floor",
  },
  pocketRocketPayday: {
    label: "Pocket Rocket Payday",
    color: COLOR.amberMuted,
    image: "crits/gymTeams/pocketRocketPayday.webp",
    description: "Sixty instant payouts on this floor",
  },
  shoulderToShoulderShares: {
    label: "Shoulder to Shoulder Shares",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/shoulderToShoulderShares.webp",
    description: "Adds 25.3% of your total income",
  },
  tealDeal: {
    label: "Teal Deal",
    color: COLOR.teaBreakBrown,
    image: "crits/gymTeams/tealDeal.webp",
    description: "Sixty-one instant payouts on this floor",
  },
  trioTrustFund: {
    label: "Trio Trust Fund",
    color: COLOR.overflowBlue,
    image: "crits/gymTeams/trioTrustFund.webp",
    description: "Adds 25.4% of your total income",
  },
  gingerPaycheck: {
    label: "Ginger Paycheck",
    color: COLOR.coinGold,
    image: "crits/gymTeams/gingerPaycheck.webp",
    description: "Eighty-four instant payouts on this floor",
  },
  threeWaySplit: {
    label: "Three Way Split",
    color: COLOR.fastForwardBlue,
    image: "crits/gymTeams/threeWaySplit.webp",
    description: "Adds 26.8% of your total income",
  },
  doubleKissDeposit: {
    label: "Double Kiss Deposit",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/gymTeams/doubleKissDeposit.webp",
    description: "Eighty-six instant payouts on this floor",
  },
  duoKissDividend: {
    label: "Duo Kiss Dividend",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/duoKissDividend.webp",
    description: "Eighty-seven instant payouts on this floor",
  },
  twinSmoochSavings: {
    label: "Twin Smooch Savings",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/twinSmoochSavings.webp",
    description: "Adds 77s of your company's income",
  },
  redheadHug: {
    label: "Redhead Hug",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/redheadHug.webp",
    description: "Spreads 13 free upgrades over the lowest-level floors",
  },
  blueBobNuzzle: {
    label: "Blue Bob Nuzzle",
    color: COLOR.summerSaleOrange,
    image: "crits/gymTeams/blueBobNuzzle.webp",
    description: "Pays 5 times the highest floor's upgrade price in cash",
  },
  curlyCuddle: {
    label: "Curly Cuddle",
    color: COLOR.amberMuted,
    image: "crits/gymTeams/curlyCuddle.webp",
    description: "Grows this floor's level by 8.1% in free upgrades",
  },
  pinkPowerhouses: {
    label: "Pink Powerhouses",
    color: COLOR.fullHouseCrimson,
    image: "crits/gymTeams/pinkPowerhouses.webp",
    description: "Pays 7 times this floor's upgrade price in cash",
  },
  armInArm: {
    label: "Arm In Arm",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/gymTeams/armInArm.webp",
    description: "Pays 139 times this floor's upgrade price in cash",
  },
  boxBraidBoost: {
    label: "Box Braid Boost",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/boxBraidBoost.webp",
    description: "Grows this floor's level by 18.2% in free upgrades",
  },
  braidWatch: {
    label: "Braid Watch",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/braidWatch.webp",
    description: "Spreads 150 free upgrades over the lowest-level floors",
  },
  headbandTwins: {
    label: "Headband Twins",
    color: COLOR.amberMuted,
    image: "crits/gymTeams/headbandTwins.webp",
    description: "Grows this floor's level by 18.4% in free upgrades",
  },
  hipNuzzle: {
    label: "Hip Nuzzle",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/hipNuzzle.webp",
    description: "Pays 142 times this floor's upgrade price in cash",
  },
  hitchhikerThumb: {
    label: "Hitchhiker Thumb",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/hitchhikerThumb.webp",
    description: "Grows this floor's level by 18.5% in free upgrades",
  },
  magentaHype: {
    label: "Magenta Hype",
    color: COLOR.amberMuted,
    image: "crits/gymTeams/magentaHype.webp",
    description: "Grows this floor's level by 18.6% in free upgrades",
  },
  neonTrimNudge: {
    label: "Neon Trim Nudge",
    color: COLOR.amberMuted,
    image: "crits/gymTeams/neonTrimNudge.webp",
    description: "Pays 144 times this floor's upgrade price in cash",
  },
  orangeAndLime: {
    label: "Orange And Lime",
    color: COLOR.summerSaleOrange,
    image: "crits/gymTeams/orangeAndLime.webp",
    description: "Grows this floor's level by 18.7% in free upgrades",
  },
  peekabooBuddy: {
    label: "Peekaboo Buddy",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/peekabooBuddy.webp",
    description: "Spreads 155 free upgrades over the lowest-level floors",
  },
  pinkTankPat: {
    label: "Pink Tank Pat",
    color: COLOR.fastForwardBlue,
    image: "crits/gymTeams/pinkTankPat.webp",
    description: "Pays 145 times this floor's upgrade price in cash",
  },
  gingerGnawers: {
    label: "Ginger Gnawers",
    color: COLOR.orange,
    image: "crits/gymTeams/gingerGnawers.webp",
    description: "Grows this floor's level by 26.8% in free upgrades",
  },
  gymBuddies: {
    label: "Gym Buddies",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/gymBuddies.webp",
    description: "Adds 44.7% of your total income",
  },
  spandexSquad: {
    label: "Spandex Squad",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/spandexSquad.webp",
    description: "Adds 45% of your total income",
  },
  spotterPair: {
    label: "Spotter Pair",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/spotterPair.webp",
    description: "Adds 45.1% of your total income",
  },
  sweatbandSmiles: {
    label: "Sweatband Smiles",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/sweatbandSmiles.webp",
    description: "Adds 45.2% of your total income",
  },
  synchronizedSquat: {
    label: "Synchronized Squat",
    color: COLOR.sameBoatCoral,
    image: "crits/gymTeams/synchronizedSquat.webp",
    description: "Adds 45.3% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
