import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const KISSES_AND_POUTS_CRITS = {
  butterflyKiss: {
    label: "Butterfly Kiss",
    color: COLOR.fastForwardBlue,
    image: "crits/kissesAndPouts/butterflyKiss.webp",
    description: "Unlocks the next 5 floors for free",
  },
  frenchKissFortune: {
    label: "French Kiss Fortune",
    color: COLOR.fastForwardBlue,
    image: "crits/kissesAndPouts/frenchKissFortune.webp",
    description: "Boosts every worker for 22s",
  },
  glossyPout: {
    label: "Glossy Pout",
    color: COLOR.sunshineGold,
    image: "crits/kissesAndPouts/glossyPout.webp",
    description: "Hires 1 free worker on this floor",
  },
  kissAndTell: {
    label: "Kiss And Tell",
    color: COLOR.peppermintPink,
    image: "crits/kissesAndPouts/kissAndTell.webp",
    description: "One tier promotion and fourteen upgrades on the lowest-level floor",
  },
  lipLockLoot: {
    label: "Lip Lock Loot",
    color: COLOR.sameBoatCoral,
    image: "crits/kissesAndPouts/lipLockLoot.webp",
    description: "Boosts every worker for 30s",
  },
  lipServiceLoot: {
    label: "Lip Service Loot",
    color: COLOR.red,
    image: "crits/kissesAndPouts/lipServiceLoot.webp",
    description: "Free office supplies for every unlocked floor",
  },
  lipstickLedger: {
    label: "Lipstick Ledger",
    color: COLOR.sunshineGold,
    image: "crits/kissesAndPouts/lipstickLedger.webp",
    description: "Repeats the crit on the floor below, 13% chance to keep falling",
  },
  mwahMoney: {
    label: "Mwah Money",
    color: COLOR.red,
    image: "crits/kissesAndPouts/mwahMoney.webp",
    description: "Adds 10.3% of your total income",
  },
  peckPortfolio: {
    label: "Peck Portfolio",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/kissesAndPouts/peckPortfolio.webp",
    description: "Unlocks the next 2 floors for free",
  },
  puckerUpPayout: {
    label: "Pucker Up Payout",
    color: COLOR.fastForwardBlue,
    image: "crits/kissesAndPouts/puckerUpPayout.webp",
    description: "Boosts every worker for 15s",
  },
  smoochStocks: {
    label: "Smooch Stocks",
    color: COLOR.sunshineGold,
    image: "crits/kissesAndPouts/smoochStocks.webp",
    description: "Cuts every price in this building by 2.4%",
  },
  stolenKissStash: {
    label: "Stolen Kiss Stash",
    color: COLOR.fullHouseCrimson,
    image: "crits/kissesAndPouts/stolenKissStash.webp",
    description: "Adds 5s of your company's income",
  },
  cheekPeckProfit: {
    label: "Cheek Peck Profit",
    color: COLOR.cyan,
    image: "crits/kissesAndPouts/cheekPeckProfit.webp",
    description: "Boosts every worker for 43s",
  },
  kissKissCash: {
    label: "Kiss Kiss Cash",
    color: COLOR.overflowBlue,
    image: "crits/kissesAndPouts/kissKissCash.webp",
    description: "Repeats the crit on the floor above, 62% chance to keep climbing",
  },
  lipBalmBonus: {
    label: "Lip Balm Bonus",
    color: COLOR.sameBoatCoral,
    image: "crits/kissesAndPouts/lipBalmBonus.webp",
    description: "Two tier promotions and thirty-three upgrades here",
  },
  poutPower: {
    label: "Pout Power",
    color: COLOR.gold,
    image: "crits/kissesAndPouts/poutPower.webp",
    description: "Adds 6.5% of your total income",
  },
  smackDabSavings: {
    label: "Smack Dab Savings",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPouts/smackDabSavings.webp",
    description: "Boosts every worker for 44s",
  },
  doubleCheekDividend: {
    label: "Double Cheek Dividend",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/kissesAndPouts/doubleCheekDividend.webp",
    description: "Cuts every price in this building by 19.5%",
  },
  pinkLipPact: {
    label: "Pink Lip Pact",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/kissesAndPouts/pinkLipPact.webp",
    description: "Adds 21.2% of your total income",
  },
  rubyLipRendezvous: {
    label: "Ruby Lip Rendezvous",
    color: COLOR.paydayEmerald,
    image: "crits/kissesAndPouts/rubyLipRendezvous.webp",
    description: "Cuts every price in this building by 19.9%",
  },
  scarletPucker: {
    label: "Scarlet Pucker",
    color: COLOR.moneyGreen,
    image: "crits/kissesAndPouts/scarletPucker.webp",
    description: "Boosts every worker for 156s, counting as 3 extra workers",
  },
  tripleSmoochSyndicate: {
    label: "Triple Smooch Syndicate",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/kissesAndPouts/tripleSmoochSyndicate.webp",
    description: "Boosts every worker for 159s, counting as 3 extra workers",
  },
  greenbackKiss: {
    label: "Greenback Kiss",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/kissesAndPouts/greenbackKiss.webp",
    description: "Fifty-one instant payouts on this floor",
  },
  kissAndMakeMoney: {
    label: "Kiss and Make Money",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/kissesAndPouts/kissAndMakeMoney.webp",
    description: "Fifty-three instant payouts on this floor",
  },
  braidedPuckers: {
    label: "Braided Puckers",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/kissesAndPouts/braidedPuckers.webp",
    description: "Spreads 18 free upgrades over this floor and the ones below",
  },
  loveBite: {
    label: "Love Bite",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPouts/loveBite.webp",
    description: "Spreads 20 free upgrades over this floor and the ones below",
  },
  lookalikeLipstick: {
    label: "Lookalike Lipstick",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPouts/lookalikeLipstick.webp",
    description: "Grows this floor's level by 8.5% in free upgrades",
  },
  necklineKiss: {
    label: "Neckline Kiss",
    color: COLOR.amberMuted,
    image: "crits/kissesAndPouts/necklineKiss.webp",
    description: "Spreads 22 free upgrades over this floor and the ones below",
  },
  lipstickTrail: {
    label: "Lipstick Trail",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPouts/lipstickTrail.webp",
    description: "Pays 36 times this floor's upgrade price in cash",
  },
  cheekSmoochDuo: {
    label: "Cheek Smooch Duo",
    color: COLOR.amberMuted,
    image: "crits/kissesAndPouts/cheekSmoochDuo.webp",
    description: "Spreads 36 free upgrades over the lowest-level floors",
  },
  ponytailPucker: {
    label: "Ponytail Pucker",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPouts/ponytailPucker.webp",
    description: "Grows this floor's level by 9.7% in free upgrades",
  },
  tongueTango: {
    label: "Tongue Tango",
    color: COLOR.starYellow,
    image: "crits/kissesAndPouts/tongueTango.webp",
    description: "Pays 67 times this floor's upgrade price in cash",
  },
} as const satisfies Record<string, FeaturedCritData>;
