import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const MATCHING_OUTFITS_CRITS = {
  ankleWrapDuo: {
    label: "Ankle Wrap Duo",
    color: COLOR.rainCheckBlue,
    image: "crits/matchingOutfits/ankleWrapDuo.webp",
    description: "Promotes 5% of this building's workers one perma tier",
  },
  bunTopSwimsuits: {
    label: "Bun Top Swimsuits",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/bunTopSwimsuits.webp",
    description: "Promotes 6.5% of this building's workers one perma tier",
  },
  cocoaCropTop: {
    label: "Cocoa Crop Top",
    color: COLOR.overflowBlue,
    image: "crits/matchingOutfits/cocoaCropTop.webp",
    description: "Promotes 41% of this floor's workers two perma tiers",
  },
  coralTopBobs: {
    label: "Coral Top Bobs",
    color: COLOR.rainCheckBlue,
    image: "crits/matchingOutfits/coralTopBobs.webp",
    description: "Promotes 10.5% of this building's workers one perma tier",
  },
  earringEnvy: {
    label: "Earring Envy",
    color: COLOR.springCleaningMint,
    image: "crits/matchingOutfits/earringEnvy.webp",
    description: "Promotes 12.5% of this building's workers one perma tier",
  },
  glossySuits: {
    label: "Glossy Suits",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/glossySuits.webp",
    description: "Promotes 13.5% of this building's workers one perma tier",
  },
  goldAndOnyx: {
    label: "Gold And Onyx",
    color: COLOR.rainCheckBlue,
    image: "crits/matchingOutfits/goldAndOnyx.webp",
    description: "Promotes 30% of this floor's workers two perma tiers",
  },
  goldHoops: {
    label: "Gold Hoops",
    color: COLOR.rainCheckBlue,
    image: "crits/matchingOutfits/goldHoops.webp",
    description: "Promotes 14% of this building's workers one perma tier",
  },
  goldRimGlow: {
    label: "Gold Rim Glow",
    color: COLOR.rainCheckBlue,
    image: "crits/matchingOutfits/goldRimGlow.webp",
    description: "Promotes 30.5% of this floor's workers two perma tiers",
  },
  greenShortsTwins: {
    label: "Green Shorts Twins",
    color: COLOR.overflowBlue,
    image: "crits/matchingOutfits/greenShortsTwins.webp",
    description: "Promotes 31% of this floor's workers two perma tiers",
  },
  greyLeggings: {
    label: "Grey Leggings",
    color: COLOR.overflowBlue,
    image: "crits/matchingOutfits/greyLeggings.webp",
    description: "Promotes 31.5% of this floor's workers two perma tiers",
  },
  legWarmers: {
    label: "Leg Warmers",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/legWarmers.webp",
    description: "Promotes 23% of this building's workers one perma tier",
  },
  lemonShorts: {
    label: "Lemon Shorts",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/lemonShorts.webp",
    description: "Promotes 43% of this floor's workers two perma tiers",
  },
  limePiping: {
    label: "Lime Piping",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/limePiping.webp",
    description: "Promotes 43.5% of this floor's workers two perma tiers",
  },
  limeSneaker: {
    label: "Lime Sneaker",
    color: COLOR.peppermintPink,
    image: "crits/matchingOutfits/limeSneaker.webp",
    description: "Promotes 24% of this building's workers one perma tier",
  },
  metallicBraDuo: {
    label: "Metallic Bra Duo",
    color: COLOR.disabledGray,
    image: "crits/matchingOutfits/metallicBraDuo.webp",
    description: "Promotes 44.5% of this floor's workers two perma tiers",
  },
  mintAndMarigold: {
    label: "Mint And Marigold",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/mintAndMarigold.webp",
    description: "Promotes 45% of this floor's workers two perma tiers",
  },
  mustardTights: {
    label: "Mustard Tights",
    color: COLOR.sunshineGold,
    image: "crits/matchingOutfits/mustardTights.webp",
    description: "Promotes 46% of this floor's workers two perma tiers",
  },
  neonLeggings: {
    label: "Neon Leggings",
    color: COLOR.peppermintPink,
    image: "crits/matchingOutfits/neonLeggings.webp",
    description: "Promotes 46.5% of this floor's workers two perma tiers",
  },
  orangeLeggings: {
    label: "Orange Leggings",
    color: COLOR.roundUpOrange,
    image: "crits/matchingOutfits/orangeLeggings.webp",
    description: "Promotes 47% of this floor's workers two perma tiers",
  },
  orangeTankBun: {
    label: "Orange Tank Bun",
    color: COLOR.rainCheckBlue,
    image: "crits/matchingOutfits/orangeTankBun.webp",
    description: "Promotes 47.5% of this floor's workers two perma tiers",
  },
  pinkHeadband: {
    label: "Pink Headband",
    color: COLOR.rainCheckBlue,
    image: "crits/matchingOutfits/pinkHeadband.webp",
    description: "Promotes 48% of this floor's workers two perma tiers",
  },
  plumAndMustard: {
    label: "Plum And Mustard",
    color: COLOR.springCleaningMint,
    image: "crits/matchingOutfits/plumAndMustard.webp",
    description: "Promotes 37% of this building's workers one perma tier",
  },
  purpleAndLime: {
    label: "Purple And Lime",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/matchingOutfits/purpleAndLime.webp",
    description: "Promotes 61% of this floor's workers two perma tiers",
  },
  rainbowAnklets: {
    label: "Rainbow Anklets",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/rainbowAnklets.webp",
    description: "Promotes 38% of this building's workers one perma tier",
  },
  rustAndNavy: {
    label: "Rust And Navy",
    color: COLOR.nightShiftIndigo,
    image: "crits/matchingOutfits/rustAndNavy.webp",
    description: "Promotes 39% of this building's workers one perma tier",
  },
  rustTopWristbands: {
    label: "Rust Top Wristbands",
    color: COLOR.overflowBlue,
    image: "crits/matchingOutfits/rustTopWristbands.webp",
    description: "Promotes 62.5% of this floor's workers two perma tiers",
  },
  tangerineShorts: {
    label: "Tangerine Shorts",
    color: COLOR.roundUpOrange,
    image: "crits/matchingOutfits/tangerineShorts.webp",
    description: "Promotes 42% of this building's workers one perma tier",
  },
  tealTrim: {
    label: "Teal Trim",
    color: COLOR.overflowBlue,
    image: "crits/matchingOutfits/tealTrim.webp",
    description: "Promotes 66% of this floor's workers two perma tiers",
  },
  tealWristbands: {
    label: "Teal Wristbands",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/tealWristbands.webp",
    description: "Promotes 43% of this building's workers one perma tier",
  },
  twinCrops: {
    label: "Twin Crops",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/twinCrops.webp",
    description: "Promotes 43.5% of this building's workers one perma tier",
  },
  twoToneTop: {
    label: "Two Tone Top",
    color: COLOR.peppermintPink,
    image: "crits/matchingOutfits/twoToneTop.webp",
    description: "Promotes 67% of this floor's workers two perma tiers",
  },
  zigzagLeotards: {
    label: "Zigzag Leotards",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/zigzagLeotards.webp",
    description: "Promotes 68.5% of this floor's workers two perma tiers",
  },
  zipSuitSisters: {
    label: "Zip Suit Sisters",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/zipSuitSisters.webp",
    description: "Promotes 69% of this floor's workers two perma tiers",
  },
  pinkStripeLeggings: {
    label: "Pink Stripe Leggings",
    color: COLOR.nightShiftIndigo,
    image: "crits/matchingOutfits/pinkStripeLeggings.webp",
    description: "Promotes 57.5% of this building's workers one perma tier",
  },
  tealUnitard: {
    label: "Teal Unitard",
    color: COLOR.coffeeRunTeal,
    image: "crits/matchingOutfits/tealUnitard.webp",
    description: "Promotes 59% of this building's workers one perma tier",
  },
  yellowSoleTrim: {
    label: "Yellow Sole Trim",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/yellowSoleTrim.webp",
    description: "Promotes 60% of this building's workers one perma tier",
  },
  yellowWaistband: {
    label: "Yellow Waistband",
    color: COLOR.fastForwardBlue,
    image: "crits/matchingOutfits/yellowWaistband.webp",
    description: "Promotes 83% of this floor's workers two perma tiers",
  },
  snowAndSeafoam: {
    label: "Snow And Seafoam",
    color: COLOR.overflowBlue,
    image: "crits/matchingOutfits/snowAndSeafoam.webp",
    description: "Promotes 63.5% of this floor's workers two perma tiers",
  },
} as const satisfies Record<string, FeaturedCritData>;
