import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const PINUPS_CRITS = {
  swimsuitSweetheart: {
    label: "Swimsuit Sweetheart",
    color: COLOR.coinGold,
    image: "crits/pinups/swimsuitSweetheart.webp",
    description: "Boosts every worker for 79s, counting as 2 extra workers",
  },
  hoopDreamDiva: {
    label: "Hoop Dream Diva",
    color: COLOR.summerSaleOrange,
    image: "crits/pinups/hoopDreamDiva.webp",
    description: "Repeats the crit above and below, 89% chance to keep spreading",
  },
  bathtubBullion: {
    label: "Bathtub Bullion",
    color: COLOR.mysticTeal,
    image: "crits/pinups/bathtubBullion.webp",
    description: "Pays 4 times the highest floor's upgrade price in cash",
  },
  bedroomBudget: {
    label: "Bedroom Budget",
    color: COLOR.sameBoatCoral,
    image: "crits/pinups/bedroomBudget.webp",
    description: "Spreads 80 free upgrades over the lowest-level floors",
  },
  burlesqueBonus: {
    label: "Burlesque Bonus",
    color: COLOR.fastForwardBlue,
    image: "crits/pinups/burlesqueBonus.webp",
    description: "Spreads 75 free upgrades over this floor and the ones below",
  },
  cashConfetti: {
    label: "Cash Confetti",
    color: COLOR.overflowBlue,
    image: "crits/pinups/cashConfetti.webp",
    description: "Pays 8 times every unlocked floor's upgrade price in cash",
  },
  cheekyCheckbook: {
    label: "Cheeky Checkbook",
    color: COLOR.amberMuted,
    image: "crits/pinups/cheekyCheckbook.webp",
    description: "Pays 12 times this floor's upgrade price in cash",
  },
  coffeeBreakGains: {
    label: "Coffee Break Gains",
    color: COLOR.doubleDownCrimson,
    image: "crits/pinups/coffeeBreakGains.webp",
    description: "Spreads 55 free upgrades over the lowest-level floors",
  },
  dowagerDividend: {
    label: "Dowager Dividend",
    color: COLOR.doubleDownCrimson,
    image: "crits/pinups/dowagerDividend.webp",
    description: "Grows every unlocked floor's level by 10% in free upgrades",
  },
  emeraldWindfall: {
    label: "Emerald Windfall",
    color: COLOR.summerSaleOrange,
    image: "crits/pinups/emeraldWindfall.webp",
    description: "Spreads 45 free upgrades over the lowest-level floors",
  },
  friskyBusiness: {
    label: "Frisky Business",
    color: COLOR.sameBoatCoral,
    image: "crits/pinups/friskyBusiness.webp",
    description: "Spreads 15 free upgrades over this floor and the ones below",
  },
  garterStash: {
    label: "Garter Stash",
    color: COLOR.headhunterRust,
    image: "crits/pinups/garterStash.webp",
    description: "Pays 6 times this floor's upgrade price in cash",
  },
  goldenHandcuffs: {
    label: "Golden Handcuffs",
    color: COLOR.nightShiftIndigo,
    image: "crits/pinups/goldenHandcuffs.webp",
    description: "Pays 8 times the highest floor's upgrade price in cash",
  },
  housekeepingHaul: {
    label: "Housekeeping Haul",
    color: COLOR.overflowBlue,
    image: "crits/pinups/housekeepingHaul.webp",
    description: "Spreads 35 free upgrades over the lowest-level floors",
  },
  hushMoney: {
    label: "Hush Money",
    color: COLOR.coinGold,
    image: "crits/pinups/hushMoney.webp",
    description: "Pays 25 times this floor's upgrade price in cash",
  },
  jackpotShowgirl: {
    label: "Jackpot Showgirl",
    color: COLOR.redActive,
    image: "crits/pinups/jackpotShowgirl.webp",
    description: "Pays 30 times the highest floor's upgrade price in cash",
  },
  lapOfLuxury: {
    label: "Lap Of Luxury",
    color: COLOR.gold,
    image: "crits/pinups/lapOfLuxury.webp",
    description: "Grows this floor's level by 12% in free upgrades",
  },
  leatherAndLucre: {
    label: "Leather And Lucre",
    color: COLOR.amberMuted,
    image: "crits/pinups/leatherAndLucre.webp",
    description: "Grows this floor's level by 18% in free upgrades",
  },
  maidInGold: {
    label: "Maid In Gold",
    color: COLOR.gold,
    image: "crits/pinups/maidInGold.webp",
    description: "Spreads 20 free upgrades over the lowest-level floors",
  },
  makeItRain: {
    label: "Make It Rain",
    color: COLOR.summerSaleOrange,
    image: "crits/pinups/makeItRain.webp",
    description: "Pays 4 times every unlocked floor's upgrade price in cash",
  },
  nightcapNestEgg: {
    label: "Nightcap Nest Egg",
    color: COLOR.coinGold,
    image: "crits/pinups/nightcapNestEgg.webp",
    description: "Spreads 120 free upgrades over the lowest-level floors",
  },
  pillowTalkProfits: {
    label: "Pillow Talk Profits",
    color: COLOR.sameBoatCoral,
    image: "crits/pinups/pillowTalkProfits.webp",
    description: "Spreads 50 free upgrades over this floor and the ones below",
  },
  roomService: {
    label: "Room Service",
    color: COLOR.gold,
    image: "crits/pinups/roomService.webp",
    description: "Spreads 10 free upgrades over the lowest-level floors",
  },
  silkAndStocks: {
    label: "Silk And Stocks",
    color: COLOR.redActive,
    image: "crits/pinups/silkAndStocks.webp",
    description: "Spreads 30 free upgrades over this floor and the ones below",
  },
  slotSiren: {
    label: "Slot Siren",
    color: COLOR.doubleDownCrimson,
    image: "crits/pinups/slotSiren.webp",
    description: "Pays 15 times the highest floor's upgrade price in cash",
  },
  sugarMama: {
    label: "Sugar Mama",
    color: COLOR.doubleDownCrimson,
    image: "crits/pinups/sugarMama.webp",
    description: "Grows every unlocked floor's level by 2% in free upgrades",
  },
  tipMe: {
    label: "Tip Me",
    color: COLOR.grandOpeningRose,
    image: "crits/pinups/tipMe.webp",
    description: "Pays 3 times this floor's upgrade price in cash",
  },
  vaultVixen: {
    label: "Vault Vixen",
    color: COLOR.gold,
    image: "crits/pinups/vaultVixen.webp",
    description: "Pays 50 times this floor's upgrade price in cash",
  },
  velvetAllowance: {
    label: "Velvet Allowance",
    color: COLOR.dressCodeGreen,
    image: "crits/pinups/velvetAllowance.webp",
    description: "Grows every unlocked floor's level by 6% in free upgrades",
  },
  bikiniLine: {
    label: "Bikini Line",
    color: COLOR.sameBoatCoral,
    image: "crits/pinups/bikiniLine.webp",
    description: "Adds 45.6% of your total income",
  },
  garterGirls: {
    label: "Garter Girls",
    color: COLOR.sameBoatCoral,
    image: "crits/pinups/garterGirls.webp",
    description: "Adds 45.7% of your total income",
  },
  goGoBoots: {
    label: "Go Go Boots",
    color: COLOR.gold,
    image: "crits/pinups/goGoBoots.webp",
    description: "Adds 45.8% of your total income",
  },
  heelClickers: {
    label: "Heel Clickers",
    color: COLOR.summerSaleOrange,
    image: "crits/pinups/heelClickers.webp",
    description: "Adds 45.9% of your total income",
  },
  hipPop: {
    label: "Hip Pop",
    color: COLOR.sameBoatCoral,
    image: "crits/pinups/hipPop.webp",
    description: "Adds 46% of your total income",
  },
  kneelAndPeek: {
    label: "Kneel And Peek",
    color: COLOR.sameBoatCoral,
    image: "crits/pinups/kneelAndPeek.webp",
    description: "Adds 46.1% of your total income",
  },
  lavenderLegs: {
    label: "Lavender Legs",
    color: COLOR.nightShiftIndigo,
    image: "crits/pinups/lavenderLegs.webp",
    description: "Adds 46.2% of your total income",
  },
  neonLocks: {
    label: "Neon Locks",
    color: COLOR.amberMuted,
    image: "crits/pinups/neonLocks.webp",
    description: "Adds 46.3% of your total income",
  },
  peekabooPair: {
    label: "Peekaboo Pair",
    color: COLOR.summerSaleOrange,
    image: "crits/pinups/peekabooPair.webp",
    description: "Adds 46.4% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
