import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const ROMANCE_CRITS = {
  airKissAssets: {
    label: "Air Kiss Assets",
    color: COLOR.headhunterRust,
    image: "crits/romance/airKissAssets.webp",
    description: "Arms the lowest-level floor's next click as an x5 crit",
  },
  blownKissBonus: {
    label: "Blown Kiss Bonus",
    color: COLOR.supplyRunTan,
    image: "crits/romance/blownKissBonus.webp",
    description: "Raises the lowest-level floor to the building's top level",
  },
  butterflyKiss: {
    label: "Butterfly Kiss",
    color: COLOR.fastForwardBlue,
    image: "crits/romance/butterflyKiss.webp",
    description: "Unlocks the next 5 floors for free",
  },
  crushCapital: {
    label: "Crush Capital",
    color: COLOR.teamBuildingCoral,
    image: "crits/romance/crushCapital.webp",
    description: "Cuts every price in this building by 2.3%",
  },
  cupidsCommission: {
    label: "Cupids Commission",
    color: COLOR.springCleaningMint,
    image: "crits/romance/cupidsCommission.webp",
    description: "Adds 45s of your company's income",
  },
  frenchKissFortune: {
    label: "French Kiss Fortune",
    color: COLOR.fastForwardBlue,
    image: "crits/romance/frenchKissFortune.webp",
    description: "Boosts every worker for 22s",
  },
  glossyPout: {
    label: "Glossy Pout",
    color: COLOR.sunshineGold,
    image: "crits/romance/glossyPout.webp",
    description: "Hires 1 free worker on this floor",
  },
  goodnightKissGains: {
    label: "Goodnight Kiss Gains",
    color: COLOR.fastForwardBlue,
    image: "crits/romance/goodnightKissGains.webp",
    description: "Repeats the crit above and below, 64% chance to keep spreading",
  },
  heartThrobHoldings: {
    label: "Heart Throb Holdings",
    color: COLOR.teaBreakBrown,
    image: "crits/romance/heartThrobHoldings.webp",
    description: "One tier promotion and nine upgrades here",
  },
  kissAndTell: {
    label: "Kiss And Tell",
    color: COLOR.peppermintPink,
    image: "crits/romance/kissAndTell.webp",
    description: "One tier promotion and fourteen upgrades on the lowest-level floor",
  },
  kissCamCashout: {
    label: "Kiss Cam Cashout",
    color: COLOR.coinGold,
    image: "crits/romance/kissCamCashout.webp",
    description: "Arms this floor's next click as an x5 crit",
  },
  kissingBoothBank: {
    label: "Kissing Booth Bank",
    color: COLOR.doubleDownCrimson,
    image: "crits/romance/kissingBoothBank.webp",
    description: "Raises alternating floors to the building's top level",
  },
  lipLockLoot: {
    label: "Lip Lock Loot",
    color: COLOR.sameBoatCoral,
    image: "crits/romance/lipLockLoot.webp",
    description: "Boosts every worker for 30s",
  },
  lipServiceLoot: {
    label: "Lip Service Loot",
    color: COLOR.red,
    image: "crits/romance/lipServiceLoot.webp",
    description: "Free office supplies for every unlocked floor",
  },
  lipstickLedger: {
    label: "Lipstick Ledger",
    color: COLOR.sunshineGold,
    image: "crits/romance/lipstickLedger.webp",
    description: "Repeats the crit on the floor below, 13% chance to keep falling",
  },
  loveLetterLedger: {
    label: "Love Letter Ledger",
    color: COLOR.coinGold,
    image: "crits/romance/loveLetterLedger.webp",
    description: "One tier promotion and six upgrades here",
  },
  mistletoeMargin: {
    label: "Mistletoe Margin",
    color: COLOR.coinGold,
    image: "crits/romance/mistletoeMargin.webp",
    description: "Cuts every price in this building by 1.4%",
  },
  mwahMoney: {
    label: "Mwah Money",
    color: COLOR.red,
    image: "crits/romance/mwahMoney.webp",
    description: "Adds 10.3% of your total income",
  },
  peckPortfolio: {
    label: "Peck Portfolio",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/peckPortfolio.webp",
    description: "Unlocks the next 2 floors for free",
  },
  puckerUpPayout: {
    label: "Pucker Up Payout",
    color: COLOR.fastForwardBlue,
    image: "crits/romance/puckerUpPayout.webp",
    description: "Boosts every worker for 15s",
  },
  rosyCheekReturns: {
    label: "Rosy Cheek Returns",
    color: COLOR.teaBreakBrown,
    image: "crits/romance/rosyCheekReturns.webp",
    description: "Hires a free manager on alternating floors",
  },
  sealedWithAKiss: {
    label: "Sealed With A Kiss",
    color: COLOR.springCleaningMint,
    image: "crits/romance/sealedWithAKiss.webp",
    description: "Repeats the crit on the floor above, 26% chance to keep climbing",
  },
  smittenSavings: {
    label: "Smitten Savings",
    color: COLOR.rainCheckBlue,
    image: "crits/romance/smittenSavings.webp",
    description: "One tier promotion and seven upgrades here",
  },
  smoochStocks: {
    label: "Smooch Stocks",
    color: COLOR.sunshineGold,
    image: "crits/romance/smoochStocks.webp",
    description: "Cuts every price in this building by 2.4%",
  },
  stolenKissStash: {
    label: "Stolen Kiss Stash",
    color: COLOR.fullHouseCrimson,
    image: "crits/romance/stolenKissStash.webp",
    description: "Adds 5s of your company's income",
  },
  sweetheartSurplus: {
    label: "Sweetheart Surplus",
    color: COLOR.chairGiveawayBrown,
    image: "crits/romance/sweetheartSurplus.webp",
    description: "Raises the lowest-level floor to the building's top level",
  },
  cheekPeckProfit: {
    label: "Cheek Peck Profit",
    color: COLOR.cyan,
    image: "crits/romance/cheekPeckProfit.webp",
    description: "Boosts every worker for 43s",
  },
  kissKissCash: {
    label: "Kiss Kiss Cash",
    color: COLOR.overflowBlue,
    image: "crits/romance/kissKissCash.webp",
    description: "Repeats the crit on the floor above, 62% chance to keep climbing",
  },
  lipBalmBonus: {
    label: "Lip Balm Bonus",
    color: COLOR.sameBoatCoral,
    image: "crits/romance/lipBalmBonus.webp",
    description: "Two tier promotions and thirty-three upgrades here",
  },
  lovebirdLoot: {
    label: "Lovebird Loot",
    color: COLOR.amberMuted,
    image: "crits/romance/lovebirdLoot.webp",
    description: "Cuts every price in this building by 10.2%",
  },
  poutPower: {
    label: "Pout Power",
    color: COLOR.gold,
    image: "crits/romance/poutPower.webp",
    description: "Adds 6.5% of your total income",
  },
  smackDabSavings: {
    label: "Smack Dab Savings",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/smackDabSavings.webp",
    description: "Boosts every worker for 44s",
  },
  scaleSmooch: {
    label: "Scale Smooch",
    color: COLOR.fullHouseCrimson,
    image: "crits/romance/scaleSmooch.webp",
    description: "Repeats the crit on the floor above, 86% chance to keep climbing",
  },
  hornLockKiss: {
    label: "Horn Lock Kiss",
    color: COLOR.fullHouseCrimson,
    image: "crits/romance/hornLockKiss.webp",
    description: "Cuts every price in this building by 18.1%",
  },
  fireAndFrostKiss: {
    label: "Fire And Frost Kiss",
    color: COLOR.headhunterRust,
    image: "crits/romance/fireAndFrostKiss.webp",
    description: "Adds 47s of your company's income",
  },
  sapphireEmberSmooch: {
    label: "Sapphire Ember Smooch",
    color: COLOR.overflowBlue,
    image: "crits/romance/sapphireEmberSmooch.webp",
    description: "Boosts every worker for 136s, counting as 3 extra workers",
  },
  fangKissFling: {
    label: "Fang Kiss Fling",
    color: COLOR.doubleDownCrimson,
    image: "crits/romance/fangKissFling.webp",
    description: "Boosts every worker for 140s, counting as 3 extra workers",
  },
  neckNibbleKiss: {
    label: "Neck Nibble Kiss",
    color: COLOR.chairGiveawayBrown,
    image: "crits/romance/neckNibbleKiss.webp",
    description: "Repeats the crit on the floor above, 88% chance to keep climbing",
  },
  baldAndBeautiful: {
    label: "Bald And Beautiful",
    color: COLOR.paydayEmerald,
    image: "crits/romance/baldAndBeautiful.webp",
    description: "Boosts every worker for 149s, counting as 3 extra workers",
  },
  battleScarBeau: {
    label: "Battle Scar Beau",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/battleScarBeau.webp",
    description: "Repeats the crit on the floor above, 92% chance to keep climbing",
  },
  boneBunBesties: {
    label: "Bone Bun Besties",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/boneBunBesties.webp",
    description: "Cuts every price in this building by 19.3%",
  },
  brunetteBliss: {
    label: "Brunette Bliss",
    color: COLOR.bullMarketGreen,
    image: "crits/romance/brunetteBliss.webp",
    description: "Adds 20.7% of your total income",
  },
  bunBraidBond: {
    label: "Bun Braid Bond",
    color: COLOR.bullMarketGreen,
    image: "crits/romance/bunBraidBond.webp",
    description: "Boosts every worker for 150s, counting as 3 extra workers",
  },
  buzzcutBesos: {
    label: "Buzzcut Besos",
    color: COLOR.luckyCloverGreen,
    image: "crits/romance/buzzcutBesos.webp",
    description: "Repeats the crit on the floor below, 92% chance to keep falling",
  },
  cheekToCheek: {
    label: "Cheek To Cheek",
    color: COLOR.disabledGray,
    image: "crits/romance/cheekToCheek.webp",
    description: "Cuts every price in this building by 19.4%",
  },
  cobaltCrush: {
    label: "Cobalt Crush",
    color: COLOR.bullMarketGreen,
    image: "crits/romance/cobaltCrush.webp",
    description: "Adds 20.8% of your total income",
  },
  cropTopCuddle: {
    label: "Crop Top Cuddle",
    color: COLOR.luckyCloverGreen,
    image: "crits/romance/cropTopCuddle.webp",
    description: "Boosts every worker for 151s, counting as 3 extra workers",
  },
  crownedCrush: {
    label: "Crowned Crush",
    color: COLOR.moneyGreen,
    image: "crits/romance/crownedCrush.webp",
    description: "Repeats the crit on the floor above, 93% chance to keep climbing",
  },
  doubleCheekDividend: {
    label: "Double Cheek Dividend",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/doubleCheekDividend.webp",
    description: "Cuts every price in this building by 19.5%",
  },
  flexAndPeck: {
    label: "Flex And Peck",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/flexAndPeck.webp",
    description: "Adds 20.9% of your total income",
  },
  frostHairFlirt: {
    label: "Frost Hair Flirt",
    color: COLOR.springCleaningMint,
    image: "crits/romance/frostHairFlirt.webp",
    description: "Boosts every worker for 152s, counting as 3 extra workers",
  },
  gildedEmbrace: {
    label: "Gilded Embrace",
    color: COLOR.threeOfAKindGreen,
    image: "crits/romance/gildedEmbrace.webp",
    description: "Repeats the crit on the floor below, 93% chance to keep falling",
  },
  goldChainSmooch: {
    label: "Gold Chain Smooch",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/goldChainSmooch.webp",
    description: "Cuts every price in this building by 19.6%",
  },
  goldenNecklaceNuzzle: {
    label: "Golden Necklace Nuzzle",
    color: COLOR.luckyCloverGreen,
    image: "crits/romance/goldenNecklaceNuzzle.webp",
    description: "Adds 21% of your total income",
  },
  goldHoopTrio: {
    label: "Gold Hoop Trio",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/goldHoopTrio.webp",
    description: "Boosts every worker for 153s, counting as 3 extra workers",
  },
  handInHandHustle: {
    label: "Hand In Hand Hustle",
    color: COLOR.disabledGray,
    image: "crits/romance/handInHandHustle.webp",
    description: "Repeats the crit on the floor above, 94% chance to keep climbing",
  },
  ironShoulderKiss: {
    label: "Iron Shoulder Kiss",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/ironShoulderKiss.webp",
    description: "Cuts every price in this building by 19.7%",
  },
  ivoryManeKiss: {
    label: "Ivory Mane Kiss",
    color: COLOR.dressCodeGreen,
    image: "crits/romance/ivoryManeKiss.webp",
    description: "Adds 21.1% of your total income",
  },
  leanInLoot: {
    label: "Lean In Loot",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/leanInLoot.webp",
    description: "Boosts every worker for 154s, counting as 3 extra workers",
  },
  limelightKiss: {
    label: "Limelight Kiss",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/limelightKiss.webp",
    description: "Repeats the crit on the floor below, 94% chance to keep falling",
  },
  mohawkMakeout: {
    label: "Mohawk Makeout",
    color: COLOR.springCleaningMint,
    image: "crits/romance/mohawkMakeout.webp",
    description: "Cuts every price in this building by 19.8%",
  },
  pinkLipPact: {
    label: "Pink Lip Pact",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/pinkLipPact.webp",
    description: "Adds 21.2% of your total income",
  },
  ponytailParade: {
    label: "Ponytail Parade",
    color: COLOR.luckyCloverGreen,
    image: "crits/romance/ponytailParade.webp",
    description: "Boosts every worker for 155s, counting as 3 extra workers",
  },
  rainbowHairHuddle: {
    label: "Rainbow Hair Huddle",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/rainbowHairHuddle.webp",
    description: "Repeats the crit on the floor above, 95% chance to keep climbing",
  },
  rubyLipRendezvous: {
    label: "Ruby Lip Rendezvous",
    color: COLOR.paydayEmerald,
    image: "crits/romance/rubyLipRendezvous.webp",
    description: "Cuts every price in this building by 19.9%",
  },
  sandwichSmooch: {
    label: "Sandwich Smooch",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/sandwichSmooch.webp",
    description: "Adds 21.3% of your total income",
  },
  scarletPucker: {
    label: "Scarlet Pucker",
    color: COLOR.moneyGreen,
    image: "crits/romance/scarletPucker.webp",
    description: "Boosts every worker for 156s, counting as 3 extra workers",
  },
  scarredSweetheart: {
    label: "Scarred Sweetheart",
    color: COLOR.luckyCloverGreen,
    image: "crits/romance/scarredSweetheart.webp",
    description: "Repeats the crit on the floor below, 95% chance to keep falling",
  },
  silverHairSnuggle: {
    label: "Silver Hair Snuggle",
    color: COLOR.luckyCloverGreen,
    image: "crits/romance/silverHairSnuggle.webp",
    description: "Boosts every worker for 157s, counting as 3 extra workers",
  },
  sixPackSmooch: {
    label: "Six Pack Smooch",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/sixPackSmooch.webp",
    description: "Cuts every price in this building by 20%",
  },
  spikySweetheart: {
    label: "Spiky Sweetheart",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/spikySweetheart.webp",
    description: "Adds 21.4% of your total income",
  },
  swoleMates: {
    label: "Swole Mates",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/swoleMates.webp",
    description: "Boosts every worker for 158s, counting as 3 extra workers",
  },
  tealBunBlush: {
    label: "Teal Bun Blush",
    color: COLOR.paydayEmerald,
    image: "crits/romance/tealBunBlush.webp",
    description: "Cuts every price in this building by 20.1%",
  },
  thirdWheelWindfall: {
    label: "Third Wheel Windfall",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/thirdWheelWindfall.webp",
    description: "Adds 21.5% of your total income",
  },
  tripleSmoochSyndicate: {
    label: "Triple Smooch Syndicate",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/tripleSmoochSyndicate.webp",
    description: "Boosts every worker for 159s, counting as 3 extra workers",
  },
  tuskTango: {
    label: "Tusk Tango",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/tuskTango.webp",
    description: "Cuts every price in this building by 20.2%",
  },
  tuskTouchKiss: {
    label: "Tusk Touch Kiss",
    color: COLOR.luckyCloverGreen,
    image: "crits/romance/tuskTouchKiss.webp",
    description: "Adds 21.6% of your total income",
  },
  tuskTrioTreaty: {
    label: "Tusk Trio Treaty",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/tuskTrioTreaty.webp",
    description: "Boosts every worker for 160s, counting as 3 extra workers",
  },
  crushHour: {
    label: "Crush Hour",
    color: COLOR.amberMuted,
    image: "crits/romance/crushHour.webp",
    description: "Cuts every price in this building by 20.9%",
  },
  earResistibleTrio: {
    label: "Ear Resistible Trio",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/earResistibleTrio.webp",
    description: "Adds 22.3% of your total income",
  },
  evergreenEmbrace: {
    label: "Evergreen Embrace",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/evergreenEmbrace.webp",
    description: "Boosts every worker for 167s, counting as 3 extra workers",
  },
  fangClub: {
    label: "Fang Club",
    color: COLOR.sameBoatCoral,
    image: "crits/romance/fangClub.webp",
    description: "Cuts every price in this building by 21%",
  },
  goldenBraidBond: {
    label: "Golden Braid Bond",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/goldenBraidBond.webp",
    description: "Adds 22.4% of your total income",
  },
  greenWithEnvy: {
    label: "Green With Envy",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/greenWithEnvy.webp",
    description: "Boosts every worker for 168s, counting as 3 extra workers",
  },
  moonbeamHuddle: {
    label: "Moonbeam Huddle",
    color: COLOR.teaBreakBrown,
    image: "crits/romance/moonbeamHuddle.webp",
    description: "Cuts every price in this building by 21.1%",
  },
  nightAndDay: {
    label: "Night And Day",
    color: COLOR.coinGold,
    image: "crits/romance/nightAndDay.webp",
    description: "Adds 22.5% of your total income",
  },
  topKnotTrio: {
    label: "Top Knot Trio",
    color: COLOR.amberMuted,
    image: "crits/romance/topKnotTrio.webp",
    description: "Boosts every worker for 169s, counting as 3 extra workers",
  },
  vestedInterest: {
    label: "Vested Interest",
    color: COLOR.amberMuted,
    image: "crits/romance/vestedInterest.webp",
    description: "Cuts every price in this building by 21.2%",
  },
  bridalCarryBonus: {
    label: "Bridal Carry Bonus",
    color: COLOR.amberMuted,
    image: "crits/romance/bridalCarryBonus.webp",
    description: "Thirty-eight instant payouts on this floor",
  },
  cheekToCheekCash: {
    label: "Cheek to Cheek Cash",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/cheekToCheekCash.webp",
    description: "Fifty instant payouts on this floor",
  },
  embraceEquity: {
    label: "Embrace Equity",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/embraceEquity.webp",
    description: "Fifty-three free upgrades on this floor",
  },
  eyeToEyeEarnings: {
    label: "Eye to Eye Earnings",
    color: COLOR.fastForwardBlue,
    image: "crits/romance/eyeToEyeEarnings.webp",
    description: "Adds 24.4% of your total income",
  },
  goblinSmoochSavings: {
    label: "Goblin Smooch Savings",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/goblinSmoochSavings.webp",
    description: "Adds 24.5% of your total income",
  },
  greenbackKiss: {
    label: "Greenback Kiss",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/greenbackKiss.webp",
    description: "Fifty-one instant payouts on this floor",
  },
  hugItOutIncome: {
    label: "Hug It Out Income",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/hugItOutIncome.webp",
    description: "Adds 24.6% of your total income",
  },
  kissAndMakeMoney: {
    label: "Kiss and Make Money",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/kissAndMakeMoney.webp",
    description: "Fifty-three instant payouts on this floor",
  },
  noseToNoseNetWorth: {
    label: "Nose to Nose Net Worth",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/noseToNoseNetWorth.webp",
    description: "Adds 24.7% of your total income",
  },
  orcKissAccount: {
    label: "Orc Kiss Account",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/orcKissAccount.webp",
    description: "Adds 24.8% of your total income",
  },
  silverFoxFund: {
    label: "Silver Fox Fund",
    color: COLOR.teaBreakBrown,
    image: "crits/romance/silverFoxFund.webp",
    description: "Adds 24.9% of your total income",
  },
  slowDanceDividend: {
    label: "Slow Dance Dividend",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/slowDanceDividend.webp",
    description: "Fifty-four instant payouts on this floor",
  },
  sweptAwaySalary: {
    label: "Swept Away Salary",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/sweptAwaySalary.webp",
    description: "Fifty-five instant payouts on this floor",
  },
  tangoTycoons: {
    label: "Tango Tycoons",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/tangoTycoons.webp",
    description: "Fifty-four free upgrades on this floor",
  },
  tieBreakerBonus: {
    label: "Tie Breaker Bonus",
    color: COLOR.amberMuted,
    image: "crits/romance/tieBreakerBonus.webp",
    description: "Fifty-six instant payouts on this floor",
  },
  twoStepTreasury: {
    label: "Two Step Treasury",
    color: COLOR.amberMuted,
    image: "crits/romance/twoStepTreasury.webp",
    description: "Adds 25% of your total income",
  },
  warmWelcomeWages: {
    label: "Warm Welcome Wages",
    color: COLOR.coinGold,
    image: "crits/romance/warmWelcomeWages.webp",
    description: "Fifty-seven instant payouts on this floor",
  },
  blondeGoblinBankroll: {
    label: "Blonde Goblin Bankroll",
    color: COLOR.threeOfAKindGreen,
    image: "crits/romance/blondeGoblinBankroll.webp",
    description: "Ninety-one instant payouts on this floor",
  },
  braidedGoblinBonus: {
    label: "Braided Goblin Bonus",
    color: COLOR.paydayEmerald,
    image: "crits/romance/braidedGoblinBonus.webp",
    description: "Ninety-two instant payouts on this floor",
  },
  emeraldKissEarnings: {
    label: "Emerald Kiss Earnings",
    color: COLOR.luckyCloverGreen,
    image: "crits/romance/emeraldKissEarnings.webp",
    description: "Adds 78s of your company's income",
  },
  goblinKissGold: {
    label: "Goblin Kiss Gold",
    color: COLOR.luckyCloverGreen,
    image: "crits/romance/goblinKissGold.webp",
    description: "Ninety-three instant payouts on this floor",
  },
  greenQueenGains: {
    label: "Green Queen Gains",
    color: COLOR.paydayEmerald,
    image: "crits/romance/greenQueenGains.webp",
    description: "Eleven free upgrades on the lowest-level floor",
  },
  hoopEarringHoldings: {
    label: "Hoop Earring Holdings",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/hoopEarringHoldings.webp",
    description: "Adds 79s of your company's income",
  },
  pointyEarPay: {
    label: "Pointy Ear Pay",
    color: COLOR.amberMuted,
    image: "crits/romance/pointyEarPay.webp",
    description: "Ninety-four instant payouts on this floor",
  },
  punkGoblinPayout: {
    label: "Punk Goblin Payout",
    color: COLOR.bullMarketGreen,
    image: "crits/romance/punkGoblinPayout.webp",
    description: "Ninety-five instant payouts on this floor",
  },
  swampSmoochStash: {
    label: "Swamp Smooch Stash",
    color: COLOR.paydayEmerald,
    image: "crits/romance/swampSmoochStash.webp",
    description: "Adds 80s of your company's income",
  },
  tuskKissTally: {
    label: "Tusk Kiss Tally",
    color: COLOR.bullMarketGreen,
    image: "crits/romance/tuskKissTally.webp",
    description: "Ninety-six instant payouts on this floor",
  },
  pompadourKiss: {
    label: "Pompadour Kiss",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/pompadourKiss.webp",
    description: "Pays 8 times this floor's upgrade price in cash",
  },
  armCandy: {
    label: "Arm Candy",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/armCandy.webp",
    description: "Grows this floor's level by 8.2% in free upgrades",
  },
  blondeBobKiss: {
    label: "Blonde Bob Kiss",
    color: COLOR.coinGold,
    image: "crits/romance/blondeBobKiss.webp",
    description: "Spreads 17 free upgrades over this floor and the ones below",
  },
  blueQuiffPeck: {
    label: "Blue Quiff Peck",
    color: COLOR.starYellow,
    image: "crits/romance/blueQuiffPeck.webp",
    description: "Pays 28 times this floor's upgrade price in cash",
  },
  blueGoblinTwins: {
    label: "Blue Goblin Twins",
    color: COLOR.moneyGreen,
    image: "crits/romance/blueGoblinTwins.webp",
    description: "Grows every unlocked floor's level by 2.5% in free upgrades",
  },
  buckleUp: {
    label: "Buckle Up",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/buckleUp.webp",
    description: "Spreads 54 free upgrades over this floor and the ones below",
  },
  coralCrush: {
    label: "Coral Crush",
    color: COLOR.sameBoatCoral,
    image: "crits/romance/coralCrush.webp",
    description: "Pays 29 times this floor's upgrade price in cash",
  },
  cottonCandyKiss: {
    label: "Cotton Candy Kiss",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/cottonCandyKiss.webp",
    description: "Grows this floor's level by 8.3% in free upgrades",
  },
  braidedPuckers: {
    label: "Braided Puckers",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/braidedPuckers.webp",
    description: "Spreads 18 free upgrades over this floor and the ones below",
  },
  fadeAndBraid: {
    label: "Fade and Braid",
    color: COLOR.teaBreakBrown,
    image: "crits/romance/fadeAndBraid.webp",
    description: "Pays 30 times this floor's upgrade price in cash",
  },
  flaxenBraidPeck: {
    label: "Flaxen Braid Peck",
    color: COLOR.amberMuted,
    image: "crits/romance/flaxenBraidPeck.webp",
    description: "Grows every unlocked floor's level by 2.6% in free upgrades",
  },
  giggleFit: {
    label: "Giggle Fit",
    color: COLOR.sameBoatCoral,
    image: "crits/romance/giggleFit.webp",
    description: "Spreads 19 free upgrades over this floor and the ones below",
  },
  goldilocks: {
    label: "Goldilocks",
    color: COLOR.chairGiveawayBrown,
    image: "crits/romance/goldilocks.webp",
    description: "Pays 31 times this floor's upgrade price in cash",
  },
  goblinLipPrint: {
    label: "Goblin Lip Print",
    color: COLOR.bullMarketGreen,
    image: "crits/romance/goblinLipPrint.webp",
    description: "Grows this floor's level by 8.4% in free upgrades",
  },
  loveBite: {
    label: "Love Bite",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/loveBite.webp",
    description: "Spreads 20 free upgrades over this floor and the ones below",
  },
  twinPonytails: {
    label: "Twin Ponytails",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/twinPonytails.webp",
    description: "Pays 32 times this floor's upgrade price in cash",
  },
  lemonCropTop: {
    label: "Lemon Crop Top",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/lemonCropTop.webp",
    description: "Grows every unlocked floor's level by 2.7% in free upgrades",
  },
  limeCrush: {
    label: "Lime Crush",
    color: COLOR.gold,
    image: "crits/romance/limeCrush.webp",
    description: "Spreads 21 free upgrades over this floor and the ones below",
  },
  rapunzelSmooch: {
    label: "Rapunzel Smooch",
    color: COLOR.amberMuted,
    image: "crits/romance/rapunzelSmooch.webp",
    description: "Pays 33 times this floor's upgrade price in cash",
  },
  lookalikeLipstick: {
    label: "Lookalike Lipstick",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/lookalikeLipstick.webp",
    description: "Grows this floor's level by 8.5% in free upgrades",
  },
  necklineKiss: {
    label: "Neckline Kiss",
    color: COLOR.amberMuted,
    image: "crits/romance/necklineKiss.webp",
    description: "Spreads 22 free upgrades over this floor and the ones below",
  },
  pinkBraidSmooch: {
    label: "Pink Braid Smooch",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/pinkBraidSmooch.webp",
    description: "Pays 34 times this floor's upgrade price in cash",
  },
  goblinCrush: {
    label: "Goblin Crush",
    color: COLOR.gold,
    image: "crits/romance/goblinCrush.webp",
    description: "Grows every unlocked floor's level by 2.8% in free upgrades",
  },
  smoochDelivery: {
    label: "Smooch Delivery",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/smoochDelivery.webp",
    description: "Spreads 21 free upgrades over the lowest-level floors",
  },
  snowcapSnuggle: {
    label: "Snowcap Snuggle",
    color: COLOR.amberMuted,
    image: "crits/romance/snowcapSnuggle.webp",
    description: "Pays 35 times this floor's upgrade price in cash",
  },
  tealBraids: {
    label: "Teal Braids",
    color: COLOR.amberMuted,
    image: "crits/romance/tealBraids.webp",
    description: "Grows this floor's level by 8.6% in free upgrades",
  },
  tomboySmooch: {
    label: "Tomboy Smooch",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romance/tomboySmooch.webp",
    description: "Spreads 22 free upgrades over the lowest-level floors",
  },
  lipstickTrail: {
    label: "Lipstick Trail",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/lipstickTrail.webp",
    description: "Pays 36 times this floor's upgrade price in cash",
  },
  blueBobSmooch: {
    label: "Blue Bob Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/blueBobSmooch.webp",
    description: "Pays 64 times this floor's upgrade price in cash",
  },
  braidsAndCurls: {
    label: "Braids And Curls",
    color: COLOR.supplyRunTan,
    image: "crits/romance/braidsAndCurls.webp",
    description: "Grows this floor's level by 9.5% in free upgrades",
  },
  cheekSmoochDuo: {
    label: "Cheek Smooch Duo",
    color: COLOR.amberMuted,
    image: "crits/romance/cheekSmoochDuo.webp",
    description: "Spreads 36 free upgrades over the lowest-level floors",
  },
  cottonCandyCuddle: {
    label: "Cotton Candy Cuddle",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/cottonCandyCuddle.webp",
    description: "Pays 65 times this floor's upgrade price in cash",
  },
  greenCheekLick: {
    label: "Green Cheek Lick",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/greenCheekLick.webp",
    description: "Grows this floor's level by 9.6% in free upgrades",
  },
  leggingsLeanIn: {
    label: "Leggings Lean In",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romance/leggingsLeanIn.webp",
    description: "Spreads 37 free upgrades over the lowest-level floors",
  },
  platinumPeck: {
    label: "Platinum Peck",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/platinumPeck.webp",
    description: "Pays 66 times this floor's upgrade price in cash",
  },
  ponytailPucker: {
    label: "Ponytail Pucker",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/ponytailPucker.webp",
    description: "Grows this floor's level by 9.7% in free upgrades",
  },
  tealBraidNuzzle: {
    label: "Teal Braid Nuzzle",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/tealBraidNuzzle.webp",
    description: "Spreads 38 free upgrades over the lowest-level floors",
  },
  tongueTango: {
    label: "Tongue Tango",
    color: COLOR.starYellow,
    image: "crits/romance/tongueTango.webp",
    description: "Pays 67 times this floor's upgrade price in cash",
  },
  buzzcutBraidBuddies: {
    label: "Buzzcut Braid Buddies",
    color: COLOR.amberMuted,
    image: "crits/romance/buzzcutBraidBuddies.webp",
    description: "Pays 68 times this floor's upgrade price in cash",
  },
  hoopEarringKiss: {
    label: "Hoop Earring Kiss",
    color: COLOR.sameBoatCoral,
    image: "crits/romance/hoopEarringKiss.webp",
    description: "Grows this floor's level by 9.9% in free upgrades",
  },
  pinkBraidSnuggle: {
    label: "Pink Braid Snuggle",
    color: COLOR.summerSaleOrange,
    image: "crits/romance/pinkBraidSnuggle.webp",
    description: "Spreads 40 free upgrades over the lowest-level floors",
  },
  violetWavesKiss: {
    label: "Violet Waves Kiss",
    color: COLOR.coinGold,
    image: "crits/romance/violetWavesKiss.webp",
    description: "Pays 69 times this floor's upgrade price in cash",
  },
} as const satisfies Record<string, FeaturedCritData>;
