import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const ROMANTIC_PORTRAITS_CRITS = {
  baldAndBeautiful: {
    label: "Bald And Beautiful",
    color: COLOR.paydayEmerald,
    image: "crits/romanticPortraits/baldAndBeautiful.webp",
    description: "Boosts every worker for 149s, counting as 3 extra workers",
  },
  battleScarBeau: {
    label: "Battle Scar Beau",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romanticPortraits/battleScarBeau.webp",
    description: "Repeats the crit on the floor above, 92% chance to keep climbing",
  },
  boneBunBesties: {
    label: "Bone Bun Besties",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romanticPortraits/boneBunBesties.webp",
    description: "Cuts every price in this building by 19.3%",
  },
  brunetteBliss: {
    label: "Brunette Bliss",
    color: COLOR.bullMarketGreen,
    image: "crits/romanticPortraits/brunetteBliss.webp",
    description: "Adds 20.7% of your total income",
  },
  bunBraidBond: {
    label: "Bun Braid Bond",
    color: COLOR.bullMarketGreen,
    image: "crits/romanticPortraits/bunBraidBond.webp",
    description: "Boosts every worker for 150s, counting as 3 extra workers",
  },
  buzzcutBesos: {
    label: "Buzzcut Besos",
    color: COLOR.luckyCloverGreen,
    image: "crits/romanticPortraits/buzzcutBesos.webp",
    description: "Repeats the crit on the floor below, 92% chance to keep falling",
  },
  flexAndPeck: {
    label: "Flex And Peck",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romanticPortraits/flexAndPeck.webp",
    description: "Adds 20.9% of your total income",
  },
  frostHairFlirt: {
    label: "Frost Hair Flirt",
    color: COLOR.springCleaningMint,
    image: "crits/romanticPortraits/frostHairFlirt.webp",
    description: "Boosts every worker for 152s, counting as 3 extra workers",
  },
  goldChainSmooch: {
    label: "Gold Chain Smooch",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romanticPortraits/goldChainSmooch.webp",
    description: "Cuts every price in this building by 19.6%",
  },
  goldHoopTrio: {
    label: "Gold Hoop Trio",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romanticPortraits/goldHoopTrio.webp",
    description: "Boosts every worker for 153s, counting as 3 extra workers",
  },
  ivoryManeKiss: {
    label: "Ivory Mane Kiss",
    color: COLOR.dressCodeGreen,
    image: "crits/romanticPortraits/ivoryManeKiss.webp",
    description: "Adds 21.1% of your total income",
  },
  mohawkMakeout: {
    label: "Mohawk Makeout",
    color: COLOR.springCleaningMint,
    image: "crits/romanticPortraits/mohawkMakeout.webp",
    description: "Cuts every price in this building by 19.8%",
  },
  ponytailParade: {
    label: "Ponytail Parade",
    color: COLOR.luckyCloverGreen,
    image: "crits/romanticPortraits/ponytailParade.webp",
    description: "Boosts every worker for 155s, counting as 3 extra workers",
  },
  scarredSweetheart: {
    label: "Scarred Sweetheart",
    color: COLOR.luckyCloverGreen,
    image: "crits/romanticPortraits/scarredSweetheart.webp",
    description: "Repeats the crit on the floor below, 95% chance to keep falling",
  },
  sixPackSmooch: {
    label: "Six Pack Smooch",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romanticPortraits/sixPackSmooch.webp",
    description: "Cuts every price in this building by 20%",
  },
  spikySweetheart: {
    label: "Spiky Sweetheart",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romanticPortraits/spikySweetheart.webp",
    description: "Adds 21.4% of your total income",
  },
  swoleMates: {
    label: "Swole Mates",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romanticPortraits/swoleMates.webp",
    description: "Boosts every worker for 158s, counting as 3 extra workers",
  },
  tealBunBlush: {
    label: "Teal Bun Blush",
    color: COLOR.paydayEmerald,
    image: "crits/romanticPortraits/tealBunBlush.webp",
    description: "Cuts every price in this building by 20.1%",
  },
  goldenBraidBond: {
    label: "Golden Braid Bond",
    color: COLOR.summerSaleOrange,
    image: "crits/romanticPortraits/goldenBraidBond.webp",
    description: "Adds 22.4% of your total income",
  },
  nightAndDay: {
    label: "Night And Day",
    color: COLOR.coinGold,
    image: "crits/romanticPortraits/nightAndDay.webp",
    description: "Adds 22.5% of your total income",
  },
  topKnotTrio: {
    label: "Top Knot Trio",
    color: COLOR.amberMuted,
    image: "crits/romanticPortraits/topKnotTrio.webp",
    description: "Boosts every worker for 169s, counting as 3 extra workers",
  },
  silverFoxFund: {
    label: "Silver Fox Fund",
    color: COLOR.teaBreakBrown,
    image: "crits/romanticPortraits/silverFoxFund.webp",
    description: "Adds 24.9% of your total income",
  },
  pompadourKiss: {
    label: "Pompadour Kiss",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/romanticPortraits/pompadourKiss.webp",
    description: "Pays 8 times this floor's upgrade price in cash",
  },
  blondeBobKiss: {
    label: "Blonde Bob Kiss",
    color: COLOR.coinGold,
    image: "crits/romanticPortraits/blondeBobKiss.webp",
    description: "Spreads 17 free upgrades over this floor and the ones below",
  },
  blueQuiffPeck: {
    label: "Blue Quiff Peck",
    color: COLOR.starYellow,
    image: "crits/romanticPortraits/blueQuiffPeck.webp",
    description: "Pays 28 times this floor's upgrade price in cash",
  },
  fadeAndBraid: {
    label: "Fade and Braid",
    color: COLOR.teaBreakBrown,
    image: "crits/romanticPortraits/fadeAndBraid.webp",
    description: "Pays 30 times this floor's upgrade price in cash",
  },
  flaxenBraidPeck: {
    label: "Flaxen Braid Peck",
    color: COLOR.amberMuted,
    image: "crits/romanticPortraits/flaxenBraidPeck.webp",
    description: "Grows every unlocked floor's level by 2.6% in free upgrades",
  },
  goldilocks: {
    label: "Goldilocks",
    color: COLOR.chairGiveawayBrown,
    image: "crits/romanticPortraits/goldilocks.webp",
    description: "Pays 31 times this floor's upgrade price in cash",
  },
  twinPonytails: {
    label: "Twin Ponytails",
    color: COLOR.summerSaleOrange,
    image: "crits/romanticPortraits/twinPonytails.webp",
    description: "Pays 32 times this floor's upgrade price in cash",
  },
  lemonCropTop: {
    label: "Lemon Crop Top",
    color: COLOR.summerSaleOrange,
    image: "crits/romanticPortraits/lemonCropTop.webp",
    description: "Grows every unlocked floor's level by 2.7% in free upgrades",
  },
  rapunzelSmooch: {
    label: "Rapunzel Smooch",
    color: COLOR.amberMuted,
    image: "crits/romanticPortraits/rapunzelSmooch.webp",
    description: "Pays 33 times this floor's upgrade price in cash",
  },
  pinkBraidSmooch: {
    label: "Pink Braid Smooch",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romanticPortraits/pinkBraidSmooch.webp",
    description: "Pays 34 times this floor's upgrade price in cash",
  },
  tealBraids: {
    label: "Teal Braids",
    color: COLOR.amberMuted,
    image: "crits/romanticPortraits/tealBraids.webp",
    description: "Grows this floor's level by 8.6% in free upgrades",
  },
  tomboySmooch: {
    label: "Tomboy Smooch",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/romanticPortraits/tomboySmooch.webp",
    description: "Spreads 22 free upgrades over the lowest-level floors",
  },
  blueBobSmooch: {
    label: "Blue Bob Smooch",
    color: COLOR.summerSaleOrange,
    image: "crits/romanticPortraits/blueBobSmooch.webp",
    description: "Pays 64 times this floor's upgrade price in cash",
  },
  braidsAndCurls: {
    label: "Braids And Curls",
    color: COLOR.supplyRunTan,
    image: "crits/romanticPortraits/braidsAndCurls.webp",
    description: "Grows this floor's level by 9.5% in free upgrades",
  },
  platinumPeck: {
    label: "Platinum Peck",
    color: COLOR.summerSaleOrange,
    image: "crits/romanticPortraits/platinumPeck.webp",
    description: "Pays 66 times this floor's upgrade price in cash",
  },
  hoopEarringKiss: {
    label: "Hoop Earring Kiss",
    color: COLOR.sameBoatCoral,
    image: "crits/romanticPortraits/hoopEarringKiss.webp",
    description: "Grows this floor's level by 9.9% in free upgrades",
  },
  violetWavesKiss: {
    label: "Violet Waves Kiss",
    color: COLOR.coinGold,
    image: "crits/romanticPortraits/violetWavesKiss.webp",
    description: "Pays 69 times this floor's upgrade price in cash",
  },
} as const satisfies Record<string, FeaturedCritData>;
