import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const SILVER_DUOS_CRITS = {
  ankleWrapDuo: {
    label: "Ankle Wrap Duo",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/ankleWrapDuo.webp",
    description: "Promotes 5% of this building's workers one perma tier",
  },
  baldAndBraided: {
    label: "Bald And Braided",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/baldAndBraided.webp",
    description: "Promotes 25% of this floor's workers two perma tiers",
  },
  baldBigGrins: {
    label: "Bald Big Grins",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/baldBigGrins.webp",
    description: "Promotes 20% of this building's workers one perma tier",
  },
  baldieBesties: {
    label: "Baldie Besties",
    color: COLOR.peppermintPink,
    image: "crits/silverDuos/baldieBesties.webp",
    description: "Promotes 60% of this floor's workers two perma tiers",
  },
  blondeBuzzcut: {
    label: "Blonde Buzzcut",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/blondeBuzzcut.webp",
    description: "Promotes 5.5% of this building's workers one perma tier",
  },
  blueLipsRecline: {
    label: "Blue Lips Recline",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/blueLipsRecline.webp",
    description: "Promotes 25.5% of this floor's workers two perma tiers",
  },
  blueLipstick: {
    label: "Blue Lipstick",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/blueLipstick.webp",
    description: "Promotes 55% of this building's workers one perma tier",
  },
  bobSquad: {
    label: "Bob Squad",
    color: COLOR.cyan,
    image: "crits/silverDuos/bobSquad.webp",
    description: "Promotes 40% of this floor's workers two perma tiers",
  },
  braidAndBob: {
    label: "Braid And Bob",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/braidAndBob.webp",
    description: "Promotes 6% of this building's workers one perma tier",
  },
  braidedPair: {
    label: "Braided Pair",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/braidedPair.webp",
    description: "Promotes 26% of this floor's workers two perma tiers",
  },
  bunAndBangs: {
    label: "Bun And Bangs",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/bunAndBangs.webp",
    description: "Promotes 80% of this building's workers one perma tier",
  },
  bunTopSwimsuits: {
    label: "Bun Top Swimsuits",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/bunTopSwimsuits.webp",
    description: "Promotes 6.5% of this building's workers one perma tier",
  },
  buzzAndBraid: {
    label: "Buzz And Braid",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/buzzAndBraid.webp",
    description: "Promotes 60.5% of this floor's workers two perma tiers",
  },
  candyHairCrew: {
    label: "Candy Hair Crew",
    color: COLOR.teal,
    image: "crits/silverDuos/candyHairCrew.webp",
    description: "Promotes 40.5% of this floor's workers two perma tiers",
  },
  chromeDomes: {
    label: "Chrome Domes",
    color: COLOR.teal,
    image: "crits/silverDuos/chromeDomes.webp",
    description: "Promotes 10% of this building's workers one perma tier",
  },
  cockyGrins: {
    label: "Cocky Grins",
    color: COLOR.springCleaningMint,
    image: "crits/silverDuos/cockyGrins.webp",
    description: "Promotes 7% of this building's workers one perma tier",
  },
  cocoaCropTop: {
    label: "Cocoa Crop Top",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/cocoaCropTop.webp",
    description: "Promotes 41% of this floor's workers two perma tiers",
  },
  coralPads: {
    label: "Coral Pads",
    color: COLOR.teamBuildingCoral,
    image: "crits/silverDuos/coralPads.webp",
    description: "Promotes 26.5% of this floor's workers two perma tiers",
  },
  coralTopBobs: {
    label: "Coral Top Bobs",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/coralTopBobs.webp",
    description: "Promotes 10.5% of this building's workers one perma tier",
  },
  crimsonTopSpread: {
    label: "Crimson Top Spread",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/crimsonTopSpread.webp",
    description: "Promotes 27% of this floor's workers two perma tiers",
  },
  crossedArms: {
    label: "Crossed Arms",
    color: COLOR.teal,
    image: "crits/silverDuos/crossedArms.webp",
    description: "Promotes 11% of this building's workers one perma tier",
  },
  crossedLegsChill: {
    label: "Crossed Legs Chill",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/crossedLegsChill.webp",
    description: "Promotes 27.5% of this floor's workers two perma tiers",
  },
  cueBallCuties: {
    label: "Cue Ball Cuties",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/cueBallCuties.webp",
    description: "Promotes 11.5% of this building's workers one perma tier",
  },
  curvyCuddle: {
    label: "Curvy Cuddle",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/curvyCuddle.webp",
    description: "Promotes 28% of this floor's workers two perma tiers",
  },
  cyanCuddle: {
    label: "Cyan Cuddle",
    color: COLOR.cyan,
    image: "crits/silverDuos/cyanCuddle.webp",
    description: "Promotes 12% of this building's workers one perma tier",
  },
  darkBobTwins: {
    label: "Dark Bob Twins",
    color: COLOR.peppermintPink,
    image: "crits/silverDuos/darkBobTwins.webp",
    description: "Promotes 28.5% of this floor's workers two perma tiers",
  },
  earringEnvy: {
    label: "Earring Envy",
    color: COLOR.springCleaningMint,
    image: "crits/silverDuos/earringEnvy.webp",
    description: "Promotes 12.5% of this building's workers one perma tier",
  },
  ebonyAndIvory: {
    label: "Ebony And Ivory",
    color: COLOR.peppermintPink,
    image: "crits/silverDuos/ebonyAndIvory.webp",
    description: "Promotes 29% of this floor's workers two perma tiers",
  },
  eclipseBuns: {
    label: "Eclipse Buns",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/eclipseBuns.webp",
    description: "Promotes 13% of this building's workers one perma tier",
  },
  frontRowFeet: {
    label: "Front Row Feet",
    color: COLOR.teal,
    image: "crits/silverDuos/frontRowFeet.webp",
    description: "Promotes 29.5% of this floor's workers two perma tiers",
  },
  glossySuits: {
    label: "Glossy Suits",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/glossySuits.webp",
    description: "Promotes 13.5% of this building's workers one perma tier",
  },
  goldAndOnyx: {
    label: "Gold And Onyx",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/goldAndOnyx.webp",
    description: "Promotes 30% of this floor's workers two perma tiers",
  },
  goldHoops: {
    label: "Gold Hoops",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/goldHoops.webp",
    description: "Promotes 14% of this building's workers one perma tier",
  },
  goldRimGlow: {
    label: "Gold Rim Glow",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/goldRimGlow.webp",
    description: "Promotes 30.5% of this floor's workers two perma tiers",
  },
  goldStudGrins: {
    label: "Gold Stud Grins",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/goldStudGrins.webp",
    description: "Promotes 14.5% of this building's workers one perma tier",
  },
  greenShortsTwins: {
    label: "Green Shorts Twins",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/greenShortsTwins.webp",
    description: "Promotes 31% of this floor's workers two perma tiers",
  },
  greyLeggings: {
    label: "Grey Leggings",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/greyLeggings.webp",
    description: "Promotes 31.5% of this floor's workers two perma tiers",
  },
  gymMat: {
    label: "Gym Mat",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/gymMat.webp",
    description: "Promotes 32% of this floor's workers two perma tiers",
  },
  hairGelPair: {
    label: "Hair Gel Pair",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/hairGelPair.webp",
    description: "Promotes 20.5% of this building's workers one perma tier",
  },
  handsPlanted: {
    label: "Hands Planted",
    color: COLOR.springCleaningMint,
    image: "crits/silverDuos/handsPlanted.webp",
    description: "Promotes 21% of this building's workers one perma tier",
  },
  highPonytailPair: {
    label: "High Ponytail Pair",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/highPonytailPair.webp",
    description: "Promotes 21.5% of this building's workers one perma tier",
  },
  indigoUpdo: {
    label: "Indigo Updo",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/indigoUpdo.webp",
    description: "Promotes 41.5% of this floor's workers two perma tiers",
  },
  jumboSoles: {
    label: "Jumbo Soles",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/jumboSoles.webp",
    description: "Promotes 22% of this building's workers one perma tier",
  },
  kneeHuggers: {
    label: "Knee Huggers",
    color: COLOR.springCleaningMint,
    image: "crits/silverDuos/kneeHuggers.webp",
    description: "Promotes 42% of this floor's workers two perma tiers",
  },
  kneesUp: {
    label: "Knees Up",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/kneesUp.webp",
    description: "Promotes 22.5% of this building's workers one perma tier",
  },
  leanBackLasses: {
    label: "Lean Back Lasses",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/leanBackLasses.webp",
    description: "Promotes 42.5% of this floor's workers two perma tiers",
  },
  legWarmers: {
    label: "Leg Warmers",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/legWarmers.webp",
    description: "Promotes 23% of this building's workers one perma tier",
  },
  lemonShorts: {
    label: "Lemon Shorts",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/lemonShorts.webp",
    description: "Promotes 43% of this floor's workers two perma tiers",
  },
  leotardLineup: {
    label: "Leotard Lineup",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/leotardLineup.webp",
    description: "Promotes 23.5% of this building's workers one perma tier",
  },
  limePiping: {
    label: "Lime Piping",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/limePiping.webp",
    description: "Promotes 43.5% of this floor's workers two perma tiers",
  },
  limeSneaker: {
    label: "Lime Sneaker",
    color: COLOR.peppermintPink,
    image: "crits/silverDuos/limeSneaker.webp",
    description: "Promotes 24% of this building's workers one perma tier",
  },
  longPonytailRecline: {
    label: "Long Ponytail Recline",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/longPonytailRecline.webp",
    description: "Promotes 44% of this floor's workers two perma tiers",
  },
  lotusLounge: {
    label: "Lotus Lounge",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/lotusLounge.webp",
    description: "Promotes 24.5% of this building's workers one perma tier",
  },
  metallicBraDuo: {
    label: "Metallic Bra Duo",
    color: COLOR.disabledGray,
    image: "crits/silverDuos/metallicBraDuo.webp",
    description: "Promotes 44.5% of this floor's workers two perma tiers",
  },
  midnightManeSprawl: {
    label: "Midnight Mane Sprawl",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/midnightManeSprawl.webp",
    description: "Promotes 25% of this building's workers one perma tier",
  },
  mintAndMarigold: {
    label: "Mint And Marigold",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/mintAndMarigold.webp",
    description: "Promotes 45% of this floor's workers two perma tiers",
  },
  mirrorPixies: {
    label: "Mirror Pixies",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/mirrorPixies.webp",
    description: "Promotes 25.5% of this building's workers one perma tier",
  },
  mohawkAndBraid: {
    label: "Mohawk And Braid",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/mohawkAndBraid.webp",
    description: "Promotes 45.5% of this floor's workers two perma tiers",
  },
  mohawkMates: {
    label: "Mohawk Mates",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/mohawkMates.webp",
    description: "Promotes 26% of this building's workers one perma tier",
  },
  mustardTights: {
    label: "Mustard Tights",
    color: COLOR.sunshineGold,
    image: "crits/silverDuos/mustardTights.webp",
    description: "Promotes 46% of this floor's workers two perma tiers",
  },
  neonBraids: {
    label: "Neon Braids",
    color: COLOR.sameBoatCoral,
    image: "crits/silverDuos/neonBraids.webp",
    description: "Promotes 26.5% of this building's workers one perma tier",
  },
  neonLeggings: {
    label: "Neon Leggings",
    color: COLOR.peppermintPink,
    image: "crits/silverDuos/neonLeggings.webp",
    description: "Promotes 46.5% of this floor's workers two perma tiers",
  },
  neonStripeLean: {
    label: "Neon Stripe Lean",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/neonStripeLean.webp",
    description: "Promotes 27% of this building's workers one perma tier",
  },
  orangeLeggings: {
    label: "Orange Leggings",
    color: COLOR.roundUpOrange,
    image: "crits/silverDuos/orangeLeggings.webp",
    description: "Promotes 47% of this floor's workers two perma tiers",
  },
  orangeTankBun: {
    label: "Orange Tank Bun",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/orangeTankBun.webp",
    description: "Promotes 47.5% of this floor's workers two perma tiers",
  },
  pinkHeadband: {
    label: "Pink Headband",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/pinkHeadband.webp",
    description: "Promotes 48% of this floor's workers two perma tiers",
  },
  pinkyLink: {
    label: "Pinky Link",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/pinkyLink.webp",
    description: "Promotes 48.5% of this floor's workers two perma tiers",
  },
  pintSizePals: {
    label: "Pint Size Pals",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/pintSizePals.webp",
    description: "Promotes 49% of this floor's workers two perma tiers",
  },
  pixieAndPlait: {
    label: "Pixie And Plait",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/pixieAndPlait.webp",
    description: "Promotes 49.5% of this floor's workers two perma tiers",
  },
  pixieAndPonytail: {
    label: "Pixie And Ponytail",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/pixieAndPonytail.webp",
    description: "Promotes 35% of this building's workers one perma tier",
  },
  pixieBesties: {
    label: "Pixie Besties",
    color: COLOR.springCleaningMint,
    image: "crits/silverDuos/pixieBesties.webp",
    description: "Promotes 35.5% of this building's workers one perma tier",
  },
  pixieCutPals: {
    label: "Pixie Cut Pals",
    color: COLOR.coffeeRunTeal,
    image: "crits/silverDuos/pixieCutPals.webp",
    description: "Promotes 36% of this building's workers one perma tier",
  },
  platinumPixie: {
    label: "Platinum Pixie",
    color: COLOR.springCleaningMint,
    image: "crits/silverDuos/platinumPixie.webp",
    description: "Promotes 36.5% of this building's workers one perma tier",
  },
  plumAndMustard: {
    label: "Plum And Mustard",
    color: COLOR.springCleaningMint,
    image: "crits/silverDuos/plumAndMustard.webp",
    description: "Promotes 37% of this building's workers one perma tier",
  },
  primAndProper: {
    label: "Prim And Proper",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/primAndProper.webp",
    description: "Promotes 37.5% of this building's workers one perma tier",
  },
  purpleAndLime: {
    label: "Purple And Lime",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/silverDuos/purpleAndLime.webp",
    description: "Promotes 61% of this floor's workers two perma tiers",
  },
  rainbowAnklets: {
    label: "Rainbow Anklets",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/rainbowAnklets.webp",
    description: "Promotes 38% of this building's workers one perma tier",
  },
  ravenHairPals: {
    label: "Raven Hair Pals",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/ravenHairPals.webp",
    description: "Promotes 61.5% of this floor's workers two perma tiers",
  },
  redBunBuddy: {
    label: "Red Bun Buddy",
    color: COLOR.springCleaningMint,
    image: "crits/silverDuos/redBunBuddy.webp",
    description: "Promotes 38.5% of this building's workers one perma tier",
  },
  ropeBraidRest: {
    label: "Rope Braid Rest",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/ropeBraidRest.webp",
    description: "Promotes 62% of this floor's workers two perma tiers",
  },
  rustAndNavy: {
    label: "Rust And Navy",
    color: COLOR.nightShiftIndigo,
    image: "crits/silverDuos/rustAndNavy.webp",
    description: "Promotes 39% of this building's workers one perma tier",
  },
  rustTopWristbands: {
    label: "Rust Top Wristbands",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/rustTopWristbands.webp",
    description: "Promotes 62.5% of this floor's workers two perma tiers",
  },
  shySitters: {
    label: "Shy Sitters",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/shySitters.webp",
    description: "Promotes 39.5% of this building's workers one perma tier",
  },
  sideBySide: {
    label: "Side By Side",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/sideBySide.webp",
    description: "Promotes 63% of this floor's workers two perma tiers",
  },
  slickBackDuo: {
    label: "Slick Back Duo",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/slickBackDuo.webp",
    description: "Promotes 40% of this building's workers one perma tier",
  },
  snowAndSeafoam: {
    label: "Snow And Seafoam",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/snowAndSeafoam.webp",
    description: "Promotes 63.5% of this floor's workers two perma tiers",
  },
  snowyBob: {
    label: "Snowy Bob",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/snowyBob.webp",
    description: "Promotes 40.5% of this building's workers one perma tier",
  },
  solesUpFront: {
    label: "Soles Up Front",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/solesUpFront.webp",
    description: "Promotes 64% of this floor's workers two perma tiers",
  },
  squeezeTight: {
    label: "Squeeze Tight",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/squeezeTight.webp",
    description: "Promotes 41% of this building's workers one perma tier",
  },
  stickerSisters: {
    label: "Sticker Sisters",
    color: COLOR.teal,
    image: "crits/silverDuos/stickerSisters.webp",
    description: "Promotes 64.5% of this floor's workers two perma tiers",
  },
  sweatbandSquad: {
    label: "Sweatband Squad",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/sweatbandSquad.webp",
    description: "Promotes 41.5% of this building's workers one perma tier",
  },
  sweatpantsSmiles: {
    label: "Sweatpants Smiles",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/sweatpantsSmiles.webp",
    description: "Promotes 65% of this floor's workers two perma tiers",
  },
  tangerineShorts: {
    label: "Tangerine Shorts",
    color: COLOR.roundUpOrange,
    image: "crits/silverDuos/tangerineShorts.webp",
    description: "Promotes 42% of this building's workers one perma tier",
  },
  tealPixie: {
    label: "Teal Pixie",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/tealPixie.webp",
    description: "Promotes 42.5% of this building's workers one perma tier",
  },
  tealTrim: {
    label: "Teal Trim",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/tealTrim.webp",
    description: "Promotes 66% of this floor's workers two perma tiers",
  },
  tealWristbands: {
    label: "Teal Wristbands",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/tealWristbands.webp",
    description: "Promotes 43% of this building's workers one perma tier",
  },
  twinBobTiptoes: {
    label: "Twin Bob Tiptoes",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/twinBobTiptoes.webp",
    description: "Promotes 66.5% of this floor's workers two perma tiers",
  },
  twinCrops: {
    label: "Twin Crops",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/twinCrops.webp",
    description: "Promotes 43.5% of this building's workers one perma tier",
  },
  twoToneTop: {
    label: "Two Tone Top",
    color: COLOR.peppermintPink,
    image: "crits/silverDuos/twoToneTop.webp",
    description: "Promotes 67% of this floor's workers two perma tiers",
  },
  undercutBraidDuo: {
    label: "Undercut Braid Duo",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/undercutBraidDuo.webp",
    description: "Promotes 44% of this building's workers one perma tier",
  },
  wideSitBraid: {
    label: "Wide Sit Braid",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/wideSitBraid.webp",
    description: "Promotes 67.5% of this floor's workers two perma tiers",
  },
  wristbandHuddle: {
    label: "Wristband Huddle",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/wristbandHuddle.webp",
    description: "Promotes 44.5% of this building's workers one perma tier",
  },
  yellowMane: {
    label: "Yellow Mane",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/yellowMane.webp",
    description: "Promotes 68% of this floor's workers two perma tiers",
  },
  zigzagLeotards: {
    label: "Zigzag Leotards",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/zigzagLeotards.webp",
    description: "Promotes 68.5% of this floor's workers two perma tiers",
  },
  zipSuitSisters: {
    label: "Zip Suit Sisters",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/zipSuitSisters.webp",
    description: "Promotes 69% of this floor's workers two perma tiers",
  },
  baldAndSidecut: {
    label: "Bald And Sidecut",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/baldAndSidecut.webp",
    description: "Promotes 69.5% of this floor's workers two perma tiers",
  },
  boxBraidsBlush: {
    label: "Box Braids Blush",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/boxBraidsBlush.webp",
    description: "Promotes 55.5% of this building's workers one perma tier",
  },
  buzzcutTwins: {
    label: "Buzzcut Twins",
    color: COLOR.rainCheckBlue,
    image: "crits/silverDuos/buzzcutTwins.webp",
    description: "Promotes 56% of this building's workers one perma tier",
  },
  jetBlackLocks: {
    label: "Jet Black Locks",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/jetBlackLocks.webp",
    description: "Promotes 56.5% of this building's workers one perma tier",
  },
  limePonytail: {
    label: "Lime Ponytail",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/limePonytail.webp",
    description: "Promotes 57% of this building's workers one perma tier",
  },
  mintGlowLounge: {
    label: "Mint Glow Lounge",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/mintGlowLounge.webp",
    description: "Promotes 80% of this floor's workers two perma tiers",
  },
  pinkStripeLeggings: {
    label: "Pink Stripe Leggings",
    color: COLOR.nightShiftIndigo,
    image: "crits/silverDuos/pinkStripeLeggings.webp",
    description: "Promotes 57.5% of this building's workers one perma tier",
  },
  plumLipsPower: {
    label: "Plum Lips Power",
    color: COLOR.springCleaningMint,
    image: "crits/silverDuos/plumLipsPower.webp",
    description: "Promotes 80.5% of this floor's workers two perma tiers",
  },
  sapphirePixie: {
    label: "Sapphire Pixie",
    color: COLOR.nightOwlIndigo,
    image: "crits/silverDuos/sapphirePixie.webp",
    description: "Promotes 58% of this building's workers one perma tier",
  },
  silverPonytailLean: {
    label: "Silver Ponytail Lean",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/silverPonytailLean.webp",
    description: "Promotes 81% of this floor's workers two perma tiers",
  },
  spikyCropBraid: {
    label: "Spiky Crop Braid",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/spikyCropBraid.webp",
    description: "Promotes 58.5% of this building's workers one perma tier",
  },
  tealStreakHair: {
    label: "Teal Streak Hair",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/tealStreakHair.webp",
    description: "Promotes 81.5% of this floor's workers two perma tiers",
  },
  tealUnitard: {
    label: "Teal Unitard",
    color: COLOR.coffeeRunTeal,
    image: "crits/silverDuos/tealUnitard.webp",
    description: "Promotes 59% of this building's workers one perma tier",
  },
  topKnotDuo: {
    label: "Top Knot Duo",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/topKnotDuo.webp",
    description: "Promotes 82% of this floor's workers two perma tiers",
  },
  turtleneckBob: {
    label: "Turtleneck Bob",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/turtleneckBob.webp",
    description: "Promotes 59.5% of this building's workers one perma tier",
  },
  wavyLocksLean: {
    label: "Wavy Locks Lean",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/wavyLocksLean.webp",
    description: "Promotes 82.5% of this floor's workers two perma tiers",
  },
  yellowSoleTrim: {
    label: "Yellow Sole Trim",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/yellowSoleTrim.webp",
    description: "Promotes 60% of this building's workers one perma tier",
  },
  yellowWaistband: {
    label: "Yellow Waistband",
    color: COLOR.fastForwardBlue,
    image: "crits/silverDuos/yellowWaistband.webp",
    description: "Promotes 83% of this floor's workers two perma tiers",
  },
  ballroomSnapshot: {
    label: "Ballroom Snapshot",
    color: COLOR.doubleDownCrimson,
    image: "crits/silverDuos/ballroomSnapshot.webp",
    description: "Adds 157s of your company's income",
  },
  bangsAndBlues: {
    label: "Bangs And Blues",
    color: COLOR.nightOwlIndigo,
    image: "crits/silverDuos/bangsAndBlues.webp",
    description: "Adds 158s of your company's income",
  },
  bigSmile: {
    label: "Big Smile",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/bigSmile.webp",
    description: "Adds 159s of your company's income",
  },
  blackTieBall: {
    label: "Black Tie Ball",
    color: COLOR.nightShiftIndigo,
    image: "crits/silverDuos/blackTieBall.webp",
    description: "Adds 160s of your company's income",
  },
  blueSteelRedHot: {
    label: "Blue Steel Red Hot",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/blueSteelRedHot.webp",
    description: "Adds 161s of your company's income",
  },
  bodiceBulk: {
    label: "Bodice Bulk",
    color: COLOR.nightOwlIndigo,
    image: "crits/silverDuos/bodiceBulk.webp",
    description: "Adds 162s of your company's income",
  },
  capeSwish: {
    label: "Cape Swish",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/capeSwish.webp",
    description: "Adds 164s of your company's income",
  },
  cocktailHour: {
    label: "Cocktail Hour",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/cocktailHour.webp",
    description: "Adds 165s of your company's income",
  },
  cuddleUp: {
    label: "Cuddle Up",
    color: COLOR.redActive,
    image: "crits/silverDuos/cuddleUp.webp",
    description: "Adds 166s of your company's income",
  },
  discoDiva: {
    label: "Disco Diva",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/discoDiva.webp",
    description: "Adds 167s of your company's income",
  },
  fuchsiaFortress: {
    label: "Fuchsia Fortress",
    color: COLOR.fullHouseCrimson,
    image: "crits/silverDuos/fuchsiaFortress.webp",
    description: "Adds 60.1% of your total income",
  },
  halterHuddle: {
    label: "Halter Huddle",
    color: COLOR.redActive,
    image: "crits/silverDuos/halterHuddle.webp",
    description: "Adds 60.2% of your total income",
  },
  helloGorgeous: {
    label: "Hello Gorgeous",
    color: COLOR.nightShiftIndigo,
    image: "crits/silverDuos/helloGorgeous.webp",
    description: "Adds 60.3% of your total income",
  },
  hugItOut: {
    label: "Hug It Out",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/hugItOut.webp",
    description: "Adds 60.4% of your total income",
  },
  jadeGiantess: {
    label: "Jade Giantess",
    color: COLOR.dressCodeGreen,
    image: "crits/silverDuos/jadeGiantess.webp",
    description: "Adds 60.5% of your total income",
  },
  jewelTones: {
    label: "Jewel Tones",
    color: COLOR.doubleDownCrimson,
    image: "crits/silverDuos/jewelTones.webp",
    description: "Adds 60.6% of your total income",
  },
  matchingTrims: {
    label: "Matching Trims",
    color: COLOR.nightOwlIndigo,
    image: "crits/silverDuos/matchingTrims.webp",
    description: "Adds 60.7% of your total income",
  },
  merlotMoment: {
    label: "Merlot Moment",
    color: COLOR.nightOwlIndigo,
    image: "crits/silverDuos/merlotMoment.webp",
    description: "Adds 60.8% of your total income",
  },
  mermaidTail: {
    label: "Mermaid Tail",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/mermaidTail.webp",
    description: "Adds 60.9% of your total income",
  },
  navyShimmer: {
    label: "Navy Shimmer",
    color: COLOR.nightOwlIndigo,
    image: "crits/silverDuos/navyShimmer.webp",
    description: "Adds 61% of your total income",
  },
  offTheShoulder: {
    label: "Off The Shoulder",
    color: COLOR.nightShiftIndigo,
    image: "crits/silverDuos/offTheShoulder.webp",
    description: "Adds 61.1% of your total income",
  },
  photoBooth: {
    label: "Photo Booth",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/photoBooth.webp",
    description: "Adds 61.2% of your total income",
  },
  pixieCuts: {
    label: "Pixie Cuts",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/pixieCuts.webp",
    description: "Adds 61.3% of your total income",
  },
  ponytailPride: {
    label: "Ponytail Pride",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/ponytailPride.webp",
    description: "Adds 61.4% of your total income",
  },
  poutAndPose: {
    label: "Pout And Pose",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/poutAndPose.webp",
    description: "Adds 61.5% of your total income",
  },
  powerBun: {
    label: "Power Bun",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/powerBun.webp",
    description: "Adds 61.6% of your total income",
  },
  promenade: {
    label: "Promenade",
    color: COLOR.nightShiftIndigo,
    image: "crits/silverDuos/promenade.webp",
    description: "Adds 61.7% of your total income",
  },
  proudGuardian: {
    label: "Proud Guardian",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/proudGuardian.webp",
    description: "Adds 61.8% of your total income",
  },
  purpleReign: {
    label: "Purple Reign",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/purpleReign.webp",
    description: "Adds 61.9% of your total income",
  },
  rainbowHem: {
    label: "Rainbow Hem",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/rainbowHem.webp",
    description: "Adds 62% of your total income",
  },
  sequinSqueeze: {
    label: "Sequin Squeeze",
    color: COLOR.coffeeRunTeal,
    image: "crits/silverDuos/sequinSqueeze.webp",
    description: "Adds 62.1% of your total income",
  },
  slenderSwirl: {
    label: "Slender Swirl",
    color: COLOR.fullHouseCrimson,
    image: "crits/silverDuos/slenderSwirl.webp",
    description: "Adds 62.3% of your total income",
  },
  smirkAndWink: {
    label: "Smirk And Wink",
    color: COLOR.nightShiftIndigo,
    image: "crits/silverDuos/smirkAndWink.webp",
    description: "Adds 62.4% of your total income",
  },
  sunnyCurls: {
    label: "Sunny Curls",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/sunnyCurls.webp",
    description: "Adds 62.5% of your total income",
  },
  tallAndTiny: {
    label: "Tall And Tiny",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/tallAndTiny.webp",
    description: "Adds 62.6% of your total income",
  },
  chinLift: {
    label: "Chin Lift",
    color: COLOR.nightOwlIndigo,
    image: "crits/silverDuos/chinLift.webp",
    description: "Adds 63.9% of your total income",
  },
  earringGlint: {
    label: "Earring Glint",
    color: COLOR.nightOwlIndigo,
    image: "crits/silverDuos/earringGlint.webp",
    description: "Adds 64% of your total income",
  },
  jadeAndNavy: {
    label: "Jade And Navy",
    color: COLOR.nightOwlIndigo,
    image: "crits/silverDuos/jadeAndNavy.webp",
    description: "Adds 64.1% of your total income",
  },
  pinkGloves: {
    label: "Pink Gloves",
    color: COLOR.overflowBlue,
    image: "crits/silverDuos/pinkGloves.webp",
    description: "Adds 64.2% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
