import { COLOR } from "../../palette";
import type { FeaturedCritData } from "./types";

export const WARHAMMER_CRITS = {
  emperorsFinest: {
    label: "Emperor's Finest",
    color: COLOR.blue,
    image: "crits/warhammer/emperorsFinest.webp",
    description: "Thirty-seven payouts on every unlocked floor",
  },
  eternalDuty: {
    label: "Eternal Duty",
    color: COLOR.red,
    image: "crits/warhammer/eternalDuty.webp",
    description: "Boosts every worker for 17s",
  },
  faithIsOurShield: {
    label: "Faith Is Our Shield",
    color: COLOR.blue,
    image: "crits/warhammer/faithIsOurShield.webp",
    description: "One tier promotion and twenty-four upgrades here",
  },
  fearNotThePsyker: {
    label: "Fear Not the Psyker",
    color: COLOR.purple,
    image: "crits/warhammer/fearNotThePsyker.webp",
    description:
      "Repeats the crit on the floor above, 37% chance to keep climbing",
  },
  neverSurrender: {
    label: "Never Surrender",
    color: COLOR.red,
    image: "crits/warhammer/neverSurrender.webp",
    description: "Arms this floor's next click as an x25 crit",
  },
  purge: {
    label: "Purge",
    color: COLOR.red,
    image: "crits/warhammer/purge.webp",
    description: "Arms this floor's next click as an x25 crit",
  },
  toTheSkies: {
    label: "To the Skies",
    color: COLOR.blue,
    image: "crits/warhammer/toTheSkies.webp",
    description: "Arms this floor's next click as an x25 crit",
  },
  whatAreYourOrders: {
    label: "What Are Your Orders",
    color: COLOR.blue,
    image: "crits/warhammer/whatAreYourOrders.webp",
    description: "Thirty free upgrades on the lowest-level floor",
  },
  emperorProvidesPurrfection: {
    label: "The Emperor Provides",
    color: COLOR.blue,
    image: "crits/warhammer/emperorProvidesPurrfection.webp",
    description: "Forty-four instant payouts on every unlocked floor",
  },
  fortyKOfGold: {
    label: "40K of Gold",
    color: COLOR.gold,
    image: "crits/warhammer/40kOfGold.webp",
    description: "Forty instant payouts on every unlocked floor",
  },
  chaoticTemptation: {
    label: "Chaotic Temptation",
    color: COLOR.red,
    image: "crits/warhammer/chaoticTemptation.webp",
    description: "Unlocks the next floor for free",
  },
  chaoticTemptation2: {
    label: "Chaos Allure",
    color: COLOR.purple,
    image: "crits/warhammer/chaoticTemptation2.webp",
    description: "Thirty-four free upgrades on this floor",
  },
  chaoticTemptation3: {
    label: "Chaos Romance",
    color: COLOR.orange,
    image: "crits/warhammer/chaoticTemptation3.webp",
    description: "Thirty-six free upgrades on every other floor",
  },
  chaoticTemptation4: {
    label: "Chaos Jackpot",
    color: COLOR.heavenlyGold,
    image: "crits/warhammer/chaoticTemptation4.webp",
    description: "Forty-two payouts from the highest-earning floor",
  },
  emperorsDividends: {
    label: "Praise The Emperor",
    color: COLOR.blue,
    image: "crits/warhammer/emperorsDividends.webp",
    description: "Raises alternating floors to the building's top level",
  },
  heavyHitter: {
    label: "Heavy Hitter",
    color: COLOR.redActive,
    image: "crits/warhammer/heavyHitter.webp",
    description: "Raises every floor to the building's top level",
  },
  iAmSpeed: {
    label: "I Am Speed",
    color: COLOR.cyan,
    image: "crits/warhammer/iAmSpeed.webp",
    description: "Boosts every worker for 32s",
  },
  neverSurrender2: {
    label: "Never Yield",
    color: COLOR.fullHouseCrimson,
    image: "crits/warhammer/neverSurrender2.webp",
    description: "Cuts every price in this building by 12.1%",
  },
  powerSword: {
    label: "Power Sword",
    color: COLOR.mysticTeal,
    image: "crits/warhammer/powerSword.webp",
    description: "Two tier promotions and eighteen upgrades here",
  },
  powerSword2: {
    label: "Sword of the Emperor",
    color: COLOR.heavenlyGold,
    image: "crits/warhammer/powerSword2.webp",
    description: "Hires 3 free workers and a manager on every unlocked floor",
  },
  cobaltJuggernaut: {
    label: "Cobalt Juggernaut",
    color: COLOR.nightOwlIndigo,
    image: "crits/warhammer/cobaltJuggernaut.webp",
    description:
      "Repeats the crit on the floor below, 10% chance to keep falling",
  },
  amberVisor: {
    label: "Amber Visor",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/amberVisor.webp",
    description: "Promotes 87% of this floor's workers two perma tiers",
  },
  blueGemPlate: {
    label: "Blue Gem Plate",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/blueGemPlate.webp",
    description: "Promotes 64.5% of this building's workers one perma tier",
  },
  bolterAim: {
    label: "Bolter Aim",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/bolterAim.webp",
    description: "Promotes 87.5% of this floor's workers two perma tiers",
  },
  bullseyePauldron: {
    label: "Bullseye Pauldron",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/bullseyePauldron.webp",
    description: "Promotes 65% of this building's workers one perma tier",
  },
  copperGrille: {
    label: "Copper Grille",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/copperGrille.webp",
    description: "Promotes 88% of this floor's workers two perma tiers",
  },
  crimsonStare: {
    label: "Crimson Stare",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/crimsonStare.webp",
    description: "Promotes 65.5% of this building's workers one perma tier",
  },
  crimsonWingHelm: {
    label: "Crimson Wing Helm",
    color: COLOR.rainCheckBlue,
    image: "crits/warhammer/crimsonWingHelm.webp",
    description: "Promotes 88.5% of this floor's workers two perma tiers",
  },
  crossedBarrels: {
    label: "Crossed Barrels",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/crossedBarrels.webp",
    description: "Promotes 66% of this building's workers one perma tier",
  },
  eagleCrest: {
    label: "Eagle Crest",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/eagleCrest.webp",
    description: "Promotes 89% of this floor's workers two perma tiers",
  },
  eagleHelm: {
    label: "Eagle Helm",
    color: COLOR.rainCheckBlue,
    image: "crits/warhammer/eagleHelm.webp",
    description: "Promotes 66.5% of this building's workers one perma tier",
  },
  eagleMedallion: {
    label: "Eagle Medallion",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/eagleMedallion.webp",
    description: "Promotes 89.5% of this floor's workers two perma tiers",
  },
  gemSkull: {
    label: "Gem Skull",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/gemSkull.webp",
    description: "Promotes 67% of this building's workers one perma tier",
  },
  goldCrestBulk: {
    label: "Gold Crest Bulk",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/goldCrestBulk.webp",
    description: "Promotes 100% of this floor's workers two perma tiers",
  },
  goldenWingHelm: {
    label: "Golden Wing Helm",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/goldenWingHelm.webp",
    description: "Adds 110s of your company's income",
  },
  goldFaceplate: {
    label: "Gold Faceplate",
    color: COLOR.rainCheckBlue,
    image: "crits/warhammer/goldFaceplate.webp",
    description: "Adds 111s of your company's income",
  },
  goldGlyphs: {
    label: "Gold Glyphs",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/goldGlyphs.webp",
    description: "Adds 112s of your company's income",
  },
  goldTrim: {
    label: "Gold Trim",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/goldTrim.webp",
    description: "Adds 35.1% of your total income",
  },
  greenVisor: {
    label: "Green Visor",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/greenVisor.webp",
    description: "Adds 35.2% of your total income",
  },
  gunwingSkull: {
    label: "Gunwing Skull",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/gunwingSkull.webp",
    description: "Adds 35.3% of your total income",
  },
  redChestPlate: {
    label: "Red Chest Plate",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/redChestPlate.webp",
    description: "Adds 35.4% of your total income",
  },
  redEyeGunner: {
    label: "Red Eye Gunner",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/redEyeGunner.webp",
    description: "Adds 35.5% of your total income",
  },
  redLaurelSkull: {
    label: "Red Laurel Skull",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/redLaurelSkull.webp",
    description: "Adds 35.6% of your total income",
  },
  redStarPauldron: {
    label: "Red Star Pauldron",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/redStarPauldron.webp",
    description: "Adds 35.7% of your total income",
  },
  redStripeHelm: {
    label: "Red Stripe Helm",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/redStripeHelm.webp",
    description: "Adds 35.8% of your total income",
  },
  shieldWings: {
    label: "Shield Wings",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/shieldWings.webp",
    description: "Adds 35.9% of your total income",
  },
  shoulderSigils: {
    label: "Shoulder Sigils",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/shoulderSigils.webp",
    description: "Adds 36% of your total income",
  },
  sigilChest: {
    label: "Sigil Chest",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/sigilChest.webp",
    description: "Adds 36.1% of your total income",
  },
  silverVisor: {
    label: "Silver Visor",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/silverVisor.webp",
    description: "Adds 36.2% of your total income",
  },
  silverWings: {
    label: "Silver Wings",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/silverWings.webp",
    description: "Adds 36.3% of your total income",
  },
  skullPauldron: {
    label: "Skull Pauldron",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/skullPauldron.webp",
    description: "Adds 36.4% of your total income",
  },
  snowCrest: {
    label: "Snow Crest",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/snowCrest.webp",
    description: "Adds 36.5% of your total income",
  },
  splitSkull: {
    label: "Split Skull",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/splitSkull.webp",
    description: "Adds 36.6% of your total income",
  },
  steelFaceplate: {
    label: "Steel Faceplate",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/steelFaceplate.webp",
    description: "Adds 36.7% of your total income",
  },
  tealVisor: {
    label: "Teal Visor",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/tealVisor.webp",
    description: "Adds 36.8% of your total income",
  },
  whiteRune: {
    label: "White Rune",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/whiteRune.webp",
    description: "Adds 36.9% of your total income",
  },
  wingedSkull: {
    label: "Winged Skull",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammer/wingedSkull.webp",
    description: "Adds 37% of your total income",
  },
  yellowVisor: {
    label: "Yellow Visor",
    color: COLOR.overflowBlue,
    image: "crits/warhammer/yellowVisor.webp",
    description: "Adds 37.2% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
