// event modules, part 7 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../gearTrainEvent";
import "../upstrikeEvent";
import "../creepingBarrageEvent";
import "../ballisticPendulumEvent";
import "../ringTawEvent";
import "../rainyWindowEvent";
import "../inflateEvent";
import "../domeFountainsEvent";
import "../bellRingersEvent";
import "../wetDogEvent";
import "../towerCraneEvent";
import "../beadLightningEvent";
import "../rockslideEvent";
import "../tightGroupEvent";
import "../jacksEvent";
import "../reflectingPoolEvent";
import "../pinArtEvent";
import "../twinWhirlpoolsEvent";
import "../hatchlingsEvent";
import "../butterfingersEvent";
import "../lockPickEvent";
import "../blacksmithEvent";
import "../seismicChargesEvent";
import "../skipShotsEvent";
import "../jumpingBeansEvent";
import "../swissCheeseEvent";
import "../explodedViewEvent";
import "../riptideEvent";
import "../fencingEvent";
import "../waterTowerEvent";
import "../barberPoleEvent";
import "../ionCannonEvent";
import "../claymoreEvent";
import "../pepperboxEvent";
import "../squashEvent";
import "../verticalHoldEvent";
import "../halftoneEvent";
import "../blowholeEvent";
import "../lamplighterEvent";
import "../fireBrigadeEvent";
import "../spokesEvent";
import "../thunderRingEvent";
import "../bottleRocketEvent";
import "../skeetEvent";
import "../tennisEvent";
import "../interlaceEvent";
import "../mirrorMirrorEvent";
import "../cottonCandyEvent";
import "../pelotonEvent";
import "../drinkingBirdEvent";
import "../laserDrillEvent";
import "../hairRaiserEvent";
import "../detonatorEvent";
import "../bulletRainEvent";
import "../bouncyCastleEvent";
import "../gameOfLifeEvent";
import "../labyrinthEvent";
import "../tidalBoreEvent";
import "../scrumEvent";
import "../goldRushEvent";
import "../suspensionBridgeEvent";
import "../redlineEvent";
import "../willowEvent";
import "../quickdrawEvent";
import "../galileanCannonEvent";
import "../chaosGameEvent";
import "../sandpileEvent";
import "../augerEvent";
import "../fountainShowEvent";
import "../spinningPlatesEvent";
import "../scoopsEvent";
import "../solarFurnaceEvent";
import "../lightningHandsEvent";
import "../ringOfFireEvent";
import "../bulletClashEvent";
import "../bouncePassEvent";
import "../oilStrikeEvent";
import "../harmonographEvent";
import "../quicksortEvent";
import "../capillaryEvent";
import "../battleTopsEvent";
import "../pneumaticTubesEvent";
import "../starPolygonEvent";
import "../voltSpiderEvent";
import "../orbitalDecayEvent";
import "../sprayAndPrayEvent";
import "../shuttleEvent";
import "../drillDuelEvent";
import "../rule30Event";
import "../airbrushEvent";
import "../calvingEvent";
import "../phoenixEvent";
import "../steamTrainEvent";
import "../lightSailEvent";
import "../inchwormEvent";
import "../criticalMassEvent";
import "../knifeThrowerEvent";
import "../compactorEvent";
import "../coreSampleEvent";
import "../foamPartyEvent";
import "../langtonsAntEvent";
import "../othelloEvent";
import "../gloopEvent";
import "../escapeVelocityEvent";
import "../sungrazerEvent";
import "../fractalTreeEvent";
import "../switchboardEvent";
import "../interferenceEvent";
import "../towerDefenseEvent";
import "../bounceWaveEvent";
import "../moleEvent";
import "../carWashEvent";
import "../dragonCurveEvent";
import "../lightsOutEvent";
import "../tumblerEvent";
import "../waggleDanceEvent";
import "../waterCycleEvent";
import "../foldingRuleEvent";
import "../arcSwarmEvent";
import "../lockstepEvent";
import "../hackySackEvent";
import "../woodwormEvent";
import "../graffitiEvent";
import "../voronoiEvent";
import "../percolationEvent";
import "../duneEvent";
import "../stringOfPearlsEvent";
import "../riverJugglerEvent";
import "../likeChargesEvent";
import "../collisionCourseEvent";
import "../targetWheelEvent";
import "../spinningHexagonEvent";
import "../beadDrillEvent";
import "../hydroseederEvent";
import "../mancalaEvent";
import "../breakthroughEvent";
import "../curvesEvent";
import "../archimedesScrewEvent";
import "../murmurationEvent";
import "../spiritBombEvent";
// the dev test bar's hooks
export { forceGearTrainEvent } from "../gearTrainEvent";
export { forceUpstrikeEvent } from "../upstrikeEvent";
export { forceCreepingBarrageEvent } from "../creepingBarrageEvent";
export { forceBallisticPendulumEvent } from "../ballisticPendulumEvent";
export { forceRingTawEvent } from "../ringTawEvent";
export { forceRainyWindowEvent } from "../rainyWindowEvent";
export { forceInflateEvent } from "../inflateEvent";
export { forceDomeFountainsEvent } from "../domeFountainsEvent";
export { forceBellRingersEvent } from "../bellRingersEvent";
export { forceWetDogEvent } from "../wetDogEvent";
export { forceTowerCraneEvent } from "../towerCraneEvent";
export { forceBeadLightningEvent } from "../beadLightningEvent";
export { forceRockslideEvent } from "../rockslideEvent";
export { forceTightGroupEvent } from "../tightGroupEvent";
export { forceJacksEvent } from "../jacksEvent";
export { forceReflectingPoolEvent } from "../reflectingPoolEvent";
export { forcePinArtEvent } from "../pinArtEvent";
export { forceTwinWhirlpoolsEvent } from "../twinWhirlpoolsEvent";
export { forceHatchlingsEvent } from "../hatchlingsEvent";
export { forceButterfingersEvent } from "../butterfingersEvent";
export { forceLockPickEvent } from "../lockPickEvent";
export { forceBlacksmithEvent } from "../blacksmithEvent";
export { forceSeismicChargesEvent } from "../seismicChargesEvent";
export { forceSkipShotsEvent } from "../skipShotsEvent";
export { forceJumpingBeansEvent } from "../jumpingBeansEvent";
export { forceSwissCheeseEvent } from "../swissCheeseEvent";
export { forceExplodedViewEvent } from "../explodedViewEvent";
export { forceRiptideEvent } from "../riptideEvent";
export { forceFencingEvent } from "../fencingEvent";
export { forceWaterTowerEvent } from "../waterTowerEvent";
export { forceBarberPoleEvent } from "../barberPoleEvent";
export { forceIonCannonEvent } from "../ionCannonEvent";
export { forceClaymoreEvent } from "../claymoreEvent";
export { forcePepperboxEvent } from "../pepperboxEvent";
export { forceSquashEvent } from "../squashEvent";
export { forceVerticalHoldEvent } from "../verticalHoldEvent";
export { forceHalftoneEvent } from "../halftoneEvent";
export { forceBlowholeEvent } from "../blowholeEvent";
export { forceLamplighterEvent } from "../lamplighterEvent";
export { forceFireBrigadeEvent } from "../fireBrigadeEvent";
export { forceSpokesEvent } from "../spokesEvent";
export { forceThunderRingEvent } from "../thunderRingEvent";
export { forceBottleRocketEvent } from "../bottleRocketEvent";
export { forceSkeetEvent } from "../skeetEvent";
export { forceTennisEvent } from "../tennisEvent";
export { forceInterlaceEvent } from "../interlaceEvent";
export { forceMirrorMirrorEvent } from "../mirrorMirrorEvent";
export { forceCottonCandyEvent } from "../cottonCandyEvent";
export { forcePelotonEvent } from "../pelotonEvent";
export { forceDrinkingBirdEvent } from "../drinkingBirdEvent";
export { forceLaserDrillEvent } from "../laserDrillEvent";
export { forceHairRaiserEvent } from "../hairRaiserEvent";
export { forceDetonatorEvent } from "../detonatorEvent";
export { forceBulletRainEvent } from "../bulletRainEvent";
export { forceBouncyCastleEvent } from "../bouncyCastleEvent";
export { forceGameOfLifeEvent } from "../gameOfLifeEvent";
export { forceLabyrinthEvent } from "../labyrinthEvent";
export { forceTidalBoreEvent } from "../tidalBoreEvent";
export { forceScrumEvent } from "../scrumEvent";
export { forceGoldRushEvent } from "../goldRushEvent";
export { forceSuspensionBridgeEvent } from "../suspensionBridgeEvent";
export { forceRedlineEvent } from "../redlineEvent";
export { forceWillowEvent } from "../willowEvent";
export { forceQuickdrawEvent } from "../quickdrawEvent";
export { forceGalileanCannonEvent } from "../galileanCannonEvent";
export { forceChaosGameEvent } from "../chaosGameEvent";
export { forceSandpileEvent } from "../sandpileEvent";
export { forceAugerEvent } from "../augerEvent";
export { forceFountainShowEvent } from "../fountainShowEvent";
export { forceSpinningPlatesEvent } from "../spinningPlatesEvent";
export { forceScoopsEvent } from "../scoopsEvent";
export { forceSolarFurnaceEvent } from "../solarFurnaceEvent";
export { forceLightningHandsEvent } from "../lightningHandsEvent";
export { forceRingOfFireEvent } from "../ringOfFireEvent";
export { forceBulletClashEvent } from "../bulletClashEvent";
export { forceBouncePassEvent } from "../bouncePassEvent";
export { forceOilStrikeEvent } from "../oilStrikeEvent";
export { forceHarmonographEvent } from "../harmonographEvent";
export { forceQuicksortEvent } from "../quicksortEvent";
export { forceCapillaryEvent } from "../capillaryEvent";
export { forceBattleTopsEvent } from "../battleTopsEvent";
export { forcePneumaticTubesEvent } from "../pneumaticTubesEvent";
export { forceStarPolygonEvent } from "../starPolygonEvent";
export { forceVoltSpiderEvent } from "../voltSpiderEvent";
export { forceOrbitalDecayEvent } from "../orbitalDecayEvent";
export { forceSprayAndPrayEvent } from "../sprayAndPrayEvent";
export { forceShuttleEvent } from "../shuttleEvent";
export { forceDrillDuelEvent } from "../drillDuelEvent";
export { forceRule30Event } from "../rule30Event";
export { forceAirbrushEvent } from "../airbrushEvent";
export { forceCalvingEvent } from "../calvingEvent";
export { forcePhoenixEvent } from "../phoenixEvent";
export { forceSteamTrainEvent } from "../steamTrainEvent";
export { forceLightSailEvent } from "../lightSailEvent";
export { forceInchwormEvent } from "../inchwormEvent";
export { forceCriticalMassEvent } from "../criticalMassEvent";
export { forceKnifeThrowerEvent } from "../knifeThrowerEvent";
export { forceCompactorEvent } from "../compactorEvent";
export { forceCoreSampleEvent } from "../coreSampleEvent";
export { forceFoamPartyEvent } from "../foamPartyEvent";
export { forceLangtonsAntEvent } from "../langtonsAntEvent";
export { forceOthelloEvent } from "../othelloEvent";
export { forceGloopEvent } from "../gloopEvent";
export { forceEscapeVelocityEvent } from "../escapeVelocityEvent";
export { forceSungrazerEvent } from "../sungrazerEvent";
export { forceFractalTreeEvent } from "../fractalTreeEvent";
export { forceSwitchboardEvent } from "../switchboardEvent";
export { forceInterferenceEvent } from "../interferenceEvent";
export { forceTowerDefenseEvent } from "../towerDefenseEvent";
export { forceBounceWaveEvent } from "../bounceWaveEvent";
export { forceMoleEvent } from "../moleEvent";
export { forceCarWashEvent } from "../carWashEvent";
export { forceDragonCurveEvent } from "../dragonCurveEvent";
export { forceLightsOutEvent } from "../lightsOutEvent";
export { forceTumblerEvent } from "../tumblerEvent";
export { forceWaggleDanceEvent } from "../waggleDanceEvent";
export { forceWaterCycleEvent } from "../waterCycleEvent";
export { forceFoldingRuleEvent } from "../foldingRuleEvent";
export { forceArcSwarmEvent } from "../arcSwarmEvent";
export { forceLockstepEvent } from "../lockstepEvent";
export { forceHackySackEvent } from "../hackySackEvent";
export { forceWoodwormEvent } from "../woodwormEvent";
export { forceGraffitiEvent } from "../graffitiEvent";
export { forceVoronoiEvent } from "../voronoiEvent";
export { forcePercolationEvent } from "../percolationEvent";
export { forceDuneEvent } from "../duneEvent";
export { forceStringOfPearlsEvent } from "../stringOfPearlsEvent";
export { forceRiverJugglerEvent } from "../riverJugglerEvent";
export { forceLikeChargesEvent } from "../likeChargesEvent";
export { forceCollisionCourseEvent } from "../collisionCourseEvent";
export { forceTargetWheelEvent } from "../targetWheelEvent";
export { forceSpinningHexagonEvent } from "../spinningHexagonEvent";
export { forceBeadDrillEvent } from "../beadDrillEvent";
export { forceHydroseederEvent } from "../hydroseederEvent";
export { forceMancalaEvent } from "../mancalaEvent";
export { forceBreakthroughEvent } from "../breakthroughEvent";
export { forceCurvesEvent } from "../curvesEvent";
export { forceArchimedesScrewEvent } from "../archimedesScrewEvent";
export { forceMurmurationEvent } from "../murmurationEvent";
export { forceSpiritBombEvent } from "../spiritBombEvent";
