// event modules, part 3 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../matryoshkaEvent";
import "../salmonRunEvent";
import "../moonTideEvent";
import "../candyFlossEvent";
import "../figureSkaterEvent";
import "../tripwireEvent";
import "../sunriseEvent";
import "../rallyEvent";
import "../ignitionEvent";
import "../tridentEvent";
import "../crawlEvent";
import "../carpetBombingEvent";
import "../timeBombEvent";
import "../bunkerBusterEvent";
import "../grenadeTossEvent";
import "../depthChargesEvent";
import "../firingSquadEvent";
import "../akimboEvent";
import "../flakBarrageEvent";
import "../sniperNestEvent";
import "../rewindEvent";
import "../morseCodeEvent";
import "../stadiumWaveEvent";
import "../knightsTourEvent";
import "../lavaLampEvent";
import "../dominoesEvent";
import "../inkblotEvent";
import "../softServeEvent";
import "../dollarSignEvent";
import "../mobiusEvent";
import "../swissRollEvent";
import "../dodgeballEvent";
import "../congaLineEvent";
import "../spinningTopEvent";
import "../gobblerEvent";
import "../majoretteEvent";
import "../hulaHoopEvent";
import "../calligraphyEvent";
import "../snakeCharmerEvent";
import "../plateSpinnerEvent";
import "../ferrisWheelEvent";
import "../bucketBrigadeEvent";
import "../skyLanternsEvent";
import "../engraverEvent";
import "../xRayEvent";
import "../laserLassoEvent";
import "../hexRingEvent";
import "../portcullisEvent";
import "../keyholeEvent";
import "../defibrillatorEvent";
import "../circuitBoardEvent";
import "../mjolnirEvent";
import "../arcFlashEvent";
import "../fourCornersEvent";
import "../boltWheelEvent";
import "../minefieldEvent";
import "../cannonadeEvent";
import "../stickyBombsEvent";
import "../crossblastEvent";
import "../mortarEvent";
import "../flashbangEvent";
import "../sentryTurretEvent";
import "../shotgunEvent";
import "../bossFightEvent";
import "../gunshipEvent";
import "../bulletTimeEvent";
import "../flechettesEvent";
import "../radarEvent";
import "../bingoEvent";
import "../laneHopperEvent";
import "../simonSaysEvent";
import "../equalizerEvent";
import "../loadingBarEvent";
import "../diceRollEvent";
import "../mandalaEvent";
import "../zenGardenEvent";
import "../accordionEvent";
import "../fizzEvent";
import "../soundwaveEvent";
import "../taffyEvent";
import "../dripPaintingEvent";
import "../mothsEvent";
import "../curlingEvent";
import "../clotheslineEvent";
import "../balloonPopEvent";
import "../spinBottleEvent";
import "../skyWriterEvent";
import "../goldPanEvent";
import "../bulldozerEvent";
import "../koiPondEvent";
import "../pipeOrganEvent";
import "../antTrailEvent";
import "../hotAirBalloonEvent";
import "../lensFlareEvent";
import "../tightropeEvent";
import "../neonSignEvent";
import "../lightCageEvent";
import "../stairwayEvent";
import "../beaconsEvent";
import "../anvilCrawlerEvent";
import "../neuronsEvent";
import "../bottledBoltEvent";
import "../thunderbirdEvent";
import "../sparkGapEvent";
import "../staticShockEvent";
import "../rocketJumpEvent";
import "../torpedoesEvent";
import "../airstrikeEvent";
import "../dambusterEvent";
import "../airburstEvent";
import "../bombPinwheelEvent";
import "../bulletCurtainEvent";
import "../trickShotEvent";
import "../railShooterEvent";
import "../skeetShootEvent";
import "../tripleTapEvent";
import "../tommyGunEvent";
import "../sweeperEvent";
import "../clawMachineEvent";
import "../lotteryEvent";
import "../wordGuessEvent";
import "../memoryMatchEvent";
import "../ticTacToeEvent";
import "../revCounterEvent";
import "../sluiceEvent";
import "../foundryEvent";
import "../jetStreamEvent";
import "../moatEvent";
import "../seepEvent";
import "../meanderEvent";
import "../waltzEvent";
import "../gyroscopeEvent";
import "../dragonflyEvent";
import "../ringTossEvent";
import "../slipstreamEvent";
import "../sheetMusicEvent";
import "../leafBlowerEvent";
import "../loomEvent";
import "../highDiveEvent";
import "../sowerEvent";
// the dev test bar's hooks
export { forceMatryoshkaEvent } from "../matryoshkaEvent";
export { forceSalmonRunEvent } from "../salmonRunEvent";
export { forceMoonTideEvent } from "../moonTideEvent";
export { forceCandyFlossEvent } from "../candyFlossEvent";
export { forceFigureSkaterEvent } from "../figureSkaterEvent";
export { forceTripwireEvent } from "../tripwireEvent";
export { forceSunriseEvent } from "../sunriseEvent";
export { forceRallyEvent } from "../rallyEvent";
export { forceIgnitionEvent } from "../ignitionEvent";
export { forceTridentEvent } from "../tridentEvent";
export { forceCrawlEvent } from "../crawlEvent";
export { forceCarpetBombingEvent } from "../carpetBombingEvent";
export { forceTimeBombEvent } from "../timeBombEvent";
export { forceBunkerBusterEvent } from "../bunkerBusterEvent";
export { forceGrenadeTossEvent } from "../grenadeTossEvent";
export { forceDepthChargesEvent } from "../depthChargesEvent";
export { forceFiringSquadEvent } from "../firingSquadEvent";
export { forceAkimboEvent } from "../akimboEvent";
export { forceFlakBarrageEvent } from "../flakBarrageEvent";
export { forceSniperNestEvent } from "../sniperNestEvent";
export { forceRewindEvent } from "../rewindEvent";
export { forceMorseCodeEvent } from "../morseCodeEvent";
export { forceStadiumWaveEvent } from "../stadiumWaveEvent";
export { forceKnightsTourEvent } from "../knightsTourEvent";
export { forceLavaLampEvent } from "../lavaLampEvent";
export { forceDominoesEvent } from "../dominoesEvent";
export { forceInkblotEvent } from "../inkblotEvent";
export { forceSoftServeEvent } from "../softServeEvent";
export { forceDollarSignEvent } from "../dollarSignEvent";
export { forceMobiusEvent } from "../mobiusEvent";
export { forceSwissRollEvent } from "../swissRollEvent";
export { forceDodgeballEvent } from "../dodgeballEvent";
export { forceCongaLineEvent } from "../congaLineEvent";
export { forceSpinningTopEvent } from "../spinningTopEvent";
export { forceGobblerEvent } from "../gobblerEvent";
export { forceMajoretteEvent } from "../majoretteEvent";
export { forceHulaHoopEvent } from "../hulaHoopEvent";
export { forceCalligraphyEvent } from "../calligraphyEvent";
export { forceSnakeCharmerEvent } from "../snakeCharmerEvent";
export { forcePlateSpinnerEvent } from "../plateSpinnerEvent";
export { forceFerrisWheelEvent } from "../ferrisWheelEvent";
export { forceBucketBrigadeEvent } from "../bucketBrigadeEvent";
export { forceSkyLanternsEvent } from "../skyLanternsEvent";
export { forceEngraverEvent } from "../engraverEvent";
export { forceXRayEvent } from "../xRayEvent";
export { forceLaserLassoEvent } from "../laserLassoEvent";
export { forceHexRingEvent } from "../hexRingEvent";
export { forcePortcullisEvent } from "../portcullisEvent";
export { forceKeyholeEvent } from "../keyholeEvent";
export { forceDefibrillatorEvent } from "../defibrillatorEvent";
export { forceCircuitBoardEvent } from "../circuitBoardEvent";
export { forceMjolnirEvent } from "../mjolnirEvent";
export { forceArcFlashEvent } from "../arcFlashEvent";
export { forceFourCornersEvent } from "../fourCornersEvent";
export { forceBoltWheelEvent } from "../boltWheelEvent";
export { forceMinefieldEvent } from "../minefieldEvent";
export { forceCannonadeEvent } from "../cannonadeEvent";
export { forceStickyBombsEvent } from "../stickyBombsEvent";
export { forceCrossblastEvent } from "../crossblastEvent";
export { forceMortarEvent } from "../mortarEvent";
export { forceFlashbangEvent } from "../flashbangEvent";
export { forceSentryTurretEvent } from "../sentryTurretEvent";
export { forceShotgunEvent } from "../shotgunEvent";
export { forceBossFightEvent } from "../bossFightEvent";
export { forceGunshipEvent } from "../gunshipEvent";
export { forceBulletTimeEvent } from "../bulletTimeEvent";
export { forceFlechettesEvent } from "../flechettesEvent";
export { forceRadarEvent } from "../radarEvent";
export { forceBingoEvent } from "../bingoEvent";
export { forceLaneHopperEvent } from "../laneHopperEvent";
export { forceSimonSaysEvent } from "../simonSaysEvent";
export { forceEqualizerEvent } from "../equalizerEvent";
export { forceLoadingBarEvent } from "../loadingBarEvent";
export { forceDiceRollEvent } from "../diceRollEvent";
export { forceMandalaEvent } from "../mandalaEvent";
export { forceZenGardenEvent } from "../zenGardenEvent";
export { forceAccordionEvent } from "../accordionEvent";
export { forceFizzEvent } from "../fizzEvent";
export { forceSoundwaveEvent } from "../soundwaveEvent";
export { forceTaffyEvent } from "../taffyEvent";
export { forceDripPaintingEvent } from "../dripPaintingEvent";
export { forceMothsEvent } from "../mothsEvent";
export { forceCurlingEvent } from "../curlingEvent";
export { forceClotheslineEvent } from "../clotheslineEvent";
export { forceBalloonPopEvent } from "../balloonPopEvent";
export { forceSpinBottleEvent } from "../spinBottleEvent";
export { forceSkyWriterEvent } from "../skyWriterEvent";
export { forceGoldPanEvent } from "../goldPanEvent";
export { forceBulldozerEvent } from "../bulldozerEvent";
export { forceKoiPondEvent } from "../koiPondEvent";
export { forcePipeOrganEvent } from "../pipeOrganEvent";
export { forceAntTrailEvent } from "../antTrailEvent";
export { forceHotAirBalloonEvent } from "../hotAirBalloonEvent";
export { forceLensFlareEvent } from "../lensFlareEvent";
export { forceTightropeEvent } from "../tightropeEvent";
export { forceNeonSignEvent } from "../neonSignEvent";
export { forceLightCageEvent } from "../lightCageEvent";
export { forceStairwayEvent } from "../stairwayEvent";
export { forceBeaconsEvent } from "../beaconsEvent";
export { forceAnvilCrawlerEvent } from "../anvilCrawlerEvent";
export { forceNeuronsEvent } from "../neuronsEvent";
export { forceBottledBoltEvent } from "../bottledBoltEvent";
export { forceThunderbirdEvent } from "../thunderbirdEvent";
export { forceSparkGapEvent } from "../sparkGapEvent";
export { forceStaticShockEvent } from "../staticShockEvent";
export { forceRocketJumpEvent } from "../rocketJumpEvent";
export { forceTorpedoesEvent } from "../torpedoesEvent";
export { forceAirstrikeEvent } from "../airstrikeEvent";
export { forceDambusterEvent } from "../dambusterEvent";
export { forceAirburstEvent } from "../airburstEvent";
export { forceBombPinwheelEvent } from "../bombPinwheelEvent";
export { forceBulletCurtainEvent } from "../bulletCurtainEvent";
export { forceTrickShotEvent } from "../trickShotEvent";
export { forceRailShooterEvent } from "../railShooterEvent";
export { forceSkeetShootEvent } from "../skeetShootEvent";
export { forceTripleTapEvent } from "../tripleTapEvent";
export { forceTommyGunEvent } from "../tommyGunEvent";
export { forceSweeperEvent } from "../sweeperEvent";
export { forceClawMachineEvent } from "../clawMachineEvent";
export { forceLotteryEvent } from "../lotteryEvent";
export { forceWordGuessEvent } from "../wordGuessEvent";
export { forceMemoryMatchEvent } from "../memoryMatchEvent";
export { forceTicTacToeEvent } from "../ticTacToeEvent";
export { forceRevCounterEvent } from "../revCounterEvent";
export { forceSluiceEvent } from "../sluiceEvent";
export { forceFoundryEvent } from "../foundryEvent";
export { forceJetStreamEvent } from "../jetStreamEvent";
export { forceMoatEvent } from "../moatEvent";
export { forceSeepEvent } from "../seepEvent";
export { forceMeanderEvent } from "../meanderEvent";
export { forceWaltzEvent } from "../waltzEvent";
export { forceGyroscopeEvent } from "../gyroscopeEvent";
export { forceDragonflyEvent } from "../dragonflyEvent";
export { forceRingTossEvent } from "../ringTossEvent";
export { forceSlipstreamEvent } from "../slipstreamEvent";
export { forceSheetMusicEvent } from "../sheetMusicEvent";
export { forceLeafBlowerEvent } from "../leafBlowerEvent";
export { forceLoomEvent } from "../loomEvent";
export { forceHighDiveEvent } from "../highDiveEvent";
export { forceSowerEvent } from "../sowerEvent";
