// event modules, part 8 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../metronomeEvent";
import "../powerGridEvent";
import "../bombBowlingEvent";
import "../showdownEvent";
import "../jumpRopeEvent";
import "../strongboxEvent";
import "../snowCannonEvent";
import "../hillClimbEvent";
import "../abacusEvent";
import "../coralEvent";
import "../chladniEvent";
import "../afterimageEvent";
import "../snowGlobeEvent";
import "../sundialEvent";
import "../riveterEvent";
import "../paddleBallEvent";
import "../geodeEvent";
import "../fogMachineEvent";
import "../chicaneEvent";
import "../epicyclesEvent";
import "../sieveEvent";
import "../clutterEvent";
import "../partingEvent";
import "../buzzWireEvent";
import "../hiccupsEvent";
import "../cutTheRopeEvent";
import "../whisperingGalleryEvent";
import "../chunnelEvent";
import "../sneezeEvent";
import "../grandPrixEvent";
import "../pillowFightEvent";
import "../dotsAndBoxesEvent";
import "../holdingPatternEvent";
import "../tankerEvent";
import "../vaporCloudEvent";
import "../shieldBreakerEvent";
import "../bottleneckEvent";
import "../skylightEvent";
import "../delugeEvent";
import "../monacoEvent";
import "../glitterSpillEvent";
import "../rogueWaveEvent";
import "../thunderEggEvent";
import "../hologramEvent";
import "../leafFallEvent";
import "../threeBodyEvent";
import "../billowsEvent";
import "../moireEvent";
import "../polePositionEvent";
import "../countersinkEvent";
import "../busyBeaverEvent";
import "../pursuitEvent";
import "../fractalChargeEvent";
import "../snowplowEvent";
import "../franklinsKiteEvent";
import "../sokobanEvent";
import "../frackingEvent";
import "../chopperEvent";
import "../extinguisherEvent";
import "../goldenSpiralEvent";
import "../wildfireEvent";
import "../timeTrialEvent";
import "../dustBunniesEvent";
import "../magneticPendulumEvent";
import "../deCasteljauEvent";
import "../buffonsNeedleEvent";
import "../fuseMazeEvent";
import "../barBilliardsEvent";
import "../levyFlightEvent";
import "../brachistochroneEvent";
import "../ulamSpiralEvent";
import "../galtonBoardEvent";
import "../poohsticksEvent";
import "../fireForEffectEvent";
import "../eyewallEvent";
import "../josephusEvent";
import "../podiumEvent";
import "../robovacEvent";
import "../figureEightEvent";
import "../bonanzaEvent";
import "../piClacksEvent";
import "../incomingEvent";
import "../stringArtEvent";
import "../petanqueEvent";
import "../centipedeEvent";
import "../mandelbrotEvent";
import "../towerOfHanoiEvent";
import "../rockTheBoatEvent";
import "../windowWasherEvent";
import "../tandemDriftEvent";
import "../postHolesEvent";
import "../clackersEvent";
import "../shishiOdoshiEvent";
import "../isingModelEvent";
import "../faradayCageEvent";
import "../freeThrowsEvent";
import "../fissionEvent";
import "../hydraEvent";
import "../opticalTweezersEvent";
import "../travellingSalesmanEvent";
import "../spinCycleEvent";
import "../pilotHoleEvent";
import "../pitStopEvent";
import "../blackHoleMergerEvent";
import "../accretionEvent";
import "../maxwellsDemonEvent";
import "../tidalTailsEvent";
import "../hypervelocityEvent";
import "../quasarEvent";
import "../volleyballEvent";
import "../smartRocketsEvent";
import "../bombMobileEvent";
import "../ringGalaxyEvent";
import "../gravitationalLensEvent";
import "../convectionEvent";
import "../paintballEvent";
import "../kirkwoodGapsEvent";
import "../periscopeEvent";
import "../waterSkiEvent";
import "../jaiAlaiEvent";
import "../polarRingEvent";
import "../kebabEvent";
import "../katamariEvent";
import "../harmonicsEvent";
import "../stairwellEvent";
import "../ironFilingsEvent";
import "../syncEvent";
import "../rocheLobeEvent";
import "../marblesEvent";
import "../bombShuffleboardEvent";
import "../barredSpiralEvent";
import "../bulletMosaicEvent";
import "../bombGrapesEvent";
import "../flowFieldEvent";
import "../rallyJumpEvent";
import "../sweetheartEvent";
import "../mintEvent";
import "../catSketchEvent";
import "../stencilEvent";
import "../denoiseEvent";
import "../pincushionEvent";
import "../updraftEvent";
import "../plugholesEvent";
import "../apollonianGasketEvent";
import "../droneShowEvent";
import "../marxGeneratorEvent";
import "../oortCloudEvent";
import "../doubleSlitEvent";
import "../blastSweepEvent";
import "../hydraulicJumpEvent";
import "../seedPodsEvent";
import "../rippleFireEvent";
import "../sparkChamberEvent";
import "../turbineEvent";
import "../strangeAttractorEvent";
import "../topsyTurvyEvent";
import "../goldPlatingEvent";
import "../crosswindEvent";
import "../hailstoneEvent";
import "../hilbertCurveEvent";
import "../leMansEvent";
import "../tunnelBorerEvent";
import "../harpoonEvent";
import "../eightQueensEvent";
import "../shortestPathEvent";
import "../sinkholeEvent";
import "../backwashEvent";
import "../deflectorEvent";
import "../sunflowerEvent";
import "../convexHullEvent";
import "../slashEvent";
import "../jackhammerEvent";
import "../pummelEvent";
import "../overloadEvent";
import "../gatlingEvent";
import "../pressEvent";
import "../drillEvent";
import "../burrowEvent";
import "../pingPongEvent";
import "../slamDunkEvent";
import "../uppercutEvent";
import "../headHopEvent";
import "../paparazziEvent";
import "../missileBarrageEvent";
import "../sonicBoomEvent";
import "../mitosisEvent";
import "../plinkoEvent";
import "../hammerThrowEvent";
import "../snakeEvent";
import "../breakoutEvent";
import "../lineClearEvent";
import "../breakShotEvent";
import "../bulletHellEvent";
import "../vortexEvent";
import "../ricochetEvent";
import "../waterfallEvent";
import "../conveyorEvent";
import "../firefliesEvent";
import "../streamEvent";
import "../trailsEvent";
import "../drawEvent";
import "../nightSkyEvent";
import "../pitcherEvent";
import "../glimmerEvent";
import "../renovateEvent";
import "../upgradeEvent";
import "../unlockEvent";
// the dev test bar's hooks
export { forceMetronomeEvent } from "../metronomeEvent";
export { forcePowerGridEvent } from "../powerGridEvent";
export { forceBombBowlingEvent } from "../bombBowlingEvent";
export { forceShowdownEvent } from "../showdownEvent";
export { forceJumpRopeEvent } from "../jumpRopeEvent";
export { forceStrongboxEvent } from "../strongboxEvent";
export { forceSnowCannonEvent } from "../snowCannonEvent";
export { forceHillClimbEvent } from "../hillClimbEvent";
export { forceAbacusEvent } from "../abacusEvent";
export { forceCoralEvent } from "../coralEvent";
export { forceChladniEvent } from "../chladniEvent";
export { forceAfterimageEvent } from "../afterimageEvent";
export { forceSnowGlobeEvent } from "../snowGlobeEvent";
export { forceSundialEvent } from "../sundialEvent";
export { forceRiveterEvent } from "../riveterEvent";
export { forcePaddleBallEvent } from "../paddleBallEvent";
export { forceGeodeEvent } from "../geodeEvent";
export { forceFogMachineEvent } from "../fogMachineEvent";
export { forceChicaneEvent } from "../chicaneEvent";
export { forceEpicyclesEvent } from "../epicyclesEvent";
export { forceSieveEvent } from "../sieveEvent";
export { forceClutterEvent } from "../clutterEvent";
export { forcePartingEvent } from "../partingEvent";
export { forceBuzzWireEvent } from "../buzzWireEvent";
export { forceHiccupsEvent } from "../hiccupsEvent";
export { forceCutTheRopeEvent } from "../cutTheRopeEvent";
export { forceWhisperingGalleryEvent } from "../whisperingGalleryEvent";
export { forceChunnelEvent } from "../chunnelEvent";
export { forceSneezeEvent } from "../sneezeEvent";
export { forceGrandPrixEvent } from "../grandPrixEvent";
export { forcePillowFightEvent } from "../pillowFightEvent";
export { forceDotsAndBoxesEvent } from "../dotsAndBoxesEvent";
export { forceHoldingPatternEvent } from "../holdingPatternEvent";
export { forceTankerEvent } from "../tankerEvent";
export { forceVaporCloudEvent } from "../vaporCloudEvent";
export { forceShieldBreakerEvent } from "../shieldBreakerEvent";
export { forceBottleneckEvent } from "../bottleneckEvent";
export { forceSkylightEvent } from "../skylightEvent";
export { forceDelugeEvent } from "../delugeEvent";
export { forceMonacoEvent } from "../monacoEvent";
export { forceGlitterSpillEvent } from "../glitterSpillEvent";
export { forceRogueWaveEvent } from "../rogueWaveEvent";
export { forceThunderEggEvent } from "../thunderEggEvent";
export { forceHologramEvent } from "../hologramEvent";
export { forceLeafFallEvent } from "../leafFallEvent";
export { forceThreeBodyEvent } from "../threeBodyEvent";
export { forceBillowsEvent } from "../billowsEvent";
export { forceMoireEvent } from "../moireEvent";
export { forcePolePositionEvent } from "../polePositionEvent";
export { forceCountersinkEvent } from "../countersinkEvent";
export { forceBusyBeaverEvent } from "../busyBeaverEvent";
export { forcePursuitEvent } from "../pursuitEvent";
export { forceFractalChargeEvent } from "../fractalChargeEvent";
export { forceSnowplowEvent } from "../snowplowEvent";
export { forceFranklinsKiteEvent } from "../franklinsKiteEvent";
export { forceSokobanEvent } from "../sokobanEvent";
export { forceFrackingEvent } from "../frackingEvent";
export { forceChopperEvent } from "../chopperEvent";
export { forceExtinguisherEvent } from "../extinguisherEvent";
export { forceGoldenSpiralEvent } from "../goldenSpiralEvent";
export { forceWildfireEvent } from "../wildfireEvent";
export { forceTimeTrialEvent } from "../timeTrialEvent";
export { forceDustBunniesEvent } from "../dustBunniesEvent";
export { forceMagneticPendulumEvent } from "../magneticPendulumEvent";
export { forceDeCasteljauEvent } from "../deCasteljauEvent";
export { forceBuffonsNeedleEvent } from "../buffonsNeedleEvent";
export { forceFuseMazeEvent } from "../fuseMazeEvent";
export { forceBarBilliardsEvent } from "../barBilliardsEvent";
export { forceLevyFlightEvent } from "../levyFlightEvent";
export { forceBrachistochroneEvent } from "../brachistochroneEvent";
export { forceUlamSpiralEvent } from "../ulamSpiralEvent";
export { forceGaltonBoardEvent } from "../galtonBoardEvent";
export { forcePoohsticksEvent } from "../poohsticksEvent";
export { forceFireForEffectEvent } from "../fireForEffectEvent";
export { forceEyewallEvent } from "../eyewallEvent";
export { forceJosephusEvent } from "../josephusEvent";
export { forcePodiumEvent } from "../podiumEvent";
export { forceRobovacEvent } from "../robovacEvent";
export { forceFigureEightEvent } from "../figureEightEvent";
export { forceBonanzaEvent } from "../bonanzaEvent";
export { forcePiClacksEvent } from "../piClacksEvent";
export { forceIncomingEvent } from "../incomingEvent";
export { forceStringArtEvent } from "../stringArtEvent";
export { forcePetanqueEvent } from "../petanqueEvent";
export { forceCentipedeEvent } from "../centipedeEvent";
export { forceMandelbrotEvent } from "../mandelbrotEvent";
export { forceTowerOfHanoiEvent } from "../towerOfHanoiEvent";
export { forceRockTheBoatEvent } from "../rockTheBoatEvent";
export { forceWindowWasherEvent } from "../windowWasherEvent";
export { forceTandemDriftEvent } from "../tandemDriftEvent";
export { forcePostHolesEvent } from "../postHolesEvent";
export { forceClackersEvent } from "../clackersEvent";
export { forceShishiOdoshiEvent } from "../shishiOdoshiEvent";
export { forceIsingModelEvent } from "../isingModelEvent";
export { forceFaradayCageEvent } from "../faradayCageEvent";
export { forceFreeThrowsEvent } from "../freeThrowsEvent";
export { forceFissionEvent } from "../fissionEvent";
export { forceHydraEvent } from "../hydraEvent";
export { forceOpticalTweezersEvent } from "../opticalTweezersEvent";
export { forceTravellingSalesmanEvent } from "../travellingSalesmanEvent";
export { forceSpinCycleEvent } from "../spinCycleEvent";
export { forcePilotHoleEvent } from "../pilotHoleEvent";
export { forcePitStopEvent } from "../pitStopEvent";
export { forceBlackHoleMergerEvent } from "../blackHoleMergerEvent";
export { forceAccretionEvent } from "../accretionEvent";
export { forceMaxwellsDemonEvent } from "../maxwellsDemonEvent";
export { forceTidalTailsEvent } from "../tidalTailsEvent";
export { forceHypervelocityEvent } from "../hypervelocityEvent";
export { forceQuasarEvent } from "../quasarEvent";
export { forceVolleyballEvent } from "../volleyballEvent";
export { forceSmartRocketsEvent } from "../smartRocketsEvent";
export { forceBombMobileEvent } from "../bombMobileEvent";
export { forceRingGalaxyEvent } from "../ringGalaxyEvent";
export { forceGravitationalLensEvent } from "../gravitationalLensEvent";
export { forceConvectionEvent } from "../convectionEvent";
export { forcePaintballEvent } from "../paintballEvent";
export { forceKirkwoodGapsEvent } from "../kirkwoodGapsEvent";
export { forcePeriscopeEvent } from "../periscopeEvent";
export { forceWaterSkiEvent } from "../waterSkiEvent";
export { forceJaiAlaiEvent } from "../jaiAlaiEvent";
export { forcePolarRingEvent } from "../polarRingEvent";
export { forceKebabEvent } from "../kebabEvent";
export { forceKatamariEvent } from "../katamariEvent";
export { forceHarmonicsEvent } from "../harmonicsEvent";
export { forceStairwellEvent } from "../stairwellEvent";
export { forceIronFilingsEvent } from "../ironFilingsEvent";
export { forceSyncEvent } from "../syncEvent";
export { forceRocheLobeEvent } from "../rocheLobeEvent";
export { forceMarblesEvent } from "../marblesEvent";
export { forceBombShuffleboardEvent } from "../bombShuffleboardEvent";
export { forceBarredSpiralEvent } from "../barredSpiralEvent";
export { forceBulletMosaicEvent } from "../bulletMosaicEvent";
export { forceBombGrapesEvent } from "../bombGrapesEvent";
export { forceFlowFieldEvent } from "../flowFieldEvent";
export { forceRallyJumpEvent } from "../rallyJumpEvent";
export { forceSweetheartEvent } from "../sweetheartEvent";
export { forceMintEvent } from "../mintEvent";
export { forceCatSketchEvent } from "../catSketchEvent";
export { forceStencilEvent } from "../stencilEvent";
export { forceDenoiseEvent } from "../denoiseEvent";
export { forcePincushionEvent } from "../pincushionEvent";
export { forceUpdraftEvent } from "../updraftEvent";
export { forcePlugholesEvent } from "../plugholesEvent";
export { forceApollonianGasketEvent } from "../apollonianGasketEvent";
export { forceDroneShowEvent } from "../droneShowEvent";
export { forceMarxGeneratorEvent } from "../marxGeneratorEvent";
export { forceOortCloudEvent } from "../oortCloudEvent";
export { forceDoubleSlitEvent } from "../doubleSlitEvent";
export { forceBlastSweepEvent } from "../blastSweepEvent";
export { forceHydraulicJumpEvent } from "../hydraulicJumpEvent";
export { forceSeedPodsEvent } from "../seedPodsEvent";
export { forceRippleFireEvent } from "../rippleFireEvent";
export { forceSparkChamberEvent } from "../sparkChamberEvent";
export { forceTurbineEvent } from "../turbineEvent";
export { forceStrangeAttractorEvent } from "../strangeAttractorEvent";
export { forceTopsyTurvyEvent } from "../topsyTurvyEvent";
export { forceGoldPlatingEvent } from "../goldPlatingEvent";
export { forceCrosswindEvent } from "../crosswindEvent";
export { forceHailstoneEvent } from "../hailstoneEvent";
export { forceHilbertCurveEvent } from "../hilbertCurveEvent";
export { forceLeMansEvent } from "../leMansEvent";
export { forceTunnelBorerEvent } from "../tunnelBorerEvent";
export { forceHarpoonEvent } from "../harpoonEvent";
export { forceEightQueensEvent } from "../eightQueensEvent";
export { forceShortestPathEvent } from "../shortestPathEvent";
export { forceSinkholeEvent } from "../sinkholeEvent";
export { forceBackwashEvent } from "../backwashEvent";
export { forceDeflectorEvent } from "../deflectorEvent";
export { forceSunflowerEvent } from "../sunflowerEvent";
export { forceConvexHullEvent } from "../convexHullEvent";
export { forceSlashEvent } from "../slashEvent";
export { forceJackhammerEvent } from "../jackhammerEvent";
export { forcePummelEvent } from "../pummelEvent";
export { forceOverloadEvent } from "../overloadEvent";
export { forceGatlingEvent } from "../gatlingEvent";
export { forcePressEvent } from "../pressEvent";
export { forceDrillEvent } from "../drillEvent";
export { forceBurrowEvent } from "../burrowEvent";
export { forcePingPongEvent } from "../pingPongEvent";
export { forceSlamDunkEvent } from "../slamDunkEvent";
export { forceUppercutEvent } from "../uppercutEvent";
export { forceHeadHopEvent } from "../headHopEvent";
export { forcePaparazziEvent } from "../paparazziEvent";
export { forceMissileBarrageEvent } from "../missileBarrageEvent";
export { forceSonicBoomEvent } from "../sonicBoomEvent";
export { forceMitosisEvent } from "../mitosisEvent";
export { forcePlinkoEvent } from "../plinkoEvent";
export { forceHammerThrowEvent } from "../hammerThrowEvent";
export { forceSnakeEvent } from "../snakeEvent";
export { forceBreakoutEvent } from "../breakoutEvent";
export { forceLineClearEvent } from "../lineClearEvent";
export { forceBreakShotEvent } from "../breakShotEvent";
export { forceBulletHellEvent } from "../bulletHellEvent";
export { forceVortexEvent } from "../vortexEvent";
export { forceRicochetEvent } from "../ricochetEvent";
export { forceWaterfallEvent } from "../waterfallEvent";
export { forceConveyorEvent } from "../conveyorEvent";
export { forceFirefliesEvent } from "../firefliesEvent";
export { forceStreamEvent } from "../streamEvent";
export { forceTrailsEvent } from "../trailsEvent";
export { forceDrawEvent } from "../drawEvent";
export { forceNightSkyEvent } from "../nightSkyEvent";
export { forcePitcherEvent } from "../pitcherEvent";
export { forceGlimmerEvent } from "../glimmerEvent";
export { forceRenovateEvent } from "../renovateEvent";
export { forceUpgradeEvent } from "../upgradeEvent";
export { forceUnlockEvent } from "../unlockEvent";
