// event modules, part 1 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../swarmEvent";
import "../kickbackEvent";
import "../paydayEvent";
import "../piggyBankEvent";
import "../coinTossEvent";
import "../hourglassEvent";
import "../rocketEvent";
import "../revealEvent";
import "../jackpotReelsEvent";
import "../chainPayEvent";
import "../twisterEvent";
import "../trickleEvent";
import "../magnetEvent";
import "../spilloverEvent";
import "../constellationEvent";
import "../ascendEvent";
import "../risingTideEvent";
import "../beanstalkEvent";
import "../blessingEvent";
import "../haloEvent";
import "../meteorShowerEvent";
import "../mentorEvent";
import "../sparkChainEvent";
import "../polishEvent";
import "../lighthouseEvent";
import "../recruitEvent";
import "../promotionDayEvent";
import "../alchemyEvent";
import "../investmentEvent";
import "../dividendsEvent";
import "../burstEvent";
import "../sprayEvent";
import "../rippleEvent";
import "../wreckingBallEvent";
import "../piledriverEvent";
import "../bowlingEvent";
import "../thunderclapEvent";
import "../bullseyeEvent";
import "../popcornEvent";
import "../newtonsCradleEvent";
import "../juggleEvent";
import "../boomerangEvent";
import "../heartbeatEvent";
import "../clashEvent";
import "../asteroidsEvent";
import "../whackAMoleEvent";
import "../drumrollEvent";
import "../shellGameEvent";
import "../seesawEvent";
import "../scratchEvent";
import "../tagEvent";
import "../bumpersEvent";
import "../catcherEvent";
import "../implosionEvent";
import "../atomEvent";
import "../spiralEvent";
import "../loopEvent";
import "../eternityEvent";
import "../helixEvent";
import "../yoYoEvent";
import "../racetrackEvent";
import "../swingEvent";
import "../kaleidoscopeEvent";
import "../zipperEvent";
import "../sprinklerEvent";
import "../clockworkEvent";
import "../holeInOneEvent";
import "../leapfrogEvent";
import "../lineupEvent";
import "../stampedeEvent";
import "../wormholeEvent";
import "../splatEvent";
import "../rouletteEvent";
import "../freeKickEvent";
import "../slalomEvent";
import "../lightningEvent";
import "../fireHoseEvent";
import "../confluenceEvent";
import "../sloshEvent";
import "../siphonEvent";
import "../crossfireEvent";
import "../gravityWellEvent";
import "../splashdownEvent";
import "../geysersEvent";
import "../cashCannonEvent";
import "../hooverEvent";
import "../airShowEvent";
import "../leakEvent";
import "../climbEvent";
import "../kiteEvent";
import "../rainbowEvent";
import "../branchesEvent";
import "../tugOfWarEvent";
import "../waterwheelEvent";
import "../braidEvent";
import "../skimEvent";
import "../latticeEvent";
import "../fireworksEvent";
import "../slingshotEvent";
import "../marqueeEvent";
import "../cropDusterEvent";
import "../bolasEvent";
import "../countdownEvent";
import "../sparklerEvent";
import "../slinkyEvent";
import "../pipelineEvent";
import "../prismEvent";
import "../trampolineEvent";
import "../hummingbirdEvent";
import "../diveBombEvent";
import "../skiJumpEvent";
import "../jetpackEvent";
import "../bassDropEvent";
import "../laserGridEvent";
import "../etchEvent";
import "../searchlightsEvent";
import "../tractorBeamEvent";
import "../beamClashEvent";
import "../butterflyEvent";
import "../kelpEvent";
import "../pendulumWaveEvent";
import "../formationEvent";
import "../ouroborosEvent";
import "../bowstringEvent";
import "../superlaserEvent";
import "../ionStormEvent";
import "../glitchEvent";
import "../magnifierEvent";
import "../waterShowEvent";
// the dev test bar's hooks
export { startSwarmEvent } from "../swarmEvent";
export { forceKickbackEvent } from "../kickbackEvent";
export { forcePaydayEvent } from "../paydayEvent";
export { forcePiggyBankEvent } from "../piggyBankEvent";
export { forceCoinTossEvent } from "../coinTossEvent";
export { forceHourglassEvent } from "../hourglassEvent";
export { forceRocketEvent } from "../rocketEvent";
export { forceRevealEvent } from "../revealEvent";
export { forceJackpotReelsEvent } from "../jackpotReelsEvent";
export { forceChainPayEvent } from "../chainPayEvent";
export { forceTwisterEvent } from "../twisterEvent";
export { forceTrickleEvent } from "../trickleEvent";
export { forceMagnetEvent } from "../magnetEvent";
export { forceSpilloverEvent } from "../spilloverEvent";
export { forceConstellationEvent } from "../constellationEvent";
export { forceAscendEvent } from "../ascendEvent";
export { forceRisingTideEvent } from "../risingTideEvent";
export { forceBeanstalkEvent } from "../beanstalkEvent";
export { forceBlessingEvent } from "../blessingEvent";
export { forceHaloEvent } from "../haloEvent";
export { forceMeteorShowerEvent } from "../meteorShowerEvent";
export { forceMentorEvent } from "../mentorEvent";
export { forceSparkChainEvent } from "../sparkChainEvent";
export { forcePolishEvent } from "../polishEvent";
export { forceLighthouseEvent } from "../lighthouseEvent";
export { forceRecruitEvent } from "../recruitEvent";
export { forcePromotionDayEvent } from "../promotionDayEvent";
export { forceAlchemyEvent } from "../alchemyEvent";
export { forceInvestmentEvent } from "../investmentEvent";
export { forceDividendsEvent } from "../dividendsEvent";
export { forceBurstEvent } from "../burstEvent";
export { forceSprayEvent } from "../sprayEvent";
export { forceRippleEvent } from "../rippleEvent";
export { forceWreckingBallEvent } from "../wreckingBallEvent";
export { forcePiledriverEvent } from "../piledriverEvent";
export { forceBowlingEvent } from "../bowlingEvent";
export { forceThunderclapEvent } from "../thunderclapEvent";
export { forceBullseyeEvent } from "../bullseyeEvent";
export { forcePopcornEvent } from "../popcornEvent";
export { forceNewtonsCradleEvent } from "../newtonsCradleEvent";
export { forceJuggleEvent } from "../juggleEvent";
export { forceBoomerangEvent } from "../boomerangEvent";
export { forceHeartbeatEvent } from "../heartbeatEvent";
export { forceClashEvent } from "../clashEvent";
export { forceAsteroidsEvent } from "../asteroidsEvent";
export { forceWhackAMoleEvent } from "../whackAMoleEvent";
export { forceDrumrollEvent } from "../drumrollEvent";
export { forceShellGameEvent } from "../shellGameEvent";
export { forceSeesawEvent } from "../seesawEvent";
export { forceScratchEvent } from "../scratchEvent";
export { forceTagEvent } from "../tagEvent";
export { forceBumpersEvent } from "../bumpersEvent";
export { forceCatcherEvent } from "../catcherEvent";
export { forceImplosionEvent } from "../implosionEvent";
export { forceAtomEvent } from "../atomEvent";
export { forceSpiralEvent } from "../spiralEvent";
export { forceLoopEvent } from "../loopEvent";
export { forceEternityEvent } from "../eternityEvent";
export { forceHelixEvent } from "../helixEvent";
export { forceYoYoEvent } from "../yoYoEvent";
export { forceRacetrackEvent } from "../racetrackEvent";
export { forceSwingEvent } from "../swingEvent";
export { forceKaleidoscopeEvent } from "../kaleidoscopeEvent";
export { forceZipperEvent } from "../zipperEvent";
export { forceSprinklerEvent } from "../sprinklerEvent";
export { forceClockworkEvent } from "../clockworkEvent";
export { forceHoleInOneEvent } from "../holeInOneEvent";
export { forceLeapfrogEvent } from "../leapfrogEvent";
export { forceLineupEvent } from "../lineupEvent";
export { forceStampedeEvent } from "../stampedeEvent";
export { forceWormholeEvent } from "../wormholeEvent";
export { forceSplatEvent } from "../splatEvent";
export { forceRouletteEvent } from "../rouletteEvent";
export { forceFreeKickEvent } from "../freeKickEvent";
export { forceSlalomEvent } from "../slalomEvent";
export { forceLightningEvent } from "../lightningEvent";
export { forceFireHoseEvent } from "../fireHoseEvent";
export { forceConfluenceEvent } from "../confluenceEvent";
export { forceSloshEvent } from "../sloshEvent";
export { forceSiphonEvent } from "../siphonEvent";
export { forceCrossfireEvent } from "../crossfireEvent";
export { forceGravityWellEvent } from "../gravityWellEvent";
export { forceSplashdownEvent } from "../splashdownEvent";
export { forceGeysersEvent } from "../geysersEvent";
export { forceCashCannonEvent } from "../cashCannonEvent";
export { forceHooverEvent } from "../hooverEvent";
export { forceAirShowEvent } from "../airShowEvent";
export { forceLeakEvent } from "../leakEvent";
export { forceClimbEvent } from "../climbEvent";
export { forceKiteEvent } from "../kiteEvent";
export { forceRainbowEvent } from "../rainbowEvent";
export { forceBranchesEvent } from "../branchesEvent";
export { forceTugOfWarEvent } from "../tugOfWarEvent";
export { forceWaterwheelEvent } from "../waterwheelEvent";
export { forceBraidEvent } from "../braidEvent";
export { forceSkimEvent } from "../skimEvent";
export { forceLatticeEvent } from "../latticeEvent";
export { forceFireworksEvent } from "../fireworksEvent";
export { forceSlingshotEvent } from "../slingshotEvent";
export { forceMarqueeEvent } from "../marqueeEvent";
export { forceCropDusterEvent } from "../cropDusterEvent";
export { forceBolasEvent } from "../bolasEvent";
export { forceCountdownEvent } from "../countdownEvent";
export { forceSparklerEvent } from "../sparklerEvent";
export { forceSlinkyEvent } from "../slinkyEvent";
export { forcePipelineEvent } from "../pipelineEvent";
export { forcePrismEvent } from "../prismEvent";
export { forceTrampolineEvent } from "../trampolineEvent";
export { forceHummingbirdEvent } from "../hummingbirdEvent";
export { forceDiveBombEvent } from "../diveBombEvent";
export { forceSkiJumpEvent } from "../skiJumpEvent";
export { forceJetpackEvent } from "../jetpackEvent";
export { forceBassDropEvent } from "../bassDropEvent";
export { forceLaserGridEvent } from "../laserGridEvent";
export { forceEtchEvent } from "../etchEvent";
export { forceSearchlightsEvent } from "../searchlightsEvent";
export { forceTractorBeamEvent } from "../tractorBeamEvent";
export { forceBeamClashEvent } from "../beamClashEvent";
export { forceButterflyEvent } from "../butterflyEvent";
export { forceKelpEvent } from "../kelpEvent";
export { forcePendulumWaveEvent } from "../pendulumWaveEvent";
export { forceFormationEvent } from "../formationEvent";
export { forceOuroborosEvent } from "../ouroborosEvent";
export { forceBowstringEvent } from "../bowstringEvent";
export { forceSuperlaserEvent } from "../superlaserEvent";
export { forceIonStormEvent } from "../ionStormEvent";
export { forceGlitchEvent } from "../glitchEvent";
export { forceMagnifierEvent } from "../magnifierEvent";
export { forceWaterShowEvent } from "../waterShowEvent";
export { forceBoostEvent } from "../boostEvent";
export { forceUnionEvent } from "../unionEvent";
export { forceHuntEvent } from "../huntEvent";
