// event modules, part 8 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../metronomeEvent";
import "../powerGridEvent";
import "../bombBowlingEvent";
import "../showdownEvent";
import "../jumpRopeEvent";
import "../strongboxEvent";
import "../snowCannonEvent";
import "../hillClimbEvent";
import "../abacusEvent";
import "../coralEvent";
import "../chladniEvent";
import "../afterimageEvent";
import "../snowGlobeEvent";
import "../sundialEvent";
import "../riveterEvent";
import "../paddleBallEvent";
import "../geodeEvent";
import "../fogMachineEvent";
import "../chicaneEvent";
import "../epicyclesEvent";
import "../sieveEvent";
import "../clutterEvent";
import "../partingEvent";
import "../buzzWireEvent";
import "../hiccupsEvent";
import "../cutTheRopeEvent";
import "../whisperingGalleryEvent";
import "../chunnelEvent";
import "../sneezeEvent";
import "../grandPrixEvent";
import "../pillowFightEvent";
import "../dotsAndBoxesEvent";
import "../holdingPatternEvent";
import "../tankerEvent";
import "../vaporCloudEvent";
import "../shieldBreakerEvent";
import "../bottleneckEvent";
import "../skylightEvent";
import "../delugeEvent";
import "../monacoEvent";
import "../glitterSpillEvent";
import "../rogueWaveEvent";
import "../thunderEggEvent";
import "../hologramEvent";
import "../leafFallEvent";
import "../threeBodyEvent";
import "../billowsEvent";
import "../moireEvent";
import "../polePositionEvent";
import "../countersinkEvent";
import "../busyBeaverEvent";
import "../pursuitEvent";
import "../fractalChargeEvent";
import "../snowplowEvent";
import "../franklinsKiteEvent";
import "../sokobanEvent";
import "../frackingEvent";
import "../chopperEvent";
import "../extinguisherEvent";
import "../goldenSpiralEvent";
import "../wildfireEvent";
import "../timeTrialEvent";
import "../dustBunniesEvent";
import "../magneticPendulumEvent";
import "../deCasteljauEvent";
import "../buffonsNeedleEvent";
import "../fuseMazeEvent";
import "../barBilliardsEvent";
import "../levyFlightEvent";
import "../brachistochroneEvent";
import "../ulamSpiralEvent";
import "../galtonBoardEvent";
import "../poohsticksEvent";
import "../fireForEffectEvent";
import "../eyewallEvent";
import "../josephusEvent";
import "../podiumEvent";
import "../robovacEvent";
import "../figureEightEvent";
import "../bonanzaEvent";
import "../piClacksEvent";
import "../seedPodsEvent";
import "../rippleFireEvent";
import "../sparkChamberEvent";
import "../turbineEvent";
import "../strangeAttractorEvent";
import "../topsyTurvyEvent";
import "../goldPlatingEvent";
import "../crosswindEvent";
import "../hailstoneEvent";
import "../hilbertCurveEvent";
import "../leMansEvent";
import "../tunnelBorerEvent";
import "../harpoonEvent";
import "../eightQueensEvent";
import "../shortestPathEvent";
import "../sinkholeEvent";
import "../backwashEvent";
import "../deflectorEvent";
import "../sunflowerEvent";
import "../convexHullEvent";
import "../slashEvent";
import "../jackhammerEvent";
import "../pummelEvent";
import "../overloadEvent";
import "../gatlingEvent";
import "../pressEvent";
import "../drillEvent";
import "../burrowEvent";
import "../pingPongEvent";
import "../slamDunkEvent";
import "../uppercutEvent";
import "../headHopEvent";
import "../paparazziEvent";
import "../missileBarrageEvent";
import "../sonicBoomEvent";
import "../mitosisEvent";
import "../plinkoEvent";
import "../hammerThrowEvent";
import "../snakeEvent";
import "../breakoutEvent";
import "../lineClearEvent";
import "../breakShotEvent";
import "../bulletHellEvent";
import "../vortexEvent";
import "../ricochetEvent";
import "../waterfallEvent";
import "../conveyorEvent";
import "../firefliesEvent";
import "../streamEvent";
import "../trailsEvent";
import "../drawEvent";
import "../nightSkyEvent";
import "../pitcherEvent";
import "../glimmerEvent";
import "../renovateEvent";
import "../upgradeEvent";
import "../unlockEvent";
// the dev test bar's hooks
export { forceMetronomeEvent } from "../metronomeEvent";
export { forcePowerGridEvent } from "../powerGridEvent";
export { forceBombBowlingEvent } from "../bombBowlingEvent";
export { forceShowdownEvent } from "../showdownEvent";
export { forceJumpRopeEvent } from "../jumpRopeEvent";
export { forceStrongboxEvent } from "../strongboxEvent";
export { forceSnowCannonEvent } from "../snowCannonEvent";
export { forceHillClimbEvent } from "../hillClimbEvent";
export { forceAbacusEvent } from "../abacusEvent";
export { forceCoralEvent } from "../coralEvent";
export { forceChladniEvent } from "../chladniEvent";
export { forceAfterimageEvent } from "../afterimageEvent";
export { forceSnowGlobeEvent } from "../snowGlobeEvent";
export { forceSundialEvent } from "../sundialEvent";
export { forceRiveterEvent } from "../riveterEvent";
export { forcePaddleBallEvent } from "../paddleBallEvent";
export { forceGeodeEvent } from "../geodeEvent";
export { forceFogMachineEvent } from "../fogMachineEvent";
export { forceChicaneEvent } from "../chicaneEvent";
export { forceEpicyclesEvent } from "../epicyclesEvent";
export { forceSieveEvent } from "../sieveEvent";
export { forceClutterEvent } from "../clutterEvent";
export { forcePartingEvent } from "../partingEvent";
export { forceBuzzWireEvent } from "../buzzWireEvent";
export { forceHiccupsEvent } from "../hiccupsEvent";
export { forceCutTheRopeEvent } from "../cutTheRopeEvent";
export { forceWhisperingGalleryEvent } from "../whisperingGalleryEvent";
export { forceChunnelEvent } from "../chunnelEvent";
export { forceSneezeEvent } from "../sneezeEvent";
export { forceGrandPrixEvent } from "../grandPrixEvent";
export { forcePillowFightEvent } from "../pillowFightEvent";
export { forceDotsAndBoxesEvent } from "../dotsAndBoxesEvent";
export { forceHoldingPatternEvent } from "../holdingPatternEvent";
export { forceTankerEvent } from "../tankerEvent";
export { forceVaporCloudEvent } from "../vaporCloudEvent";
export { forceShieldBreakerEvent } from "../shieldBreakerEvent";
export { forceBottleneckEvent } from "../bottleneckEvent";
export { forceSkylightEvent } from "../skylightEvent";
export { forceDelugeEvent } from "../delugeEvent";
export { forceMonacoEvent } from "../monacoEvent";
export { forceGlitterSpillEvent } from "../glitterSpillEvent";
export { forceRogueWaveEvent } from "../rogueWaveEvent";
export { forceThunderEggEvent } from "../thunderEggEvent";
export { forceHologramEvent } from "../hologramEvent";
export { forceLeafFallEvent } from "../leafFallEvent";
export { forceThreeBodyEvent } from "../threeBodyEvent";
export { forceBillowsEvent } from "../billowsEvent";
export { forceMoireEvent } from "../moireEvent";
export { forcePolePositionEvent } from "../polePositionEvent";
export { forceCountersinkEvent } from "../countersinkEvent";
export { forceBusyBeaverEvent } from "../busyBeaverEvent";
export { forcePursuitEvent } from "../pursuitEvent";
export { forceFractalChargeEvent } from "../fractalChargeEvent";
export { forceSnowplowEvent } from "../snowplowEvent";
export { forceFranklinsKiteEvent } from "../franklinsKiteEvent";
export { forceSokobanEvent } from "../sokobanEvent";
export { forceFrackingEvent } from "../frackingEvent";
export { forceChopperEvent } from "../chopperEvent";
export { forceExtinguisherEvent } from "../extinguisherEvent";
export { forceGoldenSpiralEvent } from "../goldenSpiralEvent";
export { forceWildfireEvent } from "../wildfireEvent";
export { forceTimeTrialEvent } from "../timeTrialEvent";
export { forceDustBunniesEvent } from "../dustBunniesEvent";
export { forceMagneticPendulumEvent } from "../magneticPendulumEvent";
export { forceDeCasteljauEvent } from "../deCasteljauEvent";
export { forceBuffonsNeedleEvent } from "../buffonsNeedleEvent";
export { forceFuseMazeEvent } from "../fuseMazeEvent";
export { forceBarBilliardsEvent } from "../barBilliardsEvent";
export { forceLevyFlightEvent } from "../levyFlightEvent";
export { forceBrachistochroneEvent } from "../brachistochroneEvent";
export { forceUlamSpiralEvent } from "../ulamSpiralEvent";
export { forceGaltonBoardEvent } from "../galtonBoardEvent";
export { forcePoohsticksEvent } from "../poohsticksEvent";
export { forceFireForEffectEvent } from "../fireForEffectEvent";
export { forceEyewallEvent } from "../eyewallEvent";
export { forceJosephusEvent } from "../josephusEvent";
export { forcePodiumEvent } from "../podiumEvent";
export { forceRobovacEvent } from "../robovacEvent";
export { forceFigureEightEvent } from "../figureEightEvent";
export { forceBonanzaEvent } from "../bonanzaEvent";
export { forcePiClacksEvent } from "../piClacksEvent";
export { forceSeedPodsEvent } from "../seedPodsEvent";
export { forceRippleFireEvent } from "../rippleFireEvent";
export { forceSparkChamberEvent } from "../sparkChamberEvent";
export { forceTurbineEvent } from "../turbineEvent";
export { forceStrangeAttractorEvent } from "../strangeAttractorEvent";
export { forceTopsyTurvyEvent } from "../topsyTurvyEvent";
export { forceGoldPlatingEvent } from "../goldPlatingEvent";
export { forceCrosswindEvent } from "../crosswindEvent";
export { forceHailstoneEvent } from "../hailstoneEvent";
export { forceHilbertCurveEvent } from "../hilbertCurveEvent";
export { forceLeMansEvent } from "../leMansEvent";
export { forceTunnelBorerEvent } from "../tunnelBorerEvent";
export { forceHarpoonEvent } from "../harpoonEvent";
export { forceEightQueensEvent } from "../eightQueensEvent";
export { forceShortestPathEvent } from "../shortestPathEvent";
export { forceSinkholeEvent } from "../sinkholeEvent";
export { forceBackwashEvent } from "../backwashEvent";
export { forceDeflectorEvent } from "../deflectorEvent";
export { forceSunflowerEvent } from "../sunflowerEvent";
export { forceConvexHullEvent } from "../convexHullEvent";
export { forceSlashEvent } from "../slashEvent";
export { forceJackhammerEvent } from "../jackhammerEvent";
export { forcePummelEvent } from "../pummelEvent";
export { forceOverloadEvent } from "../overloadEvent";
export { forceGatlingEvent } from "../gatlingEvent";
export { forcePressEvent } from "../pressEvent";
export { forceDrillEvent } from "../drillEvent";
export { forceBurrowEvent } from "../burrowEvent";
export { forcePingPongEvent } from "../pingPongEvent";
export { forceSlamDunkEvent } from "../slamDunkEvent";
export { forceUppercutEvent } from "../uppercutEvent";
export { forceHeadHopEvent } from "../headHopEvent";
export { forcePaparazziEvent } from "../paparazziEvent";
export { forceMissileBarrageEvent } from "../missileBarrageEvent";
export { forceSonicBoomEvent } from "../sonicBoomEvent";
export { forceMitosisEvent } from "../mitosisEvent";
export { forcePlinkoEvent } from "../plinkoEvent";
export { forceHammerThrowEvent } from "../hammerThrowEvent";
export { forceSnakeEvent } from "../snakeEvent";
export { forceBreakoutEvent } from "../breakoutEvent";
export { forceLineClearEvent } from "../lineClearEvent";
export { forceBreakShotEvent } from "../breakShotEvent";
export { forceBulletHellEvent } from "../bulletHellEvent";
export { forceVortexEvent } from "../vortexEvent";
export { forceRicochetEvent } from "../ricochetEvent";
export { forceWaterfallEvent } from "../waterfallEvent";
export { forceConveyorEvent } from "../conveyorEvent";
export { forceFirefliesEvent } from "../firefliesEvent";
export { forceStreamEvent } from "../streamEvent";
export { forceTrailsEvent } from "../trailsEvent";
export { forceDrawEvent } from "../drawEvent";
export { forceNightSkyEvent } from "../nightSkyEvent";
export { forcePitcherEvent } from "../pitcherEvent";
export { forceGlimmerEvent } from "../glimmerEvent";
export { forceRenovateEvent } from "../renovateEvent";
export { forceUpgradeEvent } from "../upgradeEvent";
export { forceUnlockEvent } from "../unlockEvent";
