// event modules, part 5 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../toasterEvent";
import "../xylophoneEvent";
import "../birthdayCandlesEvent";
import "../dropTowerEvent";
import "../arrowVolleyEvent";
import "../makeAWishEvent";
import "../blunderbussEvent";
import "../genieEvent";
import "../solarFlareEvent";
import "../heatVisionEvent";
import "../printHeadEvent";
import "../auroraEvent";
import "../thunderRingsEvent";
import "../arcWeldEvent";
import "../stormKiteEvent";
import "../volcanicLightningEvent";
import "../sculptorEvent";
import "../grandFinaleEvent";
import "../bombBouquetEvent";
import "../cascadeEvent";
import "../pinballBombEvent";
import "../bombTrainEvent";
import "../breachingChargeEvent";
import "../confettiCannonEvent";
import "../ammoBeltEvent";
import "../gauntletEvent";
import "../turretTowerEvent";
import "../shellCasingsEvent";
import "../dartsEvent";
import "../battleshipEvent";
import "../interceptorsEvent";
import "../landGrabEvent";
import "../duckDuckGooseEvent";
import "../ringerEvent";
import "../hurdlesEvent";
import "../luckyRollEvent";
import "../cashRegisterEvent";
import "../horseRaceEvent";
import "../dunkTankEvent";
import "../halfPipeEvent";
import "../knotEvent";
import "../tickerTapeEvent";
import "../cashBridgeEvent";
import "../skippingStoneEvent";
import "../woodpeckerEvent";
import "../frisbeeEvent";
import "../kangarooEvent";
import "../badmintonEvent";
import "../tumbleweedEvent";
import "../shuttleRunEvent";
import "../echolocationEvent";
import "../lacrosseEvent";
import "../jetSkiEvent";
import "../drinkingStrawEvent";
import "../seaSerpentEvent";
import "../magicTrickEvent";
import "../fountainPenEvent";
import "../spoolEvent";
import "../laserRainEvent";
import "../crossCutEvent";
import "../heliographEvent";
import "../starburstEvent";
import "../thunderDrumEvent";
import "../boltBarrageEvent";
import "../coilgunEvent";
import "../snowflakeEvent";
import "../bombSnakeEvent";
import "../spiderMinesEvent";
import "../crossetteEvent";
import "../spiralChargeEvent";
import "../bombBubblesEvent";
import "../rocketSledEvent";
import "../dynamiteFishingEvent";
import "../chargeShotEvent";
import "../corkscrewRoundsEvent";
import "../orbitalGunsEvent";
import "../tracerRoundsEvent";
import "../pelletStormEvent";
import "../bulletSnakeEvent";
import "../rockPaperScissorsEvent";
import "../limboEvent";
import "../quizShowEvent";
import "../sumoEvent";
import "../paperTossEvent";
import "../armWrestlingEvent";
import "../keepyUppyEvent";
import "../pinTheTailEvent";
import "../trustFallEvent";
import "../bubbleGumEvent";
import "../canalLocksEvent";
import "../bobsledEvent";
import "../springLoadedEvent";
import "../influxEvent";
import "../unevenBarsEvent";
import "../bumblebeeEvent";
import "../shotPutEvent";
import "../humanCannonballEvent";
import "../foxAndHoundsEvent";
import "../kingfisherEvent";
import "../joustEvent";
import "../pelicanEvent";
import "../dragsterEvent";
import "../fireBreatherEvent";
import "../bucketSwingEvent";
import "../puppeteerEvent";
import "../coronaEvent";
import "../pillarsEvent";
import "../laserLadderEvent";
import "../beamSplitterEvent";
import "../teleporterEvent";
import "../ringLightEvent";
import "../taserEvent";
import "../arcFurnaceEvent";
import "../fiveFingersEvent";
import "../cattleProdEvent";
import "../boltSlingEvent";
import "../collidingStormsEvent";
import "../bombJugglerEvent";
import "../bombSquadEvent";
import "../splitterEvent";
import "../bombPendulumEvent";
import "../paradropEvent";
import "../bombPachinkoEvent";
import "../fuseClockEvent";
import "../hedgehogEvent";
import "../splitShotEvent";
import "../bulletLassoEvent";
import "../bulletWeaveEvent";
import "../bulletFountainEvent";
import "../coveringFireEvent";
import "../checkersEvent";
import "../minesweeperEvent";
import "../jackInTheBoxEvent";
import "../spillwayEvent";
import "../crosscurrentsEvent";
import "../oxbowEvent";
import "../breakersEvent";
import "../rivuletsEvent";
import "../torrentEvent";
import "../lissajousEvent";
// the dev test bar's hooks
export { forceToasterEvent } from "../toasterEvent";
export { forceXylophoneEvent } from "../xylophoneEvent";
export { forceBirthdayCandlesEvent } from "../birthdayCandlesEvent";
export { forceDropTowerEvent } from "../dropTowerEvent";
export { forceArrowVolleyEvent } from "../arrowVolleyEvent";
export { forceMakeAWishEvent } from "../makeAWishEvent";
export { forceBlunderbussEvent } from "../blunderbussEvent";
export { forceGenieEvent } from "../genieEvent";
export { forceSolarFlareEvent } from "../solarFlareEvent";
export { forceHeatVisionEvent } from "../heatVisionEvent";
export { forcePrintHeadEvent } from "../printHeadEvent";
export { forceAuroraEvent } from "../auroraEvent";
export { forceThunderRingsEvent } from "../thunderRingsEvent";
export { forceArcWeldEvent } from "../arcWeldEvent";
export { forceStormKiteEvent } from "../stormKiteEvent";
export { forceVolcanicLightningEvent } from "../volcanicLightningEvent";
export { forceSculptorEvent } from "../sculptorEvent";
export { forceGrandFinaleEvent } from "../grandFinaleEvent";
export { forceBombBouquetEvent } from "../bombBouquetEvent";
export { forceCascadeEvent } from "../cascadeEvent";
export { forcePinballBombEvent } from "../pinballBombEvent";
export { forceBombTrainEvent } from "../bombTrainEvent";
export { forceBreachingChargeEvent } from "../breachingChargeEvent";
export { forceConfettiCannonEvent } from "../confettiCannonEvent";
export { forceAmmoBeltEvent } from "../ammoBeltEvent";
export { forceGauntletEvent } from "../gauntletEvent";
export { forceTurretTowerEvent } from "../turretTowerEvent";
export { forceShellCasingsEvent } from "../shellCasingsEvent";
export { forceDartsEvent } from "../dartsEvent";
export { forceBattleshipEvent } from "../battleshipEvent";
export { forceInterceptorsEvent } from "../interceptorsEvent";
export { forceLandGrabEvent } from "../landGrabEvent";
export { forceDuckDuckGooseEvent } from "../duckDuckGooseEvent";
export { forceRingerEvent } from "../ringerEvent";
export { forceHurdlesEvent } from "../hurdlesEvent";
export { forceLuckyRollEvent } from "../luckyRollEvent";
export { forceCashRegisterEvent } from "../cashRegisterEvent";
export { forceHorseRaceEvent } from "../horseRaceEvent";
export { forceDunkTankEvent } from "../dunkTankEvent";
export { forceHalfPipeEvent } from "../halfPipeEvent";
export { forceKnotEvent } from "../knotEvent";
export { forceTickerTapeEvent } from "../tickerTapeEvent";
export { forceCashBridgeEvent } from "../cashBridgeEvent";
export { forceSkippingStoneEvent } from "../skippingStoneEvent";
export { forceWoodpeckerEvent } from "../woodpeckerEvent";
export { forceFrisbeeEvent } from "../frisbeeEvent";
export { forceKangarooEvent } from "../kangarooEvent";
export { forceBadmintonEvent } from "../badmintonEvent";
export { forceTumbleweedEvent } from "../tumbleweedEvent";
export { forceShuttleRunEvent } from "../shuttleRunEvent";
export { forceEcholocationEvent } from "../echolocationEvent";
export { forceLacrosseEvent } from "../lacrosseEvent";
export { forceJetSkiEvent } from "../jetSkiEvent";
export { forceDrinkingStrawEvent } from "../drinkingStrawEvent";
export { forceSeaSerpentEvent } from "../seaSerpentEvent";
export { forceMagicTrickEvent } from "../magicTrickEvent";
export { forceFountainPenEvent } from "../fountainPenEvent";
export { forceSpoolEvent } from "../spoolEvent";
export { forceLaserRainEvent } from "../laserRainEvent";
export { forceCrossCutEvent } from "../crossCutEvent";
export { forceHeliographEvent } from "../heliographEvent";
export { forceStarburstEvent } from "../starburstEvent";
export { forceThunderDrumEvent } from "../thunderDrumEvent";
export { forceBoltBarrageEvent } from "../boltBarrageEvent";
export { forceCoilgunEvent } from "../coilgunEvent";
export { forceSnowflakeEvent } from "../snowflakeEvent";
export { forceBombSnakeEvent } from "../bombSnakeEvent";
export { forceSpiderMinesEvent } from "../spiderMinesEvent";
export { forceCrossetteEvent } from "../crossetteEvent";
export { forceSpiralChargeEvent } from "../spiralChargeEvent";
export { forceBombBubblesEvent } from "../bombBubblesEvent";
export { forceRocketSledEvent } from "../rocketSledEvent";
export { forceDynamiteFishingEvent } from "../dynamiteFishingEvent";
export { forceChargeShotEvent } from "../chargeShotEvent";
export { forceCorkscrewRoundsEvent } from "../corkscrewRoundsEvent";
export { forceOrbitalGunsEvent } from "../orbitalGunsEvent";
export { forceTracerRoundsEvent } from "../tracerRoundsEvent";
export { forcePelletStormEvent } from "../pelletStormEvent";
export { forceBulletSnakeEvent } from "../bulletSnakeEvent";
export { forceRockPaperScissorsEvent } from "../rockPaperScissorsEvent";
export { forceLimboEvent } from "../limboEvent";
export { forceQuizShowEvent } from "../quizShowEvent";
export { forceSumoEvent } from "../sumoEvent";
export { forcePaperTossEvent } from "../paperTossEvent";
export { forceArmWrestlingEvent } from "../armWrestlingEvent";
export { forceKeepyUppyEvent } from "../keepyUppyEvent";
export { forcePinTheTailEvent } from "../pinTheTailEvent";
export { forceTrustFallEvent } from "../trustFallEvent";
export { forceBubbleGumEvent } from "../bubbleGumEvent";
export { forceCanalLocksEvent } from "../canalLocksEvent";
export { forceBobsledEvent } from "../bobsledEvent";
export { forceSpringLoadedEvent } from "../springLoadedEvent";
export { forceInfluxEvent } from "../influxEvent";
export { forceUnevenBarsEvent } from "../unevenBarsEvent";
export { forceBumblebeeEvent } from "../bumblebeeEvent";
export { forceShotPutEvent } from "../shotPutEvent";
export { forceHumanCannonballEvent } from "../humanCannonballEvent";
export { forceFoxAndHoundsEvent } from "../foxAndHoundsEvent";
export { forceKingfisherEvent } from "../kingfisherEvent";
export { forceJoustEvent } from "../joustEvent";
export { forcePelicanEvent } from "../pelicanEvent";
export { forceDragsterEvent } from "../dragsterEvent";
export { forceFireBreatherEvent } from "../fireBreatherEvent";
export { forceBucketSwingEvent } from "../bucketSwingEvent";
export { forcePuppeteerEvent } from "../puppeteerEvent";
export { forceCoronaEvent } from "../coronaEvent";
export { forcePillarsEvent } from "../pillarsEvent";
export { forceLaserLadderEvent } from "../laserLadderEvent";
export { forceBeamSplitterEvent } from "../beamSplitterEvent";
export { forceTeleporterEvent } from "../teleporterEvent";
export { forceRingLightEvent } from "../ringLightEvent";
export { forceTaserEvent } from "../taserEvent";
export { forceArcFurnaceEvent } from "../arcFurnaceEvent";
export { forceFiveFingersEvent } from "../fiveFingersEvent";
export { forceCattleProdEvent } from "../cattleProdEvent";
export { forceBoltSlingEvent } from "../boltSlingEvent";
export { forceCollidingStormsEvent } from "../collidingStormsEvent";
export { forceBombJugglerEvent } from "../bombJugglerEvent";
export { forceBombSquadEvent } from "../bombSquadEvent";
export { forceSplitterEvent } from "../splitterEvent";
export { forceBombPendulumEvent } from "../bombPendulumEvent";
export { forceParadropEvent } from "../paradropEvent";
export { forceBombPachinkoEvent } from "../bombPachinkoEvent";
export { forceFuseClockEvent } from "../fuseClockEvent";
export { forceHedgehogEvent } from "../hedgehogEvent";
export { forceSplitShotEvent } from "../splitShotEvent";
export { forceBulletLassoEvent } from "../bulletLassoEvent";
export { forceBulletWeaveEvent } from "../bulletWeaveEvent";
export { forceBulletFountainEvent } from "../bulletFountainEvent";
export { forceCoveringFireEvent } from "../coveringFireEvent";
export { forceCheckersEvent } from "../checkersEvent";
export { forceMinesweeperEvent } from "../minesweeperEvent";
export { forceJackInTheBoxEvent } from "../jackInTheBoxEvent";
export { forceSpillwayEvent } from "../spillwayEvent";
export { forceCrosscurrentsEvent } from "../crosscurrentsEvent";
export { forceOxbowEvent } from "../oxbowEvent";
export { forceBreakersEvent } from "../breakersEvent";
export { forceRivuletsEvent } from "../rivuletsEvent";
export { forceTorrentEvent } from "../torrentEvent";
export { forceLissajousEvent } from "../lissajousEvent";
