// event modules, part 6 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../moonHopEvent";
import "../peekabooEvent";
import "../tiltAWhirlEvent";
import "../waterStriderEvent";
import "../ropeClimbEvent";
import "../paddleSteamerEvent";
import "../jetWashEvent";
import "../bellowsEvent";
import "../rainDanceEvent";
import "../skiTowEvent";
import "../ribbonDancerEvent";
import "../laserTurnstileEvent";
import "../lightBridgeEvent";
import "../laserWebEvent";
import "../footlightsEvent";
import "../fusionBeamEvent";
import "../pinpointEvent";
import "../galvanizeEvent";
import "../sparkJumpEvent";
import "../staticClingEvent";
import "../capacitorEvent";
import "../sparkTrainEvent";
import "../arcBridgeEvent";
import "../daisyCutterEvent";
import "../rippleMinesEvent";
import "../bombYoYoEvent";
import "../bombHailEvent";
import "../groundPoundEvent";
import "../cherryBombEvent";
import "../bombCrownEvent";
import "../bulletCombEvent";
import "../bulletBraidEvent";
import "../bulletCageEvent";
import "../gunslingerEvent";
import "../bulletWheelEvent";
import "../bulletLadderEvent";
import "../whipZoomEvent";
import "../irisOutEvent";
import "../screenReelsEvent";
import "../goldLeafEvent";
import "../pixelStormEvent";
import "../gravityFlipEvent";
import "../echoEvent";
import "../mirrorBoxEvent";
import "../pullBackEvent";
import "../treadmillEvent";
import "../blastOffEvent";
import "../popUpEvent";
import "../stickerPeelEvent";
import "../glissandoEvent";
import "../vaultDoorsEvent";
import "../champagneTowerEvent";
import "../pinballRiverEvent";
import "../pressureWasherEvent";
import "../irrigationEvent";
import "../waterspoutEvent";
import "../sidewinderEvent";
import "../orbitSwapEvent";
import "../cuckooEvent";
import "../gyreEvent";
import "../barHopEvent";
import "../cometPlowEvent";
import "../hoseReelEvent";
import "../geyserRiderEvent";
import "../bubbleBlowerEvent";
import "../poolDiveEvent";
import "../rubberBandEvent";
import "../beamViseEvent";
import "../laserRakeEvent";
import "../lightDominoesEvent";
import "../pryBarEvent";
import "../teslaTennisEvent";
import "../tuningForkEvent";
import "../boltSpiralEvent";
import "../groundCurrentEvent";
import "../overchargeEvent";
import "../bombTornadoEvent";
import "../bombBoomerangEvent";
import "../multistageEvent";
import "../bombPileEvent";
import "../bombGarlandEvent";
import "../homingRoundsEvent";
import "../waveCannonEvent";
import "../snapbackEvent";
import "../bulletFunnelEvent";
import "../crisscrossEvent";
import "../chainFountainEvent";
import "../smokeRingsEvent";
import "../waterSaluteEvent";
import "../doublePendulumEvent";
import "../trapezeEvent";
import "../diaboloEvent";
import "../zorbEvent";
import "../hoopDiveEvent";
import "../spinArtEvent";
import "../paperCutterEvent";
import "../flippersEvent";
import "../drawbridgeEvent";
import "../flailEvent";
import "../vineSwingEvent";
import "../bombSnowballEvent";
import "../gerbEvent";
import "../recoilEvent";
import "../tumbleFireEvent";
import "../rollUpEvent";
import "../shredderEvent";
import "../headOnEvent";
import "../pyramidEvent";
import "../pizzaTossEvent";
import "../compassEvent";
import "../skewerEvent";
import "../bombCometEvent";
import "../kaboomEvent";
import "../returnFireEvent";
import "../frostedGlassEvent";
import "../switchOffEvent";
import "../stuntTrackEvent";
import "../fleasEvent";
import "../handPumpEvent";
import "../pickUpSticksEvent";
import "../thunderShellEvent";
import "../midAirEvent";
import "../chainFireEvent";
import "../rimShotEvent";
import "../tinRoofEvent";
import "../crumpleEvent";
import "../minimizeEvent";
import "../jumpingJetsEvent";
import "../bubbleChamberEvent";
import "../castNetEvent";
import "../hobermanEvent";
import "../excaliburEvent";
import "../pistonsEvent";
import "../williamTellEvent";
import "../foosballEvent";
import "../rubberSheetEvent";
import "../rattleEvent";
import "../eddiesEvent";
import "../tubeManEvent";
import "../deflateEvent";
// the dev test bar's hooks
export { forceMoonHopEvent } from "../moonHopEvent";
export { forcePeekabooEvent } from "../peekabooEvent";
export { forceTiltAWhirlEvent } from "../tiltAWhirlEvent";
export { forceWaterStriderEvent } from "../waterStriderEvent";
export { forceRopeClimbEvent } from "../ropeClimbEvent";
export { forcePaddleSteamerEvent } from "../paddleSteamerEvent";
export { forceJetWashEvent } from "../jetWashEvent";
export { forceBellowsEvent } from "../bellowsEvent";
export { forceRainDanceEvent } from "../rainDanceEvent";
export { forceSkiTowEvent } from "../skiTowEvent";
export { forceRibbonDancerEvent } from "../ribbonDancerEvent";
export { forceLaserTurnstileEvent } from "../laserTurnstileEvent";
export { forceLightBridgeEvent } from "../lightBridgeEvent";
export { forceLaserWebEvent } from "../laserWebEvent";
export { forceFootlightsEvent } from "../footlightsEvent";
export { forceFusionBeamEvent } from "../fusionBeamEvent";
export { forcePinpointEvent } from "../pinpointEvent";
export { forceGalvanizeEvent } from "../galvanizeEvent";
export { forceSparkJumpEvent } from "../sparkJumpEvent";
export { forceStaticClingEvent } from "../staticClingEvent";
export { forceCapacitorEvent } from "../capacitorEvent";
export { forceSparkTrainEvent } from "../sparkTrainEvent";
export { forceArcBridgeEvent } from "../arcBridgeEvent";
export { forceDaisyCutterEvent } from "../daisyCutterEvent";
export { forceRippleMinesEvent } from "../rippleMinesEvent";
export { forceBombYoYoEvent } from "../bombYoYoEvent";
export { forceBombHailEvent } from "../bombHailEvent";
export { forceGroundPoundEvent } from "../groundPoundEvent";
export { forceCherryBombEvent } from "../cherryBombEvent";
export { forceBombCrownEvent } from "../bombCrownEvent";
export { forceBulletCombEvent } from "../bulletCombEvent";
export { forceBulletBraidEvent } from "../bulletBraidEvent";
export { forceBulletCageEvent } from "../bulletCageEvent";
export { forceGunslingerEvent } from "../gunslingerEvent";
export { forceBulletWheelEvent } from "../bulletWheelEvent";
export { forceBulletLadderEvent } from "../bulletLadderEvent";
export { forceWhipZoomEvent } from "../whipZoomEvent";
export { forceIrisOutEvent } from "../irisOutEvent";
export { forceScreenReelsEvent } from "../screenReelsEvent";
export { forceGoldLeafEvent } from "../goldLeafEvent";
export { forcePixelStormEvent } from "../pixelStormEvent";
export { forceGravityFlipEvent } from "../gravityFlipEvent";
export { forceEchoEvent } from "../echoEvent";
export { forceMirrorBoxEvent } from "../mirrorBoxEvent";
export { forcePullBackEvent } from "../pullBackEvent";
export { forceTreadmillEvent } from "../treadmillEvent";
export { forceBlastOffEvent } from "../blastOffEvent";
export { forcePopUpEvent } from "../popUpEvent";
export { forceStickerPeelEvent } from "../stickerPeelEvent";
export { forceGlissandoEvent } from "../glissandoEvent";
export { forceVaultDoorsEvent } from "../vaultDoorsEvent";
export { forceChampagneTowerEvent } from "../champagneTowerEvent";
export { forcePinballRiverEvent } from "../pinballRiverEvent";
export { forcePressureWasherEvent } from "../pressureWasherEvent";
export { forceIrrigationEvent } from "../irrigationEvent";
export { forceWaterspoutEvent } from "../waterspoutEvent";
export { forceSidewinderEvent } from "../sidewinderEvent";
export { forceOrbitSwapEvent } from "../orbitSwapEvent";
export { forceCuckooEvent } from "../cuckooEvent";
export { forceGyreEvent } from "../gyreEvent";
export { forceBarHopEvent } from "../barHopEvent";
export { forceCometPlowEvent } from "../cometPlowEvent";
export { forceHoseReelEvent } from "../hoseReelEvent";
export { forceGeyserRiderEvent } from "../geyserRiderEvent";
export { forceBubbleBlowerEvent } from "../bubbleBlowerEvent";
export { forcePoolDiveEvent } from "../poolDiveEvent";
export { forceRubberBandEvent } from "../rubberBandEvent";
export { forceBeamViseEvent } from "../beamViseEvent";
export { forceLaserRakeEvent } from "../laserRakeEvent";
export { forceLightDominoesEvent } from "../lightDominoesEvent";
export { forcePryBarEvent } from "../pryBarEvent";
export { forceTeslaTennisEvent } from "../teslaTennisEvent";
export { forceTuningForkEvent } from "../tuningForkEvent";
export { forceBoltSpiralEvent } from "../boltSpiralEvent";
export { forceGroundCurrentEvent } from "../groundCurrentEvent";
export { forceOverchargeEvent } from "../overchargeEvent";
export { forceBombTornadoEvent } from "../bombTornadoEvent";
export { forceBombBoomerangEvent } from "../bombBoomerangEvent";
export { forceMultistageEvent } from "../multistageEvent";
export { forceBombPileEvent } from "../bombPileEvent";
export { forceBombGarlandEvent } from "../bombGarlandEvent";
export { forceHomingRoundsEvent } from "../homingRoundsEvent";
export { forceWaveCannonEvent } from "../waveCannonEvent";
export { forceSnapbackEvent } from "../snapbackEvent";
export { forceBulletFunnelEvent } from "../bulletFunnelEvent";
export { forceCrisscrossEvent } from "../crisscrossEvent";
export { forceChainFountainEvent } from "../chainFountainEvent";
export { forceSmokeRingsEvent } from "../smokeRingsEvent";
export { forceWaterSaluteEvent } from "../waterSaluteEvent";
export { forceDoublePendulumEvent } from "../doublePendulumEvent";
export { forceTrapezeEvent } from "../trapezeEvent";
export { forceDiaboloEvent } from "../diaboloEvent";
export { forceZorbEvent } from "../zorbEvent";
export { forceHoopDiveEvent } from "../hoopDiveEvent";
export { forceSpinArtEvent } from "../spinArtEvent";
export { forcePaperCutterEvent } from "../paperCutterEvent";
export { forceFlippersEvent } from "../flippersEvent";
export { forceDrawbridgeEvent } from "../drawbridgeEvent";
export { forceFlailEvent } from "../flailEvent";
export { forceVineSwingEvent } from "../vineSwingEvent";
export { forceBombSnowballEvent } from "../bombSnowballEvent";
export { forceGerbEvent } from "../gerbEvent";
export { forceRecoilEvent } from "../recoilEvent";
export { forceTumbleFireEvent } from "../tumbleFireEvent";
export { forceRollUpEvent } from "../rollUpEvent";
export { forceShredderEvent } from "../shredderEvent";
export { forceHeadOnEvent } from "../headOnEvent";
export { forcePyramidEvent } from "../pyramidEvent";
export { forcePizzaTossEvent } from "../pizzaTossEvent";
export { forceCompassEvent } from "../compassEvent";
export { forceSkewerEvent } from "../skewerEvent";
export { forceBombCometEvent } from "../bombCometEvent";
export { forceKaboomEvent } from "../kaboomEvent";
export { forceReturnFireEvent } from "../returnFireEvent";
export { forceFrostedGlassEvent } from "../frostedGlassEvent";
export { forceSwitchOffEvent } from "../switchOffEvent";
export { forceStuntTrackEvent } from "../stuntTrackEvent";
export { forceFleasEvent } from "../fleasEvent";
export { forceHandPumpEvent } from "../handPumpEvent";
export { forcePickUpSticksEvent } from "../pickUpSticksEvent";
export { forceThunderShellEvent } from "../thunderShellEvent";
export { forceMidAirEvent } from "../midAirEvent";
export { forceChainFireEvent } from "../chainFireEvent";
export { forceRimShotEvent } from "../rimShotEvent";
export { forceTinRoofEvent } from "../tinRoofEvent";
export { forceCrumpleEvent } from "../crumpleEvent";
export { forceMinimizeEvent } from "../minimizeEvent";
export { forceJumpingJetsEvent } from "../jumpingJetsEvent";
export { forceBubbleChamberEvent } from "../bubbleChamberEvent";
export { forceCastNetEvent } from "../castNetEvent";
export { forceHobermanEvent } from "../hobermanEvent";
export { forceExcaliburEvent } from "../excaliburEvent";
export { forcePistonsEvent } from "../pistonsEvent";
export { forceWilliamTellEvent } from "../williamTellEvent";
export { forceFoosballEvent } from "../foosballEvent";
export { forceRubberSheetEvent } from "../rubberSheetEvent";
export { forceRattleEvent } from "../rattleEvent";
export { forceEddiesEvent } from "../eddiesEvent";
export { forceTubeManEvent } from "../tubeManEvent";
export { forceDeflateEvent } from "../deflateEvent";
