// event modules, part 2 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../mercuryEvent";
import "../alignmentEvent";
import "../dandelionEvent";
import "../bobberEvent";
import "../fishingEvent";
import "../scissorsEvent";
import "../pulseRifleEvent";
import "../splitEvent";
import "../pixelateEvent";
import "../damBurstEvent";
import "../spiderwebEvent";
import "../curtainEvent";
import "../jellyfishEvent";
import "../polarityEvent";
import "../colliderEvent";
import "../sheepdogEvent";
import "../dragonEvent";
import "../reflectorEvent";
import "../cookieCutterEvent";
import "../cinematicEvent";
import "../negativeEvent";
import "../chainLightningEvent";
import "../lockOnEvent";
import "../stitchEvent";
import "../stockpileEvent";
import "../spotWeldEvent";
import "../reelsEvent";
import "../cashShowerEvent";
import "../catherineWheelEvent";
import "../multiballEvent";
import "../whipEvent";
import "../batteryEvent";
import "../teslaCoilEvent";
import "../jacobsLadderEvent";
import "../comicBookEvent";
import "../avalancheEvent";
import "../beehiveEvent";
import "../pogoEvent";
import "../laserHarpEvent";
import "../lichtenbergEvent";
import "../shatterEvent";
import "../funnelEvent";
import "../grappleEvent";
import "../surfEvent";
import "../laserTagEvent";
import "../ballLightningEvent";
import "../eventHorizonEvent";
import "../tileFlipEvent";
import "../gusherEvent";
import "../pinataEvent";
import "../giftWrapEvent";
import "../triangulateEvent";
import "../sparkOfLifeEvent";
import "../glassRainEvent";
import "../foldEvent";
import "../cocoonEvent";
import "../gravityAssistEvent";
import "../zipLineEvent";
import "../breachEvent";
import "../stormSurgeEvent";
import "../smashAndGrabEvent";
import "../shrinkRayEvent";
import "../sandstormEvent";
import "../juggernautEvent";
import "../fuelLineEvent";
import "../checkoutEvent";
import "../lightningRodEvent";
import "../flagEvent";
import "../terracesEvent";
import "../batteringRamEvent";
import "../tetherballEvent";
import "../projectorEvent";
import "../clearEvent";
import "../infinityMirrorEvent";
import "../elevatorEvent";
import "../migrationEvent";
import "../corkscrewEvent";
import "../mirrorBallEvent";
import "../plasmaGlobeEvent";
import "../jellyEvent";
import "../shockwaveEvent";
import "../passTheParcelEvent";
import "../gardenHoseEvent";
import "../burningGlassEvent";
import "../stormFrontEvent";
import "../slidePuzzleEvent";
import "../whirlpoolEvent";
import "../satellitesEvent";
import "../typewriterEvent";
import "../railgunEvent";
import "../thunderdomeEvent";
import "../meltEvent";
import "../floodEvent";
import "../piedPiperEvent";
import "../tentaclesEvent";
import "../laserPendulumEvent";
import "../electricEelEvent";
import "../doubleVisionEvent";
import "../honeyEvent";
import "../musicalChairsEvent";
import "../bubbleWandEvent";
import "../hyperspaceEvent";
import "../javelinEvent";
import "../shuffleEvent";
import "../mushroomCloudEvent";
import "../relayEvent";
import "../laserPointerEvent";
import "../stormChaserEvent";
import "../baitBallEvent";
import "../videoWallEvent";
import "../ferrofluidEvent";
import "../hideAndSeekEvent";
import "../magicCarpetEvent";
import "../spirographEvent";
import "../electricNetEvent";
import "../demolitionEvent";
import "../shootingGalleryEvent";
import "../collapseEvent";
import "../volcanoEvent";
import "../skydiversEvent";
import "../speedboatEvent";
import "../peacockEvent";
import "../stormWingsEvent";
import "../clusterBombEvent";
import "../strafingRunEvent";
import "../stainedGlassEvent";
import "../uprisingEvent";
import "../swingRideEvent";
import "../lawnmowerEvent";
import "../lightShowEvent";
import "../bugZapperEvent";
import "../firecrackersEvent";
import "../sixShooterEvent";
import "../thermalEvent";
import "../stalactitesEvent";
import "../kintsugiEvent";
import "../galaxyEvent";
import "../snowdriftEvent";
import "../snowballEvent";
import "../cartwheelEvent";
// the dev test bar's hooks
export { forceMercuryEvent } from "../mercuryEvent";
export { forceAlignmentEvent } from "../alignmentEvent";
export { forceDandelionEvent } from "../dandelionEvent";
export { forceBobberEvent } from "../bobberEvent";
export { forceFishingEvent } from "../fishingEvent";
export { forceScissorsEvent } from "../scissorsEvent";
export { forcePulseRifleEvent } from "../pulseRifleEvent";
export { forceSplitEvent } from "../splitEvent";
export { forcePixelateEvent } from "../pixelateEvent";
export { forceDamBurstEvent } from "../damBurstEvent";
export { forceSpiderwebEvent } from "../spiderwebEvent";
export { forceCurtainEvent } from "../curtainEvent";
export { forceJellyfishEvent } from "../jellyfishEvent";
export { forcePolarityEvent } from "../polarityEvent";
export { forceColliderEvent } from "../colliderEvent";
export { forceSheepdogEvent } from "../sheepdogEvent";
export { forceDragonEvent } from "../dragonEvent";
export { forceReflectorEvent } from "../reflectorEvent";
export { forceCookieCutterEvent } from "../cookieCutterEvent";
export { forceCinematicEvent } from "../cinematicEvent";
export { forceNegativeEvent } from "../negativeEvent";
export { forceChainLightningEvent } from "../chainLightningEvent";
export { forceLockOnEvent } from "../lockOnEvent";
export { forceStitchEvent } from "../stitchEvent";
export { forceStockpileEvent } from "../stockpileEvent";
export { forceSpotWeldEvent } from "../spotWeldEvent";
export { forceReelsEvent } from "../reelsEvent";
export { forceCashShowerEvent } from "../cashShowerEvent";
export { forceCatherineWheelEvent } from "../catherineWheelEvent";
export { forceMultiballEvent } from "../multiballEvent";
export { forceWhipEvent } from "../whipEvent";
export { forceBatteryEvent } from "../batteryEvent";
export { forceTeslaCoilEvent } from "../teslaCoilEvent";
export { forceJacobsLadderEvent } from "../jacobsLadderEvent";
export { forceComicBookEvent } from "../comicBookEvent";
export { forceAvalancheEvent } from "../avalancheEvent";
export { forceBeehiveEvent } from "../beehiveEvent";
export { forcePogoEvent } from "../pogoEvent";
export { forceLaserHarpEvent } from "../laserHarpEvent";
export { forceLichtenbergEvent } from "../lichtenbergEvent";
export { forceShatterEvent } from "../shatterEvent";
export { forceFunnelEvent } from "../funnelEvent";
export { forceGrappleEvent } from "../grappleEvent";
export { forceSurfEvent } from "../surfEvent";
export { forceLaserTagEvent } from "../laserTagEvent";
export { forceBallLightningEvent } from "../ballLightningEvent";
export { forceEventHorizonEvent } from "../eventHorizonEvent";
export { forceTileFlipEvent } from "../tileFlipEvent";
export { forceGusherEvent } from "../gusherEvent";
export { forcePinataEvent } from "../pinataEvent";
export { forceGiftWrapEvent } from "../giftWrapEvent";
export { forceTriangulateEvent } from "../triangulateEvent";
export { forceSparkOfLifeEvent } from "../sparkOfLifeEvent";
export { forceGlassRainEvent } from "../glassRainEvent";
export { forceFoldEvent } from "../foldEvent";
export { forceCocoonEvent } from "../cocoonEvent";
export { forceGravityAssistEvent } from "../gravityAssistEvent";
export { forceZipLineEvent } from "../zipLineEvent";
export { forceBreachEvent } from "../breachEvent";
export { forceStormSurgeEvent } from "../stormSurgeEvent";
export { forceSmashAndGrabEvent } from "../smashAndGrabEvent";
export { forceShrinkRayEvent } from "../shrinkRayEvent";
export { forceSandstormEvent } from "../sandstormEvent";
export { forceJuggernautEvent } from "../juggernautEvent";
export { forceFuelLineEvent } from "../fuelLineEvent";
export { forceCheckoutEvent } from "../checkoutEvent";
export { forceLightningRodEvent } from "../lightningRodEvent";
export { forceFlagEvent } from "../flagEvent";
export { forceTerracesEvent } from "../terracesEvent";
export { forceBatteringRamEvent } from "../batteringRamEvent";
export { forceTetherballEvent } from "../tetherballEvent";
export { forceProjectorEvent } from "../projectorEvent";
export { forceClearEvent } from "../clearEvent";
export { forceInfinityMirrorEvent } from "../infinityMirrorEvent";
export { forceElevatorEvent } from "../elevatorEvent";
export { forceMigrationEvent } from "../migrationEvent";
export { forceCorkscrewEvent } from "../corkscrewEvent";
export { forceMirrorBallEvent } from "../mirrorBallEvent";
export { forcePlasmaGlobeEvent } from "../plasmaGlobeEvent";
export { forceJellyEvent } from "../jellyEvent";
export { forceShockwaveEvent } from "../shockwaveEvent";
export { forcePassTheParcelEvent } from "../passTheParcelEvent";
export { forceGardenHoseEvent } from "../gardenHoseEvent";
export { forceBurningGlassEvent } from "../burningGlassEvent";
export { forceStormFrontEvent } from "../stormFrontEvent";
export { forceSlidePuzzleEvent } from "../slidePuzzleEvent";
export { forceWhirlpoolEvent } from "../whirlpoolEvent";
export { forceSatellitesEvent } from "../satellitesEvent";
export { forceTypewriterEvent } from "../typewriterEvent";
export { forceRailgunEvent } from "../railgunEvent";
export { forceThunderdomeEvent } from "../thunderdomeEvent";
export { forceMeltEvent } from "../meltEvent";
export { forceFloodEvent } from "../floodEvent";
export { forcePiedPiperEvent } from "../piedPiperEvent";
export { forceTentaclesEvent } from "../tentaclesEvent";
export { forceLaserPendulumEvent } from "../laserPendulumEvent";
export { forceElectricEelEvent } from "../electricEelEvent";
export { forceDoubleVisionEvent } from "../doubleVisionEvent";
export { forceHoneyEvent } from "../honeyEvent";
export { forceMusicalChairsEvent } from "../musicalChairsEvent";
export { forceBubbleWandEvent } from "../bubbleWandEvent";
export { forceHyperspaceEvent } from "../hyperspaceEvent";
export { forceJavelinEvent } from "../javelinEvent";
export { forceShuffleEvent } from "../shuffleEvent";
export { forceMushroomCloudEvent } from "../mushroomCloudEvent";
export { forceRelayEvent } from "../relayEvent";
export { forceLaserPointerEvent } from "../laserPointerEvent";
export { forceStormChaserEvent } from "../stormChaserEvent";
export { forceBaitBallEvent } from "../baitBallEvent";
export { forceVideoWallEvent } from "../videoWallEvent";
export { forceFerrofluidEvent } from "../ferrofluidEvent";
export { forceHideAndSeekEvent } from "../hideAndSeekEvent";
export { forceMagicCarpetEvent } from "../magicCarpetEvent";
export { forceSpirographEvent } from "../spirographEvent";
export { forceElectricNetEvent } from "../electricNetEvent";
export { forceDemolitionEvent } from "../demolitionEvent";
export { forceShootingGalleryEvent } from "../shootingGalleryEvent";
export { forceCollapseEvent } from "../collapseEvent";
export { forceVolcanoEvent } from "../volcanoEvent";
export { forceSkydiversEvent } from "../skydiversEvent";
export { forceSpeedboatEvent } from "../speedboatEvent";
export { forcePeacockEvent } from "../peacockEvent";
export { forceStormWingsEvent } from "../stormWingsEvent";
export { forceClusterBombEvent } from "../clusterBombEvent";
export { forceStrafingRunEvent } from "../strafingRunEvent";
export { forceStainedGlassEvent } from "../stainedGlassEvent";
export { forceUprisingEvent } from "../uprisingEvent";
export { forceSwingRideEvent } from "../swingRideEvent";
export { forceLawnmowerEvent } from "../lawnmowerEvent";
export { forceLightShowEvent } from "../lightShowEvent";
export { forceBugZapperEvent } from "../bugZapperEvent";
export { forceFirecrackersEvent } from "../firecrackersEvent";
export { forceSixShooterEvent } from "../sixShooterEvent";
export { forceThermalEvent } from "../thermalEvent";
export { forceStalactitesEvent } from "../stalactitesEvent";
export { forceKintsugiEvent } from "../kintsugiEvent";
export { forceGalaxyEvent } from "../galaxyEvent";
export { forceSnowdriftEvent } from "../snowdriftEvent";
export { forceSnowballEvent } from "../snowballEvent";
export { forceCartwheelEvent } from "../cartwheelEvent";
