// event modules, part 4 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../courierEvent";
import "../rodeoEvent";
import "../crosshairEvent";
import "../irisEvent";
import "../bankShotEvent";
import "../sunbeamsEvent";
import "../stargateEvent";
import "../catsCradleEvent";
import "../thunderheadEvent";
import "../pitchforkEvent";
import "../jumperCablesEvent";
import "../lashEvent";
import "../sparkPlugEvent";
import "../liveWireEvent";
import "../fuseRaceEvent";
import "../bouncingBettyEvent";
import "../pressureCookerEvent";
import "../hotPotatoEvent";
import "../daisyChainEvent";
import "../shapedChargeEvent";
import "../detcordEvent";
import "../bulletBloomEvent";
import "../highNoonEvent";
import "../hailfireEvent";
import "../dervishEvent";
import "../invadersEvent";
import "../gunKataEvent";
import "../lockbusterEvent";
import "../connectFourEvent";
import "../comboEvent";
import "../skeeBallEvent";
import "../bubbleShooterEvent";
import "../deltaEvent";
import "../hydrantEvent";
import "../cloverleafEvent";
import "../pinstripeEvent";
import "../faucetEvent";
import "../showerheadEvent";
import "../binaryStarEvent";
import "../hopscotchEvent";
import "../tadpolesEvent";
import "../blinkEvent";
import "../bumperCarsEvent";
import "../pigeonsEvent";
import "../squidEvent";
import "../waterPistolEvent";
import "../poiEvent";
import "../bartenderEvent";
import "../poleVaultEvent";
import "../paintRollerEvent";
import "../buzzsawEvent";
import "../lightCyclesEvent";
import "../fiberOpticEvent";
import "../daddyLonglegsEvent";
import "../knighthoodEvent";
import "../cuttingTorchEvent";
import "../stElmosFireEvent";
import "../steppedLeaderEvent";
import "../trolleyEvent";
import "../boltBounceEvent";
import "../stormCrownEvent";
import "../vanDeGraaffEvent";
import "../barrelRollEvent";
import "../bombStackEvent";
import "../romanCandleEvent";
import "../whistlersEvent";
import "../trebuchetEvent";
import "../dropPodsEvent";
import "../bombCarouselEvent";
import "../lastStandEvent";
import "../tinCanEvent";
import "../pointDefenseEvent";
import "../targetPracticeEvent";
import "../flareGunEvent";
import "../rappelEvent";
import "../stackerEvent";
import "../coinPusherEvent";
import "../highStrikerEvent";
import "../noteHighwayEvent";
import "../safecrackerEvent";
import "../gumballMachineEvent";
import "../ninjaEvent";
import "../bungeeEvent";
import "../funnelCakeEvent";
import "../chrysanthemumEvent";
import "../crossroadsEvent";
import "../waterslideEvent";
import "../bannerEvent";
import "../hauntEvent";
import "../mapleSeedsEvent";
import "../donutsEvent";
import "../hamsterWheelEvent";
import "../lunarLanderEvent";
import "../dowsingEvent";
import "../matadorEvent";
import "../flashFloodEvent";
import "../dolphinEvent";
import "../pufferEvent";
import "../hockeyStopEvent";
import "../twirlEvent";
import "../whaleEvent";
import "../lightPaintingEvent";
import "../saberThrowEvent";
import "../laserMazeEvent";
import "../tapeMeasureEvent";
import "../pulsarEvent";
import "../shortCircuitEvent";
import "../conductorEvent";
import "../doubleStrikeEvent";
import "../lightningFenceEvent";
import "../heatLightningEvent";
import "../powderKegsEvent";
import "../bombFountainEvent";
import "../fragOutEvent";
import "../faultLineEvent";
import "../willowShellsEvent";
import "../swarmStrikeEvent";
import "../concentricEvent";
import "../grazeEvent";
import "../hotfootEvent";
import "../dogfightEvent";
import "../bulletRoseEvent";
import "../armorPiercerEvent";
import "../spotterEvent";
import "../pegSolitaireEvent";
import "../marbleDropEvent";
import "../statuesEvent";
import "../flappyWispEvent";
import "../buriedTreasureEvent";
import "../airHockeyEvent";
import "../boltOfCashEvent";
import "../pendulumPourEvent";
import "../popTheCorkEvent";
import "../wallJumpEvent";
import "../superballEvent";
import "../spinDashEvent";
import "../cupidEvent";
import "../storkEvent";
import "../paperPlaneEvent";
import "../spikeEvent";
// the dev test bar's hooks
export { forceCourierEvent } from "../courierEvent";
export { forceRodeoEvent } from "../rodeoEvent";
export { forceCrosshairEvent } from "../crosshairEvent";
export { forceIrisEvent } from "../irisEvent";
export { forceBankShotEvent } from "../bankShotEvent";
export { forceSunbeamsEvent } from "../sunbeamsEvent";
export { forceStargateEvent } from "../stargateEvent";
export { forceCatsCradleEvent } from "../catsCradleEvent";
export { forceThunderheadEvent } from "../thunderheadEvent";
export { forcePitchforkEvent } from "../pitchforkEvent";
export { forceJumperCablesEvent } from "../jumperCablesEvent";
export { forceLashEvent } from "../lashEvent";
export { forceSparkPlugEvent } from "../sparkPlugEvent";
export { forceLiveWireEvent } from "../liveWireEvent";
export { forceFuseRaceEvent } from "../fuseRaceEvent";
export { forceBouncingBettyEvent } from "../bouncingBettyEvent";
export { forcePressureCookerEvent } from "../pressureCookerEvent";
export { forceHotPotatoEvent } from "../hotPotatoEvent";
export { forceDaisyChainEvent } from "../daisyChainEvent";
export { forceShapedChargeEvent } from "../shapedChargeEvent";
export { forceDetcordEvent } from "../detcordEvent";
export { forceBulletBloomEvent } from "../bulletBloomEvent";
export { forceHighNoonEvent } from "../highNoonEvent";
export { forceHailfireEvent } from "../hailfireEvent";
export { forceDervishEvent } from "../dervishEvent";
export { forceInvadersEvent } from "../invadersEvent";
export { forceGunKataEvent } from "../gunKataEvent";
export { forceLockbusterEvent } from "../lockbusterEvent";
export { forceConnectFourEvent } from "../connectFourEvent";
export { forceComboEvent } from "../comboEvent";
export { forceSkeeBallEvent } from "../skeeBallEvent";
export { forceBubbleShooterEvent } from "../bubbleShooterEvent";
export { forceDeltaEvent } from "../deltaEvent";
export { forceHydrantEvent } from "../hydrantEvent";
export { forceCloverleafEvent } from "../cloverleafEvent";
export { forcePinstripeEvent } from "../pinstripeEvent";
export { forceFaucetEvent } from "../faucetEvent";
export { forceShowerheadEvent } from "../showerheadEvent";
export { forceBinaryStarEvent } from "../binaryStarEvent";
export { forceHopscotchEvent } from "../hopscotchEvent";
export { forceTadpolesEvent } from "../tadpolesEvent";
export { forceBlinkEvent } from "../blinkEvent";
export { forceBumperCarsEvent } from "../bumperCarsEvent";
export { forcePigeonsEvent } from "../pigeonsEvent";
export { forceSquidEvent } from "../squidEvent";
export { forceWaterPistolEvent } from "../waterPistolEvent";
export { forcePoiEvent } from "../poiEvent";
export { forceBartenderEvent } from "../bartenderEvent";
export { forcePoleVaultEvent } from "../poleVaultEvent";
export { forcePaintRollerEvent } from "../paintRollerEvent";
export { forceBuzzsawEvent } from "../buzzsawEvent";
export { forceLightCyclesEvent } from "../lightCyclesEvent";
export { forceFiberOpticEvent } from "../fiberOpticEvent";
export { forceDaddyLonglegsEvent } from "../daddyLonglegsEvent";
export { forceKnighthoodEvent } from "../knighthoodEvent";
export { forceCuttingTorchEvent } from "../cuttingTorchEvent";
export { forceStElmosFireEvent } from "../stElmosFireEvent";
export { forceSteppedLeaderEvent } from "../steppedLeaderEvent";
export { forceTrolleyEvent } from "../trolleyEvent";
export { forceBoltBounceEvent } from "../boltBounceEvent";
export { forceStormCrownEvent } from "../stormCrownEvent";
export { forceVanDeGraaffEvent } from "../vanDeGraaffEvent";
export { forceBarrelRollEvent } from "../barrelRollEvent";
export { forceBombStackEvent } from "../bombStackEvent";
export { forceRomanCandleEvent } from "../romanCandleEvent";
export { forceWhistlersEvent } from "../whistlersEvent";
export { forceTrebuchetEvent } from "../trebuchetEvent";
export { forceDropPodsEvent } from "../dropPodsEvent";
export { forceBombCarouselEvent } from "../bombCarouselEvent";
export { forceLastStandEvent } from "../lastStandEvent";
export { forceTinCanEvent } from "../tinCanEvent";
export { forcePointDefenseEvent } from "../pointDefenseEvent";
export { forceTargetPracticeEvent } from "../targetPracticeEvent";
export { forceFlareGunEvent } from "../flareGunEvent";
export { forceRappelEvent } from "../rappelEvent";
export { forceStackerEvent } from "../stackerEvent";
export { forceCoinPusherEvent } from "../coinPusherEvent";
export { forceHighStrikerEvent } from "../highStrikerEvent";
export { forceNoteHighwayEvent } from "../noteHighwayEvent";
export { forceSafecrackerEvent } from "../safecrackerEvent";
export { forceGumballMachineEvent } from "../gumballMachineEvent";
export { forceNinjaEvent } from "../ninjaEvent";
export { forceBungeeEvent } from "../bungeeEvent";
export { forceFunnelCakeEvent } from "../funnelCakeEvent";
export { forceChrysanthemumEvent } from "../chrysanthemumEvent";
export { forceCrossroadsEvent } from "../crossroadsEvent";
export { forceWaterslideEvent } from "../waterslideEvent";
export { forceBannerEvent } from "../bannerEvent";
export { forceHauntEvent } from "../hauntEvent";
export { forceMapleSeedsEvent } from "../mapleSeedsEvent";
export { forceDonutsEvent } from "../donutsEvent";
export { forceHamsterWheelEvent } from "../hamsterWheelEvent";
export { forceLunarLanderEvent } from "../lunarLanderEvent";
export { forceDowsingEvent } from "../dowsingEvent";
export { forceMatadorEvent } from "../matadorEvent";
export { forceFlashFloodEvent } from "../flashFloodEvent";
export { forceDolphinEvent } from "../dolphinEvent";
export { forcePufferEvent } from "../pufferEvent";
export { forceHockeyStopEvent } from "../hockeyStopEvent";
export { forceTwirlEvent } from "../twirlEvent";
export { forceWhaleEvent } from "../whaleEvent";
export { forceLightPaintingEvent } from "../lightPaintingEvent";
export { forceSaberThrowEvent } from "../saberThrowEvent";
export { forceLaserMazeEvent } from "../laserMazeEvent";
export { forceTapeMeasureEvent } from "../tapeMeasureEvent";
export { forcePulsarEvent } from "../pulsarEvent";
export { forceShortCircuitEvent } from "../shortCircuitEvent";
export { forceConductorEvent } from "../conductorEvent";
export { forceDoubleStrikeEvent } from "../doubleStrikeEvent";
export { forceLightningFenceEvent } from "../lightningFenceEvent";
export { forceHeatLightningEvent } from "../heatLightningEvent";
export { forcePowderKegsEvent } from "../powderKegsEvent";
export { forceBombFountainEvent } from "../bombFountainEvent";
export { forceFragOutEvent } from "../fragOutEvent";
export { forceFaultLineEvent } from "../faultLineEvent";
export { forceWillowShellsEvent } from "../willowShellsEvent";
export { forceSwarmStrikeEvent } from "../swarmStrikeEvent";
export { forceConcentricEvent } from "../concentricEvent";
export { forceGrazeEvent } from "../grazeEvent";
export { forceHotfootEvent } from "../hotfootEvent";
export { forceDogfightEvent } from "../dogfightEvent";
export { forceBulletRoseEvent } from "../bulletRoseEvent";
export { forceArmorPiercerEvent } from "../armorPiercerEvent";
export { forceSpotterEvent } from "../spotterEvent";
export { forcePegSolitaireEvent } from "../pegSolitaireEvent";
export { forceMarbleDropEvent } from "../marbleDropEvent";
export { forceStatuesEvent } from "../statuesEvent";
export { forceFlappyWispEvent } from "../flappyWispEvent";
export { forceBuriedTreasureEvent } from "../buriedTreasureEvent";
export { forceAirHockeyEvent } from "../airHockeyEvent";
export { forceBoltOfCashEvent } from "../boltOfCashEvent";
export { forcePendulumPourEvent } from "../pendulumPourEvent";
export { forcePopTheCorkEvent } from "../popTheCorkEvent";
export { forceWallJumpEvent } from "../wallJumpEvent";
export { forceSuperballEvent } from "../superballEvent";
export { forceSpinDashEvent } from "../spinDashEvent";
export { forceCupidEvent } from "../cupidEvent";
export { forceStorkEvent } from "../storkEvent";
export { forcePaperPlaneEvent } from "../paperPlaneEvent";
export { forceSpikeEvent } from "../spikeEvent";
