// odds and reward sizes for featured/catGirls.ts's crits, spread into CONFIG.crit
export const CAT_GIRLS_BALANCE = {
  pawsAndEffectChance: 0.0012,
  pawsAndEffectUpgrades: 69,
  catwalkQueenChance: 0.0006,
  catwalkQueenTierSteps: 2,
  catwalkQueenUpgrades: 25,
  runwayRoyaltyChance: 0.0009,
  runwayRoyaltyUpgrades: 67,
  blueHourStrutChance: 0.0009,
  blueHourStrutPayouts: 69,
  felineFineChance: 0.0011,
  felineFineUpgrades: 64,
  kittenHeelsChance: 0.001,
  kittenHeelsUpgrades: 63,
  catsPajamasChance: 0.0006,
  catsPajamasUpgrades: 22,
  catsPajamasPayouts: 21,
  bedtimeBonusChance: 0.0009,
  bedtimeBonusUpgrades: 27,
  bedtimeBonusPayouts: 31,
  purrsuasionChance: 0.0011,
  purrsuasionUpgrades: 45,
  coinBoopChance: 0.0012,
  coinBoopPayouts: 68,
  tailSwishChance: 0.001,
  tailSwishUpgrades: 55,
} as const;
