// odds and reward sizes for featured/critters.ts's crits, spread into CONFIG.crit
export const CRITTERS_BALANCE = {
  crownHedgehogChance: 0.003,
  crownHedgehogTierSteps: 1,
  crownHedgehogUpgrades: 22,
  lanternFoxChance: 0.003,
  lanternFoxPayouts: 31,
  lanternLynxChance: 0.012,
  lanternLynxUpgrades: 23,
  pearlOtterChance: 0.004,
  pearlOtterPayouts: 30,
  profitPigeonChance: 0.005,
  profitPigeonPayouts: 27,
  redPandaChance: 0.003,
  redPandaUpgrades: 31,
  goldenGardenGolemChance: 0.002,
  goldenGardenGolemPayouts: 33,
  vaultBeetleChance: 0.002,
  vaultBeetleUpgrades: 34,
  antleredFoxFortuneChance: 0.0025,
  antleredFoxFortuneUpgrades: 34,
  bestestBoyChance: 0.0012,
  bestestBoyUpgrades: 41,
  doggoChance: 0.0012,
  doggoPayouts: 38,
  otterlyAdorableChance: 0.0018,
  otterlyAdorablePayouts: 35,
  sleepyFoxChance: 0.0019,
  sleepyFoxPayouts: 34,
  sleepyPandaChance: 0.001,
  sleepyPandaUpgrades: 43,
} as const;
