// odds and reward sizes for featured/desserts.ts's crits, spread into CONFIG.crit
export const DESSERTS_BALANCE = {
  berryParfaitChance: 0.002,
  berryParfaitPayouts: 32,
  lemonTartChance: 0.003,
  lemonTartUpgrades: 36,
  berryShortcakeChance: 0.0025,
  berryShortcakePayouts: 33,
  cinnamonSwirlChance: 0.004,
  cinnamonSwirlUpgrades: 26,
  chocolateCakeChance: 0.003,
  chocolateCakeUpgrades: 30,
  strawberryShortcakeChance: 0.0035,
  strawberryShortcakePayouts: 28,
  rainbowDonutChance: 0.006,
  rainbowDonutUpgrades: 21,
  iceCreamSundaeChance: 0.002,
  iceCreamSundaePayouts: 34,
  iceCreamSundae2Chance: 0.003,
  iceCreamSundae2Upgrades: 29,
  macaronTowerChance: 0.0025,
  macaronTowerPayouts: 33,
  macaronTower2Chance: 0.003,
  macaronTower2Upgrades: 31,
  appleChance: 0.005,
  applePayouts: 22,
  cupcakeChance: 0.004,
  cupcakeUpgrades: 26,
  donutChance: 0.003,
  donutPayouts: 30,
} as const;
