// odds and reward sizes for featured/office.ts's crits, spread into CONFIG.crit
export const OFFICE_BALANCE = {
  executiveSpinChance: 0.05,
  executiveSpinUpgrades: 4,
  rubberStampedeChance: 0.025,
  rubberStampedePayouts: 7,
  replyAllChance: 0.06,
  replyAllPayouts: 3,
  stapleOfSuccessChance: 0.04,
  stapleOfSuccessUpgrades: 7,
  faxOfFortuneChance: 0.035,
  faxOfFortunePayouts: 8,
  casualMondayChance: 0.025,
  casualMondayUpgrades: 20,
  deskJockeyChance: 0.05,
  deskJockeyUpgrades: 6,
  inboxZeroGravityChance: 0.03,
  inboxZeroGravityPayouts: 12,
  beanCounterChance: 0.01,
  beanCounterTierSteps: 1,
  beanCounterUpgrades: 6,
  kingOfTheWorldChance: 0.015,
  kingOfTheWorldUpgrades: 30,
  officeClownChance: 0.04,
  officeClownUpgrades: 5,
  fridayTieDayChance: 0.03,
  fridayTieDayPayouts: 10,
  soReadyChance: 0.02,
  soReadyUpgrades: 15,
} as const;
