// odds and reward sizes for featured/party.ts's crits, spread into CONFIG.crit
export const PARTY_BALANCE = {
  doughDivisionChance: 0.06,
  doughDivisionUpgrades: 6,
  profitPopcornChance: 0.04,
  profitPopcornPayouts: 4,
  donutDisturbChance: 0.05,
  donutDisturbUpgrades: 5,
  donutDisturbPayouts: 5,
  cakeDayChance: 0.03,
  cakeDayUpgrades: 12,
  champagneProblemsChance: 0.02,
  champagneProblemsPayouts: 15,
  bonusBurritoChance: 0.04,
  bonusBurritoUpgrades: 8,
  bonusBurritoPayouts: 3,
  sundaeBestChance: 0.025,
  sundaeBestPayouts: 10,
  popTheQuestionChance: 0.01,
  popTheQuestionTierSteps: 1,
  popTheQuestionUpgrades: 4,
  partyCrasherChance: 0.05,
  partyCrasherUpgrades: 3,
} as const;
