// odds and reward sizes for featured/relics.ts's crits, spread into CONFIG.crit
export const RELICS_BALANCE = {
  ancientRelicChance: 0.014,
  ancientRelicPayouts: 35,
  geometricRelicChance: 0.015,
  geometricRelicPayouts: 34,
  emberKeyChance: 0.0025,
  emberKeyUpgrades: 32,
  frostRuneChance: 0.004,
  frostRuneUpgrades: 29,
  memoryCrystalChance: 0.004,
  memoryCrystalTierSteps: 1,
  memoryCrystalUpgrades: 21,
  neonBeakerChance: 0.003,
  neonBeakerPayouts: 32,
  rainbowRelicChance: 0.003,
  rainbowRelicTierSteps: 1,
  rainbowRelicUpgrades: 23,
  whisperingOrbChance: 0.002,
  whisperingOrbTierSteps: 1,
  whisperingOrbUpgrades: 25,
  lionKeyChance: 0.0015,
  lionKeyTierSteps: 1,
  lionKeyUpgrades: 26,
  restorationProjectChance: 0.0025,
  restorationProjectUpgrades: 30,
  relicCompassChance: 0.001,
  relicCompassUpgrades: 61,
} as const;
