// odds and reward sizes for featured/treasures.ts's crits, spread into CONFIG.crit
export const TREASURES_BALANCE = {
  theMoonstoneKeyChance: 0.012,
  theMoonstoneKeyTierSteps: 1,
  theMoonstoneKeyUpgrades: 6,
  spellbookSupremeChance: 0.019,
  spellbookSupremeUpgrades: 12,
  prismPotionChance: 0.017,
  prismPotionPayouts: 14,
  galaxyGumballChance: 0.023,
  galaxyGumballPayouts: 11,
  treasureTruffleChance: 0.026,
  treasureTruffleUpgrades: 5,
  treasureTrufflePayouts: 5,
  wizardsWaffleChance: 0.016,
  wizardsWaffleUpgrades: 10,
  goldenFortuneCookieChance: 0.02,
  goldenFortuneCookieUpgrades: 9,
  crystalDragonEggChance: 0.014,
  crystalDragonEggUpgrades: 12,
  diamondCompassChance: 0.018,
  diamondCompassPayouts: 10,
  emeraldCrownChance: 0.012,
  emeraldCrownTierSteps: 1,
  emeraldCrownUpgrades: 8,
  goldenFleeceChance: 0.02,
  goldenFleecePayouts: 7,
  imperialScepterChance: 0.015,
  imperialScepterUpgrades: 13,
  rubyHeartRelicChance: 0.024,
  rubyHeartRelicPayouts: 12,
  sapphireHourglassChance: 0.017,
  sapphireHourglassPayouts: 9,
  vaultOfJewelsChance: 0.016,
  vaultOfJewelsUpgrades: 6,
  goldenIdolChance: 0.011,
  goldenIdolUpgrades: 15,
} as const;
