import type { CritProcDisplayInfo } from "./index";
import { COLOR } from "../../palette";

export const ELEMENT_CRIT_INFO = {
  californiumCrescendo: {
    label: "Californium Crescendo",
    color: COLOR.blue,
    icon: "californiumCrescendo",
    description: "98 upgrades here and 98 payouts on the highest floor",
  },
  einsteiniumEpiphany: {
    label: "Einsteinium Epiphany",
    color: COLOR.purple,
    icon: "einsteiniumEpiphany",
    description: "99 upgrades here and 99 payouts on the highest floor",
  },
  fermiumFormula: {
    label: "Fermium Formula",
    color: COLOR.cyan,
    icon: "fermiumFormula",
    description: "100 upgrades here and 100 payouts on the highest floor",
  },
  mendeleviumMajesty: {
    label: "Mendelevium Majesty",
    color: COLOR.gold,
    icon: "mendeleviumMajesty",
    description: "101 upgrades here and 101 payouts on the highest floor",
  },
  nobeliumLaureate: {
    label: "Nobelium Laureate",
    color: COLOR.starYellow,
    icon: "nobeliumLaureate",
    description: "102 upgrades here and 102 payouts on the highest floor",
  },
  lawrenciumLightspeed: {
    label: "Lawrencium Lightspeed",
    color: COLOR.moneyGreen,
    icon: "lawrenciumLightspeed",
    description: "103 upgrades here and 103 payouts on the highest floor",
  },
  rutherfordiumReach: {
    label: "Rutherfordium Reach",
    color: COLOR.mysticTeal,
    icon: "rutherfordiumReach",
    description: "104 upgrades here and 104 payouts on the highest floor",
  },
  seaborgiumSwell: {
    label: "Seaborgium Swell",
    color: COLOR.silverTicketGray,
    icon: "seaborgiumSwell",
    description: "106 upgrades here and 106 payouts on the highest floor",
  },
  bohriumSummit: {
    label: "Bohrium Summit",
    color: COLOR.red,
    icon: "bohriumSummit",
    description: "107 upgrades here and 107 payouts on the highest floor",
  },
  hassiumMeteor: {
    label: "Hassium Meteor",
    color: COLOR.peppermintPink,
    icon: "hassiumMeteor",
    description: "108 upgrades here and 108 payouts on the highest floor",
  },
  meitneriumMarvel: {
    label: "Meitnerium Marvel",
    color: COLOR.blue,
    icon: "meitneriumMarvel",
    description: "109 upgrades here and 109 payouts on the highest floor",
  },
  darmstadtiumDowntown: {
    label: "Darmstadtium Downtown",
    color: COLOR.purple,
    icon: "darmstadtiumDowntown",
    description: "110 upgrades here and 110 payouts on the highest floor",
  },
  roentgeniumRevelation: {
    label: "Roentgenium Revelation",
    color: COLOR.cyan,
    icon: "roentgeniumRevelation",
    description: "111 upgrades here and 111 payouts on the highest floor",
  },
  coperniciumCarousel: {
    label: "Copernicium Carousel",
    color: COLOR.gold,
    icon: "coperniciumCarousel",
    description: "112 upgrades here and 112 payouts on the highest floor",
  },
  nihoniumDaybreak: {
    label: "Nihonium Daybreak",
    color: COLOR.starYellow,
    icon: "nihoniumDaybreak",
    description: "113 upgrades here and 113 payouts on the highest floor",
  },
  fleroviumFortress: {
    label: "Flerovium Fortress",
    color: COLOR.moneyGreen,
    icon: "fleroviumFortress",
    description: "114 upgrades here and 114 payouts on the highest floor",
  },
  moscoviumMosaic: {
    label: "Moscovium Mosaic",
    color: COLOR.mysticTeal,
    icon: "moscoviumMosaic",
    description: "115 upgrades here and 115 payouts on the highest floor",
  },
  livermoriumLightning: {
    label: "Livermorium Lightning",
    color: COLOR.silverTicketGray,
    icon: "livermoriumLightning",
    description: "116 upgrades here and 116 payouts on the highest floor",
  },
  tennessineTwinkle: {
    label: "Tennessine Twinkle",
    color: COLOR.red,
    icon: "tennessineTwinkle",
    description: "117 upgrades here and 117 payouts on the highest floor",
  },
  oganessonOdyssey: {
    label: "Oganesson Odyssey",
    color: COLOR.peppermintPink,
    icon: "oganessonOdyssey",
    description: "118 upgrades here and 118 payouts on the highest floor",
  },
  osmiumRegalia: {
    label: "Osmium Regalia",
    color: COLOR.silverTicketGray,
    icon: "osmiumRegalia",
    description: "76 upgrades here and 76 payouts on the highest floor",
  },
  iridiumAegis: {
    label: "Iridium Aegis",
    color: COLOR.cyan,
    icon: "iridiumAegis",
    description: "77 upgrades here and 77 payouts on the highest floor",
  },
  mercuryFlow: {
    label: "Mercury Flow",
    color: COLOR.blue,
    icon: "mercuryFlow",
    description: "80 upgrades here and 80 payouts on the highest floor",
  },
  thalliumThrive: {
    label: "Thallium Thrive",
    color: COLOR.moneyGreen,
    icon: "thalliumThrive",
    description: "81 upgrades here and 81 payouts on the highest floor",
  },
  leadLode: {
    label: "Lead Lode",
    color: COLOR.gold,
    icon: "leadLode",
    description: "82 upgrades here and 82 payouts on the highest floor",
  },
  bismuthBastion: {
    label: "Bismuth Bastion",
    color: COLOR.peppermintPink,
    icon: "bismuthBastion",
    description: "83 upgrades here and 83 payouts on the highest floor",
  },
  poloniumPrism: {
    label: "Polonium Prism",
    color: COLOR.red,
    icon: "poloniumPrism",
    description: "84 upgrades here and 84 payouts on the highest floor",
  },
  astatineAurora: {
    label: "Astatine Aurora",
    color: COLOR.mysticTeal,
    icon: "astatineAurora",
    description: "85 upgrades here and 85 payouts on the highest floor",
  },
  radonRipple: {
    label: "Radon Ripple",
    color: COLOR.silverTicketGray,
    icon: "radonRipple",
    description: "86 upgrades here and 86 payouts on the highest floor",
  },
  franciumFortune: {
    label: "Francium Fortune",
    color: COLOR.cyan,
    icon: "franciumFortune",
    description: "87 upgrades here and 87 payouts on the highest floor",
  },
  radiumRhythm: {
    label: "Radium Rhythm",
    color: COLOR.blue,
    icon: "radiumRhythm",
    description: "88 upgrades here and 88 payouts on the highest floor",
  },
  actiniumArc: {
    label: "Actinium Arc",
    color: COLOR.moneyGreen,
    icon: "actiniumArc",
    description: "89 upgrades here and 89 payouts on the highest floor",
  },
  thoriumThrone: {
    label: "Thorium Throne",
    color: COLOR.gold,
    icon: "thoriumThrone",
    description: "90 upgrades here and 90 payouts on the highest floor",
  },
  protactiniumOrbit: {
    label: "Protactinium Orbit",
    color: COLOR.peppermintPink,
    icon: "protactiniumOrbit",
    description: "91 upgrades here and 91 payouts on the highest floor",
  },
  neptuniumNova: {
    label: "Neptunium Nova",
    color: COLOR.red,
    icon: "neptuniumNova",
    description: "93 upgrades here and 93 payouts on the highest floor",
  },
  americiumAlarm: {
    label: "Americium Alarm",
    color: COLOR.mysticTeal,
    icon: "americiumAlarm",
    description: "95 upgrades here and 95 payouts on the highest floor",
  },
  plutoniumPulse: {
    label: "Plutonium Pulse",
    color: COLOR.orange,
    icon: "plutoniumPulse",
    description: "94 upgrades here and 94 payouts on the highest floor",
  },
  curiumCrucible: {
    label: "Curium Crucible",
    color: COLOR.silverTicketGray,
    icon: "curiumCrucible",
    description: "96 upgrades here and 96 payouts on the highest floor",
  },
  berkeliumBreakthrough: {
    label: "Berkelium Breakthrough",
    color: COLOR.cyan,
    icon: "berkeliumBreakthrough",
    description: "97 upgrades here and 97 payouts on the highest floor",
  },
  hydrogenHype: {
    label: "Hydrogen Hype",
    color: COLOR.blue,
    icon: "hydrogenHype",
    description: "1 upgrades here and 1 payouts on the highest floor",
  },
  heliumHighrise: {
    label: "Helium Highrise",
    color: COLOR.cyan,
    icon: "heliumHighrise",
    description: "2 upgrades here and 2 payouts on the highest floor",
  },
  lithiumLift: {
    label: "Lithium Lift",
    color: COLOR.moneyGreen,
    icon: "lithiumLift",
    description: "3 upgrades here and 3 payouts on the highest floor",
  },
  berylliumBrilliance: {
    label: "Beryllium Brilliance",
    color: COLOR.gold,
    icon: "berylliumBrilliance",
    description: "4 upgrades here and 4 payouts on the highest floor",
  },
  carbonCrown: {
    label: "Carbon Crown",
    color: COLOR.red,
    icon: "carbonCrown",
    description: "6 upgrades here and 6 payouts on the highest floor",
  },
  nitrogenNimbus: {
    label: "Nitrogen Nimbus",
    color: COLOR.peppermintPink,
    icon: "nitrogenNimbus",
    description: "7 upgrades here and 7 payouts on the highest floor",
  },
  oxygenOverdrive: {
    label: "Oxygen Overdrive",
    color: COLOR.silverTicketGray,
    icon: "oxygenOverdrive",
    description: "8 upgrades here and 8 payouts on the highest floor",
  },
  fluorineFlash: {
    label: "Fluorine Flash",
    color: COLOR.mysticTeal,
    icon: "fluorineFlash",
    description: "9 upgrades here and 9 payouts on the highest floor",
  },
  sodiumSprinkle: {
    label: "Sodium Sprinkle",
    color: COLOR.blue,
    icon: "sodiumSprinkle",
    description: "11 upgrades here and 11 payouts on the highest floor",
  },
  magnesiumMagnificence: {
    label: "Magnesium Magnificence",
    color: COLOR.cyan,
    icon: "magnesiumMagnificence",
    description: "12 upgrades here and 12 payouts on the highest floor",
  },
  aluminumAllStar: {
    label: "Aluminum All-Star",
    color: COLOR.moneyGreen,
    icon: "aluminumAllStar",
    description: "13 upgrades here and 13 payouts on the highest floor",
  },
  siliconSpark: {
    label: "Silicon Spark",
    color: COLOR.gold,
    icon: "siliconSpark",
    description: "14 upgrades here and 14 payouts on the highest floor",
  },
  phosphorusFlare: {
    label: "Phosphorus Flare",
    color: COLOR.red,
    icon: "phosphorusFlare",
    description: "15 upgrades here and 15 payouts on the highest floor",
  },
  sulfurSunshine: {
    label: "Sulfur Sunshine",
    color: COLOR.peppermintPink,
    icon: "sulfurSunshine",
    description: "16 upgrades here and 16 payouts on the highest floor",
  },
  chlorineConfetti: {
    label: "Chlorine Confetti",
    color: COLOR.silverTicketGray,
    icon: "chlorineConfetti",
    description: "17 upgrades here and 17 payouts on the highest floor",
  },
  argonAfterglow: {
    label: "Argon Afterglow",
    color: COLOR.mysticTeal,
    icon: "argonAfterglow",
    description: "18 upgrades here and 18 payouts on the highest floor",
  },
  potassiumPop: {
    label: "Potassium Pop",
    color: COLOR.blue,
    icon: "potassiumPop",
    description: "19 upgrades here and 19 payouts on the highest floor",
  },
  calciumCornerstone: {
    label: "Calcium Cornerstone",
    color: COLOR.cyan,
    icon: "calciumCornerstone",
    description: "20 upgrades here and 20 payouts on the highest floor",
  },
  scandiumStronghold: {
    label: "Scandium Stronghold",
    color: COLOR.moneyGreen,
    icon: "scandiumStronghold",
    description: "21 upgrades here and 21 payouts on the highest floor",
  },
  titaniumTakeoff: {
    label: "Titanium Takeoff",
    color: COLOR.gold,
    icon: "titaniumTakeoff",
    description: "22 upgrades here and 22 payouts on the highest floor",
  },
  vanadiumVoltage: {
    label: "Vanadium Voltage",
    color: COLOR.red,
    icon: "vanadiumVoltage",
    description: "23 upgrades here and 23 payouts on the highest floor",
  },
  chromiumGleam: {
    label: "Chromium Gleam",
    color: COLOR.peppermintPink,
    icon: "chromiumGleam",
    description: "24 upgrades here and 24 payouts on the highest floor",
  },
  manganeseMomentum: {
    label: "Manganese Momentum",
    color: COLOR.silverTicketGray,
    icon: "manganeseMomentum",
    description: "25 upgrades here and 25 payouts on the highest floor",
  },
  ironEmpire: {
    label: "Iron Empire",
    color: COLOR.mysticTeal,
    icon: "ironEmpire",
    description: "26 upgrades here and 26 payouts on the highest floor",
  },
  cobaltCharge: {
    label: "Cobalt Charge",
    color: COLOR.blue,
    icon: "cobaltCharge",
    description: "27 upgrades here and 27 payouts on the highest floor",
  },
  nickelNestEgg: {
    label: "Nickel Nest Egg",
    color: COLOR.cyan,
    icon: "nickelNestEgg",
    description: "28 upgrades here and 28 payouts on the highest floor",
  },
  copperCurrent: {
    label: "Copper Current",
    color: COLOR.moneyGreen,
    icon: "copperCurrent",
    description: "29 upgrades here and 29 payouts on the highest floor",
  },
  zincZing: {
    label: "Zinc Zing",
    color: COLOR.gold,
    icon: "zincZing",
    description: "30 upgrades here and 30 payouts on the highest floor",
  },
  galliumGlitter: {
    label: "Gallium Glitter",
    color: COLOR.red,
    icon: "galliumGlitter",
    description: "31 upgrades here and 31 payouts on the highest floor",
  },
  germaniumGenius: {
    label: "Germanium Genius",
    color: COLOR.peppermintPink,
    icon: "germaniumGenius",
    description: "32 upgrades here and 32 payouts on the highest floor",
  },
  arsenicAlchemy: {
    label: "Arsenic Alchemy",
    color: COLOR.silverTicketGray,
    icon: "arsenicAlchemy",
    description: "33 upgrades here and 33 payouts on the highest floor",
  },
  seleniumSunburst: {
    label: "Selenium Sunburst",
    color: COLOR.mysticTeal,
    icon: "seleniumSunburst",
    description: "34 upgrades here and 34 payouts on the highest floor",
  },
  bromineBounty: {
    label: "Bromine Bounty",
    color: COLOR.blue,
    icon: "bromineBounty",
    description: "35 upgrades here and 35 payouts on the highest floor",
  },
  kryptonKeepsake: {
    label: "Krypton Keepsake",
    color: COLOR.cyan,
    icon: "kryptonKeepsake",
    description: "36 upgrades here and 36 payouts on the highest floor",
  },
  rubidiumRadiance: {
    label: "Rubidium Radiance",
    color: COLOR.moneyGreen,
    icon: "rubidiumRadiance",
    description: "37 upgrades here and 37 payouts on the highest floor",
  },
  strontiumSpectacle: {
    label: "Strontium Spectacle",
    color: COLOR.gold,
    icon: "strontiumSpectacle",
    description: "38 upgrades here and 38 payouts on the highest floor",
  },
  yttriumYield: {
    label: "Yttrium Yield",
    color: COLOR.red,
    icon: "yttriumYield",
    description: "39 upgrades here and 39 payouts on the highest floor",
  },
  zirconiumZenith: {
    label: "Zirconium Zenith",
    color: COLOR.peppermintPink,
    icon: "zirconiumZenith",
    description: "40 upgrades here and 40 payouts on the highest floor",
  },
  niobiumNexus: {
    label: "Niobium Nexus",
    color: COLOR.silverTicketGray,
    icon: "niobiumNexus",
    description: "41 upgrades here and 41 payouts on the highest floor",
  },
  molybdenumMachine: {
    label: "Molybdenum Machine",
    color: COLOR.mysticTeal,
    icon: "molybdenumMachine",
    description: "42 upgrades here and 42 payouts on the highest floor",
  },
  technetiumTimebank: {
    label: "Technetium Timebank",
    color: COLOR.blue,
    icon: "technetiumTimebank",
    description: "43 upgrades here and 43 payouts on the highest floor",
  },
  rutheniumRiches: {
    label: "Ruthenium Riches",
    color: COLOR.cyan,
    icon: "rutheniumRiches",
    description: "44 upgrades here and 44 payouts on the highest floor",
  },
  rhodiumReflection: {
    label: "Rhodium Reflection",
    color: COLOR.moneyGreen,
    icon: "rhodiumReflection",
    description: "45 upgrades here and 45 payouts on the highest floor",
  },
  palladiumPilot: {
    label: "Palladium Pilot",
    color: COLOR.gold,
    icon: "palladiumPilot",
    description: "46 upgrades here and 46 payouts on the highest floor",
  },
  silverMoonrise: {
    label: "Silver Moonrise",
    color: COLOR.red,
    icon: "silverMoonrise",
    description: "47 upgrades here and 47 payouts on the highest floor",
  },
  cadmiumCatalyst: {
    label: "Cadmium Catalyst",
    color: COLOR.peppermintPink,
    icon: "cadmiumCatalyst",
    description: "48 upgrades here and 48 payouts on the highest floor",
  },
  indiumInsight: {
    label: "Indium Insight",
    color: COLOR.silverTicketGray,
    icon: "indiumInsight",
    description: "49 upgrades here and 49 payouts on the highest floor",
  },
  tinTreasure: {
    label: "Tin Treasure",
    color: COLOR.mysticTeal,
    icon: "tinTreasure",
    description: "50 upgrades here and 50 payouts on the highest floor",
  },
  antimonyAscension: {
    label: "Antimony Ascension",
    color: COLOR.blue,
    icon: "antimonyAscension",
    description: "51 upgrades here and 51 payouts on the highest floor",
  },
  telluriumTreasurelight: {
    label: "Tellurium Treasurelight",
    color: COLOR.cyan,
    icon: "telluriumTreasurelight",
    description: "52 upgrades here and 52 payouts on the highest floor",
  },
  iodineIridescence: {
    label: "Iodine Iridescence",
    color: COLOR.moneyGreen,
    icon: "iodineIridescence",
    description: "53 upgrades here and 53 payouts on the highest floor",
  },
  xenonSpotlight: {
    label: "Xenon Spotlight",
    color: COLOR.gold,
    icon: "xenonSpotlight",
    description: "54 upgrades here and 54 payouts on the highest floor",
  },
  cesiumClockwork: {
    label: "Cesium Clockwork",
    color: COLOR.red,
    icon: "cesiumClockwork",
    description: "55 upgrades here and 55 payouts on the highest floor",
  },
  bariumBeacon: {
    label: "Barium Beacon",
    color: COLOR.peppermintPink,
    icon: "bariumBeacon",
    description: "56 upgrades here and 56 payouts on the highest floor",
  },
  lanthanumLuster: {
    label: "Lanthanum Luster",
    color: COLOR.silverTicketGray,
    icon: "lanthanumLuster",
    description: "57 upgrades here and 57 payouts on the highest floor",
  },
  ceriumShine: {
    label: "Cerium Shine",
    color: COLOR.mysticTeal,
    icon: "ceriumShine",
    description: "58 upgrades here and 58 payouts on the highest floor",
  },
  praseodymiumPrism: {
    label: "Praseodymium Prism",
    color: COLOR.blue,
    icon: "praseodymiumPrism",
    description: "59 upgrades here and 59 payouts on the highest floor",
  },
  neodymiumNorthstar: {
    label: "Neodymium Northstar",
    color: COLOR.cyan,
    icon: "neodymiumNorthstar",
    description: "60 upgrades here and 60 payouts on the highest floor",
  },
  promethiumPulse: {
    label: "Promethium Pulse",
    color: COLOR.moneyGreen,
    icon: "promethiumPulse",
    description: "61 upgrades here and 61 payouts on the highest floor",
  },
  samariumSanctuary: {
    label: "Samarium Sanctuary",
    color: COLOR.gold,
    icon: "samariumSanctuary",
    description: "62 upgrades here and 62 payouts on the highest floor",
  },
  europiumEncore: {
    label: "Europium Encore",
    color: COLOR.red,
    icon: "europiumEncore",
    description: "63 upgrades here and 63 payouts on the highest floor",
  },
  gadoliniumGlance: {
    label: "Gadolinium Glance",
    color: COLOR.peppermintPink,
    icon: "gadoliniumGlance",
    description: "64 upgrades here and 64 payouts on the highest floor",
  },
  terbiumTempo: {
    label: "Terbium Tempo",
    color: COLOR.silverTicketGray,
    icon: "terbiumTempo",
    description: "65 upgrades here and 65 payouts on the highest floor",
  },
  dysprosiumDirection: {
    label: "Dysprosium Direction",
    color: COLOR.mysticTeal,
    icon: "dysprosiumDirection",
    description: "66 upgrades here and 66 payouts on the highest floor",
  },
  holmiumHalo: {
    label: "Holmium Halo",
    color: COLOR.blue,
    icon: "holmiumHalo",
    description: "67 upgrades here and 67 payouts on the highest floor",
  },
  erbiumElegance: {
    label: "Erbium Elegance",
    color: COLOR.cyan,
    icon: "erbiumElegance",
    description: "68 upgrades here and 68 payouts on the highest floor",
  },
  thuliumThaw: {
    label: "Thulium Thaw",
    color: COLOR.moneyGreen,
    icon: "thuliumThaw",
    description: "69 upgrades here and 69 payouts on the highest floor",
  },
  ytterbiumHourglass: {
    label: "Ytterbium Hourglass",
    color: COLOR.gold,
    icon: "ytterbiumHourglass",
    description: "70 upgrades here and 70 payouts on the highest floor",
  },
  lutetiumLimelight: {
    label: "Lutetium Limelight",
    color: COLOR.red,
    icon: "lutetiumLimelight",
    description: "71 upgrades here and 71 payouts on the highest floor",
  },
  hafniumHorizon: {
    label: "Hafnium Horizon",
    color: COLOR.peppermintPink,
    icon: "hafniumHorizon",
    description: "72 upgrades here and 72 payouts on the highest floor",
  },
  tantalumTrove: {
    label: "Tantalum Trove",
    color: COLOR.silverTicketGray,
    icon: "tantalumTrove",
    description: "73 upgrades here and 73 payouts on the highest floor",
  },
  tungstenTriumph: {
    label: "Tungsten Triumph",
    color: COLOR.mysticTeal,
    icon: "tungstenTriumph",
    description: "74 upgrades here and 74 payouts on the highest floor",
  },
  rheniumRocket: {
    label: "Rhenium Rocket",
    color: COLOR.blue,
    icon: "rheniumRocket",
    description: "75 upgrades here and 75 payouts on the highest floor",
  },
  platinumPodium: {
    label: "Platinum Podium",
    color: COLOR.cyan,
    icon: "platinumPodium",
    description: "78 upgrades here and 78 payouts on the highest floor",
  },
  goldenAtom: {
    label: "Gold Atom",
    color: COLOR.moneyGreen,
    icon: "goldenAtom",
    description: "79 upgrades here and 79 payouts on the highest floor",
  },
  uraniumUplift: {
    label: "Uranium Uplift",
    color: COLOR.gold,
    icon: "uraniumUplift",
    description: "92 upgrades here and 92 payouts on the highest floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
