import type { CritProcDisplayInfo } from "./index";
import { COLOR } from "../../palette";

export const ELEMENT_CRIT_INFO = {
  hydrogenHype: {
    label: "Hydrogen Hype",
    color: COLOR.blue,
    icon: "hydrogenHype",
    description: "1 upgrades here and 1 payouts on the highest floor",
  },
  heliumHighrise: {
    label: "Helium Highrise",
    color: COLOR.cyan,
    icon: "heliumHighrise",
    description: "2 upgrades here and 2 payouts on the highest floor",
  },
  lithiumLift: {
    label: "Lithium Lift",
    color: COLOR.moneyGreen,
    icon: "lithiumLift",
    description: "3 upgrades here and 3 payouts on the highest floor",
  },
  berylliumBrilliance: {
    label: "Beryllium Brilliance",
    color: COLOR.gold,
    icon: "berylliumBrilliance",
    description: "4 upgrades here and 4 payouts on the highest floor",
  },
  carbonCrown: {
    label: "Carbon Crown",
    color: COLOR.red,
    icon: "carbonCrown",
    description: "6 upgrades here and 6 payouts on the highest floor",
  },
  nitrogenNimbus: {
    label: "Nitrogen Nimbus",
    color: COLOR.peppermintPink,
    icon: "nitrogenNimbus",
    description: "7 upgrades here and 7 payouts on the highest floor",
  },
  oxygenOverdrive: {
    label: "Oxygen Overdrive",
    color: COLOR.silverTicketGray,
    icon: "oxygenOverdrive",
    description: "8 upgrades here and 8 payouts on the highest floor",
  },
  fluorineFlash: {
    label: "Fluorine Flash",
    color: COLOR.mysticTeal,
    icon: "fluorineFlash",
    description: "9 upgrades here and 9 payouts on the highest floor",
  },
  sodiumSprinkle: {
    label: "Sodium Sprinkle",
    color: COLOR.blue,
    icon: "sodiumSprinkle",
    description: "11 upgrades here and 11 payouts on the highest floor",
  },
  magnesiumMagnificence: {
    label: "Magnesium Magnificence",
    color: COLOR.cyan,
    icon: "magnesiumMagnificence",
    description: "12 upgrades here and 12 payouts on the highest floor",
  },
  aluminumAllStar: {
    label: "Aluminum All-Star",
    color: COLOR.moneyGreen,
    icon: "aluminumAllStar",
    description: "13 upgrades here and 13 payouts on the highest floor",
  },
  siliconSpark: {
    label: "Silicon Spark",
    color: COLOR.gold,
    icon: "siliconSpark",
    description: "14 upgrades here and 14 payouts on the highest floor",
  },
  phosphorusFlare: {
    label: "Phosphorus Flare",
    color: COLOR.red,
    icon: "phosphorusFlare",
    description: "15 upgrades here and 15 payouts on the highest floor",
  },
  sulfurSunshine: {
    label: "Sulfur Sunshine",
    color: COLOR.peppermintPink,
    icon: "sulfurSunshine",
    description: "16 upgrades here and 16 payouts on the highest floor",
  },
  chlorineConfetti: {
    label: "Chlorine Confetti",
    color: COLOR.silverTicketGray,
    icon: "chlorineConfetti",
    description: "17 upgrades here and 17 payouts on the highest floor",
  },
  argonAfterglow: {
    label: "Argon Afterglow",
    color: COLOR.mysticTeal,
    icon: "argonAfterglow",
    description: "18 upgrades here and 18 payouts on the highest floor",
  },
  potassiumPop: {
    label: "Potassium Pop",
    color: COLOR.blue,
    icon: "potassiumPop",
    description: "19 upgrades here and 19 payouts on the highest floor",
  },
  calciumCornerstone: {
    label: "Calcium Cornerstone",
    color: COLOR.cyan,
    icon: "calciumCornerstone",
    description: "20 upgrades here and 20 payouts on the highest floor",
  },
  scandiumStronghold: {
    label: "Scandium Stronghold",
    color: COLOR.moneyGreen,
    icon: "scandiumStronghold",
    description: "21 upgrades here and 21 payouts on the highest floor",
  },
  titaniumTakeoff: {
    label: "Titanium Takeoff",
    color: COLOR.gold,
    icon: "titaniumTakeoff",
    description: "22 upgrades here and 22 payouts on the highest floor",
  },
  vanadiumVoltage: {
    label: "Vanadium Voltage",
    color: COLOR.red,
    icon: "vanadiumVoltage",
    description: "23 upgrades here and 23 payouts on the highest floor",
  },
  chromiumGleam: {
    label: "Chromium Gleam",
    color: COLOR.peppermintPink,
    icon: "chromiumGleam",
    description: "24 upgrades here and 24 payouts on the highest floor",
  },
  manganeseMomentum: {
    label: "Manganese Momentum",
    color: COLOR.silverTicketGray,
    icon: "manganeseMomentum",
    description: "25 upgrades here and 25 payouts on the highest floor",
  },
  ironEmpire: {
    label: "Iron Empire",
    color: COLOR.mysticTeal,
    icon: "ironEmpire",
    description: "26 upgrades here and 26 payouts on the highest floor",
  },
  cobaltCharge: {
    label: "Cobalt Charge",
    color: COLOR.blue,
    icon: "cobaltCharge",
    description: "27 upgrades here and 27 payouts on the highest floor",
  },
  nickelNestEgg: {
    label: "Nickel Nest Egg",
    color: COLOR.cyan,
    icon: "nickelNestEgg",
    description: "28 upgrades here and 28 payouts on the highest floor",
  },
  copperCurrent: {
    label: "Copper Current",
    color: COLOR.moneyGreen,
    icon: "copperCurrent",
    description: "29 upgrades here and 29 payouts on the highest floor",
  },
  zincZing: {
    label: "Zinc Zing",
    color: COLOR.gold,
    icon: "zincZing",
    description: "30 upgrades here and 30 payouts on the highest floor",
  },
  galliumGlitter: {
    label: "Gallium Glitter",
    color: COLOR.red,
    icon: "galliumGlitter",
    description: "31 upgrades here and 31 payouts on the highest floor",
  },
  germaniumGenius: {
    label: "Germanium Genius",
    color: COLOR.peppermintPink,
    icon: "germaniumGenius",
    description: "32 upgrades here and 32 payouts on the highest floor",
  },
  arsenicAlchemy: {
    label: "Arsenic Alchemy",
    color: COLOR.silverTicketGray,
    icon: "arsenicAlchemy",
    description: "33 upgrades here and 33 payouts on the highest floor",
  },
  seleniumSunburst: {
    label: "Selenium Sunburst",
    color: COLOR.mysticTeal,
    icon: "seleniumSunburst",
    description: "34 upgrades here and 34 payouts on the highest floor",
  },
  bromineBounty: {
    label: "Bromine Bounty",
    color: COLOR.blue,
    icon: "bromineBounty",
    description: "35 upgrades here and 35 payouts on the highest floor",
  },
  kryptonKeepsake: {
    label: "Krypton Keepsake",
    color: COLOR.cyan,
    icon: "kryptonKeepsake",
    description: "36 upgrades here and 36 payouts on the highest floor",
  },
  rubidiumRadiance: {
    label: "Rubidium Radiance",
    color: COLOR.moneyGreen,
    icon: "rubidiumRadiance",
    description: "37 upgrades here and 37 payouts on the highest floor",
  },
  strontiumSpectacle: {
    label: "Strontium Spectacle",
    color: COLOR.gold,
    icon: "strontiumSpectacle",
    description: "38 upgrades here and 38 payouts on the highest floor",
  },
  yttriumYield: {
    label: "Yttrium Yield",
    color: COLOR.red,
    icon: "yttriumYield",
    description: "39 upgrades here and 39 payouts on the highest floor",
  },
  zirconiumZenith: {
    label: "Zirconium Zenith",
    color: COLOR.peppermintPink,
    icon: "zirconiumZenith",
    description: "40 upgrades here and 40 payouts on the highest floor",
  },
  niobiumNexus: {
    label: "Niobium Nexus",
    color: COLOR.silverTicketGray,
    icon: "niobiumNexus",
    description: "41 upgrades here and 41 payouts on the highest floor",
  },
  molybdenumMachine: {
    label: "Molybdenum Machine",
    color: COLOR.mysticTeal,
    icon: "molybdenumMachine",
    description: "42 upgrades here and 42 payouts on the highest floor",
  },
  technetiumTimebank: {
    label: "Technetium Timebank",
    color: COLOR.blue,
    icon: "technetiumTimebank",
    description: "43 upgrades here and 43 payouts on the highest floor",
  },
  rutheniumRiches: {
    label: "Ruthenium Riches",
    color: COLOR.cyan,
    icon: "rutheniumRiches",
    description: "44 upgrades here and 44 payouts on the highest floor",
  },
  rhodiumReflection: {
    label: "Rhodium Reflection",
    color: COLOR.moneyGreen,
    icon: "rhodiumReflection",
    description: "45 upgrades here and 45 payouts on the highest floor",
  },
  palladiumPilot: {
    label: "Palladium Pilot",
    color: COLOR.gold,
    icon: "palladiumPilot",
    description: "46 upgrades here and 46 payouts on the highest floor",
  },
  silverMoonrise: {
    label: "Silver Moonrise",
    color: COLOR.red,
    icon: "silverMoonrise",
    description: "47 upgrades here and 47 payouts on the highest floor",
  },
  cadmiumCatalyst: {
    label: "Cadmium Catalyst",
    color: COLOR.peppermintPink,
    icon: "cadmiumCatalyst",
    description: "48 upgrades here and 48 payouts on the highest floor",
  },
  indiumInsight: {
    label: "Indium Insight",
    color: COLOR.silverTicketGray,
    icon: "indiumInsight",
    description: "49 upgrades here and 49 payouts on the highest floor",
  },
  tinTreasure: {
    label: "Tin Treasure",
    color: COLOR.mysticTeal,
    icon: "tinTreasure",
    description: "50 upgrades here and 50 payouts on the highest floor",
  },
  antimonyAscension: {
    label: "Antimony Ascension",
    color: COLOR.blue,
    icon: "antimonyAscension",
    description: "51 upgrades here and 51 payouts on the highest floor",
  },
  telluriumTreasurelight: {
    label: "Tellurium Treasurelight",
    color: COLOR.cyan,
    icon: "telluriumTreasurelight",
    description: "52 upgrades here and 52 payouts on the highest floor",
  },
  iodineIridescence: {
    label: "Iodine Iridescence",
    color: COLOR.moneyGreen,
    icon: "iodineIridescence",
    description: "53 upgrades here and 53 payouts on the highest floor",
  },
  xenonSpotlight: {
    label: "Xenon Spotlight",
    color: COLOR.gold,
    icon: "xenonSpotlight",
    description: "54 upgrades here and 54 payouts on the highest floor",
  },
  cesiumClockwork: {
    label: "Cesium Clockwork",
    color: COLOR.red,
    icon: "cesiumClockwork",
    description: "55 upgrades here and 55 payouts on the highest floor",
  },
  bariumBeacon: {
    label: "Barium Beacon",
    color: COLOR.peppermintPink,
    icon: "bariumBeacon",
    description: "56 upgrades here and 56 payouts on the highest floor",
  },
  lanthanumLuster: {
    label: "Lanthanum Luster",
    color: COLOR.silverTicketGray,
    icon: "lanthanumLuster",
    description: "57 upgrades here and 57 payouts on the highest floor",
  },
  ceriumShine: {
    label: "Cerium Shine",
    color: COLOR.mysticTeal,
    icon: "ceriumShine",
    description: "58 upgrades here and 58 payouts on the highest floor",
  },
  praseodymiumPrism: {
    label: "Praseodymium Prism",
    color: COLOR.blue,
    icon: "praseodymiumPrism",
    description: "59 upgrades here and 59 payouts on the highest floor",
  },
  neodymiumNorthstar: {
    label: "Neodymium Northstar",
    color: COLOR.cyan,
    icon: "neodymiumNorthstar",
    description: "60 upgrades here and 60 payouts on the highest floor",
  },
  promethiumPulse: {
    label: "Promethium Pulse",
    color: COLOR.moneyGreen,
    icon: "promethiumPulse",
    description: "61 upgrades here and 61 payouts on the highest floor",
  },
  samariumSanctuary: {
    label: "Samarium Sanctuary",
    color: COLOR.gold,
    icon: "samariumSanctuary",
    description: "62 upgrades here and 62 payouts on the highest floor",
  },
  europiumEncore: {
    label: "Europium Encore",
    color: COLOR.red,
    icon: "europiumEncore",
    description: "63 upgrades here and 63 payouts on the highest floor",
  },
  gadoliniumGlance: {
    label: "Gadolinium Glance",
    color: COLOR.peppermintPink,
    icon: "gadoliniumGlance",
    description: "64 upgrades here and 64 payouts on the highest floor",
  },
  terbiumTempo: {
    label: "Terbium Tempo",
    color: COLOR.silverTicketGray,
    icon: "terbiumTempo",
    description: "65 upgrades here and 65 payouts on the highest floor",
  },
  dysprosiumDirection: {
    label: "Dysprosium Direction",
    color: COLOR.mysticTeal,
    icon: "dysprosiumDirection",
    description: "66 upgrades here and 66 payouts on the highest floor",
  },
  holmiumHalo: {
    label: "Holmium Halo",
    color: COLOR.blue,
    icon: "holmiumHalo",
    description: "67 upgrades here and 67 payouts on the highest floor",
  },
  erbiumElegance: {
    label: "Erbium Elegance",
    color: COLOR.cyan,
    icon: "erbiumElegance",
    description: "68 upgrades here and 68 payouts on the highest floor",
  },
  thuliumThaw: {
    label: "Thulium Thaw",
    color: COLOR.moneyGreen,
    icon: "thuliumThaw",
    description: "69 upgrades here and 69 payouts on the highest floor",
  },
  ytterbiumHourglass: {
    label: "Ytterbium Hourglass",
    color: COLOR.gold,
    icon: "ytterbiumHourglass",
    description: "70 upgrades here and 70 payouts on the highest floor",
  },
  lutetiumLimelight: {
    label: "Lutetium Limelight",
    color: COLOR.red,
    icon: "lutetiumLimelight",
    description: "71 upgrades here and 71 payouts on the highest floor",
  },
  hafniumHorizon: {
    label: "Hafnium Horizon",
    color: COLOR.peppermintPink,
    icon: "hafniumHorizon",
    description: "72 upgrades here and 72 payouts on the highest floor",
  },
  tantalumTrove: {
    label: "Tantalum Trove",
    color: COLOR.silverTicketGray,
    icon: "tantalumTrove",
    description: "73 upgrades here and 73 payouts on the highest floor",
  },
  tungstenTriumph: {
    label: "Tungsten Triumph",
    color: COLOR.mysticTeal,
    icon: "tungstenTriumph",
    description: "74 upgrades here and 74 payouts on the highest floor",
  },
  rheniumRocket: {
    label: "Rhenium Rocket",
    color: COLOR.blue,
    icon: "rheniumRocket",
    description: "75 upgrades here and 75 payouts on the highest floor",
  },
  platinumPodium: {
    label: "Platinum Podium",
    color: COLOR.cyan,
    icon: "platinumPodium",
    description: "78 upgrades here and 78 payouts on the highest floor",
  },
  goldenAtom: {
    label: "Golden Atom",
    color: COLOR.moneyGreen,
    icon: "goldenAtom",
    description: "79 upgrades here and 79 payouts on the highest floor",
  },
  uraniumUplift: {
    label: "Uranium Uplift",
    color: COLOR.gold,
    icon: "uraniumUplift",
    description: "92 upgrades here and 92 payouts on the highest floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;
