import type { CritProcDisplayInfo } from "./index";
import { COLOR } from "../../palette";

export const FEATURED_CRIT_INFO = {
  ballerina: {
    label: "Pirouette",
    color: COLOR.peppermintPink,
    icon: "ballerina",
    description: "Three free upgrades and three payouts on this floor",
  },
  cowboy: {
    label: "Roundup Rodeo",
    color: COLOR.gold,
    icon: "cowboy",
    description: "Eight free upgrades on the lowest-level floor",
  },
  dinnerTime: {
    label: "Dinner Time",
    color: COLOR.moneyGreen,
    icon: "dinnerTime",
    description: "Five instant payouts on every unlocked floor",
  },
  fingerGuns: {
    label: "Finger Guns",
    color: COLOR.blue,
    icon: "fingerGuns",
    description: "Two upgrades here and two on the highest floor",
  },
  flamenco: {
    label: "Flamenco",
    color: COLOR.red,
    icon: "flamenco",
    description: "Seven free upgrades on every unlocked floor",
  },
  milestone: {
    label: "Milestone",
    color: COLOR.cyan,
    icon: "milestone",
    description: "Raises this floor to the next multiple of 25",
  },
  moonwalker: {
    label: "Moonwalk",
    color: COLOR.silverTicketGray,
    icon: "moonwalker",
    description: "Six upgrades on this floor and every floor below",
  },
  ninja: {
    label: "Ninja Bonus",
    color: COLOR.nightShiftIndigo,
    icon: "ninja",
    description: "Twelve free upgrades on this floor",
  },
  obelisk: {
    label: "Obelisk",
    color: COLOR.mysticTeal,
    icon: "obelisk",
    description: "Two tier promotions and two upgrades on this floor",
  },
  sharpShooter: {
    label: "Sharpshooter",
    color: COLOR.starYellow,
    icon: "sharpShooter",
    description: "Ten payouts from the highest-earning floor",
  },
  space: {
    label: "Space Race",
    color: COLOR.orange,
    icon: "space",
    description: "Twenty free upgrades on the highest unlocked floor",
  },
  yesChef: {
    label: "Yes, Chef",
    color: COLOR.blue,
    icon: "yesChef",
    description: "Eight instant payouts on every unlocked floor",
  },
  amethyst: {
    label: "Amethyst",
    color: COLOR.purple,
    icon: "amethyst",
    description: "Six instant payouts on this floor",
  },
  blessed: {
    label: "Blessed",
    color: COLOR.heavenlyGold,
    icon: "blessed",
    description: "One tier promotion and three upgrades here",
  },
  centurion: {
    label: "Centurion",
    color: COLOR.red,
    icon: "centurion",
    description: "One hundred free upgrades on this floor",
  },
  checkUp: {
    label: "Check Up",
    color: COLOR.cyan,
    icon: "checkUp",
    description: "Four upgrades and two payouts on the lowest-level floor",
  },
  diamond: {
    label: "Diamond",
    color: COLOR.cyan,
    icon: "diamond",
    description: "Twenty-four instant payouts on this floor",
  },
  emerald: {
    label: "Emerald",
    color: COLOR.moneyGreen,
    icon: "emerald",
    description: "Nine instant payouts on this floor",
  },
  fireman: {
    label: "First Responder",
    color: COLOR.orange,
    icon: "fireman",
    description: "Three upgrades, then one payout on every floor",
  },
  forTheEmperor: {
    label: "For the Emperor",
    color: COLOR.blue,
    icon: "forTheEmperor",
    description: "Twenty-five upgrades on every unlocked floor",
  },
  forTheKing: {
    label: "For the King",
    color: COLOR.starYellow,
    icon: "forTheKing",
    description: "Fifteen upgrades on every unlocked floor",
  },
  goldNugget: {
    label: "Gold Nugget",
    color: COLOR.gold,
    icon: "goldNugget",
    description: "Four instant payouts on this floor",
  },
  goldRush: {
    label: "Gold Rush",
    color: COLOR.gold,
    icon: "goldRush",
    description: "Ten instant payouts on every unlocked floor",
  },
  hammerTime: {
    label: "Hammer Time",
    color: COLOR.red,
    icon: "hammerTime",
    description: "Nine free upgrades on this floor",
  },
  robinHood: {
    label: "Honor among thieves",
    color: COLOR.moneyGreen,
    icon: "robinHood",
    description: "Seven top-earner payouts; three lowest-level upgrades",
  },
  roman: {
    label: "Roman Holiday",
    color: COLOR.fullHouseCrimson,
    icon: "roman",
    description: "Nine upgrades on every unlocked floor",
  },
  ruby: {
    label: "Ruby",
    color: COLOR.red,
    icon: "ruby",
    description: "Twelve instant payouts on this floor",
  },
  samurai: {
    label: "Samurai",
    color: COLOR.fullHouseCrimson,
    icon: "samurai",
    description: "Thirty free upgrades on this floor",
  },
  saphire: {
    label: "Sapphire",
    color: COLOR.blue,
    icon: "saphire",
    description: "Eighteen instant payouts on this floor",
  },
  silverRush: {
    label: "Silver Rush",
    color: COLOR.silverTicketGray,
    icon: "silverRush",
    description: "Six instant payouts on every unlocked floor",
  },
  spy: {
    label: "Undercover",
    color: COLOR.nightShiftIndigo,
    icon: "spy",
    description: "Seventeen upgrades on the lowest-earning floor",
  },
  theLawWon: {
    label: "The Law Won",
    color: COLOR.blue,
    icon: "theLawWon",
    description: "Six upgrades and two payouts on the cheapest floor",
  },
  victorian: {
    label: "High Society",
    color: COLOR.gold,
    icon: "victorian",
    description: "Nine payouts on alternating floors, from the ground",
  },
  executiveSpin: {
    label: "Executive Spin",
    color: COLOR.orange,
    icon: "executiveSpin",
    description: "Four free upgrades on the highest floor",
  },
  rubberStampede: {
    label: "Rubber Stampede",
    color: COLOR.red,
    icon: "rubberStampede",
    description: "Seven instant payouts on every unlocked floor",
  },
  replyAll: {
    label: "Reply All",
    color: COLOR.blue,
    icon: "replyAll",
    description: "Three payouts on this floor and the lowest-level floor",
  },
  stapleOfSuccess: {
    label: "Staple of Success",
    color: COLOR.silverTicketGray,
    icon: "stapleOfSuccess",
    description: "Seven free upgrades on this floor",
  },
  faxOfFortune: {
    label: "Fax of Fortune",
    color: COLOR.moneyGreen,
    icon: "faxOfFortune",
    description: "Eight payouts from the highest-earning floor",
  },
  casualMonday: {
    label: "Casual Monday",
    color: COLOR.peppermintPink,
    icon: "casualMonday",
    description: "Twenty free upgrades on this floor",
  },
  deskJockey: {
    label: "Desk Jockey",
    color: COLOR.nightShiftIndigo,
    icon: "deskJockey",
    description: "Six free upgrades on the lowest-level floor",
  },
  inboxZeroGravity: {
    label: "Inbox Zero Gravity",
    color: COLOR.cyan,
    icon: "inboxZeroGravity",
    description: "Twelve instant payouts on every unlocked floor",
  },
  beanCounter: {
    label: "Bean Counter",
    color: COLOR.heavenlyGold,
    icon: "beanCounter",
    description: "One tier promotion and six upgrades here",
  },
  kingOfTheWorld: {
    label: "King of the World",
    color: COLOR.gold,
    icon: "kingOfTheWorld",
    description: "Thirty free upgrades on the highest floor",
  },
  officeClown: {
    label: "Office Clown",
    color: COLOR.red,
    icon: "officeClown",
    description: "Five free upgrades on the lowest-level floor",
  },
  fridayTieDay: {
    label: "Friday Tie Day",
    color: COLOR.blue,
    icon: "fridayTieDay",
    description: "Ten payouts on alternating floors, from the ground",
  },
  soReady: {
    label: "So Ready",
    color: COLOR.cyan,
    icon: "soReady",
    description: "Fifteen free upgrades on this floor",
  },
  doughDivision: {
    label: "Dough Division",
    color: COLOR.gold,
    icon: "doughDivision",
    description: "Six free upgrades on this floor",
  },
  profitPopcorn: {
    label: "Profit Popcorn",
    color: COLOR.heavenlyGold,
    icon: "profitPopcorn",
    description: "Four instant payouts on every unlocked floor",
  },
  donutDisturb: {
    label: "Donut Disturb",
    color: COLOR.peppermintPink,
    icon: "donutDisturb",
    description: "Five upgrades and five payouts on this floor",
  },
  cakeDay: {
    label: "Cake Day",
    color: COLOR.red,
    icon: "cakeDay",
    description: "Twelve upgrades on the lowest-level floor",
  },
  champagneProblems: {
    label: "Champagne Problems",
    color: COLOR.starYellow,
    icon: "champagneProblems",
    description: "Fifteen payouts from the highest-earning floor",
  },
  bonusBurrito: {
    label: "Bonus Burrito",
    color: COLOR.orange,
    icon: "bonusBurrito",
    description: "Eight upgrades and three payouts on this floor",
  },
  sundaeBest: {
    label: "Sundae Best",
    color: COLOR.blue,
    icon: "sundaeBest",
    description: "Ten payouts on alternating floors, from the ground",
  },
  popTheQuestion: {
    label: "Pop the Question",
    color: COLOR.cyan,
    icon: "popTheQuestion",
    description: "One tier promotion and four upgrades here",
  },
  partyCrasher: {
    label: "Party Crasher",
    color: COLOR.red,
    icon: "partyCrasher",
    description: "Three upgrades here and three on the highest floor",
  },
  wizard: {
    label: "Wizard",
    color: COLOR.purple,
    icon: "wizard",
    description: "Two tier promotions and five upgrades here",
  },
  epic: {
    label: "Epic Loot",
    color: COLOR.royalFlushPurple,
    icon: "epic",
    description: "Forty free upgrades on this floor",
  },
  ready: {
    label: "Dual Wield",
    color: COLOR.fourOfAKindIndigo,
    icon: "ready",
    description: "Four upgrades and four payouts on the top earner",
  },
  workWork: {
    label: "Work Work",
    color: COLOR.suppliesGiveawayLime,
    icon: "workWork",
    description: "Eleven free upgrades on every unlocked floor",
  },
  yesWarchief: {
    label: "Yes, Warchief",
    color: COLOR.doubleDownCrimson,
    icon: "yesWarchief",
    description: "Fourteen instant payouts on every unlocked floor",
  },
  youAreNotPrepared: {
    label: "Not Prepared",
    color: COLOR.threeOfAKindGreen,
    icon: "youAreNotPrepared",
    description: "Two tier promotions and nine upgrades here",
  },
  arcana: {
    label: "Arcane Surge",
    color: COLOR.pairBlue,
    icon: "arcana",
    description: "One tier promotion and twelve upgrades here",
  },
  bigDaddy: {
    label: "Big Daddy",
    color: COLOR.mysticTeal,
    icon: "bigDaddy",
    description: "Forty-five free upgrades on this floor",
  },
  chonk: {
    label: "Chonk",
    color: COLOR.suppliesGiveawayLime,
    icon: "chonk",
    description: "Sixteen instant payouts on this floor",
  },
  cyberPunk: {
    label: "Cyberpunk",
    color: COLOR.cyan,
    icon: "cyberPunk",
    description: "Thirteen free upgrades on this floor",
  },
  dodgeThis: {
    label: "Dodge This",
    color: COLOR.unionBossSlate,
    icon: "dodgeThis",
    description: "Six payouts from the highest-earning floor",
  },
  whiteRabbit: {
    label: "White Rabbit",
    color: COLOR.silverTicketGray,
    icon: "whiteRabbit",
    description: "Five upgrades here and five on the lowest-level floor",
  },
  gladiator: {
    label: "Gladiator",
    color: COLOR.goldenHandshakeGold,
    icon: "gladiator",
    description: "Thirteen free upgrades on every unlocked floor",
  },
  iDidntAskForThis: {
    label: "I Didn't Ask For This",
    color: COLOR.rainCheckBlue,
    icon: "iDidntAskForThis",
    description: "One tier promotion and twenty upgrades here",
  },
  iHatePortals: {
    label: "I Hate Portals",
    color: COLOR.snowdayFrost,
    icon: "iHatePortals",
    description: "Eleven instant payouts on this floor",
  },
  littleSister: {
    label: "Little Sister",
    color: COLOR.easterSalePink,
    icon: "littleSister",
    description: "Seven free upgrades on the lowest-level floor",
  },
  magicIsATool: {
    label: "Magic Is a Tool",
    color: COLOR.halloweenSalePurple,
    icon: "magicIsATool",
    description: "Eight upgrades on alternating floors, from the ground",
  },
  megaChonk: {
    label: "Mega Chonk",
    color: COLOR.fullHouseCrimson,
    icon: "megaChonk",
    description: "Twenty-two instant payouts on this floor",
  },
  metal: {
    label: "Heavy Metal",
    color: COLOR.goldStandardAmber,
    icon: "metal",
    description: "Seventeen free upgrades on the highest floor",
  },
  princess: {
    label: "Princess Cut",
    color: COLOR.springSalePink,
    icon: "princess",
    description: "Thirteen payouts on alternating floors, from the ground",
  },
  spaceAndTime: {
    label: "Space and Time",
    color: COLOR.nightShiftIndigo,
    icon: "spaceAndTime",
    description: "Nine upgrades on this floor and every floor below",
  },
  thinkWithYourHead: {
    label: "Think With Your Head",
    color: COLOR.executiveOrderTeal,
    icon: "thinkWithYourHead",
    description: "Five upgrades and five payouts on the lowest-level floor",
  },
  wouldYouKindly: {
    label: "Would You Kindly",
    color: COLOR.espressoShotBrown,
    icon: "wouldYouKindly",
    description: "Sixteen instant payouts on every unlocked floor",
  },
  yesYourHighness: {
    label: "Yes, Your Highness",
    color: COLOR.heavenlyGold,
    icon: "yesYourHighness",
    description: "Nineteen free upgrades on every unlocked floor",
  },
  bulletDodger: {
    label: "Bullet Dodger",
    color: COLOR.pairBlue,
    icon: "bulletDodger",
    description: "Fourteen free upgrades on this floor",
  },
  nothingToSee: {
    label: "Nothing to See",
    color: COLOR.bullMarketGreen,
    icon: "nothingToSee",
    description: "Twenty instant payouts on this floor",
  },
  nowIAmSuspicious: {
    label: "Now I'm Suspicious",
    color: COLOR.nightOwlIndigo,
    icon: "nowIAmSuspicious",
    description: "Seventeen instant payouts on every unlocked floor",
  },
  redOrBlue: {
    label: "Red or Blue",
    color: COLOR.grandOpeningRose,
    icon: "redOrBlue",
    description: "Six upgrades on the lowest floor; six top-earner payouts",
  },
  abraCashDabra: {
    label: "Abra-Cash-Dabra",
    color: COLOR.moneyGreen,
    icon: "abraCashDabra",
    description: "Twenty-five instant payouts on this floor",
  },
  captainOfIndustry: {
    label: "Captain of Industry",
    color: COLOR.fastForwardBlue,
    icon: "captainOfIndustry",
    description: "Twenty-one free upgrades on every unlocked floor",
  },
  clowningAround: {
    label: "Clowning Around",
    color: COLOR.summerSaleOrange,
    icon: "clowningAround",
    description: "Three upgrades and three payouts on every floor",
  },
  discoDividend: {
    label: "Disco Dividend",
    color: COLOR.silverTicketGray,
    icon: "discoDividend",
    description: "Eleven payouts on alternating floors, from the ground",
  },
  mimeYourBusiness: {
    label: "Mime Your Business",
    color: COLOR.winterSaleIceBlue,
    icon: "mimeYourBusiness",
    description: "Eight upgrades on this floor and every floor below",
  },
  redCarpetTreatment: {
    label: "Red Carpet Treatment",
    color: COLOR.fullHouseCrimson,
    icon: "redCarpetTreatment",
    description: "Twelve payouts from the highest-earning floor",
  },
  rockTheStock: {
    label: "Rock the Stock",
    color: COLOR.peppermintPink,
    icon: "rockTheStock",
    description: "Sixteen free upgrades on this floor",
  },
  strongReturn: {
    label: "Strong Return",
    color: COLOR.goldenHandshakeGold,
    icon: "strongReturn",
    description: "Twenty-six free upgrades on the highest floor",
  },
  theBigCheese: {
    label: "The Big Cheese",
    color: COLOR.sunshineGold,
    icon: "theBigCheese",
    description: "Two tier promotions and thirty upgrades here",
  },
  queenOfQueens: {
    label: "Queen of Queens",
    color: COLOR.royalFlushPurple,
    icon: "queenOfQueens",
    description: "Twenty-eight free upgrades on every unlocked floor",
  },
  bubbleEconomy: {
    label: "Bubble Economy",
    color: COLOR.snowballBlue,
    icon: "bubbleEconomy",
    description: "Seven instant payouts on this floor",
  },
  cloudNineToFive: {
    label: "Cloud Nine to Five",
    color: COLOR.floorShareBlue,
    icon: "cloudNineToFive",
    description: "Nine instant payouts on every unlocked floor",
  },
  luckyLaundromat: {
    label: "Lucky Laundromat",
    color: COLOR.luckyCloverGreen,
    icon: "luckyLaundromat",
    description: "Five upgrades and five payouts on every floor",
  },
  moneyMagnet: {
    label: "Money Magnet",
    color: COLOR.red,
    icon: "moneyMagnet",
    description: "Fourteen payouts from the highest-earning floor",
  },
  overTheRainbow: {
    label: "Over the Rainbow",
    color: COLOR.purple,
    icon: "overTheRainbow",
    description: "Fifteen payouts on alternating floors, from the ground",
  },
  pocketDimension: {
    label: "Pocket Dimension",
    color: COLOR.fourOfAKindIndigo,
    icon: "pocketDimension",
    description: "Eighteen upgrades on this floor and every floor below",
  },
  shootingStarEmployee: {
    label: "Shooting Star",
    color: COLOR.starYellow,
    icon: "shootingStarEmployee",
    description: "Twenty-three free upgrades on the highest floor",
  },
  treasureMeasure: {
    label: "Treasure Measure",
    color: COLOR.supplyRunTan,
    icon: "treasureMeasure",
    description: "Ten free upgrades on the lowest-level floor",
  },
  wishfulBanking: {
    label: "Wishful Banking",
    color: COLOR.goldenTicketYellow,
    icon: "wishfulBanking",
    description: "Two tier promotions and twelve upgrades here",
  },
  backToTheFiscal: {
    label: "Back to the Fiscal",
    color: COLOR.blue,
    icon: "backToTheFiscal",
    description: "Eleven free upgrades on this floor",
  },
  despicableFees: {
    label: "Despicable Fees",
    color: COLOR.amber,
    icon: "despicableFees",
    description: "Thirty instant payouts on this floor",
  },
  howToTrainYourManager: {
    label: "Train Your Manager",
    color: COLOR.teal,
    icon: "howToTrainYourManager",
    description: "Four upgrades and six payouts on this floor",
  },
  jurassicPerk: {
    label: "Jurassic Perk",
    color: COLOR.dressCodeGreen,
    icon: "jurassicPerk",
    description: "Thirteen instant payouts on this floor",
  },
  raidersOfTheLostReceipt: {
    label: "Lost Receipt",
    color: COLOR.chairGiveawayBrown,
    icon: "raidersOfTheLostReceipt",
    description: "Nine free upgrades on the lowest-level floor",
  },
  theDevilWearsPawda: {
    label: "The Devil Wears Pawda",
    color: COLOR.fancyFridayIndigo,
    icon: "theDevilWearsPawda",
    description: "Fourteen upgrades on the cheapest floor",
  },
  theExpenseMatrix: {
    label: "The Expense Matrix",
    color: COLOR.payoutOlive,
    icon: "theExpenseMatrix",
    description: "Eighteen instant payouts on every unlocked floor",
  },
  theFastAndTheFurriest: {
    label: "The Fast and the Furriest",
    color: COLOR.roundUpOrange,
    icon: "theFastAndTheFurriest",
    description: "Twelve upgrades on alternating floors, from the ground",
  },
  theFellowshipOfTheBling: {
    label: "Fellowship of the Bling",
    color: COLOR.mergerGold,
    icon: "theFellowshipOfTheBling",
    description: "Six upgrades and six payouts on every floor",
  },
  theGreatCatsby: {
    label: "The Great Catsby",
    color: COLOR.coinGold,
    icon: "theGreatCatsby",
    description: "One tier promotion and thirty upgrades here",
  },
  theLordOfTheRingBinders: {
    label: "The Ring Binders",
    color: COLOR.goldenParachuteMarigold,
    icon: "theLordOfTheRingBinders",
    description: "Thirty-five free upgrades on this floor",
  },
  breakEven: {
    label: "Break Even",
    color: COLOR.performanceBonusBlue,
    icon: "breakEven",
    description: "Eight free upgrades on this floor",
  },
  chaChaChing: {
    label: "Cha-Cha-Ching",
    color: COLOR.amberMuted,
    icon: "chaChaChing",
    description: "Eight instant payouts on this floor",
  },
  charlestonCharge: {
    label: "Charleston Charge",
    color: COLOR.teaBreakBrown,
    icon: "charlestonCharge",
    description: "Eleven free upgrades on the lowest-level floor",
  },
  congaCompounding: {
    label: "Conga Compounding",
    color: COLOR.springSalePink,
    icon: "congaCompounding",
    description: "Four upgrades and four payouts on every floor",
  },
  robotResources: {
    label: "Robot Resources",
    color: COLOR.headhunterRust,
    icon: "robotResources",
    description: "Nineteen free upgrades on the highest floor",
  },
  rumbaReturns: {
    label: "Rumba Returns",
    color: COLOR.redActive,
    icon: "rumbaReturns",
    description: "Twenty-one instant payouts on this floor",
  },
  salsaSalary: {
    label: "Salsa Salary",
    color: COLOR.peppermintPink,
    icon: "salsaSalary",
    description: "Thirteen payouts from the highest-earning floor",
  },
  shuffleTheFunds: {
    label: "Shuffle the Funds",
    color: COLOR.springCleaningMint,
    icon: "shuffleTheFunds",
    description: "Fourteen upgrades on this floor and every floor below",
  },
  tangoTender: {
    label: "Tango Tender",
    color: COLOR.fullHouseCrimson,
    icon: "tangoTender",
    description: "Seven upgrades here and seven on the highest floor",
  },
  tapThatAsset: {
    label: "Tap That Asset",
    color: COLOR.bonusRoundGold,
    icon: "tapThatAsset",
    description: "Seventeen payouts on alternating floors, from the ground",
  },
  waltzStreet: {
    label: "Waltz Street",
    color: COLOR.shareholdersGreen,
    icon: "waltzStreet",
    description: "Seventeen free upgrades on every unlocked floor",
  },
  prehistoric: {
    label: "Prehistoric",
    color: COLOR.chairGiveawayBrown,
    icon: "prehistoric",
    description: "One tier promotion and forty upgrades here",
  },
  breadyOrNot: {
    label: "Bready or Not",
    color: COLOR.goldenHandshakeGold,
    icon: "breadyOrNot",
    description: "Eleven upgrades on this floor and every floor below",
  },
  eggcellentWork: {
    label: "Egg-cellent Work",
    color: COLOR.sunshineGold,
    icon: "eggcellentWork",
    description: "One tier promotion and eight upgrades here",
  },
  holyGuacamole: {
    label: "Holy Guacamole",
    color: COLOR.dressCodeGreen,
    icon: "holyGuacamole",
    description: "Nineteen instant payouts on every unlocked floor",
  },
  loafActually: {
    label: "Loaf Actually",
    color: COLOR.espressoShotBrown,
    icon: "loafActually",
    description: "Twelve free upgrades on every unlocked floor",
  },
  pastaLaVista: {
    label: "Pasta La Vista",
    color: COLOR.orange,
    icon: "pastaLaVista",
    description: "Sixteen payouts on alternating floors, from the ground",
  },
  souperStar: {
    label: "Souper Star",
    color: COLOR.amberMuted,
    icon: "souperStar",
    description: "Sixteen payouts from the highest-earning floor",
  },
  tacoBoutIt: {
    label: "Taco 'Bout It",
    color: COLOR.autumnSaleAmber,
    icon: "tacoBoutIt",
    description: "Four upgrades here and four on the lowest-level floor",
  },
  theGreatPancakeStack: {
    label: "The Great Pancake Stack",
    color: COLOR.supplyRunTan,
    icon: "theGreatPancakeStack",
    description: "Twenty-one upgrades here and every floor below",
  },
  wokAndRoll: {
    label: "Wok and Roll",
    color: COLOR.summerSaleOrange,
    icon: "wokAndRoll",
    description: "Twenty-four free upgrades on the highest floor",
  },
  iAmTheNight: {
    label: "I Am the Night",
    color: COLOR.fourOfAKindIndigo,
    icon: "iAmTheNight",
    description: "Twenty-seven free upgrades on every unlocked floor",
  },
  tubs: {
    label: "Tubs",
    color: COLOR.rainCheckBlue,
    icon: "tubs",
    description: "Twenty-six instant payouts on this floor",
  },
  whySoSerious: {
    label: "Why So Serious",
    color: COLOR.halloweenSalePurple,
    icon: "whySoSerious",
    description: "Two tier promotions and twenty upgrades here",
  },
  avocardio: {
    label: "Avocardio",
    color: COLOR.bullMarketGreen,
    icon: "avocardio",
    description: "Fifteen free upgrades on this floor",
  },
  butterBelieveIt: {
    label: "Butter Believe It",
    color: COLOR.sunshineGold,
    icon: "butterBelieveIt",
    description: "Eighteen instant payouts on this floor",
  },
  cheesePullChampion: {
    label: "Cheese Pull Champion",
    color: COLOR.goldenHandshakeGold,
    icon: "cheesePullChampion",
    description: "Six upgrades and six payouts on this floor",
  },
  grillSergeant: {
    label: "Grill Sergeant",
    color: COLOR.red,
    icon: "grillSergeant",
    description: "Twenty free upgrades on every unlocked floor",
  },
  noodleNap: {
    label: "Noodle Nap",
    color: COLOR.autumnSaleAmber,
    icon: "noodleNap",
    description: "Twenty-two payouts on alternating floors, from the ground",
  },
  picklePredicament: {
    label: "Pickle Predicament",
    color: COLOR.dressCodeGreen,
    icon: "picklePredicament",
    description: "Eight free upgrades on the lowest-level floor",
  },
  golem: {
    label: "Golem",
    color: COLOR.unionBossSlate,
    icon: "golem",
    description: "Thirty-five free upgrades on the highest floor",
  },
  hotPotato: {
    label: "Hot Potato",
    color: COLOR.roundUpOrange,
    icon: "hotPotato",
    description: "Eighteen instant payouts on this floor",
  },
  brunchBoss: {
    label: "Brunch Boss",
    color: COLOR.supplyRunTan,
    icon: "brunchBoss",
    description: "Seven upgrades and seven payouts on this floor",
  },
  curryFavour: {
    label: "Curry Favour",
    color: COLOR.halloweenSalePurple,
    icon: "curryFavour",
    description: "Fourteen payouts from the highest-earning floor",
  },
  dimSumDynasty: {
    label: "Dim Sum Dynasty",
    color: COLOR.goldenHandshakeGold,
    icon: "dimSumDynasty",
    description: "Fifteen free upgrades on every unlocked floor",
  },
  soupDumplingSurgeon: {
    label: "Soup Dumpling Surgeon",
    color: COLOR.teaBreakBrown,
    icon: "soupDumplingSurgeon",
    description: "Five upgrades and ten payouts on this floor",
  },
  chocolateFountainOfYouth: {
    label: "Chocolate Fountain of Youth",
    color: COLOR.autumnSaleAmber,
    icon: "chocolateFountainOfYouth",
    description: "Twenty instant payouts on this floor",
  },
  gummyBearMarket: {
    label: "Gummy Bear Market",
    color: COLOR.red,
    icon: "gummyBearMarket",
    description: "Ten free upgrades on every unlocked floor",
  },
  jawbreaker: {
    label: "Jawbreaker",
    color: COLOR.purple,
    icon: "jawbreaker",
    description: "Eighteen free upgrades on this floor",
  },
  licoriceLaces: {
    label: "Licorice Laces",
    color: COLOR.fullHouseCrimson,
    icon: "licoriceLaces",
    description: "Nine free upgrades on the lowest-level floor",
  },
  lollipopGuild: {
    label: "Lollipop Guild",
    color: COLOR.peppermintPink,
    icon: "lollipopGuild",
    description: "Twelve payouts on alternating floors, from the ground",
  },
  marshmallowMountain: {
    label: "Marshmallow Mountain",
    color: COLOR.white,
    icon: "marshmallowMountain",
    description: "Eight free upgrades on the highest unlocked floor",
  },
  sugarHigh: {
    label: "Sugar High",
    color: COLOR.starYellow,
    icon: "sugarHigh",
    description: "Five upgrades and five payouts on every unlocked floor",
  },
  bubblegumBalloon: {
    label: "Bubblegum Balloon",
    color: COLOR.springSalePink,
    icon: "bubblegumBalloon",
    description: "Fifteen instant payouts on this floor",
  },
  candyCaneClimber: {
    label: "Candy Cane Climber",
    color: COLOR.red,
    icon: "candyCaneClimber",
    description: "Twelve free upgrades on the highest unlocked floor",
  },
  sherbetSherpa: {
    label: "Sherbet Sherpa",
    color: COLOR.easterSalePink,
    icon: "sherbetSherpa",
    description: "Eight instant payouts on every unlocked floor",
  },
  toffeeTrap: {
    label: "Toffee Trap",
    color: COLOR.autumnSaleAmber,
    icon: "toffeeTrap",
    description: "Seven free upgrades on this floor",
  },
  cottonCandyCloud: {
    label: "Cotton Candy Cloud",
    color: COLOR.peppermintPink,
    icon: "cottonCandyCloud",
    description: "Eleven instant payouts on this floor",
  },
  fudgeIt: {
    label: "Fudge It",
    color: COLOR.autumnSaleAmber,
    icon: "fudgeIt",
    description: "Fourteen free upgrades on this floor",
  },
  gobstopperGetaway: {
    label: "Gobstopper Getaway",
    color: COLOR.orange,
    icon: "gobstopperGetaway",
    description: "Thirteen free upgrades on the highest floor",
  },
  jellyBeanJamboree: {
    label: "Jelly Bean Jamboree",
    color: COLOR.springSalePink,
    icon: "jellyBeanJamboree",
    description: "Ten payouts on alternating floors, from the ground",
  },
  rockCandyQuarry: {
    label: "Rock Candy Quarry",
    color: COLOR.cyan,
    icon: "rockCandyQuarry",
    description: "One tier promotion and seven upgrades here",
  },
  sprinkleStorm: {
    label: "Sprinkle Storm",
    color: COLOR.blue,
    icon: "sprinkleStorm",
    description: "Six free upgrades on every unlocked floor",
  },
  dungeonAccountant: {
    label: "Dungeon Accountant",
    color: COLOR.nightShiftIndigo,
    icon: "dungeonAccountant",
    description: "Nine free upgrades on this floor",
  },
  lootGoblin: {
    label: "Loot Goblin",
    color: COLOR.bullMarketGreen,
    icon: "lootGoblin",
    description: "Sixteen instant payouts on this floor",
  },
  inventoryFull: {
    label: "Inventory Full",
    color: COLOR.gold,
    icon: "inventoryFull",
    description: "Twelve free upgrades on this floor",
  },
  sideQuestSalary: {
    label: "Side Quest Salary",
    color: COLOR.heavenlyGold,
    icon: "sideQuestSalary",
    description: "Seven payouts from the highest-earning floor",
  },
  minMaxManager: {
    label: "Min-Max Manager",
    color: COLOR.cyan,
    icon: "minMaxManager",
    description: "Ten free upgrades on the lowest-level floor",
  },
  criticalKnit: {
    label: "Critical Knit",
    color: COLOR.peppermintPink,
    icon: "criticalKnit",
    description: "Six payouts on alternating floors, from the ground",
  },
  savePointSavings: {
    label: "Save Point Savings",
    color: COLOR.blue,
    icon: "savePointSavings",
    description: "One tier promotion and five upgrades here",
  },
  achievementUnlocked: {
    label: "Achievement Unlocked",
    color: COLOR.starYellow,
    icon: "achievementUnlocked",
    description: "One tier promotion and eight upgrades here",
  },
  newGamePlus: {
    label: "New Game Plus",
    color: COLOR.orange,
    icon: "newGamePlus",
    description: "Twenty free upgrades on this floor",
  },
  speedrunPayroll: {
    label: "Speedrun Payroll",
    color: COLOR.red,
    icon: "speedrunPayroll",
    description: "Fifteen instant payouts on every unlocked floor",
  },
  lagCompensation: {
    label: "Lag Compensation",
    color: COLOR.silverTicketGray,
    icon: "lagCompensation",
    description: "Nine instant payouts on this floor",
  },
  patchNotesPayday: {
    label: "Patch Notes Payday",
    color: COLOR.moneyGreen,
    icon: "patchNotesPayday",
    description: "Eleven free upgrades on the highest floor",
  },
  biggerOnTheInside: {
    label: "Bigger on the Inside",
    color: COLOR.blue,
    icon: "biggerOnTheInside",
    description: "Ten instant payouts on every unlocked floor",
  },
  cacheMeOutside: {
    label: "Cache Me Outside",
    color: COLOR.orange,
    icon: "cacheMeOutside",
    description: "Eight free upgrades on the lowest-level floor",
  },
  itCompiles: {
    label: "It Compiles!",
    color: COLOR.moneyGreen,
    icon: "itCompiles",
    description: "Fifteen free upgrades on this floor",
  },
  magicalPayrollGirl: {
    label: "Magical Payroll Girl",
    color: COLOR.peppermintPink,
    icon: "magicalPayrollGirl",
    description: "One tier promotion and ten upgrades here",
  },
  mechaMiddleManagement: {
    label: "Mecha Middle Management",
    color: COLOR.red,
    icon: "mechaMiddleManagement",
    description: "Twelve free upgrades on every unlocked floor",
  },
  mergeConflict: {
    label: "Merge Conflict",
    color: COLOR.fullHouseCrimson,
    icon: "mergeConflict",
    description: "Seven upgrades and seven payouts on this floor",
  },
  mintCondition: {
    label: "Mint Condition",
    color: COLOR.cyan,
    icon: "mintCondition",
    description: "Eighteen payouts from the highest-earning floor",
  },
  stackOverflowing: {
    label: "Stack Overflowing",
    color: COLOR.gold,
    icon: "stackOverflowing",
    description: "Nine free upgrades on the highest floor",
  },
  oneMoreRound: {
    label: "One More Round",
    color: COLOR.sunshineGold,
    icon: "oneMoreRound",
    description: "Eight upgrades and eight payouts on this floor",
  },
  couchCoOpCapital: {
    label: "Couch Co-Op Capital",
    color: COLOR.blue,
    icon: "couchCoOpCapital",
    description: "Nine free upgrades on every unlocked floor",
  },
  hardCarry: {
    label: "Hard Carry",
    color: COLOR.orange,
    icon: "hardCarry",
    description: "Fourteen free upgrades on the highest floor",
  },
  readyCheck: {
    label: "Ready Check",
    color: COLOR.moneyGreen,
    icon: "readyCheck",
    description: "Six free upgrades on every unlocked floor",
  },
  queueRoyalty: {
    label: "Queue Royalty",
    color: COLOR.heavenlyGold,
    icon: "queueRoyalty",
    description: "Twelve instant payouts on this floor",
  },
  rankedAndBanked: {
    label: "Ranked and Banked",
    color: COLOR.gold,
    icon: "rankedAndBanked",
    description: "Eleven free upgrades on this floor",
  },
  victoryPose: {
    label: "Victory Pose",
    color: COLOR.starYellow,
    icon: "victoryPose",
    description: "Eighteen free upgrades on this floor",
  },
  emoteEconomy: {
    label: "Emote Economy",
    color: COLOR.peppermintPink,
    icon: "emoteEconomy",
    description: "Eight payouts on every unlocked floor",
  },
  checkpointChampion: {
    label: "Checkpoint Champion",
    color: COLOR.cyan,
    icon: "checkpointChampion",
    description: "Ten free upgrades on the highest floor",
  },
  fishingForFunds: {
    label: "Fishing for Funds",
    color: COLOR.moneyGreen,
    icon: "fishingForFunds",
    description: "Thirteen instant payouts on this floor",
  },
  purrfectOrigin: {
    label: "Purrfect Origin",
    color: COLOR.sunshineGold,
    icon: "purrfectOrigin",
    description: "Seven free upgrades on this floor",
  },
  capeEscape: {
    label: "Cape Escape",
    color: COLOR.red,
    icon: "capeEscape",
    description: "Ten payouts from the highest-earning floor",
  },
  thunderPaws: {
    label: "Thunder Paws",
    color: COLOR.blue,
    icon: "thunderPaws",
    description: "Eight free upgrades on every unlocked floor",
  },
  clawAndOrder: {
    label: "Claw and Order",
    color: COLOR.cyan,
    icon: "clawAndOrder",
    description: "Six instant payouts on this floor",
  },
  felineFury: {
    label: "Feline Fury",
    color: COLOR.fullHouseCrimson,
    icon: "felineFury",
    description: "Sixteen free upgrades on this floor",
  },
  sidekickShuffle: {
    label: "Sidekick Shuffle",
    color: COLOR.peppermintPink,
    icon: "sidekickShuffle",
    description: "Seven upgrades on alternating floors, from the ground",
  },
  cosmicCatapult: {
    label: "Cosmic Catapult",
    color: COLOR.nightShiftIndigo,
    icon: "cosmicCatapult",
    description: "Nine payouts on every unlocked floor",
  },
  theMoonstoneKey: {
    label: "The Moonstone Key",
    color: COLOR.silverTicketGray,
    icon: "theMoonstoneKey",
    description: "One tier promotion and six upgrades here",
  },
  spellbookSupreme: {
    label: "Spellbook Supreme",
    color: COLOR.purple,
    icon: "spellbookSupreme",
    description: "Twelve free upgrades on this floor",
  },
  prismPotion: {
    label: "Prism Potion",
    color: COLOR.cyan,
    icon: "prismPotion",
    description: "Fourteen payouts from the highest-earning floor",
  },
  galaxyGumball: {
    label: "Galaxy Gumball",
    color: COLOR.springSalePink,
    icon: "galaxyGumball",
    description: "Eleven instant payouts on this floor",
  },
  treasureTruffle: {
    label: "Treasure Truffle",
    color: COLOR.goldenHandshakeGold,
    icon: "treasureTruffle",
    description: "Five upgrades and five payouts on this floor",
  },
  wizardsWaffle: {
    label: "Wizard's Waffle",
    color: COLOR.autumnSaleAmber,
    icon: "wizardsWaffle",
    description: "Ten free upgrades on every unlocked floor",
  },
  goldenFortuneCookie: {
    label: "Golden Fortune Cookie",
    color: COLOR.heavenlyGold,
    icon: "goldenFortuneCookie",
    description: "Nine free upgrades on the lowest-level floor",
  },
  crystalDragonEgg: {
    label: "Crystal Dragon Egg",
    color: COLOR.cyan,
    icon: "crystalDragonEgg",
    description: "Twelve free upgrades on this floor",
  },
  diamondCompass: {
    label: "Diamond Compass",
    color: COLOR.blue,
    icon: "diamondCompass",
    description: "Ten payouts from the highest-earning floor",
  },
  emeraldCrown: {
    label: "Emerald Crown",
    color: COLOR.moneyGreen,
    icon: "emeraldCrown",
    description: "One tier promotion and eight upgrades here",
  },
  goldenFleece: {
    label: "Golden Fleece",
    color: COLOR.gold,
    icon: "goldenFleece",
    description: "Seven payouts on every unlocked floor",
  },
  imperialScepter: {
    label: "Imperial Scepter",
    color: COLOR.heavenlyGold,
    icon: "imperialScepter",
    description: "Thirteen free upgrades on the highest floor",
  },
  rubyHeartRelic: {
    label: "Ruby Heart Relic",
    color: COLOR.fullHouseCrimson,
    icon: "rubyHeartRelic",
    description: "Twelve instant payouts on this floor",
  },
  sapphireHourglass: {
    label: "Sapphire Hourglass",
    color: COLOR.silverTicketGray,
    icon: "sapphireHourglass",
    description: "Nine payouts on alternating floors, from the ground",
  },
  vaultOfJewels: {
    label: "Vault of Jewels",
    color: COLOR.goldenHandshakeGold,
    icon: "vaultOfJewels",
    description: "Six free upgrades on every unlocked floor",
  },
  goldenIdol: {
    label: "Golden Idol",
    color: COLOR.goldenParachuteMarigold,
    icon: "goldenIdol",
    description: "Fifteen free upgrades on this floor",
  },
  emberwingDragon: {
    label: "Emberwing Dragon",
    color: COLOR.red,
    icon: "emberwingDragon",
    description: "Eighteen free upgrades on this floor",
  },
  moonlitKirin: {
    label: "Moonlit Kirin",
    color: COLOR.silverTicketGray,
    icon: "moonlitKirin",
    description: "Ten payouts from the highest-earning floor",
  },
  pocketPhoenix: {
    label: "Pocket Phoenix",
    color: COLOR.sunshineGold,
    icon: "pocketPhoenix",
    description: "Seven free upgrades on this floor",
  },
  crystalGriffin: {
    label: "Crystal Griffin",
    color: COLOR.blue,
    icon: "crystalGriffin",
    description: "Eight payouts on every unlocked floor",
  },
  velvetManticore: {
    label: "Velvet Manticore",
    color: COLOR.halloweenSalePurple,
    icon: "velvetManticore",
    description: "One tier promotion and nine upgrades here",
  },
  frostfangYeti: {
    label: "Frostfang Yeti",
    color: COLOR.frozenIceBlue,
    icon: "frostfangYeti",
    description: "Eleven free upgrades on every unlocked floor",
  },
  lanternKitsune: {
    label: "Lantern Kitsune",
    color: COLOR.orange,
    icon: "lanternKitsune",
    description: "Six instant payouts on this floor",
  },
  coralSeaSerpent: {
    label: "Coral Sea Serpent",
    color: COLOR.cyan,
    icon: "coralSeaSerpent",
    description: "Twelve payouts on this floor",
  },
  clockworkMinotaur: {
    label: "Clockwork Minotaur",
    color: COLOR.gold,
    icon: "clockworkMinotaur",
    description: "Thirteen free upgrades on this floor",
  },
  starryCerberus: {
    label: "Starry Cerberus",
    color: COLOR.nightShiftIndigo,
    icon: "starryCerberus",
    description: "Eight free upgrades on alternating floors, from the ground",
  },
  goldenSphinx: {
    label: "Golden Sphinx",
    color: COLOR.heavenlyGold,
    icon: "goldenSphinx",
    description: "Ten free upgrades on the highest floor",
  },
  mossbackTreant: {
    label: "Mossback Treant",
    color: COLOR.moneyGreen,
    icon: "mossbackTreant",
    description: "Five free upgrades on every unlocked floor",
  },
  rainbowAlicorn: {
    label: "Rainbow Alicorn",
    color: COLOR.peppermintPink,
    icon: "rainbowAlicorn",
    description: "Nine payouts from the highest-earning floor",
  },
  bogWitchFamiliar: {
    label: "Bog Witch Familiar",
    color: COLOR.dressCodeGreen,
    icon: "bogWitchFamiliar",
    description: "Six free upgrades on this floor",
  },
  pearlHippocampus: {
    label: "Pearl Hippocampus",
    color: COLOR.silverTicketGray,
    icon: "pearlHippocampus",
    description: "Seven instant payouts on this floor",
  },
  thunderbirdChick: {
    label: "Thunderbird Chick",
    color: COLOR.blue,
    icon: "thunderbirdChick",
    description: "Nine free upgrades on this floor",
  },
  obsidianBasilisk: {
    label: "Obsidian Basilisk",
    color: COLOR.fullHouseCrimson,
    icon: "obsidianBasilisk",
    description: "Twenty free upgrades on this floor",
  },
  cloudNymph: {
    label: "Cloud Nymph",
    color: COLOR.winterSaleIceBlue,
    icon: "cloudNymph",
    description: "Five payouts on every unlocked floor",
  },
  alchemyAtDusk: {
    label: "Alchemy at Dusk",
    color: COLOR.purple,
    icon: "alchemyAtDusk",
    description: "Six free upgrades on this floor",
  },
  astropathAlleycat: {
    label: "Astropath Alleycat",
    color: COLOR.nightShiftIndigo,
    icon: "astropathAlleycat",
    description: "Eight payouts on every unlocked floor",
  },
  bardOfTheBrokenLyre: {
    label: "Bard of the Broken Lyre",
    color: COLOR.peppermintPink,
    icon: "bardOfTheBrokenLyre",
    description: "Seven instant payouts on this floor",
  },
  battleStandardBobcat: {
    label: "Battle Standard Bobcat",
    color: COLOR.red,
    icon: "battleStandardBobcat",
    description: "Ten free upgrades on this floor",
  },
  cathedralStarship: {
    label: "Cathedral Starship",
    color: COLOR.blue,
    icon: "cathedralStarship",
    description: "Twelve payouts on every unlocked floor",
  },
  cursedCrownHunt: {
    label: "Cursed Crown Hunt",
    color: COLOR.fullHouseCrimson,
    icon: "cursedCrownHunt",
    description: "Fifteen free upgrades on this floor",
  },
  dreadnoughtWhisker: {
    label: "Dreadnought Whisker",
    color: COLOR.unionBossSlate,
    icon: "dreadnoughtWhisker",
    description: "Twenty free upgrades on this floor",
  },
  elixirUnderMoonlight: {
    label: "Elixir Under Moonlight",
    color: COLOR.silverTicketGray,
    icon: "elixirUnderMoonlight",
    description: "One tier promotion and seven upgrades here",
  },
  frostbiteTracker: {
    label: "Frostbite Tracker",
    color: COLOR.frozenIceBlue,
    icon: "frostbiteTracker",
    description: "Nine payouts from the highest-earning floor",
  },
  ironpawVanguard: {
    label: "Ironpaw Vanguard",
    color: COLOR.gold,
    icon: "ironpawVanguard",
    description: "Eleven free upgrades on every unlocked floor",
  },
  lastStandLionheart: {
    label: "Last Stand Lionheart",
    color: COLOR.red,
    icon: "lastStandLionheart",
    description: "Fourteen free upgrades on this floor",
  },
  meowchineBerserker: {
    label: "Meowchine Berserker",
    color: COLOR.orange,
    icon: "meowchineBerserker",
    description: "Eight free upgrades on this floor",
  },
  meowtallicanGunner: {
    label: "Meowtallican Gunner",
    color: COLOR.silverTicketGray,
    icon: "meowtallicanGunner",
    description: "Ten payouts from the highest-earning floor",
  },
  midnightMonsterContract: {
    label: "Midnight Monster Contract",
    color: COLOR.nightShiftIndigo,
    icon: "midnightMonsterContract",
    description: "Six free upgrades on the lowest-level floor",
  },
  moonlitWyvernHunt: {
    label: "Moonlit Wyvern Hunt",
    color: COLOR.blue,
    icon: "moonlitWyvernHunt",
    description: "Thirteen payouts on this floor",
  },
  orbitalPounce: {
    label: "Orbital Pounce",
    color: COLOR.cyan,
    icon: "orbitalPounce",
    description: "Five free upgrades on every unlocked floor",
  },
  plasmaPurrgeon: {
    label: "Plasma Purrgeon",
    color: COLOR.blue,
    icon: "plasmaPurrgeon",
    description: "Nine free upgrades on this floor",
  },
  relicbladeRonin: {
    label: "Relicblade Ronin",
    color: COLOR.fullHouseCrimson,
    icon: "relicbladeRonin",
    description: "Sixteen free upgrades on this floor",
  },
  seaMonsterSlayer: {
    label: "Sea Monster Slayer",
    color: COLOR.cyan,
    icon: "seaMonsterSlayer",
    description: "Ten instant payouts on this floor",
  },
  silverclawSentinel: {
    label: "Silverclaw Sentinel",
    color: COLOR.silverTicketGray,
    icon: "silverclawSentinel",
    description: "Seven free upgrades on this floor",
  },
  starBastionCaptain: {
    label: "Star Bastion Captain",
    color: COLOR.blue,
    icon: "starBastionCaptain",
    description: "Twelve free upgrades on this floor",
  },
  tavernTactician: {
    label: "Tavern Tactician",
    color: COLOR.autumnSaleAmber,
    icon: "tavernTactician",
    description: "Eight payouts on every unlocked floor",
  },
  theAntlerwoodStalker: {
    label: "The Antlerwood Stalker",
    color: COLOR.moneyGreen,
    icon: "theAntlerwoodStalker",
    description: "One tier promotion and five upgrades here",
  },
  theCataclysmicChaplain: {
    label: "The Cataclysmic Chaplain",
    color: COLOR.fullHouseCrimson,
    icon: "theCataclysmicChaplain",
    description: "Fifteen free upgrades on this floor",
  },
  theGriffinContract: {
    label: "The Griffin Contract",
    color: COLOR.gold,
    icon: "theGriffinContract",
    description: "Nine payouts on the highest-earning floor",
  },
  theSiegeScratcher: {
    label: "The Siege Scratcher",
    color: COLOR.red,
    icon: "theSiegeScratcher",
    description: "Eighteen free upgrades on this floor",
  },
  theWarpwayWatcher: {
    label: "The Warpway Watcher",
    color: COLOR.purple,
    icon: "theWarpwayWatcher",
    description: "Six payouts on every unlocked floor",
  },
  theWhiteWhisker: {
    label: "The White Whisker",
    color: COLOR.white,
    icon: "theWhiteWhisker",
    description: "Ten free upgrades on the highest floor",
  },
  toxinclawInfiltrator: {
    label: "Toxinclaw Infiltrator",
    color: COLOR.dressCodeGreen,
    icon: "toxinclawInfiltrator",
    description: "Seven instant payouts on this floor",
  },
  voidclawVeteran: {
    label: "Voidclaw Veteran",
    color: COLOR.nightShiftIndigo,
    icon: "voidclawVeteran",
    description: "Thirteen free upgrades on this floor",
  },
  voidshieldTemplar: {
    label: "Voidshield Templar",
    color: COLOR.blue,
    icon: "voidshieldTemplar",
    description: "Eight free upgrades on every unlocked floor",
  },
  wolfmarkWanderer: {
    label: "Wolfmark Wanderer",
    color: COLOR.silverTicketGray,
    icon: "wolfmarkWanderer",
    description: "Eleven payouts from the highest-earning floor",
  },
  wolfpackFarewell: {
    label: "Wolfpack Farewell",
    color: COLOR.peppermintPink,
    icon: "wolfpackFarewell",
    description: "Six free upgrades on every unlocked floor",
  },
  bloodlineOmen: {
    label: "Bloodline Omen",
    color: COLOR.fullHouseCrimson,
    icon: "bloodlineOmen",
    description: "Seventeen free upgrades on this floor",
  },
  candleclawCatacomb: {
    label: "Candleclaw Catacomb",
    color: COLOR.nightShiftIndigo,
    icon: "candleclawCatacomb",
    description: "Fourteen instant payouts on this floor",
  },
  emberPawPatrol: {
    label: "Ember Paw Patrol",
    color: COLOR.orange,
    icon: "emberPawPatrol",
    description: "Fourteen free upgrades on every unlocked floor",
  },
  whiskerCoastSurvivor: {
    label: "Whisker Coast Survivor",
    color: COLOR.cyan,
    icon: "whiskerCoastSurvivor",
    description: "Seventeen payouts from the highest-earning floor",
  },
  astapurrion: {
    label: "Astapurrion",
    color: COLOR.fullHouseCrimson,
    icon: "astapurrion",
    description: "Nineteen instant payouts on this floor",
  },
  astralclawSkyblade: {
    label: "Astralclaw Skyblade",
    color: COLOR.red,
    icon: "astralclawSkyblade",
    description: "Twenty-three free upgrades on this floor",
  },
  drizztDoPurrden: {
    label: "Drizzt Do'Purrden",
    color: COLOR.cyan,
    icon: "drizztDoPurrden",
    description: "Nine upgrades on alternating floors",
  },
  elmiaowster: {
    label: "Elmiaowster",
    color: COLOR.royalFlushPurple,
    icon: "elmiaowster",
    description: "Two tier promotions and six upgrades here",
  },
  elvenSongblade: {
    label: "Elven Songblade",
    color: COLOR.pairBlue,
    icon: "elvenSongblade",
    description: "Twenty payouts on every unlocked floor",
  },
  galepaw: {
    label: "Galepaw",
    color: COLOR.purple,
    icon: "galepaw",
    description: "Eleven payouts on every unlocked floor",
  },
  halsinpaw: {
    label: "Halsinpaw",
    color: COLOR.dressCodeGreen,
    icon: "halsinpaw",
    description: "Sixteen free upgrades on every unlocked floor",
  },
  hearthpawShadowagent: {
    label: "Hearthpaw Shadowagent",
    color: COLOR.nightShiftIndigo,
    icon: "hearthpawShadowagent",
    description: "Twenty payouts from the highest-earning floor",
  },
  imeown: {
    label: "Imeown",
    color: COLOR.peppermintPink,
    icon: "imeown",
    description: "Thirteen free upgrades on the lowest-level floor",
  },
  jaheirball: {
    label: "Jaheirball",
    color: COLOR.moneyGreen,
    icon: "jaheirball",
    description: "Fourteen payouts on alternating floors",
  },
  karlachonk: {
    label: "Karlachonk",
    color: COLOR.orange,
    icon: "karlachonk",
    description: "Twenty-one free upgrades on this floor",
  },
  laezclaw: {
    label: "Lae'zclaw",
    color: COLOR.suppliesGiveawayLime,
    icon: "laezclaw",
    description: "Nineteen free upgrades on this floor",
  },
  minscAndMeow: {
    label: "Minsc and Meow",
    color: COLOR.supplyRunTan,
    icon: "minscAndMeow",
    description: "Eighteen free upgrades on every unlocked floor",
  },
  sarevmeowk: {
    label: "Sarevmeowk",
    color: COLOR.gold,
    icon: "sarevmeowk",
    description: "Fifteen upgrades on the highest unlocked floor",
  },
  shadowpurr: {
    label: "Shadowpurr",
    color: COLOR.nightOwlIndigo,
    icon: "shadowpurr",
    description: "One tier promotion and eleven upgrades here",
  },
  theEmpurror: {
    label: "The Empurror",
    color: COLOR.halloweenSalePurple,
    icon: "theEmpurror",
    description: "Thirteen payouts on every unlocked floor",
  },
  thisIsTheEnd: {
    label: "This Is The End",
    color: COLOR.luckyCloverGreen,
    icon: "thisIsTheEnd",
    description: "Twenty-two free upgrades on this floor",
  },
  whiskerWyll: {
    label: "Whisker Wyll",
    color: COLOR.blue,
    icon: "whiskerWyll",
    description: "Nineteen payouts from the highest-earning floor",
  },
  winkWink: {
    label: "Wink Wink",
    color: COLOR.springSalePink,
    icon: "winkWink",
    description: "Fourteen free upgrades on the lowest-level floor",
  },
  adamWhiskersen: {
    label: "Adam Whiskersen",
    color: COLOR.goldStandardAmber,
    icon: "adamWhiskersen",
    description: "Two tier promotions and eight upgrades here",
  },
  bankroll: {
    label: "Bankroll",
    color: COLOR.paydayEmerald,
    icon: "bankroll",
    description: "Twenty-five free upgrades on this floor",
  },
  billBlizzard: {
    label: "Bill Blizzard",
    color: COLOR.shareholdersGreen,
    icon: "billBlizzard",
    description: "Twenty-three payouts on every unlocked floor",
  },
  bobPawge: {
    label: "Bob Pawge",
    color: COLOR.nightShiftIndigo,
    icon: "bobPawge",
    description: "Twenty-four free upgrades on every unlocked floor",
  },
  bullionStack: {
    label: "Bullion Brigade",
    color: COLOR.gold,
    icon: "bullionStack",
    description: "Twenty-four free upgrades on this floor",
  },
  cashCannon: {
    label: "Cash Cannon",
    color: COLOR.bonusRoundGold,
    icon: "cashCannon",
    description: "Ten upgrades on alternating floors",
  },
  fairExchange: {
    label: "Fair Exchange",
    color: COLOR.mergerGold,
    icon: "fairExchange",
    description: "Eighteen payouts on alternating floors",
  },
  gemMine: {
    label: "Gem Mine",
    color: COLOR.pairBlue,
    icon: "gemMine",
    description: "Ten upgrades on this floor and every floor below",
  },
  goldMine: {
    label: "Gold Mine",
    color: COLOR.supplyRunTan,
    icon: "goldMine",
    description: "Fifteen payouts on the highest unlocked floor",
  },
  goldenChalice: {
    label: "Golden Chalice",
    color: COLOR.sunshineGold,
    icon: "goldenChalice",
    description: "Two tier promotions and seven upgrades here",
  },
  goldenGoose: {
    label: "Golden Goose",
    color: COLOR.goldenTicketYellow,
    icon: "goldenGoose",
    description: "Twenty-one payouts on every unlocked floor",
  },
  goldenStag: {
    label: "Golden Stag",
    color: COLOR.heavenlyGold,
    icon: "goldenStag",
    description: "Twenty-two payouts from the highest-earning floor",
  },
  handsomeJake: {
    label: "Handsome Jake",
    color: COLOR.orange,
    icon: "handsomeJake",
    description: "Eighteen upgrades on the highest unlocked floor",
  },
  jcDentclaw: {
    label: "JC Dentclaw",
    color: COLOR.nightOwlIndigo,
    icon: "jcDentclaw",
    description: "Twenty-six free upgrades on this floor",
  },
  liquidAssets: {
    label: "Liquid Assets",
    color: COLOR.goldenHandshakeGold,
    icon: "liquidAssets",
    description: "Twenty-one payouts from the highest-earning floor",
  },
  midasTouch: {
    label: "Midas Touch",
    color: COLOR.goldStandardAmber,
    icon: "midasTouch",
    description: "One tier promotion and thirteen upgrades here",
  },
  moneyPrinter: {
    label: "Money Printer",
    color: COLOR.bullMarketGreen,
    icon: "moneyPrinter",
    description: "Twenty-three free upgrades on every unlocked floor",
  },
  moneyTree: {
    label: "Money Tree",
    color: COLOR.moneyGreen,
    icon: "moneyTree",
    description: "Twenty-two payouts on every unlocked floor",
  },
  nuggetAvalanche: {
    label: "Nugget Avalanche",
    color: COLOR.amber,
    icon: "nuggetAvalanche",
    description: "Seventeen instant payouts on this floor",
  },
  pennyJar: {
    label: "Penny Jar",
    color: COLOR.headhunterRust,
    icon: "pennyJar",
    description: "Fifteen free upgrades on the lowest-level floor",
  },
  purrDenton: {
    label: "Purr Denton",
    color: COLOR.fastForwardBlue,
    icon: "purrDenton",
    description: "Seventeen free upgrades on the lowest-level floor",
  },
  strikeItRich: {
    label: "Strike It Rich",
    color: COLOR.goldenParachuteMarigold,
    icon: "strikeItRich",
    description: "Sixteen upgrades on the highest unlocked floor",
  },
  vaultDoor: {
    label: "Vault Door",
    color: COLOR.unionBossSlate,
    icon: "vaultDoor",
    description: "Twenty-two free upgrades on every unlocked floor",
  },
  wishingWell: {
    label: "Wishing Well",
    color: COLOR.rainCheckBlue,
    icon: "wishingWell",
    description: "Twenty-three instant payouts on this floor",
  },
  youKnowWhatStallion: {
    label: "You Know What, Stallion",
    color: COLOR.royalFlushPurple,
    icon: "youKnowWhatStallion",
    description: "Eleven upgrades on alternating floors",
  },
  annaNyavarre: {
    label: "Anna Nyavarre",
    color: COLOR.red,
    icon: "annaNyavarre",
    description: "Twenty-three payouts from the highest-earning floor",
  },
  batteryCell: {
    label: "Battery Life",
    color: COLOR.internSkyBlue,
    icon: "batteryCell",
    description: "Sixteen free upgrades on the lowest-level floor",
  },
  blackBlade: {
    label: "Black Blade",
    color: COLOR.royalFlushPurple,
    icon: "blackBlade",
    description: "Thirty-one free upgrades on this floor",
  },
  boneFlute: {
    label: "Bone Solo",
    color: COLOR.springCleaningMint,
    icon: "boneFlute",
    description: "Twenty payouts on alternating floors",
  },
  coldSteel: {
    label: "Cold Steel",
    color: COLOR.pairBlue,
    icon: "coldSteel",
    description: "Thirty-three free upgrades on this floor",
  },
  commando: {
    label: "Commando",
    color: COLOR.dressCodeGreen,
    icon: "commando",
    description: "Twenty-seven free upgrades on this floor",
  },
  corvidCrown: {
    label: "Corvid Crown",
    color: COLOR.shareholdersGreen,
    icon: "corvidCrown",
    description: "Two tier promotions and ten upgrades here",
  },
  daedalynx: {
    label: "Daedalynx",
    color: COLOR.cyan,
    icon: "daedalynx",
    description: "Twenty-four payouts on every unlocked floor",
  },
  dataCube: {
    label: "Read The Emails",
    color: COLOR.threeOfAKindGreen,
    icon: "dataCube",
    description: "Twelve upgrades on this floor and every floor below",
  },
  dropTuned: {
    label: "Drop Tuned",
    color: COLOR.supplyRunTan,
    icon: "dropTuned",
    description: "Thirteen upgrades on alternating floors",
  },
  eternalFlame: {
    label: "Eternal Flame",
    color: COLOR.roundUpOrange,
    icon: "eternalFlame",
    description: "Twenty-eight instant payouts on this floor",
  },
  forgeAhead: {
    label: "Forge Ahead",
    color: COLOR.headhunterRust,
    icon: "forgeAhead",
    description: "Thirty free upgrades on every unlocked floor",
  },
  guntherHairman: {
    label: "Gunther Hairman",
    color: COLOR.unionBossSlate,
    icon: "guntherHairman",
    description: "Twenty-eight free upgrades on this floor",
  },
  heliopaws: {
    label: "Heliopaws",
    color: COLOR.gold,
    icon: "heliopaws",
    description: "Twenty-six free upgrades on every unlocked floor",
  },
  hornsUp: {
    label: "Horns Up",
    color: COLOR.espressoShotBrown,
    icon: "hornsUp",
    description: "Twenty-two upgrades on the highest unlocked floor",
  },
  ironKey: {
    label: "Iron Key",
    color: COLOR.supplyRunTan,
    icon: "ironKey",
    description: "Nineteen free upgrades on the lowest-level floor",
  },
  lastCall: {
    label: "Last Call",
    color: COLOR.bonusRoundGold,
    icon: "lastCall",
    description: "Twenty-nine instant payouts on this floor",
  },
  nanoBlade: {
    label: "Wrist Work",
    color: COLOR.goldenHandshakeGold,
    icon: "nanoBlade",
    description: "Twenty-nine free upgrades on this floor",
  },
  peltCloak: {
    label: "Pelt Cloak",
    color: COLOR.teaBreakBrown,
    icon: "peltCloak",
    description: "Fourteen upgrades on alternating floors",
  },
  pigIron: {
    label: "Pig Iron",
    color: COLOR.unionBossSlate,
    icon: "pigIron",
    description: "Thirty-one free upgrades on every unlocked floor",
  },
  praxisKit: {
    label: "Level Up",
    color: COLOR.goldStandardAmber,
    icon: "praxisKit",
    description: "One tier promotion and fourteen upgrades here",
  },
  quickSilver: {
    label: "Quicksilver",
    color: COLOR.silverTicketGray,
    icon: "quickSilver",
    description: "Twenty-one payouts on alternating floors",
  },
  runicAmulet: {
    label: "Runic Amulet",
    color: COLOR.halloweenSalePurple,
    icon: "runicAmulet",
    description: "Two tier promotions and eleven upgrades here",
  },
  scaledGrip: {
    label: "Scaled Grip",
    color: COLOR.redActive,
    icon: "scaledGrip",
    description: "Thirty-two free upgrades on this floor",
  },
  securityTurret: {
    label: "Friendly Fire",
    color: COLOR.luckyCloverGreen,
    icon: "securityTurret",
    description: "Eighteen payouts on the highest unlocked floor",
  },
  shoulderSpikes: {
    label: "Shoulder Spikes",
    color: COLOR.unionBossSlate,
    icon: "shoulderSpikes",
    description: "Twenty-nine free upgrades on every unlocked floor",
  },
  shredMetal: {
    label: "Shred Metal",
    color: COLOR.orange,
    icon: "shredMetal",
    description: "Twenty-one upgrades on the highest unlocked floor",
  },
  signetOfSkulls: {
    label: "Signet of Skulls",
    color: COLOR.silverTicketGray,
    icon: "signetOfSkulls",
    description: "One tier promotion and fifteen upgrades here",
  },
  stormFork: {
    label: "Storm Fork",
    color: COLOR.fastForwardBlue,
    icon: "stormFork",
    description: "Twenty-five payouts on every unlocked floor",
  },
  studdedBelt: {
    label: "Studded Belt",
    color: COLOR.nightOwlIndigo,
    icon: "studdedBelt",
    description: "Eighteen free upgrades on the lowest-level floor",
  },
  swashbuckler: {
    label: "Swashbuckler",
    color: COLOR.autumnSaleAmber,
    icon: "swashbuckler",
    description: "Nineteen payouts on alternating floors",
  },
  tempered: {
    label: "Tempered",
    color: COLOR.silverTicketGray,
    icon: "tempered",
    description: "Twenty-five upgrades on the highest unlocked floor",
  },
  theCure: {
    label: "The Cure",
    color: COLOR.pairBlue,
    icon: "theCure",
    description: "Twenty-seven instant payouts on this floor",
  },
  titaniumGrip: {
    label: "Titanium Grip",
    color: COLOR.fancyFridayIndigo,
    icon: "titaniumGrip",
    description: "Twenty-four payouts from the highest-earning floor",
  },
  wardingSigil: {
    label: "Warding Sigil",
    color: COLOR.fullHouseCrimson,
    icon: "wardingSigil",
    description: "Thirteen upgrades on this floor and every floor below",
  },
  blackHole: {
    label: "Black Hole",
    color: COLOR.royalFlushPurple,
    icon: "blackHole",
    description: "Twenty-six payouts on every unlocked floor",
  },
  bottledNebula: {
    label: "Bottled Nebula",
    color: COLOR.halloweenSalePurple,
    icon: "bottledNebula",
    description: "One tier promotion and sixteen upgrades here",
  },
  eclipse: {
    label: "Eclipse",
    color: COLOR.orange,
    icon: "eclipse",
    description: "Twenty-seven upgrades on the highest unlocked floor",
  },
  treasureMap: {
    label: "Treasure Map",
    color: COLOR.supplyRunTan,
    icon: "treasureMap",
    description: "Twenty-five payouts from the highest-earning floor",
  },
  captainLeFluff: {
    label: "Captain Le Fluff",
    color: COLOR.fullHouseCrimson,
    icon: "captainLeFluff",
    description: "Twenty-eight upgrades on the highest unlocked floor",
  },
  divingBell: {
    label: "Deep Dive",
    color: COLOR.goldenHandshakeGold,
    icon: "divingBell",
    description: "Two free upgrades cascading down from this floor",
  },
  flooringInspector: {
    label: "Flooring Inspector",
    color: COLOR.autumnSaleAmber,
    icon: "flooringInspector",
    description: "Fifteen upgrades on this floor and every floor below",
  },
  kraken: {
    label: "Kraken",
    color: COLOR.royalFlushPurple,
    icon: "kraken",
    description: "Twenty-seven payouts on every unlocked floor",
  },
  lighthouse: {
    label: "Lighthouse",
    color: COLOR.red,
    icon: "lighthouse",
    description: "Twenty-six payouts from the highest-earning floor",
  },
  messageInABottle: {
    label: "Message in a Bottle",
    color: COLOR.threeOfAKindGreen,
    icon: "messageInABottle",
    description: "Twenty free upgrades on the lowest-level floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;

export type FeaturedCritKind = keyof typeof FEATURED_CRIT_INFO;
export const FEATURED_CRIT_KINDS = Object.keys(
  FEATURED_CRIT_INFO,
) as FeaturedCritKind[];

export function featuredCritFlags(
  enabled: ReadonlySet<string> = new Set(),
): Record<FeaturedCritKind, boolean> {
  return Object.fromEntries(
    FEATURED_CRIT_KINDS.map((kind) => [kind, enabled.has(kind)]),
  ) as Record<FeaturedCritKind, boolean>;
}
