import type { CritProcDisplayInfo } from "./index";
import { COLOR } from "../../palette";

export const FEATURED_CRIT_INFO = {
  ballerina: {
    label: "Pirouette",
    color: COLOR.peppermintPink,
    icon: "ballerina",
    description: "Three free upgrades and three payouts on this floor",
  },
  cowboy: {
    label: "Roundup Rodeo",
    color: COLOR.gold,
    icon: "cowboy",
    description: "Eight free upgrades on the lowest-level floor",
  },
  dinnerTime: {
    label: "Dinner Time",
    color: COLOR.moneyGreen,
    icon: "dinnerTime",
    description: "Five instant payouts on every unlocked floor",
  },
  fingerGuns: {
    label: "Finger Guns",
    color: COLOR.blue,
    icon: "fingerGuns",
    description: "Two upgrades here and two on the highest floor",
  },
  flamenco: {
    label: "Flamenco",
    color: COLOR.red,
    icon: "flamenco",
    description: "Seven free upgrades on every unlocked floor",
  },
  milestone: {
    label: "Milestone",
    color: COLOR.cyan,
    icon: "milestone",
    description: "Raises this floor to the next multiple of 25",
  },
  moonwalker: {
    label: "Moonwalk",
    color: COLOR.silverTicketGray,
    icon: "moonwalker",
    description: "Six upgrades on this floor and every floor below",
  },
  ninja: {
    label: "Ninja Bonus",
    color: COLOR.nightShiftIndigo,
    icon: "ninja",
    description: "Twelve free upgrades on this floor",
  },
  obelisk: {
    label: "Obelisk",
    color: COLOR.mysticTeal,
    icon: "obelisk",
    description: "Two tier promotions and two upgrades on this floor",
  },
  sharpShooter: {
    label: "Sharpshooter",
    color: COLOR.starYellow,
    icon: "sharpShooter",
    description: "Ten payouts from the highest-earning floor",
  },
  space: {
    label: "Space Race",
    color: COLOR.orange,
    icon: "space",
    description: "Twenty free upgrades on the highest unlocked floor",
  },
  yesChef: {
    label: "Yes Chef",
    color: COLOR.blue,
    icon: "yesChef",
    description: "Eight instant payouts on every unlocked floor",
  },
  amethyst: {
    label: "Amethyst",
    color: COLOR.purple,
    icon: "amethyst",
    description: "Six instant payouts on this floor",
  },
  blessed: {
    label: "Blessed",
    color: COLOR.heavenlyGold,
    icon: "blessed",
    description: "One tier promotion and three upgrades here",
  },
  centurion: {
    label: "Centurion",
    color: COLOR.red,
    icon: "centurion",
    description: "One hundred free upgrades on this floor",
  },
  checkUp: {
    label: "Check Up",
    color: COLOR.cyan,
    icon: "checkUp",
    description: "Four upgrades and two payouts on the lowest-level floor",
  },
  diamond: {
    label: "Diamond",
    color: COLOR.cyan,
    icon: "diamond",
    description: "Twenty-four instant payouts on this floor",
  },
  emerald: {
    label: "Emerald",
    color: COLOR.moneyGreen,
    icon: "emerald",
    description: "Nine instant payouts on this floor",
  },
  fireman: {
    label: "First Responder",
    color: COLOR.orange,
    icon: "fireman",
    description: "Three upgrades, then one payout on every floor",
  },
  forTheEmperor: {
    label: "For the Emperor",
    color: COLOR.blue,
    icon: "forTheEmperor",
    description: "Twenty-five upgrades on every unlocked floor",
  },
  forTheKing: {
    label: "For the King",
    color: COLOR.starYellow,
    icon: "forTheKing",
    description: "Fifteen upgrades on every unlocked floor",
  },
  goldNugget: {
    label: "Gold Nugget",
    color: COLOR.gold,
    icon: "goldNugget",
    description: "Four instant payouts on this floor",
  },
  goldRush: {
    label: "Gold Rush",
    color: COLOR.gold,
    icon: "goldRush",
    description: "Ten instant payouts on every unlocked floor",
  },
  hammerTime: {
    label: "Hammer Time",
    color: COLOR.red,
    icon: "hammerTime",
    description: "Nine free upgrades on this floor",
  },
  robinHood: {
    label: "Robin Hood",
    color: COLOR.moneyGreen,
    icon: "robinHood",
    description: "Seven top-earner payouts; three lowest-level upgrades",
  },
  roman: {
    label: "Roman Holiday",
    color: COLOR.fullHouseCrimson,
    icon: "roman",
    description: "Nine upgrades on every unlocked floor",
  },
  ruby: {
    label: "Ruby",
    color: COLOR.red,
    icon: "ruby",
    description: "Twelve instant payouts on this floor",
  },
  samurai: {
    label: "Samurai",
    color: COLOR.fullHouseCrimson,
    icon: "samurai",
    description: "Thirty free upgrades on this floor",
  },
  saphire: {
    label: "Sapphire",
    color: COLOR.blue,
    icon: "saphire",
    description: "Eighteen instant payouts on this floor",
  },
  silverRush: {
    label: "Silver Rush",
    color: COLOR.silverTicketGray,
    icon: "silverRush",
    description: "Six instant payouts on every unlocked floor",
  },
  spy: {
    label: "Undercover",
    color: COLOR.nightShiftIndigo,
    icon: "spy",
    description: "Seventeen upgrades on the lowest-earning floor",
  },
  theLawWon: {
    label: "The Law Won",
    color: COLOR.blue,
    icon: "theLawWon",
    description: "Six upgrades and two payouts on the cheapest floor",
  },
  victorian: {
    label: "High Society",
    color: COLOR.gold,
    icon: "victorian",
    description: "Nine payouts on alternating floors, from the ground",
  },
  executiveSpin: {
    label: "Executive Spin",
    color: COLOR.orange,
    icon: "executiveSpin",
    description: "Four free upgrades on the highest floor",
  },
  rubberStampede: {
    label: "Rubber Stampede",
    color: COLOR.red,
    icon: "rubberStampede",
    description: "Seven instant payouts on every unlocked floor",
  },
  replyAll: {
    label: "Reply All",
    color: COLOR.blue,
    icon: "replyAll",
    description: "Three payouts on this floor and the lowest-level floor",
  },
  stapleOfSuccess: {
    label: "Staple of Success",
    color: COLOR.silverTicketGray,
    icon: "stapleOfSuccess",
    description: "Seven free upgrades on this floor",
  },
  faxOfFortune: {
    label: "Fax of Fortune",
    color: COLOR.moneyGreen,
    icon: "faxOfFortune",
    description: "Eight payouts from the highest-earning floor",
  },
  casualMonday: {
    label: "Casual Monday",
    color: COLOR.peppermintPink,
    icon: "casualMonday",
    description: "Twenty free upgrades on this floor",
  },
  deskJockey: {
    label: "Desk Jockey",
    color: COLOR.nightShiftIndigo,
    icon: "deskJockey",
    description: "Six free upgrades on the lowest-level floor",
  },
  inboxZeroGravity: {
    label: "Inbox Zero Gravity",
    color: COLOR.cyan,
    icon: "inboxZeroGravity",
    description: "Twelve instant payouts on every unlocked floor",
  },
  beanCounter: {
    label: "Bean Counter",
    color: COLOR.heavenlyGold,
    icon: "beanCounter",
    description: "One tier promotion and six upgrades here",
  },
  kingOfTheWorld: {
    label: "King of the World",
    color: COLOR.gold,
    icon: "kingOfTheWorld",
    description: "Thirty free upgrades on the highest floor",
  },
  officeClown: {
    label: "Office Clown",
    color: COLOR.red,
    icon: "officeClown",
    description: "Five free upgrades on the lowest-level floor",
  },
  fridayTieDay: {
    label: "Friday Tie Day",
    color: COLOR.blue,
    icon: "fridayTieDay",
    description: "Ten payouts on alternating floors, from the ground",
  },
  soReady: {
    label: "So Ready",
    color: COLOR.cyan,
    icon: "soReady",
    description: "Fifteen free upgrades on this floor",
  },
  doughDivision: {
    label: "Dough Division",
    color: COLOR.gold,
    icon: "doughDivision",
    description: "Six free upgrades on this floor",
  },
  profitPopcorn: {
    label: "Profit Popcorn",
    color: COLOR.heavenlyGold,
    icon: "profitPopcorn",
    description: "Four instant payouts on every unlocked floor",
  },
  donutDisturb: {
    label: "Donut Disturb",
    color: COLOR.peppermintPink,
    icon: "donutDisturb",
    description: "Five upgrades and five payouts on this floor",
  },
  cakeDay: {
    label: "Cake Day",
    color: COLOR.red,
    icon: "cakeDay",
    description: "Twelve upgrades on the lowest-level floor",
  },
  champagneProblems: {
    label: "Champagne Problems",
    color: COLOR.starYellow,
    icon: "champagneProblems",
    description: "Fifteen payouts from the highest-earning floor",
  },
  bonusBurrito: {
    label: "Bonus Burrito",
    color: COLOR.orange,
    icon: "bonusBurrito",
    description: "Eight upgrades and three payouts on this floor",
  },
  sundaeBest: {
    label: "Sundae Best",
    color: COLOR.blue,
    icon: "sundaeBest",
    description: "Ten payouts on alternating floors, from the ground",
  },
  popTheQuestion: {
    label: "Pop the Question",
    color: COLOR.cyan,
    icon: "popTheQuestion",
    description: "One tier promotion and four upgrades here",
  },
  partyCrasher: {
    label: "Party Crasher",
    color: COLOR.red,
    icon: "partyCrasher",
    description: "Three upgrades here and three on the highest floor",
  },
  wizard: {
    label: "Wizard",
    color: COLOR.purple,
    icon: "wizard",
    description: "Two tier promotions and five upgrades here",
  },
  epic: {
    label: "Epic Loot",
    color: COLOR.royalFlushPurple,
    icon: "epic",
    description: "Forty free upgrades on this floor",
  },
  ready: {
    label: "Dual Wield",
    color: COLOR.fourOfAKindIndigo,
    icon: "ready",
    description: "Four upgrades and four payouts on the top earner",
  },
  workWork: {
    label: "Work Work",
    color: COLOR.suppliesGiveawayLime,
    icon: "workWork",
    description: "Eleven free upgrades on every unlocked floor",
  },
  yesWarchief: {
    label: "Yes, Warchief",
    color: COLOR.doubleDownCrimson,
    icon: "yesWarchief",
    description: "Fourteen instant payouts on every unlocked floor",
  },
  youAreNotPrepared: {
    label: "Not Prepared",
    color: COLOR.threeOfAKindGreen,
    icon: "youAreNotPrepared",
    description: "Two tier promotions and nine upgrades here",
  },
  arcana: {
    label: "Arcane Surge",
    color: COLOR.pairBlue,
    icon: "arcana",
    description: "One tier promotion and twelve upgrades here",
  },
  bigDaddy: {
    label: "Big Daddy",
    color: COLOR.mysticTeal,
    icon: "bigDaddy",
    description: "Forty-five free upgrades on this floor",
  },
  chonk: {
    label: "Chonk",
    color: COLOR.suppliesGiveawayLime,
    icon: "chonk",
    description: "Sixteen instant payouts on this floor",
  },
  cyberPunk: {
    label: "Cyberpunk",
    color: COLOR.cyan,
    icon: "cyberPunk",
    description: "Thirteen free upgrades on this floor",
  },
  dodgeThis: {
    label: "Dodge This",
    color: COLOR.unionBossSlate,
    icon: "dodgeThis",
    description: "Six payouts from the highest-earning floor",
  },
  whiteRabbit: {
    label: "White Rabbit",
    color: COLOR.silverTicketGray,
    icon: "whiteRabbit",
    description: "Five upgrades here and five on the lowest-level floor",
  },
  gladiator: {
    label: "Gladiator",
    color: COLOR.goldenHandshakeGold,
    icon: "gladiator",
    description: "Thirteen free upgrades on every unlocked floor",
  },
  iDidntAskForThis: {
    label: "I Didn't Ask For This",
    color: COLOR.rainCheckBlue,
    icon: "iDidntAskForThis",
    description: "One tier promotion and twenty upgrades here",
  },
  iHatePortals: {
    label: "I Hate Portals",
    color: COLOR.snowdayFrost,
    icon: "iHatePortals",
    description: "Eleven instant payouts on this floor",
  },
  littleSister: {
    label: "Little Sister",
    color: COLOR.easterSalePink,
    icon: "littleSister",
    description: "Seven free upgrades on the lowest-level floor",
  },
  magicIsATool: {
    label: "Magic Is a Tool",
    color: COLOR.halloweenSalePurple,
    icon: "magicIsATool",
    description: "Eight upgrades on alternating floors, from the ground",
  },
  megaChonk: {
    label: "Mega Chonk",
    color: COLOR.fullHouseCrimson,
    icon: "megaChonk",
    description: "Twenty-two instant payouts on this floor",
  },
  metal: {
    label: "Heavy Metal",
    color: COLOR.goldStandardAmber,
    icon: "metal",
    description: "Seventeen free upgrades on the highest floor",
  },
  princess: {
    label: "Princess Cut",
    color: COLOR.springSalePink,
    icon: "princess",
    description: "Thirteen payouts on alternating floors, from the ground",
  },
  spaceAndTime: {
    label: "Space and Time",
    color: COLOR.nightShiftIndigo,
    icon: "spaceAndTime",
    description: "Nine upgrades on this floor and every floor below",
  },
  thinkWithYourHead: {
    label: "Think With Your Head",
    color: COLOR.executiveOrderTeal,
    icon: "thinkWithYourHead",
    description: "Five upgrades and five payouts on the lowest-level floor",
  },
  wouldYouKindly: {
    label: "Would You Kindly",
    color: COLOR.espressoShotBrown,
    icon: "wouldYouKindly",
    description: "Sixteen instant payouts on every unlocked floor",
  },
  yesYourHighness: {
    label: "Yes, Your Highness",
    color: COLOR.heavenlyGold,
    icon: "yesYourHighness",
    description: "Nineteen free upgrades on every unlocked floor",
  },
  bulletDodger: {
    label: "Bullet Dodger",
    color: COLOR.pairBlue,
    icon: "bulletDodger",
    description: "Fourteen free upgrades on this floor",
  },
  nothingToSee: {
    label: "Nothing to See",
    color: COLOR.bullMarketGreen,
    icon: "nothingToSee",
    description: "Twenty instant payouts on this floor",
  },
  nowIAmSuspicious: {
    label: "Now I'm Suspicious",
    color: COLOR.nightOwlIndigo,
    icon: "nowIAmSuspicious",
    description: "Seventeen instant payouts on every unlocked floor",
  },
  redOrBlue: {
    label: "Red or Blue",
    color: COLOR.grandOpeningRose,
    icon: "redOrBlue",
    description: "Six upgrades on the lowest floor; six top-earner payouts",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;

export type FeaturedCritKind = keyof typeof FEATURED_CRIT_INFO;
export const FEATURED_CRIT_KINDS = Object.keys(
  FEATURED_CRIT_INFO,
) as FeaturedCritKind[];

export function featuredCritFlags(
  enabled: ReadonlySet<string> = new Set(),
): Record<FeaturedCritKind, boolean> {
  return Object.fromEntries(
    FEATURED_CRIT_KINDS.map((kind) => [kind, enabled.has(kind)]),
  ) as Record<FeaturedCritKind, boolean>;
}
