import type { CritProcDisplayInfo } from "./index";
import { COLOR } from "../../palette";

export const FEATURED_CRIT_INFO = {
  ballerina: {
    label: "Pirouette",
    color: COLOR.peppermintPink,
    icon: "ballerina",
    description: "Three free upgrades and three payouts on this floor",
  },
  cowboy: {
    label: "Roundup Rodeo",
    color: COLOR.gold,
    icon: "cowboy",
    description: "Eight free upgrades on the lowest-level floor",
  },
  dinnerTime: {
    label: "Dinner Time",
    color: COLOR.moneyGreen,
    icon: "dinnerTime",
    description: "Five instant payouts on every unlocked floor",
  },
  fingerGuns: {
    label: "Finger Guns",
    color: COLOR.blue,
    icon: "fingerGuns",
    description: "Two upgrades here and two on the highest floor",
  },
  flamenco: {
    label: "Flamenco",
    color: COLOR.red,
    icon: "flamenco",
    description: "Seven free upgrades on every unlocked floor",
  },
  milestone: {
    label: "Milestone",
    color: COLOR.cyan,
    icon: "milestone",
    description: "Raises this floor to the next multiple of 25",
  },
  moonwalker: {
    label: "Moonwalk",
    color: COLOR.silverTicketGray,
    icon: "moonwalker",
    description: "Six upgrades on this floor and every floor below",
  },
  ninja: {
    label: "Ninja Bonus",
    color: COLOR.nightShiftIndigo,
    icon: "ninja",
    description: "Twelve free upgrades on this floor",
  },
  obelisk: {
    label: "Obelisk",
    color: COLOR.mysticTeal,
    icon: "obelisk",
    description: "Two tier promotions and two upgrades on this floor",
  },
  sharpShooter: {
    label: "Sharpshooter",
    color: COLOR.starYellow,
    icon: "sharpShooter",
    description: "Ten payouts from the highest-earning floor",
  },
  space: {
    label: "Space Race",
    color: COLOR.orange,
    icon: "space",
    description: "Twenty free upgrades on the highest unlocked floor",
  },
  yesChef: {
    label: "Yes, Chef",
    color: COLOR.blue,
    icon: "yesChef",
    description: "Eight instant payouts on every unlocked floor",
  },
  amethyst: {
    label: "Amethyst",
    color: COLOR.purple,
    icon: "amethyst",
    description: "Six instant payouts on this floor",
  },
  blessed: {
    label: "Blessed",
    color: COLOR.heavenlyGold,
    icon: "blessed",
    description: "One tier promotion and three upgrades here",
  },
  centurion: {
    label: "Centurion",
    color: COLOR.red,
    icon: "centurion",
    description: "One hundred free upgrades on this floor",
  },
  checkUp: {
    label: "Check Up",
    color: COLOR.cyan,
    icon: "checkUp",
    description: "Four upgrades and two payouts on the lowest-level floor",
  },
  diamond: {
    label: "Diamond",
    color: COLOR.cyan,
    icon: "diamond",
    description: "Twenty-four instant payouts on this floor",
  },
  emerald: {
    label: "Emerald",
    color: COLOR.moneyGreen,
    icon: "emerald",
    description: "Nine instant payouts on this floor",
  },
  fireman: {
    label: "First Responder",
    color: COLOR.orange,
    icon: "fireman",
    description: "Three upgrades, then one payout on every floor",
  },
  forTheEmperor: {
    label: "For the Emperor",
    color: COLOR.blue,
    icon: "forTheEmperor",
    description: "Twenty-five upgrades on every unlocked floor",
  },
  forTheKing: {
    label: "For the King",
    color: COLOR.starYellow,
    icon: "forTheKing",
    description: "Fifteen upgrades on every unlocked floor",
  },
  goldNugget: {
    label: "Gold Nugget",
    color: COLOR.gold,
    icon: "goldNugget",
    description: "Four instant payouts on this floor",
  },
  goldRush: {
    label: "Gold Rush",
    color: COLOR.gold,
    icon: "goldRush",
    description: "Ten instant payouts on every unlocked floor",
  },
  hammerTime: {
    label: "Hammer Time",
    color: COLOR.red,
    icon: "hammerTime",
    description: "Nine free upgrades on this floor",
  },
  robinHood: {
    label: "Honor among thieves",
    color: COLOR.moneyGreen,
    icon: "robinHood",
    description: "Seven top-earner payouts; three lowest-level upgrades",
  },
  roman: {
    label: "Roman Holiday",
    color: COLOR.fullHouseCrimson,
    icon: "roman",
    description: "Nine upgrades on every unlocked floor",
  },
  ruby: {
    label: "Ruby",
    color: COLOR.red,
    icon: "ruby",
    description: "Twelve instant payouts on this floor",
  },
  samurai: {
    label: "Samurai",
    color: COLOR.fullHouseCrimson,
    icon: "samurai",
    description: "Thirty free upgrades on this floor",
  },
  saphire: {
    label: "Sapphire",
    color: COLOR.blue,
    icon: "saphire",
    description: "Eighteen instant payouts on this floor",
  },
  silverRush: {
    label: "Silver Rush",
    color: COLOR.silverTicketGray,
    icon: "silverRush",
    description: "Six instant payouts on every unlocked floor",
  },
  spy: {
    label: "Undercover",
    color: COLOR.nightShiftIndigo,
    icon: "spy",
    description: "Seventeen upgrades on the lowest-earning floor",
  },
  theLawWon: {
    label: "The Law Won",
    color: COLOR.blue,
    icon: "theLawWon",
    description: "Six upgrades and two payouts on the cheapest floor",
  },
  victorian: {
    label: "High Society",
    color: COLOR.gold,
    icon: "victorian",
    description: "Nine payouts on alternating floors, from the ground",
  },
  executiveSpin: {
    label: "Executive Spin",
    color: COLOR.orange,
    icon: "executiveSpin",
    description: "Four free upgrades on the highest floor",
  },
  rubberStampede: {
    label: "Rubber Stampede",
    color: COLOR.red,
    icon: "rubberStampede",
    description: "Seven instant payouts on every unlocked floor",
  },
  replyAll: {
    label: "Reply All",
    color: COLOR.blue,
    icon: "replyAll",
    description: "Three payouts on this floor and the lowest-level floor",
  },
  stapleOfSuccess: {
    label: "Staple of Success",
    color: COLOR.silverTicketGray,
    icon: "stapleOfSuccess",
    description: "Seven free upgrades on this floor",
  },
  faxOfFortune: {
    label: "Fax of Fortune",
    color: COLOR.moneyGreen,
    icon: "faxOfFortune",
    description: "Eight payouts from the highest-earning floor",
  },
  casualMonday: {
    label: "Casual Monday",
    color: COLOR.peppermintPink,
    icon: "casualMonday",
    description: "Twenty free upgrades on this floor",
  },
  deskJockey: {
    label: "Desk Jockey",
    color: COLOR.nightShiftIndigo,
    icon: "deskJockey",
    description: "Six free upgrades on the lowest-level floor",
  },
  inboxZeroGravity: {
    label: "Inbox Zero Gravity",
    color: COLOR.cyan,
    icon: "inboxZeroGravity",
    description: "Twelve instant payouts on every unlocked floor",
  },
  beanCounter: {
    label: "Bean Counter",
    color: COLOR.heavenlyGold,
    icon: "beanCounter",
    description: "One tier promotion and six upgrades here",
  },
  kingOfTheWorld: {
    label: "King of the World",
    color: COLOR.gold,
    icon: "kingOfTheWorld",
    description: "Thirty free upgrades on the highest floor",
  },
  officeClown: {
    label: "Office Clown",
    color: COLOR.red,
    icon: "officeClown",
    description: "Five free upgrades on the lowest-level floor",
  },
  fridayTieDay: {
    label: "Friday Tie Day",
    color: COLOR.blue,
    icon: "fridayTieDay",
    description: "Ten payouts on alternating floors, from the ground",
  },
  soReady: {
    label: "So Ready",
    color: COLOR.cyan,
    icon: "soReady",
    description: "Fifteen free upgrades on this floor",
  },
  doughDivision: {
    label: "Dough Division",
    color: COLOR.gold,
    icon: "doughDivision",
    description: "Six free upgrades on this floor",
  },
  profitPopcorn: {
    label: "Profit Popcorn",
    color: COLOR.heavenlyGold,
    icon: "profitPopcorn",
    description: "Four instant payouts on every unlocked floor",
  },
  donutDisturb: {
    label: "Donut Disturb",
    color: COLOR.peppermintPink,
    icon: "donutDisturb",
    description: "Five upgrades and five payouts on this floor",
  },
  cakeDay: {
    label: "Cake Day",
    color: COLOR.red,
    icon: "cakeDay",
    description: "Twelve upgrades on the lowest-level floor",
  },
  champagneProblems: {
    label: "Champagne Problems",
    color: COLOR.starYellow,
    icon: "champagneProblems",
    description: "Fifteen payouts from the highest-earning floor",
  },
  bonusBurrito: {
    label: "Bonus Burrito",
    color: COLOR.orange,
    icon: "bonusBurrito",
    description: "Eight upgrades and three payouts on this floor",
  },
  sundaeBest: {
    label: "Sundae Best",
    color: COLOR.blue,
    icon: "sundaeBest",
    description: "Ten payouts on alternating floors, from the ground",
  },
  popTheQuestion: {
    label: "Pop the Question",
    color: COLOR.cyan,
    icon: "popTheQuestion",
    description: "One tier promotion and four upgrades here",
  },
  partyCrasher: {
    label: "Party Crasher",
    color: COLOR.red,
    icon: "partyCrasher",
    description: "Three upgrades here and three on the highest floor",
  },
  wizard: {
    label: "Wizard",
    color: COLOR.purple,
    icon: "wizard",
    description: "Two tier promotions and five upgrades here",
  },
  epic: {
    label: "Epic Loot",
    color: COLOR.royalFlushPurple,
    icon: "epic",
    description: "Forty free upgrades on this floor",
  },
  ready: {
    label: "Dual Wield",
    color: COLOR.fourOfAKindIndigo,
    icon: "ready",
    description: "Four upgrades and four payouts on the top earner",
  },
  workWork: {
    label: "Work Work",
    color: COLOR.suppliesGiveawayLime,
    icon: "workWork",
    description: "Eleven free upgrades on every unlocked floor",
  },
  yesWarchief: {
    label: "Yes, Warchief",
    color: COLOR.doubleDownCrimson,
    icon: "yesWarchief",
    description: "Fourteen instant payouts on every unlocked floor",
  },
  youAreNotPrepared: {
    label: "Not Prepared",
    color: COLOR.threeOfAKindGreen,
    icon: "youAreNotPrepared",
    description: "Two tier promotions and nine upgrades here",
  },
  arcana: {
    label: "Arcane Surge",
    color: COLOR.pairBlue,
    icon: "arcana",
    description: "One tier promotion and twelve upgrades here",
  },
  bigDaddy: {
    label: "Big Daddy",
    color: COLOR.mysticTeal,
    icon: "bigDaddy",
    description: "Forty-five free upgrades on this floor",
  },
  chonk: {
    label: "Chonk",
    color: COLOR.suppliesGiveawayLime,
    icon: "chonk",
    description: "Sixteen instant payouts on this floor",
  },
  cyberPunk: {
    label: "Cyberpunk",
    color: COLOR.cyan,
    icon: "cyberPunk",
    description: "Thirteen free upgrades on this floor",
  },
  dodgeThis: {
    label: "Dodge This",
    color: COLOR.unionBossSlate,
    icon: "dodgeThis",
    description: "Six payouts from the highest-earning floor",
  },
  whiteRabbit: {
    label: "White Rabbit",
    color: COLOR.silverTicketGray,
    icon: "whiteRabbit",
    description: "Five upgrades here and five on the lowest-level floor",
  },
  gladiator: {
    label: "Gladiator",
    color: COLOR.goldenHandshakeGold,
    icon: "gladiator",
    description: "Thirteen free upgrades on every unlocked floor",
  },
  iDidntAskForThis: {
    label: "I Didn't Ask For This",
    color: COLOR.rainCheckBlue,
    icon: "iDidntAskForThis",
    description: "One tier promotion and twenty upgrades here",
  },
  iHatePortals: {
    label: "I Hate Portals",
    color: COLOR.snowdayFrost,
    icon: "iHatePortals",
    description: "Eleven instant payouts on this floor",
  },
  littleSister: {
    label: "Little Sister",
    color: COLOR.easterSalePink,
    icon: "littleSister",
    description: "Seven free upgrades on the lowest-level floor",
  },
  magicIsATool: {
    label: "Magic Is a Tool",
    color: COLOR.halloweenSalePurple,
    icon: "magicIsATool",
    description: "Eight upgrades on alternating floors, from the ground",
  },
  megaChonk: {
    label: "Mega Chonk",
    color: COLOR.fullHouseCrimson,
    icon: "megaChonk",
    description: "Twenty-two instant payouts on this floor",
  },
  metal: {
    label: "Heavy Metal",
    color: COLOR.goldStandardAmber,
    icon: "metal",
    description: "Seventeen free upgrades on the highest floor",
  },
  princess: {
    label: "Princess Cut",
    color: COLOR.springSalePink,
    icon: "princess",
    description: "Thirteen payouts on alternating floors, from the ground",
  },
  spaceAndTime: {
    label: "Space and Time",
    color: COLOR.nightShiftIndigo,
    icon: "spaceAndTime",
    description: "Nine upgrades on this floor and every floor below",
  },
  thinkWithYourHead: {
    label: "Think With Your Head",
    color: COLOR.executiveOrderTeal,
    icon: "thinkWithYourHead",
    description: "Five upgrades and five payouts on the lowest-level floor",
  },
  wouldYouKindly: {
    label: "Would You Kindly",
    color: COLOR.espressoShotBrown,
    icon: "wouldYouKindly",
    description: "Sixteen instant payouts on every unlocked floor",
  },
  yesYourHighness: {
    label: "Yes, Your Highness",
    color: COLOR.heavenlyGold,
    icon: "yesYourHighness",
    description: "Nineteen free upgrades on every unlocked floor",
  },
  bulletDodger: {
    label: "Bullet Dodger",
    color: COLOR.pairBlue,
    icon: "bulletDodger",
    description: "Fourteen free upgrades on this floor",
  },
  nothingToSee: {
    label: "Nothing to See",
    color: COLOR.bullMarketGreen,
    icon: "nothingToSee",
    description: "Twenty instant payouts on this floor",
  },
  nowIAmSuspicious: {
    label: "Now I'm Suspicious",
    color: COLOR.nightOwlIndigo,
    icon: "nowIAmSuspicious",
    description: "Seventeen instant payouts on every unlocked floor",
  },
  redOrBlue: {
    label: "Red or Blue",
    color: COLOR.grandOpeningRose,
    icon: "redOrBlue",
    description: "Six upgrades on the lowest floor; six top-earner payouts",
  },
  abraCashDabra: {
    label: "Abra-Cash-Dabra",
    color: COLOR.moneyGreen,
    icon: "abraCashDabra",
    description: "Twenty-five instant payouts on this floor",
  },
  captainOfIndustry: {
    label: "Captain of Industry",
    color: COLOR.fastForwardBlue,
    icon: "captainOfIndustry",
    description: "Twenty-one free upgrades on every unlocked floor",
  },
  clowningAround: {
    label: "Clowning Around",
    color: COLOR.summerSaleOrange,
    icon: "clowningAround",
    description: "Three upgrades and three payouts on every floor",
  },
  discoDividend: {
    label: "Disco Dividend",
    color: COLOR.silverTicketGray,
    icon: "discoDividend",
    description: "Eleven payouts on alternating floors, from the ground",
  },
  mimeYourBusiness: {
    label: "Mime Your Business",
    color: COLOR.winterSaleIceBlue,
    icon: "mimeYourBusiness",
    description: "Eight upgrades on this floor and every floor below",
  },
  redCarpetTreatment: {
    label: "Red Carpet Treatment",
    color: COLOR.fullHouseCrimson,
    icon: "redCarpetTreatment",
    description: "Twelve payouts from the highest-earning floor",
  },
  rockTheStock: {
    label: "Rock the Stock",
    color: COLOR.peppermintPink,
    icon: "rockTheStock",
    description: "Sixteen free upgrades on this floor",
  },
  strongReturn: {
    label: "Strong Return",
    color: COLOR.goldenHandshakeGold,
    icon: "strongReturn",
    description: "Twenty-six free upgrades on the highest floor",
  },
  theBigCheese: {
    label: "The Big Cheese",
    color: COLOR.sunshineGold,
    icon: "theBigCheese",
    description: "Two tier promotions and thirty upgrades here",
  },
  queenOfQueens: {
    label: "Queen of Queens",
    color: COLOR.royalFlushPurple,
    icon: "queenOfQueens",
    description: "Twenty-eight free upgrades on every unlocked floor",
  },
  bubbleEconomy: {
    label: "Bubble Economy",
    color: COLOR.snowballBlue,
    icon: "bubbleEconomy",
    description: "Seven instant payouts on this floor",
  },
  cloudNineToFive: {
    label: "Cloud Nine to Five",
    color: COLOR.floorShareBlue,
    icon: "cloudNineToFive",
    description: "Nine instant payouts on every unlocked floor",
  },
  luckyLaundromat: {
    label: "Lucky Laundromat",
    color: COLOR.luckyCloverGreen,
    icon: "luckyLaundromat",
    description: "Five upgrades and five payouts on every floor",
  },
  moneyMagnet: {
    label: "Money Magnet",
    color: COLOR.red,
    icon: "moneyMagnet",
    description: "Fourteen payouts from the highest-earning floor",
  },
  overTheRainbow: {
    label: "Over the Rainbow",
    color: COLOR.purple,
    icon: "overTheRainbow",
    description: "Fifteen payouts on alternating floors, from the ground",
  },
  pocketDimension: {
    label: "Pocket Dimension",
    color: COLOR.fourOfAKindIndigo,
    icon: "pocketDimension",
    description: "Eighteen upgrades on this floor and every floor below",
  },
  shootingStarEmployee: {
    label: "Shooting Star",
    color: COLOR.starYellow,
    icon: "shootingStarEmployee",
    description: "Twenty-three free upgrades on the highest floor",
  },
  treasureMeasure: {
    label: "Treasure Measure",
    color: COLOR.supplyRunTan,
    icon: "treasureMeasure",
    description: "Ten free upgrades on the lowest-level floor",
  },
  wishfulBanking: {
    label: "Wishful Banking",
    color: COLOR.goldenTicketYellow,
    icon: "wishfulBanking",
    description: "Two tier promotions and twelve upgrades here",
  },
  backToTheFiscal: {
    label: "Back to the Fiscal",
    color: COLOR.blue,
    icon: "backToTheFiscal",
    description: "Eleven free upgrades on this floor",
  },
  despicableFees: {
    label: "Despicable Fees",
    color: COLOR.amber,
    icon: "despicableFees",
    description: "Thirty instant payouts on this floor",
  },
  howToTrainYourManager: {
    label: "Train Your Manager",
    color: COLOR.teal,
    icon: "howToTrainYourManager",
    description: "Four upgrades and six payouts on this floor",
  },
  jurassicPerk: {
    label: "Jurassic Perk",
    color: COLOR.dressCodeGreen,
    icon: "jurassicPerk",
    description: "Thirteen instant payouts on this floor",
  },
  raidersOfTheLostReceipt: {
    label: "Lost Receipt",
    color: COLOR.chairGiveawayBrown,
    icon: "raidersOfTheLostReceipt",
    description: "Nine free upgrades on the lowest-level floor",
  },
  theDevilWearsPawda: {
    label: "The Devil Wears Pawda",
    color: COLOR.fancyFridayIndigo,
    icon: "theDevilWearsPawda",
    description: "Fourteen upgrades on the cheapest floor",
  },
  theExpenseMatrix: {
    label: "The Expense Matrix",
    color: COLOR.payoutOlive,
    icon: "theExpenseMatrix",
    description: "Eighteen instant payouts on every unlocked floor",
  },
  theFastAndTheFurriest: {
    label: "The Fast and the Furriest",
    color: COLOR.roundUpOrange,
    icon: "theFastAndTheFurriest",
    description: "Twelve upgrades on alternating floors, from the ground",
  },
  theFellowshipOfTheBling: {
    label: "Fellowship of the Bling",
    color: COLOR.mergerGold,
    icon: "theFellowshipOfTheBling",
    description: "Six upgrades and six payouts on every floor",
  },
  theGreatCatsby: {
    label: "The Great Catsby",
    color: COLOR.coinGold,
    icon: "theGreatCatsby",
    description: "One tier promotion and thirty upgrades here",
  },
  theLordOfTheRingBinders: {
    label: "The Ring Binders",
    color: COLOR.goldenParachuteMarigold,
    icon: "theLordOfTheRingBinders",
    description: "Thirty-five free upgrades on this floor",
  },
  breakEven: {
    label: "Break Even",
    color: COLOR.performanceBonusBlue,
    icon: "breakEven",
    description: "Eight free upgrades on this floor",
  },
  chaChaChing: {
    label: "Cha-Cha-Ching",
    color: COLOR.amberMuted,
    icon: "chaChaChing",
    description: "Eight instant payouts on this floor",
  },
  charlestonCharge: {
    label: "Charleston Charge",
    color: COLOR.teaBreakBrown,
    icon: "charlestonCharge",
    description: "Eleven free upgrades on the lowest-level floor",
  },
  congaCompounding: {
    label: "Conga Compounding",
    color: COLOR.springSalePink,
    icon: "congaCompounding",
    description: "Four upgrades and four payouts on every floor",
  },
  robotResources: {
    label: "Robot Resources",
    color: COLOR.headhunterRust,
    icon: "robotResources",
    description: "Nineteen free upgrades on the highest floor",
  },
  rumbaReturns: {
    label: "Rumba Returns",
    color: COLOR.redActive,
    icon: "rumbaReturns",
    description: "Twenty-one instant payouts on this floor",
  },
  salsaSalary: {
    label: "Salsa Salary",
    color: COLOR.peppermintPink,
    icon: "salsaSalary",
    description: "Thirteen payouts from the highest-earning floor",
  },
  shuffleTheFunds: {
    label: "Shuffle the Funds",
    color: COLOR.springCleaningMint,
    icon: "shuffleTheFunds",
    description: "Fourteen upgrades on this floor and every floor below",
  },
  tangoTender: {
    label: "Tango Tender",
    color: COLOR.fullHouseCrimson,
    icon: "tangoTender",
    description: "Seven upgrades here and seven on the highest floor",
  },
  tapThatAsset: {
    label: "Tap That Asset",
    color: COLOR.bonusRoundGold,
    icon: "tapThatAsset",
    description: "Seventeen payouts on alternating floors, from the ground",
  },
  waltzStreet: {
    label: "Waltz Street",
    color: COLOR.shareholdersGreen,
    icon: "waltzStreet",
    description: "Seventeen free upgrades on every unlocked floor",
  },
  prehistoric: {
    label: "Prehistoric",
    color: COLOR.chairGiveawayBrown,
    icon: "prehistoric",
    description: "One tier promotion and forty upgrades here",
  },
  breadyOrNot: {
    label: "Bready or Not",
    color: COLOR.goldenHandshakeGold,
    icon: "breadyOrNot",
    description: "Eleven upgrades on this floor and every floor below",
  },
  eggcellentWork: {
    label: "Egg-cellent Work",
    color: COLOR.sunshineGold,
    icon: "eggcellentWork",
    description: "One tier promotion and eight upgrades here",
  },
  holyGuacamole: {
    label: "Holy Guacamole",
    color: COLOR.dressCodeGreen,
    icon: "holyGuacamole",
    description: "Nineteen instant payouts on every unlocked floor",
  },
  loafActually: {
    label: "Loaf Actually",
    color: COLOR.espressoShotBrown,
    icon: "loafActually",
    description: "Twelve free upgrades on every unlocked floor",
  },
  pastaLaVista: {
    label: "Pasta La Vista",
    color: COLOR.orange,
    icon: "pastaLaVista",
    description: "Sixteen payouts on alternating floors, from the ground",
  },
  souperStar: {
    label: "Souper Star",
    color: COLOR.amberMuted,
    icon: "souperStar",
    description: "Sixteen payouts from the highest-earning floor",
  },
  tacoBoutIt: {
    label: "Taco 'Bout It",
    color: COLOR.autumnSaleAmber,
    icon: "tacoBoutIt",
    description: "Four upgrades here and four on the lowest-level floor",
  },
  theGreatPancakeStack: {
    label: "The Great Pancake Stack",
    color: COLOR.supplyRunTan,
    icon: "theGreatPancakeStack",
    description: "Twenty-one upgrades here and every floor below",
  },
  wokAndRoll: {
    label: "Wok and Roll",
    color: COLOR.summerSaleOrange,
    icon: "wokAndRoll",
    description: "Twenty-four free upgrades on the highest floor",
  },
  iAmTheNight: {
    label: "I Am the Night",
    color: COLOR.fourOfAKindIndigo,
    icon: "iAmTheNight",
    description: "Twenty-seven free upgrades on every unlocked floor",
  },
  tubs: {
    label: "Tubs",
    color: COLOR.rainCheckBlue,
    icon: "tubs",
    description: "Twenty-six instant payouts on this floor",
  },
  whySoSerious: {
    label: "Why So Serious",
    color: COLOR.halloweenSalePurple,
    icon: "whySoSerious",
    description: "Two tier promotions and twenty upgrades here",
  },
  avocardio: {
    label: "Avocardio",
    color: COLOR.bullMarketGreen,
    icon: "avocardio",
    description: "Fifteen free upgrades on this floor",
  },
  butterBelieveIt: {
    label: "Butter Believe It",
    color: COLOR.sunshineGold,
    icon: "butterBelieveIt",
    description: "Eighteen instant payouts on this floor",
  },
  cheesePullChampion: {
    label: "Cheese Pull Champion",
    color: COLOR.goldenHandshakeGold,
    icon: "cheesePullChampion",
    description: "Six upgrades and six payouts on this floor",
  },
  grillSergeant: {
    label: "Grill Sergeant",
    color: COLOR.red,
    icon: "grillSergeant",
    description: "Twenty free upgrades on every unlocked floor",
  },
  noodleNap: {
    label: "Noodle Nap",
    color: COLOR.autumnSaleAmber,
    icon: "noodleNap",
    description: "Twenty-two payouts on alternating floors, from the ground",
  },
  picklePredicament: {
    label: "Pickle Predicament",
    color: COLOR.dressCodeGreen,
    icon: "picklePredicament",
    description: "Eight free upgrades on the lowest-level floor",
  },
  golem: {
    label: "Golem",
    color: COLOR.unionBossSlate,
    icon: "golem",
    description: "Thirty-five free upgrades on the highest floor",
  },
  hotPotato: {
    label: "Hot Potato",
    color: COLOR.roundUpOrange,
    icon: "hotPotato",
    description: "Eighteen instant payouts on this floor",
  },
  brunchBoss: {
    label: "Brunch Boss",
    color: COLOR.supplyRunTan,
    icon: "brunchBoss",
    description: "Seven upgrades and seven payouts on this floor",
  },
  curryFavour: {
    label: "Curry Favour",
    color: COLOR.halloweenSalePurple,
    icon: "curryFavour",
    description: "Fourteen payouts from the highest-earning floor",
  },
  dimSumDynasty: {
    label: "Dim Sum Dynasty",
    color: COLOR.goldenHandshakeGold,
    icon: "dimSumDynasty",
    description: "Fifteen free upgrades on every unlocked floor",
  },
  soupDumplingSurgeon: {
    label: "Soup Dumpling Surgeon",
    color: COLOR.teaBreakBrown,
    icon: "soupDumplingSurgeon",
    description: "Five upgrades and ten payouts on this floor",
  },
  chocolateFountainOfYouth: {
    label: "Chocolate Fountain of Youth",
    color: COLOR.autumnSaleAmber,
    icon: "chocolateFountainOfYouth",
    description: "Twenty instant payouts on this floor",
  },
  gummyBearMarket: {
    label: "Gummy Bear Market",
    color: COLOR.red,
    icon: "gummyBearMarket",
    description: "Ten free upgrades on every unlocked floor",
  },
  jawbreaker: {
    label: "Jawbreaker",
    color: COLOR.purple,
    icon: "jawbreaker",
    description: "Eighteen free upgrades on this floor",
  },
  licoriceLaces: {
    label: "Licorice Laces",
    color: COLOR.fullHouseCrimson,
    icon: "licoriceLaces",
    description: "Nine free upgrades on the lowest-level floor",
  },
  lollipopGuild: {
    label: "Lollipop Guild",
    color: COLOR.peppermintPink,
    icon: "lollipopGuild",
    description: "Twelve payouts on alternating floors, from the ground",
  },
  marshmallowMountain: {
    label: "Marshmallow Mountain",
    color: COLOR.white,
    icon: "marshmallowMountain",
    description: "Eight free upgrades on the highest unlocked floor",
  },
  sugarHigh: {
    label: "Sugar High",
    color: COLOR.starYellow,
    icon: "sugarHigh",
    description: "Five upgrades and five payouts on every unlocked floor",
  },
  bubblegumBalloon: {
    label: "Bubblegum Balloon",
    color: COLOR.springSalePink,
    icon: "bubblegumBalloon",
    description: "Fifteen instant payouts on this floor",
  },
  candyCaneClimber: {
    label: "Candy Cane Climber",
    color: COLOR.red,
    icon: "candyCaneClimber",
    description: "Twelve free upgrades on the highest unlocked floor",
  },
  sherbetSherpa: {
    label: "Sherbet Sherpa",
    color: COLOR.easterSalePink,
    icon: "sherbetSherpa",
    description: "Eight instant payouts on every unlocked floor",
  },
  toffeeTrap: {
    label: "Toffee Trap",
    color: COLOR.autumnSaleAmber,
    icon: "toffeeTrap",
    description: "Seven free upgrades on this floor",
  },
  cottonCandyCloud: {
    label: "Cotton Candy Cloud",
    color: COLOR.peppermintPink,
    icon: "cottonCandyCloud",
    description: "Eleven instant payouts on this floor",
  },
  fudgeIt: {
    label: "Fudge It",
    color: COLOR.autumnSaleAmber,
    icon: "fudgeIt",
    description: "Fourteen free upgrades on this floor",
  },
  gobstopperGetaway: {
    label: "Gobstopper Getaway",
    color: COLOR.orange,
    icon: "gobstopperGetaway",
    description: "Thirteen free upgrades on the highest floor",
  },
  jellyBeanJamboree: {
    label: "Jelly Bean Jamboree",
    color: COLOR.springSalePink,
    icon: "jellyBeanJamboree",
    description: "Ten payouts on alternating floors, from the ground",
  },
  rockCandyQuarry: {
    label: "Rock Candy Quarry",
    color: COLOR.cyan,
    icon: "rockCandyQuarry",
    description: "One tier promotion and seven upgrades here",
  },
  sprinkleStorm: {
    label: "Sprinkle Storm",
    color: COLOR.blue,
    icon: "sprinkleStorm",
    description: "Six free upgrades on every unlocked floor",
  },
  dungeonAccountant: {
    label: "Dungeon Accountant",
    color: COLOR.nightShiftIndigo,
    icon: "dungeonAccountant",
    description: "Nine free upgrades on this floor",
  },
  lootGoblin: {
    label: "Loot Goblin",
    color: COLOR.bullMarketGreen,
    icon: "lootGoblin",
    description: "Sixteen instant payouts on this floor",
  },
  inventoryFull: {
    label: "Inventory Full",
    color: COLOR.gold,
    icon: "inventoryFull",
    description: "Twelve free upgrades on this floor",
  },
  sideQuestSalary: {
    label: "Side Quest Salary",
    color: COLOR.heavenlyGold,
    icon: "sideQuestSalary",
    description: "Seven payouts from the highest-earning floor",
  },
  minMaxManager: {
    label: "Min-Max Manager",
    color: COLOR.cyan,
    icon: "minMaxManager",
    description: "Ten free upgrades on the lowest-level floor",
  },
  criticalKnit: {
    label: "Critical Knit",
    color: COLOR.peppermintPink,
    icon: "criticalKnit",
    description: "Six payouts on alternating floors, from the ground",
  },
  savePointSavings: {
    label: "Save Point Savings",
    color: COLOR.blue,
    icon: "savePointSavings",
    description: "One tier promotion and five upgrades here",
  },
  achievementUnlocked: {
    label: "Achievement Unlocked",
    color: COLOR.starYellow,
    icon: "achievementUnlocked",
    description: "One tier promotion and eight upgrades here",
  },
  newGamePlus: {
    label: "New Game Plus",
    color: COLOR.orange,
    icon: "newGamePlus",
    description: "Twenty free upgrades on this floor",
  },
  speedrunPayroll: {
    label: "Speedrun Payroll",
    color: COLOR.red,
    icon: "speedrunPayroll",
    description: "Fifteen instant payouts on every unlocked floor",
  },
  lagCompensation: {
    label: "Lag Compensation",
    color: COLOR.silverTicketGray,
    icon: "lagCompensation",
    description: "Nine instant payouts on this floor",
  },
  patchNotesPayday: {
    label: "Patch Notes Payday",
    color: COLOR.moneyGreen,
    icon: "patchNotesPayday",
    description: "Eleven free upgrades on the highest floor",
  },
  biggerOnTheInside: {
    label: "Bigger on the Inside",
    color: COLOR.blue,
    icon: "biggerOnTheInside",
    description: "Ten instant payouts on every unlocked floor",
  },
  cacheMeOutside: {
    label: "Cache Me Outside",
    color: COLOR.orange,
    icon: "cacheMeOutside",
    description: "Eight free upgrades on the lowest-level floor",
  },
  itCompiles: {
    label: "It Compiles!",
    color: COLOR.moneyGreen,
    icon: "itCompiles",
    description: "Fifteen free upgrades on this floor",
  },
  magicalPayrollGirl: {
    label: "Magical Payroll Girl",
    color: COLOR.peppermintPink,
    icon: "magicalPayrollGirl",
    description: "One tier promotion and ten upgrades here",
  },
  mechaMiddleManagement: {
    label: "Mecha Middle Management",
    color: COLOR.red,
    icon: "mechaMiddleManagement",
    description: "Twelve free upgrades on every unlocked floor",
  },
  mergeConflict: {
    label: "Merge Conflict",
    color: COLOR.fullHouseCrimson,
    icon: "mergeConflict",
    description: "Seven upgrades and seven payouts on this floor",
  },
  mintCondition: {
    label: "Mint Condition",
    color: COLOR.cyan,
    icon: "mintCondition",
    description: "Eighteen payouts from the highest-earning floor",
  },
  stackOverflowing: {
    label: "Stack Overflowing",
    color: COLOR.gold,
    icon: "stackOverflowing",
    description: "Nine free upgrades on the highest floor",
  },
  oneMoreRound: {
    label: "One More Round",
    color: COLOR.sunshineGold,
    icon: "oneMoreRound",
    description: "Eight upgrades and eight payouts on this floor",
  },
  couchCoOpCapital: {
    label: "Couch Co-Op Capital",
    color: COLOR.blue,
    icon: "couchCoOpCapital",
    description: "Nine free upgrades on every unlocked floor",
  },
  hardCarry: {
    label: "Hard Carry",
    color: COLOR.orange,
    icon: "hardCarry",
    description: "Fourteen free upgrades on the highest floor",
  },
  readyCheck: {
    label: "Ready Check",
    color: COLOR.moneyGreen,
    icon: "readyCheck",
    description: "Six free upgrades on every unlocked floor",
  },
  queueRoyalty: {
    label: "Queue Royalty",
    color: COLOR.heavenlyGold,
    icon: "queueRoyalty",
    description: "Twelve instant payouts on this floor",
  },
  rankedAndBanked: {
    label: "Ranked and Banked",
    color: COLOR.gold,
    icon: "rankedAndBanked",
    description: "Eleven free upgrades on this floor",
  },
  victoryPose: {
    label: "Victory Pose",
    color: COLOR.starYellow,
    icon: "victoryPose",
    description: "Eighteen free upgrades on this floor",
  },
  emoteEconomy: {
    label: "Emote Economy",
    color: COLOR.peppermintPink,
    icon: "emoteEconomy",
    description: "Eight payouts on every unlocked floor",
  },
  checkpointChampion: {
    label: "Checkpoint Champion",
    color: COLOR.cyan,
    icon: "checkpointChampion",
    description: "Ten free upgrades on the highest floor",
  },
  fishingForFunds: {
    label: "Fishing for Funds",
    color: COLOR.moneyGreen,
    icon: "fishingForFunds",
    description: "Thirteen instant payouts on this floor",
  },
  purrfectOrigin: {
    label: "Purrfect Origin",
    color: COLOR.sunshineGold,
    icon: "purrfectOrigin",
    description: "Seven free upgrades on this floor",
  },
  capeEscape: {
    label: "Cape Escape",
    color: COLOR.red,
    icon: "capeEscape",
    description: "Ten payouts from the highest-earning floor",
  },
  thunderPaws: {
    label: "Thunder Paws",
    color: COLOR.blue,
    icon: "thunderPaws",
    description: "Eight free upgrades on every unlocked floor",
  },
  clawAndOrder: {
    label: "Claw and Order",
    color: COLOR.cyan,
    icon: "clawAndOrder",
    description: "Six instant payouts on this floor",
  },
  felineFury: {
    label: "Feline Fury",
    color: COLOR.fullHouseCrimson,
    icon: "felineFury",
    description: "Sixteen free upgrades on this floor",
  },
  sidekickShuffle: {
    label: "Sidekick Shuffle",
    color: COLOR.peppermintPink,
    icon: "sidekickShuffle",
    description: "Seven upgrades on alternating floors, from the ground",
  },
  cosmicCatapult: {
    label: "Cosmic Catapult",
    color: COLOR.nightShiftIndigo,
    icon: "cosmicCatapult",
    description: "Nine payouts on every unlocked floor",
  },
  theMoonstoneKey: {
    label: "The Moonstone Key",
    color: COLOR.silverTicketGray,
    icon: "theMoonstoneKey",
    description: "One tier promotion and six upgrades here",
  },
  spellbookSupreme: {
    label: "Spellbook Supreme",
    color: COLOR.purple,
    icon: "spellbookSupreme",
    description: "Twelve free upgrades on this floor",
  },
  prismPotion: {
    label: "Prism Potion",
    color: COLOR.cyan,
    icon: "prismPotion",
    description: "Fourteen payouts from the highest-earning floor",
  },
  galaxyGumball: {
    label: "Galaxy Gumball",
    color: COLOR.springSalePink,
    icon: "galaxyGumball",
    description: "Eleven instant payouts on this floor",
  },
  treasureTruffle: {
    label: "Treasure Truffle",
    color: COLOR.goldenHandshakeGold,
    icon: "treasureTruffle",
    description: "Five upgrades and five payouts on this floor",
  },
  wizardsWaffle: {
    label: "Wizard's Waffle",
    color: COLOR.autumnSaleAmber,
    icon: "wizardsWaffle",
    description: "Ten free upgrades on every unlocked floor",
  },
  goldenFortuneCookie: {
    label: "Golden Fortune Cookie",
    color: COLOR.heavenlyGold,
    icon: "goldenFortuneCookie",
    description: "Nine free upgrades on the lowest-level floor",
  },
  crystalDragonEgg: {
    label: "Crystal Dragon Egg",
    color: COLOR.cyan,
    icon: "crystalDragonEgg",
    description: "Twelve free upgrades on this floor",
  },
  diamondCompass: {
    label: "Diamond Compass",
    color: COLOR.blue,
    icon: "diamondCompass",
    description: "Ten payouts from the highest-earning floor",
  },
  emeraldCrown: {
    label: "Emerald Crown",
    color: COLOR.moneyGreen,
    icon: "emeraldCrown",
    description: "One tier promotion and eight upgrades here",
  },
  goldenFleece: {
    label: "Golden Fleece",
    color: COLOR.gold,
    icon: "goldenFleece",
    description: "Seven payouts on every unlocked floor",
  },
  imperialScepter: {
    label: "Imperial Scepter",
    color: COLOR.heavenlyGold,
    icon: "imperialScepter",
    description: "Thirteen free upgrades on the highest floor",
  },
  rubyHeartRelic: {
    label: "Ruby Heart Relic",
    color: COLOR.fullHouseCrimson,
    icon: "rubyHeartRelic",
    description: "Twelve instant payouts on this floor",
  },
  sapphireHourglass: {
    label: "Sapphire Hourglass",
    color: COLOR.silverTicketGray,
    icon: "sapphireHourglass",
    description: "Nine payouts on alternating floors, from the ground",
  },
  vaultOfJewels: {
    label: "Vault of Jewels",
    color: COLOR.goldenHandshakeGold,
    icon: "vaultOfJewels",
    description: "Six free upgrades on every unlocked floor",
  },
  goldenIdol: {
    label: "Golden Idol",
    color: COLOR.goldenParachuteMarigold,
    icon: "goldenIdol",
    description: "Fifteen free upgrades on this floor",
  },
} as const satisfies Record<string, CritProcDisplayInfo>;

export type FeaturedCritKind = keyof typeof FEATURED_CRIT_INFO;
export const FEATURED_CRIT_KINDS = Object.keys(
  FEATURED_CRIT_INFO,
) as FeaturedCritKind[];

export function featuredCritFlags(
  enabled: ReadonlySet<string> = new Set(),
): Record<FeaturedCritKind, boolean> {
  return Object.fromEntries(
    FEATURED_CRIT_KINDS.map((kind) => [kind, enabled.has(kind)]),
  ) as Record<FeaturedCritKind, boolean>;
}
