import {
  FLOOR_X_MIN,
  FLOOR_X_MAX,
  ROOM_CONTENT_SCALE,
  ROOM_CONTENT_Y_OFFSET,
} from "../constants";
import {
  isBoosted,
  activateBoosted,
  getBoostRemainingMs,
  BOOST_URGENT_THRESHOLD_MS,
  getWorkerTintIndexes,
  type Floor,
} from "../../gameState";
import { randomInt } from "../../utils";
import { loadThemeSprite } from "../../loadAssets";
import { spawnCoinBurst } from "../coins";
import { playBloop } from "../../sound";

// generated by scripts/process-cat-sprites.mjs from src/assets/themes/references/workerSprites.png —
// a single row of 5 equal-size cells, feet aligned to the same bottom row in every
// cell. Frame size is read from the loaded image's own natural size rather than
// hardcoded, in case that script is ever re-run with different padding.
const FRAME_COUNT = 5;
// fixed palette of hues recolor.ts-style 'hue' blend-mode tinting cycles workers
// through (see recolorFrame below) — one base sprite instead of separate art per
// color. Picked as saturated, evenly-spaced hues rather than named cat colors
// (gray/black/white) because the 'hue' canvas blend mode can only change hue while
// keeping the sprite's own saturation/lightness — it can't desaturate or darken/
// lighten, so grayscale variants aren't achievable with this technique.
const THEME_COLORS = [
  "hsl(20, 85%, 50%)", // ginger (close to the base art's own natural color)
  "hsl(45, 85%, 50%)", // gold
  "hsl(340, 85%, 50%)", // rose
  "hsl(275, 85%, 50%)", // violet
  "hsl(205, 85%, 50%)", // sky blue
  "hsl(150, 85%, 40%)", // mint
  "hsl(0, 80%, 50%)", // red
  "hsl(5, 75%, 65%)", // salmon
  "hsl(10, 85%, 55%)", // coral
  "hsl(35, 85%, 50%)", // amber
  "hsl(55, 80%, 45%)", // honey
  "hsl(75, 70%, 40%)", // lime
  "hsl(90, 55%, 35%)", // olive
  "hsl(110, 60%, 30%)", // forest
  "hsl(130, 65%, 35%)", // emerald
  "hsl(170, 70%, 35%)", // teal
  "hsl(185, 80%, 45%)", // cyan
  "hsl(195, 80%, 45%)", // cerulean
  "hsl(220, 75%, 50%)", // cobalt
  "hsl(240, 60%, 50%)", // indigo
  "hsl(250, 70%, 60%)", // periwinkle
  "hsl(260, 60%, 65%)", // lavender
  "hsl(290, 70%, 55%)", // orchid
  "hsl(310, 80%, 50%)", // magenta
  "hsl(325, 85%, 55%)", // fuchsia
  "hsl(350, 80%, 45%)", // crimson
];
// frames 2/3 are the two mirrored mid-stride poses (left-leg-forward / right-leg-
// forward) and alternate forever as the walk loop; frames 0/1 play once, in order,
// as a brief turn-around transition right after a direction reversal (see
// TURN_FRAME_MS below) before the walk loop resumes; frame 4 (arms-up happy pose) is
// reserved for the click reaction.
const WALK_FRAMES = [2, 3];
const TURN_FRAMES = [0, 1];
const CLICK_FRAME = 4;
const WALK_FRAME_MS = 260; // how long each walk-cycle frame is held on screen
// every pose in the sheet faces the camera head-on rather than in profile, so
// flipping mid-stride whenever direction reverses can momentarily show legs
// "swapping sides" — playing the short TURN_FRAMES sequence (already mirrored to
// the new direction) right after a turn hides that seam, then the walk loop resumes
// cleanly from its own first frame instead of wherever the shared clock lands
const TURN_FRAME_MS = 260;
// squash-and-stretch while walking, synced to each individual step (not the full
// L/R stride pair) so the bounce cadence matches footfalls: neutral at each foot
// contact, stretched taller/narrower at the mid-step peak — without this the sprite
// just slides across the floor frame-swapping in place, reading as a cardboard
// cutout instead of a cartoon character actually moving
const WALK_BOUNCE_MS = WALK_FRAME_MS;
const WALK_SQUASH_AMOUNT = 0.015;
const WALK_BOB_HEIGHT = 1;

// on-screen render size of one worker; width is aspect-locked to the sprite's own
// cell shape (see drawFigure)
const RENDER_H = 480;

let workerSprite: HTMLImageElement | null = null;
// generated by scripts/process-cat-sprites.mjs from src/assets/managerSprites.png,
// same uniform 5-pose grid as the base cat sprite above. Whichever worker
// currently represents a floor's hired manager (see drawWorker below) uses this
// sheet instead of catSpriteUrl, going through the exact same tint/movement code
let managerSprite: HTMLImageElement | null = null;

// loads both base sprite sheets once; main.ts awaits this alongside
// loadFloorBackgrounds before the first frame ever needs to draw a worker
export async function loadWorkerSprite(): Promise<HTMLImageElement> {
  [workerSprite, managerSprite] = await Promise.all([
    loadThemeSprite("references", "worker"),
    loadThemeSprite("references", "manager"),
  ]);
  return workerSprite!;
}

let workerIconUrl: string | null = null;
let managerIconUrl: string | null = null;

// crops sprite's TURN_FRAMES[0] pose (the plain, untinted, camera-facing neutral
// pose already in every walk-cycle sheet) down to its own actual non-transparent
// silhouette bounding box — the whole figure, head to feet, no forced aspect
// ratio — instead of the raw frame's own padded cell (room for the walk cycle's
// other poses to swing arms/legs into). object-fit: contain in the fixed square
// icon box (see style.css's .worker-menu__icon) then scales this tighter crop up
// to fill as much of the icon box as its own aspect ratio allows, with nothing
// cut off — reused by both getWorkerIconUrl and getManagerIconUrl below
function cropCameraFacingIconUrl(sprite: HTMLImageElement): string {
  const frameW = sprite.naturalWidth / FRAME_COUNT;
  const frameH = sprite.naturalHeight;
  const frameX = TURN_FRAMES[0] * frameW;

  // isolate just this one frame first so the bounding-box scan below only sees
  // its own content, not the sheet's other frames
  const frameCanvas = document.createElement("canvas");
  frameCanvas.width = frameW;
  frameCanvas.height = frameH;
  const frameCtx = frameCanvas.getContext("2d")!;
  frameCtx.drawImage(sprite, frameX, 0, frameW, frameH, 0, 0, frameW, frameH);

  const { data } = frameCtx.getImageData(0, 0, frameW, frameH);
  let minX = frameW;
  let maxX = 0;
  let minY = frameH;
  let maxY = 0;
  for (let y = 0; y < frameH; y++) {
    for (let x = 0; x < frameW; x++) {
      if (data[(y * frameW + x) * 4 + 3] === 0) continue;
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
  const cropW = Math.max(1, maxX - minX);
  const cropH = Math.max(1, maxY - minY);

  const canvas = document.createElement("canvas");
  canvas.width = cropW;
  canvas.height = cropH;
  const ctx = canvas.getContext("2d")!;
  ctx.drawImage(frameCanvas, minX, minY, cropW, cropH, 0, 0, cropW, cropH);
  return canvas.toDataURL("image/png");
}

// the generic "hire worker" icon (hud/upgradeMenu) — see cropCameraFacingIconUrl.
// Cropped once and cached; returns null until loadWorkerSprite has resolved
export function getWorkerIconUrl(): string | null {
  if (workerIconUrl) return workerIconUrl;
  if (!workerSprite) return null;
  workerIconUrl = cropCameraFacingIconUrl(workerSprite);
  return workerIconUrl;
}

// the "hire manager"/manager-boost icons (hud/upgradeMenu, hud/corporationBoostMenu)
// — see cropCameraFacingIconUrl. Cropped once and cached; returns null until
// loadWorkerSprite has resolved (it loads managerSprite too)
export function getManagerIconUrl(): string | null {
  if (managerIconUrl) return managerIconUrl;
  if (!managerSprite) return null;
  managerIconUrl = cropCameraFacingIconUrl(managerSprite);
  return managerIconUrl;
}

export const WALK_SPEED = 50; // px/sec
const BOOSTED_WALK_SPEED = WALK_SPEED * 2;
// feet rest on the room art's own floor line, scaled by the same ROOM_CONTENT_SCALE/
// ROOM_CONTENT_Y_OFFSET drawFloor positions its art by, so the cat keeps standing on
// the art's actual floor instead of the area now covered by the taller divider —
// nudged down an extra WORKER_FEET_Y_NUDGE_PX per an explicit visual tweak request
export const WORKER_FEET_Y_NUDGE_PX = 46;
const WORKER_FEET_Y =
  ROOM_CONTENT_Y_OFFSET + 650 * ROOM_CONTENT_SCALE + WORKER_FEET_Y_NUDGE_PX;
const CLICK_BOUNCE_MS = 300; // how long the little "boing" reaction plays after a click
const CLICK_COOLDOWN_MS = 500; // ignore re-clicks faster than this so coin bursts don't stack up
// how long a walker keeps walking, or keeps doing one of the idle behaviors below,
// before randomly rolling its next behavior — see rollBehavior
const WALK_MS_RANGE: [number, number] = [2000, 5000];
const PAUSE_MS_RANGE: [number, number] = [500, 2000];
const LOOK_BACK_MS_RANGE: [number, number] = [450, 900];
// generous click-target box around the figure; the sprite's own ~0.48
// width/height aspect ratio, so this doesn't need per-frame precision
const HIT_HALF_WIDTH = RENDER_H * 0.48 * 0.5 + 10;
const HIT_TOP = RENDER_H + 10;
const HIT_BOTTOM = 10;
// workerMenu.ts caps floor.workerCount at this too, so every worker a floor has is
// always one of the little figures actually drawn/walked here
export const MAX_RENDERED_WORKERS = 3;

// a walker's current idle behavior: normal pacing, paused standing still (facing the
// camera like every pose in the sheet already does), or briefly glancing back over
// its shoulder (rendered facing the opposite way) without actually reversing course
type Behavior = "walking" | "paused" | "lookingBack";

interface WalkerState {
  x: number;
  direction: 1 | -1;
  lastUpdate: number;
  facingSince: number; // when direction last changed, so a turn briefly plays TURN_FRAMES
  clickedAt: number; // Date.now() of this worker's own last click, -Infinity if never clicked
  behavior: Behavior;
  behaviorSince: number; // when the current behavior started (animates lookingBack's turn)
  behaviorUntil: number; // when to randomly roll the next behavior
}

interface FloorWorkers {
  walkers: WalkerState[];
}

// each floor gets its own independent set of walkers, keyed by the floor itself
const floorWorkers = new WeakMap<Floor, FloorWorkers>();

// picks a color for a new walker: always one none of this floor's other current
// walkers are already wearing, picked randomly among whichever qualify. Only
// forced into a duplicate if there are more walkers than THEME_COLORS entries
// (impossible today — MAX_RENDERED_WORKERS is far smaller than the palette — but
// kept as a safety net instead of throwing if that ever changes)
function pickTintIndex(existingIndexes: number[]): number {
  const count = THEME_COLORS.length;
  if (count <= 1) return 0;
  const used = new Set(existingIndexes);
  const unused: number[] = [];
  for (let i = 0; i < count; i++) if (!used.has(i)) unused.push(i);
  const pool =
    unused.length > 0 ? unused : Array.from({ length: count }, (_, i) => i);
  return pool[randomInt(0, pool.length - 1)];
}

// reassigns any duplicate color still left in a floor's persisted tint picks (e.g.
// from before this floor's worker count shrank and regrew, or from an older save)
// to one nothing else on the floor is currently wearing, so every rendered worker
// on the same floor is always visually distinct. Only looks at/touches the first
// activeCount entries — any extra trailing picks belong to workers not currently
// rendered and get their own chance to dedupe once they're actually drawn again
function dedupeTintIndexes(tintIndexes: number[], activeCount: number): void {
  const seen = new Set<number>();
  for (let i = 0; i < activeCount; i++) {
    if (seen.has(tintIndexes[i])) {
      tintIndexes[i] = pickTintIndex(Array.from(seen));
    }
    seen.add(tintIndexes[i]);
  }
}

function makeWalker(index: number, total: number, now: number): WalkerState {
  // spreads walkers into evenly-spaced starting bands instead of piling them on
  // top of each other when a floor has more than one
  const bandWidth = (FLOOR_X_MAX - FLOOR_X_MIN) / total;
  const bandStart = FLOOR_X_MIN + bandWidth * index;
  return {
    x: bandStart + Math.random() * bandWidth,
    direction: Math.random() < 0.5 ? 1 : -1,
    lastUpdate: now,
    facingSince: now,
    clickedAt: -Infinity,
    behavior: "walking",
    behaviorSince: now,
    behaviorUntil: now + randomInt(...WALK_MS_RANGE),
  };
}

// randomly picks the walker's next idle behavior once its current one expires:
// mostly keeps pacing, but sometimes pauses to stand facing the camera for a bit,
// or glances back the way it came before carrying on in the same direction
function rollBehavior(
  now: number,
): Pick<WalkerState, "behavior" | "behaviorSince" | "behaviorUntil"> {
  const roll = Math.random();
  const [behavior, range]: [Behavior, [number, number]] =
    roll < 0.2
      ? ["paused", PAUSE_MS_RANGE]
      : roll < 0.35
        ? ["lookingBack", LOOK_BACK_MS_RANGE]
        : ["walking", WALK_MS_RANGE];
  return {
    behavior,
    behaviorSince: now,
    behaviorUntil: now + randomInt(...range),
  };
}

function getFloorWorkers(floor: Floor, now: number): FloorWorkers {
  let state = floorWorkers.get(floor);
  if (!state) {
    state = { walkers: [] };
    floorWorkers.set(floor, state);
  }
  // a hired manager (see hud/upgradeMenu) is an EXTRA figure alongside this
  // floor's regular workers, not a reskin of one of them — so it's tacked on past
  // the normal worker-count cap, not counted against MAX_RENDERED_WORKERS
  const targetCount =
    Math.min(Math.max(floor.workerCount, 1), MAX_RENDERED_WORKERS) +
    (floor.hasManager ? 1 : 0);
  while (state.walkers.length < targetCount) {
    state.walkers.push(makeWalker(state.walkers.length, targetCount, now));
  }
  if (state.walkers.length > targetCount) state.walkers.length = targetCount;

  // a persisted color pick (survives reload) exists per worker index once assigned;
  // grow it here (never shrink — a restored floor may briefly have more picks than
  // currently-rendered workers if MAX_RENDERED_WORKERS changes) the first time each
  // index is actually drawn, avoiding duplicates among this floor's other workers.
  // Also repairs any duplicate left over in already-persisted picks (e.g. from an
  // older save), so every currently-rendered worker on a floor is always distinct.
  const tintIndexes = getWorkerTintIndexes(floor);
  while (tintIndexes.length < state.walkers.length) {
    tintIndexes.push(pickTintIndex(tintIndexes));
  }
  dedupeTintIndexes(tintIndexes, state.walkers.length);
  return state;
}

// how many worker figures a floor actually renders, including its manager slot if
// hired (see getFloorWorkers) — boostMenu.ts uses this so "boost every worker"
// boosts the manager too, instead of recomputing its own (manager-unaware) count
export function getRenderedWorkerCount(floor: Floor): number {
  return (
    Math.min(Math.max(floor.workerCount, 1), MAX_RENDERED_WORKERS) +
    (floor.hasManager ? 1 : 0)
  );
}

// how often a hired manager re-triggers the boost on its own floor, no player
// action needed
const MANAGER_AUTO_BOOST_INTERVAL_MS = 20_000;
const managerNextBoostAt = new WeakMap<Floor, number>();

// once a floor has a manager, it re-boosts every worker (+ itself) on its own
// floor every MANAGER_AUTO_BOOST_INTERVAL_MS, with the same click/jump
// celebration + coin burst + sound a real worker click produces — called once
// per frame from drawWorker below
function maybeTriggerManagerBoost(floor: Floor, now: number): void {
  if (!floor.hasManager) {
    managerNextBoostAt.delete(floor);
    return;
  }
  const nextAt = managerNextBoostAt.get(floor);
  if (nextAt === undefined) {
    managerNextBoostAt.set(floor, now + MANAGER_AUTO_BOOST_INTERVAL_MS);
    return;
  }
  if (now < nextAt) return;
  const state = getFloorWorkers(floor, now);
  const feetY = WORKER_FEET_Y;
  state.walkers.forEach((walker, i) => {
    activateBoosted(floor, i, now);
    walker.clickedAt = now;
    // same coin burst + sound a real click on this worker would produce
    playBloop();
    spawnCoinBurst(floor, walker.x, feetY - RENDER_H / 2, () => {});
  });
  managerNextBoostAt.set(floor, now + MANAGER_AUTO_BOOST_INTERVAL_MS);
}

// every one of a floor's rendered workers whose hitbox covers a floor-local point —
// a click on overlapping cats hits all of them at once, not just the frontmost one
export function hitTestWorkers(x: number, y: number, floor: Floor): number[] {
  if (!floor.unlocked) return [];
  const state = floorWorkers.get(floor);
  if (!state) return [];

  const withinY =
    y >= WORKER_FEET_Y - HIT_TOP && y <= WORKER_FEET_Y + HIT_BOTTOM;
  if (!withinY) return [];

  const indexes: number[] = [];
  state.walkers.forEach((w, i) => {
    if (x >= w.x - HIT_HALF_WIDTH && x <= w.x + HIT_HALF_WIDTH) indexes.push(i);
  });
  return indexes;
}

// starts the clicked worker's own click-bounce animation and reports whether the click
// should spawn a coin burst; returns false while that specific worker is still on
// cooldown, so rapid clicks on it can't pile up coins (clicking a different worker on
// the same floor is unaffected)
export function clickWorker(
  floor: Floor,
  workerIndex: number,
  now: number,
): boolean {
  const walker = getFloorWorkers(floor, now).walkers[workerIndex];
  if (!walker) return false;
  if (now - walker.clickedAt < CLICK_COOLDOWN_MS) return false;
  walker.clickedAt = now;
  return true;
}

// starts every unlocked floor's every worker's own click-bounce/jump animation at
// once, ignoring each worker's individual click cooldown — used for building-wide
// celebrations (e.g. clicking the free-boost mouse) rather than a single click on
// one specific worker
export function triggerJumpAll(floors: Floor[], now: number): void {
  for (const floor of floors) {
    if (!floor.unlocked) continue;
    for (const walker of getFloorWorkers(floor, now).walkers) {
      walker.clickedAt = now;
    }
  }
}

// on-screen (floor-local) center of one of a floor's workers, for aiming a coin burst
// at it; null if it hasn't been drawn yet (shouldn't happen once unlocked)
export function getWorkerCenter(
  floor: Floor,
  workerIndex: number,
): { x: number; y: number } | null {
  const walker = floorWorkers.get(floor)?.walkers[workerIndex];
  if (!walker) return null;
  return { x: walker.x, y: WORKER_FEET_Y - RENDER_H / 2 };
}

// on-screen (floor-local) center of every currently-boosted worker on the floor, so
// the floating-coin animation only plays at the ones actually boosted.
// `blinkIntensity` ramps from 0 (just entered the urgent window) to 1 (about to
// expire) once that worker's boost has BOOST_URGENT_THRESHOLD_MS or less left, so
// the caller's floating coins can blink harder the closer the boost is to running out
export function getBoostedWorkerCenters(
  floor: Floor,
  now: number,
): { x: number; y: number; blinkIntensity: number }[] {
  const state = floorWorkers.get(floor);
  if (!state) return [];
  const y = WORKER_FEET_Y - RENDER_H / 2;
  return state.walkers
    .map((w, i) => ({
      x: w.x,
      y,
      boosted: isBoosted(floor, i, now),
      remainingMs: getBoostRemainingMs(floor, i, now),
    }))
    .filter((w) => w.boosted)
    .map(({ x, y, remainingMs }) => ({
      x,
      y,
      blinkIntensity:
        remainingMs >= BOOST_URGENT_THRESHOLD_MS
          ? 0
          : 1 - remainingMs / BOOST_URGENT_THRESHOLD_MS,
    }));
}

// one recolored frame per (frame, tintIndex) pair is built once and reused forever
// after that — cheap since it's at most 5 frames * THEME_COLORS.length canvases
const recoloredFrameCache = new Map<string, HTMLCanvasElement>();

// crops one frame out of the base sprite onto its own canvas, then recolors it via
// the canvas 'hue' blend mode (shifts hue only, keeping the art's own
// shading/highlights) tinted to THEME_COLORS[tintIndex]. The 'hue' blend mode
// ignores destination alpha when compositing, so it would otherwise paint a solid
// colored box over the frame's transparent padding too — 'destination-in' with the
// original frame re-masks the result back down to the cat's actual silhouette.
function getRecoloredFrame(
  frame: number,
  tintIndex: number,
  sprite: HTMLImageElement | null,
): HTMLCanvasElement | null {
  if (!sprite) return null;
  const key = `${sprite === managerSprite ? "m" : "w"}:${frame}:${tintIndex}`;
  const cached = recoloredFrameCache.get(key);
  if (cached) return cached;

  const frameW = sprite.naturalWidth / FRAME_COUNT;
  const frameH = sprite.naturalHeight;
  const canvas = document.createElement("canvas");
  canvas.width = frameW;
  canvas.height = frameH;
  const ctx = canvas.getContext("2d")!;

  ctx.drawImage(
    sprite,
    frame * frameW,
    0,
    frameW,
    frameH,
    0,
    0,
    frameW,
    frameH,
  );
  ctx.globalCompositeOperation = "hue";
  ctx.fillStyle = THEME_COLORS[tintIndex] ?? THEME_COLORS[0];
  ctx.fillRect(0, 0, frameW, frameH);
  ctx.globalCompositeOperation = "destination-in";
  ctx.drawImage(
    sprite,
    frame * frameW,
    0,
    frameW,
    frameH,
    0,
    0,
    frameW,
    frameH,
  );
  ctx.globalCompositeOperation = "source-over";

  recoloredFrameCache.set(key, canvas);
  return canvas;
}

// draws one worker's current walk-cycle/click-reaction frame at (cx, groundY), facing
// per direction; groundY is where its feet touch down, recolored per tintIndex,
// cropped from whichever base sprite sheet is passed in (workerSprite or
// managerSprite — same recolor/movement logic either way). stretchX/stretchY (both
// 1 outside an active walk bounce) scale from that same feet anchor, so squashing/
// stretching never lifts the feet off their ground line
function drawFigure(
  ctx: CanvasRenderingContext2D,
  cx: number,
  groundY: number,
  direction: 1 | -1,
  frame: number,
  tintIndex: number,
  stretchX: number,
  stretchY: number,
  sprite: HTMLImageElement | null,
): void {
  const recolored = getRecoloredFrame(frame, tintIndex, sprite);
  if (!recolored) return;
  const renderW = (RENDER_H * recolored.width) / recolored.height;

  ctx.save();
  ctx.translate(cx, groundY);
  // the jump/click pose (frame 4) is authored mirrored relative to every other
  // frame in the sheet, so it needs the opposite mirror rule to still face the
  // walker's actual direction
  const mirrored = frame === CLICK_FRAME ? direction === 1 : direction === -1;
  ctx.scale(mirrored ? -stretchX : stretchX, stretchY);
  ctx.drawImage(recolored, -renderW / 2, -RENDER_H, renderW, RENDER_H);
  ctx.restore();
}

// this walker's current frame: TURN_FRAMES played once right after its last
// direction turn, then the walk loop cycling cleanly from its own first frame
function walkFrameFor(walker: WalkerState, now: number): number {
  const sinceTurn = now - walker.facingSince;
  const turnDuration = TURN_FRAMES.length * TURN_FRAME_MS;
  if (sinceTurn < turnDuration) {
    return TURN_FRAMES[Math.floor(sinceTurn / TURN_FRAME_MS)];
  }
  const step =
    Math.floor((sinceTurn - turnDuration) / WALK_FRAME_MS) % WALK_FRAMES.length;
  return WALK_FRAMES[step];
}

// plays TURN_FRAMES once (turning to glance back), then holds on the last one for
// the rest of the lookingBack window
function lookBackFrameFor(walker: WalkerState, now: number): number {
  const step = Math.min(
    Math.floor((now - walker.behaviorSince) / TURN_FRAME_MS),
    TURN_FRAMES.length - 1,
  );
  return TURN_FRAMES[step];
}

// up to MAX_RENDERED_WORKERS little cats (walk-cycle sprite flipbook) that pace back
// and forth across the floor's walkable band; no-ops on locked floors (nothing to
// animate behind the grey overlay) or before the sprite sheet has finished loading
export function drawWorker(
  ctx: CanvasRenderingContext2D,
  floor: Floor,
  now: number,
): void {
  if (!floor.unlocked || !workerSprite) return;

  maybeTriggerManagerBoost(floor, now);

  const state = getFloorWorkers(floor, now);
  const tintIndexes = getWorkerTintIndexes(floor);
  // the manager (see getFloorWorkers) is always the LAST walker once hired — an
  // extra figure tacked on past the regular workers, not one of them reskinned
  const managerWalkerIndex = floor.hasManager ? state.walkers.length - 1 : -1;

  state.walkers.forEach((walker, i) => {
    if (now >= walker.behaviorUntil) Object.assign(walker, rollBehavior(now));

    const speed = isBoosted(floor, i, now) ? BOOSTED_WALK_SPEED : WALK_SPEED;
    // exact position never needs to be preserved (it's not persisted, and nobody
    // notices where a worker "was" after a gap) so there's no reason to cap this at
    // 0.1s — that cap was actually the cause of the visible slowdown: any redraw gap
    // over 100ms (common for a boosted/faster worker, or a floor cycling in and out
    // of gameRenderer's IntersectionObserver buffer while scrolling) got truncated to
    // a fixed 0.1s worth of movement instead of the real distance covered, making
    // motion look like it kept stuttering to a crawl. Using the real elapsed time and
    // letting the boundary clamp below catch any overshoot fixes that outright.
    const dtSeconds = Math.max((now - walker.lastUpdate) / 1000, 0);
    walker.lastUpdate = now;

    // paused/lookingBack workers stand in place — only actively walking ones move
    // or can hit a wall and reverse
    if (walker.behavior === "walking") {
      walker.x += walker.direction * speed * dtSeconds;
      if (walker.x >= FLOOR_X_MAX) {
        walker.x = FLOOR_X_MAX;
        if (walker.direction !== -1) walker.facingSince = now;
        walker.direction = -1;
      } else if (walker.x <= FLOOR_X_MIN) {
        walker.x = FLOOR_X_MIN;
        if (walker.direction !== 1) walker.facingSince = now;
        walker.direction = 1;
      }
    }

    const clickT = Math.min((now - walker.clickedAt) / CLICK_BOUNCE_MS, 1);
    const bounce = clickT < 1 ? Math.sin(clickT * Math.PI) * 14 : 0;

    // squash/stretch + a small vertical bob, synced to each footfall; only while
    // actually walking (not mid click-reaction, and not standing still/looking
    // back) so idle poses stay put instead of bobbing in place
    let walkBob = 0;
    let stretchX = 1;
    let stretchY = 1;
    if (clickT >= 1 && walker.behavior === "walking") {
      const stepPhase =
        ((now - walker.facingSince) % WALK_BOUNCE_MS) / WALK_BOUNCE_MS;
      const lift = Math.sin(stepPhase * Math.PI); // 0 at each footfall, 1 mid-step
      walkBob = -lift * WALK_BOB_HEIGHT;
      stretchX = 1 - lift * WALK_SQUASH_AMOUNT;
      stretchY = 1 + lift * WALK_SQUASH_AMOUNT;
    }

    // the click reaction always wins; otherwise the current idle behavior picks
    // both the frame and which way the figure actually faces on screen —
    // lookingBack renders facing the opposite of the walker's real direction
    // (glancing back over its shoulder) without changing where it's actually headed
    let frame: number;
    let renderDirection: 1 | -1;
    if (clickT < 1) {
      frame = CLICK_FRAME;
      renderDirection = walker.direction;
    } else if (walker.behavior === "paused") {
      frame = TURN_FRAMES[0]; // neutral pose, already facing the camera
      renderDirection = walker.direction;
    } else if (walker.behavior === "lookingBack") {
      frame = lookBackFrameFor(walker, now);
      renderDirection = walker.direction === -1 ? 1 : -1;
    } else {
      frame = walkFrameFor(walker, now);
      renderDirection = walker.direction;
    }

    drawFigure(
      ctx,
      walker.x,
      WORKER_FEET_Y - bounce + walkBob,
      renderDirection,
      frame,
      tintIndexes[i] ?? 0,
      stretchX,
      stretchY,
      // the floor's hired manager (see hud/upgradeMenu) is this one extra
      // walker slot, using managerSprite instead of the plain cat one — same
      // tint/movement code either way, just a different base sheet
      i === managerWalkerIndex ? managerSprite : workerSprite,
    );
  });
}
