import { FLOOR_X_MIN, FLOOR_X_MAX } from "../constants";
import { isBoosted, getWorkerTintIndexes, type Floor } from "../../gameState";
import { loadImage, randomInt } from "../../utils";
import catSpriteUrl from "../../assets/sprites/kitty1Walk.png";

// generated by scripts/process-cat-sprites.mjs from src/assets/kitty1Sprites.png —
// a single row of 5 equal-size cells, feet aligned to the same bottom row in every
// cell. Frame size is read from the loaded image's own natural size rather than
// hardcoded, in case that script is ever re-run with different padding.
const FRAME_COUNT = 5;
// fixed palette of hues recolor.ts-style 'hue' blend-mode tinting cycles workers
// through (see recolorFrame below) — one base sprite instead of separate art per
// color. Picked as saturated, evenly-spaced hues rather than named cat colors
// (gray/black/white) because the 'hue' canvas blend mode can only change hue while
// keeping the sprite's own saturation/lightness — it can't desaturate or darken/
// lighten, so grayscale variants aren't achievable with this technique.
const THEME_COLORS = [
  "hsl(20, 85%, 50%)", // ginger (close to the base art's own natural color)
  "hsl(45, 85%, 50%)", // gold
  "hsl(340, 85%, 50%)", // rose
  "hsl(275, 85%, 50%)", // violet
  "hsl(205, 85%, 50%)", // sky blue
  "hsl(150, 85%, 40%)", // mint
  "hsl(0, 80%, 50%)", // red
  "hsl(5, 75%, 65%)", // salmon
  "hsl(10, 85%, 55%)", // coral
  "hsl(35, 85%, 50%)", // amber
  "hsl(55, 80%, 45%)", // honey
  "hsl(75, 70%, 40%)", // lime
  "hsl(90, 55%, 35%)", // olive
  "hsl(110, 60%, 30%)", // forest
  "hsl(130, 65%, 35%)", // emerald
  "hsl(170, 70%, 35%)", // teal
  "hsl(185, 80%, 45%)", // cyan
  "hsl(195, 80%, 45%)", // cerulean
  "hsl(220, 75%, 50%)", // cobalt
  "hsl(240, 60%, 50%)", // indigo
  "hsl(250, 70%, 60%)", // periwinkle
  "hsl(260, 60%, 65%)", // lavender
  "hsl(290, 70%, 55%)", // orchid
  "hsl(310, 80%, 50%)", // magenta
  "hsl(325, 85%, 55%)", // fuchsia
  "hsl(350, 80%, 45%)", // crimson
];
// frames 2/3 are the two mirrored mid-stride poses (left-leg-forward / right-leg-
// forward) and alternate forever as the walk loop; frames 0/1 play once, in order,
// as a brief turn-around transition right after a direction reversal (see
// TURN_FRAME_MS below) before the walk loop resumes; frame 4 (arms-up happy pose) is
// reserved for the click reaction.
const WALK_FRAMES = [2, 3];
const TURN_FRAMES = [0, 1];
const CLICK_FRAME = 4;
const WALK_FRAME_MS = 260; // how long each walk-cycle frame is held on screen
// every pose in the sheet faces the camera head-on rather than in profile, so
// flipping mid-stride whenever direction reverses can momentarily show legs
// "swapping sides" — playing the short TURN_FRAMES sequence (already mirrored to
// the new direction) right after a turn hides that seam, then the walk loop resumes
// cleanly from its own first frame instead of wherever the shared clock lands
const TURN_FRAME_MS = 260;

// on-screen render size of one worker; width is aspect-locked to the sprite's own
// cell shape (see drawFigure)
const RENDER_H = 480;

let workerSprite: HTMLImageElement | null = null;

// loads the base sprite sheet once; main.ts awaits this alongside
// loadFloorBackgrounds before the first frame ever needs to draw a worker
export async function loadWorkerSprite(): Promise<HTMLImageElement> {
  workerSprite = await loadImage(catSpriteUrl);
  return workerSprite;
}

const WALK_SPEED = 50; // px/sec
const BOOSTED_WALK_SPEED = WALK_SPEED * 2;
// feet rest well above the bottom income/upgrade panels (which start at y=577) so the
// worker is always visible walking across the open floor instead of ducking behind them
const WORKER_FEET_Y = 650;
const CLICK_BOUNCE_MS = 300; // how long the little "boing" reaction plays after a click
const CLICK_COOLDOWN_MS = 500; // ignore re-clicks faster than this so coin bursts don't stack up
// how long a walker keeps walking, or keeps doing one of the idle behaviors below,
// before randomly rolling its next behavior — see rollBehavior
const WALK_MS_RANGE: [number, number] = [2000, 5000];
const PAUSE_MS_RANGE: [number, number] = [500, 2000];
const LOOK_BACK_MS_RANGE: [number, number] = [450, 900];
// generous click-target box around the figure; the sprite's own ~0.48
// width/height aspect ratio, so this doesn't need per-frame precision
const HIT_HALF_WIDTH = RENDER_H * 0.48 * 0.5 + 10;
const HIT_TOP = RENDER_H + 10;
const HIT_BOTTOM = 10;
// workerMenu.ts caps floor.workerCount at this too, so every worker a floor has is
// always one of the little figures actually drawn/walked here
export const MAX_RENDERED_WORKERS = 3;

// a walker's current idle behavior: normal pacing, paused standing still (facing the
// camera like every pose in the sheet already does), or briefly glancing back over
// its shoulder (rendered facing the opposite way) without actually reversing course
type Behavior = "walking" | "paused" | "lookingBack";

interface WalkerState {
  x: number;
  direction: 1 | -1;
  lastUpdate: number;
  facingSince: number; // when direction last changed, so a turn briefly plays TURN_FRAMES
  clickedAt: number; // Date.now() of this worker's own last click, -Infinity if never clicked
  behavior: Behavior;
  behaviorSince: number; // when the current behavior started (animates lookingBack's turn)
  behaviorUntil: number; // when to randomly roll the next behavior
}

interface FloorWorkers {
  walkers: WalkerState[];
}

// each floor gets its own independent set of walkers, keyed by the floor itself
const floorWorkers = new WeakMap<Floor, FloorWorkers>();

// picks a color for a new walker: always one none of this floor's other current
// walkers are already wearing, picked randomly among whichever qualify. Only
// forced into a duplicate if there are more walkers than THEME_COLORS entries
// (impossible today — MAX_RENDERED_WORKERS is far smaller than the palette — but
// kept as a safety net instead of throwing if that ever changes)
function pickTintIndex(existingIndexes: number[]): number {
  const count = THEME_COLORS.length;
  if (count <= 1) return 0;
  const used = new Set(existingIndexes);
  const unused: number[] = [];
  for (let i = 0; i < count; i++) if (!used.has(i)) unused.push(i);
  const pool =
    unused.length > 0 ? unused : Array.from({ length: count }, (_, i) => i);
  return pool[randomInt(0, pool.length - 1)];
}

// reassigns any duplicate color still left in a floor's persisted tint picks (e.g.
// from before this floor's worker count shrank and regrew, or from an older save)
// to one nothing else on the floor is currently wearing, so every rendered worker
// on the same floor is always visually distinct. Only looks at/touches the first
// activeCount entries — any extra trailing picks belong to workers not currently
// rendered and get their own chance to dedupe once they're actually drawn again
function dedupeTintIndexes(tintIndexes: number[], activeCount: number): void {
  const seen = new Set<number>();
  for (let i = 0; i < activeCount; i++) {
    if (seen.has(tintIndexes[i])) {
      tintIndexes[i] = pickTintIndex(Array.from(seen));
    }
    seen.add(tintIndexes[i]);
  }
}

function makeWalker(index: number, total: number, now: number): WalkerState {
  // spreads walkers into evenly-spaced starting bands instead of piling them on
  // top of each other when a floor has more than one
  const bandWidth = (FLOOR_X_MAX - FLOOR_X_MIN) / total;
  const bandStart = FLOOR_X_MIN + bandWidth * index;
  return {
    x: bandStart + Math.random() * bandWidth,
    direction: Math.random() < 0.5 ? 1 : -1,
    lastUpdate: now,
    facingSince: now,
    clickedAt: -Infinity,
    behavior: "walking",
    behaviorSince: now,
    behaviorUntil: now + randomInt(...WALK_MS_RANGE),
  };
}

// randomly picks the walker's next idle behavior once its current one expires:
// mostly keeps pacing, but sometimes pauses to stand facing the camera for a bit,
// or glances back the way it came before carrying on in the same direction
function rollBehavior(
  now: number,
): Pick<WalkerState, "behavior" | "behaviorSince" | "behaviorUntil"> {
  const roll = Math.random();
  const [behavior, range]: [Behavior, [number, number]] =
    roll < 0.2
      ? ["paused", PAUSE_MS_RANGE]
      : roll < 0.35
        ? ["lookingBack", LOOK_BACK_MS_RANGE]
        : ["walking", WALK_MS_RANGE];
  return {
    behavior,
    behaviorSince: now,
    behaviorUntil: now + randomInt(...range),
  };
}

function getFloorWorkers(floor: Floor, now: number): FloorWorkers {
  let state = floorWorkers.get(floor);
  if (!state) {
    state = { walkers: [] };
    floorWorkers.set(floor, state);
  }
  const targetCount = Math.min(
    Math.max(floor.workerCount, 1),
    MAX_RENDERED_WORKERS,
  );
  while (state.walkers.length < targetCount) {
    state.walkers.push(makeWalker(state.walkers.length, targetCount, now));
  }
  if (state.walkers.length > targetCount) state.walkers.length = targetCount;

  // a persisted color pick (survives reload) exists per worker index once assigned;
  // grow it here (never shrink — a restored floor may briefly have more picks than
  // currently-rendered workers if MAX_RENDERED_WORKERS changes) the first time each
  // index is actually drawn, avoiding duplicates among this floor's other workers.
  // Also repairs any duplicate left over in already-persisted picks (e.g. from an
  // older save), so every currently-rendered worker on a floor is always distinct.
  const tintIndexes = getWorkerTintIndexes(floor);
  while (tintIndexes.length < state.walkers.length) {
    tintIndexes.push(pickTintIndex(tintIndexes));
  }
  dedupeTintIndexes(tintIndexes, state.walkers.length);
  return state;
}

// every one of a floor's rendered workers whose hitbox covers a floor-local point —
// a click on overlapping cats hits all of them at once, not just the frontmost one
export function hitTestWorkers(x: number, y: number, floor: Floor): number[] {
  if (!floor.unlocked) return [];
  const state = floorWorkers.get(floor);
  if (!state) return [];

  const withinY =
    y >= WORKER_FEET_Y - HIT_TOP && y <= WORKER_FEET_Y + HIT_BOTTOM;
  if (!withinY) return [];

  const indexes: number[] = [];
  state.walkers.forEach((w, i) => {
    if (x >= w.x - HIT_HALF_WIDTH && x <= w.x + HIT_HALF_WIDTH) indexes.push(i);
  });
  return indexes;
}

// starts the clicked worker's own click-bounce animation and reports whether the click
// should spawn a coin burst; returns false while that specific worker is still on
// cooldown, so rapid clicks on it can't pile up coins (clicking a different worker on
// the same floor is unaffected)
export function clickWorker(
  floor: Floor,
  workerIndex: number,
  now: number,
): boolean {
  const walker = getFloorWorkers(floor, now).walkers[workerIndex];
  if (!walker) return false;
  if (now - walker.clickedAt < CLICK_COOLDOWN_MS) return false;
  walker.clickedAt = now;
  return true;
}

// on-screen (floor-local) center of one of a floor's workers, for aiming a coin burst
// at it; null if it hasn't been drawn yet (shouldn't happen once unlocked)
export function getWorkerCenter(
  floor: Floor,
  workerIndex: number,
): { x: number; y: number } | null {
  const walker = floorWorkers.get(floor)?.walkers[workerIndex];
  if (!walker) return null;
  return { x: walker.x, y: WORKER_FEET_Y - RENDER_H / 2 };
}

// on-screen (floor-local) center of every currently-boosted worker on the floor, so
// the floating-coin animation only plays at the ones actually boosted
export function getBoostedWorkerCenters(
  floor: Floor,
  now: number,
): { x: number; y: number }[] {
  const state = floorWorkers.get(floor);
  if (!state) return [];
  const y = WORKER_FEET_Y - RENDER_H / 2;
  return state.walkers
    .map((w, i) => ({ x: w.x, y, boosted: isBoosted(floor, i, now) }))
    .filter((w) => w.boosted)
    .map(({ x, y }) => ({ x, y }));
}

// one recolored frame per (frame, tintIndex) pair is built once and reused forever
// after that — cheap since it's at most 5 frames * THEME_COLORS.length canvases
const recoloredFrameCache = new Map<string, HTMLCanvasElement>();

// crops one frame out of the base sprite onto its own canvas, then recolors it via
// the canvas 'hue' blend mode (shifts hue only, keeping the art's own
// shading/highlights) tinted to THEME_COLORS[tintIndex]. The 'hue' blend mode
// ignores destination alpha when compositing, so it would otherwise paint a solid
// colored box over the frame's transparent padding too — 'destination-in' with the
// original frame re-masks the result back down to the cat's actual silhouette.
function getRecoloredFrame(
  frame: number,
  tintIndex: number,
): HTMLCanvasElement | null {
  if (!workerSprite) return null;
  const key = `${frame}:${tintIndex}`;
  const cached = recoloredFrameCache.get(key);
  if (cached) return cached;

  const frameW = workerSprite.naturalWidth / FRAME_COUNT;
  const frameH = workerSprite.naturalHeight;
  const canvas = document.createElement("canvas");
  canvas.width = frameW;
  canvas.height = frameH;
  const ctx = canvas.getContext("2d")!;

  ctx.drawImage(
    workerSprite,
    frame * frameW,
    0,
    frameW,
    frameH,
    0,
    0,
    frameW,
    frameH,
  );
  ctx.globalCompositeOperation = "hue";
  ctx.fillStyle = THEME_COLORS[tintIndex] ?? THEME_COLORS[0];
  ctx.fillRect(0, 0, frameW, frameH);
  ctx.globalCompositeOperation = "destination-in";
  ctx.drawImage(
    workerSprite,
    frame * frameW,
    0,
    frameW,
    frameH,
    0,
    0,
    frameW,
    frameH,
  );
  ctx.globalCompositeOperation = "source-over";

  recoloredFrameCache.set(key, canvas);
  return canvas;
}

// draws one worker's current walk-cycle/click-reaction frame at (cx, groundY), facing
// per direction; groundY is where its feet touch down, recolored per tintIndex
function drawFigure(
  ctx: CanvasRenderingContext2D,
  cx: number,
  groundY: number,
  direction: 1 | -1,
  frame: number,
  tintIndex: number,
): void {
  const recolored = getRecoloredFrame(frame, tintIndex);
  if (!recolored) return;
  const renderW = (RENDER_H * recolored.width) / recolored.height;

  ctx.save();
  ctx.translate(cx, groundY);
  // the jump/click pose (frame 4) is authored mirrored relative to every other
  // frame in the sheet, so it needs the opposite mirror rule to still face the
  // walker's actual direction
  const mirrored = frame === CLICK_FRAME ? direction === 1 : direction === -1;
  ctx.scale(mirrored ? -1 : 1, 1);
  ctx.drawImage(recolored, -renderW / 2, -RENDER_H, renderW, RENDER_H);
  ctx.restore();
}

// this walker's current frame: TURN_FRAMES played once right after its last
// direction turn, then the walk loop cycling cleanly from its own first frame
function walkFrameFor(walker: WalkerState, now: number): number {
  const sinceTurn = now - walker.facingSince;
  const turnDuration = TURN_FRAMES.length * TURN_FRAME_MS;
  if (sinceTurn < turnDuration) {
    return TURN_FRAMES[Math.floor(sinceTurn / TURN_FRAME_MS)];
  }
  const step =
    Math.floor((sinceTurn - turnDuration) / WALK_FRAME_MS) % WALK_FRAMES.length;
  return WALK_FRAMES[step];
}

// plays TURN_FRAMES once (turning to glance back), then holds on the last one for
// the rest of the lookingBack window
function lookBackFrameFor(walker: WalkerState, now: number): number {
  const step = Math.min(
    Math.floor((now - walker.behaviorSince) / TURN_FRAME_MS),
    TURN_FRAMES.length - 1,
  );
  return TURN_FRAMES[step];
}

// up to MAX_RENDERED_WORKERS little cats (walk-cycle sprite flipbook) that pace back
// and forth across the floor's walkable band; no-ops on locked floors (nothing to
// animate behind the grey overlay) or before the sprite sheet has finished loading
export function drawWorker(
  ctx: CanvasRenderingContext2D,
  floor: Floor,
  now: number,
): void {
  if (!floor.unlocked || !workerSprite) return;

  const state = getFloorWorkers(floor, now);
  const tintIndexes = getWorkerTintIndexes(floor);

  state.walkers.forEach((walker, i) => {
    if (now >= walker.behaviorUntil) Object.assign(walker, rollBehavior(now));

    const speed = isBoosted(floor, i, now) ? BOOSTED_WALK_SPEED : WALK_SPEED;
    // exact position never needs to be preserved (it's not persisted, and nobody
    // notices where a worker "was" after a gap) so there's no reason to cap this at
    // 0.1s — that cap was actually the cause of the visible slowdown: any redraw gap
    // over 100ms (common for a boosted/faster worker, or a floor cycling in and out
    // of gameRenderer's IntersectionObserver buffer while scrolling) got truncated to
    // a fixed 0.1s worth of movement instead of the real distance covered, making
    // motion look like it kept stuttering to a crawl. Using the real elapsed time and
    // letting the boundary clamp below catch any overshoot fixes that outright.
    const dtSeconds = Math.max((now - walker.lastUpdate) / 1000, 0);
    walker.lastUpdate = now;

    // paused/lookingBack workers stand in place — only actively walking ones move
    // or can hit a wall and reverse
    if (walker.behavior === "walking") {
      walker.x += walker.direction * speed * dtSeconds;
      if (walker.x >= FLOOR_X_MAX) {
        walker.x = FLOOR_X_MAX;
        if (walker.direction !== -1) walker.facingSince = now;
        walker.direction = -1;
      } else if (walker.x <= FLOOR_X_MIN) {
        walker.x = FLOOR_X_MIN;
        if (walker.direction !== 1) walker.facingSince = now;
        walker.direction = 1;
      }
    }

    const clickT = Math.min((now - walker.clickedAt) / CLICK_BOUNCE_MS, 1);
    const bounce = clickT < 1 ? Math.sin(clickT * Math.PI) * 14 : 0;

    // the click reaction always wins; otherwise the current idle behavior picks
    // both the frame and which way the figure actually faces on screen —
    // lookingBack renders facing the opposite of the walker's real direction
    // (glancing back over its shoulder) without changing where it's actually headed
    let frame: number;
    let renderDirection: 1 | -1;
    if (clickT < 1) {
      frame = CLICK_FRAME;
      renderDirection = walker.direction;
    } else if (walker.behavior === "paused") {
      frame = TURN_FRAMES[0]; // neutral pose, already facing the camera
      renderDirection = walker.direction;
    } else if (walker.behavior === "lookingBack") {
      frame = lookBackFrameFor(walker, now);
      renderDirection = walker.direction === -1 ? 1 : -1;
    } else {
      frame = walkFrameFor(walker, now);
      renderDirection = walker.direction;
    }

    drawFigure(
      ctx,
      walker.x,
      WORKER_FEET_Y - bounce,
      renderDirection,
      frame,
      tintIndexes[i] ?? 0,
    );
  });
}
