// Writes src/crits/badgeCrits/critData/kinds.ts: every featured crit's kind by
// its category, in catalog order. Startup reads only that list; the catalog
// itself (labels, colours, descriptions) loads after the first frame. Run by
// vite (on start and whenever critData changes) and by `npm run build`.
// Usage: node scripts/crit-kinds.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DATA = path.join(ROOT, "src/crits/badgeCrits/critData");
const OUT = path.join(DATA, "kinds.ts");

export function writeCritKinds() {
  const index = fs.readFileSync(path.join(DATA, "index.ts"), "utf8");
  const fileOf = new Map(
    [...index.matchAll(/import \{ (\w+) \} from "\.\/(\w+)";/g)].map((m) => [
      m[1],
      m[2],
    ]),
  );
  const order = [...index.matchAll(/^\s*\.\.\.(\w+),/gm)].map((m) => m[1]);
  const lines = order.map((name) => {
    const category = fileOf.get(name);
    if (!category) throw new Error(`critData/index.ts: no import for ${name}`);
    const text = fs.readFileSync(path.join(DATA, `${category}.ts`), "utf8");
    const kinds = [...text.matchAll(/^ {2}(\w+): \{/gm)].map((m) => m[1]);
    return `  ${category}: [${kinds.map((kind) => `"${kind}"`).join(", ")}],`;
  });
  const source = [
    "// generated by scripts/crit-kinds.mjs from critData/<category>.ts: don't edit",
    "// every featured crit's kind by category, in catalog order: all startup needs",
    "export const FEATURED_KINDS_BY_CATEGORY = {",
    ...lines,
    "} as const;",
    "",
  ].join("\n");
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== source) fs.writeFileSync(OUT, source);
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
)
  writeCritKinds();
