import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const AFRICAN_AND_AMERICAS_FEASTS_CRITS = {
  barbecuePot: {
    label: "Barbecue Pot",
    color: COLOR.supplyRunTan,
    image: "crits/africanAndAmericasFeasts/barbecuePot.webp",
    description: "Promotes 81% of this building's workers one perma tier",
  },
  blackBeanPlatter: {
    label: "Black Bean Platter",
    color: COLOR.starYellow,
    image: "crits/africanAndAmericasFeasts/blackBeanPlatter.webp",
    description: "Pays 32 times the highest floor's upgrade price in cash",
  },
  bluePlatterStew: {
    label: "Blue Platter Stew",
    color: COLOR.chairGiveawayBrown,
    image: "crits/africanAndAmericasFeasts/bluePlatterStew.webp",
    description: "Promotes 83.5% of this building's workers one perma tier",
  },
  blueSnapper: {
    label: "Blue Snapper",
    color: COLOR.disabledGray,
    image: "crits/africanAndAmericasFeasts/blueSnapper.webp",
    description: "Pays 33 times the highest floor's upgrade price in cash",
  },
  burritoFiesta: {
    label: "Burrito Fiesta",
    color: COLOR.amber,
    image: "crits/africanAndAmericasFeasts/burritoFiesta.webp",
    description: "Pays 34 times the highest floor's upgrade price in cash",
  },
  citrusChicken: {
    label: "Citrus Chicken",
    color: COLOR.supplyRunTan,
    image: "crits/africanAndAmericasFeasts/citrusChicken.webp",
    description: "Pays 38 times the highest floor's upgrade price in cash",
  },
  cornCobCookout: {
    label: "Corn Cob Cookout",
    color: COLOR.amber,
    image: "crits/africanAndAmericasFeasts/cornCobCookout.webp",
    description: "Promotes 87% of this building's workers one perma tier",
  },
  drumstickDuo: {
    label: "Drumstick Duo",
    color: COLOR.supplyRunTan,
    image: "crits/africanAndAmericasFeasts/drumstickDuo.webp",
    description: "Promotes 88% of this building's workers one perma tier",
  },
  fishAndWings: {
    label: "Fish And Wings",
    color: COLOR.headhunterRust,
    image: "crits/africanAndAmericasFeasts/fishAndWings.webp",
    description: "Promotes 89% of this building's workers one perma tier",
  },
  limeTacoPlate: {
    label: "Lime Taco Plate",
    color: COLOR.gold,
    image: "crits/africanAndAmericasFeasts/limeTacoPlate.webp",
    description: "Promotes 91.5% of this building's workers one perma tier",
  },
  lobsterCrown: {
    label: "Lobster Crown",
    color: COLOR.headhunterRust,
    image: "crits/africanAndAmericasFeasts/lobsterCrown.webp",
    description: "Promotes 92% of this building's workers one perma tier",
  },
  lobsterTail: {
    label: "Lobster Tail",
    color: COLOR.gold,
    image: "crits/africanAndAmericasFeasts/lobsterTail.webp",
    description: "Pays 65 times the highest floor's upgrade price in cash",
  },
  okraStew: {
    label: "Okra Stew",
    color: COLOR.headhunterRust,
    image: "crits/africanAndAmericasFeasts/okraStew.webp",
    description: "Pays 67 times the highest floor's upgrade price in cash",
  },
  pickleAndSteakBoard: {
    label: "Pickle And Steak Board",
    color: COLOR.chairGiveawayBrown,
    image: "crits/africanAndAmericasFeasts/pickleAndSteakBoard.webp",
    description: "Pays 69 times the highest floor's upgrade price in cash",
  },
  plantainPlatter: {
    label: "Plantain Platter",
    color: COLOR.gold,
    image: "crits/africanAndAmericasFeasts/plantainPlatter.webp",
    description: "Spreads 80 free upgrades over this floor and the ones below",
  },
  salmonGreens: {
    label: "Salmon Greens",
    color: COLOR.starYellow,
    image: "crits/africanAndAmericasFeasts/salmonGreens.webp",
    description: "Promotes 96.5% of this building's workers one perma tier",
  },
  steakTacoNight: {
    label: "Steak Taco Night",
    color: COLOR.coinGold,
    image: "crits/africanAndAmericasFeasts/steakTacoNight.webp",
    description: "Promotes 98% of this building's workers one perma tier",
  },
  stuffedPastryPicnic: {
    label: "Stuffed Pastry Picnic",
    color: COLOR.starYellow,
    image: "crits/africanAndAmericasFeasts/stuffedPastryPicnic.webp",
    description: "Promotes 98.5% of this building's workers one perma tier",
  },
  stuffedRollRoast: {
    label: "Stuffed Roll Roast",
    color: COLOR.chairGiveawayBrown,
    image: "crits/africanAndAmericasFeasts/stuffedRollRoast.webp",
    description: "Pays 78 times the highest floor's upgrade price in cash",
  },
  surfAndTurfPan: {
    label: "Surf And Turf Pan",
    color: COLOR.headhunterRust,
    image: "crits/africanAndAmericasFeasts/surfAndTurfPan.webp",
    description: "Spreads 89 free upgrades over this floor and the ones below",
  },
  tacoTuesday: {
    label: "Taco Tuesday",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/africanAndAmericasFeasts/tacoTuesday.webp",
    description: "Promotes 99% of this building's workers one perma tier",
  },
  tortillaStew: {
    label: "Tortilla Stew",
    color: COLOR.chairGiveawayBrown,
    image: "crits/africanAndAmericasFeasts/tortillaStew.webp",
    description: "Pays 80 times the highest floor's upgrade price in cash",
  },
  twinLobsters: {
    label: "Twin Lobsters",
    color: COLOR.headhunterRust,
    image: "crits/africanAndAmericasFeasts/twinLobsters.webp",
    description: "Spreads 91 free upgrades over this floor and the ones below",
  },
  umbrellaDrink: {
    label: "Umbrella Drink",
    color: COLOR.amberMuted,
    image: "crits/africanAndAmericasFeasts/umbrellaDrink.webp",
    description: "Pays 81 times the highest floor's upgrade price in cash",
  },
  acaiBoard: {
    label: "Acai Board",
    color: COLOR.chairGiveawayBrown,
    image: "crits/africanAndAmericasFeasts/acaiBoard.webp",
    description: "Pays 83 times the highest floor's upgrade price in cash",
  },
  ebaAndOkra: {
    label: "Eba And Okra",
    color: COLOR.supplyRunTan,
    image: "crits/africanAndAmericasFeasts/ebaAndOkra.webp",
    description: "Spreads 98 free upgrades over this floor and the ones below",
  },
  feijoadaFiesta: {
    label: "Feijoada Fiesta",
    color: COLOR.chairGiveawayBrown,
    image: "crits/africanAndAmericasFeasts/feijoadaFiesta.webp",
    description: "Pays 88 times the highest floor's upgrade price in cash",
  },
  fufuMound: {
    label: "Fufu Mound",
    color: COLOR.supplyRunTan,
    image: "crits/africanAndAmericasFeasts/fufuMound.webp",
    description: "Pays 89 times the highest floor's upgrade price in cash",
  },
  islandTwinFish: {
    label: "Island Twin Fish",
    color: COLOR.overflowBlue,
    image: "crits/africanAndAmericasFeasts/islandTwinFish.webp",
    description: "Spreads 102 free upgrades over this floor and the ones below",
  },
  mapleSyrupBagel: {
    label: "Maple Syrup Bagel",
    color: COLOR.headhunterRust,
    image: "crits/africanAndAmericasFeasts/mapleSyrupBagel.webp",
    description: "Spreads 104 free upgrades over this floor and the ones below",
  },
  nanaimoPoutine: {
    label: "Nanaimo Poutine",
    color: COLOR.chairGiveawayBrown,
    image: "crits/africanAndAmericasFeasts/nanaimoPoutine.webp",
    description: "Spreads 105 free upgrades over this floor and the ones below",
  },
  puffPuffSpread: {
    label: "Puff Puff Spread",
    color: COLOR.amber,
    image: "crits/africanAndAmericasFeasts/puffPuffSpread.webp",
    description: "Spreads 106 free upgrades over this floor and the ones below",
  },
  quesoFritoPlate: {
    label: "Queso Frito Plate",
    color: COLOR.starYellow,
    image: "crits/africanAndAmericasFeasts/quesoFritoPlate.webp",
    description: "Grows every unlocked floor's level by 10.1% in free upgrades",
  },
  tomatoRiceCatch: {
    label: "Tomato Rice Catch",
    color: COLOR.headhunterRust,
    image: "crits/africanAndAmericasFeasts/tomatoRiceCatch.webp",
    description: "Spreads 109 free upgrades over this floor and the ones below",
  },
  waakyePlate: {
    label: "Waakye Plate",
    color: COLOR.chairGiveawayBrown,
    image: "crits/africanAndAmericasFeasts/waakyePlate.webp",
    description: "Grows every unlocked floor's level by 10.4% in free upgrades",
  },
  wovenTrayGrill: {
    label: "Woven Tray Grill",
    color: COLOR.gold,
    image: "crits/africanAndAmericasFeasts/wovenTrayGrill.webp",
    description: "Spreads 110 free upgrades over this floor and the ones below",
  },
  suyaAndStew: {
    label: "Suya And Stew",
    color: COLOR.chairGiveawayBrown,
    image: "crits/africanAndAmericasFeasts/suyaAndStew.webp",
    description: "Grows every unlocked floor's level by 10.5% in free upgrades",
  },
} as const satisfies Record<string, FeaturedCritData>;
