import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const CHROME_GLAMOUR_CRITS = {
  chromeCrush: {
    label: "Chrome Crush",
    color: COLOR.fullHouseCrimson,
    image: "crits/chromeGlamour/chromeCrush.webp",
    description: "Boosts every worker for 49s, counting as 1 extra worker",
  },
  puckerProtocol: {
    label: "Pucker Protocol",
    color: COLOR.red,
    image: "crits/chromeGlamour/puckerProtocol.webp",
    description: "Forty-four payouts here and on the lowest-earning floor",
  },
  alloyAngel: {
    label: "Alloy Angel",
    color: COLOR.goldenHandshakeGold,
    image: "crits/chromeGlamour/alloyAngel.webp",
    description: "Two tier promotions and nineteen upgrades on the top earner",
  },
  sereneSeraph: {
    label: "Serene Seraph",
    color: COLOR.white,
    image: "crits/chromeGlamour/sereneSeraph.webp",
    description: "Fifty-one payouts on every unlocked floor",
  },
  glossyGaze: {
    label: "Glossy Gaze",
    color: COLOR.silverTicketGray,
    image: "crits/chromeGlamour/glossyGaze.webp",
    description: "Sixty-four upgrades on the highest unlocked floor",
  },
  goldenFreckles: {
    label: "Golden Freckles",
    color: COLOR.goldenTicketYellow,
    image: "crits/chromeGlamour/goldenFreckles.webp",
    description: "Adds 26s of your company's income",
  },
  mirrorBob: {
    label: "Mirror Bob",
    color: COLOR.silverTicketGray,
    image: "crits/chromeGlamour/mirrorBob.webp",
    description: "Raises the lowest-level floor to the building's top level",
  },
  liquidMetalLashes: {
    label: "Liquid Metal Lashes",
    color: COLOR.fastForwardBlue,
    image: "crits/chromeGlamour/liquidMetalLashes.webp",
    description: "Forty-six upgrades here and on the highest floor",
  },
  dripAndDazzle: {
    label: "Drip and Dazzle",
    color: COLOR.goldenHandshakeGold,
    image: "crits/chromeGlamour/dripAndDazzle.webp",
    description: "Forty-two payouts here and on the highest floor",
  },
  silverPour: {
    label: "Silver Pour",
    color: COLOR.silverTicketGray,
    image: "crits/chromeGlamour/silverPour.webp",
    description: "Raises every floor below this one to its level",
  },
  polishedPout: {
    label: "Polished Pout",
    color: COLOR.red,
    image: "crits/chromeGlamour/polishedPout.webp",
    description: "Raises the lowest-level floor to the building's top level",
  },
  loweredLenses: {
    label: "Lowered Lenses",
    color: COLOR.nightShiftIndigo,
    image: "crits/chromeGlamour/loweredLenses.webp",
    description: "Cuts every price in this building by 4.6%",
  },
  bicepBooster: {
    label: "Bicep Booster",
    color: COLOR.overflowBlue,
    image: "crits/chromeGlamour/bicepBooster.webp",
    description: "Grows this floor's level by 25.3% in free upgrades",
  },
  blueBoltFlex: {
    label: "Blue Bolt Flex",
    color: COLOR.overflowBlue,
    image: "crits/chromeGlamour/blueBoltFlex.webp",
    description: "Grows this floor's level by 25.4% in free upgrades",
  },
  chromeKnuckles: {
    label: "Chrome Knuckles",
    color: COLOR.fastForwardBlue,
    image: "crits/chromeGlamour/chromeKnuckles.webp",
    description: "Grows this floor's level by 25.5% in free upgrades",
  },
  pinkPiston: {
    label: "Pink Piston",
    color: COLOR.sameBoatCoral,
    image: "crits/chromeGlamour/pinkPiston.webp",
    description: "Grows this floor's level by 25.7% in free upgrades",
  },
  silverMechSuit: {
    label: "Silver Mech Suit",
    color: COLOR.overflowBlue,
    image: "crits/chromeGlamour/silverMechSuit.webp",
    description: "Grows this floor's level by 25.8% in free upgrades",
  },
  topazCore: {
    label: "Topaz Core",
    color: COLOR.fastForwardBlue,
    image: "crits/chromeGlamour/topazCore.webp",
    description: "Grows this floor's level by 25.9% in free upgrades",
  },
  blueBelleWave: {
    label: "Blue Belle Wave",
    color: COLOR.nightOwlIndigo,
    image: "crits/chromeGlamour/blueBelleWave.webp",
    description: "Adds 38.4% of your total income",
  },
  cherrySlit: {
    label: "Cherry Slit",
    color: COLOR.doubleDownCrimson,
    image: "crits/chromeGlamour/cherrySlit.webp",
    description: "Adds 38.5% of your total income",
  },
  cobaltPose: {
    label: "Cobalt Pose",
    color: COLOR.overflowBlue,
    image: "crits/chromeGlamour/cobaltPose.webp",
    description: "Adds 38.6% of your total income",
  },
  hourglassHips: {
    label: "Hourglass Hips",
    color: COLOR.redActive,
    image: "crits/chromeGlamour/hourglassHips.webp",
    description: "Adds 38.7% of your total income",
  },
  midnightStrapless: {
    label: "Midnight Strapless",
    color: COLOR.nightOwlIndigo,
    image: "crits/chromeGlamour/midnightStrapless.webp",
    description: "Adds 38.8% of your total income",
  },
  plumPower: {
    label: "Plum Power",
    color: COLOR.nightOwlIndigo,
    image: "crits/chromeGlamour/plumPower.webp",
    description: "Adds 39.1% of your total income",
  },
  redVelvet: {
    label: "Red Velvet",
    color: COLOR.doubleDownCrimson,
    image: "crits/chromeGlamour/redVelvet.webp",
    description: "Adds 39.3% of your total income",
  },
  rougeNoir: {
    label: "Rouge Noir",
    color: COLOR.doubleDownCrimson,
    image: "crits/chromeGlamour/rougeNoir.webp",
    description: "Adds 39.4% of your total income",
  },
  royalDrape: {
    label: "Royal Drape",
    color: COLOR.overflowBlue,
    image: "crits/chromeGlamour/royalDrape.webp",
    description: "Adds 39.5% of your total income",
  },
  rubyBallgown: {
    label: "Ruby Ballgown",
    color: COLOR.doubleDownCrimson,
    image: "crits/chromeGlamour/rubyBallgown.webp",
    description: "Adds 39.6% of your total income",
  },
  tealTress: {
    label: "Teal Tress",
    color: COLOR.overflowBlue,
    image: "crits/chromeGlamour/tealTress.webp",
    description: "Adds 39.8% of your total income",
  },
  twilightGlam: {
    label: "Twilight Glam",
    color: COLOR.overflowBlue,
    image: "crits/chromeGlamour/twilightGlam.webp",
    description: "Adds 39.9% of your total income",
  },
  twoToneTease: {
    label: "Two Tone Tease",
    color: COLOR.overflowBlue,
    image: "crits/chromeGlamour/twoToneTease.webp",
    description: "Adds 40% of your total income",
  },
  violetFlex: {
    label: "Violet Flex",
    color: COLOR.nightShiftIndigo,
    image: "crits/chromeGlamour/violetFlex.webp",
    description: "Adds 40.1% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
