import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const COURTSHIP_AND_DATES_CRITS = {
  airKissAssets: {
    label: "Air Kiss Assets",
    color: COLOR.headhunterRust,
    image: "crits/courtshipAndDates/airKissAssets.webp",
    description: "Arms the lowest-level floor's next click as an x5 crit",
  },
  blownKissBonus: {
    label: "Blown Kiss Bonus",
    color: COLOR.supplyRunTan,
    image: "crits/courtshipAndDates/blownKissBonus.webp",
    description: "Raises the lowest-level floor to the building's top level",
  },
  crushCapital: {
    label: "Crush Capital",
    color: COLOR.teamBuildingCoral,
    image: "crits/courtshipAndDates/crushCapital.webp",
    description: "Cuts every price in this building by 2.3%",
  },
  cupidsCommission: {
    label: "Cupids Commission",
    color: COLOR.springCleaningMint,
    image: "crits/courtshipAndDates/cupidsCommission.webp",
    description: "Adds 45s of your company's income",
  },
  goodnightKissGains: {
    label: "Goodnight Kiss Gains",
    color: COLOR.fastForwardBlue,
    image: "crits/courtshipAndDates/goodnightKissGains.webp",
    description: "Repeats the crit above and below, 64% chance to keep spreading",
  },
  heartThrobHoldings: {
    label: "Heart Throb Holdings",
    color: COLOR.teaBreakBrown,
    image: "crits/courtshipAndDates/heartThrobHoldings.webp",
    description: "One tier promotion and nine upgrades here",
  },
  kissCamCashout: {
    label: "Kiss Cam Cashout",
    color: COLOR.coinGold,
    image: "crits/courtshipAndDates/kissCamCashout.webp",
    description: "Arms this floor's next click as an x5 crit",
  },
  kissingBoothBank: {
    label: "Kissing Booth Bank",
    color: COLOR.doubleDownCrimson,
    image: "crits/courtshipAndDates/kissingBoothBank.webp",
    description: "Raises alternating floors to the building's top level",
  },
  loveLetterLedger: {
    label: "Love Letter Ledger",
    color: COLOR.coinGold,
    image: "crits/courtshipAndDates/loveLetterLedger.webp",
    description: "One tier promotion and six upgrades here",
  },
  mistletoeMargin: {
    label: "Mistletoe Margin",
    color: COLOR.coinGold,
    image: "crits/courtshipAndDates/mistletoeMargin.webp",
    description: "Cuts every price in this building by 1.4%",
  },
  rosyCheekReturns: {
    label: "Rosy Cheek Returns",
    color: COLOR.teaBreakBrown,
    image: "crits/courtshipAndDates/rosyCheekReturns.webp",
    description: "Hires a free manager on alternating floors",
  },
  sealedWithAKiss: {
    label: "Sealed With A Kiss",
    color: COLOR.springCleaningMint,
    image: "crits/courtshipAndDates/sealedWithAKiss.webp",
    description: "Repeats the crit on the floor above, 26% chance to keep climbing",
  },
  smittenSavings: {
    label: "Smitten Savings",
    color: COLOR.rainCheckBlue,
    image: "crits/courtshipAndDates/smittenSavings.webp",
    description: "One tier promotion and seven upgrades here",
  },
  sweetheartSurplus: {
    label: "Sweetheart Surplus",
    color: COLOR.chairGiveawayBrown,
    image: "crits/courtshipAndDates/sweetheartSurplus.webp",
    description: "Raises the lowest-level floor to the building's top level",
  },
  lovebirdLoot: {
    label: "Lovebird Loot",
    color: COLOR.amberMuted,
    image: "crits/courtshipAndDates/lovebirdLoot.webp",
    description: "Cuts every price in this building by 10.2%",
  },
  cobaltCrush: {
    label: "Cobalt Crush",
    color: COLOR.bullMarketGreen,
    image: "crits/courtshipAndDates/cobaltCrush.webp",
    description: "Adds 20.8% of your total income",
  },
  crownedCrush: {
    label: "Crowned Crush",
    color: COLOR.moneyGreen,
    image: "crits/courtshipAndDates/crownedCrush.webp",
    description: "Repeats the crit on the floor above, 93% chance to keep climbing",
  },
  limelightKiss: {
    label: "Limelight Kiss",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/courtshipAndDates/limelightKiss.webp",
    description: "Repeats the crit on the floor below, 94% chance to keep falling",
  },
  thirdWheelWindfall: {
    label: "Third Wheel Windfall",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/courtshipAndDates/thirdWheelWindfall.webp",
    description: "Adds 21.5% of your total income",
  },
  crushHour: {
    label: "Crush Hour",
    color: COLOR.amberMuted,
    image: "crits/courtshipAndDates/crushHour.webp",
    description: "Cuts every price in this building by 20.9%",
  },
  vestedInterest: {
    label: "Vested Interest",
    color: COLOR.amberMuted,
    image: "crits/courtshipAndDates/vestedInterest.webp",
    description: "Cuts every price in this building by 21.2%",
  },
  slowDanceDividend: {
    label: "Slow Dance Dividend",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/courtshipAndDates/slowDanceDividend.webp",
    description: "Fifty-four instant payouts on this floor",
  },
  tangoTycoons: {
    label: "Tango Tycoons",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/courtshipAndDates/tangoTycoons.webp",
    description: "Fifty-four free upgrades on this floor",
  },
  tieBreakerBonus: {
    label: "Tie Breaker Bonus",
    color: COLOR.amberMuted,
    image: "crits/courtshipAndDates/tieBreakerBonus.webp",
    description: "Fifty-six instant payouts on this floor",
  },
  twoStepTreasury: {
    label: "Two Step Treasury",
    color: COLOR.amberMuted,
    image: "crits/courtshipAndDates/twoStepTreasury.webp",
    description: "Adds 25% of your total income",
  },
  buckleUp: {
    label: "Buckle Up",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/courtshipAndDates/buckleUp.webp",
    description: "Spreads 54 free upgrades over this floor and the ones below",
  },
  coralCrush: {
    label: "Coral Crush",
    color: COLOR.sameBoatCoral,
    image: "crits/courtshipAndDates/coralCrush.webp",
    description: "Pays 29 times this floor's upgrade price in cash",
  },
  cottonCandyKiss: {
    label: "Cotton Candy Kiss",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/courtshipAndDates/cottonCandyKiss.webp",
    description: "Grows this floor's level by 8.3% in free upgrades",
  },
  giggleFit: {
    label: "Giggle Fit",
    color: COLOR.sameBoatCoral,
    image: "crits/courtshipAndDates/giggleFit.webp",
    description: "Spreads 19 free upgrades over this floor and the ones below",
  },
  limeCrush: {
    label: "Lime Crush",
    color: COLOR.gold,
    image: "crits/courtshipAndDates/limeCrush.webp",
    description: "Spreads 21 free upgrades over this floor and the ones below",
  },
  smoochDelivery: {
    label: "Smooch Delivery",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/courtshipAndDates/smoochDelivery.webp",
    description: "Spreads 21 free upgrades over the lowest-level floors",
  },
} as const satisfies Record<string, FeaturedCritData>;
