import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const DEMON_GIRLS_CRITS = {
  hellfireHeartbreaker: {
    label: "Hellfire Heartbreaker",
    color: COLOR.fullHouseCrimson,
    image: "crits/demonGirls/hellfireHeartbreaker.webp",
    description: "One tier promotion and forty-two upgrades here",
  },
  spadeTailSass: {
    label: "Spade Tail Sass",
    color: COLOR.red,
    image: "crits/demonGirls/spadeTailSass.webp",
    description: "Sixty-eight free upgrades on this floor",
  },
  sinfullySolvent: {
    label: "Sinfully Solvent",
    color: COLOR.royalFlushPurple,
    image: "crits/demonGirls/sinfullySolvent.webp",
    description: "Adds 5.1% of your total income",
  },
  slyStack: {
    label: "Sly Stack",
    color: COLOR.bonusRoundGold,
    image: "crits/demonGirls/slyStack.webp",
    description: "Sixty-six instant payouts on this floor",
  },
  lavenderLounge: {
    label: "Lavender Lounge",
    color: COLOR.peppermintPink,
    image: "crits/demonGirls/lavenderLounge.webp",
    description: "Sixty-six upgrades on the top earner",
  },
  pitchforkCharmer: {
    label: "Pitchfork Charmer",
    color: COLOR.doubleDownCrimson,
    image: "crits/demonGirls/pitchforkCharmer.webp",
    description: "Arms every floor's next click as an x5 crit",
  },
  scarletSaunter: {
    label: "Scarlet Saunter",
    color: COLOR.fireDrillRed,
    image: "crits/demonGirls/scarletSaunter.webp",
    description: "Cuts every price in this building by 6.5%",
  },
  forkFlourish: {
    label: "Fork Flourish",
    color: COLOR.goldStandardAmber,
    image: "crits/demonGirls/forkFlourish.webp",
    description: "Caps every floor's income timer at 0.5s for 15s",
  },
  brimstoneBelle: {
    label: "Brimstone Belle",
    color: COLOR.autumnSaleAmber,
    image: "crits/demonGirls/brimstoneBelle.webp",
    description: "Fifty payouts on every unlocked floor",
  },
  flapperFlames: {
    label: "Flapper Flames",
    color: COLOR.amberMuted,
    image: "crits/demonGirls/flapperFlames.webp",
    description: "Boosts every worker for 71s, counting as 2 extra workers",
  },
  sootAndSequins: {
    label: "Soot and Sequins",
    color: COLOR.nightShiftIndigo,
    image: "crits/demonGirls/sootAndSequins.webp",
    description:
      "Repeats the crit above and below, 45% chance to keep spreading",
  },
  impeccableTaste: {
    label: "Impeccable Taste",
    color: COLOR.mysticTeal,
    image: "crits/demonGirls/impeccableTaste.webp",
    description: "Fifty-eight payouts on alternating floors",
  },
  heartsAflame: {
    label: "Hearts Aflame",
    color: COLOR.grandOpeningRose,
    image: "crits/demonGirls/heartsAflame.webp",
    description: "Boosts every worker for 35s",
  },
  finePrintFiend: {
    label: "Fine Print Fiend",
    color: COLOR.espressoShotBrown,
    image: "crits/demonGirls/finePrintFiend.webp",
    description:
      "Repeats the crit on the floor above, 57% chance to keep climbing",
  },
  signedInScarlet: {
    label: "Signed in Scarlet",
    color: COLOR.fullHouseCrimson,
    image: "crits/demonGirls/signedInScarlet.webp",
    description:
      "Repeats the crit above and below, 46% chance to keep spreading",
  },
  termsAndTemptations: {
    label: "Terms and Temptations",
    color: COLOR.chairGiveawayBrown,
    image: "crits/demonGirls/termsAndTemptations.webp",
    description: "Sixty-three payouts on the highest unlocked floor",
  },
  hotTake: {
    label: "Hot Take",
    color: COLOR.red,
    image: "crits/demonGirls/hotTake.webp",
    description: "Unlocks the next floor for free",
  },
  coinFlambe: {
    label: "Coin Flambe",
    color: COLOR.goldenTicketYellow,
    image: "crits/demonGirls/coinFlambe.webp",
    description: "Adds 13.8% of your total income",
  },
  rivetRebel: {
    label: "Rivet Rebel",
    color: COLOR.silverTicketGray,
    image: "crits/demonGirls/rivetRebel.webp",
    description: "Fifty-eight upgrades rolling down the floors below",
  },
  flickerGrin: {
    label: "Flicker Grin",
    color: COLOR.autumnSaleAmber,
    image: "crits/demonGirls/flickerGrin.webp",
    description: "Sixty-eight payouts on the lowest-earning floor",
  },
  smolderEyes: {
    label: "Smolder Eyes",
    color: COLOR.goldStandardAmber,
    image: "crits/demonGirls/smolderEyes.webp",
    description: "Hires 1 free worker on every unlocked floor",
  },
  crimsonGlare: {
    label: "Crimson Glare",
    color: COLOR.doubleDownCrimson,
    image: "crits/demonGirls/crimsonGlare.webp",
    description: "Hires a free manager on alternating floors",
  },
  midnightSideEye: {
    label: "Midnight Side-Eye",
    color: COLOR.nightShiftIndigo,
    image: "crits/demonGirls/midnightSideEye.webp",
    description: "Unlocks the next floor for free",
  },
  amberStare: {
    label: "Amber Stare",
    color: COLOR.goldenHandshakeGold,
    image: "crits/demonGirls/amberStare.webp",
    description: "Hires 1 free worker on every unlocked floor",
  },
  brimstoneBonus: {
    label: "Brimstone Bonus",
    color: COLOR.fullHouseCrimson,
    image: "crits/demonGirls/brimstoneBonus.webp",
    description: "Boosts this floor's workers for 28s",
  },
  devilishDeal: {
    label: "Devilish Deal",
    color: COLOR.doubleDownCrimson,
    image: "crits/demonGirls/devilishDeal.webp",
    description: "Arms the highest floor's next click as an x5 crit",
  },
  hellfireHustle: {
    label: "Hellfire Hustle",
    color: COLOR.red,
    image: "crits/demonGirls/hellfireHustle.webp",
    description: "Boosts every worker for 22s",
  },
  hornedHedge: {
    label: "Horned Hedge",
    color: COLOR.fullHouseCrimson,
    image: "crits/demonGirls/hornedHedge.webp",
    description: "Hires 1 free worker on this floor",
  },
  infernalInvoice: {
    label: "Infernal Melons",
    color: COLOR.fullHouseCrimson,
    image: "crits/demonGirls/infernalInvoice.webp",
    description:
      "Repeats the crit on the floor below, 11% chance to keep falling",
  },
  pitchforkProfits: {
    label: "Pitchfork Profits",
    color: COLOR.doubleDownCrimson,
    image: "crits/demonGirls/pitchforkProfits.webp",
    description: "One tier promotion and six upgrades here",
  },
  sinfulSurplus: {
    label: "Sinful Surplus",
    color: COLOR.doubleDownCrimson,
    image: "crits/demonGirls/sinfulSurplus.webp",
    description: "Cuts every price in this building by 1%",
  },
  soulContractClause: {
    label: "Soul Contract Clause",
    color: COLOR.redActive,
    image: "crits/demonGirls/soulContractClause.webp",
    description: "Adds 5s of your company's income",
  },
  underworldUpsell: {
    label: "Underworld Upsell",
    color: COLOR.redActive,
    image: "crits/demonGirls/underworldUpsell.webp",
    description: "Raises the lowest-level floor to the building's top level",
  },
  blueDevil: {
    label: "Blue Devil",
    color: COLOR.internSkyBlue,
    image: "crits/demonGirls/blueDevil.webp",
    description: "Grows every unlocked floor's level by 4.1% in free upgrades",
  },
  brimstoneBiceps: {
    label: "Brimstone Biceps",
    color: COLOR.doubleDownCrimson,
    image: "crits/demonGirls/brimstoneBiceps.webp",
    description: "Pays 5 times every unlocked floor's upgrade price in cash",
  },
  devilMayKiss: {
    label: "Devil May Kiss",
    color: COLOR.doubleDownCrimson,
    image: "crits/demonGirls/devilMayKiss.webp",
    description: "Grows every unlocked floor's level by 4.2% in free upgrades",
  },
  sinnersPlea: {
    label: "Sinners Plea",
    color: COLOR.redActive,
    image: "crits/demonGirls/sinnersPlea.webp",
    description: "Spreads 51 free upgrades over this floor and the ones below",
  },
  tealTemptress: {
    label: "Teal Temptress",
    color: COLOR.fullHouseCrimson,
    image: "crits/demonGirls/tealTemptress.webp",
    description: "Pays 16 times the highest floor's upgrade price in cash",
  },
  hornsAndBraids: {
    label: "Horns and Braids",
    color: COLOR.overflowBlue,
    image: "crits/demonGirls/hornsAndBraids.webp",
    description: "Grows every unlocked floor's level by 6.1% in free upgrades",
  },
  lipstickDevils: {
    label: "Lipstick Devils",
    color: COLOR.fullHouseCrimson,
    image: "crits/demonGirls/lipstickDevils.webp",
    description: "Spreads 96 free upgrades over the lowest-level floors",
  },
  flexingFiends: {
    label: "Flexing Fiends",
    color: COLOR.fullHouseCrimson,
    image: "crits/demonGirls/flexingFiends.webp",
    description: "Pays 51 times this floor's upgrade price in cash",
  },
  demonHandshake: {
    label: "Demon Handshake",
    color: COLOR.overflowBlue,
    image: "crits/demonGirls/demonHandshake.webp",
    description: "Grows this floor's level by 13.1% in free upgrades",
  },
  ashAndEmber: {
    label: "Ash and Ember",
    color: COLOR.doubleDownCrimson,
    image: "crits/demonGirls/ashAndEmber.webp",
    description: "Spreads 97 free upgrades over the lowest-level floors",
  },
  infernalToeHold: {
    label: "Infernal Toe Hold",
    color: COLOR.doubleDownCrimson,
    image: "crits/demonGirls/infernalToeHold.webp",
    description: "Pays 22 times the highest floor's upgrade price in cash",
  },
} as const satisfies Record<string, FeaturedCritData>;
