import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const DUO_HAIRSTYLES_CRITS = {
  baldAndBraided: {
    label: "Bald And Braided",
    color: COLOR.overflowBlue,
    image: "crits/duoHairstyles/baldAndBraided.webp",
    description: "Promotes 25% of this floor's workers two perma tiers",
  },
  blondeBuzzcut: {
    label: "Blonde Buzzcut",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/blondeBuzzcut.webp",
    description: "Promotes 5.5% of this building's workers one perma tier",
  },
  braidAndBob: {
    label: "Braid And Bob",
    color: COLOR.overflowBlue,
    image: "crits/duoHairstyles/braidAndBob.webp",
    description: "Promotes 6% of this building's workers one perma tier",
  },
  braidedPair: {
    label: "Braided Pair",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/braidedPair.webp",
    description: "Promotes 26% of this floor's workers two perma tiers",
  },
  bunAndBangs: {
    label: "Bun And Bangs",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/bunAndBangs.webp",
    description: "Promotes 80% of this building's workers one perma tier",
  },
  buzzAndBraid: {
    label: "Buzz And Braid",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/buzzAndBraid.webp",
    description: "Promotes 60.5% of this floor's workers two perma tiers",
  },
  chromeDomes: {
    label: "Chrome Domes",
    color: COLOR.teal,
    image: "crits/duoHairstyles/chromeDomes.webp",
    description: "Promotes 10% of this building's workers one perma tier",
  },
  cueBallCuties: {
    label: "Cue Ball Cuties",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/cueBallCuties.webp",
    description: "Promotes 11.5% of this building's workers one perma tier",
  },
  darkBobTwins: {
    label: "Dark Bob Twins",
    color: COLOR.peppermintPink,
    image: "crits/duoHairstyles/darkBobTwins.webp",
    description: "Promotes 28.5% of this floor's workers two perma tiers",
  },
  hairGelPair: {
    label: "Hair Gel Pair",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/hairGelPair.webp",
    description: "Promotes 20.5% of this building's workers one perma tier",
  },
  highPonytailPair: {
    label: "High Ponytail Pair",
    color: COLOR.rainCheckBlue,
    image: "crits/duoHairstyles/highPonytailPair.webp",
    description: "Promotes 21.5% of this building's workers one perma tier",
  },
  indigoUpdo: {
    label: "Indigo Updo",
    color: COLOR.overflowBlue,
    image: "crits/duoHairstyles/indigoUpdo.webp",
    description: "Promotes 41.5% of this floor's workers two perma tiers",
  },
  mirrorPixies: {
    label: "Mirror Pixies",
    color: COLOR.overflowBlue,
    image: "crits/duoHairstyles/mirrorPixies.webp",
    description: "Promotes 25.5% of this building's workers one perma tier",
  },
  mohawkAndBraid: {
    label: "Mohawk And Braid",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/mohawkAndBraid.webp",
    description: "Promotes 45.5% of this floor's workers two perma tiers",
  },
  mohawkMates: {
    label: "Mohawk Mates",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/mohawkMates.webp",
    description: "Promotes 26% of this building's workers one perma tier",
  },
  neonBraids: {
    label: "Neon Braids",
    color: COLOR.sameBoatCoral,
    image: "crits/duoHairstyles/neonBraids.webp",
    description: "Promotes 26.5% of this building's workers one perma tier",
  },
  pixieAndPlait: {
    label: "Pixie And Plait",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/pixieAndPlait.webp",
    description: "Promotes 49.5% of this floor's workers two perma tiers",
  },
  pixieAndPonytail: {
    label: "Pixie And Ponytail",
    color: COLOR.overflowBlue,
    image: "crits/duoHairstyles/pixieAndPonytail.webp",
    description: "Promotes 35% of this building's workers one perma tier",
  },
  platinumPixie: {
    label: "Platinum Pixie",
    color: COLOR.springCleaningMint,
    image: "crits/duoHairstyles/platinumPixie.webp",
    description: "Promotes 36.5% of this building's workers one perma tier",
  },
  slickBackDuo: {
    label: "Slick Back Duo",
    color: COLOR.rainCheckBlue,
    image: "crits/duoHairstyles/slickBackDuo.webp",
    description: "Promotes 40% of this building's workers one perma tier",
  },
  snowyBob: {
    label: "Snowy Bob",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/snowyBob.webp",
    description: "Promotes 40.5% of this building's workers one perma tier",
  },
  tealPixie: {
    label: "Teal Pixie",
    color: COLOR.overflowBlue,
    image: "crits/duoHairstyles/tealPixie.webp",
    description: "Promotes 42.5% of this building's workers one perma tier",
  },
  undercutBraidDuo: {
    label: "Undercut Braid Duo",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/undercutBraidDuo.webp",
    description: "Promotes 44% of this building's workers one perma tier",
  },
  baldAndSidecut: {
    label: "Bald And Sidecut",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/baldAndSidecut.webp",
    description: "Promotes 69.5% of this floor's workers two perma tiers",
  },
  boxBraidsBlush: {
    label: "Box Braids Blush",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/boxBraidsBlush.webp",
    description: "Promotes 55.5% of this building's workers one perma tier",
  },
  buzzcutTwins: {
    label: "Buzzcut Twins",
    color: COLOR.rainCheckBlue,
    image: "crits/duoHairstyles/buzzcutTwins.webp",
    description: "Promotes 56% of this building's workers one perma tier",
  },
  jetBlackLocks: {
    label: "Jet Black Locks",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/jetBlackLocks.webp",
    description: "Promotes 56.5% of this building's workers one perma tier",
  },
  limePonytail: {
    label: "Lime Ponytail",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/limePonytail.webp",
    description: "Promotes 57% of this building's workers one perma tier",
  },
  sapphirePixie: {
    label: "Sapphire Pixie",
    color: COLOR.nightOwlIndigo,
    image: "crits/duoHairstyles/sapphirePixie.webp",
    description: "Promotes 58% of this building's workers one perma tier",
  },
  spikyCropBraid: {
    label: "Spiky Crop Braid",
    color: COLOR.overflowBlue,
    image: "crits/duoHairstyles/spikyCropBraid.webp",
    description: "Promotes 58.5% of this building's workers one perma tier",
  },
  tealStreakHair: {
    label: "Teal Streak Hair",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/tealStreakHair.webp",
    description: "Promotes 81.5% of this floor's workers two perma tiers",
  },
  topKnotDuo: {
    label: "Top Knot Duo",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/topKnotDuo.webp",
    description: "Promotes 82% of this floor's workers two perma tiers",
  },
  yellowMane: {
    label: "Yellow Mane",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/yellowMane.webp",
    description: "Promotes 68% of this floor's workers two perma tiers",
  },
  turtleneckBob: {
    label: "Turtleneck Bob",
    color: COLOR.fastForwardBlue,
    image: "crits/duoHairstyles/turtleneckBob.webp",
    description: "Promotes 59.5% of this building's workers one perma tier",
  },
} as const satisfies Record<string, FeaturedCritData>;
