import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const FANTASY_AND_WORSHIP_CRITS = {
  hellfireHug: {
    label: "Hellfire Hug",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyAndWorship/hellfireHug.webp",
    description: "Cuts every price in this building by 17.3%",
  },
  hornedHeartbreakers: {
    label: "Horned Heartbreakers",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyAndWorship/hornedHeartbreakers.webp",
    description: "Boosts every worker for 127s, counting as 3 extra workers",
  },
  shoulderDevilDuo: {
    label: "Shoulder Devil Duo",
    color: COLOR.fullHouseCrimson,
    image: "crits/fantasyAndWorship/shoulderDevilDuo.webp",
    description: "Boosts every worker for 135s, counting as 3 extra workers",
  },
  goblinGluteGains: {
    label: "Goblin Glute Gains",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyAndWorship/goblinGluteGains.webp",
    description: "Cuts every price in this building by 20.3%",
  },
  greenKisser: {
    label: "Green Kisser",
    color: COLOR.gold,
    image: "crits/fantasyAndWorship/greenKisser.webp",
    description: "One hundred and ten instant payouts on this floor",
  },
  cheekyGoblin: {
    label: "Cheeky Goblin",
    color: COLOR.moneyGreen,
    image: "crits/fantasyAndWorship/cheekyGoblin.webp",
    description: "Pays 2 times every unlocked floor's upgrade price in cash",
  },
  evergreenGains: {
    label: "Evergreen Gains",
    color: COLOR.rainCheckBlue,
    image: "crits/fantasyAndWorship/evergreenGains.webp",
    description: "Pays 13 times this floor's upgrade price in cash",
  },
  forestFlirt: {
    label: "Forest Flirt",
    color: COLOR.dressCodeGreen,
    image: "crits/fantasyAndWorship/forestFlirt.webp",
    description: "Grows every unlocked floor's level by 4.4% in free upgrades",
  },
  goblinSmirk: {
    label: "Goblin Smirk",
    color: COLOR.gold,
    image: "crits/fantasyAndWorship/goblinSmirk.webp",
    description: "Spreads 84 free upgrades over the lowest-level floors",
  },
  pointedLook: {
    label: "Pointed Look",
    color: COLOR.coinGold,
    image: "crits/fantasyAndWorship/pointedLook.webp",
    description: "Spreads 86 free upgrades over the lowest-level floors",
  },
  axeDeduction: {
    label: "Axe Deduction",
    color: COLOR.chairGiveawayBrown,
    image: "crits/fantasyAndWorship/axeDeduction.webp",
    description: "Pays 11 times every unlocked floor's upgrade price in cash",
  },
  chopChop: {
    label: "Chop Chop",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fantasyAndWorship/chopChop.webp",
    description: "Grows this floor's level by 12.9% in free upgrades",
  },
  norseCode: {
    label: "Norse Code",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fantasyAndWorship/norseCode.webp",
    description: "Spreads 94 free upgrades over the lowest-level floors",
  },
  plunderPose: {
    label: "Plunder Pose",
    color: COLOR.chairGiveawayBrown,
    image: "crits/fantasyAndWorship/plunderPose.webp",
    description: "Pays 27 times this floor's upgrade price in cash",
  },
  raidDay: {
    label: "Raid Day",
    color: COLOR.amberMuted,
    image: "crits/fantasyAndWorship/raidDay.webp",
    description: "Grows this floor's level by 13% in free upgrades",
  },
  shieldMaiden: {
    label: "Shield Maiden",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fantasyAndWorship/shieldMaiden.webp",
    description: "Spreads 95 free upgrades over the lowest-level floors",
  },
  valhallaVenture: {
    label: "Valhalla Venture",
    color: COLOR.supplyRunTan,
    image: "crits/fantasyAndWorship/valhallaVenture.webp",
    description: "Pays 21 times the highest floor's upgrade price in cash",
  },
  orcMatronHomage: {
    label: "Orc Matron Homage",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyAndWorship/orcMatronHomage.webp",
    description: "Pays 57 times this floor's upgrade price in cash",
  },
  goldenBraidIdol: {
    label: "Golden Braid Idol",
    color: COLOR.summerSaleOrange,
    image: "crits/fantasyAndWorship/goldenBraidIdol.webp",
    description: "Pays 58 times this floor's upgrade price in cash",
  },
  goblinAcolyte: {
    label: "Goblin Acolyte",
    color: COLOR.amberMuted,
    image: "crits/fantasyAndWorship/goblinAcolyte.webp",
    description: "Grows every unlocked floor's level by 6.4% in free upgrades",
  },
  adoringGaze: {
    label: "Adoring Gaze",
    color: COLOR.summerSaleOrange,
    image: "crits/fantasyAndWorship/adoringGaze.webp",
    description: "Pays 59 times this floor's upgrade price in cash",
  },
  kneepadOrcSovereign: {
    label: "Kneepad Orc Sovereign",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyAndWorship/kneepadOrcSovereign.webp",
    description: "Grows this floor's level by 13.2% in free upgrades",
  },
  loinclothDeity: {
    label: "Loincloth Deity",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyAndWorship/loinclothDeity.webp",
    description: "Spreads 35 free upgrades over this floor and the ones below",
  },
  mountainGoddess: {
    label: "Mountain Goddess",
    color: COLOR.amberMuted,
    image: "crits/fantasyAndWorship/mountainGoddess.webp",
    description: "Pays 60 times this floor's upgrade price in cash",
  },
  armoredOrcIdol: {
    label: "Armored Orc Idol",
    color: COLOR.luckyCloverGreen,
    image: "crits/fantasyAndWorship/armoredOrcIdol.webp",
    description: "Grows every unlocked floor's level by 6.5% in free upgrades",
  },
  tealTribute: {
    label: "Teal Tribute",
    color: COLOR.amberMuted,
    image: "crits/fantasyAndWorship/tealTribute.webp",
    description: "Grows this floor's level by 9.4% in free upgrades",
  },
  armsCrossedGoddess: {
    label: "Arms Crossed Goddess",
    color: COLOR.amberMuted,
    image: "crits/fantasyAndWorship/armsCrossedGoddess.webp",
    description: "Spreads 41 free upgrades over the lowest-level floors",
  },
  cherryTopColossus: {
    label: "Cherry Top Colossus",
    color: COLOR.amberMuted,
    image: "crits/fantasyAndWorship/cherryTopColossus.webp",
    description: "Pays 71 times this floor's upgrade price in cash",
  },
  coralCropVeneration: {
    label: "Coral Crop Veneration",
    color: COLOR.sameBoatCoral,
    image: "crits/fantasyAndWorship/coralCropVeneration.webp",
    description: "Grows this floor's level by 3.4% in free upgrades",
  },
  platinumAmazon: {
    label: "Platinum Amazon",
    color: COLOR.amberMuted,
    image: "crits/fantasyAndWorship/platinumAmazon.webp",
    description: "Pays 73 times this floor's upgrade price in cash",
  },
  navySanctum: {
    label: "Navy Sanctum",
    color: COLOR.amberMuted,
    image: "crits/fantasyAndWorship/navySanctum.webp",
    description: "Spreads 55 free upgrades over this floor and the ones below",
  },
  plumMatriarch: {
    label: "Plum Matriarch",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fantasyAndWorship/plumMatriarch.webp",
    description: "Grows this floor's level by 3.7% in free upgrades",
  },
  giantessSanctuary: {
    label: "Giantess Sanctuary",
    color: COLOR.sameBoatCoral,
    image: "crits/fantasyAndWorship/giantessSanctuary.webp",
    description: "Spreads 57 free upgrades over this floor and the ones below",
  },
  ponytailPriestess: {
    label: "Ponytail Priestess",
    color: COLOR.sameBoatCoral,
    image: "crits/fantasyAndWorship/ponytailPriestess.webp",
    description: "Pays 16 times every unlocked floor's upgrade price in cash",
  },
  rainbowShortsShrine: {
    label: "Rainbow Shorts Shrine",
    color: COLOR.coinGold,
    image: "crits/fantasyAndWorship/rainbowShortsShrine.webp",
    description: "Grows this floor's level by 5.2% in free upgrades",
  },
  sunnyDivaAltar: {
    label: "Sunny Diva Altar",
    color: COLOR.summerSaleOrange,
    image: "crits/fantasyAndWorship/sunnyDivaAltar.webp",
    description: "Spreads 60 free upgrades over this floor and the ones below",
  },
  emeraldTopAdoration: {
    label: "Emerald Top Adoration",
    color: COLOR.coinGold,
    image: "crits/fantasyAndWorship/emeraldTopAdoration.webp",
    description: "Pays 19 times every unlocked floor's upgrade price in cash",
  },
  blondeDisciple: {
    label: "Blonde Disciple",
    color: COLOR.amberMuted,
    image: "crits/fantasyAndWorship/blondeDisciple.webp",
    description: "Spreads 61 free upgrades over this floor and the ones below",
  },
} as const satisfies Record<string, FeaturedCritData>;
