import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const FANTASY_ROMANCES_CRITS = {
  scaleSmooch: {
    label: "Scale Smooch",
    color: COLOR.fullHouseCrimson,
    image: "crits/fantasyRomances/scaleSmooch.webp",
    description: "Repeats the crit on the floor above, 86% chance to keep climbing",
  },
  hornLockKiss: {
    label: "Horn Lock Kiss",
    color: COLOR.fullHouseCrimson,
    image: "crits/fantasyRomances/hornLockKiss.webp",
    description: "Cuts every price in this building by 18.1%",
  },
  fireAndFrostKiss: {
    label: "Fire And Frost Kiss",
    color: COLOR.headhunterRust,
    image: "crits/fantasyRomances/fireAndFrostKiss.webp",
    description: "Adds 47s of your company's income",
  },
  sapphireEmberSmooch: {
    label: "Sapphire Ember Smooch",
    color: COLOR.overflowBlue,
    image: "crits/fantasyRomances/sapphireEmberSmooch.webp",
    description: "Boosts every worker for 136s, counting as 3 extra workers",
  },
  fangKissFling: {
    label: "Fang Kiss Fling",
    color: COLOR.doubleDownCrimson,
    image: "crits/fantasyRomances/fangKissFling.webp",
    description: "Boosts every worker for 140s, counting as 3 extra workers",
  },
  neckNibbleKiss: {
    label: "Neck Nibble Kiss",
    color: COLOR.chairGiveawayBrown,
    image: "crits/fantasyRomances/neckNibbleKiss.webp",
    description: "Repeats the crit on the floor above, 88% chance to keep climbing",
  },
  tuskTango: {
    label: "Tusk Tango",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyRomances/tuskTango.webp",
    description: "Cuts every price in this building by 20.2%",
  },
  tuskTouchKiss: {
    label: "Tusk Touch Kiss",
    color: COLOR.luckyCloverGreen,
    image: "crits/fantasyRomances/tuskTouchKiss.webp",
    description: "Adds 21.6% of your total income",
  },
  tuskTrioTreaty: {
    label: "Tusk Trio Treaty",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyRomances/tuskTrioTreaty.webp",
    description: "Boosts every worker for 160s, counting as 3 extra workers",
  },
  earResistibleTrio: {
    label: "Ear Resistible Trio",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fantasyRomances/earResistibleTrio.webp",
    description: "Adds 22.3% of your total income",
  },
  fangClub: {
    label: "Fang Club",
    color: COLOR.sameBoatCoral,
    image: "crits/fantasyRomances/fangClub.webp",
    description: "Cuts every price in this building by 21%",
  },
  greenWithEnvy: {
    label: "Green With Envy",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyRomances/greenWithEnvy.webp",
    description: "Boosts every worker for 168s, counting as 3 extra workers",
  },
  goblinSmoochSavings: {
    label: "Goblin Smooch Savings",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyRomances/goblinSmoochSavings.webp",
    description: "Adds 24.5% of your total income",
  },
  orcKissAccount: {
    label: "Orc Kiss Account",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyRomances/orcKissAccount.webp",
    description: "Adds 24.8% of your total income",
  },
  blondeGoblinBankroll: {
    label: "Blonde Goblin Bankroll",
    color: COLOR.threeOfAKindGreen,
    image: "crits/fantasyRomances/blondeGoblinBankroll.webp",
    description: "Ninety-one instant payouts on this floor",
  },
  braidedGoblinBonus: {
    label: "Braided Goblin Bonus",
    color: COLOR.paydayEmerald,
    image: "crits/fantasyRomances/braidedGoblinBonus.webp",
    description: "Ninety-two instant payouts on this floor",
  },
  emeraldKissEarnings: {
    label: "Emerald Kiss Earnings",
    color: COLOR.luckyCloverGreen,
    image: "crits/fantasyRomances/emeraldKissEarnings.webp",
    description: "Adds 78s of your company's income",
  },
  goblinKissGold: {
    label: "Goblin Kiss Gold",
    color: COLOR.luckyCloverGreen,
    image: "crits/fantasyRomances/goblinKissGold.webp",
    description: "Ninety-three instant payouts on this floor",
  },
  greenQueenGains: {
    label: "Green Queen Gains",
    color: COLOR.paydayEmerald,
    image: "crits/fantasyRomances/greenQueenGains.webp",
    description: "Eleven free upgrades on the lowest-level floor",
  },
  hoopEarringHoldings: {
    label: "Hoop Earring Holdings",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/fantasyRomances/hoopEarringHoldings.webp",
    description: "Adds 79s of your company's income",
  },
  pointyEarPay: {
    label: "Pointy Ear Pay",
    color: COLOR.amberMuted,
    image: "crits/fantasyRomances/pointyEarPay.webp",
    description: "Ninety-four instant payouts on this floor",
  },
  punkGoblinPayout: {
    label: "Punk Goblin Payout",
    color: COLOR.bullMarketGreen,
    image: "crits/fantasyRomances/punkGoblinPayout.webp",
    description: "Ninety-five instant payouts on this floor",
  },
  swampSmoochStash: {
    label: "Swamp Smooch Stash",
    color: COLOR.paydayEmerald,
    image: "crits/fantasyRomances/swampSmoochStash.webp",
    description: "Adds 80s of your company's income",
  },
  tuskKissTally: {
    label: "Tusk Kiss Tally",
    color: COLOR.bullMarketGreen,
    image: "crits/fantasyRomances/tuskKissTally.webp",
    description: "Ninety-six instant payouts on this floor",
  },
  blueGoblinTwins: {
    label: "Blue Goblin Twins",
    color: COLOR.moneyGreen,
    image: "crits/fantasyRomances/blueGoblinTwins.webp",
    description: "Grows every unlocked floor's level by 2.5% in free upgrades",
  },
  goblinLipPrint: {
    label: "Goblin Lip Print",
    color: COLOR.bullMarketGreen,
    image: "crits/fantasyRomances/goblinLipPrint.webp",
    description: "Grows this floor's level by 8.4% in free upgrades",
  },
  goblinCrush: {
    label: "Goblin Crush",
    color: COLOR.gold,
    image: "crits/fantasyRomances/goblinCrush.webp",
    description: "Grows every unlocked floor's level by 2.8% in free upgrades",
  },
  greenCheekLick: {
    label: "Green Cheek Lick",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/fantasyRomances/greenCheekLick.webp",
    description: "Grows this floor's level by 9.6% in free upgrades",
  },
} as const satisfies Record<string, FeaturedCritData>;
