import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const FOOT_POSES_CRITS = {
  cooldownStretch: {
    label: "Cooldown Stretch",
    color: COLOR.luckyCloverGreen,
    image: "crits/footPoses/cooldownStretch.webp",
    description: "Adds 53s of your company's income",
  },
  flexiblePricing: {
    label: "Flexible Pricing",
    color: COLOR.fullHouseCrimson,
    image: "crits/footPoses/flexiblePricing.webp",
    description: "Cuts every price in this building by 21.3%",
  },
  highKickMarkdown: {
    label: "High Kick Markdown",
    color: COLOR.nightShiftIndigo,
    image: "crits/footPoses/highKickMarkdown.webp",
    description: "Cuts every price in this building by 21.4%",
  },
  splitTheProfits: {
    label: "Split the Profits",
    color: COLOR.chairGiveawayBrown,
    image: "crits/footPoses/splitTheProfits.webp",
    description: "Adds 23.3% of your total income",
  },
  legUpLedger: {
    label: "Leg Up Ledger",
    color: COLOR.sameBoatCoral,
    image: "crits/footPoses/legUpLedger.webp",
    description: "Adds 22.8% of your total income",
  },
  butterflySplit: {
    label: "Butterfly Split",
    color: COLOR.starYellow,
    image: "crits/footPoses/butterflySplit.webp",
    description: "Spreads 133 free upgrades over the lowest-level floors",
  },
  ponytailVSplit: {
    label: "Ponytail V Split",
    color: COLOR.fastForwardBlue,
    image: "crits/footPoses/ponytailVSplit.webp",
    description: "Grows every unlocked floor's level by 6.9% in free upgrades",
  },
  bunTopPike: {
    label: "Bun Top Pike",
    color: COLOR.summerSaleOrange,
    image: "crits/footPoses/bunTopPike.webp",
    description: "Grows this floor's level by 14.8% in free upgrades",
  },
  frogSitFlex: {
    label: "Frog Sit Flex",
    color: COLOR.summerSaleOrange,
    image: "crits/footPoses/frogSitFlex.webp",
    description: "Grows every unlocked floor's level by 6.6% in free upgrades",
  },
  goldenLocksLegUp: {
    label: "Golden Locks Leg Up",
    color: COLOR.starYellow,
    image: "crits/footPoses/goldenLocksLegUp.webp",
    description: "Spreads 135 free upgrades over the lowest-level floors",
  },
  huggedStilts: {
    label: "Hugged Stilts",
    color: COLOR.amberMuted,
    image: "crits/footPoses/huggedStilts.webp",
    description: "Pays 125 times this floor's upgrade price in cash",
  },
  kneeHugHuddle: {
    label: "Knee Hug Huddle",
    color: COLOR.amberMuted,
    image: "crits/footPoses/kneeHugHuddle.webp",
    description: "Grows every unlocked floor's level by 6.7% in free upgrades",
  },
  lowFadeFootrest: {
    label: "Low Fade Footrest",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/footPoses/lowFadeFootrest.webp",
    description: "Spreads 136 free upgrades over the lowest-level floors",
  },
  pinkCropPowerhouse: {
    label: "Pink Crop Powerhouse",
    color: COLOR.amberMuted,
    image: "crits/footPoses/pinkCropPowerhouse.webp",
    description: "Spreads 137 free upgrades over the lowest-level floors",
  },
  reclineRaise: {
    label: "Recline Raise",
    color: COLOR.amberMuted,
    image: "crits/footPoses/reclineRaise.webp",
    description: "Pays 128 times this floor's upgrade price in cash",
  },
  redheadCrossover: {
    label: "Redhead Crossover",
    color: COLOR.sameBoatCoral,
    image: "crits/footPoses/redheadCrossover.webp",
    description: "Grows every unlocked floor's level by 7% in free upgrades",
  },
  redTankRaise: {
    label: "Red Tank Raise",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/footPoses/redTankRaise.webp",
    description: "Spreads 139 free upgrades over the lowest-level floors",
  },
  crisscrossBun: {
    label: "Crisscross Bun",
    color: COLOR.amberMuted,
    image: "crits/footPoses/crisscrossBun.webp",
    description: "Pays 124 times this floor's upgrade price in cash",
  },
  blondeBallUp: {
    label: "Blonde Ball Up",
    color: COLOR.sameBoatCoral,
    image: "crits/footPoses/blondeBallUp.webp",
    description: "Spreads 132 free upgrades over the lowest-level floors",
  },
  onTheBall: {
    label: "On The Ball",
    color: COLOR.amberMuted,
    image: "crits/footPoses/onTheBall.webp",
    description: "Boosts every worker for 165s, counting as 3 extra workers",
  },
  toePyramid: {
    label: "Toe Pyramid",
    color: COLOR.summerSaleOrange,
    image: "crits/footPoses/toePyramid.webp",
    description: "Pays 18 times this floor's upgrade price in cash",
  },
  toeStackLean: {
    label: "Toe Stack Lean",
    color: COLOR.amberMuted,
    image: "crits/footPoses/toeStackLean.webp",
    description: "Spreads 142 free upgrades over the lowest-level floors",
  },
  cherryBobBundle: {
    label: "Cherry Bob Bundle",
    color: COLOR.teamBuildingCoral,
    image: "crits/footPoses/cherryBobBundle.webp",
    description: "Grows every unlocked floor's level by 7.3% in free upgrades",
  },
  victoryVSoles: {
    label: "Victory V Soles",
    color: COLOR.starYellow,
    image: "crits/footPoses/victoryVSoles.webp",
    description: "Pays 131 times this floor's upgrade price in cash",
  },
  tippyToeTycoon: {
    label: "Tippy Toe Tycoon",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/footPoses/tippyToeTycoon.webp",
    description: "Unlocks the next 5 floors for free",
  },
  topknotTiptoe: {
    label: "Topknot Tiptoe",
    color: COLOR.amberMuted,
    image: "crits/footPoses/topknotTiptoe.webp",
    description: "Spreads 130 free upgrades over the lowest-level floors",
  },
  stepUpStocks: {
    label: "Step Up Stocks",
    color: COLOR.overflowBlue,
    image: "crits/footPoses/stepUpStocks.webp",
    description: "Repeats the crit on the floor above, 25% chance to keep climbing",
  },
  kickBackCapital: {
    label: "Kick Back Capital",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/footPoses/kickBackCapital.webp",
    description: "Boosts every worker for 143s, counting as 3 extra workers",
  },
  lyingLowLedger: {
    label: "Lying Low Ledger",
    color: COLOR.amberMuted,
    image: "crits/footPoses/lyingLowLedger.webp",
    description: "Adds 24.2% of your total income",
  },
  cobaltBobKick: {
    label: "Cobalt Bob Kick",
    color: COLOR.summerSaleOrange,
    image: "crits/footPoses/cobaltBobKick.webp",
    description: "Grows this floor's level by 14.9% in free upgrades",
  },
  frontKickPucker: {
    label: "Front Kick Pucker",
    color: COLOR.coinGold,
    image: "crits/footPoses/frontKickPucker.webp",
    description: "Pays 106 times this floor's upgrade price in cash",
  },
  flexPosePeck: {
    label: "Flex Pose Peck",
    color: COLOR.summerSaleOrange,
    image: "crits/footPoses/flexPosePeck.webp",
    description: "Spreads 63 free upgrades over the lowest-level floors",
  },
  pinkCarpetKickoff: {
    label: "Pink Carpet Kickoff",
    color: COLOR.fullHouseCrimson,
    image: "crits/footPoses/pinkCarpetKickoff.webp",
    description: "Boosts every worker for 171s, counting as 3 extra workers",
  },
  silverBuzzFlex: {
    label: "Silver Buzz Flex",
    color: COLOR.sameBoatCoral,
    image: "crits/footPoses/silverBuzzFlex.webp",
    description: "Spreads 128 free upgrades over the lowest-level floors",
  },
} as const satisfies Record<string, FeaturedCritData>;
