import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const GLAMOUR_AND_RUNWAY_CRITS = {
  leotardLuster: {
    label: "Leotard Luster",
    color: COLOR.fastForwardBlue,
    image: "crits/glamourAndRunway/leotardLuster.webp",
    description: "Sixty-four payouts on alternating floors",
  },
  outOfTheBlue: {
    label: "Out of the Blue",
    color: COLOR.recruitmentDriveBlue,
    image: "crits/glamourAndRunway/outOfTheBlue.webp",
    description:
      "Repeats the crit on the floor above, 59% chance to keep climbing",
  },
  blondeAmbition: {
    label: "Blonde Ambition",
    color: COLOR.fireDrillRed,
    image: "crits/glamourAndRunway/blondeAmbition.webp",
    description: "Seventy-seven payouts on the highest unlocked floor",
  },
  prizeHeifer: {
    label: "Prize Heifer",
    color: COLOR.starYellow,
    image: "crits/glamourAndRunway/prizeHeifer.webp",
    description: "One tier promotion and forty-five upgrades here",
  },
  quicksilverQueen: {
    label: "Quicksilver Queen",
    color: COLOR.overflowBlue,
    image: "crits/glamourAndRunway/quicksilverQueen.webp",
    description: "Cuts every price in this building by 1.3%",
  },
  ballgownBullion: {
    label: "Ballgown Bullion",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/glamourAndRunway/ballgownBullion.webp",
    description: "One hundred and three instant payouts on this floor",
  },
  coutureCapital: {
    label: "Couture Capital",
    color: COLOR.overflowBlue,
    image: "crits/glamourAndRunway/coutureCapital.webp",
    description: "Adds 86s of your company's income",
  },
  emeraldEarnings: {
    label: "Emerald Earnings",
    color: COLOR.moneyGreen,
    image: "crits/glamourAndRunway/emeraldEarnings.webp",
    description: "Adds 87s of your company's income",
  },
  platinumPortfolio: {
    label: "Platinum Portfolio",
    color: COLOR.overflowBlue,
    image: "crits/glamourAndRunway/platinumPortfolio.webp",
    description: "Adds 89s of your company's income",
  },
  redDressReserve: {
    label: "Red Dress Reserve",
    color: COLOR.redActive,
    image: "crits/glamourAndRunway/redDressReserve.webp",
    description: "One hundred and four instant payouts on this floor",
  },
  ruffleReturns: {
    label: "Ruffle Returns",
    color: COLOR.fastForwardBlue,
    image: "crits/glamourAndRunway/ruffleReturns.webp",
    description: "One hundred and five instant payouts on this floor",
  },
  runwayRevenue: {
    label: "Runway Revenue",
    color: COLOR.fancyFridayIndigo,
    image: "crits/glamourAndRunway/runwayRevenue.webp",
    description: "One hundred and six instant payouts on this floor",
  },
  silverScreenShares: {
    label: "Silver Screen Shares",
    color: COLOR.nightOwlIndigo,
    image: "crits/glamourAndRunway/silverScreenShares.webp",
    description: "Adds 91s of your company's income",
  },
  thighHighYield: {
    label: "Thigh High Yield",
    color: COLOR.doubleDownCrimson,
    image: "crits/glamourAndRunway/thighHighYield.webp",
    description: "Adds 92s of your company's income",
  },
  updoUpside: {
    label: "Updo Upside",
    color: COLOR.redActive,
    image: "crits/glamourAndRunway/updoUpside.webp",
    description: "One hundred and seven instant payouts on this floor",
  },
  kissCurl: {
    label: "Kiss Curl",
    color: COLOR.sameBoatCoral,
    image: "crits/glamourAndRunway/kissCurl.webp",
    description: "Adds 96s of your company's income",
  },
  blueStreak: {
    label: "Blue Streak",
    color: COLOR.overflowBlue,
    image: "crits/glamourAndRunway/blueStreak.webp",
    description: "Grows every unlocked floor's level by 4.3% in free upgrades",
  },
  cameoAppearance: {
    label: "Cameo Appearance",
    color: COLOR.amberMuted,
    image: "crits/glamourAndRunway/cameoAppearance.webp",
    description: "Spreads 82 free upgrades over the lowest-level floors",
  },
  cleanSlate: {
    label: "Clean Slate",
    color: COLOR.summerSaleOrange,
    image: "crits/glamourAndRunway/cleanSlate.webp",
    description: "Spreads 83 free upgrades over the lowest-level floors",
  },
  goldenHoops: {
    label: "Golden Hoops",
    color: COLOR.coffeeRunTeal,
    image: "crits/glamourAndRunway/goldenHoops.webp",
    description: "Pays 17 times the highest floor's upgrade price in cash",
  },
  ivoryTower: {
    label: "Ivory Tower",
    color: COLOR.fastForwardBlue,
    image: "crits/glamourAndRunway/ivoryTower.webp",
    description: "Grows this floor's level by 12.3% in free upgrades",
  },
  overallWinner: {
    label: "Overall Winner",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/glamourAndRunway/overallWinner.webp",
    description: "Grows this floor's level by 3.1% in free upgrades",
  },
  silverBraid: {
    label: "Silver Braid",
    color: COLOR.summerSaleOrange,
    image: "crits/glamourAndRunway/silverBraid.webp",
    description: "Pays 4 times this floor's upgrade price in cash",
  },
  strappedForCash: {
    label: "Strapped For Cash",
    color: COLOR.gold,
    image: "crits/glamourAndRunway/strappedForCash.webp",
    description: "Spreads 11 free upgrades over the lowest-level floors",
  },
  swimsuitVenus: {
    label: "Swimsuit Venus",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/glamourAndRunway/swimsuitVenus.webp",
    description: "Grows every unlocked floor's level by 6.3% in free upgrades",
  },
  pinkTopPedestal: {
    label: "Pink Top Pedestal",
    color: COLOR.amberMuted,
    image: "crits/glamourAndRunway/pinkTopPedestal.webp",
    description: "Spreads 37 free upgrades over this floor and the ones below",
  },
  leotardDivinity: {
    label: "Leotard Divinity",
    color: COLOR.coinGold,
    image: "crits/glamourAndRunway/leotardDivinity.webp",
    description: "Grows this floor's level by 3.3% in free upgrades",
  },
  aquaShortsMuse: {
    label: "Aqua Shorts Muse",
    color: COLOR.coinGold,
    image: "crits/glamourAndRunway/aquaShortsMuse.webp",
    description: "Pays 17 times every unlocked floor's upgrade price in cash",
  },
  pinkTightsPowerhouse: {
    label: "Pink Tights Powerhouse",
    color: COLOR.summerSaleOrange,
    image: "crits/glamourAndRunway/pinkTightsPowerhouse.webp",
    description: "Pays 18 times every unlocked floor's upgrade price in cash",
  },
  grapeSpandex: {
    label: "Grape Spandex",
    color: COLOR.overflowBlue,
    image: "crits/glamourAndRunway/grapeSpandex.webp",
    description: "Pays 141 times this floor's upgrade price in cash",
  },
  highlighterLeggings: {
    label: "Highlighter Leggings",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/glamourAndRunway/highlighterLeggings.webp",
    description: "Spreads 152 free upgrades over the lowest-level floors",
  },
  ivoryShorts: {
    label: "Ivory Shorts",
    color: COLOR.amberMuted,
    image: "crits/glamourAndRunway/ivoryShorts.webp",
    description: "Spreads 153 free upgrades over the lowest-level floors",
  },
  sterlingProwl: {
    label: "Sterling Prowl",
    color: COLOR.disabledGray,
    image: "crits/glamourAndRunway/sterlingProwl.webp",
    description: "Adds 40.4% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
