import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const KISSES_AND_PINUPS_CRITS = {
  swingAndASmooch: {
    label: "Swing and a Smooch",
    color: COLOR.spendingFreezeTeal,
    image: "crits/kissesAndPinups/swingAndASmooch.webp",
    description: "Raises the lowest-level floor to the building's top level",
  },
  pumpAndPout: {
    label: "Pump & Pout",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/kissesAndPinups/pumpAndPout.webp",
    description: "Boosts every worker for 54s, counting as 1 extra worker",
  },
  blowAKissBudget: {
    label: "Blow a Kiss Budget",
    color: COLOR.amberMuted,
    image: "crits/kissesAndPinups/blowAKissBudget.webp",
    description: "Adds 26.9% of your total income",
  },
  blueKissBonus: {
    label: "Blue Kiss Bonus",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/blueKissBonus.webp",
    description: "Eighty-five instant payouts on this floor",
  },
  farewellKissFund: {
    label: "Farewell Kiss Fund",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/kissesAndPinups/farewellKissFund.webp",
    description: "Adds 27% of your total income",
  },
  kissKissCapital: {
    label: "Kiss Kiss Capital",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/kissesAndPinups/kissKissCapital.webp",
    description: "Adds 27.1% of your total income",
  },
  kissMarkProfit: {
    label: "Kiss Mark Profit",
    color: COLOR.coinGold,
    image: "crits/kissesAndPinups/kissMarkProfit.webp",
    description: "Adds 27.2% of your total income",
  },
  kissYourMoneyHello: {
    label: "Kiss Your Money Hello",
    color: COLOR.amberMuted,
    image: "crits/kissesAndPinups/kissYourMoneyHello.webp",
    description: "Eighty-eight instant payouts on this floor",
  },
  pointedProfits: {
    label: "Pointed Profits",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/pointedProfits.webp",
    description: "Adds 27.3% of your total income",
  },
  rainbowKissRebate: {
    label: "Rainbow Kiss Rebate",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/rainbowKissRebate.webp",
    description: "Adds 27.4% of your total income",
  },
  sealedKissCheck: {
    label: "Sealed Kiss Check",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/sealedKissCheck.webp",
    description: "Eighty-nine instant payouts on this floor",
  },
  smoochStipend: {
    label: "Smooch Stipend",
    color: COLOR.coinGold,
    image: "crits/kissesAndPinups/smoochStipend.webp",
    description: "Ninety instant payouts on this floor",
  },
  sunnySmoochShares: {
    label: "Sunny Smooch Shares",
    color: COLOR.starYellow,
    image: "crits/kissesAndPinups/sunnySmoochShares.webp",
    description: "Adds 76s of your company's income",
  },
  pixieKissPaycheck: {
    label: "Pixie Kiss Paycheck",
    color: COLOR.sameBoatCoral,
    image: "crits/kissesAndPinups/pixieKissPaycheck.webp",
    description: "Ninety-seven instant payouts on this floor",
  },
  smoochSalary: {
    label: "Smooch Salary",
    color: COLOR.amberMuted,
    image: "crits/kissesAndPinups/smoochSalary.webp",
    description: "Ninety-eight instant payouts on this floor",
  },
  bigHairPout: {
    label: "Big Hair Pout",
    color: COLOR.sameBoatCoral,
    image: "crits/kissesAndPinups/bigHairPout.webp",
    description: "Adds 93s of your company's income",
  },
  blushingPucker: {
    label: "Blushing Pucker",
    color: COLOR.fullHouseCrimson,
    image: "crits/kissesAndPinups/blushingPucker.webp",
    description: "One hundred and eight instant payouts on this floor",
  },
  peckPlease: {
    label: "Peck Please",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/peckPlease.webp",
    description: "One hundred and nine instant payouts on this floor",
  },
  lipService: {
    label: "Lip Service",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/lipService.webp",
    description: "Adds 94s of your company's income",
  },
  candyLips: {
    label: "Candy Lips",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/candyLips.webp",
    description: "Adds 95s of your company's income",
  },
  kissyFace: {
    label: "Kissy Face",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/kissyFace.webp",
    description: "Adds 97s of your company's income",
  },
  lipGlossGrin: {
    label: "Lip Gloss Grin",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/lipGlossGrin.webp",
    description: "One hundred and eleven instant payouts on this floor",
  },
  hotLips: {
    label: "Hot Lips",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/hotLips.webp",
    description: "Adds 99s of your company's income",
  },
  mwahaha: {
    label: "Mwahaha",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/mwahaha.webp",
    description: "One hundred and twelve instant payouts on this floor",
  },
  mostKissable: {
    label: "Most Kissable",
    color: COLOR.coinGold,
    image: "crits/kissesAndPinups/mostKissable.webp",
    description: "Adds 100s of your company's income",
  },
  puckerUp: {
    label: "Pucker Up",
    color: COLOR.fastForwardBlue,
    image: "crits/kissesAndPinups/puckerUp.webp",
    description: "One hundred and thirteen instant payouts on this floor",
  },
  redHotKiss: {
    label: "Red Hot Kiss",
    color: COLOR.sameBoatCoral,
    image: "crits/kissesAndPinups/redHotKiss.webp",
    description: "One hundred and fourteen instant payouts on this floor",
  },
  bedroomEyes: {
    label: "Bedroom Eyes",
    color: COLOR.rainCheckBlue,
    image: "crits/kissesAndPinups/bedroomEyes.webp",
    description: "Adds 101s of your company's income",
  },
  airKiss: {
    label: "Air Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/airKiss.webp",
    description: "One hundred and fifteen instant payouts on this floor",
  },
  xoxo: {
    label: "XOXO",
    color: COLOR.fastForwardBlue,
    image: "crits/kissesAndPinups/xoxo.webp",
    description: "Adds 102s of your company's income",
  },
  sugarKiss: {
    label: "Sugar Kiss",
    color: COLOR.fastForwardBlue,
    image: "crits/kissesAndPinups/sugarKiss.webp",
    description: "Adds 103s of your company's income",
  },
  tenderLips: {
    label: "Tender Lips",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/kissesAndPinups/tenderLips.webp",
    description: "One hundred and sixteen instant payouts on this floor",
  },
  beeStungLips: {
    label: "Bee Stung Lips",
    color: COLOR.fastForwardBlue,
    image: "crits/kissesAndPinups/beeStungLips.webp",
    description: "Adds 104s of your company's income",
  },
  winkAndAKiss: {
    label: "Wink And A Kiss",
    color: COLOR.coinGold,
    image: "crits/kissesAndPinups/winkAndAKiss.webp",
    description: "One hundred and seventeen instant payouts on this floor",
  },
  selfLove: {
    label: "Self Love",
    color: COLOR.amberMuted,
    image: "crits/kissesAndPinups/selfLove.webp",
    description: "One hundred and eighteen instant payouts on this floor",
  },
  lipNibble: {
    label: "Lip Nibble",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/kissesAndPinups/lipNibble.webp",
    description: "Spreads 85 free upgrades over the lowest-level floors",
  },
  mohawkMwah: {
    label: "Mohawk Mwah",
    color: COLOR.moneyGreen,
    image: "crits/kissesAndPinups/mohawkMwah.webp",
    description: "Pays 14 times this floor's upgrade price in cash",
  },
  olivePout: {
    label: "Olive Pout",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/kissesAndPinups/olivePout.webp",
    description: "Pays 18 times the highest floor's upgrade price in cash",
  },
  royalHandKiss: {
    label: "Royal Hand Kiss",
    color: COLOR.summerSaleOrange,
    image: "crits/kissesAndPinups/royalHandKiss.webp",
    description: "Spreads 36 free upgrades over this floor and the ones below",
  },
} as const satisfies Record<string, FeaturedCritData>;
