import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const LUCKY_CHARMS_CRITS = {
  bubbleEconomy: {
    label: "Bubble Economy",
    color: COLOR.snowballBlue,
    image: "crits/luckyCharms/bubbleEconomy.webp",
    description: "Seven instant payouts on this floor",
  },
  cloudNineToFive: {
    label: "Cloud Nine to Five",
    color: COLOR.floorShareBlue,
    image: "crits/luckyCharms/cloudNineToFive.webp",
    description: "Unlocks the next floor for free",
  },
  luckyLaundromat: {
    label: "Lucky Laundromat",
    color: COLOR.luckyCloverGreen,
    image: "crits/luckyCharms/luckyLaundromat.webp",
    description: "Five upgrades and five payouts on every floor",
  },
  moneyMagnet: {
    label: "Money Magnet",
    color: COLOR.red,
    image: "crits/luckyCharms/moneyMagnet.webp",
    description: "Adds 3.2% of your total income",
  },
  overTheRainbow: {
    label: "Over the Rainbow",
    color: COLOR.purple,
    image: "crits/luckyCharms/overTheRainbow.webp",
    description: "Locks this floor's upgrade price for 5s",
  },
  pocketDimension: {
    label: "Pocket Dimension",
    color: COLOR.fourOfAKindIndigo,
    image: "crits/luckyCharms/pocketDimension.webp",
    description: "Arms this floor's next click as an x5 crit",
  },
  shootingStarEmployee: {
    label: "Shooting Star",
    color: COLOR.starYellow,
    image: "crits/luckyCharms/shootingStarEmployee.webp",
    description: "Twenty-three free upgrades on the highest floor",
  },
  treasureMeasure: {
    label: "Treasure Measure",
    color: COLOR.supplyRunTan,
    image: "crits/luckyCharms/treasureMeasure.webp",
    description: "Adds 5s of your company's income",
  },
  wishfulBanking: {
    label: "Wishful Banking",
    color: COLOR.goldenTicketYellow,
    image: "crits/luckyCharms/wishfulBanking.webp",
    description: "Two tier promotions and twelve upgrades here",
  },
  amethyst: {
    label: "Amethyst",
    color: COLOR.purple,
    image: "crits/luckyCharms/amethyst.webp",
    description: "Arms this floor's next click as an x5 crit",
  },
  diamond: {
    label: "Diamond",
    color: COLOR.cyan,
    image: "crits/luckyCharms/diamond.webp",
    description: "Adds 3.5% of your total income",
  },
  emerald: {
    label: "Emerald",
    color: COLOR.moneyGreen,
    image: "crits/luckyCharms/emerald.webp",
    description: "Adds 5s of your company's income",
  },
  goldNugget: {
    label: "Gold Nugget",
    color: COLOR.gold,
    image: "crits/luckyCharms/goldNugget.webp",
    description: "Adds 3% of your total income",
  },
  goldRush: {
    label: "Gold Rush",
    color: COLOR.gold,
    image: "crits/luckyCharms/goldRush.webp",
    description: "Boosts this floor's workers for 23s",
  },
  ruby: {
    label: "Ruby",
    color: COLOR.red,
    image: "crits/luckyCharms/ruby.webp",
    description: "Adds 6s of your company's income",
  },
  saphire: {
    label: "Sapphire",
    color: COLOR.blue,
    image: "crits/luckyCharms/saphire.webp",
    description: "Free office supplies for this floor",
  },
  silverRush: {
    label: "Silver Rush",
    color: COLOR.silverTicketGray,
    image: "crits/luckyCharms/silverRush.webp",
    description: "Boosts this floor's workers for 21s",
  },
  rainbowGems: {
    label: "Rainbow Gems",
    color: COLOR.overflowBlue,
    image: "crits/luckyCharms/rainbowGems.webp",
    description: "Grows every unlocked floor's level by 2.3% in free upgrades",
  },
  goldLion: {
    label: "Golden Lion",
    color: COLOR.gold,
    image: "crits/luckyCharms/goldLion.webp",
    description: "Adds 13s of your company's income",
  },
  goldElephant: {
    label: "Golden Elephant",
    color: COLOR.sunshineGold,
    image: "crits/luckyCharms/goldElephant.webp",
    description: "Adds 6.7% of your total income",
  },
  goldBear: {
    label: "Golden Bear",
    color: COLOR.orange,
    image: "crits/luckyCharms/goldBear.webp",
    description: "Adds 13s of your company's income",
  },
  goldWolf: {
    label: "Golden Wolf",
    color: COLOR.blue,
    image: "crits/luckyCharms/goldWolf.webp",
    description: "Adds 6.3% of your total income",
  },
  goldOwl: {
    label: "Golden Owl",
    color: COLOR.luckyCloverGreen,
    image: "crits/luckyCharms/goldOwl.webp",
    description: "Adds 11s of your company's income",
  },
  goldRam: {
    label: "Golden Ram",
    color: COLOR.starYellow,
    image: "crits/luckyCharms/goldRam.webp",
    description: "Adds 5.6% of your total income",
  },
  goldRabbit: {
    label: "Golden Rabbit",
    color: COLOR.springSalePink,
    image: "crits/luckyCharms/goldRabbit.webp",
    description: "Adds 10s of your company's income",
  },
  goldCat: {
    label: "Golden Cat",
    color: COLOR.teaBreakBrown,
    image: "crits/luckyCharms/goldCat.webp",
    description: "Adds 5.3% of your total income",
  },
  goldenLion: {
    label: "King of the Jungle",
    color: COLOR.heavenlyGold,
    image: "crits/luckyCharms/goldenLion.webp",
    description: "One tier promotion, then twenty free upgrades here",
  },
  platinumPaw: {
    label: "Platinum Paw",
    color: COLOR.silverTicketGray,
    image: "crits/luckyCharms/platinumPaw.webp",
    description: "One tier promotion and forty-one upgrades here",
  },
  gildedWyrm: {
    label: "Gilded Wyrm",
    color: COLOR.amberMuted,
    image: "crits/luckyCharms/gildedWyrm.webp",
    description: "Adds 20.1% of your total income",
  },
  bullionDrake: {
    label: "Bullion Drake",
    color: COLOR.amber,
    image: "crits/luckyCharms/bullionDrake.webp",
    description: "One tier promotion and ten upgrades on the lowest-level floor",
  },
  slowAndGold: {
    label: "Slow And Gold",
    color: COLOR.amber,
    image: "crits/luckyCharms/slowAndGold.webp",
    description: "Raises the lowest-level floor to half the building's top level",
  },
  platinumPlume: {
    label: "Platinum Plume",
    color: COLOR.amberMuted,
    image: "crits/luckyCharms/platinumPlume.webp",
    description: "Free office supplies for this floor",
  },
} as const satisfies Record<string, FeaturedCritData>;
