import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const MEDITERRANEAN_FEASTS_CRITS = {
  batteredBrunch: {
    label: "Battered Brunch",
    color: COLOR.gold,
    image: "crits/mediterraneanFeasts/batteredBrunch.webp",
    description: "Promotes 82% of this building's workers one perma tier",
  },
  beerHallPlate: {
    label: "Beer Hall Plate",
    color: COLOR.amberMuted,
    image: "crits/mediterraneanFeasts/beerHallPlate.webp",
    description: "Promotes 82.5% of this building's workers one perma tier",
  },
  berryDumplings: {
    label: "Berry Dumplings",
    color: COLOR.gold,
    image: "crits/mediterraneanFeasts/berryDumplings.webp",
    description: "Promotes 83% of this building's workers one perma tier",
  },
  borschtBrunch: {
    label: "Borscht Brunch",
    color: COLOR.gold,
    image: "crits/mediterraneanFeasts/borschtBrunch.webp",
    description: "Promotes 84% of this building's workers one perma tier",
  },
  charcuterieBoard: {
    label: "Charcuterie Board",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/charcuterieBoard.webp",
    description: "Promotes 84.5% of this building's workers one perma tier",
  },
  cheesyGreens: {
    label: "Cheesy Greens",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/cheesyGreens.webp",
    description: "Promotes 85% of this building's workers one perma tier",
  },
  chocolateTruffleWaffle: {
    label: "Chocolate Truffle Waffle",
    color: COLOR.amberMuted,
    image: "crits/mediterraneanFeasts/chocolateTruffleWaffle.webp",
    description: "Promotes 85.5% of this building's workers one perma tier",
  },
  coffeeBreak: {
    label: "Coffee Break",
    color: COLOR.amberMuted,
    image: "crits/mediterraneanFeasts/coffeeBreak.webp",
    description: "Pays 39 times the highest floor's upgrade price in cash",
  },
  figAndOlivePlatter: {
    label: "Fig And Olive Platter",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/figAndOlivePlatter.webp",
    description: "Pays 43 times the highest floor's upgrade price in cash",
  },
  giantCrepe: {
    label: "Giant Crepe",
    color: COLOR.gold,
    image: "crits/mediterraneanFeasts/giantCrepe.webp",
    description: "Promotes 89.5% of this building's workers one perma tier",
  },
  goldenPiePlate: {
    label: "Golden Pie Plate",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/goldenPiePlate.webp",
    description: "Promotes 90.5% of this building's workers one perma tier",
  },
  layeredPastrySpread: {
    label: "Layered Pastry Spread",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/layeredPastrySpread.webp",
    description: "Promotes 91% of this building's workers one perma tier",
  },
  lemonMussels: {
    label: "Lemon Mussels",
    color: COLOR.gold,
    image: "crits/mediterraneanFeasts/lemonMussels.webp",
    description: "Pays 63 times the highest floor's upgrade price in cash",
  },
  littlePlates: {
    label: "Little Plates",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/littlePlates.webp",
    description: "Pays 64 times the highest floor's upgrade price in cash",
  },
  meatballMezze: {
    label: "Meatball Mezze",
    color: COLOR.supplyRunTan,
    image: "crits/mediterraneanFeasts/meatballMezze.webp",
    description: "Promotes 92.5% of this building's workers one perma tier",
  },
  mustardJarSalmon: {
    label: "Mustard Jar Salmon",
    color: COLOR.supplyRunTan,
    image: "crits/mediterraneanFeasts/mustardJarSalmon.webp",
    description: "Spreads 77 free upgrades over this floor and the ones below",
  },
  oktoberfest: {
    label: "Oktoberfest",
    color: COLOR.supplyRunTan,
    image: "crits/mediterraneanFeasts/oktoberfest.webp",
    description: "Spreads 78 free upgrades over this floor and the ones below",
  },
  oliveOilTrio: {
    label: "Olive Oil Trio",
    color: COLOR.headhunterRust,
    image: "crits/mediterraneanFeasts/oliveOilTrio.webp",
    description: "Promotes 93.5% of this building's workers one perma tier",
  },
  paellaPicnic: {
    label: "Paella Picnic",
    color: COLOR.gold,
    image: "crits/mediterraneanFeasts/paellaPicnic.webp",
    description: "Spreads 79 free upgrades over this floor and the ones below",
  },
  pepperoniTwirl: {
    label: "Pepperoni Twirl",
    color: COLOR.headhunterRust,
    image: "crits/mediterraneanFeasts/pepperoniTwirl.webp",
    description: "Promotes 94% of this building's workers one perma tier",
  },
  polentaMountain: {
    label: "Polenta Mountain",
    color: COLOR.headhunterRust,
    image: "crits/mediterraneanFeasts/polentaMountain.webp",
    description: "Promotes 94.5% of this building's workers one perma tier",
  },
  pomegranateKebab: {
    label: "Pomegranate Kebab",
    color: COLOR.gold,
    image: "crits/mediterraneanFeasts/pomegranateKebab.webp",
    description: "Pays 70 times the highest floor's upgrade price in cash",
  },
  pretzelBangers: {
    label: "Pretzel Bangers",
    color: COLOR.supplyRunTan,
    image: "crits/mediterraneanFeasts/pretzelBangers.webp",
    description: "Promotes 95% of this building's workers one perma tier",
  },
  pretzelPileup: {
    label: "Pretzel Pileup",
    color: COLOR.amberMuted,
    image: "crits/mediterraneanFeasts/pretzelPileup.webp",
    description: "Pays 71 times the highest floor's upgrade price in cash",
  },
  sausagePotLunch: {
    label: "Sausage Pot Lunch",
    color: COLOR.headhunterRust,
    image: "crits/mediterraneanFeasts/sausagePotLunch.webp",
    description: "Promotes 97% of this building's workers one perma tier",
  },
  smorgasbord: {
    label: "Smorgasbord",
    color: COLOR.teaBreakBrown,
    image: "crits/mediterraneanFeasts/smorgasbord.webp",
    description: "Pays 76 times the highest floor's upgrade price in cash",
  },
  sourCreamPancakes: {
    label: "Sour Cream Pancakes",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/sourCreamPancakes.webp",
    description: "Spreads 87 free upgrades over this floor and the ones below",
  },
  stuffedGrapeLeaves: {
    label: "Stuffed Grape Leaves",
    color: COLOR.amberMuted,
    image: "crits/mediterraneanFeasts/stuffedGrapeLeaves.webp",
    description: "Spreads 88 free upgrades over this floor and the ones below",
  },
  tagineTable: {
    label: "Tagine Table",
    color: COLOR.headhunterRust,
    image: "crits/mediterraneanFeasts/tagineTable.webp",
    description: "Pays 79 times the highest floor's upgrade price in cash",
  },
  twoGlassTapas: {
    label: "Two Glass Tapas",
    color: COLOR.gold,
    image: "crits/mediterraneanFeasts/twoGlassTapas.webp",
    description: "Promotes 100% of this building's workers one perma tier",
  },
  woodenMugGrill: {
    label: "Wooden Mug Grill",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/woodenMugGrill.webp",
    description: "Pays 82 times the highest floor's upgrade price in cash",
  },
  baklavaMezze: {
    label: "Baklava Mezze",
    color: COLOR.amberMuted,
    image: "crits/mediterraneanFeasts/baklavaMezze.webp",
    description: "Spreads 94 free upgrades over this floor and the ones below",
  },
  cevapiEspresso: {
    label: "Cevapi Espresso",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/cevapiEspresso.webp",
    description: "Spreads 96 free upgrades over this floor and the ones below",
  },
  cucumberSoupMeze: {
    label: "Cucumber Soup Meze",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/cucumberSoupMeze.webp",
    description: "Pays 87 times the highest floor's upgrade price in cash",
  },
  flatbreadFingers: {
    label: "Flatbread Fingers",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/flatbreadFingers.webp",
    description: "Spreads 99 free upgrades over this floor and the ones below",
  },
  honeyPotBanitsa: {
    label: "Honey Pot Banitsa",
    color: COLOR.chairGiveawayBrown,
    image: "crits/mediterraneanFeasts/honeyPotBanitsa.webp",
    description: "Spreads 101 free upgrades over this floor and the ones below",
  },
  roastedPepperFeast: {
    label: "Roasted Pepper Feast",
    color: COLOR.redActive,
    image: "crits/mediterraneanFeasts/roastedPepperFeast.webp",
    description: "Spreads 107 free upgrades over this floor and the ones below",
  },
} as const satisfies Record<string, FeaturedCritData>;
