import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const PAIRED_POSES_CRITS = {
  blueLipsRecline: {
    label: "Blue Lips Recline",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/blueLipsRecline.webp",
    description: "Promotes 25.5% of this floor's workers two perma tiers",
  },
  crimsonTopSpread: {
    label: "Crimson Top Spread",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/crimsonTopSpread.webp",
    description: "Promotes 27% of this floor's workers two perma tiers",
  },
  crossedArms: {
    label: "Crossed Arms",
    color: COLOR.teal,
    image: "crits/pairedPoses/crossedArms.webp",
    description: "Promotes 11% of this building's workers one perma tier",
  },
  crossedLegsChill: {
    label: "Crossed Legs Chill",
    color: COLOR.fastForwardBlue,
    image: "crits/pairedPoses/crossedLegsChill.webp",
    description: "Promotes 27.5% of this floor's workers two perma tiers",
  },
  frontRowFeet: {
    label: "Front Row Feet",
    color: COLOR.teal,
    image: "crits/pairedPoses/frontRowFeet.webp",
    description: "Promotes 29.5% of this floor's workers two perma tiers",
  },
  gymMat: {
    label: "Gym Mat",
    color: COLOR.fastForwardBlue,
    image: "crits/pairedPoses/gymMat.webp",
    description: "Promotes 32% of this floor's workers two perma tiers",
  },
  handsPlanted: {
    label: "Hands Planted",
    color: COLOR.springCleaningMint,
    image: "crits/pairedPoses/handsPlanted.webp",
    description: "Promotes 21% of this building's workers one perma tier",
  },
  jumboSoles: {
    label: "Jumbo Soles",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/jumboSoles.webp",
    description: "Promotes 22% of this building's workers one perma tier",
  },
  kneeHuggers: {
    label: "Knee Huggers",
    color: COLOR.springCleaningMint,
    image: "crits/pairedPoses/kneeHuggers.webp",
    description: "Promotes 42% of this floor's workers two perma tiers",
  },
  kneesUp: {
    label: "Knees Up",
    color: COLOR.rainCheckBlue,
    image: "crits/pairedPoses/kneesUp.webp",
    description: "Promotes 22.5% of this building's workers one perma tier",
  },
  leanBackLasses: {
    label: "Lean Back Lasses",
    color: COLOR.fastForwardBlue,
    image: "crits/pairedPoses/leanBackLasses.webp",
    description: "Promotes 42.5% of this floor's workers two perma tiers",
  },
  lotusLounge: {
    label: "Lotus Lounge",
    color: COLOR.rainCheckBlue,
    image: "crits/pairedPoses/lotusLounge.webp",
    description: "Promotes 24.5% of this building's workers one perma tier",
  },
  midnightManeSprawl: {
    label: "Midnight Mane Sprawl",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/midnightManeSprawl.webp",
    description: "Promotes 25% of this building's workers one perma tier",
  },
  neonStripeLean: {
    label: "Neon Stripe Lean",
    color: COLOR.fastForwardBlue,
    image: "crits/pairedPoses/neonStripeLean.webp",
    description: "Promotes 27% of this building's workers one perma tier",
  },
  shySitters: {
    label: "Shy Sitters",
    color: COLOR.fastForwardBlue,
    image: "crits/pairedPoses/shySitters.webp",
    description: "Promotes 39.5% of this building's workers one perma tier",
  },
  solesUpFront: {
    label: "Soles Up Front",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/solesUpFront.webp",
    description: "Promotes 64% of this floor's workers two perma tiers",
  },
  wideSitBraid: {
    label: "Wide Sit Braid",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/wideSitBraid.webp",
    description: "Promotes 67.5% of this floor's workers two perma tiers",
  },
  ropeBraidRest: {
    label: "Rope Braid Rest",
    color: COLOR.rainCheckBlue,
    image: "crits/pairedPoses/ropeBraidRest.webp",
    description: "Promotes 62% of this floor's workers two perma tiers",
  },
  longPonytailRecline: {
    label: "Long Ponytail Recline",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/longPonytailRecline.webp",
    description: "Promotes 44% of this floor's workers two perma tiers",
  },
  silverPonytailLean: {
    label: "Silver Ponytail Lean",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/silverPonytailLean.webp",
    description: "Promotes 81% of this floor's workers two perma tiers",
  },
  wavyLocksLean: {
    label: "Wavy Locks Lean",
    color: COLOR.fastForwardBlue,
    image: "crits/pairedPoses/wavyLocksLean.webp",
    description: "Promotes 82.5% of this floor's workers two perma tiers",
  },
  twinBobTiptoes: {
    label: "Twin Bob Tiptoes",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/twinBobTiptoes.webp",
    description: "Promotes 66.5% of this floor's workers two perma tiers",
  },
  mintGlowLounge: {
    label: "Mint Glow Lounge",
    color: COLOR.fastForwardBlue,
    image: "crits/pairedPoses/mintGlowLounge.webp",
    description: "Promotes 80% of this floor's workers two perma tiers",
  },
  chinLift: {
    label: "Chin Lift",
    color: COLOR.nightOwlIndigo,
    image: "crits/pairedPoses/chinLift.webp",
    description: "Adds 63.9% of your total income",
  },
  poutAndPose: {
    label: "Pout And Pose",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/poutAndPose.webp",
    description: "Adds 61.5% of your total income",
  },
  capeSwish: {
    label: "Cape Swish",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/capeSwish.webp",
    description: "Adds 164s of your company's income",
  },
  slenderSwirl: {
    label: "Slender Swirl",
    color: COLOR.fullHouseCrimson,
    image: "crits/pairedPoses/slenderSwirl.webp",
    description: "Adds 62.3% of your total income",
  },
  proudGuardian: {
    label: "Proud Guardian",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/proudGuardian.webp",
    description: "Adds 61.8% of your total income",
  },
  powerBun: {
    label: "Power Bun",
    color: COLOR.overflowBlue,
    image: "crits/pairedPoses/powerBun.webp",
    description: "Adds 61.6% of your total income",
  },
  coralPads: {
    label: "Coral Pads",
    color: COLOR.teamBuildingCoral,
    image: "crits/pairedPoses/coralPads.webp",
    description: "Promotes 26.5% of this floor's workers two perma tiers",
  },
  plumLipsPower: {
    label: "Plum Lips Power",
    color: COLOR.springCleaningMint,
    image: "crits/pairedPoses/plumLipsPower.webp",
    description: "Promotes 80.5% of this floor's workers two perma tiers",
  },
} as const satisfies Record<string, FeaturedCritData>;
