import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const SOLE_CLOSEUPS_CRITS = {
  archEnemyAssets: {
    label: "Arch Enemy Assets",
    color: COLOR.redActive,
    image: "crits/soleCloseups/archEnemyAssets.webp",
    description: "Boosts every worker for 38s",
  },
  barefootBanker: {
    label: "Barefoot Banker",
    color: COLOR.supplyRunTan,
    image: "crits/soleCloseups/barefootBanker.webp",
    description: "Hires 2 free workers and a manager on every unlocked floor",
  },
  bestFootForward: {
    label: "Best Foot Forward",
    color: COLOR.teaBreakBrown,
    image: "crits/soleCloseups/bestFootForward.webp",
    description: "Repeats the crit above and below, 62% chance to keep spreading",
  },
  coldFeetCash: {
    label: "Cold Feet Cash",
    color: COLOR.coinGold,
    image: "crits/soleCloseups/coldFeetCash.webp",
    description: "One tier promotion and seven upgrades here",
  },
  footInTheDoor: {
    label: "Foot In The Door",
    color: COLOR.coinGold,
    image: "crits/soleCloseups/footInTheDoor.webp",
    description: "Cuts every price in this building by 1.1%",
  },
  heelTurnHaul: {
    label: "Heel Turn Haul",
    color: COLOR.peppermintPink,
    image: "crits/soleCloseups/heelTurnHaul.webp",
    description: "Boosts this floor's workers for 29s",
  },
  soleProprietor: {
    label: "Sole Proprietor",
    color: COLOR.overflowBlue,
    image: "crits/soleCloseups/soleProprietor.webp",
    description: "Hires 1 free worker on alternating floors",
  },
  tenToeTreasury: {
    label: "Ten Toe Treasury",
    color: COLOR.fastForwardBlue,
    image: "crits/soleCloseups/tenToeTreasury.webp",
    description: "One tier promotion and eight upgrades here",
  },
  toeTally: {
    label: "Toe Tally",
    color: COLOR.fullHouseCrimson,
    image: "crits/soleCloseups/toeTally.webp",
    description: "Adds 44s of your company's income",
  },
  doubleSoleMoo: {
    label: "Double Sole Moo",
    color: COLOR.sameBoatCoral,
    image: "crits/soleCloseups/doubleSoleMoo.webp",
    description: "Cuts every price in this building by 16.5%",
  },
  lazySundaySoles: {
    label: "Lazy Sunday Soles",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/soleCloseups/lazySundaySoles.webp",
    description: "Repeats the crit on the floor below, 89% chance to keep falling",
  },
  logLoungeSoles: {
    label: "Log Lounge Soles",
    color: COLOR.luckyCloverGreen,
    image: "crits/soleCloseups/logLoungeSoles.webp",
    description: "Adds 55s of your company's income",
  },
  mirrorImageSoles: {
    label: "Mirror Image Soles",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/soleCloseups/mirrorImageSoles.webp",
    description: "Boosts every worker for 145s, counting as 3 extra workers",
  },
  muscleToeMogul: {
    label: "Muscle Toe Mogul",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/soleCloseups/muscleToeMogul.webp",
    description: "Repeats the crit on the floor above, 90% chance to keep climbing",
  },
  scrapyardSoles: {
    label: "Scrapyard Soles",
    color: COLOR.bullMarketGreen,
    image: "crits/soleCloseups/scrapyardSoles.webp",
    description: "Repeats the crit on the floor below, 90% chance to keep falling",
  },
  soleSpotlight: {
    label: "Sole Spotlight",
    color: COLOR.luckyCloverGreen,
    image: "crits/soleCloseups/soleSpotlight.webp",
    description: "Cuts every price in this building by 19%",
  },
  sunnySoleSisters: {
    label: "Sunny Sole Sisters",
    color: COLOR.summerSaleOrange,
    image: "crits/soleCloseups/sunnySoleSisters.webp",
    description: "Adds 57s of your company's income",
  },
  tickleTax: {
    label: "Tickle Tax",
    color: COLOR.suppliesGiveawayLime,
    image: "crits/soleCloseups/tickleTax.webp",
    description: "Repeats the crit on the floor above, 91% chance to keep climbing",
  },
  feelingBlue: {
    label: "Feeling Blue",
    color: COLOR.overflowBlue,
    image: "crits/soleCloseups/feelingBlue.webp",
    description: "Adds 22% of your total income",
  },
  oddCouple: {
    label: "Odd Couple",
    color: COLOR.gold,
    image: "crits/soleCloseups/oddCouple.webp",
    description: "Adds 22.1% of your total income",
  },
  pixieCutPayday: {
    label: "Pixie Cut Payday",
    color: COLOR.nightShiftIndigo,
    image: "crits/soleCloseups/pixieCutPayday.webp",
    description: "Adds 22.9% of your total income",
  },
  faceValue: {
    label: "Face Value",
    color: COLOR.amberMuted,
    image: "crits/soleCloseups/faceValue.webp",
    description: "Adds 23.1% of your total income",
  },
  heelDeal: {
    label: "Heel Deal",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/soleCloseups/heelDeal.webp",
    description: "Eight instant payouts on this floor",
  },
  soleCustody: {
    label: "Sole Custody",
    color: COLOR.summerSaleOrange,
    image: "crits/soleCloseups/soleCustody.webp",
    description: "Adds 23.2% of your total income",
  },
  footTheBill: {
    label: "Foot the Bill",
    color: COLOR.amberMuted,
    image: "crits/soleCloseups/footTheBill.webp",
    description: "Thirty-six instant payouts on this floor",
  },
  toeToToeTrade: {
    label: "Toe to Toe Trade",
    color: COLOR.teaBreakBrown,
    image: "crits/soleCloseups/toeToToeTrade.webp",
    description: "Fifty-two free upgrades on this floor",
  },
  toeTussle: {
    label: "Toe Tussle",
    color: COLOR.gold,
    image: "crits/soleCloseups/toeTussle.webp",
    description: "Grows every unlocked floor's level by 2.2% in free upgrades",
  },
  toeGrip: {
    label: "Toe Grip",
    color: COLOR.amberMuted,
    image: "crits/soleCloseups/toeGrip.webp",
    description: "Spreads 12 free upgrades over the lowest-level floors",
  },
  giantArchDare: {
    label: "Giant Arch Dare",
    color: COLOR.summerSaleOrange,
    image: "crits/soleCloseups/giantArchDare.webp",
    description: "Grows this floor's level by 6.3% in free upgrades",
  },
  peekabooSole: {
    label: "Peekaboo Sole",
    color: COLOR.coinGold,
    image: "crits/soleCloseups/peekabooSole.webp",
    description: "Grows this floor's level by 13.8% in free upgrades",
  },
  bigSoleSpread: {
    label: "Big Sole Spread",
    color: COLOR.coinGold,
    image: "crits/soleCloseups/bigSoleSpread.webp",
    description: "Grows this floor's level by 14.7% in free upgrades",
  },
  sidewaysSoles: {
    label: "Sideways Soles",
    color: COLOR.sameBoatCoral,
    image: "crits/soleCloseups/sidewaysSoles.webp",
    description: "Pays 129 times this floor's upgrade price in cash",
  },
  soleSandwich: {
    label: "Sole Sandwich",
    color: COLOR.coinGold,
    image: "crits/soleCloseups/soleSandwich.webp",
    description: "Grows every unlocked floor's level by 7.1% in free upgrades",
  },
} as const satisfies Record<string, FeaturedCritData>;
