import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const VOYAGES_CRITS = {
  anchorInk: {
    label: "Anchor Ink",
    color: COLOR.sameBoatCoral,
    image: "crits/voyages/anchorInk.webp",
    description: "Grows this floor's level by 20.1% in free upgrades",
  },
  blueSails: {
    label: "Blue Sails",
    color: COLOR.overflowBlue,
    image: "crits/voyages/blueSails.webp",
    description: "Spreads 169 free upgrades over the lowest-level floors",
  },
  grumpyDeckhands: {
    label: "Grumpy Deckhands",
    color: COLOR.amberMuted,
    image: "crits/voyages/grumpyDeckhands.webp",
    description: "Grows this floor's level by 20.2% in free upgrades",
  },
  hookAndScar: {
    label: "Hook And Scar",
    color: COLOR.sameBoatCoral,
    image: "crits/voyages/hookAndScar.webp",
    description: "Spreads 170 free upgrades over the lowest-level floors",
  },
  plumedPowerhouse: {
    label: "Plumed Powerhouse",
    color: COLOR.summerSaleOrange,
    image: "crits/voyages/plumedPowerhouse.webp",
    description: "Grows this floor's level by 20.3% in free upgrades",
  },
  shipmateSqueeze: {
    label: "Shipmate Squeeze",
    color: COLOR.amberMuted,
    image: "crits/voyages/shipmateSqueeze.webp",
    description: "Spreads 171 free upgrades over the lowest-level floors",
  },
  skullHatCrest: {
    label: "Skull Hat Crest",
    color: COLOR.amberMuted,
    image: "crits/voyages/skullHatCrest.webp",
    description: "Grows this floor's level by 20.4% in free upgrades",
  },
  stripedSkipper: {
    label: "Striped Skipper",
    color: COLOR.amberMuted,
    image: "crits/voyages/stripedSkipper.webp",
    description: "Spreads 172 free upgrades over the lowest-level floors",
  },
  tealPatch: {
    label: "Teal Patch",
    color: COLOR.amberMuted,
    image: "crits/voyages/tealPatch.webp",
    description: "Grows this floor's level by 20.5% in free upgrades",
  },
  doubleDenim: {
    label: "Double Denim",
    color: COLOR.amberMuted,
    image: "crits/voyages/doubleDenim.webp",
    description: "Adds 63.3% of your total income",
  },
  lassoLadies: {
    label: "Lasso Ladies",
    color: COLOR.supplyRunTan,
    image: "crits/voyages/lassoLadies.webp",
    description: "Adds 63.4% of your total income",
  },
  rodeoPals: {
    label: "Rodeo Pals",
    color: COLOR.nightShiftIndigo,
    image: "crits/voyages/rodeoPals.webp",
    description: "Adds 63.5% of your total income",
  },
  arenaAllies: {
    label: "Arena Allies",
    color: COLOR.amberMuted,
    image: "crits/voyages/arenaAllies.webp",
    description: "Adds 37.3% of your total income",
  },
  bronzeBreastplate: {
    label: "Bronze Breastplate",
    color: COLOR.amberMuted,
    image: "crits/voyages/bronzeBreastplate.webp",
    description: "Adds 37.4% of your total income",
  },
  colosseum: {
    label: "Colosseum",
    color: COLOR.gold,
    image: "crits/voyages/colosseum.webp",
    description: "Adds 37.5% of your total income",
  },
  gildedWarriors: {
    label: "Gilded Warriors",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/voyages/gildedWarriors.webp",
    description: "Adds 37.6% of your total income",
  },
  goldenGladiatrix: {
    label: "Golden Gladiatrix",
    color: COLOR.amberMuted,
    image: "crits/voyages/goldenGladiatrix.webp",
    description: "Adds 37.7% of your total income",
  },
  plumedHelmet: {
    label: "Plumed Helmet",
    color: COLOR.chairGiveawayBrown,
    image: "crits/voyages/plumedHelmet.webp",
    description: "Adds 37.8% of your total income",
  },
  sandalStrut: {
    label: "Sandal Strut",
    color: COLOR.goldenParachuteMarigold,
    image: "crits/voyages/sandalStrut.webp",
    description: "Adds 37.9% of your total income",
  },
  shieldWall: {
    label: "Shield Wall",
    color: COLOR.supplyRunTan,
    image: "crits/voyages/shieldWall.webp",
    description: "Adds 38% of your total income",
  },
  shortSwords: {
    label: "Short Swords",
    color: COLOR.amberMuted,
    image: "crits/voyages/shortSwords.webp",
    description: "Adds 38.1% of your total income",
  },
  templeMaidens: {
    label: "Temple Maidens",
    color: COLOR.sameBoatCoral,
    image: "crits/voyages/templeMaidens.webp",
    description: "Adds 38.2% of your total income",
  },
  togaParty: {
    label: "Toga Party",
    color: COLOR.teaBreakBrown,
    image: "crits/voyages/togaParty.webp",
    description: "Adds 38.3% of your total income",
  },
  chooChoo: {
    label: "Choo Choo",
    color: COLOR.rainCheckBlue,
    image: "crits/voyages/chooChoo.webp",
    description: "Adds 62.7% of your total income",
  },
  clockTower: {
    label: "Clock Tower",
    color: COLOR.overflowBlue,
    image: "crits/voyages/clockTower.webp",
    description: "Adds 62.8% of your total income",
  },
  commuterLine: {
    label: "Commuter Line",
    color: COLOR.rainCheckBlue,
    image: "crits/voyages/commuterLine.webp",
    description: "Adds 62.9% of your total income",
  },
  mainStreet: {
    label: "Main Street",
    color: COLOR.sameBoatCoral,
    image: "crits/voyages/mainStreet.webp",
    description: "Adds 63% of your total income",
  },
  rooftopRainbow: {
    label: "Rooftop Rainbow",
    color: COLOR.fastForwardBlue,
    image: "crits/voyages/rooftopRainbow.webp",
    description: "Adds 63.1% of your total income",
  },
  steamExpress: {
    label: "Steam Express",
    color: COLOR.overflowBlue,
    image: "crits/voyages/steamExpress.webp",
    description: "Adds 63.2% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
