import { COLOR } from "../../../palette";
import type { FeaturedCritData } from "./types";

export const WARHAMMER_ARMOR_CRITS = {
  amberVisor: {
    label: "Amber Visor",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/amberVisor.webp",
    description: "Promotes 87% of this floor's workers two perma tiers",
  },
  blueGemPlate: {
    label: "Blue Gem Plate",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/blueGemPlate.webp",
    description: "Promotes 64.5% of this building's workers one perma tier",
  },
  bullseyePauldron: {
    label: "Bullseye Pauldron",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/bullseyePauldron.webp",
    description: "Promotes 65% of this building's workers one perma tier",
  },
  copperGrille: {
    label: "Copper Grille",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/copperGrille.webp",
    description: "Promotes 88% of this floor's workers two perma tiers",
  },
  crimsonWingHelm: {
    label: "Crimson Wing Helm",
    color: COLOR.rainCheckBlue,
    image: "crits/warhammerArmor/crimsonWingHelm.webp",
    description: "Promotes 88.5% of this floor's workers two perma tiers",
  },
  crossedBarrels: {
    label: "Crossed Barrels",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/crossedBarrels.webp",
    description: "Promotes 66% of this building's workers one perma tier",
  },
  eagleCrest: {
    label: "Eagle Crest",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/eagleCrest.webp",
    description: "Promotes 89% of this floor's workers two perma tiers",
  },
  eagleHelm: {
    label: "Eagle Helm",
    color: COLOR.rainCheckBlue,
    image: "crits/warhammerArmor/eagleHelm.webp",
    description: "Promotes 66.5% of this building's workers one perma tier",
  },
  eagleMedallion: {
    label: "Eagle Medallion",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/eagleMedallion.webp",
    description: "Promotes 89.5% of this floor's workers two perma tiers",
  },
  gemSkull: {
    label: "Gem Skull",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/gemSkull.webp",
    description: "Promotes 67% of this building's workers one perma tier",
  },
  goldenWingHelm: {
    label: "Golden Wing Helm",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/goldenWingHelm.webp",
    description: "Adds 110s of your company's income",
  },
  goldFaceplate: {
    label: "Gold Faceplate",
    color: COLOR.rainCheckBlue,
    image: "crits/warhammerArmor/goldFaceplate.webp",
    description: "Adds 111s of your company's income",
  },
  goldGlyphs: {
    label: "Gold Glyphs",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/goldGlyphs.webp",
    description: "Adds 112s of your company's income",
  },
  goldTrim: {
    label: "Gold Trim",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/goldTrim.webp",
    description: "Adds 35.1% of your total income",
  },
  greenVisor: {
    label: "Green Visor",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/greenVisor.webp",
    description: "Adds 35.2% of your total income",
  },
  gunwingSkull: {
    label: "Gunwing Skull",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/gunwingSkull.webp",
    description: "Adds 35.3% of your total income",
  },
  redChestPlate: {
    label: "Red Chest Plate",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/redChestPlate.webp",
    description: "Adds 35.4% of your total income",
  },
  redLaurelSkull: {
    label: "Red Laurel Skull",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/redLaurelSkull.webp",
    description: "Adds 35.6% of your total income",
  },
  redStarPauldron: {
    label: "Red Star Pauldron",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/redStarPauldron.webp",
    description: "Adds 35.7% of your total income",
  },
  redStripeHelm: {
    label: "Red Stripe Helm",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/redStripeHelm.webp",
    description: "Adds 35.8% of your total income",
  },
  shieldWings: {
    label: "Shield Wings",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/shieldWings.webp",
    description: "Adds 35.9% of your total income",
  },
  shoulderSigils: {
    label: "Shoulder Sigils",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/shoulderSigils.webp",
    description: "Adds 36% of your total income",
  },
  sigilChest: {
    label: "Sigil Chest",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/sigilChest.webp",
    description: "Adds 36.1% of your total income",
  },
  silverVisor: {
    label: "Silver Visor",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/silverVisor.webp",
    description: "Adds 36.2% of your total income",
  },
  silverWings: {
    label: "Silver Wings",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/silverWings.webp",
    description: "Adds 36.3% of your total income",
  },
  skullPauldron: {
    label: "Skull Pauldron",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/skullPauldron.webp",
    description: "Adds 36.4% of your total income",
  },
  snowCrest: {
    label: "Snow Crest",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/snowCrest.webp",
    description: "Adds 36.5% of your total income",
  },
  splitSkull: {
    label: "Split Skull",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/splitSkull.webp",
    description: "Adds 36.6% of your total income",
  },
  steelFaceplate: {
    label: "Steel Faceplate",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/steelFaceplate.webp",
    description: "Adds 36.7% of your total income",
  },
  tealVisor: {
    label: "Teal Visor",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/tealVisor.webp",
    description: "Adds 36.8% of your total income",
  },
  whiteRune: {
    label: "White Rune",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/whiteRune.webp",
    description: "Adds 36.9% of your total income",
  },
  wingedSkull: {
    label: "Winged Skull",
    color: COLOR.fastForwardBlue,
    image: "crits/warhammerArmor/wingedSkull.webp",
    description: "Adds 37% of your total income",
  },
  yellowVisor: {
    label: "Yellow Visor",
    color: COLOR.overflowBlue,
    image: "crits/warhammerArmor/yellowVisor.webp",
    description: "Adds 37.2% of your total income",
  },
} as const satisfies Record<string, FeaturedCritData>;
