import { loadImage } from "../utils";

const PUBLIC_ASSET_BASE = import.meta.env.BASE_URL;
const themeAssetUrl = (filename: string) => `${PUBLIC_ASSET_BASE}${filename}`;
const critAssetUrl = (filename: string) => `${PUBLIC_ASSET_BASE}${filename}`;
const sharedThemeImages = new Set([
  "city.png",
  "mapBg.png",
  "wallMaterial.png",
  "coin.png",
  "mouse.png",
  "isometricBox.png",
  "isometricYarn.png",
  "merge.png",
  "skyscraper.png",
  "cashRegister.png",
  "clock.png",
]);
const backgroundFiles = ["bg2.png", "bg4.png", "bg6.png"];
const cloudFiles = [
  "cloud0.png",
  "cloud1.png",
  "cloud2.png",
  "cloud3.png",
  "cloud4.png",
];

// Every sprite this game loads, by logical name -> its filename in public/assets/.
const SPRITE_FILES = {
  worker: "workerWalk.png",
  manager: "managerWalk.png",
  coinSpin: "coinSpin.png",
  cashBill: "cashBillFlutter.png",
} as const;
export type SpriteName = keyof typeof SPRITE_FILES;

// every flat single-file image this game loads, by logical name -> its filename
// inside dist/ root — same reasoning as SPRITE_FILES above
export const IMAGE_FILES = {
  chromeDome: "crits/cyberpunk/chromeDome.png",
  skullSyndicate: "crits/cyberpunk/skullSyndicate.png",
  circuitDuchess: "crits/cyberpunk/circuitDuchess.png",
  cyberCat: "crits/cyberpunk/cyberCat.png",
  chromeChassis: "crits/cyberpunk/chromeChassis.png",
  elbowRoom: "crits/cyberpunk/elbowRoom.png",
  heartware: "crits/cyberpunk/heartware.png",
  pulseDividend: "crits/cyberpunk/pulseDividend.png",
  neonNegotiator: "crits/cyberpunk/neonNegotiator.png",
  platinumRefrain: "crits/cyberpunk/platinumRefrain.png",
  retinaRoyale: "crits/cyberpunk/retinaRoyale.png",
  silverHandshake: "crits/cyberpunk/silverHandshake.png",
  staticEncore: "crits/cyberpunk/staticEncore.png",
  goldenSkull: "crits/attitude/goldenSkull.png",
  lordOfMurder: "crits/attitude/lordOfMurder.png",
  speedDemon: "crits/attitude/speedDemon.png",
  bubbleButt: "crits/attitude/bubbleButt.png",
  canNotLie: "crits/attitude/canNotLie.png",
  badonkadonk: "crits/attitude/badonkadonk.png",
  demoncBuns: "crits/attitude/demoncBuns.png",
  infernalInterest: "crits/attitude/infernalInterest.png",
  dropItLow: "crits/attitude/dropItLow.png",
  kittyWagon: "crits/attitude/kittyWagon.png",
  madeYouLook: "crits/attitude/madeYouLook.png",
  wagonWarrior: "crits/attitude/wagonWarrior.png",
  californiumCrescendo: "crits/elements/californiumCrescendo.png",
  einsteiniumEpiphany: "crits/elements/einsteiniumEpiphany.png",
  fermiumFormula: "crits/elements/fermiumFormula.png",
  mendeleviumMajesty: "crits/elements/mendeleviumMajesty.png",
  nobeliumLaureate: "crits/elements/nobeliumLaureate.png",
  lawrenciumLightspeed: "crits/elements/lawrenciumLightspeed.png",
  rutherfordiumReach: "crits/elements/rutherfordiumReach.png",
  seaborgiumSwell: "crits/elements/seaborgiumSwell.png",
  bohriumSummit: "crits/elements/bohriumSummit.png",
  hassiumMeteor: "crits/elements/hassiumMeteor.png",
  meitneriumMarvel: "crits/elements/meitneriumMarvel.png",
  darmstadtiumDowntown: "crits/elements/darmstadtiumDowntown.png",
  roentgeniumRevelation: "crits/elements/roentgeniumRevelation.png",
  coperniciumCarousel: "crits/elements/coperniciumCarousel.png",
  nihoniumDaybreak: "crits/elements/nihoniumDaybreak.png",
  fleroviumFortress: "crits/elements/fleroviumFortress.png",
  moscoviumMosaic: "crits/elements/moscoviumMosaic.png",
  livermoriumLightning: "crits/elements/livermoriumLightning.png",
  tennessineTwinkle: "crits/elements/tennessineTwinkle.png",
  oganessonOdyssey: "crits/elements/oganessonOdyssey.png",
  heavyElement: "crits/elements/heavyElement.png",
  osmiumRegalia: "crits/elements/osmiumRegalia.png",
  iridiumAegis: "crits/elements/iridiumAegis.png",
  mercuryFlow: "crits/elements/mercuryFlow.png",
  thalliumThrive: "crits/elements/thalliumThrive.png",
  leadLode: "crits/elements/leadLode.png",
  bismuthBastion: "crits/elements/bismuthBastion.png",
  poloniumPrism: "crits/elements/poloniumPrism.png",
  astatineAurora: "crits/elements/astatineAurora.png",
  radonRipple: "crits/elements/radonRipple.png",
  franciumFortune: "crits/elements/franciumFortune.png",
  radiumRhythm: "crits/elements/radiumRhythm.png",
  actiniumArc: "crits/elements/actiniumArc.png",
  thoriumThrone: "crits/elements/thoriumThrone.png",
  protactiniumOrbit: "crits/elements/protactiniumOrbit.png",
  neptuniumNova: "crits/elements/neptuniumNova.png",
  plutoniumPulse: "crits/elements/plutoniumPulse.png",
  americiumAlarm: "crits/elements/americiumAlarm.png",
  curiumCrucible: "crits/elements/curiumCrucible.png",
  berkeliumBreakthrough: "crits/elements/berkeliumBreakthrough.png",
  nucleusDividend: "crits/elements/nucleusDividend.png",
  hydrogenHype: "crits/elements/hydrogenHype.png",
  heliumHighrise: "crits/elements/heliumHighrise.png",
  lithiumLift: "crits/elements/lithiumLift.png",
  berylliumBrilliance: "crits/elements/berylliumBrilliance.png",
  carbonCrown: "crits/elements/carbonCrown.png",
  nitrogenNimbus: "crits/elements/nitrogenNimbus.png",
  oxygenOverdrive: "crits/elements/oxygenOverdrive.png",
  fluorineFlash: "crits/elements/fluorineFlash.png",
  sodiumSprinkle: "crits/elements/sodiumSprinkle.png",
  magnesiumMagnificence: "crits/elements/magnesiumMagnificence.png",
  aluminumAllStar: "crits/elements/aluminumAllStar.png",
  siliconSpark: "crits/elements/siliconSpark.png",
  phosphorusFlare: "crits/elements/phosphorusFlare.png",
  sulfurSunshine: "crits/elements/sulfurSunshine.png",
  chlorineConfetti: "crits/elements/chlorineConfetti.png",
  argonAfterglow: "crits/elements/argonAfterglow.png",
  potassiumPop: "crits/elements/potassiumPop.png",
  calciumCornerstone: "crits/elements/calciumCornerstone.png",
  scandiumStronghold: "crits/elements/scandiumStronghold.png",
  titaniumTakeoff: "crits/elements/titaniumTakeoff.png",
  vanadiumVoltage: "crits/elements/vanadiumVoltage.png",
  chromiumGleam: "crits/elements/chromiumGleam.png",
  manganeseMomentum: "crits/elements/manganeseMomentum.png",
  ironEmpire: "crits/elements/ironEmpire.png",
  cobaltCharge: "crits/elements/cobaltCharge.png",
  nickelNestEgg: "crits/elements/nickelNestEgg.png",
  copperCurrent: "crits/elements/copperCurrent.png",
  zincZing: "crits/elements/zincZing.png",
  galliumGlitter: "crits/elements/galliumGlitter.png",
  germaniumGenius: "crits/elements/germaniumGenius.png",
  arsenicAlchemy: "crits/elements/arsenicAlchemy.png",
  seleniumSunburst: "crits/elements/seleniumSunburst.png",
  bromineBounty: "crits/elements/bromineBounty.png",
  kryptonKeepsake: "crits/elements/kryptonKeepsake.png",
  rubidiumRadiance: "crits/elements/rubidiumRadiance.png",
  strontiumSpectacle: "crits/elements/strontiumSpectacle.png",
  yttriumYield: "crits/elements/yttriumYield.png",
  zirconiumZenith: "crits/elements/zirconiumZenith.png",
  niobiumNexus: "crits/elements/niobiumNexus.png",
  molybdenumMachine: "crits/elements/molybdenumMachine.png",
  technetiumTimebank: "crits/elements/technetiumTimebank.png",
  rutheniumRiches: "crits/elements/rutheniumRiches.png",
  rhodiumReflection: "crits/elements/rhodiumReflection.png",
  palladiumPilot: "crits/elements/palladiumPilot.png",
  silverMoonrise: "crits/elements/silverMoonrise.png",
  cadmiumCatalyst: "crits/elements/cadmiumCatalyst.png",
  indiumInsight: "crits/elements/indiumInsight.png",
  tinTreasure: "crits/elements/tinTreasure.png",
  antimonyAscension: "crits/elements/antimonyAscension.png",
  telluriumTreasurelight: "crits/elements/telluriumTreasurelight.png",
  iodineIridescence: "crits/elements/iodineIridescence.png",
  xenonSpotlight: "crits/elements/xenonSpotlight.png",
  cesiumClockwork: "crits/elements/cesiumClockwork.png",
  bariumBeacon: "crits/elements/bariumBeacon.png",
  lanthanumLuster: "crits/elements/lanthanumLuster.png",
  ceriumShine: "crits/elements/ceriumShine.png",
  praseodymiumPrism: "crits/elements/praseodymiumPrism.png",
  neodymiumNorthstar: "crits/elements/neodymiumNorthstar.png",
  promethiumPulse: "crits/elements/promethiumPulse.png",
  samariumSanctuary: "crits/elements/samariumSanctuary.png",
  europiumEncore: "crits/elements/europiumEncore.png",
  gadoliniumGlance: "crits/elements/gadoliniumGlance.png",
  terbiumTempo: "crits/elements/terbiumTempo.png",
  dysprosiumDirection: "crits/elements/dysprosiumDirection.png",
  holmiumHalo: "crits/elements/holmiumHalo.png",
  erbiumElegance: "crits/elements/erbiumElegance.png",
  thuliumThaw: "crits/elements/thuliumThaw.png",
  ytterbiumHourglass: "crits/elements/ytterbiumHourglass.png",
  lutetiumLimelight: "crits/elements/lutetiumLimelight.png",
  hafniumHorizon: "crits/elements/hafniumHorizon.png",
  tantalumTrove: "crits/elements/tantalumTrove.png",
  tungstenTriumph: "crits/elements/tungstenTriumph.png",
  rheniumRocket: "crits/elements/rheniumRocket.png",
  platinumPodium: "crits/elements/platinumPodium.png",
  goldenAtom: "crits/elements/goldenAtom.png",
  uraniumUplift: "crits/elements/uraniumUplift.png",
  city: "city.png", // distant tiled skyline behind buildings
  cityMapBackground: "mapBg.png", // city map screen's own backdrop
  cloudCatIdle: "cloudCatIdle.png", // city map corner mascot, resting pose
  cloudCatHappy: "cloudCatHappy.png", // same mascot, cheering pose
  wallMaterial: "wallMaterial.png", // exterior wall/floor-divider tile material
  coin: "coin.png", // flat coin icon (HUD/menus)
  mouse: "mouse.png", // free-boost critter
  officeChairsIcon: "isometricBox.png", // office-chairs upgrade icon
  officeSuppliesIcon: "isometricYarn.png", // office-supplies upgrade icon
  merge: "merge.png", // Merge companies' own menu icon
  skyscraper: "skyscraper.png", // Create new Company / Renovate floors icon
  cashRegister: "cashRegister.png", // Trigger sales event's own menu icon
  clock: "clock.png", // Work overtime's own menu icon
  chain: "chain.png", // Chain crit flash's own backdrop icon
  dominoEffect: "dominoEffect.png", // Domino Effect crit flash's own backdrop icon
  blueprint: "blueprint.png", // Blueprint crit flash's own backdrop icon
  executiveBonus: "executiveBonus.png", // Executive Bonus crit flash's own backdrop icon
  powerSurge: "powerSurge.png", // Power Surge crit flash's own backdrop icon
  priceMatch: "priceMatch.png", // Price Match crit flash's own backdrop icon
  firstClass: "firstClass.png", // First Class crit flash's own backdrop icon
  ball: "ball.png", // Bounce crit flash's own backdrop icon
  explosion: "explosion.png", // Explosion crit flash's own backdrop icon
  booty: "booty.png", // Booty crit flash's own backdrop icon
  cashFlow: "cashFlow.png", // Cash Flow crit flash's own backdrop icon
  upgrade: "upgrade.png", // Upgrade crit flash's own backdrop icon
  peppermint: "peppermint.png", // Peppermint crit flash's own backdrop icon
  heaven: "heaven.png", // Heavenly crit flash's own backdrop icon
  skip: "skip.png", // Skip crit flash's own backdrop icon
  mystic: "mystic.png", // Mystic crit flash's own backdrop icon
  keynote: "keynote.png", // Keynote crit flash's own backdrop icon
  pair: "pair.png", // Pair crit flash's own backdrop icon
  threeOfAKind: "threeOfAKind.png", // Three of a Kind crit flash's own backdrop icon
  fourOfAKind: "fourOfAKind.png", // Four of a Kind crit flash's own backdrop icon
  fullHouse: "fullHouse.png", // Full House crit flash's own backdrop icon
  royalFlush: "royalFlush.png", // Royal Flush crit flash's own backdrop icon
  winter: "christmasTree.png", // Winter Sale crit flash's own backdrop icon
  spring: "spring.png", // Spring Sale crit flash's own backdrop icon
  summer: "summer.png", // Summer Sale crit flash's own backdrop icon
  autumn: "fall.png", // Autumn Sale crit flash's own backdrop icon
  halloween: "halloween.png", // Halloween Sale crit flash's own backdrop icon
  sunny: "sunny.png", // Sunshine crit flash's own backdrop icon
  snowman: "snowman.png", // Snowday crit flash's own backdrop icon
  fastforward: "fastforward.png", // Fast Forward crit flash's own backdrop icon
  icecube: "icecube.png", // Frozen crit flash's own backdrop icon
  spendingFreeze: "spendingFreeze.png", // Spending Freeze crit flash's own backdrop icon
  snowball: "snowball.png", // Snowball crit flash's own backdrop icon
  bull: "bull.png", // Bull Market crit flash's own backdrop icon
  payday: "payday.png", // Payday crit flash's own backdrop icon
  goldStandard: "goldStandard.png", // Gold Standard crit flash's own backdrop icon
  sleepyMoon: "sleepyMoon.png", // Night Shift crit flash's own backdrop icon
  intern: "intern.png", // Intern crit flash's own backdrop icon
  talentScout: "talentScout.png", // Talent Scout crit flash's own backdrop icon
  unionBoss: "unionBoss.png", // Union Boss crit flash's own backdrop icon
  easterBunny: "easterBunny.png", // Easter Sale crit flash's own backdrop icon
  sportscar: "sportscar.png", // Rush Hour crit flash's own backdrop icon
  rateLock: "rateLock.png", // Rate Lock crit flash's own backdrop icon
  goldenTicket: "goldenTicket.png", // Golden Ticket crit flash's own backdrop icon
  silverTicket: "silverTicket.png", // Silver Ticket crit flash's own backdrop icon
  goldenParachute: "goldenParachute.png", // Golden Parachute crit flash's own backdrop icon
  rainCheck: "rainCheck.png", // Rain Check crit flash's own backdrop icon
  payout: "payout.png", // Payout crit flash's own backdrop icon
  grandOpening: "grandOpening.png", // Grand Opening crit flash's own backdrop icon
  fullyStaffed: "fullyStaffed.png", // Fully Staffed crit flash's own backdrop icon
  shiftChange: "shiftChange.png", // Shift Change crit flash's own backdrop icon
  espressoShot: "espressoShot.png", // Espresso Shot crit flash's own backdrop icon
  dejaVu: "dejaVu.png", // Deja Vu crit flash's own backdrop icon
  cloneArmy: "cloneArmy.png", // Reinforcements crit flash's own backdrop icon
  luckyClover: "luckyClover.png", // Lucky Clover crit flash's own backdrop icon
  secondWind: "secondWind.png", // Second Wind crit flash's own backdrop icon
  executiveOrder: "executiveOrder.png", // Executive Order crit flash's own backdrop icon
  roundUp: "roundUp.png", // Round Up crit flash's own backdrop icon
  safetyNet: "safetyNet.png", // Safety Net crit flash's own backdrop icon
  floorShare: "floorShare.png", // Floor Share crit flash's own backdrop icon
  sameBoat: "sameBoat.png", // Same Boat crit flash's own backdrop icon
  goldenHandshake: "goldenHandshake.png", // Golden Handshake crit flash's own backdrop icon
  supplyRun: "supplyRun.png", // Supply Run crit flash's own backdrop icon
  casualFriday: "casualFriday.png", // Casual Friday crit flash's own backdrop icon
  fancyFriday: "fancyFriday.png", // Fancy Friday crit flash's own backdrop icon
  fireDrill: "fireDrill.png", // Fire Drill crit flash's own backdrop icon
  bonusRound: "bonusRound.png", // Bonus Round crit flash's own backdrop icon
  overflow: "overflow.png", // Overflow crit flash's own backdrop icon
  performanceBonus: "performanceBonus.png", // Performance Bonus crit flash's own backdrop icon
  doubleDown: "doubleDown.png", // Double Down crit flash's own backdrop icon
  coffeeRun: "coffeeRun.png", // Coffee Run crit flash's own backdrop icon
  teamBuilding: "teamBuilding.png", // Team Building crit flash's own backdrop icon
  teamLunch: "teamLunch.png", // Team Lunch crit flash's own backdrop icon
  springCleaning: "springCleaning.png", // Spring Cleaning crit flash's own backdrop icon
  nightOwl: "nightOwl.png", // Night Owl crit flash's own backdrop icon
  headhunter: "headhunter.png", // Headhunter crit flash's own backdrop icon
  dressCode: "dressCode.png", // Dress Code crit flash's own backdrop icon
  teaBreak: "teaBreak.png", // Tea Break crit flash's own backdrop icon
  recruitmentDrive: "recruitmentDrive.png", // Recruitment Drive crit flash's own backdrop icon
  merger: "merger.png", // Merger crit flash's own backdrop icon
  shareholders: "sharedholders.png", // Shareholders crit flash's own backdrop icon
  luckyNumber: "luckyNumber.png", // Lucky Number crit flash's own backdrop icon
  openBook: "openBook.png", // Open Book crit flash's own backdrop icon
  ballerina: "crits/showtime/ballerina.png",
  cowboy: "crits/showtime/cowboy.png",
  dinnerTime: "crits/showtime/dinnerTime.png",
  fingerGuns: "crits/showtime/fingerGuns.png",
  flamenco: "crits/showtime/flamenco.png",
  milestone: "crits/showtime/milestone.png",
  moonwalker: "crits/showtime/moonwalker.png",
  ninja: "crits/showtime/ninja.png",
  obelisk: "crits/showtime/obelisk.png",
  sharpShooter: "crits/showtime/sharpShooter.png",
  space: "crits/showtime/space.png",
  yesChef: "crits/showtime/yesChef.png",
  amethyst: "crits/gems/amethyst.png",
  blessed: "crits/heroes/blessed.png",
  centurion: "crits/heroes/centurion.png",
  checkUp: "crits/heroes/checkUp.png",
  diamond: "crits/gems/diamond.png",
  emerald: "crits/gems/emerald.png",
  fireman: "crits/heroes/fireman.png",
  forTheEmperor: "crits/heroes/forTheEmperor.png",
  forTheKing: "crits/heroes/forTheKing.png",
  goldNugget: "crits/gems/goldNugget.png",
  goldRush: "crits/gems/goldRush.png",
  hammerTime: "crits/heroes/hammerTime.png",
  robinHood: "crits/heroes/robinHood.png",
  roman: "crits/heroes/roman.png",
  ruby: "crits/gems/ruby.png",
  samurai: "crits/heroes/samurai.png",
  saphire: "crits/gems/saphire.png",
  silverRush: "crits/gems/silverRush.png",
  spy: "crits/heroes/spy.png",
  theLawWon: "crits/heroes/theLawWon.png",
  victorian: "crits/heroes/victorian.png",
  wizard: "crits/gameQuotes/wizard.png",
  executiveSpin: "crits/office/executiveSpin.png",
  rubberStampede: "crits/office/rubberStampede.png",
  replyAll: "crits/office/replyAll.png",
  stapleOfSuccess: "crits/office/stapleOfSuccess.png",
  faxOfFortune: "crits/office/faxOfFortune.png",
  casualMonday: "crits/office/casualMonday.png",
  deskJockey: "crits/office/deskJockey.png",
  inboxZeroGravity: "crits/office/inboxZeroGravity.png",
  beanCounter: "crits/office/beanCounter.png",
  kingOfTheWorld: "crits/office/kingOfTheWorld.png",
  officeClown: "crits/office/officeClown.png",
  fridayTieDay: "crits/office/fridayTieDay.png",
  soReady: "crits/office/soReady.png",
  doughDivision: "crits/party/doughDivision.png",
  profitPopcorn: "crits/party/profitPopcorn.png",
  donutDisturb: "crits/party/donutDisturb.png",
  cakeDay: "crits/party/cakeDay.png",
  champagneProblems: "crits/party/champagneProblems.png",
  bonusBurrito: "crits/party/bonusBurrito.png",
  sundaeBest: "crits/party/sundaeBest.png",
  popTheQuestion: "crits/party/popTheQuestion.png",
  partyCrasher: "crits/party/partyCrasher.png",
  epic: "crits/gameQuotes/epic.png",
  ready: "crits/gameQuotes/ready.png",
  workWork: "crits/gameQuotes/workWork.png",
  yesWarchief: "crits/gameQuotes/yesWarchief.png",
  youAreNotPrepared: "crits/gameQuotes/youAreNotPrepared.png",
  arcana: "crits/gameQuotes/arcana.png",
  bigDaddy: "crits/gameQuotes/bigDaddy.png",
  chonk: "crits/gameQuotes/chonk.png",
  cyberPunk: "crits/gameQuotes/cyberPunk.png",
  dodgeThis: "crits/gameQuotes/dodgeThis.png",
  whiteRabbit: "crits/gameQuotes/whiteRabbit.png",
  gladiator: "crits/gameQuotes/gladiator.png",
  iDidntAskForThis: "crits/gameQuotes/iDidntAskForThis.png",
  iHatePortals: "crits/gameQuotes/iHatePortals.png",
  littleSister: "crits/gameQuotes/littleSister.png",
  magicIsATool: "crits/gameQuotes/magicIsATool.png",
  megaChonk: "crits/gameQuotes/megaChonk.png",
  metal: "crits/gameQuotes/metal.png",
  princess: "crits/gameQuotes/princess.png",
  spaceAndTime: "crits/gameQuotes/spaceAndTime.png",
  thinkWithYourHead: "crits/gameQuotes/thinkWithYourHead.png",
  wouldYouKindly: "crits/gameQuotes/wouldYouKindly.png",
  yesYourHighness: "crits/gameQuotes/yesYourHighness.png",
  bulletDodger: "crits/gameQuotes/bulletDodger.png",
  nothingToSee: "crits/gameQuotes/nothingToSee.png",
  nowIAmSuspicious: "crits/gameQuotes/nowIAmSuspicious.png",
  redOrBlue: "crits/gameQuotes/redOrBlue.png",
  abraCashDabra: "crits/bigPersonalities/abraCashDabra.png",
  captainOfIndustry: "crits/bigPersonalities/captainOfIndustry.png",
  clowningAround: "crits/bigPersonalities/clowningAround.png",
  discoDividend: "crits/bigPersonalities/discoDividend.png",
  mimeYourBusiness: "crits/bigPersonalities/mimeYourBusiness.png",
  redCarpetTreatment: "crits/bigPersonalities/redCarpetTreatment.png",
  rockTheStock: "crits/bigPersonalities/rockTheStock.png",
  strongReturn: "crits/bigPersonalities/strongReturn.png",
  theBigCheese: "crits/bigPersonalities/theBigCheese.png",
  queenOfQueens: "crits/bigPersonalities/queenOfQueens.png",
  bubbleEconomy: "crits/goodLuck/bubbleEconomy.png",
  cloudNineToFive: "crits/goodLuck/cloudNineToFive.png",
  luckyLaundromat: "crits/goodLuck/luckyLaundromat.png",
  moneyMagnet: "crits/goodLuck/moneyMagnet.png",
  overTheRainbow: "crits/goodLuck/overTheRainbow.png",
  pocketDimension: "crits/goodLuck/pocketDimension.png",
  shootingStarEmployee: "crits/goodLuck/shootingStarEmployee.png",
  treasureMeasure: "crits/goodLuck/treasureMeasure.png",
  wishfulBanking: "crits/goodLuck/wishfulBanking.png",
  backToTheFiscal: "crits/movies/backToTheFiscal.png",
  despicableFees: "crits/movies/despicableFees.png",
  howToTrainYourManager: "crits/movies/howToTrainYourManager.png",
  jurassicPerk: "crits/movies/jurassicPerk.png",
  raidersOfTheLostReceipt: "crits/movies/raidersOfTheLostReceipt.png",
  theDevilWearsPawda: "crits/movies/theDevilWearsPawda.png",
  theExpenseMatrix: "crits/movies/theExpenseMatrix.png",
  theFastAndTheFurriest: "crits/movies/theFastAndTheFurriest.png",
  theFellowshipOfTheBling: "crits/movies/theFellowshipOfTheBling.png",
  theGreatCatsby: "crits/movies/theGreatCatsby.png",
  theLordOfTheRingBinders: "crits/movies/theLordOfTheRingBinders.png",
  breakEven: "crits/dance/breakEven.png",
  chaChaChing: "crits/dance/chaChaChing.png",
  charlestonCharge: "crits/dance/charlestonCharge.png",
  congaCompounding: "crits/dance/congaCompounding.png",
  robotResources: "crits/dance/robotResources.png",
  rumbaReturns: "crits/dance/rumbaReturns.png",
  salsaSalary: "crits/dance/salsaSalary.png",
  shuffleTheFunds: "crits/dance/shuffleTheFunds.png",
  tangoTender: "crits/dance/tangoTender.png",
  tapThatAsset: "crits/dance/tapThatAsset.png",
  waltzStreet: "crits/dance/waltzStreet.png",
  prehistoric: "crits/dance/prehistoric.png",
  breadyOrNot: "crits/comfortFood/breadyOrNot.png",
  eggcellentWork: "crits/comfortFood/eggcellentWork.png",
  holyGuacamole: "crits/comfortFood/holyGuacamole.png",
  loafActually: "crits/comfortFood/loafActually.png",
  pastaLaVista: "crits/comfortFood/pastaLaVista.png",
  souperStar: "crits/comfortFood/souperStar.png",
  tacoBoutIt: "crits/comfortFood/tacoBoutIt.png",
  theGreatPancakeStack: "crits/comfortFood/theGreatPancakeStack.png",
  wokAndRoll: "crits/comfortFood/wokAndRoll.png",
  iAmTheNight: "crits/gotham/iAmTheNight.png",
  tubs: "crits/gotham/tubs.png",
  whySoSerious: "crits/gotham/whySoSerious.png",
  avocardio: "crits/comfortFood/avocardio.png",
  butterBelieveIt: "crits/comfortFood/butterBelieveIt.png",
  cheesePullChampion: "crits/comfortFood/cheesePullChampion.png",
  grillSergeant: "crits/comfortFood/grillSergeant.png",
  noodleNap: "crits/comfortFood/noodleNap.png",
  picklePredicament: "crits/comfortFood/picklePredicament.png",
  golem: "crits/mythicCreatures/golem.png",
  hotPotato: "crits/comfortFood/hotPotato.png",
  brunchBoss: "crits/comfortFood/brunchBoss.png",
  curryFavour: "crits/comfortFood/curryFavour.png",
  dimSumDynasty: "crits/comfortFood/dimSumDynasty.png",
  soupDumplingSurgeon: "crits/comfortFood/soupDumplingSurgeon.png",
  chocolateFountainOfYouth: "crits/candy/chocolateFountainOfYouth.png",
  gummyBearMarket: "crits/candy/gummyBearMarket.png",
  jawbreaker: "crits/candy/jawbreaker.png",
  licoriceLaces: "crits/candy/licoriceLaces.png",
  lollipopGuild: "crits/candy/lollipopGuild.png",
  marshmallowMountain: "crits/candy/marshmallowMountain.png",
  sugarHigh: "crits/candy/sugarHigh.png",
  bubblegumBalloon: "crits/candy/bubblegumBalloon.png",
  candyCaneClimber: "crits/candy/candyCaneClimber.png",
  sherbetSherpa: "crits/candy/sherbetSherpa.png",
  toffeeTrap: "crits/candy/toffeeTrap.png",
  cottonCandyCloud: "crits/candy/cottonCandyCloud.png",
  fudgeIt: "crits/candy/fudgeIt.png",
  gobstopperGetaway: "crits/candy/gobstopperGetaway.png",
  jellyBeanJamboree: "crits/candy/jellyBeanJamboree.png",
  rockCandyQuarry: "crits/candy/rockCandyQuarry.png",
  sprinkleStorm: "crits/candy/sprinkleStorm.png",
  dungeonAccountant: "crits/gamerLife/dungeonAccountant.png",
  lootGoblin: "crits/gamerLife/lootGoblin.png",
  inventoryFull: "crits/gamerLife/inventoryFull.png",
  sideQuestSalary: "crits/gamerLife/sideQuestSalary.png",
  minMaxManager: "crits/gamerLife/minMaxManager.png",
  criticalKnit: "crits/gamerLife/criticalKnit.png",
  savePointSavings: "crits/gamerLife/savePointSavings.png",
  achievementUnlocked: "crits/gamerLife/achievementUnlocked.png",
  newGamePlus: "crits/gamerLife/newGamePlus.png",
  speedrunPayroll: "crits/gamerLife/speedrunPayroll.png",
  lagCompensation: "crits/gamerLife/lagCompensation.png",
  patchNotesPayday: "crits/gamerLife/patchNotesPayday.png",
  biggerOnTheInside: "crits/gamerLife/biggerOnTheInside.png",
  cacheMeOutside: "crits/gamerLife/cacheMeOutside.png",
  itCompiles: "crits/gamerLife/itCompiles.png",
  magicalPayrollGirl: "crits/gamerLife/magicalPayrollGirl.png",
  mechaMiddleManagement: "crits/gamerLife/mechaMiddleManagement.png",
  mergeConflict: "crits/gamerLife/mergeConflict.png",
  mintCondition: "crits/gamerLife/mintCondition.png",
  stackOverflowing: "crits/gamerLife/stackOverflowing.png",
  oneMoreRound: "crits/gamerLife/oneMoreRound.png",
  couchCoOpCapital: "crits/gamerLife/couchCoOpCapital.png",
  hardCarry: "crits/gamerLife/hardCarry.png",
  readyCheck: "crits/gamerLife/readyCheck.png",
  queueRoyalty: "crits/gamerLife/queueRoyalty.png",
  rankedAndBanked: "crits/gamerLife/rankedAndBanked.png",
  victoryPose: "crits/gamerLife/victoryPose.png",
  emoteEconomy: "crits/gamerLife/emoteEconomy.png",
  checkpointChampion: "crits/gamerLife/checkpointChampion.png",
  fishingForFunds: "crits/gamerLife/fishingForFunds.png",
  purrfectOrigin: "crits/superheroes/purrfectOrigin.png",
  capeEscape: "crits/superheroes/capeEscape.png",
  thunderPaws: "crits/superheroes/thunderPaws.png",
  clawAndOrder: "crits/superheroes/clawAndOrder.png",
  felineFury: "crits/superheroes/felineFury.png",
  sidekickShuffle: "crits/superheroes/sidekickShuffle.png",
  cosmicCatapult: "crits/superheroes/cosmicCatapult.png",
  theMoonstoneKey: "crits/treasures/theMoonstoneKey.png",
  spellbookSupreme: "crits/treasures/spellbookSupreme.png",
  prismPotion: "crits/treasures/prismPotion.png",
  galaxyGumball: "crits/treasures/galaxyGumball.png",
  treasureTruffle: "crits/treasures/treasureTruffle.png",
  wizardsWaffle: "crits/treasures/wizardsWaffle.png",
  goldenFortuneCookie: "crits/treasures/goldenFortuneCookie.png",
  crystalDragonEgg: "crits/treasures/crystalDragonEgg.png",
  diamondCompass: "crits/treasures/diamondCompass.png",
  emeraldCrown: "crits/treasures/emeraldCrown.png",
  goldenFleece: "crits/treasures/goldenFleece.png",
  imperialScepter: "crits/treasures/imperialScepter.png",
  rubyHeartRelic: "crits/treasures/rubyHeartRelic.png",
  sapphireHourglass: "crits/treasures/sapphireHourglass.png",
  vaultOfJewels: "crits/treasures/vaultOfJewels.png",
  goldenIdol: "crits/treasures/goldenIdol.png",
  emberwingDragon: "crits/mythicCreatures/emberwingDragon.png",
  moonlitKirin: "crits/mythicCreatures/moonlitKirin.png",
  pocketPhoenix: "crits/mythicCreatures/pocketPhoenix.png",
  crystalGriffin: "crits/mythicCreatures/crystalGriffin.png",
  velvetManticore: "crits/mythicCreatures/velvetManticore.png",
  frostfangYeti: "crits/mythicCreatures/frostfangYeti.png",
  lanternKitsune: "crits/mythicCreatures/lanternKitsune.png",
  coralSeaSerpent: "crits/mythicCreatures/coralSeaSerpent.png",
  clockworkMinotaur: "crits/mythicCreatures/clockworkMinotaur.png",
  starryCerberus: "crits/mythicCreatures/starryCerberus.png",
  goldenSphinx: "crits/mythicCreatures/goldenSphinx.png",
  mossbackTreant: "crits/mythicCreatures/mossbackTreant.png",
  rainbowAlicorn: "crits/mythicCreatures/rainbowAlicorn.png",
  bogWitchFamiliar: "crits/mythicCreatures/bogWitchFamiliar.png",
  pearlHippocampus: "crits/mythicCreatures/pearlHippocampus.png",
  thunderbirdChick: "crits/mythicCreatures/thunderbirdChick.png",
  obsidianBasilisk: "crits/mythicCreatures/obsidianBasilisk.png",
  cloudNymph: "crits/mythicCreatures/cloudNymph.png",
  alchemyAtDusk: "crits/adventurers/alchemyAtDusk.png",
  astropathAlleycat: "crits/adventurers/astropathAlleycat.png",
  bardOfTheBrokenLyre: "crits/adventurers/bardOfTheBrokenLyre.png",
  battleStandardBobcat: "crits/adventurers/battleStandardBobcat.png",
  cathedralStarship: "crits/adventurers/cathedralStarship.png",
  cursedCrownHunt: "crits/adventurers/cursedCrownHunt.png",
  dreadnoughtWhisker: "crits/adventurers/dreadnoughtWhisker.png",
  elixirUnderMoonlight: "crits/adventurers/elixirUnderMoonlight.png",
  frostbiteTracker: "crits/adventurers/frostbiteTracker.png",
  ironpawVanguard: "crits/adventurers/ironpawVanguard.png",
  lastStandLionheart: "crits/adventurers/lastStandLionheart.png",
  meowchineBerserker: "crits/adventurers/meowchineBerserker.png",
  meowtallicanGunner: "crits/adventurers/meowtallicanGunner.png",
  midnightMonsterContract: "crits/adventurers/midnightMonsterContract.png",
  moonlitWyvernHunt: "crits/adventurers/moonlitWyvernHunt.png",
  orbitalPounce: "crits/adventurers/orbitalPounce.png",
  plasmaPurrgeon: "crits/adventurers/plasmaPurrgeon.png",
  relicbladeRonin: "crits/adventurers/relicbladeRonin.png",
  seaMonsterSlayer: "crits/adventurers/seaMonsterSlayer.png",
  silverclawSentinel: "crits/adventurers/silverclawSentinel.png",
  starBastionCaptain: "crits/adventurers/starBastionCaptain.png",
  tavernTactician: "crits/adventurers/tavernTactician.png",
  theAntlerwoodStalker: "crits/adventurers/theAntlerwoodStalker.png",
  theCataclysmicChaplain: "crits/adventurers/theCataclysmicChaplain.png",
  theGriffinContract: "crits/adventurers/theGriffinContract.png",
  theSiegeScratcher: "crits/adventurers/theSiegeScratcher.png",
  theWarpwayWatcher: "crits/adventurers/theWarpwayWatcher.png",
  theWhiteWhisker: "crits/adventurers/theWhiteWhisker.png",
  toxinclawInfiltrator: "crits/adventurers/toxinclawInfiltrator.png",
  voidclawVeteran: "crits/adventurers/voidclawVeteran.png",
  voidshieldTemplar: "crits/adventurers/voidshieldTemplar.png",
  wolfmarkWanderer: "crits/adventurers/wolfmarkWanderer.png",
  wolfpackFarewell: "crits/adventurers/wolfpackFarewell.png",
  bloodlineOmen: "crits/adventurers/bloodlineOmen.png",
  candleclawCatacomb: "crits/adventurers/candleclawCatacomb.png",
  emberPawPatrol: "crits/adventurers/emberPawPatrol.png",
  whiskerCoastSurvivor: "crits/adventurers/whiskerCoastSurvivor.png",
  astapurrion: "crits/baldursGate/astapurrion.png",
  astralclawSkyblade: "crits/baldursGate/astralclawSkyblade.png",
  drizztDoPurrden: "crits/baldursGate/drizztDoPurrden.png",
  elmiaowster: "crits/baldursGate/elmiaowster.png",
  elvenSongblade: "crits/baldursGate/elvenSongblade.png",
  galepaw: "crits/baldursGate/galepaw.png",
  halsinpaw: "crits/baldursGate/halsinpaw.png",
  hearthpawShadowagent: "crits/baldursGate/hearthpawShadowagent.png",
  imeown: "crits/baldursGate/imeown.png",
  jaheirball: "crits/baldursGate/jaheirball.png",
  karlachonk: "crits/baldursGate/karlachonk.png",
  laezclaw: "crits/baldursGate/laezclaw.png",
  minscAndMeow: "crits/baldursGate/minscAndMeow.png",
  sarevmeowk: "crits/baldursGate/sarevmeowk.png",
  shadowpurr: "crits/baldursGate/shadowpurr.png",
  theEmpurror: "crits/baldursGate/theEmpurror.png",
  thisIsTheEnd: "crits/baldursGate/thisIsTheEnd.png",
  whiskerWyll: "crits/baldursGate/whiskerWyll.png",
  winkWink: "crits/baldursGate/winkWink.png",
  adamWhiskersen: "crits/riches/adamWhiskersen.png",
  bankroll: "crits/riches/bankroll.png",
  billBlizzard: "crits/riches/billBlizzard.png",
  bobPawge: "crits/riches/bobPawge.png",
  bullionStack: "crits/riches/bullionStack.png",
  cashCannon: "crits/riches/cashCannon.png",
  fairExchange: "crits/riches/fairExchange.png",
  gemMine: "crits/riches/gemMine.png",
  goldMine: "crits/riches/goldMine.png",
  goldenChalice: "crits/riches/goldenChalice.png",
  goldenGoose: "crits/riches/goldenGoose.png",
  goldenStag: "crits/riches/goldenStag.png",
  handsomeJake: "crits/riches/handsomeJake.png",
  jcDentclaw: "crits/riches/jcDentclaw.png",
  liquidAssets: "crits/riches/liquidAssets.png",
  midasTouch: "crits/riches/midasTouch.png",
  moneyPrinter: "crits/riches/moneyPrinter.png",
  moneyTree: "crits/riches/moneyTree.png",
  nuggetAvalanche: "crits/riches/nuggetAvalanche.png",
  pennyJar: "crits/riches/pennyJar.png",
  purrDenton: "crits/riches/purrDenton.png",
  strikeItRich: "crits/riches/strikeItRich.png",
  vaultDoor: "crits/riches/vaultDoor.png",
  wishingWell: "crits/riches/wishingWell.png",
  youKnowWhatStallion: "crits/riches/youKnowWhatStallion.png",
  annaNyavarre: "crits/gear/annaNyavarre.png",
  batteryCell: "crits/gear/batteryCell.png",
  blackBlade: "crits/gear/blackBlade.png",
  boneFlute: "crits/gear/boneFlute.png",
  coldSteel: "crits/gear/coldSteel.png",
  commando: "crits/gear/commando.png",
  corvidCrown: "crits/gear/corvidCrown.png",
  daedalynx: "crits/gear/daedalynx.png",
  dataCube: "crits/gear/dataCube.png",
  dropTuned: "crits/gear/dropTuned.png",
  eternalFlame: "crits/gear/eternalFlame.png",
  forgeAhead: "crits/gear/forgeAhead.png",
  guntherHairman: "crits/gear/guntherHairman.png",
  heliopaws: "crits/gear/heliopaws.png",
  hornsUp: "crits/gear/hornsUp.png",
  ironKey: "crits/gear/ironKey.png",
  lastCall: "crits/gear/lastCall.png",
  nanoBlade: "crits/gear/nanoBlade.png",
  peltCloak: "crits/gear/peltCloak.png",
  pigIron: "crits/gear/pigIron.png",
  praxisKit: "crits/gear/praxisKit.png",
  quickSilver: "crits/gear/quickSilver.png",
  runicAmulet: "crits/gear/runicAmulet.png",
  scaledGrip: "crits/gear/scaledGrip.png",
  securityTurret: "crits/gear/securityTurret.png",
  shoulderSpikes: "crits/gear/shoulderSpikes.png",
  shredMetal: "crits/gear/shredMetal.png",
  signetOfSkulls: "crits/gear/signetOfSkulls.png",
  stormFork: "crits/gear/stormFork.png",
  studdedBelt: "crits/gear/studdedBelt.png",
  swashbuckler: "crits/gear/swashbuckler.png",
  tempered: "crits/gear/tempered.png",
  theCure: "crits/gear/theCure.png",
  titaniumGrip: "crits/gear/titaniumGrip.png",
  wardingSigil: "crits/gear/wardingSigil.png",
  blackHole: "crits/cosmos/blackHole.png",
  bottledNebula: "crits/cosmos/bottledNebula.png",
  eclipse: "crits/cosmos/eclipse.png",
  treasureMap: "crits/ocean/treasureMap.png",
  captainLeFluff: "crits/ocean/captainLeFluff.png",
  divingBell: "crits/ocean/divingBell.png",
  flooringInspector: "crits/ocean/flooringInspector.png",
  kraken: "crits/ocean/kraken.png",
  messageInABottle: "crits/ocean/messageInABottle.png",
  bullseye: "crits/gamesOfChance/bullseye.png",
  chainReaction: "crits/gamesOfChance/chainReaction.png",
  doubleHelix: "crits/gamesOfChance/doubleHelix.png",
  eureka: "crits/gamesOfChance/eureka.png",
  goldMedal: "crits/gamesOfChance/goldMedal.png",
  halfLife: "crits/gamesOfChance/halfLife.png",
  highRoller: "crits/gamesOfChance/highRoller.png",
  jackpot: "crits/gamesOfChance/jackpot.png",
  knockout: "crits/gamesOfChance/knockout.png",
  pearlDiver: "crits/gamesOfChance/pearlDiver.png",
  roundAndRound: "crits/gamesOfChance/roundAndRound.png",
  scratchCard: "crits/gamesOfChance/scratchCard.png",
  silverware: "crits/gamesOfChance/silverware.png",
  snakeEyes: "crits/gamesOfChance/snakeEyes.png",
  twentyOne: "crits/gamesOfChance/twentyOne.png",
  wheelOfFortune: "crits/gamesOfChance/wheelOfFortune.png",
  aetherLantern: "crits/steampunk/aetherLantern.png",
  boilerRoom: "crits/steampunk/boilerRoom.png",
  brassDiver: "crits/steampunk/brassDiver.png",
  clockworkHand: "crits/steampunk/clockworkHand.png",
  cogwork: "crits/steampunk/cogwork.png",
  fullSteam: "crits/steampunk/fullSteam.png",
  pocketWatch: "crits/steampunk/pocketWatch.png",
  tubeDelivery: "crits/steampunk/tubeDelivery.png",
  windUp: "crits/steampunk/windUp.png",
  ancientRelic: "crits/relics/ancientRelic.png",
  geometricRelic: "crits/relics/geometricRelic.png",
  berryParfait: "crits/desserts/berryParfait.png",
  berrySmoothie: "crits/drinks/berrySmoothie.png",
  butterCroissant: "crits/bakery/butterCroissant.png",
  cheeseWheel: "crits/comfortFood/cheeseWheel.png",
  chromeArm: "crits/cyberpunk/chromeArm.png",
  circuitBreaker: "crits/cyberpunk/circuitBreaker.png",
  glassWyvern: "crits/mythicCreatures/glassWyvern.png",
  goldBar: "crits/riches/goldBar.png",
  honeyToast: "crits/comfortFood/honeyToast.png",
  potionCommotion: "crits/gear/potionCommotion.png",
  lemonTart: "crits/desserts/lemonTart.png",
  lifelineLoot: "crits/gear/lifelineLoot.png",
  moonCloak: "crits/gear/moonCloak.png",
  mossbackManticore: "crits/mythicCreatures/mossbackManticore.png",
  platinumRing: "crits/gear/platinumRing.png",
  sapphireOrbit: "crits/gear/sapphireOrbit.png",
  roboticGripper: "crits/cyberpunk/roboticGripper.png",
  silverCoin: "crits/riches/silverCoin.png",
  spicedChai: "crits/drinks/spicedChai.png",
  stormBoots: "crits/gear/stormBoots.png",
  sushiPlatter: "crits/comfortFood/sushiPlatter.png",
  thornmailGlove: "crits/gear/thornmailGlove.png",
  gildedCache: "crits/riches/gildedCache.png",
  berryShortcake: "crits/desserts/berryShortcake.png",
  brassBanker: "crits/riches/brassBanker.png",
  candyCastle: "crits/candy/candyCastle.png",
  caramelApple: "crits/candy/caramelApple.png",
  catnipSatchel: "crits/gear/catnipSatchel.png",
  cinnamonSwirl: "crits/desserts/cinnamonSwirl.png",
  citrusCoin: "crits/riches/citrusCoin.png",
  clockworkSatellite: "crits/steampunk/clockworkSatellite.png",
  coinCascade: "crits/riches/coinCascade.png",
  comfortFood: "crits/comfortFood/comfortFood.png",
  crownHedgehog: "crits/critters/crownHedgehog.png",
  emberKey: "crits/relics/emberKey.png",
  emberwingDragon2: "crits/mythicCreatures/emberwingDragon2.png",
  emperorsFinest: "crits/warhammer/emperorsFinest.png",
  eternalDuty: "crits/warhammer/eternalDuty.png",
  faithIsOurShield: "crits/warhammer/faithIsOurShield.png",
  fearNotThePsyker: "crits/warhammer/fearNotThePsyker.png",
  frostRune: "crits/relics/frostRune.png",
  lanternFox: "crits/critters/lanternFox.png",
  lanternLynx: "crits/critters/lanternLynx.png",
  memoryCrystal: "crits/relics/memoryCrystal.png",
  mochaFroth: "crits/drinks/mochaFroth.png",
  coinrootGrove: "crits/riches/coinrootGrove.png",
  neonBeaker: "crits/relics/neonBeaker.png",
  neverSurrender: "crits/warhammer/neverSurrender.png",
  pearlOtter: "crits/critters/pearlOtter.png",
  pickleParade: "crits/comfortFood/pickleParade.png",
  profitPigeon: "crits/critters/profitPigeon.png",
  purge: "crits/warhammer/purge.png",
  rainbowRelic: "crits/relics/rainbowRelic.png",
  ramenCrown: "crits/comfortFood/ramenCrown.png",
  redPanda: "crits/critters/redPanda.png",
  silverLaurel: "crits/gear/silverLaurel.png",
  thunderNachos: "crits/comfortFood/thunderNachos.png",
  toTheSkies: "crits/warhammer/toTheSkies.png",
  treasureTeapot: "crits/drinks/treasureTeapot.png",
  whatAreYourOrders: "crits/warhammer/whatAreYourOrders.png",
  whisperingOrb: "crits/relics/whisperingOrb.png",
  clockworkOwl: "crits/steampunk/clockworkOwl.png",
  goldenGardenGolem: "crits/critters/goldenGardenGolem.png",
  moonlitMint: "crits/candy/moonlitMint.png",
  vaultBeetle: "crits/critters/vaultBeetle.png",
  lionKey: "crits/relics/lionKey.png",
  restorationProject: "crits/relics/restorationProject.png",
  arfthas: "crits/warcraft/arfthas.png",
  guldanMeow: "crits/warcraft/guldanMeow.png",
  sargerasPurrgeras: "crits/warcraft/sargerasPurrgeras.png",
  sylvanwhisker: "crits/warcraft/sylvanwhisker.png",
  sylvanasWhiskerunner: "crits/warcraft/sylvanasWhiskerunner.png",
  jainaPurrmoore: "crits/warcraft/jainaPurrmoore.png",
  thrallpaw: "crits/warcraft/thrallpaw.png",
  varianWrynnkles: "crits/warcraft/varianWrynnkles.png",
  anduinWrynncat: "crits/warcraft/anduinWrynncat.png",
  illidandelight: "crits/warcraft/illidandelight.png",
  malfurionStormpaw: "crits/warcraft/malfurionStormpaw.png",
  voljinWhisker: "crits/warcraft/voljinWhisker.png",
  lorthemewPurron: "crits/warcraft/lorthemewPurron.png",
  khadgarPurr: "crits/warcraft/khadgarPurr.png",
  garroshHellscreamPurr: "crits/warcraft/garroshHellscreamPurr.png",
  grommewHellscream: "crits/warcraft/grommewHellscream.png",
  deathwingTheDestroycat: "crits/warcraft/deathwingTheDestroycat.png",
  deathwingAshwing: "crits/warcraft/deathwingAshwing.png",
  deathwingDestroypurr: "crits/warcraft/deathwingDestroypurr.png",
  ragnapurrs: "crits/warcraft/ragnapurrs.png",
  medivhMewage: "crits/warcraft/medivhMewage.png",
  tyrandeWhiskerwind: "crits/warcraft/tyrandeWhiskerwind.png",
  tyrandeMoonwhisker: "crits/warcraft/tyrandeMoonwhisker.png",
  tyrandeWhisperpaws: "crits/warcraft/tyrandeWhisperpaws.png",
  tyrandeStarbow: "crits/warcraft/tyrandeStarbow.png",
  chenStormstout: "crits/warcraft/chenStormstout.png",
  antleredFoxFortune: "crits/critters/antleredFoxFortune.png",
  emperorProvidesPurrfection: "crits/warhammer/emperorProvidesPurrfection.png",
  furionStormpaw: "crits/warcraft/furionStormpaw.png",
  whatIsBrewing: "crits/warcraft/whatIsBrewing.png",
  goldLion: "crits/goldenAnimals/goldLion.png",
  goldElephant: "crits/goldenAnimals/goldElephant.png",
  goldBear: "crits/goldenAnimals/goldBear.png",
  goldWolf: "crits/goldenAnimals/goldWolf.png",
  goldOwl: "crits/goldenAnimals/goldOwl.png",
  goldRam: "crits/goldenAnimals/goldRam.png",
  goldRabbit: "crits/goldenAnimals/goldRabbit.png",
  goldCat: "crits/goldenAnimals/goldCat.png",
  goldenLion: "crits/goldenAnimals/goldenLion.png",
  loadedBurger: "crits/comfortFood/loadedBurger.png",
  tacoFeast: "crits/comfortFood/tacoFeast.png",
  pizzaSupreme: "crits/comfortFood/pizzaSupreme.png",
  sushiPlatter2: "crits/comfortFood/sushiPlatter2.png",
  sushiPlatter3: "crits/comfortFood/sushiPlatter3.png",
  sushiPlatter4: "crits/comfortFood/sushiPlatter4.png",
  ramenBowl: "crits/comfortFood/ramenBowl.png",
  berrySmoothie2: "crits/drinks/berrySmoothie2.png",
  berrySmoothie3: "crits/drinks/berrySmoothie3.png",
  berrySmoothie4: "crits/drinks/berrySmoothie4.png",
  icedCoffee: "crits/drinks/icedCoffee.png",
  tropicalLemonade: "crits/drinks/tropicalLemonade.png",
  tropicalLemonade2: "crits/drinks/tropicalLemonade2.png",
  hotChocolate: "crits/drinks/hotChocolate.png",
  hotChocolate2: "crits/drinks/hotChocolate2.png",
  sunsetMargarita: "crits/drinks/sunsetMargarita.png",
  blueLagoonCocktail: "crits/drinks/blueLagoonCocktail.png",
  blueLagoonCocktail2: "crits/drinks/blueLagoonCocktail2.png",
  blueLagoonCocktail3: "crits/drinks/blueLagoonCocktail3.png",
  strawberryDaiquiri: "crits/drinks/strawberryDaiquiri.png",
  mangoMojito: "crits/drinks/mangoMojito.png",
  mangoMojito2: "crits/drinks/mangoMojito2.png",
  espressoMartini: "crits/drinks/espressoMartini.png",
  chocolateCake: "crits/desserts/chocolateCake.png",
  strawberryShortcake: "crits/desserts/strawberryShortcake.png",
  rainbowDonut: "crits/desserts/rainbowDonut.png",
  iceCreamSundae: "crits/desserts/iceCreamSundae.png",
  iceCreamSundae2: "crits/desserts/iceCreamSundae2.png",
  macaronTower: "crits/desserts/macaronTower.png",
  macaronTower2: "crits/desserts/macaronTower2.png",
  batman: "crits/gotham/batman.png",
  joker: "crits/gotham/joker.png",
  harleyQuinn: "crits/gotham/harleyQuinn.png",
  killerCroc: "crits/gotham/killerCroc.png",
  mrFreeze: "crits/gotham/mrFreeze.png",
  poisonIvy: "crits/gotham/poisonIvy.png",
  scarecrow: "crits/gotham/scarecrow.png",
  thePenguin: "crits/gotham/thePenguin.png",
  theRiddler: "crits/gotham/theRiddler.png",
  bane: "crits/gotham/bane.png",
  harleyQuinn2: "crits/gotham/harleyQuinn2.png",
  killerCroc2: "crits/gotham/killerCroc2.png",
  poisonIvy2: "crits/gotham/poisonIvy2.png",
  poisonIvy3: "crits/gotham/poisonIvy3.png",
  thePenguin2: "crits/gotham/thePenguin2.png",
  bestestBoy: "crits/critters/bestestBoy.png",
  doggo: "crits/critters/doggo.png",
  otterlyAdorable: "crits/critters/otterlyAdorable.png",
  apple: "crits/desserts/apple.png",
  bulwark: "crits/steampunk/bulwark.png",
  fullPlate: "crits/steampunk/fullPlate.png",
  clockworkWizard: "crits/steampunk/clockworkWizard.png",
  clockworkWizard2: "crits/steampunk/clockworkWizard2.png",
  cupcake: "crits/desserts/cupcake.png",
  donut: "crits/desserts/donut.png",
  metalHeart: "crits/steampunk/metalHeart.png",
  metalHeart2: "crits/steampunk/metalHeart2.png",
  overlord: "crits/steampunk/overlord.png",
  potion: "crits/gear/potion.png",
  beerBelly: "crits/drinks/beerBelly.png",
  bottomsUp: "crits/drinks/bottomsUp.png",
  splitThePot: "crits/gamesOfChance/splitThePot.png",
  highRoller2: "crits/gamesOfChance/highRoller2.png",
  highRoller3: "crits/gamesOfChance/highRoller3.png",
  pokerNight: "crits/gamesOfChance/pokerNight.png",
  ponyKeg: "crits/drinks/ponyKeg.png",
  vodkaWhiskers: "crits/drinks/vodkaWhiskers.png",
  wineCountry: "crits/drinks/wineCountry.png",
  allowance: "crits/riches/allowance.png",
  allowance2: "crits/riches/allowance2.png",
  amberSpritz: "crits/drinks/amberSpritz.png",
  blackberryBramble: "crits/drinks/blackberryBramble.png",
  blackberryBramble2: "crits/drinks/blackberryBramble2.png",
  copperMugMule: "crits/drinks/copperMugMule.png",
  copperMugMule2: "crits/drinks/copperMugMule2.png",
  cosmoCashout: "crits/drinks/cosmoCashout.png",
  derbyDayJulep: "crits/drinks/derbyDayJulep.png",
  derbyDayJulep2: "crits/drinks/derbyDayJulep2.png",
  emptyGlass: "crits/drinks/emptyGlass.png",
  frenchSeventyFive: "crits/drinks/frenchSeventyFive.png",
  hurricaneHour: "crits/drinks/hurricaneHour.png",
  hurricaneHour2: "crits/drinks/hurricaneHour2.png",
  liquidAssets2: "crits/riches/liquidAssets2.png",
  longIslandLandslide: "crits/drinks/longIslandLandslide.png",
  lootBags: "crits/riches/lootBags.png",
  negroniNightfall: "crits/drinks/negroniNightfall.png",
  negroniNightfall2: "crits/drinks/negroniNightfall2.png",
  oldFashionedFortune: "crits/drinks/oldFashionedFortune.png",
  pineappleParadise: "crits/drinks/pineappleParadise.png",
  pocketMoney: "crits/riches/pocketMoney.png",
  pocketMoney2: "crits/riches/pocketMoney2.png",
  fortyKOfGold: "crits/warhammer/40kOfGold.png",
  chaoticTemptation: "crits/warhammer/chaoticTemptation.png",
  chaoticTemptation2: "crits/warhammer/chaoticTemptation2.png",
  chaoticTemptation3: "crits/warhammer/chaoticTemptation3.png",
  chaoticTemptation4: "crits/warhammer/chaoticTemptation4.png",
  emperorsDividends: "crits/warhammer/emperorsDividends.png",
  heavyHitter: "crits/warhammer/heavyHitter.png",
  iAmSpeed: "crits/warhammer/iAmSpeed.png",
  neverSurrender2: "crits/warhammer/neverSurrender2.png",
  plushieDog: "crits/plushies/plushieDog.png",
  plushieElephant: "crits/plushies/plushieElephant.png",
  plushieHamster: "crits/plushies/plushieHamster.png",
  plushieOtter: "crits/plushies/plushieOtter.png",
  plushiePand: "crits/plushies/plushiePand.png",
  plushiePenguin: "crits/plushies/plushiePenguin.png",
  plushieRabbit: "crits/plushies/plushieRabbit.png",
  plushieRacoon: "crits/plushies/plushieRacoon.png",
  plushieSeal: "crits/plushies/plushieSeal.png",
  plushieTiger: "crits/plushies/plushieTiger.png",
  powerSword: "crits/warhammer/powerSword.png",
  powerSword2: "crits/warhammer/powerSword2.png",
  sleepyFox: "crits/critters/sleepyFox.png",
  sleepyPanda: "crits/critters/sleepyPanda.png",
  alicorn: "crits/mythicCreatures/alicorn.png",
  alicorn2: "crits/mythicCreatures/alicorn2.png",
  crystallineDragon: "crits/mythicCreatures/crystallineDragon.png",
  dragonWithEgg: "crits/mythicCreatures/dragonWithEgg.png",
  griffin: "crits/mythicCreatures/griffin.png",
  hippocampus: "crits/mythicCreatures/hippocampus.png",
  hydra: "crits/mythicCreatures/hydra.png",
  kirin: "crits/mythicCreatures/kirin.png",
  kitsune: "crits/mythicCreatures/kitsune.png",
  manticore: "crits/mythicCreatures/manticore.png",
  manticore2: "crits/mythicCreatures/manticore2.png",
  manticore3: "crits/mythicCreatures/manticore3.png",
  pegasus: "crits/mythicCreatures/pegasus.png",
  phoneix: "crits/mythicCreatures/phoneix.png",
  puppyPosey: "crits/mythicCreatures/puppyPosey.png",
  salamander: "crits/mythicCreatures/salamander.png",
  salamander2: "crits/mythicCreatures/salamander2.png",
  salamander3: "crits/mythicCreatures/salamander3.png",
  seaSerpet: "crits/mythicCreatures/seaSerpet.png",
  thunderbird: "crits/mythicCreatures/thunderbird.png",
  treant: "crits/mythicCreatures/treant.png",
  unicorn: "crits/mythicCreatures/unicorn.png",
  velvetManticore2: "crits/mythicCreatures/velvetManticore2.png",
  velvetManticore3: "crits/mythicCreatures/velvetManticore3.png",
  almondEncore: "crits/bakery/almondEncore.png",
  babkaRhapsody: "crits/bakery/babkaRhapsody.png",
  bagelBoulevard: "crits/bakery/bagelBoulevard.png",
  baguetteBaton: "crits/bakery/baguetteBaton.png",
  briocheBonanza: "crits/bakery/briocheBonanza.png",
  breadWinner: "crits/bakery/breadWinner.png",
  challahCharm: "crits/bakery/challahCharm.png",
  chouxBusiness: "crits/bakery/chouxBusiness.png",
  cinnamonSpin: "crits/bakery/cinnamonSpin.png",
  icingOnTheBun: "crits/bakery/icingOnTheBun.png",
  cruffinSummit: "crits/bakery/cruffinSummit.png",
  custardCrown: "crits/bakery/custardCrown.png",
  danishDaydream: "crits/bakery/danishDaydream.png",
  eclairFlair: "crits/bakery/eclairFlair.png",
  focacciaFiesta: "crits/bakery/focacciaFiesta.png",
  jamSession: "crits/bakery/jamSession.png",
  sconeWithTheWind: "crits/bakery/sconeWithTheWind.png",
  knotYourAverage: "crits/bakery/knotYourAverage.png",
  naanStop: "crits/bakery/naanStop.png",
  palmierParade: "crits/bakery/palmierParade.png",
  pistachioPalace: "crits/bakery/pistachioPalace.png",
  pitaPocketPayday: "crits/bakery/pitaPocketPayday.png",
  ryeOnThePrize: "crits/bakery/ryeOnThePrize.png",
  shokupanCloud: "crits/bakery/shokupanCloud.png",
  sourdoughSunrise: "crits/bakery/sourdoughSunrise.png",
  strudelCuddle: "crits/bakery/strudelCuddle.png",
  appleOfMyEye: "crits/bakery/appleOfMyEye.png",
  turnoverTreasure: "crits/bakery/turnoverTreasure.png",
  cocoaClout: "crits/chocolate/cocoaClout.png",
  shadesOfCocoa: "crits/chocolate/shadesOfCocoa.png",
  bigMugEnergy: "crits/chocolate/bigMugEnergy.png",
  bonbonBigwig: "crits/chocolate/bonbonBigwig.png",
  ganacheGains: "crits/chocolate/ganacheGains.png",
  hazelnutHedgeFund: "crits/chocolate/hazelnutHedgeFund.png",
  spreadTheWealth: "crits/chocolate/spreadTheWealth.png",
  chocolateBarExam: "crits/chocolate/chocolateBarExam.png",
  darkChocolateDeal: "crits/chocolate/darkChocolateDeal.png",
  mousseMoxie: "crits/chocolate/mousseMoxie.png",
  rockyRoadRally: "crits/chocolate/rockyRoadRally.png",
  browniePoints: "crits/cakes/browniePoints.png",
  torteReform: "crits/cakes/torteReform.png",
  justDesserts: "crits/cakes/justDesserts.png",
  sweetVerdict: "crits/cakes/sweetVerdict.png",
  operaCakeOverture: "crits/cakes/operaCakeOverture.png",
  sacherStockpile: "crits/cakes/sacherStockpile.png",
  tripleLayerTreasury: "crits/cakes/tripleLayerTreasury.png",
  layeredSecurity: "crits/cakes/layeredSecurity.png",
  mississippiMudMillionaire: "crits/cakes/mississippiMudMillionaire.png",
  swissRollRollover: "crits/cakes/swissRollRollover.png",
  chocolateDripDynamo: "crits/cakes/chocolateDripDynamo.png",
  marbleCakeMargin: "crits/cakes/marbleCakeMargin.png",
  souffleSurplus: "crits/cakes/souffleSurplus.png",
  onTheRise: "crits/cakes/onTheRise.png",
  blackForestFortune: "crits/cakes/blackForestFortune.png",
  redVelvetRope: "crits/cakes/redVelvetRope.png",
  tiramisuTycoon: "crits/cakes/tiramisuTycoon.png",
  cheesecakeChairman: "crits/cakes/cheesecakeChairman.png",
  carrotCakeCapital: "crits/cakes/carrotCakeCapital.png",
  angelFoodAscension: "crits/cakes/angelFoodAscension.png",
  poundCakeProfits: "crits/cakes/poundCakeProfits.png",
  bundtFund: "crits/cakes/bundtFund.png",
  lavaCakeLiquidity: "crits/cakes/lavaCakeLiquidity.png",
  upsideDownUpswing: "crits/cakes/upsideDownUpswing.png",
  watermelonWindfall: "crits/fruits/watermelonWindfall.png",
  papayaPayroll: "crits/fruits/papayaPayroll.png",
  kiwiKickback: "crits/fruits/kiwiKickback.png",
  topBanana: "crits/fruits/topBanana.png",
  cherryOnTop: "crits/fruits/cherryOnTop.png",
  peachPerfect: "crits/fruits/peachPerfect.png",
  plumJob: "crits/fruits/plumJob.png",
  dragonfruitDynasty: "crits/fruits/dragonfruitDynasty.png",
  grapeExpectations: "crits/fruits/grapeExpectations.png",
  pomegranatePortfolio: "crits/fruits/pomegranatePortfolio.png",
  gumdropGazillionaire: "crits/candy/gumdropGazillionaire.png",
  candyCornCornucopia: "crits/candy/candyCornCornucopia.png",
  butterscotchBuyout: "crits/candy/butterscotchBuyout.png",
  sourStrawSprint: "crits/candy/sourStrawSprint.png",
  pralinePremium: "crits/candy/pralinePremium.png",
  fizzyFortune: "crits/candy/fizzyFortune.png",
  marzipanMogul: "crits/candy/marzipanMogul.png",
  gummyWormWealth: "crits/candy/gummyWormWealth.png",
  chocolateCoinCartel: "crits/candy/chocolateCoinCartel.png",
  honeycombHustle: "crits/candy/honeycombHustle.png",
  sidecarSurge: "crits/drinks/sidecarSurge.png",
  singaporeSling: "crits/drinks/singaporeSling.png",
  tikiZombie: "crits/drinks/tikiZombie.png",
  tikiZombie2: "crits/drinks/tikiZombie2.png",
} as const;
export type ImageName = keyof typeof IMAGE_FILES;

export function getBackgroundUrls(): string[] {
  return backgroundFiles.map(themeAssetUrl);
}

export function getGroundUrl(): string {
  return themeAssetUrl("street.png");
}

export function getSpriteUrl(name: SpriteName): string {
  return themeAssetUrl(SPRITE_FILES[name]);
}

export function loadBackgrounds(): Promise<HTMLImageElement[]> {
  return Promise.all(getBackgroundUrls().map(loadImage));
}

export function loadGroundImage(): Promise<HTMLImageElement> {
  return loadImage(getGroundUrl());
}

export function loadSprite(name: SpriteName): Promise<HTMLImageElement> {
  return loadImage(getSpriteUrl(name));
}

export function getImageUrl(name: ImageName): string {
  const filename = IMAGE_FILES[name];
  return sharedThemeImages.has(filename)
    ? themeAssetUrl(filename)
    : critAssetUrl(filename);
}

// the white-bordered "sticker" cut of the same artwork, generated into
// public/stickers/ by scripts/add-sticker-borders.mjs — used by the Special
// Crits dialog, while the celebration flash draws the plain cut-out
export function getStickerUrl(name: ImageName): string {
  return `${PUBLIC_ASSET_BASE}stickers/${IMAGE_FILES[name]}`;
}

// flat black cut of the same sticker, shown for a crit the player hasn't
// discovered yet — its own file so an undiscovered crit never downloads the
// artwork it's hiding
export function getSilhouetteUrl(name: ImageName): string {
  return `${PUBLIC_ASSET_BASE}silhouettes/${IMAGE_FILES[name]}`;
}

export function loadImageByName(name: ImageName): Promise<HTMLImageElement> {
  return loadImage(getImageUrl(name));
}

export function getCloudUrls(): string[] {
  return cloudFiles.map(themeAssetUrl);
}

export function loadThemeClouds(): Promise<HTMLImageElement[]> {
  return Promise.all(getCloudUrls().map(loadImage));
}
