import { loadImage } from "../utils";

const PUBLIC_ASSET_BASE = import.meta.env.BASE_URL;
const themeAssetUrl = (filename: string) => `${PUBLIC_ASSET_BASE}${filename}`;
const critAssetUrl = (filename: string) => `${PUBLIC_ASSET_BASE}${filename}`;
const sharedThemeImages = new Set([
  "city.png",
  "mapBg.png",
  "wallMaterial.png",
  "coin.png",
  "mouse.png",
  "isometricBox.png",
  "isometricYarn.png",
  "merge.png",
  "skyscraper.png",
  "cashRegister.png",
  "clock.png",
]);
const backgroundFiles = ["bg2.png", "bg4.png", "bg6.png"];
const cloudFiles = [
  "cloud0.png",
  "cloud1.png",
  "cloud2.png",
  "cloud3.png",
  "cloud4.png",
];

// Every sprite this game loads, by logical name -> its filename in public/assets/.
const SPRITE_FILES = {
  worker: "workerWalk.png",
  manager: "managerWalk.png",
  coinSpin: "coinSpin.png",
  cashBill: "cashBillFlutter.png",
} as const;
export type SpriteName = keyof typeof SPRITE_FILES;

// every flat single-file image this game loads, by logical name -> its filename
// inside dist/ root — same reasoning as SPRITE_FILES above
export const IMAGE_FILES = {
  chromeDome: "chromeDome.png",
  skullSyndicate: "skullSyndicate.png",
  circuitDuchess: "circuitDuchess.png",
  cyberCat: "cyberCat.png",
  chromeChassis: "chromeChassis.png",
  elbowRoom: "elbowRoom.png",
  heartware: "heartware.png",
  pulseDividend: "pulseDividend.png",
  neonNegotiator: "neonNegotiator.png",
  platinumRefrain: "platinumRefrain.png",
  retinaRoyale: "retinaRoyale.png",
  silverHandshake: "silverHandshake.png",
  staticEncore: "staticEncore.png",
  goldenSkull: "goldenSkull.png",
  lordOfMurder: "lordOfMurder.png",
  speedDemon: "speedDemon.png",
  bubbleButt: "bubbleButt.png",
  canNotLie: "canNotLie.png",
  badonkadonk: "badonkadonk.png",
  demoncBuns: "demoncBuns.png",
  infernalInterest: "infernalInterest.png",
  dropItLow: "dropItLow.png",
  kittyWagon: "kittyWagon.png",
  madeYouLook: "madeYouLook.png",
  wagonWarrior: "wagonWarrior.png",
  californiumCrescendo: "californiumCrescendo.png",
  einsteiniumEpiphany: "einsteiniumEpiphany.png",
  fermiumFormula: "fermiumFormula.png",
  mendeleviumMajesty: "mendeleviumMajesty.png",
  nobeliumLaureate: "nobeliumLaureate.png",
  lawrenciumLightspeed: "lawrenciumLightspeed.png",
  rutherfordiumReach: "rutherfordiumReach.png",
  seaborgiumSwell: "seaborgiumSwell.png",
  bohriumSummit: "bohriumSummit.png",
  hassiumMeteor: "hassiumMeteor.png",
  meitneriumMarvel: "meitneriumMarvel.png",
  darmstadtiumDowntown: "darmstadtiumDowntown.png",
  roentgeniumRevelation: "roentgeniumRevelation.png",
  coperniciumCarousel: "coperniciumCarousel.png",
  nihoniumDaybreak: "nihoniumDaybreak.png",
  fleroviumFortress: "fleroviumFortress.png",
  moscoviumMosaic: "moscoviumMosaic.png",
  livermoriumLightning: "livermoriumLightning.png",
  tennessineTwinkle: "tennessineTwinkle.png",
  oganessonOdyssey: "oganessonOdyssey.png",
  heavyElement: "heavyElement.png",
  osmiumRegalia: "osmiumRegalia.png",
  iridiumAegis: "iridiumAegis.png",
  mercuryFlow: "mercuryFlow.png",
  thalliumThrive: "thalliumThrive.png",
  leadLode: "leadLode.png",
  bismuthBastion: "bismuthBastion.png",
  poloniumPrism: "poloniumPrism.png",
  astatineAurora: "astatineAurora.png",
  radonRipple: "radonRipple.png",
  franciumFortune: "franciumFortune.png",
  radiumRhythm: "radiumRhythm.png",
  actiniumArc: "actiniumArc.png",
  thoriumThrone: "thoriumThrone.png",
  protactiniumOrbit: "protactiniumOrbit.png",
  neptuniumNova: "neptuniumNova.png",
  plutoniumPulse: "plutoniumPulse.png",
  americiumAlarm: "americiumAlarm.png",
  curiumCrucible: "curiumCrucible.png",
  berkeliumBreakthrough: "berkeliumBreakthrough.png",
  nucleusDividend: "nucleusDividend.png",
  hydrogenHype: "hydrogenHype.png",
  heliumHighrise: "heliumHighrise.png",
  lithiumLift: "lithiumLift.png",
  berylliumBrilliance: "berylliumBrilliance.png",
  carbonCrown: "carbonCrown.png",
  nitrogenNimbus: "nitrogenNimbus.png",
  oxygenOverdrive: "oxygenOverdrive.png",
  fluorineFlash: "fluorineFlash.png",
  sodiumSprinkle: "sodiumSprinkle.png",
  magnesiumMagnificence: "magnesiumMagnificence.png",
  aluminumAllStar: "aluminumAllStar.png",
  siliconSpark: "siliconSpark.png",
  phosphorusFlare: "phosphorusFlare.png",
  sulfurSunshine: "sulfurSunshine.png",
  chlorineConfetti: "chlorineConfetti.png",
  argonAfterglow: "argonAfterglow.png",
  potassiumPop: "potassiumPop.png",
  calciumCornerstone: "calciumCornerstone.png",
  scandiumStronghold: "scandiumStronghold.png",
  titaniumTakeoff: "titaniumTakeoff.png",
  vanadiumVoltage: "vanadiumVoltage.png",
  chromiumGleam: "chromiumGleam.png",
  manganeseMomentum: "manganeseMomentum.png",
  ironEmpire: "ironEmpire.png",
  cobaltCharge: "cobaltCharge.png",
  nickelNestEgg: "nickelNestEgg.png",
  copperCurrent: "copperCurrent.png",
  zincZing: "zincZing.png",
  galliumGlitter: "galliumGlitter.png",
  germaniumGenius: "germaniumGenius.png",
  arsenicAlchemy: "arsenicAlchemy.png",
  seleniumSunburst: "seleniumSunburst.png",
  bromineBounty: "bromineBounty.png",
  kryptonKeepsake: "kryptonKeepsake.png",
  rubidiumRadiance: "rubidiumRadiance.png",
  strontiumSpectacle: "strontiumSpectacle.png",
  yttriumYield: "yttriumYield.png",
  zirconiumZenith: "zirconiumZenith.png",
  niobiumNexus: "niobiumNexus.png",
  molybdenumMachine: "molybdenumMachine.png",
  technetiumTimebank: "technetiumTimebank.png",
  rutheniumRiches: "rutheniumRiches.png",
  rhodiumReflection: "rhodiumReflection.png",
  palladiumPilot: "palladiumPilot.png",
  silverMoonrise: "silverMoonrise.png",
  cadmiumCatalyst: "cadmiumCatalyst.png",
  indiumInsight: "indiumInsight.png",
  tinTreasure: "tinTreasure.png",
  antimonyAscension: "antimonyAscension.png",
  telluriumTreasurelight: "telluriumTreasurelight.png",
  iodineIridescence: "iodineIridescence.png",
  xenonSpotlight: "xenonSpotlight.png",
  cesiumClockwork: "cesiumClockwork.png",
  bariumBeacon: "bariumBeacon.png",
  lanthanumLuster: "lanthanumLuster.png",
  ceriumShine: "ceriumShine.png",
  praseodymiumPrism: "praseodymiumPrism.png",
  neodymiumNorthstar: "neodymiumNorthstar.png",
  promethiumPulse: "promethiumPulse.png",
  samariumSanctuary: "samariumSanctuary.png",
  europiumEncore: "europiumEncore.png",
  gadoliniumGlance: "gadoliniumGlance.png",
  terbiumTempo: "terbiumTempo.png",
  dysprosiumDirection: "dysprosiumDirection.png",
  holmiumHalo: "holmiumHalo.png",
  erbiumElegance: "erbiumElegance.png",
  thuliumThaw: "thuliumThaw.png",
  ytterbiumHourglass: "ytterbiumHourglass.png",
  lutetiumLimelight: "lutetiumLimelight.png",
  hafniumHorizon: "hafniumHorizon.png",
  tantalumTrove: "tantalumTrove.png",
  tungstenTriumph: "tungstenTriumph.png",
  rheniumRocket: "rheniumRocket.png",
  platinumPodium: "platinumPodium.png",
  goldenAtom: "goldenAtom.png",
  uraniumUplift: "uraniumUplift.png",
  city: "city.png", // distant tiled skyline behind buildings
  cityMapBackground: "mapBg.png", // city map screen's own backdrop
  cloudCatIdle: "cloudCatIdle.png", // city map corner mascot, resting pose
  cloudCatHappy: "cloudCatHappy.png", // same mascot, cheering pose
  wallMaterial: "wallMaterial.png", // exterior wall/floor-divider tile material
  coin: "coin.png", // flat coin icon (HUD/menus)
  mouse: "mouse.png", // free-boost critter
  officeChairsIcon: "isometricBox.png", // office-chairs upgrade icon
  officeSuppliesIcon: "isometricYarn.png", // office-supplies upgrade icon
  merge: "merge.png", // Merge companies' own menu icon
  skyscraper: "skyscraper.png", // Create new Company / Renovate floors icon
  cashRegister: "cashRegister.png", // Trigger sales event's own menu icon
  clock: "clock.png", // Work overtime's own menu icon
  chain: "chain.png", // Chain crit flash's own backdrop icon
  dominoEffect: "dominoEffect.png", // Domino Effect crit flash's own backdrop icon
  blueprint: "blueprint.png", // Blueprint crit flash's own backdrop icon
  executiveBonus: "executiveBonus.png", // Executive Bonus crit flash's own backdrop icon
  powerSurge: "powerSurge.png", // Power Surge crit flash's own backdrop icon
  priceMatch: "priceMatch.png", // Price Match crit flash's own backdrop icon
  firstClass: "firstClass.png", // First Class crit flash's own backdrop icon
  ball: "ball.png", // Bounce crit flash's own backdrop icon
  explosion: "explosion.png", // Explosion crit flash's own backdrop icon
  booty: "booty.png", // Booty crit flash's own backdrop icon
  cashFlow: "cashFlow.png", // Cash Flow crit flash's own backdrop icon
  upgrade: "upgrade.png", // Upgrade crit flash's own backdrop icon
  peppermint: "peppermint.png", // Peppermint crit flash's own backdrop icon
  heaven: "heaven.png", // Heavenly crit flash's own backdrop icon
  skip: "skip.png", // Skip crit flash's own backdrop icon
  mystic: "mystic.png", // Mystic crit flash's own backdrop icon
  keynote: "keynote.png", // Keynote crit flash's own backdrop icon
  pair: "pair.png", // Pair crit flash's own backdrop icon
  threeOfAKind: "threeOfAKind.png", // Three of a Kind crit flash's own backdrop icon
  fourOfAKind: "fourOfAKind.png", // Four of a Kind crit flash's own backdrop icon
  fullHouse: "fullHouse.png", // Full House crit flash's own backdrop icon
  royalFlush: "royalFlush.png", // Royal Flush crit flash's own backdrop icon
  winter: "christmasTree.png", // Winter Sale crit flash's own backdrop icon
  spring: "spring.png", // Spring Sale crit flash's own backdrop icon
  summer: "summer.png", // Summer Sale crit flash's own backdrop icon
  autumn: "fall.png", // Autumn Sale crit flash's own backdrop icon
  halloween: "halloween.png", // Halloween Sale crit flash's own backdrop icon
  sunny: "sunny.png", // Sunshine crit flash's own backdrop icon
  snowman: "snowman.png", // Snowday crit flash's own backdrop icon
  fastforward: "fastforward.png", // Fast Forward crit flash's own backdrop icon
  icecube: "icecube.png", // Frozen crit flash's own backdrop icon
  spendingFreeze: "spendingFreeze.png", // Spending Freeze crit flash's own backdrop icon
  snowball: "snowball.png", // Snowball crit flash's own backdrop icon
  bull: "bull.png", // Bull Market crit flash's own backdrop icon
  payday: "payday.png", // Payday crit flash's own backdrop icon
  goldStandard: "goldStandard.png", // Gold Standard crit flash's own backdrop icon
  sleepyMoon: "sleepyMoon.png", // Night Shift crit flash's own backdrop icon
  intern: "intern.png", // Intern crit flash's own backdrop icon
  talentScout: "talentScout.png", // Talent Scout crit flash's own backdrop icon
  unionBoss: "unionBoss.png", // Union Boss crit flash's own backdrop icon
  easterBunny: "easterBunny.png", // Easter Sale crit flash's own backdrop icon
  sportscar: "sportscar.png", // Rush Hour crit flash's own backdrop icon
  rateLock: "rateLock.png", // Rate Lock crit flash's own backdrop icon
  goldenTicket: "goldenTicket.png", // Golden Ticket crit flash's own backdrop icon
  silverTicket: "silverTicket.png", // Silver Ticket crit flash's own backdrop icon
  goldenParachute: "goldenParachute.png", // Golden Parachute crit flash's own backdrop icon
  rainCheck: "rainCheck.png", // Rain Check crit flash's own backdrop icon
  payout: "payout.png", // Payout crit flash's own backdrop icon
  grandOpening: "grandOpening.png", // Grand Opening crit flash's own backdrop icon
  fullyStaffed: "fullyStaffed.png", // Fully Staffed crit flash's own backdrop icon
  shiftChange: "shiftChange.png", // Shift Change crit flash's own backdrop icon
  espressoShot: "espressoShot.png", // Espresso Shot crit flash's own backdrop icon
  dejaVu: "dejaVu.png", // Deja Vu crit flash's own backdrop icon
  cloneArmy: "cloneArmy.png", // Reinforcements crit flash's own backdrop icon
  luckyClover: "luckyClover.png", // Lucky Clover crit flash's own backdrop icon
  secondWind: "secondWind.png", // Second Wind crit flash's own backdrop icon
  executiveOrder: "executiveOrder.png", // Executive Order crit flash's own backdrop icon
  roundUp: "roundUp.png", // Round Up crit flash's own backdrop icon
  safetyNet: "safetyNet.png", // Safety Net crit flash's own backdrop icon
  floorShare: "floorShare.png", // Floor Share crit flash's own backdrop icon
  sameBoat: "sameBoat.png", // Same Boat crit flash's own backdrop icon
  goldenHandshake: "goldenHandshake.png", // Golden Handshake crit flash's own backdrop icon
  supplyRun: "supplyRun.png", // Supply Run crit flash's own backdrop icon
  casualFriday: "casualFriday.png", // Casual Friday crit flash's own backdrop icon
  fancyFriday: "fancyFriday.png", // Fancy Friday crit flash's own backdrop icon
  fireDrill: "fireDrill.png", // Fire Drill crit flash's own backdrop icon
  bonusRound: "bonusRound.png", // Bonus Round crit flash's own backdrop icon
  overflow: "overflow.png", // Overflow crit flash's own backdrop icon
  performanceBonus: "performanceBonus.png", // Performance Bonus crit flash's own backdrop icon
  doubleDown: "doubleDown.png", // Double Down crit flash's own backdrop icon
  coffeeRun: "coffeeRun.png", // Coffee Run crit flash's own backdrop icon
  teamBuilding: "teamBuilding.png", // Team Building crit flash's own backdrop icon
  teamLunch: "teamLunch.png", // Team Lunch crit flash's own backdrop icon
  springCleaning: "springCleaning.png", // Spring Cleaning crit flash's own backdrop icon
  nightOwl: "nightOwl.png", // Night Owl crit flash's own backdrop icon
  headhunter: "headhunter.png", // Headhunter crit flash's own backdrop icon
  dressCode: "dressCode.png", // Dress Code crit flash's own backdrop icon
  teaBreak: "teaBreak.png", // Tea Break crit flash's own backdrop icon
  recruitmentDrive: "recruitmentDrive.png", // Recruitment Drive crit flash's own backdrop icon
  merger: "merger.png", // Merger crit flash's own backdrop icon
  shareholders: "sharedholders.png", // Shareholders crit flash's own backdrop icon
  luckyNumber: "luckyNumber.png", // Lucky Number crit flash's own backdrop icon
  openBook: "openBook.png", // Open Book crit flash's own backdrop icon
  ballerina: "ballerina.png",
  cowboy: "cowboy.png",
  dinnerTime: "dinnerTime.png",
  fingerGuns: "fingerGuns.png",
  flamenco: "flamenco.png",
  milestone: "milestone.png",
  moonwalker: "moonwalker.png",
  ninja: "ninja.png",
  obelisk: "obelisk.png",
  sharpShooter: "sharpShooter.png",
  space: "space.png",
  yesChef: "yesChef.png",
  amethyst: "amethyst.png",
  blessed: "blessed.png",
  centurion: "centurion.png",
  checkUp: "checkUp.png",
  diamond: "diamond.png",
  emerald: "emerald.png",
  fireman: "fireman.png",
  forTheEmperor: "forTheEmperor.png",
  forTheKing: "forTheKing.png",
  goldNugget: "goldNugget.png",
  goldRush: "goldRush.png",
  hammerTime: "hammerTime.png",
  robinHood: "robinHood.png",
  roman: "roman.png",
  ruby: "ruby.png",
  samurai: "samurai.png",
  saphire: "saphire.png",
  silverRush: "silverRush.png",
  spy: "spy.png",
  theLawWon: "theLawWon.png",
  victorian: "victorian.png",
  wizard: "wizard.png",
  executiveSpin: "executiveSpin.png",
  rubberStampede: "rubberStampede.png",
  replyAll: "replyAll.png",
  stapleOfSuccess: "stapleOfSuccess.png",
  faxOfFortune: "faxOfFortune.png",
  casualMonday: "casualMonday.png",
  deskJockey: "deskJockey.png",
  inboxZeroGravity: "inboxZeroGravity.png",
  beanCounter: "beanCounter.png",
  kingOfTheWorld: "kingOfTheWorld.png",
  officeClown: "officeClown.png",
  fridayTieDay: "fridayTieDay.png",
  soReady: "soReady.png",
  doughDivision: "doughDivision.png",
  profitPopcorn: "profitPopcorn.png",
  donutDisturb: "donutDisturb.png",
  cakeDay: "cakeDay.png",
  champagneProblems: "champagneProblems.png",
  bonusBurrito: "bonusBurrito.png",
  sundaeBest: "sundaeBest.png",
  popTheQuestion: "popTheQuestion.png",
  partyCrasher: "partyCrasher.png",
  epic: "epic.png",
  ready: "ready.png",
  workWork: "workWork.png",
  yesWarchief: "yesWarchief.png",
  youAreNotPrepared: "youAreNotPrepared.png",
  arcana: "arcana.png",
  bigDaddy: "bigDaddy.png",
  chonk: "chonk.png",
  cyberPunk: "cyberPunk.png",
  dodgeThis: "dodgeThis.png",
  whiteRabbit: "whiteRabbit.png",
  gladiator: "gladiator.png",
  iDidntAskForThis: "iDidntAskForThis.png",
  iHatePortals: "iHatePortals.png",
  littleSister: "littleSister.png",
  magicIsATool: "magicIsATool.png",
  megaChonk: "megaChonk.png",
  metal: "metal.png",
  princess: "princess.png",
  spaceAndTime: "spaceAndTime.png",
  thinkWithYourHead: "thinkWithYourHead.png",
  wouldYouKindly: "wouldYouKindly.png",
  yesYourHighness: "yesYourHighness.png",
  bulletDodger: "bulletDodger.png",
  nothingToSee: "nothingToSee.png",
  nowIAmSuspicious: "nowIAmSuspicious.png",
  redOrBlue: "redOrBlue.png",
  abraCashDabra: "abraCashDabra.png",
  captainOfIndustry: "captainOfIndustry.png",
  clowningAround: "clowningAround.png",
  discoDividend: "discoDividend.png",
  mimeYourBusiness: "mimeYourBusiness.png",
  redCarpetTreatment: "redCarpetTreatment.png",
  rockTheStock: "rockTheStock.png",
  strongReturn: "strongReturn.png",
  theBigCheese: "theBigCheese.png",
  queenOfQueens: "queenOfQueens.png",
  bubbleEconomy: "bubbleEconomy.png",
  cloudNineToFive: "cloudNineToFive.png",
  luckyLaundromat: "luckyLaundromat.png",
  moneyMagnet: "moneyMagnet.png",
  overTheRainbow: "overTheRainbow.png",
  pocketDimension: "pocketDimension.png",
  shootingStarEmployee: "shootingStarEmployee.png",
  treasureMeasure: "treasureMeasure.png",
  wishfulBanking: "wishfulBanking.png",
  backToTheFiscal: "backToTheFiscal.png",
  despicableFees: "despicableFees.png",
  howToTrainYourManager: "howToTrainYourManager.png",
  jurassicPerk: "jurassicPerk.png",
  raidersOfTheLostReceipt: "raidersOfTheLostReceipt.png",
  theDevilWearsPawda: "theDevilWearsPawda.png",
  theExpenseMatrix: "theExpenseMatrix.png",
  theFastAndTheFurriest: "theFastAndTheFurriest.png",
  theFellowshipOfTheBling: "theFellowshipOfTheBling.png",
  theGreatCatsby: "theGreatCatsby.png",
  theLordOfTheRingBinders: "theLordOfTheRingBinders.png",
  breakEven: "breakEven.png",
  chaChaChing: "chaChaChing.png",
  charlestonCharge: "charlestonCharge.png",
  congaCompounding: "congaCompounding.png",
  robotResources: "robotResources.png",
  rumbaReturns: "rumbaReturns.png",
  salsaSalary: "salsaSalary.png",
  shuffleTheFunds: "shuffleTheFunds.png",
  tangoTender: "tangoTender.png",
  tapThatAsset: "tapThatAsset.png",
  waltzStreet: "waltzStreet.png",
  prehistoric: "prehistoric.png",
  breadyOrNot: "breadyOrNot.png",
  eggcellentWork: "eggcellentWork.png",
  holyGuacamole: "holyGuacamole.png",
  loafActually: "loafActually.png",
  pastaLaVista: "pastaLaVista.png",
  souperStar: "souperStar.png",
  tacoBoutIt: "tacoBoutIt.png",
  theGreatPancakeStack: "theGreatPancakeStack.png",
  wokAndRoll: "wokAndRoll.png",
  iAmTheNight: "iAmTheNight.png",
  tubs: "tubs.png",
  whySoSerious: "whySoSerious.png",
  avocardio: "avocardio.png",
  butterBelieveIt: "butterBelieveIt.png",
  cheesePullChampion: "cheesePullChampion.png",
  grillSergeant: "grillSergeant.png",
  noodleNap: "noodleNap.png",
  picklePredicament: "picklePredicament.png",
  golem: "golem.png",
  hotPotato: "hotPotato.png",
  brunchBoss: "brunchBoss.png",
  curryFavour: "curryFavour.png",
  dimSumDynasty: "dimSumDynasty.png",
  soupDumplingSurgeon: "soupDumplingSurgeon.png",
  chocolateFountainOfYouth: "chocolateFountainOfYouth.png",
  gummyBearMarket: "gummyBearMarket.png",
  jawbreaker: "jawbreaker.png",
  licoriceLaces: "licoriceLaces.png",
  lollipopGuild: "lollipopGuild.png",
  marshmallowMountain: "marshmallowMountain.png",
  sugarHigh: "sugarHigh.png",
  bubblegumBalloon: "bubblegumBalloon.png",
  candyCaneClimber: "candyCaneClimber.png",
  sherbetSherpa: "sherbetSherpa.png",
  toffeeTrap: "toffeeTrap.png",
  cottonCandyCloud: "cottonCandyCloud.png",
  fudgeIt: "fudgeIt.png",
  gobstopperGetaway: "gobstopperGetaway.png",
  jellyBeanJamboree: "jellyBeanJamboree.png",
  rockCandyQuarry: "rockCandyQuarry.png",
  sprinkleStorm: "sprinkleStorm.png",
  dungeonAccountant: "dungeonAccountant.png",
  lootGoblin: "lootGoblin.png",
  inventoryFull: "inventoryFull.png",
  sideQuestSalary: "sideQuestSalary.png",
  minMaxManager: "minMaxManager.png",
  criticalKnit: "criticalKnit.png",
  savePointSavings: "savePointSavings.png",
  achievementUnlocked: "achievementUnlocked.png",
  newGamePlus: "newGamePlus.png",
  speedrunPayroll: "speedrunPayroll.png",
  lagCompensation: "lagCompensation.png",
  patchNotesPayday: "patchNotesPayday.png",
  biggerOnTheInside: "biggerOnTheInside.png",
  cacheMeOutside: "cacheMeOutside.png",
  itCompiles: "itCompiles.png",
  magicalPayrollGirl: "magicalPayrollGirl.png",
  mechaMiddleManagement: "mechaMiddleManagement.png",
  mergeConflict: "mergeConflict.png",
  mintCondition: "mintCondition.png",
  stackOverflowing: "stackOverflowing.png",
  oneMoreRound: "oneMoreRound.png",
  couchCoOpCapital: "couchCoOpCapital.png",
  hardCarry: "hardCarry.png",
  readyCheck: "readyCheck.png",
  queueRoyalty: "queueRoyalty.png",
  rankedAndBanked: "rankedAndBanked.png",
  victoryPose: "victoryPose.png",
  emoteEconomy: "emoteEconomy.png",
  checkpointChampion: "checkpointChampion.png",
  fishingForFunds: "fishingForFunds.png",
  purrfectOrigin: "purrfectOrigin.png",
  capeEscape: "capeEscape.png",
  thunderPaws: "thunderPaws.png",
  clawAndOrder: "clawAndOrder.png",
  felineFury: "felineFury.png",
  sidekickShuffle: "sidekickShuffle.png",
  cosmicCatapult: "cosmicCatapult.png",
  theMoonstoneKey: "theMoonstoneKey.png",
  spellbookSupreme: "spellbookSupreme.png",
  prismPotion: "prismPotion.png",
  galaxyGumball: "galaxyGumball.png",
  treasureTruffle: "treasureTruffle.png",
  wizardsWaffle: "wizardsWaffle.png",
  goldenFortuneCookie: "goldenFortuneCookie.png",
  crystalDragonEgg: "crystalDragonEgg.png",
  diamondCompass: "diamondCompass.png",
  emeraldCrown: "emeraldCrown.png",
  goldenFleece: "goldenFleece.png",
  imperialScepter: "imperialScepter.png",
  rubyHeartRelic: "rubyHeartRelic.png",
  sapphireHourglass: "sapphireHourglass.png",
  vaultOfJewels: "vaultOfJewels.png",
  goldenIdol: "goldenIdol.png",
  emberwingDragon: "emberwingDragon.png",
  moonlitKirin: "moonlitKirin.png",
  pocketPhoenix: "pocketPhoenix.png",
  crystalGriffin: "crystalGriffin.png",
  velvetManticore: "velvetManticore.png",
  frostfangYeti: "frostfangYeti.png",
  lanternKitsune: "lanternKitsune.png",
  coralSeaSerpent: "coralSeaSerpent.png",
  clockworkMinotaur: "clockworkMinotaur.png",
  starryCerberus: "starryCerberus.png",
  goldenSphinx: "goldenSphinx.png",
  mossbackTreant: "mossbackTreant.png",
  rainbowAlicorn: "rainbowAlicorn.png",
  bogWitchFamiliar: "bogWitchFamiliar.png",
  pearlHippocampus: "pearlHippocampus.png",
  thunderbirdChick: "thunderbirdChick.png",
  obsidianBasilisk: "obsidianBasilisk.png",
  cloudNymph: "cloudNymph.png",
  alchemyAtDusk: "alchemyAtDusk.png",
  astropathAlleycat: "astropathAlleycat.png",
  bardOfTheBrokenLyre: "bardOfTheBrokenLyre.png",
  battleStandardBobcat: "battleStandardBobcat.png",
  cathedralStarship: "cathedralStarship.png",
  cursedCrownHunt: "cursedCrownHunt.png",
  dreadnoughtWhisker: "dreadnoughtWhisker.png",
  elixirUnderMoonlight: "elixirUnderMoonlight.png",
  frostbiteTracker: "frostbiteTracker.png",
  ironpawVanguard: "ironpawVanguard.png",
  lastStandLionheart: "lastStandLionheart.png",
  meowchineBerserker: "meowchineBerserker.png",
  meowtallicanGunner: "meowtallicanGunner.png",
  midnightMonsterContract: "midnightMonsterContract.png",
  moonlitWyvernHunt: "moonlitWyvernHunt.png",
  orbitalPounce: "orbitalPounce.png",
  plasmaPurrgeon: "plasmaPurrgeon.png",
  relicbladeRonin: "relicbladeRonin.png",
  seaMonsterSlayer: "seaMonsterSlayer.png",
  silverclawSentinel: "silverclawSentinel.png",
  starBastionCaptain: "starBastionCaptain.png",
  tavernTactician: "tavernTactician.png",
  theAntlerwoodStalker: "theAntlerwoodStalker.png",
  theCataclysmicChaplain: "theCataclysmicChaplain.png",
  theGriffinContract: "theGriffinContract.png",
  theSiegeScratcher: "theSiegeScratcher.png",
  theWarpwayWatcher: "theWarpwayWatcher.png",
  theWhiteWhisker: "theWhiteWhisker.png",
  toxinclawInfiltrator: "toxinclawInfiltrator.png",
  voidclawVeteran: "voidclawVeteran.png",
  voidshieldTemplar: "voidshieldTemplar.png",
  wolfmarkWanderer: "wolfmarkWanderer.png",
  wolfpackFarewell: "wolfpackFarewell.png",
  bloodlineOmen: "bloodlineOmen.png",
  candleclawCatacomb: "candleclawCatacomb.png",
  emberPawPatrol: "emberPawPatrol.png",
  whiskerCoastSurvivor: "whiskerCoastSurvivor.png",
  astapurrion: "astapurrion.png",
  astralclawSkyblade: "astralclawSkyblade.png",
  drizztDoPurrden: "drizztDoPurrden.png",
  elmiaowster: "elmiaowster.png",
  elvenSongblade: "elvenSongblade.png",
  galepaw: "galepaw.png",
  halsinpaw: "halsinpaw.png",
  hearthpawShadowagent: "hearthpawShadowagent.png",
  imeown: "imeown.png",
  jaheirball: "jaheirball.png",
  karlachonk: "karlachonk.png",
  laezclaw: "laezclaw.png",
  minscAndMeow: "minscAndMeow.png",
  sarevmeowk: "sarevmeowk.png",
  shadowpurr: "shadowpurr.png",
  theEmpurror: "theEmpurror.png",
  thisIsTheEnd: "thisIsTheEnd.png",
  whiskerWyll: "whiskerWyll.png",
  winkWink: "winkWink.png",
  adamWhiskersen: "adamWhiskersen.png",
  bankroll: "bankroll.png",
  billBlizzard: "billBlizzard.png",
  bobPawge: "bobPawge.png",
  bullionStack: "bullionStack.png",
  cashCannon: "cashCannon.png",
  fairExchange: "fairExchange.png",
  gemMine: "gemMine.png",
  goldMine: "goldMine.png",
  goldenChalice: "goldenChalice.png",
  goldenGoose: "goldenGoose.png",
  goldenStag: "goldenStag.png",
  handsomeJake: "handsomeJake.png",
  jcDentclaw: "jcDentclaw.png",
  liquidAssets: "liquidAssets.png",
  midasTouch: "midasTouch.png",
  moneyPrinter: "moneyPrinter.png",
  moneyTree: "moneyTree.png",
  nuggetAvalanche: "nuggetAvalanche.png",
  pennyJar: "pennyJar.png",
  purrDenton: "purrDenton.png",
  strikeItRich: "strikeItRich.png",
  vaultDoor: "vaultDoor.png",
  wishingWell: "wishingWell.png",
  youKnowWhatStallion: "youKnowWhatStallion.png",
  annaNyavarre: "annaNyavarre.png",
  batteryCell: "batteryCell.png",
  blackBlade: "blackBlade.png",
  boneFlute: "boneFlute.png",
  coldSteel: "coldSteel.png",
  commando: "commando.png",
  corvidCrown: "corvidCrown.png",
  daedalynx: "daedalynx.png",
  dataCube: "dataCube.png",
  dropTuned: "dropTuned.png",
  eternalFlame: "eternalFlame.png",
  forgeAhead: "forgeAhead.png",
  guntherHairman: "guntherHairman.png",
  heliopaws: "heliopaws.png",
  hornsUp: "hornsUp.png",
  ironKey: "ironKey.png",
  lastCall: "lastCall.png",
  nanoBlade: "nanoBlade.png",
  peltCloak: "peltCloak.png",
  pigIron: "pigIron.png",
  praxisKit: "praxisKit.png",
  quickSilver: "quickSilver.png",
  runicAmulet: "runicAmulet.png",
  scaledGrip: "scaledGrip.png",
  securityTurret: "securityTurret.png",
  shoulderSpikes: "shoulderSpikes.png",
  shredMetal: "shredMetal.png",
  signetOfSkulls: "signetOfSkulls.png",
  stormFork: "stormFork.png",
  studdedBelt: "studdedBelt.png",
  swashbuckler: "swashbuckler.png",
  tempered: "tempered.png",
  theCure: "theCure.png",
  titaniumGrip: "titaniumGrip.png",
  wardingSigil: "wardingSigil.png",
  blackHole: "blackHole.png",
  bottledNebula: "bottledNebula.png",
  eclipse: "eclipse.png",
  treasureMap: "treasureMap.png",
  captainLeFluff: "captainLeFluff.png",
  divingBell: "divingBell.png",
  flooringInspector: "flooringInspector.png",
  kraken: "kraken.png",
  messageInABottle: "messageInABottle.png",
  bullseye: "bullseye.png",
  chainReaction: "chainReaction.png",
  doubleHelix: "doubleHelix.png",
  eureka: "eureka.png",
  goldMedal: "goldMedal.png",
  halfLife: "halfLife.png",
  highRoller: "highRoller.png",
  jackpot: "jackpot.png",
  knockout: "knockout.png",
  pearlDiver: "pearlDiver.png",
  roundAndRound: "roundAndRound.png",
  scratchCard: "scratchCard.png",
  silverware: "silverware.png",
  snakeEyes: "snakeEyes.png",
  twentyOne: "twentyOne.png",
  wheelOfFortune: "wheelOfFortune.png",
  aetherLantern: "aetherLantern.png",
  boilerRoom: "boilerRoom.png",
  brassDiver: "brassDiver.png",
  clockworkHand: "clockworkHand.png",
  cogwork: "cogwork.png",
  fullSteam: "fullSteam.png",
  pocketWatch: "pocketWatch.png",
  tubeDelivery: "tubeDelivery.png",
  windUp: "windUp.png",
  ancientRelic: "ancientRelic.png",
  geometricRelic: "geometricRelic.png",
  berryParfait: "berryParfait.png",
  berrySmoothie: "berrySmoothie.png",
  butterCroissant: "butterCroissant.png",
  cheeseWheel: "cheeseWheel.png",
  chromeArm: "chromeArm.png",
  circuitBreaker: "circuitBreaker.png",
  glassWyvern: "glassWyvern.png",
  goldBar: "goldBar.png",
  honeyToast: "honeyToast.png",
  potionCommotion: "potionCommotion.png",
  lemonTart: "lemonTart.png",
  lifelineLoot: "lifelineLoot.png",
  moonCloak: "moonCloak.png",
  mossbackManticore: "mossbackManticore.png",
  platinumRing: "platinumRing.png",
  sapphireOrbit: "sapphireOrbit.png",
  roboticGripper: "roboticGripper.png",
  silverCoin: "silverCoin.png",
  spicedChai: "spicedChai.png",
  stormBoots: "stormBoots.png",
  sushiPlatter: "sushiPlatter.png",
  thornmailGlove: "thornmailGlove.png",
  gildedCache: "gildedCache.png",
  berryShortcake: "berryShortcake.png",
  brassBanker: "brassBanker.png",
  candyCastle: "candyCastle.png",
  caramelApple: "caramelApple.png",
  catnipSatchel: "catnipSatchel.png",
  cinnamonSwirl: "cinnamonSwirl.png",
  citrusCoin: "citrusCoin.png",
  clockworkSatellite: "clockworkSatellite.png",
  coinCascade: "coinCascade.png",
  comfortFood: "comfortFood.png",
  crownHedgehog: "crownHedgehog.png",
  emberKey: "emberKey.png",
  emberwingDragon2: "emberwingDragon2.png",
  emperorsFinest: "emperorsFinest.png",
  eternalDuty: "eternalDuty.png",
  faithIsOurShield: "faithIsOurShield.png",
  fearNotThePsyker: "fearNotThePsyker.png",
  frostRune: "frostRune.png",
  lanternFox: "lanternFox.png",
  lanternLynx: "lanternLynx.png",
  memoryCrystal: "memoryCrystal.png",
  mochaFroth: "mochaFroth.png",
  coinrootGrove: "coinrootGrove.png",
  neonBeaker: "neonBeaker.png",
  neverSurrender: "neverSurrender.png",
  pearlOtter: "pearlOtter.png",
  pickleParade: "pickleParade.png",
  profitPigeon: "profitPigeon.png",
  purge: "purge.png",
  rainbowRelic: "rainbowRelic.png",
  ramenCrown: "ramenCrown.png",
  redPanda: "redPanda.png",
  silverLaurel: "silverLaurel.png",
  thunderNachos: "thunderNachos.png",
  toTheSkies: "toTheSkies.png",
  treasureTeapot: "treasureTeapot.png",
  whatAreYourOrders: "whatAreYourOrders.png",
  whisperingOrb: "whisperingOrb.png",
  clockworkOwl: "clockworkOwl.png",
  goldenGardenGolem: "goldenGardenGolem.png",
  moonlitMint: "moonlitMint.png",
  vaultBeetle: "vaultBeetle.png",
  lionKey: "lionKey.png",
  restorationProject: "restorationProject.png",
  arfthas: "arfthas.png",
  guldanMeow: "guldanMeow.png",
  sargerasPurrgeras: "sargerasPurrgeras.png",
  sylvanwhisker: "sylvanwhisker.png",
  sylvanasWhiskerunner: "sylvanasWhiskerunner.png",
  jainaPurrmoore: "jainaPurrmoore.png",
  thrallpaw: "thrallpaw.png",
  varianWrynnkles: "varianWrynnkles.png",
  anduinWrynncat: "anduinWrynncat.png",
  illidandelight: "illidandelight.png",
  malfurionStormpaw: "malfurionStormpaw.png",
  voljinWhisker: "voljinWhisker.png",
  lorthemewPurron: "lorthemewPurron.png",
  khadgarPurr: "khadgarPurr.png",
  garroshHellscreamPurr: "garroshHellscreamPurr.png",
  grommewHellscream: "grommewHellscream.png",
  deathwingTheDestroycat: "deathwingTheDestroycat.png",
  deathwingAshwing: "deathwingAshwing.png",
  deathwingDestroypurr: "deathwingDestroypurr.png",
  ragnapurrs: "ragnapurrs.png",
  medivhMewage: "medivhMewage.png",
  tyrandeWhiskerwind: "tyrandeWhiskerwind.png",
  tyrandeMoonwhisker: "tyrandeMoonwhisker.png",
  tyrandeWhisperpaws: "tyrandeWhisperpaws.png",
  tyrandeStarbow: "tyrandeStarbow.png",
  chenStormstout: "chenStormstout.png",
  antleredFoxFortune: "antleredFoxFortune.png",
  emperorProvidesPurrfection: "emperorProvidesPurrfection.png",
  furionStormpaw: "furionStormpaw.png",
  whatIsBrewing: "whatIsBrewing.png",
  goldLion: "goldLion.png",
  goldElephant: "goldElephant.png",
  goldBear: "goldBear.png",
  goldWolf: "goldWolf.png",
  goldOwl: "goldOwl.png",
  goldRam: "goldRam.png",
  goldRabbit: "goldRabbit.png",
  goldCat: "goldCat.png",
  goldenLion: "goldenLion.png",
  loadedBurger: "loadedBurger.png",
  tacoFeast: "tacoFeast.png",
  pizzaSupreme: "pizzaSupreme.png",
  sushiPlatter2: "sushiPlatter2.png",
  sushiPlatter3: "sushiPlatter3.png",
  sushiPlatter4: "sushiPlatter4.png",
  ramenBowl: "ramenBowl.png",
  berrySmoothie2: "berrySmoothie2.png",
  berrySmoothie3: "berrySmoothie3.png",
  berrySmoothie4: "berrySmoothie4.png",
  icedCoffee: "icedCoffee.png",
  tropicalLemonade: "tropicalLemonade.png",
  tropicalLemonade2: "tropicalLemonade2.png",
  hotChocolate: "hotChocolate.png",
  hotChocolate2: "hotChocolate2.png",
  sunsetMargarita: "sunsetMargarita.png",
  blueLagoonCocktail: "blueLagoonCocktail.png",
  blueLagoonCocktail2: "blueLagoonCocktail2.png",
  blueLagoonCocktail3: "blueLagoonCocktail3.png",
  strawberryDaiquiri: "strawberryDaiquiri.png",
  mangoMojito: "mangoMojito.png",
  mangoMojito2: "mangoMojito2.png",
  espressoMartini: "espressoMartini.png",
  chocolateCake: "chocolateCake.png",
  strawberryShortcake: "strawberryShortcake.png",
  rainbowDonut: "rainbowDonut.png",
  iceCreamSundae: "iceCreamSundae.png",
  iceCreamSundae2: "iceCreamSundae2.png",
  macaronTower: "macaronTower.png",
  macaronTower2: "macaronTower2.png",
  batman: "batman.png",
  joker: "joker.png",
  harleyQuinn: "harleyQuinn.png",
  killerCroc: "killerCroc.png",
  mrFreeze: "mrFreeze.png",
  poisonIvy: "poisonIvy.png",
  scarecrow: "scarecrow.png",
  thePenguin: "thePenguin.png",
  theRiddler: "theRiddler.png",
  bane: "bane.png",
  harleyQuinn2: "harleyQuinn2.png",
  killerCroc2: "killerCroc2.png",
  poisonIvy2: "poisonIvy2.png",
  poisonIvy3: "poisonIvy3.png",
  thePenguin2: "thePenguin2.png",
  bestestBoy: "bestestBoy.png",
  doggo: "doggo.png",
  otterlyAdorable: "otterlyAdorable.png",
  apple: "apple.png",
  bulwark: "bulwark.png",
  fullPlate: "fullPlate.png",
  clockworkWizard: "clockworkWizard.png",
  clockworkWizard2: "clockworkWizard2.png",
  cupcake: "cupcake.png",
  donut: "donut.png",
  metalHeart: "metalHeart.png",
  metalHeart2: "metalHeart2.png",
  overlord: "overlord.png",
  potion: "potion.png",
  beerBelly: "beerBelly.png",
  bottomsUp: "bottomsUp.png",
  splitThePot: "splitThePot.png",
  highRoller2: "highRoller2.png",
  highRoller3: "highRoller3.png",
  pokerNight: "pokerNight.png",
  ponyKeg: "ponyKeg.png",
  vodkaWhiskers: "vodkaWhiskers.png",
  wineCountry: "wineCountry.png",
  allowance: "allowance.png",
  allowance2: "allowance2.png",
  amberSpritz: "amberSpritz.png",
  blackberryBramble: "blackberryBramble.png",
  blackberryBramble2: "blackberryBramble2.png",
  copperMugMule: "copperMugMule.png",
  copperMugMule2: "copperMugMule2.png",
  cosmoCashout: "cosmoCashout.png",
  derbyDayJulep: "derbyDayJulep.png",
  derbyDayJulep2: "derbyDayJulep2.png",
  emptyGlass: "emptyGlass.png",
  frenchSeventyFive: "frenchSeventyFive.png",
  hurricaneHour: "hurricaneHour.png",
  hurricaneHour2: "hurricaneHour2.png",
  liquidAssets2: "liquidAssets2.png",
  longIslandLandslide: "longIslandLandslide.png",
  lootBags: "lootBags.png",
  negroniNightfall: "negroniNightfall.png",
  negroniNightfall2: "negroniNightfall2.png",
  oldFashionedFortune: "oldFashionedFortune.png",
  pineappleParadise: "pineappleParadise.png",
  pocketMoney: "pocketMoney.png",
  pocketMoney2: "pocketMoney2.png",
  fortyKOfGold: "40kOfGold.png",
  chaoticTemptation: "chaoticTemptation.png",
  chaoticTemptation2: "chaoticTemptation2.png",
  chaoticTemptation3: "chaoticTemptation3.png",
  chaoticTemptation4: "chaoticTemptation4.png",
  emperorsDividends: "emperorsDividends.png",
  heavyHitter: "heavyHitter.png",
  iAmSpeed: "iAmSpeed.png",
  neverSurrender2: "neverSurrender2.png",
  plushieDog: "plushieDog.png",
  plushieElephant: "plushieElephant.png",
  plushieHamster: "plushieHamster.png",
  plushieOtter: "plushieOtter.png",
  plushiePand: "plushiePand.png",
  plushiePenguin: "plushiePenguin.png",
  plushieRabbit: "plushieRabbit.png",
  plushieRacoon: "plushieRacoon.png",
  plushieSeal: "plushieSeal.png",
  plushieTiger: "plushieTiger.png",
  powerSword: "powerSword.png",
  powerSword2: "powerSword2.png",
  sleepyFox: "sleepyFox.png",
  sleepyPanda: "sleepyPanda.png",
  alicorn: "alicorn.png",
  alicorn2: "alicorn2.png",
  crystallineDragon: "crystallineDragon.png",
  dragonWithEgg: "dragonWithEgg.png",
  griffin: "griffin.png",
  hippocampus: "hippocampus.png",
  hydra: "hydra.png",
  kirin: "kirin.png",
  kitsune: "kitsune.png",
  manticore: "manticore.png",
  manticore2: "manticore2.png",
  manticore3: "manticore3.png",
  pegasus: "pegasus.png",
  phoneix: "phoneix.png",
  puppyPosey: "puppyPosey.png",
  salamander: "salamander.png",
  salamander2: "salamander2.png",
  salamander3: "salamander3.png",
  seaSerpet: "seaSerpet.png",
  thunderbird: "thunderbird.png",
  treant: "treant.png",
  unicorn: "unicorn.png",
  velvetManticore2: "velvetManticore2.png",
  velvetManticore3: "velvetManticore3.png",
  sidecarSurge: "sidecarSurge.png",
  singaporeSling: "singaporeSling.png",
  tikiZombie: "tikiZombie.png",
  tikiZombie2: "tikiZombie2.png",
} as const;
export type ImageName = keyof typeof IMAGE_FILES;

export function getBackgroundUrls(): string[] {
  return backgroundFiles.map(themeAssetUrl);
}

export function getGroundUrl(): string {
  return themeAssetUrl("street.png");
}

export function getSpriteUrl(name: SpriteName): string {
  return themeAssetUrl(SPRITE_FILES[name]);
}

export function loadBackgrounds(): Promise<HTMLImageElement[]> {
  return Promise.all(getBackgroundUrls().map(loadImage));
}

export function loadGroundImage(): Promise<HTMLImageElement> {
  return loadImage(getGroundUrl());
}

export function loadSprite(name: SpriteName): Promise<HTMLImageElement> {
  return loadImage(getSpriteUrl(name));
}

export function getImageUrl(name: ImageName): string {
  const filename = IMAGE_FILES[name];
  return sharedThemeImages.has(filename)
    ? themeAssetUrl(filename)
    : critAssetUrl(filename);
}

// the white-bordered "sticker" cut of the same artwork, generated into
// public/stickers/ by scripts/add-sticker-borders.mjs — used by the Special
// Crits dialog, while the celebration flash draws the plain cut-out
export function getStickerUrl(name: ImageName): string {
  return `${PUBLIC_ASSET_BASE}stickers/${IMAGE_FILES[name]}`;
}

// flat black cut of the same sticker, shown for a crit the player hasn't
// discovered yet — its own file so an undiscovered crit never downloads the
// artwork it's hiding
export function getSilhouetteUrl(name: ImageName): string {
  return `${PUBLIC_ASSET_BASE}silhouettes/${IMAGE_FILES[name]}`;
}

export function loadImageByName(name: ImageName): Promise<HTMLImageElement> {
  return loadImage(getImageUrl(name));
}

export function getCloudUrls(): string[] {
  return cloudFiles.map(themeAssetUrl);
}

export function loadThemeClouds(): Promise<HTMLImageElement[]> {
  return Promise.all(getCloudUrls().map(loadImage));
}
