// Central balance sheet for every number that feeds into "how much money is being
// made" — per-floor income growth, upgrade pricing, crit-tier odds/payouts, sale
// boosts, and corporation-wide modifiers. This is
// the one place to tune when rebalancing income across methods so they stay
// proportionate to each other — nothing else in the codebase should hardcode a
// balance number already owned here; add new tunable values as new fields instead
// of a fresh standalone constant elsewhere. Pure data, no imports — safe for any
// module (including circular-import-sensitive ones like floors/index.ts) to read.

export const CONFIG = {
  // Floor income and interval scale together up to the starting interval limit.
  // With a 1s limit, floors share a base rate; buildings scale the whole economy.
  floors: {
    floorEconomyMultiplierPerBuilding: 1_000,
    baseIncomeAmount: 1,
    incomeGrowthFactor: 2,
    baseIncomeIntervalSeconds: 1,
    baseUpgradeCost: 2,
    baseUnlockCost: 200,
    unlockCostGrowthFactor: 2,
    baseRateStep: 2,
  },

  // src/buildings/index.ts — purchase prices only; floor scaling lives in floors.
  buildings: {
    basePrice: 125_000_000_000,
  },

  // src/floors/incomePanel/index.ts — how a floor's income/interval evolve as
  // it's upgraded, and the bounds its payout cycle is clamped to.
  incomePanel: {
    minIncomeIntervalSeconds: 0.5,
    maxIncomeIntervalSeconds: 1,
    upgradeSpeedLevelScale: 20,
    upgradeMilestoneStep: 10,
    upgradePriceLevelScale: 3,
  },

  // src/floors/upgradeButton/index.ts's CRIT_TIER_CONFIG — odds + free-upgrade/
  // sale-payout/permanent-rate multiplier per tier (color/label are cosmetic,
  // not balance, and stay defined alongside CRIT_TIER_CONFIG itself).
  crit: {
    californiumCrescendoChance: 0.0011525,
    californiumCrescendoUpgrades: 98,
    californiumCrescendoPayouts: 98,
    einsteiniumEpiphanyChance: 0.001145,
    einsteiniumEpiphanyUpgrades: 99,
    einsteiniumEpiphanyPayouts: 99,
    fermiumFormulaChance: 0.0011375,
    fermiumFormulaUpgrades: 100,
    fermiumFormulaPayouts: 100,
    mendeleviumMajestyChance: 0.00113,
    mendeleviumMajestyUpgrades: 101,
    mendeleviumMajestyPayouts: 101,
    nobeliumLaureateChance: 0.0011225,
    nobeliumLaureateUpgrades: 102,
    nobeliumLaureatePayouts: 102,
    lawrenciumLightspeedChance: 0.001115,
    lawrenciumLightspeedUpgrades: 103,
    lawrenciumLightspeedPayouts: 103,
    rutherfordiumReachChance: 0.0011075,
    rutherfordiumReachUpgrades: 104,
    rutherfordiumReachPayouts: 104,
    seaborgiumSwellChance: 0.0010925,
    seaborgiumSwellUpgrades: 106,
    seaborgiumSwellPayouts: 106,
    bohriumSummitChance: 0.001085,
    bohriumSummitUpgrades: 107,
    bohriumSummitPayouts: 107,
    hassiumMeteorChance: 0.0010775,
    hassiumMeteorUpgrades: 108,
    hassiumMeteorPayouts: 108,
    meitneriumMarvelChance: 0.00107,
    meitneriumMarvelUpgrades: 109,
    meitneriumMarvelPayouts: 109,
    darmstadtiumDowntownChance: 0.0010625,
    darmstadtiumDowntownUpgrades: 110,
    darmstadtiumDowntownPayouts: 110,
    roentgeniumRevelationChance: 0.001055,
    roentgeniumRevelationUpgrades: 111,
    roentgeniumRevelationPayouts: 111,
    coperniciumCarouselChance: 0.0010475,
    coperniciumCarouselUpgrades: 112,
    coperniciumCarouselPayouts: 112,
    nihoniumDaybreakChance: 0.00104,
    nihoniumDaybreakUpgrades: 113,
    nihoniumDaybreakPayouts: 113,
    fleroviumFortressChance: 0.0010325,
    fleroviumFortressUpgrades: 114,
    fleroviumFortressPayouts: 114,
    moscoviumMosaicChance: 0.001025,
    moscoviumMosaicUpgrades: 115,
    moscoviumMosaicPayouts: 115,
    livermoriumLightningChance: 0.0010175,
    livermoriumLightningUpgrades: 116,
    livermoriumLightningPayouts: 116,
    tennessineTwinkleChance: 0.00101,
    tennessineTwinkleUpgrades: 117,
    tennessineTwinklePayouts: 117,
    oganessonOdysseyChance: 0.0010025,
    oganessonOdysseyUpgrades: 118,
    oganessonOdysseyPayouts: 118,
    heavyElementChance: 0.013,
    heavyElementUpgrades: 7,
    heavyElementPayouts: 5,
    bubbleButtChance: 0.035,
    bubbleButtUpgrades: 8,
    bubbleButtPayouts: 9,
    canNotLieChance: 0.025,
    canNotLieUpgrades: 12,
    canNotLiePayouts: 15,
    badonkadonkChance: 0.03,
    badonkadonkUpgrades: 10,
    badonkadonkPayouts: 12,
    demonicBunsChance: 0.015,
    demonicBunsUpgrades: 16,
    demonicBunsPayouts: 21,
    infernalInterestChance: 0.01,
    infernalInterestUpgrades: 20,
    infernalInterestPayouts: 27,
    dropItLowChance: 0.04,
    dropItLowUpgrades: 9,
    dropItLowPayouts: 5,
    kittyWagonChance: 0.03,
    kittyWagonUpgrades: 3,
    kittyWagonPayouts: 2,
    madeYouLookChance: 0.04,
    madeYouLookUpgrades: 6,
    madeYouLookPayouts: 7,
    wagonWarriorChance: 0.02,
    wagonWarriorUpgrades: 5,
    wagonWarriorPayouts: 3,
    goldenSkullChance: 0.02,
    goldenSkullUpgrades: 13,
    goldenSkullPayouts: 19,
    lordOfMurderChance: 0.008,
    lordOfMurderUpgrades: 8,
    lordOfMurderPayouts: 6,
    speedDemonChance: 0.023,
    speedDemonUpgrades: 11,
    speedDemonPayouts: 17,
    circuitDuchessChance: 0.035,
    circuitDuchessUpgrades: 6,
    circuitDuchessPayouts: 13,
    cyberCatChance: 0.018,
    cyberCatUpgrades: 4,
    cyberCatPayouts: 7,
    chromeChassisChance: 0.014,
    chromeChassisUpgrades: 6,
    chromeChassisPayouts: 5,
    elbowRoomChance: 0.032,
    elbowRoomUpgrades: 9,
    elbowRoomPayouts: 8,
    heartwareChance: 0.028,
    heartwareUpgrades: 7,
    heartwarePayouts: 18,
    pulseDividendChance: 0.022,
    pulseDividendUpgrades: 9,
    pulseDividendPayouts: 24,
    neonNegotiatorChance: 0.029,
    neonNegotiatorUpgrades: 8,
    neonNegotiatorPayouts: 11,
    platinumRefrainChance: 0.01,
    platinumRefrainUpgrades: 7,
    platinumRefrainPayouts: 8,
    retinaRoyaleChance: 0.024,
    retinaRoyaleUpgrades: 10,
    retinaRoyalePayouts: 16,
    silverHandshakeChance: 0.045,
    silverHandshakeUpgrades: 4,
    silverHandshakePayouts: 6,
    staticEncoreChance: 0.023,
    staticEncoreUpgrades: 5,
    staticEncorePayouts: 7,
    chromeDomeChance: 0.017,
    chromeDomeUpgrades: 14,
    chromeDomePayouts: 23,
    skullSyndicateChance: 0.007,
    skullSyndicateUpgrades: 9,
    skullSyndicatePayouts: 7,
    osmiumRegaliaChance: 0.002,
    osmiumRegaliaUpgrades: 76,
    osmiumRegaliaPayouts: 76,
    iridiumAegisChance: 0.00196,
    iridiumAegisUpgrades: 77,
    iridiumAegisPayouts: 77,
    mercuryFlowChance: 0.00184,
    mercuryFlowUpgrades: 80,
    mercuryFlowPayouts: 80,
    thalliumThriveChance: 0.0018,
    thalliumThriveUpgrades: 81,
    thalliumThrivePayouts: 81,
    leadLodeChance: 0.00176,
    leadLodeUpgrades: 82,
    leadLodePayouts: 82,
    bismuthBastionChance: 0.00172,
    bismuthBastionUpgrades: 83,
    bismuthBastionPayouts: 83,
    poloniumPrismChance: 0.00168,
    poloniumPrismUpgrades: 84,
    poloniumPrismPayouts: 84,
    astatineAuroraChance: 0.00164,
    astatineAuroraUpgrades: 85,
    astatineAuroraPayouts: 85,
    radonRippleChance: 0.0016,
    radonRippleUpgrades: 86,
    radonRipplePayouts: 86,
    franciumFortuneChance: 0.00156,
    franciumFortuneUpgrades: 87,
    franciumFortunePayouts: 87,
    radiumRhythmChance: 0.00152,
    radiumRhythmUpgrades: 88,
    radiumRhythmPayouts: 88,
    actiniumArcChance: 0.00148,
    actiniumArcUpgrades: 89,
    actiniumArcPayouts: 89,
    thoriumThroneChance: 0.00144,
    thoriumThroneUpgrades: 90,
    thoriumThronePayouts: 90,
    protactiniumOrbitChance: 0.0014,
    protactiniumOrbitUpgrades: 91,
    protactiniumOrbitPayouts: 91,
    neptuniumNovaChance: 0.00132,
    neptuniumNovaUpgrades: 93,
    neptuniumNovaPayouts: 93,
    plutoniumPulseChance: 0.00128,
    plutoniumPulseUpgrades: 94,
    plutoniumPulsePayouts: 94,
    americiumAlarmChance: 0.00124,
    americiumAlarmUpgrades: 95,
    americiumAlarmPayouts: 95,
    curiumCrucibleChance: 0.0012,
    curiumCrucibleUpgrades: 96,
    curiumCruciblePayouts: 96,
    berkeliumBreakthroughChance: 0.00116,
    berkeliumBreakthroughUpgrades: 97,
    berkeliumBreakthroughPayouts: 97,
    nucleusDividendChance: 0.014,
    nucleusDividendUpgrades: 6,
    nucleusDividendPayouts: 4,
    hydrogenHypeChance: 0.09,
    hydrogenHypeUpgrades: 1,
    hydrogenHypePayouts: 1,
    heliumHighriseChance: 0.08,
    heliumHighriseUpgrades: 2,
    heliumHighrisePayouts: 2,
    lithiumLiftChance: 0.07,
    lithiumLiftUpgrades: 3,
    lithiumLiftPayouts: 3,
    berylliumBrillianceChance: 0.06,
    berylliumBrillianceUpgrades: 4,
    berylliumBrilliancePayouts: 4,
    carbonCrownChance: 0.05,
    carbonCrownUpgrades: 6,
    carbonCrownPayouts: 6,
    nitrogenNimbusChance: 0.048,
    nitrogenNimbusUpgrades: 7,
    nitrogenNimbusPayouts: 7,
    oxygenOverdriveChance: 0.046,
    oxygenOverdriveUpgrades: 8,
    oxygenOverdrivePayouts: 8,
    fluorineFlashChance: 0.044,
    fluorineFlashUpgrades: 9,
    fluorineFlashPayouts: 9,
    sodiumSprinkleChance: 0.04,
    sodiumSprinkleUpgrades: 11,
    sodiumSprinklePayouts: 11,
    magnesiumMagnificenceChance: 0.038,
    magnesiumMagnificenceUpgrades: 12,
    magnesiumMagnificencePayouts: 12,
    aluminumAllStarChance: 0.036,
    aluminumAllStarUpgrades: 13,
    aluminumAllStarPayouts: 13,
    siliconSparkChance: 0.034,
    siliconSparkUpgrades: 14,
    siliconSparkPayouts: 14,
    phosphorusFlareChance: 0.032,
    phosphorusFlareUpgrades: 15,
    phosphorusFlarePayouts: 15,
    sulfurSunshineChance: 0.03,
    sulfurSunshineUpgrades: 16,
    sulfurSunshinePayouts: 16,
    chlorineConfettiChance: 0.028,
    chlorineConfettiUpgrades: 17,
    chlorineConfettiPayouts: 17,
    argonAfterglowChance: 0.026,
    argonAfterglowUpgrades: 18,
    argonAfterglowPayouts: 18,
    potassiumPopChance: 0.024,
    potassiumPopUpgrades: 19,
    potassiumPopPayouts: 19,
    calciumCornerstoneChance: 0.022,
    calciumCornerstoneUpgrades: 20,
    calciumCornerstonePayouts: 20,
    scandiumStrongholdChance: 0.015,
    scandiumStrongholdUpgrades: 21,
    scandiumStrongholdPayouts: 21,
    titaniumTakeoffChance: 0.0147,
    titaniumTakeoffUpgrades: 22,
    titaniumTakeoffPayouts: 22,
    vanadiumVoltageChance: 0.0144,
    vanadiumVoltageUpgrades: 23,
    vanadiumVoltagePayouts: 23,
    chromiumGleamChance: 0.0141,
    chromiumGleamUpgrades: 24,
    chromiumGleamPayouts: 24,
    manganeseMomentumChance: 0.0138,
    manganeseMomentumUpgrades: 25,
    manganeseMomentumPayouts: 25,
    ironEmpireChance: 0.0135,
    ironEmpireUpgrades: 26,
    ironEmpirePayouts: 26,
    cobaltChargeChance: 0.0132,
    cobaltChargeUpgrades: 27,
    cobaltChargePayouts: 27,
    nickelNestEggChance: 0.0129,
    nickelNestEggUpgrades: 28,
    nickelNestEggPayouts: 28,
    copperCurrentChance: 0.0126,
    copperCurrentUpgrades: 29,
    copperCurrentPayouts: 29,
    zincZingChance: 0.0123,
    zincZingUpgrades: 30,
    zincZingPayouts: 30,
    galliumGlitterChance: 0.012,
    galliumGlitterUpgrades: 31,
    galliumGlitterPayouts: 31,
    germaniumGeniusChance: 0.0117,
    germaniumGeniusUpgrades: 32,
    germaniumGeniusPayouts: 32,
    arsenicAlchemyChance: 0.0114,
    arsenicAlchemyUpgrades: 33,
    arsenicAlchemyPayouts: 33,
    seleniumSunburstChance: 0.0111,
    seleniumSunburstUpgrades: 34,
    seleniumSunburstPayouts: 34,
    bromineBountyChance: 0.0108,
    bromineBountyUpgrades: 35,
    bromineBountyPayouts: 35,
    kryptonKeepsakeChance: 0.0105,
    kryptonKeepsakeUpgrades: 36,
    kryptonKeepsakePayouts: 36,
    rubidiumRadianceChance: 0.0102,
    rubidiumRadianceUpgrades: 37,
    rubidiumRadiancePayouts: 37,
    strontiumSpectacleChance: 0.0099,
    strontiumSpectacleUpgrades: 38,
    strontiumSpectaclePayouts: 38,
    yttriumYieldChance: 0.0096,
    yttriumYieldUpgrades: 39,
    yttriumYieldPayouts: 39,
    zirconiumZenithChance: 0.0093,
    zirconiumZenithUpgrades: 40,
    zirconiumZenithPayouts: 40,
    niobiumNexusChance: 0.009,
    niobiumNexusUpgrades: 41,
    niobiumNexusPayouts: 41,
    molybdenumMachineChance: 0.0087,
    molybdenumMachineUpgrades: 42,
    molybdenumMachinePayouts: 42,
    technetiumTimebankChance: 0.0084,
    technetiumTimebankUpgrades: 43,
    technetiumTimebankPayouts: 43,
    rutheniumRichesChance: 0.0081,
    rutheniumRichesUpgrades: 44,
    rutheniumRichesPayouts: 44,
    rhodiumReflectionChance: 0.0078,
    rhodiumReflectionUpgrades: 45,
    rhodiumReflectionPayouts: 45,
    palladiumPilotChance: 0.0075,
    palladiumPilotUpgrades: 46,
    palladiumPilotPayouts: 46,
    silverMoonriseChance: 0.0072,
    silverMoonriseUpgrades: 47,
    silverMoonrisePayouts: 47,
    cadmiumCatalystChance: 0.0069,
    cadmiumCatalystUpgrades: 48,
    cadmiumCatalystPayouts: 48,
    indiumInsightChance: 0.0066,
    indiumInsightUpgrades: 49,
    indiumInsightPayouts: 49,
    tinTreasureChance: 0.0063,
    tinTreasureUpgrades: 50,
    tinTreasurePayouts: 50,
    antimonyAscensionChance: 0.003,
    antimonyAscensionUpgrades: 51,
    antimonyAscensionPayouts: 51,
    telluriumTreasurelightChance: 0.00296,
    telluriumTreasurelightUpgrades: 52,
    telluriumTreasurelightPayouts: 52,
    iodineIridescenceChance: 0.00292,
    iodineIridescenceUpgrades: 53,
    iodineIridescencePayouts: 53,
    xenonSpotlightChance: 0.00288,
    xenonSpotlightUpgrades: 54,
    xenonSpotlightPayouts: 54,
    cesiumClockworkChance: 0.00284,
    cesiumClockworkUpgrades: 55,
    cesiumClockworkPayouts: 55,
    bariumBeaconChance: 0.0028,
    bariumBeaconUpgrades: 56,
    bariumBeaconPayouts: 56,
    lanthanumLusterChance: 0.00276,
    lanthanumLusterUpgrades: 57,
    lanthanumLusterPayouts: 57,
    ceriumShineChance: 0.00272,
    ceriumShineUpgrades: 58,
    ceriumShinePayouts: 58,
    praseodymiumPrismChance: 0.00268,
    praseodymiumPrismUpgrades: 59,
    praseodymiumPrismPayouts: 59,
    neodymiumNorthstarChance: 0.00264,
    neodymiumNorthstarUpgrades: 60,
    neodymiumNorthstarPayouts: 60,
    promethiumPulseChance: 0.0026,
    promethiumPulseUpgrades: 61,
    promethiumPulsePayouts: 61,
    samariumSanctuaryChance: 0.00256,
    samariumSanctuaryUpgrades: 62,
    samariumSanctuaryPayouts: 62,
    europiumEncoreChance: 0.00252,
    europiumEncoreUpgrades: 63,
    europiumEncorePayouts: 63,
    gadoliniumGlanceChance: 0.00248,
    gadoliniumGlanceUpgrades: 64,
    gadoliniumGlancePayouts: 64,
    terbiumTempoChance: 0.00244,
    terbiumTempoUpgrades: 65,
    terbiumTempoPayouts: 65,
    dysprosiumDirectionChance: 0.0024,
    dysprosiumDirectionUpgrades: 66,
    dysprosiumDirectionPayouts: 66,
    holmiumHaloChance: 0.00236,
    holmiumHaloUpgrades: 67,
    holmiumHaloPayouts: 67,
    erbiumEleganceChance: 0.00232,
    erbiumEleganceUpgrades: 68,
    erbiumElegancePayouts: 68,
    thuliumThawChance: 0.00228,
    thuliumThawUpgrades: 69,
    thuliumThawPayouts: 69,
    ytterbiumHourglassChance: 0.00224,
    ytterbiumHourglassUpgrades: 70,
    ytterbiumHourglassPayouts: 70,
    lutetiumLimelightChance: 0.0022,
    lutetiumLimelightUpgrades: 71,
    lutetiumLimelightPayouts: 71,
    hafniumHorizonChance: 0.00216,
    hafniumHorizonUpgrades: 72,
    hafniumHorizonPayouts: 72,
    tantalumTroveChance: 0.00212,
    tantalumTroveUpgrades: 73,
    tantalumTrovePayouts: 73,
    tungstenTriumphChance: 0.00208,
    tungstenTriumphUpgrades: 74,
    tungstenTriumphPayouts: 74,
    rheniumRocketChance: 0.00204,
    rheniumRocketUpgrades: 75,
    rheniumRocketPayouts: 75,
    platinumPodiumChance: 0.00192,
    platinumPodiumUpgrades: 78,
    platinumPodiumPayouts: 78,
    goldenAtomChance: 0.00188,
    goldenAtomUpgrades: 79,
    goldenAtomPayouts: 79,
    uraniumUpliftChance: 0.00136,
    uraniumUpliftUpgrades: 92,
    uraniumUpliftPayouts: 92,
    crit: { chance: 0.08, multiplier: 5 },
    mega: { chance: 0.015, multiplier: 25 },
    ultra: { chance: 0.001, multiplier: 125 },
    // gateway roll for the whole "special crit" (chain/boost/bounce/
    // explosion/booty/upgrade) system: checked ONCE per landed crit/mega/
    // ultra, before any of the 6 individual proc chances below are even
    // rolled — a miss here means NONE of them get a chance to land at all
    // this time, silently (see rollCrit in shared/critTypes). A hit just
    // opens the door to the existing independent-roll-then-cap-at-2 logic,
    // it doesn't guarantee a proc actually lands
    specialCritGatewayChance: 0.25,
    bonusTierGatewayChance: 0.01,
    // "chain crit" — an extra roll on top of an already-landed crit/mega/ultra
    // (see rollCritUpgrade): applies that same tier's upgrade to the next floor
    // too, then has chainContinueChance to keep going up the building one floor
    // at a time
    chainChance: 0.08,
    chainContinueChance: 0.5,
    // "domino effect" — starts with one free upgrade on the critted floor,
    // then has a 50% chance to reach each floor above it with double the
    // previous floor's upgrade count
    dominoEffectChance: 0.04,
    dominoEffectContinueChance: 0.5,
    // "blueprint" crit — unlocks the next floor and copies the triggering
    // floor's upgrades, workers, and manager to it for free
    blueprintChance: 0.04,
    // "boost crit" — a separate, independent roll from chain, but only ever
    // checked once a crit/mega/ultra tier has already landed on this same
    // click: it piggybacks on that tier's own free-upgrade payout instead of
    // replacing it, adding a free worker boost on top
    boostChance: 0.1,
    // "bounce crit" — same shape as chain (extends the landed tier's
    // free-upgrade payout floor by floor), but starts from the BOTTOM of the
    // building (floor 0) and climbs up, instead of starting at the floor that
    // actually crit
    bounceChance: 0.08,
    bounceContinueChance: 0.5,
    // "explosion crit" — same shape as chain again, but spreads BOTH
    // directions (up AND down) from the floor that actually crit, instead of
    // only upward
    explosionChance: 0.06,
    explosionContinueChance: 0.5,
    // "booty crit" — a flat one-time effect (not tier-scaled, same as boost):
    // doubles the CURRENTLY ACTIVE company's total income once
    bootyChance: 0.03,
    // "cash flow" — a flat one-time effect: pays one second of the combined
    // income rate across every corporation, without loading dormant buildings
    cashFlowChance: 0.03,
    // "upgrade crit" — a flat one-time effect (not tier-scaled, same as
    // boost/booty): permanently promotes the affected floor's (or, for a
    // building-unlock crit, EVERY floor in that building's) own
    // critMultiplierTier one step further (see shared/critTypes' nextCritTier)
    upgradeChance: 0.012,
    // "peppermint crit" — a flat one-time effect, not tier-scaled, but a much
    // bigger swing than a single upgrade crit: promotes every OTHER unlocked
    // floor in the building one tier step at once (see shared/critTypes'
    // nextCritTier). Rarer than upgradeChance since it's a guaranteed
    // building-wide effect instead of a single floor
    peppermintChance: 0.002,
    // "heavenly crit" — the single biggest reward in the game: unlocks every
    // remaining floor in the building for free, promotes every floor (new
    // ones included) straight to the max tier, then grants that tier's own
    // free-upgrade batch to every floor. Rarer than peppermintChance since a
    // fully-unlocked, fully-maxed building is a far bigger swing than
    // promoting alternating floors one step
    heavenlyChance: 0.0001,
    // "skip crit" — unlocks every floor and buys its upgrade items for free,
    // without changing floor tiers or upgrade levels
    skipChance: 0.0001,
    // "mystic crit" — map-only: buys one extra building for free and gives
    // its ground floor exactly 10 normal upgrade-rate increases
    mysticChance: 0.001,
    // "keynote" — grants 10 free upgrades to the floor that crits
    keynoteChance: 0.03,
    // "pair"/"three of a kind"/"four of a kind"/"full house" crits — four more
    // flat, not-tier-scaled procs (see shared/critTypes' POKER_HAND_CRIT_COUNTS):
    // each promotes a FIXED number of floors' own permanent crit tier one step
    // (2/3/4/5 respectively), auto-unlocking locked floors along the way if the
    // building doesn't have enough unlocked ones yet. Rarer as the count grows,
    // same "bigger guaranteed swing costs more" logic as peppermint/heavenly
    pairChance: 0.02,
    threeOfAKindChance: 0.012,
    fourOfAKindChance: 0.006,
    fullHouseChance: 0.003,
    // "royal flush crit" — same shape again, the natural next step past full
    // house's 5: promotes 6 floors. Rarer still, same "bigger guaranteed
    // swing costs more" logic
    royalFlushChance: 0.0015,
    // "lucky number" — unlocks a random 2-12 floors in this building for free
    luckyNumberChance: 0.001,
    // "open book" — pays the current value of upgrades bought across every building
    openBookChance: 0.02,
    // "tick tock crit" — a flat, not-tier-scaled proc: instantly credits every
    // unlocked floor 2 extra payouts' worth of income at its own current rate,
    // without touching its fill-cycle progress (see shared/income's
    // floor.lastCollectedAt) — the bar keeps ticking from exactly where it was
    tickTockChance: 0.1,
    // "Chair Giveaway"/"Supplies Giveaway" crits — flat, not-tier-scaled procs: grant
    // the floor being upgraded its one-time office chairs/supplies purchase
    // (see hud/upgradeMenu's buyOfficeChairs/buyOfficeSupplies) for free,
    // if it doesn't already have it
    chairGiveawayChance: 0.1,
    suppliesGiveawayChance: 0.1,
    // "winter sale"/"spring sale"/"summer sale"/"autumn sale" crits — four
    // more flat, not-tier-scaled procs, all sharing one effect (see
    // shared/critTypes' SEASONAL_SALE_DISCOUNT_MULTIPLIER): permanently cut
    // every unlocked floor's own upgrade AND worker/office chairs/supplies/
    // manager costs by 25%, for the WHOLE building the roll happened in
    winterSaleChance: 0.04,
    springSaleChance: 0.04,
    summerSaleChance: 0.04,
    autumnSaleChance: 0.04,
    // 0.25 = 25% off; procs multiply the affected cost by 1 - this
    seasonalSaleDiscount: 0.25,
    // "halloween sale" crit — same shape as the 4 seasonal sales above (same
    // floor/upgrade/worker cost cut, same building-wide scope), but its own
    // steeper discount (see shared/critTypes' HALLOWEEN_SALE_DISCOUNT_MULTIPLIER)
    halloweenSaleChance: 0.02,
    // 0.5 = 50% off — double the seasonal sales' own 25%
    halloweenSaleDiscount: 0.5,
    // "easter sale" crit — same shape/steeper discount again as halloween
    // sale above, just its own icon/label/color (see shared/critTypes'
    // EASTER_SALE_DISCOUNT_MULTIPLIER)
    easterSaleChance: 0.02,
    easterSaleDiscount: 0.5,
    // "sunshine crit" — same free-worker-boost reward as boost above, just
    // its own longer duration (see shared/critTypes' SUNSHINE_BOOST_DURATION_MS)
    sunshineChance: 0.08,
    // "snowday crit" — same free-worker-boost reward as sunshine above, just
    // its own longer duration still (see shared/critTypes' SNOWDAY_BOOST_DURATION_MS)
    snowdayChance: 0.06,
    // "fast forward crit" — same instant-income reward as tick tock above,
    // just a steeper multiplier (see shared/critTypes' FAST_FORWARD_PAYOUT_MULTIPLIER)
    fastForwardChance: 0.05,
    // "frozen crit" — starts a window (see
    // upgradeButton.ts's isFrozenActive/triggerFrozenCrit) during which this
    // floor's own upgradeCost stops growing entirely (see incomePanel.ts's
    // increaseIncomeRate) — upgrades still cost real money as normal, just
    // at whatever price was already locked in when the window started
    frozenChance: 0.1,
    frozenDurationMs: 5000,
    // "spending freeze crit" — locks every unlocked floor's current upgrade
    // price for the whole building for a short window
    spendingFreezeChance: 0.05,
    spendingFreezeDurationMs: 5000,
    // "snowball crit" — a flat, not-tier-scaled proc (see shared/critTypes'
    // applySnowballCrit): instantly credits every unlocked floor 1 extra
    // payout's worth of income at its own current rate, multiplied by how
    // many floors are currently unlocked — the more floors owned, the bigger
    // the snowball
    snowballChance: 0.05,
    // "free sale crit" — no reward of its own: just triggers the SAME "Sale"
    // event hud/boostMenu's paid purchase starts (see
    // floorInteractions.ts's applyFreeSaleCrit/upgradeButton.ts's
    // triggerSaleBoost), for free
    freeSaleChance: 0.08,
    // "bull market crit" — doubles every unlocked floor's own upgradeCount
    // building-wide (see floorInteractions.ts's applyBullMarketCrit), same
    // recompute-from-increaseIncomeRate approach applyHeavenlyCrit uses
    bullMarketChance: 0.02,
    // "payday crit" — a flat one-time effect (not tier-scaled, same shape as
    // booty): triples the CURRENTLY ACTIVE company's total income once
    paydayChance: 0.03,
    // "gold standard crit" — same flat one-time effect as payday, just a
    // steeper multiplier
    goldStandardChance: 0.01,
    // "night shift crit" — same building-wide free-worker-boost reward as
    // boost/sunshine/snowday above, but SHORTER than plain boost's own
    // duration, and temporarily counts as +1 worker for boost-strength
    // purposes (see shared/critTypes' NIGHT_SHIFT_BOOST_DURATION_MS)
    nightShiftChance: 0.08,
    // "Intern"/"Union Boss" crits — flat, not-tier-scaled procs: grant the
    // floor being upgraded one free worker/manager (see hud/upgradeMenu's
    // buyWorker/buyManager), free of charge
    internChance: 0.1,
    // "Talent Scout" crit — adds one capped worker, then briefly boosts every
    // actual worker on the critted floor
    talentScoutChance: 0.08,
    unionBossChance: 0.08,
    // "Rush Hour" crit — for rushHourDurationMs, every unlocked floor's own
    // income timer is capped at rushHourIntervalSeconds (never slowed down —
    // see shared/critTypes' isRushHourActive), stacking with whatever worker
    // boost/office-upgrade speedup already applies; a floor already faster
    // than the cap is left completely untouched
    rushHourChance: 0.08,
    rushHourIntervalSeconds: 0.5,
    rushHourDurationMs: 15000,
    // "Rate Lock" crit — for one floor, guarantees a half-length income interval
    // multiplier for a short window without changing its stored interval
    rateLockChance: 0.08,
    rateLockSpeedMultiplier: 0.5,
    rateLockDurationMs: 10000,
    // "Golden Ticket" crit — no instant reward: guarantees the very NEXT
    // crit roll on this floor lands ultra, bypassing every tier chance (and
    // every other piggyback proc's own chance) entirely for that one roll
    // (see shared/critTypes' isGoldenTicketCrit / upgradeButton's
    // armGuaranteedUltraCrit). Rare, since it's a guaranteed jackpot
    goldenTicketChance: 0.008,
    // "Silver Ticket" crit — same shape as Golden Ticket, but guarantees
    // only mega instead of ultra (see upgradeButton's armGuaranteedMegaCrit)
    // — a smaller guaranteed swing, so less rare than Golden Ticket
    silverTicketChance: 0.02,
    // "Grand Opening" crit — if it lands on a map building purchase, buys
    // the next building for free; if it lands on an upgrade/floor unlock,
    // unlocks every remaining floor in that building for free. Big swing,
    // so keep rarer than most flat one-time procs
    grandOpeningChance: 0.001,
    // "Fully Staffed" crit — fills every unlocked floor to its worker cap and
    // grants every manager-eligible unlocked floor a manager for free
    fullyStaffedChance: 0.02,
    // "Shift Change" crit — fills the critted floor and the immediately lower
    // unlocked floor to the rendered worker cap
    shiftChangeChance: 0.08,
    // "Espresso Shot" crit — boosts every unlocked floor's workers for the
    // regular boost duration, with the same canonical worker-speed behavior
    espressoShotChance: 0.08,
    // "Deja Vu" crit — chooses a random crit tier at consumption time and
    // applies that tier's free-upgrade batch twice
    dejaVuChance: 0.02,
    // "Reinforcements" crit - copies the largest unlocked floor workforce to all
    // other unlocked floors for free
    cloneArmyChance: 0.03,
    // "Lucky Clover" crit — instantly pays out 4 back-to-back ultra-tier
    // crits on the floor; rare, since that's 500 free upgrades at once
    luckyCloverChance: 0.004,
    // "Second Wind" crit — refunds everything the active company has ever
    // spent on upgrades, floor unlocks and building purchases
    secondWindChance: 0.008,
    // "Executive Order" crit — promotes every floor in the building one
    // permanent crit tier step at once
    executiveOrderChance: 0.006,
    // "Round Up" crit — tops every unlocked floor's upgradeCount up to the
    // next multiple of 10, for free
    roundUpChance: 0.04,
    // "Safety Net" crit — gives 5 free upgrades to the most expensive
    // unlocked floor in the building
    safetyNetChance: 0.04,
    // "Floor Share" crit - gives the critted floor one temporary upgrade
    // reward scaled by its own level plus every unlocked floor below it
    floorShareChance: 0.04,
    // "Same Boat" crit - gives the critted floor twice the Floor Share
    // temporary reward
    sameBoatChance: 0.02,
    // "Golden Handshake" crit — hands every unlocked floor a free manager at
    // once (Union Boss's building-wide sibling)
    goldenHandshakeChance: 0.03,
    // "Supply Run" crit — free office chairs AND supplies for the floor that
    // crit, in one go
    supplyRunChance: 0.08,
    // "Casual Friday" crit — a flat batch of free upgrades for every unlocked
    // floor in the building
    casualFridayChance: 0.05,
    // "Fancy Friday" crit — Casual Friday's bigger sibling: twice the free
    // upgrades on every unlocked floor
    fancyFridayChance: 0.025,
    // "Fire Drill" crit — instantly completes every unlocked floor's income
    // timer once, paying it out and restarting the bar
    fireDrillChance: 0.08,
    // "Bonus Round" crit — completes the critted floor's income timer twice,
    // paying two current payouts and restarting that floor's bar
    bonusRoundChance: 0.08,
    // "Overflow" crit — pays five current income timer payouts on the critted
    // floor, then restarts that floor's bar
    overflowChance: 0.06,
    // "Performance Bonus" crit — completes one income timer per worker and
    // manager on every unlocked floor
    performanceBonusChance: 0.06,
    // "Double Down" crit — replays the tier that spawned it twice more on the
    // same floor, so it scales with whatever landed (up to 250 extra free
    // upgrades off an ultra); priced like the other tier-scaled repeats
    doubleDownChance: 0.015,
    // "Coffee Run" crit — same building-wide free-worker-boost reward as
    // boost/sunshine/snowday, but the longest duration of the family (a full
    // minute), so rarer than any of them
    coffeeRunChance: 0.03,
    // "Team Building" crit — one free worker on every unlocked floor at once
    // (Intern's building-wide sibling, priced like Golden Handshake)
    teamBuildingChance: 0.03,
    // "Team Lunch" crit — doubles the normal boost duration for every actual
    // worker on only the floor where the crit landed
    teamLunchChance: 0.08,
    // "Spring Cleaning" crit — promotes every unlocked floor one permanent tier
    // AND resets it to a fresh, un-upgraded floor at that higher tier; a floor
    // already at the top tier is left alone. Trades banked upgrades for a
    // permanently better multiplier, so priced with the other tier promotions
    springCleaningChance: 0.006,
    // "Night Owl" crit — Night Shift's reward with twice the virtual-worker
    // bump (+2 instead of +1), so a touch rarer than it
    nightOwlChance: 0.05,
    // "Headhunter" crit — matches the floor that crit to the building's
    // best-staffed floor; a no-op if it's already the best, so priced like
    // the other single-floor staffing procs
    headhunterChance: 0.06,
    // "Dress Code" crit — adds a manager or worker on every unlocked floor
    dressCodeChance: 0.08,
    // "Tea Break" crit — grants one free upgrade to the floor that landed it
    teaBreakChance: 0.08,
    // "Recruitment Drive" crit — fills this floor and contiguous unlocked
    // floors above it, stopping at the first maxed or locked floor
    recruitmentDriveChance: 0.06,
    // "Merger" crit - synchronizes lower unlocked floors to the landing
    // floor's upgrade level, bounded by the levels already earned there
    mergerChance: 0.03,
    // "Golden Parachute" crit — a flat, not-tier-scaled instant payout (see
    // floorInteractions.ts's applyGoldenParachuteCrit): instantly adds 15
    // seconds' worth of the currently active company's own combined income
    // rate (across every one of its buildings), straight to its total
    goldenParachuteChance: 0.03,
    // "Rain Check" crit — pays 5 seconds of the landed building's combined
    // current income rate
    rainCheckChance: 0.03,
    rainCheckSeconds: 5,
    // "Executive Bonus" crit — pays 25% of the active company's asset value
    executiveBonusChance: 0.04,
    powerSurgeChance: 0.05,
    priceMatchChance: 0.05,
    priceMatchDurationMs: 5000,
    firstClassChance: 0.05,
    // "Payout" crit — the biggest flat one-time jackpot: instantly adds the
    // combined total income + upgrades value across EVERY corporation (not
    // just the active one) to the currently active company's own total (see
    // floorInteractions.ts's applyPayoutCrit/totalIncome.ts's
    // getAllCompaniesUpgradesValue) — rare, since a multi-company save could
    // make this enormous
    payoutChance: 0.005,
    shareholdersChance: 0.02,
    ballerinaChance: 0.06,
    ballerinaUpgrades: 3,
    ballerinaPayouts: 3,
    cowboyChance: 0.035,
    cowboyUpgrades: 8,
    dinnerTimeChance: 0.04,
    dinnerTimePayouts: 5,
    fingerGunsChance: 0.07,
    fingerGunsUpgrades: 2,
    flamencoChance: 0.035,
    flamencoUpgrades: 7,
    milestoneChance: 0.025,
    milestoneStep: 25,
    moonwalkerChance: 0.04,
    moonwalkerUpgrades: 6,
    ninjaChance: 0.025,
    ninjaUpgrades: 12,
    obeliskChance: 0.008,
    obeliskTierSteps: 2,
    obeliskUpgrades: 2,
    sharpShooterChance: 0.04,
    sharpShooterPayouts: 10,
    spaceChance: 0.02,
    spaceUpgrades: 20,
    yesChefChance: 0.025,
    yesChefPayouts: 8,
    goldNuggetChance: 0.07,
    goldNuggetPayouts: 4,
    amethystChance: 0.05,
    amethystPayouts: 6,
    emeraldChance: 0.04,
    emeraldPayouts: 9,
    rubyChance: 0.03,
    rubyPayouts: 12,
    saphireChance: 0.025,
    saphirePayouts: 18,
    diamondChance: 0.02,
    diamondPayouts: 24,
    silverRushChance: 0.035,
    silverRushPayouts: 6,
    goldRushChance: 0.02,
    goldRushPayouts: 10,
    blessedChance: 0.01,
    blessedTierSteps: 1,
    blessedUpgrades: 3,
    wizardChance: 0.006,
    wizardTierSteps: 2,
    wizardUpgrades: 5,
    centurionChance: 0.01,
    centurionUpgrades: 100,
    checkUpChance: 0.05,
    checkUpUpgrades: 4,
    checkUpPayouts: 2,
    firemanChance: 0.04,
    firemanUpgrades: 3,
    firemanPayouts: 1,
    forTheKingChance: 0.02,
    forTheKingUpgrades: 15,
    forTheEmperorChance: 0.015,
    forTheEmperorUpgrades: 25,
    hammerTimeChance: 0.04,
    hammerTimeUpgrades: 9,
    robinHoodChance: 0.03,
    robinHoodPayouts: 7,
    robinHoodUpgrades: 3,
    romanChance: 0.03,
    romanUpgrades: 9,
    samuraiChance: 0.015,
    samuraiUpgrades: 30,
    spyChance: 0.022,
    spyUpgrades: 17,
    theLawWonChance: 0.045,
    theLawWonUpgrades: 6,
    theLawWonPayouts: 2,
    victorianChance: 0.03,
    victorianPayouts: 9,
    executiveSpinChance: 0.05,
    executiveSpinUpgrades: 4,
    rubberStampedeChance: 0.025,
    rubberStampedePayouts: 7,
    replyAllChance: 0.06,
    replyAllPayouts: 3,
    stapleOfSuccessChance: 0.04,
    stapleOfSuccessUpgrades: 7,
    faxOfFortuneChance: 0.035,
    faxOfFortunePayouts: 8,
    casualMondayChance: 0.025,
    casualMondayUpgrades: 20,
    deskJockeyChance: 0.05,
    deskJockeyUpgrades: 6,
    inboxZeroGravityChance: 0.03,
    inboxZeroGravityPayouts: 12,
    beanCounterChance: 0.01,
    beanCounterTierSteps: 1,
    beanCounterUpgrades: 6,
    kingOfTheWorldChance: 0.015,
    kingOfTheWorldUpgrades: 30,
    officeClownChance: 0.04,
    officeClownUpgrades: 5,
    fridayTieDayChance: 0.03,
    fridayTieDayPayouts: 10,
    soReadyChance: 0.02,
    soReadyUpgrades: 15,
    doughDivisionChance: 0.06,
    doughDivisionUpgrades: 6,
    profitPopcornChance: 0.04,
    profitPopcornPayouts: 4,
    donutDisturbChance: 0.05,
    donutDisturbUpgrades: 5,
    donutDisturbPayouts: 5,
    cakeDayChance: 0.03,
    cakeDayUpgrades: 12,
    champagneProblemsChance: 0.02,
    champagneProblemsPayouts: 15,
    bonusBurritoChance: 0.04,
    bonusBurritoUpgrades: 8,
    bonusBurritoPayouts: 3,
    sundaeBestChance: 0.025,
    sundaeBestPayouts: 10,
    popTheQuestionChance: 0.01,
    popTheQuestionTierSteps: 1,
    popTheQuestionUpgrades: 4,
    partyCrasherChance: 0.05,
    partyCrasherUpgrades: 3,
    epicChance: 0.012,
    epicUpgrades: 40,
    readyChance: 0.03,
    readyUpgrades: 4,
    readyPayouts: 4,
    workWorkChance: 0.028,
    workWorkUpgrades: 11,
    yesWarchiefChance: 0.018,
    yesWarchiefPayouts: 14,
    youAreNotPreparedChance: 0.005,
    youAreNotPreparedTierSteps: 2,
    youAreNotPreparedUpgrades: 9,
    arcanaChance: 0.009,
    arcanaTierSteps: 1,
    arcanaUpgrades: 12,
    bigDaddyChance: 0.011,
    bigDaddyUpgrades: 45,
    chonkChance: 0.028,
    chonkPayouts: 16,
    cyberPunkChance: 0.024,
    cyberPunkUpgrades: 13,
    dodgeThisChance: 0.045,
    dodgeThisPayouts: 6,
    whiteRabbitChance: 0.035,
    whiteRabbitUpgrades: 5,
    gladiatorChance: 0.022,
    gladiatorUpgrades: 13,
    iDidntAskForThisChance: 0.007,
    iDidntAskForThisTierSteps: 1,
    iDidntAskForThisUpgrades: 20,
    iHatePortalsChance: 0.035,
    iHatePortalsPayouts: 11,
    littleSisterChance: 0.038,
    littleSisterUpgrades: 7,
    magicIsAToolChance: 0.018,
    magicIsAToolUpgrades: 8,
    megaChonkChance: 0.022,
    megaChonkPayouts: 22,
    metalChance: 0.024,
    metalUpgrades: 17,
    princessChance: 0.021,
    princessPayouts: 13,
    spaceAndTimeChance: 0.03,
    spaceAndTimeUpgrades: 9,
    thinkWithYourHeadChance: 0.04,
    thinkWithYourHeadUpgrades: 5,
    thinkWithYourHeadPayouts: 5,
    wouldYouKindlyChance: 0.015,
    wouldYouKindlyPayouts: 16,
    yesYourHighnessChance: 0.017,
    yesYourHighnessUpgrades: 19,
    bulletDodgerChance: 0.022,
    bulletDodgerUpgrades: 14,
    nothingToSeeChance: 0.024,
    nothingToSeePayouts: 20,
    nowIAmSuspiciousChance: 0.013,
    nowIAmSuspiciousPayouts: 17,
    redOrBlueChance: 0.03,
    redOrBlueUpgrades: 6,
    redOrBluePayouts: 6,
    abraCashDabraChance: 0.018,
    abraCashDabraPayouts: 25,
    captainOfIndustryChance: 0.016,
    captainOfIndustryUpgrades: 21,
    clowningAroundChance: 0.03,
    clowningAroundUpgrades: 3,
    clowningAroundPayouts: 3,
    discoDividendChance: 0.024,
    discoDividendPayouts: 11,
    mimeYourBusinessChance: 0.035,
    mimeYourBusinessUpgrades: 8,
    redCarpetTreatmentChance: 0.03,
    redCarpetTreatmentPayouts: 12,
    rockTheStockChance: 0.021,
    rockTheStockUpgrades: 16,
    strongReturnChance: 0.017,
    strongReturnUpgrades: 26,
    theBigCheeseChance: 0.004,
    theBigCheeseTierSteps: 2,
    theBigCheeseUpgrades: 30,
    queenOfQueensChance: 0.013,
    queenOfQueensUpgrades: 28,
    bubbleEconomyChance: 0.045,
    bubbleEconomyPayouts: 7,
    cloudNineToFiveChance: 0.022,
    cloudNineToFivePayouts: 9,
    luckyLaundromatChance: 0.02,
    luckyLaundromatUpgrades: 5,
    luckyLaundromatPayouts: 5,
    moneyMagnetChance: 0.025,
    moneyMagnetPayouts: 14,
    overTheRainbowChance: 0.018,
    overTheRainbowPayouts: 15,
    pocketDimensionChance: 0.02,
    pocketDimensionUpgrades: 18,
    shootingStarEmployeeChance: 0.019,
    shootingStarEmployeeUpgrades: 23,
    treasureMeasureChance: 0.032,
    treasureMeasureUpgrades: 10,
    wishfulBankingChance: 0.0045,
    wishfulBankingTierSteps: 2,
    wishfulBankingUpgrades: 12,
    backToTheFiscalChance: 0.026,
    backToTheFiscalUpgrades: 11,
    despicableFeesChance: 0.016,
    despicableFeesPayouts: 30,
    howToTrainYourManagerChance: 0.04,
    howToTrainYourManagerUpgrades: 4,
    howToTrainYourManagerPayouts: 6,
    jurassicPerkChance: 0.029,
    jurassicPerkPayouts: 13,
    raidersOfTheLostReceiptChance: 0.034,
    raidersOfTheLostReceiptUpgrades: 9,
    theDevilWearsPawdaChance: 0.028,
    theDevilWearsPawdaUpgrades: 14,
    theExpenseMatrixChance: 0.012,
    theExpenseMatrixPayouts: 18,
    theFastAndTheFurriestChance: 0.015,
    theFastAndTheFurriestUpgrades: 12,
    theFellowshipOfTheBlingChance: 0.016,
    theFellowshipOfTheBlingUpgrades: 6,
    theFellowshipOfTheBlingPayouts: 6,
    theGreatCatsbyChance: 0.0065,
    theGreatCatsbyTierSteps: 1,
    theGreatCatsbyUpgrades: 30,
    theLordOfTheRingBindersChance: 0.013,
    theLordOfTheRingBindersUpgrades: 35,
    breakEvenChance: 0.045,
    breakEvenUpgrades: 8,
    chaChaChingChance: 0.042,
    chaChaChingPayouts: 8,
    charlestonChargeChance: 0.031,
    charlestonChargeUpgrades: 11,
    congaCompoundingChance: 0.025,
    congaCompoundingUpgrades: 4,
    congaCompoundingPayouts: 4,
    robotResourcesChance: 0.022,
    robotResourcesUpgrades: 19,
    rumbaReturnsChance: 0.023,
    rumbaReturnsPayouts: 21,
    salsaSalaryChance: 0.027,
    salsaSalaryPayouts: 13,
    shuffleTheFundsChance: 0.025,
    shuffleTheFundsUpgrades: 14,
    tangoTenderChance: 0.028,
    tangoTenderUpgrades: 7,
    tapThatAssetChance: 0.016,
    tapThatAssetPayouts: 17,
    waltzStreetChance: 0.018,
    waltzStreetUpgrades: 17,
    prehistoricChance: 0.0055,
    prehistoricTierSteps: 1,
    prehistoricUpgrades: 40,
    breadyOrNotChance: 0.028,
    breadyOrNotUpgrades: 11,
    eggcellentWorkChance: 0.0095,
    eggcellentWorkTierSteps: 1,
    eggcellentWorkUpgrades: 8,
    holyGuacamoleChance: 0.011,
    holyGuacamolePayouts: 19,
    loafActuallyChance: 0.026,
    loafActuallyUpgrades: 12,
    pastaLaVistaChance: 0.017,
    pastaLaVistaPayouts: 16,
    souperStarChance: 0.019,
    souperStarPayouts: 16,
    tacoBoutItChance: 0.04,
    tacoBoutItUpgrades: 4,
    theGreatPancakeStackChance: 0.018,
    theGreatPancakeStackUpgrades: 21,
    wokAndRollChance: 0.018,
    wokAndRollUpgrades: 24,
    iAmTheNightChance: 0.014,
    iAmTheNightUpgrades: 27,
    tubsChance: 0.017,
    tubsPayouts: 26,
    whySoSeriousChance: 0.0035,
    whySoSeriousTierSteps: 2,
    whySoSeriousUpgrades: 20,
    avocardioChance: 0.035,
    avocardioUpgrades: 15,
    butterBelieveItChance: 0.024,
    butterBelieveItPayouts: 18,
    cheesePullChampionChance: 0.022,
    cheesePullChampionUpgrades: 6,
    cheesePullChampionPayouts: 6,
    grillSergeantChance: 0.013,
    grillSergeantUpgrades: 20,
    noodleNapChance: 0.015,
    noodleNapPayouts: 22,
    picklePredicamentChance: 0.032,
    picklePredicamentUpgrades: 8,
    golemChance: 0.0115,
    golemUpgrades: 35,
    hotPotatoChance: 0.034,
    hotPotatoPayouts: 18,
    brunchBossChance: 0.021,
    brunchBossUpgrades: 7,
    brunchBossPayouts: 7,
    curryFavourChance: 0.018,
    curryFavourPayouts: 14,
    dimSumDynastyChance: 0.016,
    dimSumDynastyUpgrades: 15,
    soupDumplingSurgeonChance: 0.012,
    soupDumplingSurgeonUpgrades: 5,
    soupDumplingSurgeonPayouts: 10,
    chocolateFountainOfYouthChance: 0.02,
    chocolateFountainOfYouthPayouts: 20,
    gummyBearMarketChance: 0.015,
    gummyBearMarketUpgrades: 10,
    jawbreakerChance: 0.028,
    jawbreakerUpgrades: 18,
    licoriceLacesChance: 0.024,
    licoriceLacesUpgrades: 9,
    lollipopGuildChance: 0.018,
    lollipopGuildPayouts: 12,
    marshmallowMountainChance: 0.026,
    marshmallowMountainUpgrades: 8,
    sugarHighChance: 0.012,
    sugarHighUpgrades: 5,
    sugarHighPayouts: 5,
    bubblegumBalloonChance: 0.03,
    bubblegumBalloonPayouts: 15,
    candyCaneClimberChance: 0.022,
    candyCaneClimberUpgrades: 12,
    sherbetSherpaChance: 0.016,
    sherbetSherpaPayouts: 8,
    toffeeTrapChance: 0.027,
    toffeeTrapUpgrades: 7,
    cottonCandyCloudChance: 0.024,
    cottonCandyCloudPayouts: 11,
    fudgeItChance: 0.021,
    fudgeItUpgrades: 14,
    gobstopperGetawayChance: 0.018,
    gobstopperGetawayUpgrades: 13,
    jellyBeanJamboreeChance: 0.026,
    jellyBeanJamboreePayouts: 10,
    rockCandyQuarryChance: 0.014,
    rockCandyQuarryTierSteps: 1,
    rockCandyQuarryUpgrades: 7,
    sprinkleStormChance: 0.03,
    sprinkleStormUpgrades: 6,
    dungeonAccountantChance: 0.028,
    dungeonAccountantUpgrades: 9,
    lootGoblinChance: 0.022,
    lootGoblinPayouts: 16,
    inventoryFullChance: 0.02,
    inventoryFullUpgrades: 12,
    sideQuestSalaryChance: 0.03,
    sideQuestSalaryPayouts: 7,
    minMaxManagerChance: 0.025,
    minMaxManagerUpgrades: 10,
    criticalKnitChance: 0.024,
    criticalKnitPayouts: 6,
    savePointSavingsChance: 0.012,
    savePointSavingsTierSteps: 1,
    savePointSavingsUpgrades: 5,
    achievementUnlockedChance: 0.009,
    achievementUnlockedTierSteps: 1,
    achievementUnlockedUpgrades: 8,
    newGamePlusChance: 0.018,
    newGamePlusUpgrades: 20,
    speedrunPayrollChance: 0.014,
    speedrunPayrollPayouts: 15,
    lagCompensationChance: 0.026,
    lagCompensationPayouts: 9,
    patchNotesPaydayChance: 0.021,
    patchNotesPaydayUpgrades: 11,
    biggerOnTheInsideChance: 0.018,
    biggerOnTheInsidePayouts: 10,
    cacheMeOutsideChance: 0.026,
    cacheMeOutsideUpgrades: 8,
    itCompilesChance: 0.024,
    itCompilesUpgrades: 15,
    magicalPayrollGirlChance: 0.011,
    magicalPayrollGirlTierSteps: 1,
    magicalPayrollGirlUpgrades: 10,
    mechaMiddleManagementChance: 0.016,
    mechaMiddleManagementUpgrades: 12,
    mergeConflictChance: 0.02,
    mergeConflictUpgrades: 7,
    mergeConflictPayouts: 7,
    mintConditionChance: 0.015,
    mintConditionPayouts: 18,
    stackOverflowingChance: 0.022,
    stackOverflowingUpgrades: 9,
    oneMoreRoundChance: 0.02,
    oneMoreRoundUpgrades: 8,
    oneMoreRoundPayouts: 8,
    couchCoOpCapitalChance: 0.017,
    couchCoOpCapitalUpgrades: 9,
    hardCarryChance: 0.019,
    hardCarryUpgrades: 14,
    readyCheckChance: 0.013,
    readyCheckUpgrades: 6,
    queueRoyaltyChance: 0.023,
    queueRoyaltyPayouts: 12,
    rankedAndBankedChance: 0.02,
    rankedAndBankedUpgrades: 11,
    victoryPoseChance: 0.016,
    victoryPoseUpgrades: 18,
    emoteEconomyChance: 0.027,
    emoteEconomyPayouts: 8,
    checkpointChampionChance: 0.015,
    checkpointChampionUpgrades: 10,
    fishingForFundsChance: 0.025,
    fishingForFundsPayouts: 13,
    purrfectOriginChance: 0.028,
    purrfectOriginUpgrades: 7,
    capeEscapeChance: 0.02,
    capeEscapePayouts: 10,
    thunderPawsChance: 0.018,
    thunderPawsUpgrades: 8,
    clawAndOrderChance: 0.024,
    clawAndOrderPayouts: 6,
    felineFuryChance: 0.015,
    felineFuryUpgrades: 16,
    sidekickShuffleChance: 0.021,
    sidekickShuffleUpgrades: 7,
    cosmicCatapultChance: 0.014,
    cosmicCatapultPayouts: 9,
    theMoonstoneKeyChance: 0.012,
    theMoonstoneKeyTierSteps: 1,
    theMoonstoneKeyUpgrades: 6,
    spellbookSupremeChance: 0.019,
    spellbookSupremeUpgrades: 12,
    prismPotionChance: 0.017,
    prismPotionPayouts: 14,
    galaxyGumballChance: 0.023,
    galaxyGumballPayouts: 11,
    treasureTruffleChance: 0.026,
    treasureTruffleUpgrades: 5,
    treasureTrufflePayouts: 5,
    wizardsWaffleChance: 0.016,
    wizardsWaffleUpgrades: 10,
    goldenFortuneCookieChance: 0.02,
    goldenFortuneCookieUpgrades: 9,
    crystalDragonEggChance: 0.014,
    crystalDragonEggUpgrades: 12,
    diamondCompassChance: 0.018,
    diamondCompassPayouts: 10,
    emeraldCrownChance: 0.012,
    emeraldCrownTierSteps: 1,
    emeraldCrownUpgrades: 8,
    goldenFleeceChance: 0.02,
    goldenFleecePayouts: 7,
    imperialScepterChance: 0.015,
    imperialScepterUpgrades: 13,
    rubyHeartRelicChance: 0.024,
    rubyHeartRelicPayouts: 12,
    sapphireHourglassChance: 0.017,
    sapphireHourglassPayouts: 9,
    vaultOfJewelsChance: 0.016,
    vaultOfJewelsUpgrades: 6,
    goldenIdolChance: 0.011,
    goldenIdolUpgrades: 15,
    emberwingDragonChance: 0.015,
    emberwingDragonUpgrades: 18,
    moonlitKirinChance: 0.013,
    moonlitKirinPayouts: 10,
    pocketPhoenixChance: 0.02,
    pocketPhoenixUpgrades: 7,
    crystalGriffinChance: 0.017,
    crystalGriffinPayouts: 8,
    velvetManticoreChance: 0.012,
    velvetManticoreTierSteps: 1,
    velvetManticoreUpgrades: 9,
    frostfangYetiChance: 0.022,
    frostfangYetiUpgrades: 11,
    lanternKitsuneChance: 0.019,
    lanternKitsunePayouts: 6,
    coralSeaSerpentChance: 0.016,
    coralSeaSerpentPayouts: 12,
    clockworkMinotaurChance: 0.018,
    clockworkMinotaurUpgrades: 13,
    starryCerberusChance: 0.014,
    starryCerberusUpgrades: 8,
    goldenSphinxChance: 0.011,
    goldenSphinxUpgrades: 10,
    mossbackTreantChance: 0.021,
    mossbackTreantUpgrades: 5,
    rainbowAlicornChance: 0.013,
    rainbowAlicornPayouts: 9,
    bogWitchFamiliarChance: 0.025,
    bogWitchFamiliarUpgrades: 6,
    pearlHippocampusChance: 0.018,
    pearlHippocampusPayouts: 7,
    thunderbirdChickChance: 0.016,
    thunderbirdChickUpgrades: 9,
    obsidianBasiliskChance: 0.01,
    obsidianBasiliskUpgrades: 20,
    cloudNymphChance: 0.023,
    cloudNymphPayouts: 5,
    alchemyAtDuskChance: 0.022,
    alchemyAtDuskUpgrades: 6,
    astropathAlleycatChance: 0.016,
    astropathAlleycatPayouts: 8,
    bardOfTheBrokenLyreChance: 0.025,
    bardOfTheBrokenLyrePayouts: 7,
    battleStandardBobcatChance: 0.014,
    battleStandardBobcatUpgrades: 10,
    cathedralStarshipChance: 0.012,
    cathedralStarshipPayouts: 12,
    cursedCrownHuntChance: 0.02,
    cursedCrownHuntUpgrades: 15,
    dreadnoughtWhiskerChance: 0.009,
    dreadnoughtWhiskerUpgrades: 20,
    elixirUnderMoonlightChance: 0.013,
    elixirUnderMoonlightTierSteps: 1,
    elixirUnderMoonlightUpgrades: 7,
    frostbiteTrackerChance: 0.021,
    frostbiteTrackerPayouts: 9,
    ironpawVanguardChance: 0.018,
    ironpawVanguardUpgrades: 11,
    lastStandLionheartChance: 0.015,
    lastStandLionheartUpgrades: 14,
    meowchineBerserkerChance: 0.017,
    meowchineBerserkerUpgrades: 8,
    meowtallicanGunnerChance: 0.023,
    meowtallicanGunnerPayouts: 10,
    midnightMonsterContractChance: 0.026,
    midnightMonsterContractUpgrades: 6,
    moonlitWyvernHuntChance: 0.014,
    moonlitWyvernHuntPayouts: 13,
    orbitalPounceChance: 0.019,
    orbitalPounceUpgrades: 5,
    plasmaPurrgeonChance: 0.02,
    plasmaPurrgeonUpgrades: 9,
    relicbladeRoninChance: 0.011,
    relicbladeRoninUpgrades: 16,
    seaMonsterSlayerChance: 0.013,
    seaMonsterSlayerPayouts: 10,
    silverclawSentinelChance: 0.024,
    silverclawSentinelUpgrades: 7,
    starBastionCaptainChance: 0.016,
    starBastionCaptainUpgrades: 12,
    tavernTacticianChance: 0.027,
    tavernTacticianPayouts: 8,
    theAntlerwoodStalkerChance: 0.012,
    theAntlerwoodStalkerTierSteps: 1,
    theAntlerwoodStalkerUpgrades: 5,
    theCataclysmicChaplainChance: 0.01,
    theCataclysmicChaplainUpgrades: 15,
    theGriffinContractChance: 0.018,
    theGriffinContractPayouts: 9,
    theSiegeScratcherChance: 0.014,
    theSiegeScratcherUpgrades: 18,
    theWarpwayWatcherChance: 0.022,
    theWarpwayWatcherPayouts: 6,
    theWhiteWhiskerChance: 0.013,
    theWhiteWhiskerUpgrades: 10,
    toxinclawInfiltratorChance: 0.025,
    toxinclawInfiltratorPayouts: 7,
    voidclawVeteranChance: 0.012,
    voidclawVeteranUpgrades: 13,
    voidshieldTemplarChance: 0.019,
    voidshieldTemplarUpgrades: 8,
    wolfmarkWandererChance: 0.021,
    wolfmarkWandererPayouts: 11,
    wolfpackFarewellChance: 0.017,
    wolfpackFarewellUpgrades: 6,
    bloodlineOmenChance: 0.012,
    bloodlineOmenUpgrades: 17,
    candleclawCatacombChance: 0.013,
    candleclawCatacombPayouts: 14,
    emberPawPatrolChance: 0.011,
    emberPawPatrolUpgrades: 14,
    whiskerCoastSurvivorChance: 0.012,
    whiskerCoastSurvivorPayouts: 17,
    astapurrionChance: 0.01,
    astapurrionPayouts: 19,
    astralclawSkybladeChance: 0.007,
    astralclawSkybladeUpgrades: 23,
    drizztDoPurrdenChance: 0.013,
    drizztDoPurrdenUpgrades: 9,
    elmiaowsterChance: 0.009,
    elmiaowsterTierSteps: 2,
    elmiaowsterUpgrades: 6,
    elvenSongbladeChance: 0.007,
    elvenSongbladePayouts: 20,
    galepawChance: 0.016,
    galepawPayouts: 11,
    halsinpawChance: 0.01,
    halsinpawUpgrades: 16,
    hearthpawShadowagentChance: 0.01,
    hearthpawShadowagentPayouts: 20,
    imeownChance: 0.024,
    imeownUpgrades: 13,
    jaheirballChance: 0.012,
    jaheirballPayouts: 14,
    karlachonkChance: 0.009,
    karlachonkUpgrades: 21,
    laezclawChance: 0.01,
    laezclawUpgrades: 19,
    minscAndMeowChance: 0.008,
    minscAndMeowUpgrades: 18,
    sarevmeowkChance: 0.015,
    sarevmeowkUpgrades: 15,
    shadowpurrChance: 0.011,
    shadowpurrTierSteps: 1,
    shadowpurrUpgrades: 11,
    theEmpurrorChance: 0.011,
    theEmpurrorPayouts: 13,
    thisIsTheEndChance: 0.008,
    thisIsTheEndUpgrades: 22,
    whiskerWyllChance: 0.011,
    whiskerWyllPayouts: 19,
    winkWinkChance: 0.022,
    winkWinkUpgrades: 14,
    adamWhiskersenChance: 0.007,
    adamWhiskersenTierSteps: 2,
    adamWhiskersenUpgrades: 8,
    bankrollChance: 0.006,
    bankrollUpgrades: 25,
    billBlizzardChance: 0.005,
    billBlizzardPayouts: 23,
    bobPawgeChance: 0.005,
    bobPawgeUpgrades: 24,
    bullionStackChance: 0.007,
    bullionStackUpgrades: 24,
    cashCannonChance: 0.013,
    cashCannonUpgrades: 10,
    fairExchangeChance: 0.011,
    fairExchangePayouts: 18,
    gemMineChance: 0.013,
    gemMineUpgrades: 10,
    goldMineChance: 0.012,
    goldMinePayouts: 15,
    goldenChaliceChance: 0.008,
    goldenChaliceTierSteps: 2,
    goldenChaliceUpgrades: 7,
    goldenGooseChance: 0.007,
    goldenGoosePayouts: 21,
    goldenStagChance: 0.008,
    goldenStagPayouts: 22,
    handsomeJakeChance: 0.012,
    handsomeJakeUpgrades: 18,
    jcDentclawChance: 0.005,
    jcDentclawUpgrades: 26,
    liquidAssetsChance: 0.009,
    liquidAssetsPayouts: 21,
    midasTouchChance: 0.009,
    midasTouchTierSteps: 1,
    midasTouchUpgrades: 13,
    moneyPrinterChance: 0.006,
    moneyPrinterUpgrades: 23,
    moneyTreeChance: 0.006,
    moneyTreePayouts: 22,
    nuggetAvalancheChance: 0.012,
    nuggetAvalanchePayouts: 17,
    pennyJarChance: 0.02,
    pennyJarUpgrades: 15,
    purrDentonChance: 0.019,
    purrDentonUpgrades: 17,
    strikeItRichChance: 0.014,
    strikeItRichUpgrades: 16,
    vaultDoorChance: 0.006,
    vaultDoorUpgrades: 22,
    wishingWellChance: 0.009,
    wishingWellPayouts: 23,
    youKnowWhatStallionChance: 0.012,
    youKnowWhatStallionUpgrades: 11,
    annaNyavarreChance: 0.008,
    annaNyavarrePayouts: 23,
    batteryCellChance: 0.019,
    batteryCellUpgrades: 16,
    blackBladeChance: 0.004,
    blackBladeUpgrades: 31,
    boneFluteChance: 0.009,
    boneFlutePayouts: 20,
    coldSteelChance: 0.004,
    coldSteelUpgrades: 33,
    commandoChance: 0.006,
    commandoUpgrades: 27,
    corvidCrownChance: 0.006,
    corvidCrownTierSteps: 2,
    corvidCrownUpgrades: 10,
    daedalynxChance: 0.005,
    daedalynxPayouts: 24,
    dataCubeChance: 0.012,
    dataCubeUpgrades: 12,
    dropTunedChance: 0.011,
    dropTunedUpgrades: 13,
    eternalFlameChance: 0.006,
    eternalFlamePayouts: 28,
    forgeAheadChance: 0.003,
    forgeAheadUpgrades: 30,
    guntherHairmanChance: 0.005,
    guntherHairmanUpgrades: 28,
    heliopawsChance: 0.004,
    heliopawsUpgrades: 26,
    hornsUpChance: 0.009,
    hornsUpUpgrades: 22,
    ironKeyChance: 0.017,
    ironKeyUpgrades: 19,
    lastCallChance: 0.006,
    lastCallPayouts: 29,
    nanoBladeChance: 0.005,
    nanoBladeUpgrades: 29,
    peltCloakChance: 0.01,
    peltCloakUpgrades: 14,
    pigIronChance: 0.003,
    pigIronUpgrades: 31,
    praxisKitChance: 0.008,
    praxisKitTierSteps: 1,
    praxisKitUpgrades: 14,
    quickSilverChance: 0.008,
    quickSilverPayouts: 21,
    runicAmuletChance: 0.006,
    runicAmuletTierSteps: 2,
    runicAmuletUpgrades: 11,
    scaledGripChance: 0.004,
    scaledGripUpgrades: 32,
    securityTurretChance: 0.01,
    securityTurretPayouts: 18,
    shoulderSpikesChance: 0.004,
    shoulderSpikesUpgrades: 29,
    shredMetalChance: 0.01,
    shredMetalUpgrades: 21,
    signetOfSkullsChance: 0.007,
    signetOfSkullsTierSteps: 1,
    signetOfSkullsUpgrades: 15,
    stormForkChance: 0.004,
    stormForkPayouts: 25,
    studdedBeltChance: 0.018,
    studdedBeltUpgrades: 18,
    swashbucklerChance: 0.01,
    swashbucklerPayouts: 19,
    temperedChance: 0.008,
    temperedUpgrades: 25,
    theCureChance: 0.007,
    theCurePayouts: 27,
    titaniumGripChance: 0.007,
    titaniumGripPayouts: 24,
    wardingSigilChance: 0.011,
    wardingSigilUpgrades: 13,
    blackHoleChance: 0.003,
    blackHolePayouts: 26,
    bottledNebulaChance: 0.006,
    bottledNebulaTierSteps: 1,
    bottledNebulaUpgrades: 16,
    eclipseChance: 0.007,
    eclipseUpgrades: 27,
    treasureMapChance: 0.007,
    treasureMapPayouts: 25,
    captainLeFluffChance: 0.006,
    captainLeFluffUpgrades: 28,
    // same downward cascade as bounce above, just a bigger step per floor, so
    // it has to be meaningfully rarer than bounceChance
    divingBellChance: 0.05,
    divingBellUpgrades: 2,
    flooringInspectorChance: 0.01,
    flooringInspectorUpgrades: 15,
    krakenChance: 0.003,
    krakenPayouts: 27,
    messageInABottleChance: 0.016,
    messageInABottleUpgrades: 20,
    ancientRelicChance: 0.014,
    ancientRelicPayouts: 35,
    geometricRelicChance: 0.015,
    geometricRelicPayouts: 34,
    berryParfaitChance: 0.002,
    berryParfaitPayouts: 32,
    berrySmoothieChance: 0.004,
    berrySmoothiePayouts: 32,
    butterCroissantChance: 0.002,
    butterCroissantUpgrades: 39,
    chromeArmChance: 0.002,
    chromeArmUpgrades: 37,
    circuitBreakerChance: 0.002,
    circuitBreakerUpgrades: 36,
    cheeseWheelChance: 0.003,
    cheeseWheelPayouts: 34,
    glassWyvernChance: 0.004,
    glassWyvernPayouts: 30,
    goldBarChance: 0.002,
    goldBarPayouts: 31,
    honeyToastChance: 0.013,
    honeyToastUpgrades: 23,
    potionCommotionChance: 0.004,
    potionCommotionPayouts: 30,
    lemonTartChance: 0.003,
    lemonTartUpgrades: 36,
    lifelineLootChance: 0.014,
    lifelineLootUpgrades: 22,
    moonCloakChance: 0.007,
    moonCloakUpgrades: 20,
    mossbackManticoreChance: 0.003,
    mossbackManticorePayouts: 30,
    platinumRingChance: 0.004,
    platinumRingUpgrades: 32,
    sapphireOrbitChance: 0.0045,
    sapphireOrbitTierSteps: 1,
    sapphireOrbitUpgrades: 20,
    roboticGripperChance: 0.002,
    roboticGripperUpgrades: 38,
    silverCoinChance: 0.006,
    silverCoinPayouts: 25,
    spicedChaiChance: 0.003,
    spicedChaiPayouts: 35,
    stormBootsChance: 0.006,
    stormBootsUpgrades: 18,
    sushiPlatterChance: 0.006,
    sushiPlatterPayouts: 26,
    thornmailGloveChance: 0.004,
    thornmailGloveTierSteps: 1,
    thornmailGloveUpgrades: 19,
    gildedCacheChance: 0.0025,
    gildedCacheUpgrades: 35,
    bullseyeChance: 0.015,
    bullseyeUpgrades: 21,
    chainReactionChance: 0.009,
    chainReactionUpgrades: 16,
    doubleHelixChance: 0.01,
    doubleHelixUpgrades: 15,
    eurekaChance: 0.005,
    eurekaTierSteps: 1,
    eurekaUpgrades: 18,
    goldMedalChance: 0.006,
    goldMedalPayouts: 31,
    halfLifeChance: 0.003,
    halfLifePayouts: 28,
    highRollerChance: 0.005,
    highRollerPayouts: 28,
    jackpotChance: 0.003,
    jackpotUpgrades: 32,
    knockoutChance: 0.004,
    knockoutUpgrades: 34,
    pearlDiverChance: 0.006,
    pearlDiverPayouts: 27,
    roundAndRoundChance: 0.008,
    roundAndRoundPayouts: 23,
    scratchCardChance: 0.006,
    scratchCardPayouts: 32,
    silverwareChance: 0.006,
    silverwareUpgrades: 29,
    snakeEyesChance: 0.009,
    snakeEyesPayouts: 20,
    twentyOneChance: 0.009,
    twentyOneUpgrades: 17,
    wheelOfFortuneChance: 0.005,
    wheelOfFortuneTierSteps: 2,
    wheelOfFortuneUpgrades: 13,
    aetherLanternChance: 0.008,
    aetherLanternUpgrades: 19,
    boilerRoomChance: 0.014,
    boilerRoomUpgrades: 22,
    brassDiverChance: 0.005,
    brassDiverPayouts: 33,
    clockworkHandChance: 0.009,
    clockworkHandUpgrades: 16,
    cogworkChance: 0.003,
    cogworkPayouts: 29,
    fullSteamChance: 0.003,
    fullSteamUpgrades: 33,
    pocketWatchChance: 0.005,
    pocketWatchPayouts: 29,
    tubeDeliveryChance: 0.005,
    tubeDeliveryUpgrades: 31,
    windUpChance: 0.0055,
    windUpTierSteps: 1,
    windUpUpgrades: 17,
    berryShortcakeChance: 0.0025,
    berryShortcakePayouts: 33,
    brassBankerChance: 0.002,
    brassBankerUpgrades: 34,
    candyCastleChance: 0.002,
    candyCastlePayouts: 36,
    caramelAppleChance: 0.004,
    caramelAppleUpgrades: 28,
    catnipSatchelChance: 0.005,
    catnipSatchelPayouts: 29,
    cinnamonSwirlChance: 0.004,
    cinnamonSwirlUpgrades: 26,
    citrusCoinChance: 0.004,
    citrusCoinPayouts: 33,
    clockworkSatelliteChance: 0.003,
    clockworkSatelliteUpgrades: 30,
    coinCascadeChance: 0.0015,
    coinCascadePayouts: 38,
    comfortFoodChance: 0.01,
    comfortFoodUpgrades: 24,
    crownHedgehogChance: 0.003,
    crownHedgehogTierSteps: 1,
    crownHedgehogUpgrades: 22,
    emberKeyChance: 0.0025,
    emberKeyUpgrades: 32,
    emberwingDragon2Chance: 0.003,
    emberwingDragon2Payouts: 30,
    emperorsFinestChance: 0.0015,
    emperorsFinestPayouts: 37,
    eternalDutyChance: 0.004,
    eternalDutyUpgrades: 27,
    faithIsOurShieldChance: 0.002,
    faithIsOurShieldTierSteps: 1,
    faithIsOurShieldUpgrades: 24,
    fearNotThePsykerChance: 0.0025,
    fearNotThePsykerPayouts: 34,
    frostRuneChance: 0.004,
    frostRuneUpgrades: 29,
    lanternFoxChance: 0.003,
    lanternFoxPayouts: 31,
    lanternLynxChance: 0.012,
    lanternLynxUpgrades: 23,
    memoryCrystalChance: 0.004,
    memoryCrystalTierSteps: 1,
    memoryCrystalUpgrades: 21,
    mochaFrothChance: 0.003,
    mochaFrothPayouts: 28,
    coinrootGroveChance: 0.005,
    coinrootGroveUpgrades: 20,
    neonBeakerChance: 0.003,
    neonBeakerPayouts: 32,
    neverSurrenderChance: 0.002,
    neverSurrenderUpgrades: 35,
    pearlOtterChance: 0.004,
    pearlOtterPayouts: 30,
    pickleParadeChance: 0.008,
    pickleParadeUpgrades: 25,
    profitPigeonChance: 0.005,
    profitPigeonPayouts: 27,
    purgeChance: 0.002,
    purgeUpgrades: 33,
    rainbowRelicChance: 0.003,
    rainbowRelicTierSteps: 1,
    rainbowRelicUpgrades: 23,
    ramenCrownChance: 0.002,
    ramenCrownPayouts: 35,
    redPandaChance: 0.003,
    redPandaUpgrades: 31,
    silverLaurelChance: 0.004,
    silverLaurelPayouts: 29,
    thunderNachosChance: 0.003,
    thunderNachosUpgrades: 28,
    toTheSkiesChance: 0.0015,
    toTheSkiesUpgrades: 36,
    treasureTeapotChance: 0.002,
    treasureTeapotPayouts: 34,
    whatAreYourOrdersChance: 0.004,
    whatAreYourOrdersUpgrades: 30,
    whisperingOrbChance: 0.002,
    whisperingOrbTierSteps: 1,
    whisperingOrbUpgrades: 25,
    clockworkOwlChance: 0.004,
    clockworkOwlUpgrades: 27,
    goldenGardenGolemChance: 0.002,
    goldenGardenGolemPayouts: 33,
    moonlitMintChance: 0.006,
    moonlitMintPayouts: 26,
    vaultBeetleChance: 0.002,
    vaultBeetleUpgrades: 34,
    lionKeyChance: 0.0015,
    lionKeyTierSteps: 1,
    lionKeyUpgrades: 26,
    restorationProjectChance: 0.0025,
    restorationProjectUpgrades: 30,
    arfthasChance: 0.004,
    arfthasUpgrades: 22,
    guldanMeowChance: 0.003,
    guldanMeowPayouts: 31,
    sargerasPurrgerasChance: 0.0003,
    sargerasPurrgerasUpgrades: 45,
    sylvanwhiskerChance: 0.0035,
    sylvanwhiskerPayouts: 28,
    sylvanasWhiskerunnerChance: 0.003,
    sylvanasWhiskerunnerPayouts: 30,
    jainaPurrmooreChance: 0.0045,
    jainaPurrmooreUpgrades: 24,
    thrallpawChance: 0.0015,
    thrallpawPayouts: 32,
    varianWrynnklesChance: 0.001,
    varianWrynnklesUpgrades: 38,
    anduinWrynncatChance: 0.003,
    anduinWrynncatPayouts: 30,
    illidandelightChance: 0.0008,
    illidandelightUpgrades: 42,
    malfurionStormpawChance: 0.001,
    malfurionStormpawPayouts: 35,
    voljinWhiskerChance: 0.004,
    voljinWhiskerUpgrades: 26,
    lorthemewPurronChance: 0.0035,
    lorthemewPurronPayouts: 29,
    khadgarPurrChance: 0.0008,
    khadgarPurrUpgrades: 33,
    garroshHellscreamPurrChance: 0.0005,
    garroshHellscreamPurrUpgrades: 48,
    grommewHellscreamChance: 0.0008,
    grommewHellscreamPayouts: 40,
    deathwingTheDestroycatChance: 0.0003,
    deathwingTheDestroycatUpgrades: 55,
    deathwingAshwingChance: 0.0005,
    deathwingAshwingUpgrades: 50,
    deathwingDestroypurrChance: 0.0002,
    deathwingDestroypurrUpgrades: 60,
    ragnapurrsChance: 0.0015,
    ragnapurrsPayouts: 37,
    medivhMewageChance: 0.004,
    medivhMewageUpgrades: 27,
    tyrandeWhiskerwindChance: 0.002,
    tyrandeWhiskerwindPayouts: 34,
    tyrandeMoonwhiskerChance: 0.0025,
    tyrandeMoonwhiskerPayouts: 32,
    tyrandeWhisperpawsChance: 0.0008,
    tyrandeWhisperpawsPayouts: 38,
    tyrandeStarbowChance: 0.0035,
    tyrandeStarbowUpgrades: 31,
    chenStormstoutChance: 0.0025,
    chenStormstoutUpgrades: 25,
    antleredFoxFortuneChance: 0.0025,
    antleredFoxFortuneUpgrades: 34,
    emperorProvidesPurrfectionChance: 0.0006,
    emperorProvidesPurrfectionPayouts: 44,
    furionStormpawChance: 0.0006,
    furionStormpawPayouts: 42,
    whatIsBrewingChance: 0.0035,
    whatIsBrewingPayouts: 16,
    goldLionChance: 0.005,
    goldLionPayouts: 27,
    goldElephantChance: 0.0045,
    goldElephantUpgrades: 28,
    goldBearChance: 0.0055,
    goldBearPayouts: 24,
    goldWolfChance: 0.006,
    goldWolfUpgrades: 22,
    goldOwlChance: 0.007,
    goldOwlPayouts: 20,
    goldRamChance: 0.0065,
    goldRamUpgrades: 18,
    goldRabbitChance: 0.01,
    goldRabbitPayouts: 13,
    goldCatChance: 0.008,
    goldCatUpgrades: 15,
    goldenLionChance: 0.0035,
    goldenLionUpgrades: 20,
    loadedBurgerChance: 0.004,
    loadedBurgerUpgrades: 24,
    tacoFeastChance: 0.005,
    tacoFeastPayouts: 22,
    pizzaSupremeChance: 0.0045,
    pizzaSupremeUpgrades: 26,
    sushiPlatter2Chance: 0.004,
    sushiPlatter2Payouts: 28,
    sushiPlatter3Chance: 0.0055,
    sushiPlatter3Upgrades: 23,
    sushiPlatter4Chance: 0.0035,
    sushiPlatter4Payouts: 30,
    ramenBowlChance: 0.004,
    ramenBowlUpgrades: 27,
    berrySmoothie2Chance: 0.005,
    berrySmoothie2Payouts: 29,
    berrySmoothie3Chance: 0.0045,
    berrySmoothie3Upgrades: 25,
    berrySmoothie4Chance: 0.003,
    berrySmoothie4Payouts: 31,
    icedCoffeeChance: 0.008,
    icedCoffeePayouts: 18,
    tropicalLemonadeChance: 0.006,
    tropicalLemonadeUpgrades: 20,
    tropicalLemonade2Chance: 0.005,
    tropicalLemonade2Payouts: 24,
    hotChocolateChance: 0.006,
    hotChocolateUpgrades: 19,
    hotChocolate2Chance: 0.005,
    hotChocolate2Payouts: 21,
    sunsetMargaritaChance: 0.004,
    sunsetMargaritaUpgrades: 17,
    blueLagoonCocktailChance: 0.0045,
    blueLagoonCocktailUpgrades: 22,
    blueLagoonCocktail2Chance: 0.005,
    blueLagoonCocktail2Payouts: 23,
    blueLagoonCocktail3Chance: 0.0035,
    blueLagoonCocktail3Upgrades: 25,
    strawberryDaiquiriChance: 0.004,
    strawberryDaiquiriPayouts: 27,
    mangoMojitoChance: 0.005,
    mangoMojitoUpgrades: 24,
    mangoMojito2Chance: 0.004,
    mangoMojito2Payouts: 26,
    espressoMartiniChance: 0.0025,
    espressoMartiniPayouts: 32,
    chocolateCakeChance: 0.003,
    chocolateCakeUpgrades: 30,
    strawberryShortcakeChance: 0.0035,
    strawberryShortcakePayouts: 28,
    rainbowDonutChance: 0.006,
    rainbowDonutUpgrades: 21,
    iceCreamSundaeChance: 0.002,
    iceCreamSundaePayouts: 34,
    iceCreamSundae2Chance: 0.003,
    iceCreamSundae2Upgrades: 29,
    macaronTowerChance: 0.0025,
    macaronTowerPayouts: 33,
    macaronTower2Chance: 0.003,
    macaronTower2Upgrades: 31,
    batmanChance: 0.0015,
    batmanUpgrades: 38,
    jokerChance: 0.002,
    jokerPayouts: 35,
    harleyQuinnChance: 0.0025,
    harleyQuinnUpgrades: 32,
    killerCrocChance: 0.001,
    killerCrocPayouts: 40,
    mrFreezeChance: 0.0015,
    mrFreezeUpgrades: 36,
    poisonIvyChance: 0.002,
    poisonIvyPayouts: 34,
    scarecrowChance: 0.0025,
    scarecrowUpgrades: 30,
    thePenguinChance: 0.003,
    thePenguinPayouts: 28,
    theRiddlerChance: 0.0025,
    theRiddlerUpgrades: 27,
    baneChance: 0.001,
    baneUpgrades: 42,
    harleyQuinn2Chance: 0.002,
    harleyQuinn2Payouts: 33,
    killerCroc2Chance: 0.0015,
    killerCroc2Upgrades: 39,
    poisonIvy2Chance: 0.0025,
    poisonIvy2Upgrades: 31,
    poisonIvy3Chance: 0.0015,
    poisonIvy3Payouts: 37,
    thePenguin2Chance: 0.0025,
    thePenguin2Upgrades: 29,
    bestestBoyChance: 0.0012,
    bestestBoyUpgrades: 41,
    doggoChance: 0.0012,
    doggoPayouts: 38,
    otterlyAdorableChance: 0.0018,
    otterlyAdorablePayouts: 35,
    appleChance: 0.005,
    applePayouts: 22,
    cupcakeChance: 0.004,
    cupcakeUpgrades: 26,
    potionChance: 0.0035,
    potionUpgrades: 24,
    donutChance: 0.003,
    donutPayouts: 30,
    clockworkWizard2Chance: 0.002,
    clockworkWizard2Upgrades: 34,
    metalHeartChance: 0.0018,
    metalHeartUpgrades: 36,
    metalHeart2Chance: 0.0014,
    metalHeart2Payouts: 41,
    clockworkWizardChance: 0.0012,
    clockworkWizardTierSteps: 1,
    clockworkWizardUpgrades: 12,
    bulwarkChance: 0.0009,
    bulwarkUpgrades: 43,
    fullPlateChance: 0.0025,
    fullPlateUpgrades: 33,
    overlordChance: 0.0008,
    overlordPayouts: 45,
    beerBellyChance: 0.006,
    beerBellyPayouts: 23,
    bottomsUpChance: 0.0045,
    bottomsUpUpgrades: 25,
    wineCountryChance: 0.0038,
    wineCountryPayouts: 27,
    ponyKegChance: 0.0032,
    ponyKegPayouts: 28,
    vodkaWhiskersChance: 0.0028,
    vodkaWhiskersUpgrades: 31,
    highRoller3Chance: 0.0026,
    highRoller3Payouts: 32,
    splitThePotChance: 0.0022,
    splitThePotUpgrades: 35,
    highRoller2Chance: 0.0016,
    highRoller2Upgrades: 37,
    pokerNightChance: 0.0011,
    pokerNightPayouts: 39,
    emptyGlassChance: 0.0075,
    emptyGlassPayouts: 19,
    amberSpritzChance: 0.007,
    amberSpritzPayouts: 20,
    copperMugMule2Chance: 0.0065,
    copperMugMule2Payouts: 21,
    negroniNightfall2Chance: 0.0055,
    negroniNightfall2Payouts: 24,
    blackberryBrambleChance: 0.0052,
    blackberryBrambleUpgrades: 22,
    blackberryBramble2Chance: 0.0048,
    blackberryBramble2Upgrades: 21,
    singaporeSlingChance: 0.0042,
    singaporeSlingPayouts: 25,
    derbyDayJulepChance: 0.0039,
    derbyDayJulepUpgrades: 27,
    derbyDayJulep2Chance: 0.0037,
    derbyDayJulep2Payouts: 26,
    hurricaneHourChance: 0.0036,
    hurricaneHourUpgrades: 28,
    cosmoCashoutChance: 0.0034,
    cosmoCashoutUpgrades: 29,
    frenchSeventyFiveChance: 0.0033,
    frenchSeventyFiveUpgrades: 26,
    sidecarSurgeChance: 0.0031,
    sidecarSurgeUpgrades: 27,
    allowanceChance: 0.003,
    allowancePayouts: 30,
    hurricaneHour2Chance: 0.0029,
    hurricaneHour2Payouts: 31,
    copperMugMuleChance: 0.0027,
    copperMugMuleUpgrades: 30,
    pineappleParadiseChance: 0.0026,
    pineappleParadiseUpgrades: 31,
    negroniNightfallChance: 0.0024,
    negroniNightfallUpgrades: 30,
    oldFashionedFortuneChance: 0.0023,
    oldFashionedFortunePayouts: 34,
    tikiZombieChance: 0.0021,
    tikiZombiePayouts: 33,
    tikiZombie2Chance: 0.0019,
    tikiZombie2Upgrades: 20,
    tikiZombie2Payouts: 20,
    allowance2Chance: 0.0018,
    allowance2Upgrades: 32,
    lootBagsChance: 0.0017,
    lootBagsUpgrades: 38,
    longIslandLandslideChance: 0.0015,
    longIslandLandslidePayouts: 36,
    pocketMoney2Chance: 0.0013,
    pocketMoney2Payouts: 37,
    liquidAssets2Chance: 0.0012,
    liquidAssets2Payouts: 44,
    pocketMoneyChance: 0.0011,
    pocketMoneyTierSteps: 1,
    pocketMoneyUpgrades: 15,
    fortyKOfGoldChance: 0.00095,
    fortyKOfGoldPayouts: 40,
    chaoticTemptationChance: 0.002,
    chaoticTemptationPayouts: 32,
    chaoticTemptation2Chance: 0.0018,
    chaoticTemptation2Upgrades: 34,
    chaoticTemptation3Chance: 0.0016,
    chaoticTemptation3Upgrades: 36,
    chaoticTemptation4Chance: 0.001,
    chaoticTemptation4Payouts: 42,
    emperorsDividendsChance: 0.0009,
    emperorsDividendsPayouts: 41,
    heavyHitterChance: 0.0007,
    heavyHitterUpgrades: 46,
    iAmSpeedChance: 0.0014,
    iAmSpeedUpgrades: 35,
    neverSurrender2Chance: 0.00075,
    neverSurrender2Upgrades: 43,
    plushieDogChance: 0.00105,
    plushieDogPayouts: 39,
    plushieElephantChance: 0.00085,
    plushieElephantUpgrades: 44,
    plushieHamsterChance: 0.0017,
    plushieHamsterPayouts: 36,
    plushieOtterChance: 0.0013,
    plushieOtterPayouts: 40,
    plushiePandChance: 0.00095,
    plushiePandPayouts: 38,
    plushiePenguinChance: 0.0015,
    plushiePenguinUpgrades: 37,
    plushieRabbitChance: 0.0012,
    plushieRabbitUpgrades: 35,
    plushieRacoonChance: 0.0009,
    plushieRacoonPayouts: 42,
    plushieSealChance: 0.0011,
    plushieSealUpgrades: 40,
    plushieTigerChance: 0.00065,
    plushieTigerUpgrades: 47,
    powerSwordChance: 0.0008,
    powerSwordTierSteps: 2,
    powerSwordUpgrades: 18,
    powerSword2Chance: 0.00055,
    powerSword2Upgrades: 48,
    sleepyFoxChance: 0.0019,
    sleepyFoxPayouts: 34,
    sleepyPandaChance: 0.001,
    sleepyPandaUpgrades: 43,
    alicornChance: 0.0012,
    alicornPayouts: 36,
    alicorn2Chance: 0.0008,
    alicorn2Upgrades: 41,
    crystallineDragonChance: 0.0006,
    crystallineDragonUpgrades: 47,
    dragonWithEggChance: 0.0007,
    dragonWithEggTierSteps: 2,
    dragonWithEggUpgrades: 20,
    griffinChance: 0.0009,
    griffinPayouts: 40,
    hippocampusChance: 0.0014,
    hippocampusPayouts: 38,
    hydraChance: 0.001,
    hydraUpgrades: 44,
    kirinChance: 0.0013,
    kirinUpgrades: 37,
    kitsuneChance: 0.0011,
    kitsunePayouts: 42,
    manticoreChance: 0.00075,
    manticoreUpgrades: 43,
    manticore2Chance: 0.00105,
    manticore2Payouts: 39,
    manticore3Chance: 0.00065,
    manticore3Upgrades: 46,
    pegasusChance: 0.0015,
    pegasusUpgrades: 35,
    phoneixChance: 0.00095,
    phoneixPayouts: 41,
    puppyPoseyChance: 0.00055,
    puppyPoseyUpgrades: 48,
    salamanderChance: 0.0018,
    salamanderPayouts: 34,
    salamander2Chance: 0.00085,
    salamander2Upgrades: 42,
    salamander3Chance: 0.0005,
    salamander3Payouts: 45,
    seaSerpetChance: 0.0016,
    seaSerpetUpgrades: 38,
    thunderbirdChance: 0.0008,
    thunderbirdPayouts: 44,
    treantChance: 0.0011,
    treantUpgrades: 40,
    unicornChance: 0.0017,
    unicornPayouts: 36,
    velvetManticore2Chance: 0.0007,
    velvetManticore2TierSteps: 2,
    velvetManticore2Upgrades: 22,
    velvetManticore3Chance: 0.00045,
    velvetManticore3Upgrades: 49,
    almondEncoreChance: 0.0017,
    almondEncorePayouts: 36,
    babkaRhapsodyChance: 0.0012,
    babkaRhapsodyUpgrades: 40,
    bagelBoulevardChance: 0.0011,
    bagelBoulevardPayouts: 38,
    baguetteBatonChance: 0.0012,
    baguetteBatonUpgrades: 39,
    briocheBonanzaChance: 0.0009,
    briocheBonanzaUpgrades: 44,
    breadWinnerChance: 0.0009,
    breadWinnerUpgrades: 22,
    breadWinnerPayouts: 20,
    challahCharmChance: 0.001,
    challahCharmTierSteps: 1,
    challahCharmUpgrades: 22,
    chouxBusinessChance: 0.0014,
    chouxBusinessUpgrades: 20,
    chouxBusinessPayouts: 18,
    cinnamonSpinChance: 0.0013,
    cinnamonSpinUpgrades: 30,
    icingOnTheBunChance: 0.0014,
    icingOnTheBunPayouts: 37,
    cruffinSummitChance: 0.0008,
    cruffinSummitUpgrades: 46,
    custardCrownChance: 0.0006,
    custardCrownTierSteps: 2,
    custardCrownUpgrades: 20,
    danishDaydreamChance: 0.001,
    danishDaydreamPayouts: 43,
    eclairFlairChance: 0.0007,
    eclairFlairUpgrades: 47,
    focacciaFiestaChance: 0.0007,
    focacciaFiestaUpgrades: 42,
    jamSessionChance: 0.0013,
    jamSessionPayouts: 35,
    sconeWithTheWindChance: 0.0012,
    sconeWithTheWindUpgrades: 40,
    knotYourAverageChance: 0.0009,
    knotYourAverageUpgrades: 38,
    naanStopChance: 0.0007,
    naanStopPayouts: 44,
    palmierParadeChance: 0.001,
    palmierParadeUpgrades: 45,
    pistachioPalaceChance: 0.0006,
    pistachioPalaceUpgrades: 48,
    pitaPocketPaydayChance: 0.0008,
    pitaPocketPaydayPayouts: 46,
    ryeOnThePrizeChance: 0.0012,
    ryeOnThePrizePayouts: 39,
    shokupanCloudChance: 0.0012,
    shokupanCloudUpgrades: 38,
    sourdoughSunriseChance: 0.0013,
    sourdoughSunrisePayouts: 40,
    strudelCuddleChance: 0.0012,
    strudelCuddleUpgrades: 24,
    strudelCuddlePayouts: 16,
    appleOfMyEyeChance: 0.001,
    appleOfMyEyePayouts: 43,
    turnoverTreasureChance: 0.0006,
    turnoverTreasurePayouts: 49,
    androidAnalystChance: 0.0009,
    androidAnalystUpgrades: 23,
    androidAnalystPayouts: 24,
    cocoaCloutChance: 0.0012,
    cocoaCloutUpgrades: 22,
    cocoaCloutPayouts: 20,
    shadesOfCocoaChance: 0.0009,
    shadesOfCocoaPayouts: 43,
    bigMugEnergyChance: 0.0007,
    bigMugEnergyUpgrades: 36,
    bonbonBigwigChance: 0.0008,
    bonbonBigwigTierSteps: 1,
    bonbonBigwigUpgrades: 31,
    ganacheGainsChance: 0.001,
    ganacheGainsUpgrades: 39,
    hazelnutHedgeFundChance: 0.0012,
    hazelnutHedgeFundUpgrades: 34,
    spreadTheWealthChance: 0.0007,
    spreadTheWealthPayouts: 45,
    chocolateBarExamChance: 0.001,
    chocolateBarExamUpgrades: 42,
    darkChocolateDealChance: 0.0009,
    darkChocolateDealUpgrades: 44,
    mousseMoxieChance: 0.0008,
    mousseMoxieUpgrades: 47,
    rockyRoadRallyChance: 0.0009,
    rockyRoadRallyUpgrades: 46,
    browniePointsChance: 0.0011,
    browniePointsUpgrades: 25,
    browniePointsPayouts: 15,
    torteReformChance: 0.001,
    torteReformUpgrades: 43,
    justDessertsChance: 0.0008,
    justDessertsUpgrades: 26,
    justDessertsPayouts: 22,
    sweetVerdictChance: 0.001,
    sweetVerdictPayouts: 44,
    operaCakeOvertureChance: 0.00045,
    operaCakeOvertureTierSteps: 2,
    operaCakeOvertureUpgrades: 26,
    sacherStockpileChance: 0.0008,
    sacherStockpilePayouts: 47,
    tripleLayerTreasuryChance: 0.00065,
    tripleLayerTreasuryUpgrades: 38,
    layeredSecurityChance: 0.001,
    layeredSecurityUpgrades: 25,
    layeredSecurityPayouts: 23,
    mississippiMudMillionaireChance: 0.0007,
    mississippiMudMillionairePayouts: 46,
    swissRollRolloverChance: 0.0011,
    swissRollRolloverPayouts: 41,
    chocolateDripDynamoChance: 0.0009,
    chocolateDripDynamoPayouts: 45,
    marbleCakeMarginChance: 0.0011,
    marbleCakeMarginUpgrades: 40,
    souffleSurplusChance: 0.0009,
    souffleSurplusUpgrades: 41,
    onTheRiseChance: 0.0007,
    onTheRiseUpgrades: 49,
    blackForestFortuneChance: 0.0011,
    blackForestFortuneUpgrades: 18,
    blackForestFortunePayouts: 24,
    redVelvetRopeChance: 0.0008,
    redVelvetRopeTierSteps: 1,
    redVelvetRopeUpgrades: 29,
    tiramisuTycoonChance: 0.0008,
    tiramisuTycoonUpgrades: 24,
    tiramisuTycoonPayouts: 21,
    cheesecakeChairmanChance: 0.0006,
    cheesecakeChairmanUpgrades: 50,
    carrotCakeCapitalChance: 0.0011,
    carrotCakeCapitalUpgrades: 23,
    carrotCakeCapitalPayouts: 17,
    angelFoodAscensionChance: 0.0005,
    angelFoodAscensionTierSteps: 2,
    angelFoodAscensionUpgrades: 24,
    poundCakeProfitsChance: 0.0013,
    poundCakeProfitsPayouts: 41,
    bundtFundChance: 0.0012,
    bundtFundPayouts: 39,
    lavaCakeLiquidityChance: 0.0009,
    lavaCakeLiquidityPayouts: 44,
    upsideDownUpswingChance: 0.001,
    upsideDownUpswingUpgrades: 43,
    watermelonWindfallChance: 0.0008,
    watermelonWindfallUpgrades: 34,
    papayaPayrollChance: 0.0013,
    papayaPayrollPayouts: 34,
    kiwiKickbackChance: 0.0009,
    kiwiKickbackPayouts: 47,
    topBananaChance: 0.0011,
    topBananaPayouts: 40,
    cherryOnTopChance: 0.0011,
    cherryOnTopUpgrades: 41,
    peachPerfectChance: 0.001,
    peachPerfectTierSteps: 1,
    peachPerfectUpgrades: 27,
    plumJobChance: 0.0012,
    plumJobUpgrades: 21,
    plumJobPayouts: 19,
    dragonfruitDynastyChance: 0.0012,
    dragonfruitDynastyUpgrades: 37,
    grapeExpectationsChance: 0.0011,
    grapeExpectationsUpgrades: 38,
    pomegranatePortfolioChance: 0.0013,
    pomegranatePortfolioUpgrades: 32,
    gumdropGazillionaireChance: 0.0006,
    gumdropGazillionaireUpgrades: 41,
    candyCornCornucopiaChance: 0.0009,
    candyCornCornucopiaPayouts: 41,
    butterscotchBuyoutChance: 0.0011,
    butterscotchBuyoutUpgrades: 42,
    sourStrawSprintChance: 0.0012,
    sourStrawSprintUpgrades: 36,
    pralinePremiumChance: 0.0009,
    pralinePremiumTierSteps: 1,
    pralinePremiumUpgrades: 28,
    fizzyFortuneChance: 0.0008,
    fizzyFortunePayouts: 48,
    marzipanMogulChance: 0.0006,
    marzipanMogulPayouts: 50,
    gummyWormWealthChance: 0.0009,
    gummyWormWealthUpgrades: 44,
    chocolateCoinCartelChance: 0.0009,
    chocolateCoinCartelUpgrades: 19,
    chocolateCoinCartelPayouts: 25,
    honeycombHustleChance: 0.0013,
    honeycombHustleUpgrades: 36,
    aceUpTheSleeveChance: 0.0008,
    aceUpTheSleeveTierSteps: 1,
    aceUpTheSleeveUpgrades: 33,
    baccaratBaronChance: 0.0009,
    baccaratBaronPayouts: 49,
    betTheFarmChance: 0.0007,
    betTheFarmUpgrades: 39,
    cardSharkChance: 0.0011,
    cardSharkUpgrades: 24,
    cardSharkPayouts: 26,
    casinoWhaleChance: 0.0007,
    casinoWhaleTierSteps: 1,
    casinoWhaleUpgrades: 30,
    croupierSweepChance: 0.001,
    croupierSweepUpgrades: 43,
    dealersChoiceChance: 0.001,
    dealersChoiceUpgrades: 45,
    feedTheKittyChance: 0.0009,
    feedTheKittyUpgrades: 49,
    bowlOfBetsChance: 0.001,
    bowlOfBetsPayouts: 52,
    peekabooPotChance: 0.0011,
    peekabooPotUpgrades: 37,
    headsOrTailsChance: 0.001,
    headsOrTailsPayouts: 47,
    highSteaksChance: 0.0009,
    highSteaksUpgrades: 51,
    lottoLlamaChance: 0.0009,
    lottoLlamaPayouts: 53,
    mahjongMaestroChance: 0.0006,
    mahjongMaestroTierSteps: 2,
    mahjongMaestroUpgrades: 21,
    neonStripChance: 0.0009,
    neonStripUpgrades: 48,
    oneArmedBanditChance: 0.001,
    oneArmedBanditUpgrades: 29,
    oneArmedBanditPayouts: 31,
    slotStickupChance: 0.0012,
    slotStickupPayouts: 55,
    pachinkoPlungeChance: 0.0009,
    pachinkoPlungePayouts: 44,
    photoFinishChance: 0.0011,
    photoFinishUpgrades: 39,
    pitBossChance: 0.001,
    pitBossUpgrades: 53,
    casinoBouncerChance: 0.0012,
    casinoBouncerUpgrades: 54,
    clipboardKingpinChance: 0.0006,
    clipboardKingpinUpgrades: 18,
    clipboardKingpinPayouts: 16,
    earpieceEnforcerChance: 0.001,
    earpieceEnforcerUpgrades: 26,
    earpieceEnforcerPayouts: 30,
    pokerChipmunkChance: 0.0011,
    pokerChipmunkPayouts: 57,
    pokerFaceChance: 0.0009,
    pokerFaceUpgrades: 56,
    stoneColdBluffChance: 0.001,
    stoneColdBluffUpgrades: 25,
    stoneColdBluffPayouts: 27,
    deadpanDealChance: 0.0011,
    deadpanDealPayouts: 58,
    rouletteWhirlChance: 0.0007,
    rouletteWhirlPayouts: 43,
    showdownChance: 0.0011,
    showdownUpgrades: 32,
    highNoonHandChance: 0.001,
    highNoonHandPayouts: 36,
    sicBoShakerChance: 0.001,
    sicBoShakerUpgrades: 23,
    sicBoShakerPayouts: 28,
    theCatfatherChance: 0.0006,
    theCatfatherTierSteps: 2,
    theCatfatherUpgrades: 23,
    unrefusableOfferChance: 0.0009,
    unrefusableOfferPayouts: 62,
    briefcaseBonusChance: 0.0011,
    briefcaseBonusUpgrades: 32,
    briefcaseBonusPayouts: 34,
    violinCaseCaperChance: 0.0012,
    violinCaseCaperPayouts: 59,
    technicolorTakeChance: 0.0007,
    technicolorTakePayouts: 46,
    stringsAttachedChance: 0.001,
    stringsAttachedUpgrades: 52,
    fiddlesticksFundChance: 0.001,
    fiddlesticksFundPayouts: 53,
    fedoraFlexChance: 0.0012,
    fedoraFlexUpgrades: 61,
    brimTipperChance: 0.0009,
    brimTipperUpgrades: 60,
    greenbackFanChance: 0.001,
    greenbackFanUpgrades: 28,
    greenbackFanPayouts: 31,
    craftyConsigliereChance: 0.0011,
    craftyConsigliereUpgrades: 41,
    cappuccinoCapoChance: 0.001,
    cappuccinoCapoUpgrades: 47,
    demitasseDuesChance: 0.001,
    demitasseDuesPayouts: 49,
    latteLoyaltyChance: 0.0011,
    latteLoyaltyUpgrades: 55,
    takeTheCannoliChance: 0.0011,
    takeTheCannoliPayouts: 61,
    speakeasyStashChance: 0.001,
    speakeasyStashUpgrades: 57,
    passwordPleaseChance: 0.001,
    passwordPleasePayouts: 58,
    hiddenDoorHaulChance: 0.0011,
    hiddenDoorHaulUpgrades: 58,
    pinstripePensionChance: 0.0007,
    pinstripePensionUpgrades: 43,
    lipsSealedChance: 0.0012,
    lipsSealedPayouts: 63,
    protectionRacketChance: 0.001,
    protectionRacketUpgrades: 43,
    runningBoardRichesChance: 0.001,
    runningBoardRichesUpgrades: 53,
    sundaySauceSitdownChance: 0.0006,
    sundaySauceSitdownUpgrades: 20,
    sundaySauceSitdownPayouts: 19,
    kissTheRingChance: 0.0007,
    kissTheRingTierSteps: 1,
    kissTheRingUpgrades: 36,
    bootlegBarrelChance: 0.0012,
    bootlegBarrelPayouts: 64,
    wiseguySwaggerChance: 0.0011,
    wiseguySwaggerUpgrades: 38,
    dontWorryAboutItChance: 0.001,
    dontWorryAboutItUpgrades: 29,
    dontWorryAboutItPayouts: 33,
    mindYourOwnBusinessChance: 0.0009,
    mindYourOwnBusinessUpgrades: 26,
    mindYourOwnBusinessPayouts: 30,
    oyabunsBlessingChance: 0.0008,
    oyabunsBlessingTierSteps: 1,
    oyabunsBlessingUpgrades: 38,
    irezumiInkChance: 0.0012,
    irezumiInkUpgrades: 63,
    teboriTabbyChance: 0.0012,
    teboriTabbyPayouts: 61,
    indigoInkwellChance: 0.0011,
    indigoInkwellUpgrades: 33,
    indigoInkwellPayouts: 35,
    dragonBackpieceChance: 0.0006,
    dragonBackpieceTierSteps: 2,
    dragonBackpieceUpgrades: 20,
    dragonPearlPactChance: 0.0009,
    dragonPearlPactPayouts: 64,
    gingerDragonChance: 0.0009,
    gingerDragonUpgrades: 62,
    katanaCashflowChance: 0.001,
    katanaCashflowUpgrades: 50,
    samuraiSpillwayChance: 0.001,
    samuraiSpillwayPayouts: 51,
    goldenKoiClanChance: 0.001,
    goldenKoiClanUpgrades: 54,
    koiCoinWhirlpoolChance: 0.001,
    koiCoinWhirlpoolPayouts: 56,
    manekiMobsterChance: 0.0007,
    manekiMobsterPayouts: 48,
    hanafudaHeistChance: 0.0012,
    hanafudaHeistPayouts: 66,
    hannyaMuscleChance: 0.0012,
    hannyaMuscleUpgrades: 65,
    redMaskGuardChance: 0.001,
    redMaskGuardUpgrades: 59,
    maskedRetainerChance: 0.001,
    maskedRetainerPayouts: 60,
    blackSedanConvoyChance: 0.001,
    blackSedanConvoyUpgrades: 55,
    pompadourPosseChance: 0.0007,
    pompadourPosseUpgrades: 44,
    sakazukiOathChance: 0.001,
    sakazukiOathPayouts: 40,
    sakuraSwornChance: 0.0011,
    sakuraSwornUpgrades: 60,
    shogunShakedownChance: 0.001,
    shogunShakedownUpgrades: 30,
    shogunShakedownPayouts: 32,
    tanukiTreasurerChance: 0.0006,
    tanukiTreasurerUpgrades: 21,
    tanukiTreasurerPayouts: 20,
    demonGirlChance: 0.0011,
    demonGirlUpgrades: 34,
    demonGirlPayouts: 36,
    candyCometChance: 0.001,
    candyCometUpgrades: 57,
    chromeBearChance: 0.0012,
    chromeBearUpgrades: 67,
    chromeCatChance: 0.0012,
    chromeCatPayouts: 65,
    chromeOwlChance: 0.0009,
    chromeOwlPayouts: 66,
    chromeWolfChance: 0.0009,
    chromeWolfUpgrades: 64,
    sterlingSiestaChance: 0.0011,
    sterlingSiestaUpgrades: 62,
    chromeGirlChance: 0.001,
    chromeGirlUpgrades: 31,
    chromeGirlPayouts: 33,
    platinumPawChance: 0.0008,
    platinumPawTierSteps: 1,
    platinumPawUpgrades: 41,
    relicCompassChance: 0.001,
    relicCompassUpgrades: 61,
    capitalCarouselChance: 0.0007,
    capitalCarouselPayouts: 49,
    executiveEscalatorChance: 0.001,
    executiveEscalatorUpgrades: 52,
    fiscalFireworksChance: 0.0007,
    fiscalFireworksUpgrades: 45,
    gildedGongChance: 0.001,
    gildedGongPayouts: 57,
    overtimeOracleChance: 0.0012,
    overtimeOraclePayouts: 67,
    paperworkPaladinChance: 0.0011,
    paperworkPaladinUpgrades: 60,
    payrollPagodaChance: 0.001,
    payrollPagodaPayouts: 52,
    pensionPinataChance: 0.0011,
    pensionPinataPayouts: 63,
    profitPretzelChance: 0.0011,
    profitPretzelUpgrades: 44,
    receiptRocketChance: 0.001,
    receiptRocketPayouts: 62,
    rubberBandReserveChance: 0.0012,
    rubberBandReservePayouts: 66,
    sovereignSnowglobeChance: 0.0007,
    sovereignSnowglobeTierSteps: 1,
    sovereignSnowglobeUpgrades: 39,
    velvetLockboxChance: 0.001,
    velvetLockboxUpgrades: 58,
    hellfireHeartbreakerChance: 0.0008,
    hellfireHeartbreakerTierSteps: 1,
    hellfireHeartbreakerUpgrades: 42,
    spadeTailSassChance: 0.0012,
    spadeTailSassUpgrades: 68,
    sinfullySolventChance: 0.0009,
    sinfullySolventPayouts: 68,
    slyStackChance: 0.0012,
    slyStackPayouts: 66,
    lavenderLoungeChance: 0.0009,
    lavenderLoungeUpgrades: 66,
    pitchforkCharmerChance: 0.0011,
    pitchforkCharmerUpgrades: 35,
    pitchforkCharmerPayouts: 37,
    scarletSaunterChance: 0.001,
    scarletSaunterUpgrades: 54,
    forkFlourishChance: 0.001,
    forkFlourishPayouts: 53,
    brimstoneBelleChance: 0.0007,
    brimstoneBellePayouts: 50,
    flapperFlamesChance: 0.0007,
    flapperFlamesUpgrades: 46,
    sootAndSequinsChance: 0.001,
    sootAndSequinsUpgrades: 59,
    impeccableTasteChance: 0.001,
    impeccableTastePayouts: 58,
    heartsAflameChance: 0.0011,
    heartsAflameUpgrades: 63,
    finePrintFiendChance: 0.0011,
    finePrintFiendPayouts: 64,
    signedInScarletChance: 0.001,
    signedInScarletUpgrades: 62,
    termsAndTemptationsChance: 0.001,
    termsAndTemptationsPayouts: 63,
    hotTakeChance: 0.0011,
    hotTakeUpgrades: 61,
    coinFlambeChance: 0.0012,
    coinFlambePayouts: 67,
    rivetRebelChance: 0.001,
    rivetRebelUpgrades: 58,
    flickerGrinChance: 0.0012,
    flickerGrinPayouts: 68,
    smolderEyesChance: 0.001,
    smolderEyesUpgrades: 45,
    crimsonGlareChance: 0.001,
    crimsonGlarePayouts: 41,
    midnightSideEyeChance: 0.0011,
    midnightSideEyeUpgrades: 39,
    amberStareChance: 0.001,
    amberStareUpgrades: 32,
    amberStarePayouts: 34,
    pawsAndEffectChance: 0.0012,
    pawsAndEffectUpgrades: 69,
    catwalkQueenChance: 0.0006,
    catwalkQueenTierSteps: 2,
    catwalkQueenUpgrades: 25,
    runwayRoyaltyChance: 0.0009,
    runwayRoyaltyUpgrades: 67,
    blueHourStrutChance: 0.0009,
    blueHourStrutPayouts: 69,
    felineFineChance: 0.0011,
    felineFineUpgrades: 64,
    kittenHeelsChance: 0.001,
    kittenHeelsUpgrades: 63,
    catsPajamasChance: 0.0006,
    catsPajamasUpgrades: 22,
    catsPajamasPayouts: 21,
    bedtimeBonusChance: 0.0009,
    bedtimeBonusUpgrades: 27,
    bedtimeBonusPayouts: 31,
    purrsuasionChance: 0.0011,
    purrsuasionUpgrades: 45,
    coinBoopChance: 0.0012,
    coinBoopPayouts: 68,
    tailSwishChance: 0.001,
    tailSwishUpgrades: 55,
    heartOfChromeChance: 0.0008,
    heartOfChromeTierSteps: 1,
    heartOfChromeUpgrades: 43,
    heartDriveChance: 0.0012,
    heartDriveUpgrades: 70,
    chromeCrushChance: 0.001,
    chromeCrushUpgrades: 33,
    chromeCrushPayouts: 35,
    heartBeamChance: 0.0012,
    heartBeamPayouts: 69,
    puckerProtocolChance: 0.001,
    puckerProtocolPayouts: 44,
    alloyAngelChance: 0.0006,
    alloyAngelTierSteps: 2,
    alloyAngelUpgrades: 19,
    sereneSeraphChance: 0.0007,
    sereneSeraphPayouts: 51,
    wingedWealthChance: 0.0007,
    wingedWealthUpgrades: 47,
    cyberSirenChance: 0.0009,
    cyberSirenPayouts: 70,
    micDropMavenChance: 0.0009,
    micDropMavenUpgrades: 68,
    circuitSerenadeChance: 0.001,
    circuitSerenadeUpgrades: 60,
    chromeCroonerChance: 0.001,
    chromeCroonerPayouts: 59,
    sunkissedSignalChance: 0.0011,
    sunkissedSignalPayouts: 65,
    wiredWarbleChance: 0.0011,
    wiredWarbleUpgrades: 65,
    beltItOutChance: 0.001,
    beltItOutPayouts: 64,
    glossyGazeChance: 0.001,
    glossyGazeUpgrades: 64,
    goldenFrecklesChance: 0.0012,
    goldenFrecklesPayouts: 68,
    mirrorBobChance: 0.0011,
    mirrorBobUpgrades: 62,
    holoHeartChance: 0.001,
    holoHeartUpgrades: 59,
    pixelHeartChance: 0.0012,
    pixelHeartPayouts: 69,
    heartProjectionChance: 0.001,
    heartProjectionPayouts: 54,
    liquidMetalLashesChance: 0.001,
    liquidMetalLashesUpgrades: 46,
    dripAndDazzleChance: 0.001,
    dripAndDazzlePayouts: 42,
    silverPourChance: 0.001,
    silverPourUpgrades: 30,
    silverPourPayouts: 32,
    polishedPoutChance: 0.0011,
    polishedPoutUpgrades: 36,
    polishedPoutPayouts: 38,
    loweredLensesChance: 0.0011,
    loweredLensesUpgrades: 40,
    flameFlirtChance: 0.0011,
    flameFlirtPayouts: 74,
    tidalTeaseChance: 0.001,
    tidalTeasePayouts: 61,
    riptideRomanceChance: 0.0009,
    riptideRomanceUpgrades: 53,
    zephyrGlamourChance: 0.0007,
    zephyrGlamourPayouts: 52,
    galeGalaChance: 0.0007,
    galeGalaUpgrades: 48,
    crosswindCrushChance: 0.0009,
    crosswindCrushUpgrades: 48,
    windfallWaltzChance: 0.0011,
    windfallWaltzPayouts: 71,
    glacialGlamChance: 0.0011,
    glacialGlamUpgrades: 76,
    snowglobeWinkChance: 0.0011,
    snowglobeWinkPayouts: 73,
    iceboxIdolChance: 0.0011,
    iceboxIdolUpgrades: 66,
    joltValentineChance: 0.0008,
    joltValentineTierSteps: 1,
    joltValentineUpgrades: 47,
    sparkSweetheartChance: 0.001,
    sparkSweetheartPayouts: 74,
    voltageVowChance: 0.001,
    voltageVowUpgrades: 71,
    magmaMuseChance: 0.0009,
    magmaMuseUpgrades: 37,
    magmaMusePayouts: 39,
    moltenMogulChance: 0.0006,
    moltenMogulTierSteps: 2,
    moltenMogulUpgrades: 23,
    lavaLoungerChance: 0.001,
    lavaLoungerUpgrades: 41,
    lavaLoungerPayouts: 43,
    mossMaidenChance: 0.0011,
    mossMaidenUpgrades: 72,
    blossomBashfulChance: 0.0011,
    blossomBashfulPayouts: 71,
    bedrockBeautyChance: 0.0011,
    bedrockBeautyUpgrades: 69,
    basaltBombshellChance: 0.001,
    basaltBombshellUpgrades: 34,
    basaltBombshellPayouts: 36,
    nuggetKnockoutChance: 0.0008,
    nuggetKnockoutTierSteps: 1,
    nuggetKnockoutUpgrades: 51,
    duneDarlingChance: 0.0009,
    duneDarlingPayouts: 58,
    hourglassHeiressChance: 0.001,
    hourglassHeiressPayouts: 47,
    sandsOfFortuneChance: 0.0011,
    sandsOfFortuneUpgrades: 67,
    vaporVogueChance: 0.0011,
    vaporVoguePayouts: 72,
    teatimeTeaseChance: 0.001,
    teatimeTeaseUpgrades: 45,
    earlGreyGlamourChance: 0.001,
    earlGreyGlamourPayouts: 46,
    tempestTiaraChance: 0.001,
    tempestTiaraUpgrades: 63,
    starlightSwoonChance: 0.0006,
    starlightSwoonUpgrades: 21,
    starlightSwoonPayouts: 23,
    stardustSighChance: 0.0009,
    stardustSighUpgrades: 50,
    umbraEnchantressChance: 0.0008,
    umbraEnchantressTierSteps: 1,
    umbraEnchantressUpgrades: 54,
    nightfallNudgeChance: 0.0009,
    nightfallNudgeUpgrades: 49,
    hoodedHushChance: 0.0009,
    hoodedHushPayouts: 50,
    smokescreenSmirkChance: 0.001,
    smokescreenSmirkPayouts: 48,
    ringletRascalChance: 0.001,
    ringletRascalUpgrades: 44,
    ashenAllureChance: 0.001,
    ashenAllureUpgrades: 35,
    ashenAllurePayouts: 37,
    geodeCoquetteChance: 0.0006,
    geodeCoquetteTierSteps: 2,
    geodeCoquetteUpgrades: 17,
    amethystAllureChance: 0.001,
    amethystAllureUpgrades: 38,
    amethystAllurePayouts: 40,
    crystalCurtsyChance: 0.0008,
    crystalCurtsyUpgrades: 29,
    crystalCurtsyPayouts: 31,
    prismPinupChance: 0.0009,
    prismPinupUpgrades: 44,
    prismPinupPayouts: 42,
  },

  // src/floors/upgradeButton/index.ts — the purchasable "Sale" boost.
  sale: {
    durationMs: 15_000,
  },

  // src/renovation — bulk "Renovate floors" purchases replay one upgrade at a
  // time, so a huge balance's plan is capped per floor
  renovation: {
    maxUpgradesPerFloor: 100_000,
  },

  // src/floors/boostEvent — the rare "Boost" event button. A paid or crit
  // upgrade click arms it; clicking it freezes the screen, streams coins into
  // one random on-screen worker (or manager) below the top crit tier, and
  // promotes it one crit tier (x5 -> x25 -> x125, see CRIT_TIER_CONFIG): while
  // boosted it multiplies its floor's speed by that tier's multiplier.
  boostEvent: {
    chance: 0.005, // per qualifying upgrade click
    cooldownMs: 30_000, // minimum time between two procs
    durationMs: 3_000, // whole freeze; the worker's glow changes tier from the first coin landing until it ends
    // a perma-boosted manager's auto-boost lasts this many times longer
    managerBoostDurationMultiplier: 2,
  },

  // src/floors/upgradeButton/index.ts — the purchasable "Work overtime" boost.
  // Each free click during the event adds a tick (crit-scaled, see
  // CRIT_TIER_CONFIG) to the floor's own overtime gauge (incomePanel.ts).
  overtime: {
    tickGoal: 125, // base goal for a floor with no permanent crit tier yet
    // a floor's CURRENT permanent crit tier raises its own gauge's goal further
    // (multiplies the base tickGoal above) — a higher tier already earns more
    // per tick, so its own gauge should take proportionally longer to fill
    tickGoalMultiplierByTier: {
      crit: 2,
      mega: 4,
      ultra: 4,
    },
  },

  // src/hud/upgradeMenu/index.ts — per-floor worker/office-upgrade pricing.
  upgradeMenu: {
    workerBasePriceFloor1: 100,
    managerMinUpgradeCount: 50, // a floor must be upgraded this many times to hire a manager
  },

  // src/floors/incomePanel/index.ts's officeUpgradeSpeedMultiplier — each of
  // office chairs / office supplies / a manager doubles a floor's speed once
  // owned; all three stack multiplicatively (up to 8x total).
  officeUpgrades: {
    speedMultiplierPerUpgrade: 2,
  },

  // src/hud/corporationBoostMenu/economy.ts — corporation-wide modifiers.
  corporation: {
    // sqrt(log10(amount)) * this rate — the shared "$ amount -> a small,
    // steadily-growing global-boost %" conversion a company's own
    // size-based baseline contribution uses (see getCompanyBaseModifierPercent)
    baseModifierRate: 0.5,
  },
} as const;
