// event modules, part 8 of 9 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../events/metronomeEvent";
import "../events/powerGridEvent";
import "../events/bombBowlingEvent";
import "../events/showdownEvent";
import "../events/jumpRopeEvent";
import "../events/strongboxEvent";
import "../events/snowCannonEvent";
import "../events/hillClimbEvent";
import "../events/abacusEvent";
import "../events/coralEvent";
import "../events/chladniEvent";
import "../events/afterimageEvent";
import "../events/snowGlobeEvent";
import "../events/sundialEvent";
import "../events/riveterEvent";
import "../events/paddleBallEvent";
import "../events/geodeEvent";
import "../events/fogMachineEvent";
import "../events/chicaneEvent";
import "../events/epicyclesEvent";
import "../events/sieveEvent";
import "../events/partingEvent";
import "../events/buzzWireEvent";
import "../events/hiccupsEvent";
import "../events/cutTheRopeEvent";
import "../events/whisperingGalleryEvent";
import "../events/chunnelEvent";
import "../events/sneezeEvent";
import "../events/grandPrixEvent";
import "../events/pillowFightEvent";
import "../events/dotsAndBoxesEvent";
import "../events/holdingPatternEvent";
import "../events/tankerEvent";
import "../events/vaporCloudEvent";
import "../events/shieldBreakerEvent";
import "../events/bottleneckEvent";
import "../events/skylightEvent";
import "../events/delugeEvent";
import "../events/monacoEvent";
import "../events/glitterSpillEvent";
import "../events/rogueWaveEvent";
import "../events/thunderEggEvent";
import "../events/hologramEvent";
import "../events/leafFallEvent";
import "../events/threeBodyEvent";
import "../events/billowsEvent";
import "../events/moireEvent";
import "../events/polePositionEvent";
import "../events/countersinkEvent";
import "../events/busyBeaverEvent";
import "../events/pursuitEvent";
import "../events/fractalChargeEvent";
import "../events/snowplowEvent";
import "../events/franklinsKiteEvent";
import "../events/sokobanEvent";
import "../events/frackingEvent";
import "../events/chopperEvent";
import "../events/extinguisherEvent";
import "../events/goldenSpiralEvent";
import "../events/wildfireEvent";
import "../events/timeTrialEvent";
import "../events/dustBunniesEvent";
import "../events/magneticPendulumEvent";
import "../events/deCasteljauEvent";
import "../events/buffonsNeedleEvent";
import "../events/fuseMazeEvent";
import "../events/barBilliardsEvent";
import "../events/levyFlightEvent";
import "../events/brachistochroneEvent";
import "../events/ulamSpiralEvent";
import "../events/galtonBoardEvent";
import "../events/poohsticksEvent";
import "../events/fireForEffectEvent";
import "../events/eyewallEvent";
import "../events/josephusEvent";
import "../events/podiumEvent";
import "../events/robovacEvent";
import "../events/figureEightEvent";
import "../events/bonanzaEvent";
import "../events/piClacksEvent";
import "../events/incomingEvent";
import "../events/stringArtEvent";
import "../events/petanqueEvent";
import "../events/centipedeEvent";
import "../events/mandelbrotEvent";
import "../events/towerOfHanoiEvent";
import "../events/rockTheBoatEvent";
import "../events/windowWasherEvent";
import "../events/tandemDriftEvent";
import "../events/postHolesEvent";
import "../events/clackersEvent";
import "../events/shishiOdoshiEvent";
import "../events/isingModelEvent";
import "../events/faradayCageEvent";
import "../events/freeThrowsEvent";
import "../events/fissionEvent";
import "../events/hydraEvent";
import "../events/opticalTweezersEvent";
import "../events/travellingSalesmanEvent";
import "../events/spinCycleEvent";
import "../events/pilotHoleEvent";
import "../events/pitStopEvent";
import "../events/blackHoleMergerEvent";
import "../events/maxwellsDemonEvent";
import "../events/tidalTailsEvent";
import "../events/hypervelocityEvent";
import "../events/quasarEvent";
import "../events/volleyballEvent";
import "../events/smartRocketsEvent";
import "../events/bombMobileEvent";
import "../events/ringGalaxyEvent";
import "../events/gravitationalLensEvent";
import "../events/convectionEvent";
import "../events/paintballEvent";
import "../events/kirkwoodGapsEvent";
import "../events/periscopeEvent";
import "../events/waterSkiEvent";
import "../events/jaiAlaiEvent";
import "../events/polarRingEvent";
import "../events/kebabEvent";
import "../events/katamariEvent";
import "../events/harmonicsEvent";
import "../events/stairwellEvent";
import "../events/ironFilingsEvent";
import "../events/syncEvent";
import "../events/rocheLobeEvent";
import "../events/marblesEvent";
import "../events/bombShuffleboardEvent";
import "../events/barredSpiralEvent";
import "../events/bombGrapesEvent";
import "../events/flowFieldEvent";
import "../events/rallyJumpEvent";
import "../events/sweetheartEvent";
import "../events/mintEvent";
import "../events/catSketchEvent";
import "../events/stencilEvent";
import "../events/denoiseEvent";
import "../events/pincushionEvent";
import "../events/updraftEvent";
import "../events/plugholesEvent";

export { forceMetronomeEvent } from "../events/metronomeEvent";
export { forcePowerGridEvent } from "../events/powerGridEvent";
export { forceBombBowlingEvent } from "../events/bombBowlingEvent";
export { forceShowdownEvent } from "../events/showdownEvent";
export { forceJumpRopeEvent } from "../events/jumpRopeEvent";
export { forceStrongboxEvent } from "../events/strongboxEvent";
export { forceSnowCannonEvent } from "../events/snowCannonEvent";
export { forceHillClimbEvent } from "../events/hillClimbEvent";
export { forceAbacusEvent } from "../events/abacusEvent";
export { forceCoralEvent } from "../events/coralEvent";
export { forceChladniEvent } from "../events/chladniEvent";
export { forceAfterimageEvent } from "../events/afterimageEvent";
export { forceSnowGlobeEvent } from "../events/snowGlobeEvent";
export { forceSundialEvent } from "../events/sundialEvent";
export { forceRiveterEvent } from "../events/riveterEvent";
export { forcePaddleBallEvent } from "../events/paddleBallEvent";
export { forceGeodeEvent } from "../events/geodeEvent";
export { forceFogMachineEvent } from "../events/fogMachineEvent";
export { forceChicaneEvent } from "../events/chicaneEvent";
export { forceEpicyclesEvent } from "../events/epicyclesEvent";
export { forceSieveEvent } from "../events/sieveEvent";
export { forcePartingEvent } from "../events/partingEvent";
export { forceBuzzWireEvent } from "../events/buzzWireEvent";
export { forceHiccupsEvent } from "../events/hiccupsEvent";
export { forceCutTheRopeEvent } from "../events/cutTheRopeEvent";
export { forceWhisperingGalleryEvent } from "../events/whisperingGalleryEvent";
export { forceChunnelEvent } from "../events/chunnelEvent";
export { forceSneezeEvent } from "../events/sneezeEvent";
export { forceGrandPrixEvent } from "../events/grandPrixEvent";
export { forcePillowFightEvent } from "../events/pillowFightEvent";
export { forceDotsAndBoxesEvent } from "../events/dotsAndBoxesEvent";
export { forceHoldingPatternEvent } from "../events/holdingPatternEvent";
export { forceTankerEvent } from "../events/tankerEvent";
export { forceVaporCloudEvent } from "../events/vaporCloudEvent";
export { forceShieldBreakerEvent } from "../events/shieldBreakerEvent";
export { forceBottleneckEvent } from "../events/bottleneckEvent";
export { forceSkylightEvent } from "../events/skylightEvent";
export { forceDelugeEvent } from "../events/delugeEvent";
export { forceMonacoEvent } from "../events/monacoEvent";
export { forceGlitterSpillEvent } from "../events/glitterSpillEvent";
export { forceRogueWaveEvent } from "../events/rogueWaveEvent";
export { forceThunderEggEvent } from "../events/thunderEggEvent";
export { forceHologramEvent } from "../events/hologramEvent";
export { forceLeafFallEvent } from "../events/leafFallEvent";
export { forceThreeBodyEvent } from "../events/threeBodyEvent";
export { forceBillowsEvent } from "../events/billowsEvent";
export { forceMoireEvent } from "../events/moireEvent";
export { forcePolePositionEvent } from "../events/polePositionEvent";
export { forceCountersinkEvent } from "../events/countersinkEvent";
export { forceBusyBeaverEvent } from "../events/busyBeaverEvent";
export { forcePursuitEvent } from "../events/pursuitEvent";
export { forceFractalChargeEvent } from "../events/fractalChargeEvent";
export { forceSnowplowEvent } from "../events/snowplowEvent";
export { forceFranklinsKiteEvent } from "../events/franklinsKiteEvent";
export { forceSokobanEvent } from "../events/sokobanEvent";
export { forceFrackingEvent } from "../events/frackingEvent";
export { forceChopperEvent } from "../events/chopperEvent";
export { forceExtinguisherEvent } from "../events/extinguisherEvent";
export { forceGoldenSpiralEvent } from "../events/goldenSpiralEvent";
export { forceWildfireEvent } from "../events/wildfireEvent";
export { forceTimeTrialEvent } from "../events/timeTrialEvent";
export { forceDustBunniesEvent } from "../events/dustBunniesEvent";
export { forceMagneticPendulumEvent } from "../events/magneticPendulumEvent";
export { forceDeCasteljauEvent } from "../events/deCasteljauEvent";
export { forceBuffonsNeedleEvent } from "../events/buffonsNeedleEvent";
export { forceFuseMazeEvent } from "../events/fuseMazeEvent";
export { forceBarBilliardsEvent } from "../events/barBilliardsEvent";
export { forceLevyFlightEvent } from "../events/levyFlightEvent";
export { forceBrachistochroneEvent } from "../events/brachistochroneEvent";
export { forceUlamSpiralEvent } from "../events/ulamSpiralEvent";
export { forceGaltonBoardEvent } from "../events/galtonBoardEvent";
export { forcePoohsticksEvent } from "../events/poohsticksEvent";
export { forceFireForEffectEvent } from "../events/fireForEffectEvent";
export { forceEyewallEvent } from "../events/eyewallEvent";
export { forceJosephusEvent } from "../events/josephusEvent";
export { forcePodiumEvent } from "../events/podiumEvent";
export { forceRobovacEvent } from "../events/robovacEvent";
export { forceFigureEightEvent } from "../events/figureEightEvent";
export { forceBonanzaEvent } from "../events/bonanzaEvent";
export { forcePiClacksEvent } from "../events/piClacksEvent";
export { forceIncomingEvent } from "../events/incomingEvent";
export { forceStringArtEvent } from "../events/stringArtEvent";
export { forcePetanqueEvent } from "../events/petanqueEvent";
export { forceCentipedeEvent } from "../events/centipedeEvent";
export { forceMandelbrotEvent } from "../events/mandelbrotEvent";
export { forceTowerOfHanoiEvent } from "../events/towerOfHanoiEvent";
export { forceRockTheBoatEvent } from "../events/rockTheBoatEvent";
export { forceWindowWasherEvent } from "../events/windowWasherEvent";
export { forceTandemDriftEvent } from "../events/tandemDriftEvent";
export { forcePostHolesEvent } from "../events/postHolesEvent";
export { forceClackersEvent } from "../events/clackersEvent";
export { forceShishiOdoshiEvent } from "../events/shishiOdoshiEvent";
export { forceIsingModelEvent } from "../events/isingModelEvent";
export { forceFaradayCageEvent } from "../events/faradayCageEvent";
export { forceFreeThrowsEvent } from "../events/freeThrowsEvent";
export { forceFissionEvent } from "../events/fissionEvent";
export { forceHydraEvent } from "../events/hydraEvent";
export { forceOpticalTweezersEvent } from "../events/opticalTweezersEvent";
export { forceTravellingSalesmanEvent } from "../events/travellingSalesmanEvent";
export { forceSpinCycleEvent } from "../events/spinCycleEvent";
export { forcePilotHoleEvent } from "../events/pilotHoleEvent";
export { forcePitStopEvent } from "../events/pitStopEvent";
export { forceBlackHoleMergerEvent } from "../events/blackHoleMergerEvent";
export { forceMaxwellsDemonEvent } from "../events/maxwellsDemonEvent";
export { forceTidalTailsEvent } from "../events/tidalTailsEvent";
export { forceHypervelocityEvent } from "../events/hypervelocityEvent";
export { forceQuasarEvent } from "../events/quasarEvent";
export { forceVolleyballEvent } from "../events/volleyballEvent";
export { forceSmartRocketsEvent } from "../events/smartRocketsEvent";
export { forceBombMobileEvent } from "../events/bombMobileEvent";
export { forceRingGalaxyEvent } from "../events/ringGalaxyEvent";
export { forceGravitationalLensEvent } from "../events/gravitationalLensEvent";
export { forceConvectionEvent } from "../events/convectionEvent";
export { forcePaintballEvent } from "../events/paintballEvent";
export { forceKirkwoodGapsEvent } from "../events/kirkwoodGapsEvent";
export { forcePeriscopeEvent } from "../events/periscopeEvent";
export { forceWaterSkiEvent } from "../events/waterSkiEvent";
export { forceJaiAlaiEvent } from "../events/jaiAlaiEvent";
export { forcePolarRingEvent } from "../events/polarRingEvent";
export { forceKebabEvent } from "../events/kebabEvent";
export { forceKatamariEvent } from "../events/katamariEvent";
export { forceHarmonicsEvent } from "../events/harmonicsEvent";
export { forceStairwellEvent } from "../events/stairwellEvent";
export { forceIronFilingsEvent } from "../events/ironFilingsEvent";
export { forceSyncEvent } from "../events/syncEvent";
export { forceRocheLobeEvent } from "../events/rocheLobeEvent";
export { forceMarblesEvent } from "../events/marblesEvent";
export { forceBombShuffleboardEvent } from "../events/bombShuffleboardEvent";
export { forceBarredSpiralEvent } from "../events/barredSpiralEvent";
export { forceBombGrapesEvent } from "../events/bombGrapesEvent";
export { forceFlowFieldEvent } from "../events/flowFieldEvent";
export { forceRallyJumpEvent } from "../events/rallyJumpEvent";
export { forceSweetheartEvent } from "../events/sweetheartEvent";
export { forceMintEvent } from "../events/mintEvent";
export { forceCatSketchEvent } from "../events/catSketchEvent";
export { forceStencilEvent } from "../events/stencilEvent";
export { forceDenoiseEvent } from "../events/denoiseEvent";
export { forcePincushionEvent } from "../events/pincushionEvent";
export { forceUpdraftEvent } from "../events/updraftEvent";
export { forcePlugholesEvent } from "../events/plugholesEvent";
