// event modules, part 7 of 9 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../events/gearTrainEvent";
import "../events/upstrikeEvent";
import "../events/creepingBarrageEvent";
import "../events/ballisticPendulumEvent";
import "../events/ringTawEvent";
import "../events/rainyWindowEvent";
import "../events/inflateEvent";
import "../events/domeFountainsEvent";
import "../events/bellRingersEvent";
import "../events/wetDogEvent";
import "../events/towerCraneEvent";
import "../events/beadLightningEvent";
import "../events/rockslideEvent";
import "../events/tightGroupEvent";
import "../events/jacksEvent";
import "../events/reflectingPoolEvent";
import "../events/pinArtEvent";
import "../events/twinWhirlpoolsEvent";
import "../events/hatchlingsEvent";
import "../events/butterfingersEvent";
import "../events/lockPickEvent";
import "../events/blacksmithEvent";
import "../events/seismicChargesEvent";
import "../events/skipShotsEvent";
import "../events/jumpingBeansEvent";
import "../events/swissCheeseEvent";
import "../events/explodedViewEvent";
import "../events/riptideEvent";
import "../events/fencingEvent";
import "../events/waterTowerEvent";
import "../events/barberPoleEvent";
import "../events/ionCannonEvent";
import "../events/claymoreEvent";
import "../events/pepperboxEvent";
import "../events/squashEvent";
import "../events/verticalHoldEvent";
import "../events/halftoneEvent";
import "../events/blowholeEvent";
import "../events/lamplighterEvent";
import "../events/fireBrigadeEvent";
import "../events/spokesEvent";
import "../events/thunderRingEvent";
import "../events/bottleRocketEvent";
import "../events/skeetEvent";
import "../events/tennisEvent";
import "../events/interlaceEvent";
import "../events/mirrorMirrorEvent";
import "../events/cottonCandyEvent";
import "../events/pelotonEvent";
import "../events/drinkingBirdEvent";
import "../events/hairRaiserEvent";
import "../events/detonatorEvent";
import "../events/bulletRainEvent";
import "../events/bouncyCastleEvent";
import "../events/gameOfLifeEvent";
import "../events/labyrinthEvent";
import "../events/tidalBoreEvent";
import "../events/scrumEvent";
import "../events/goldRushEvent";
import "../events/suspensionBridgeEvent";
import "../events/redlineEvent";
import "../events/willowEvent";
import "../events/quickdrawEvent";
import "../events/galileanCannonEvent";
import "../events/chaosGameEvent";
import "../events/sandpileEvent";
import "../events/augerEvent";
import "../events/fountainShowEvent";
import "../events/spinningPlatesEvent";
import "../events/scoopsEvent";
import "../events/solarFurnaceEvent";
import "../events/lightningHandsEvent";
import "../events/ringOfFireEvent";
import "../events/bulletClashEvent";
import "../events/bouncePassEvent";
import "../events/oilStrikeEvent";
import "../events/harmonographEvent";
import "../events/quicksortEvent";
import "../events/capillaryEvent";
import "../events/battleTopsEvent";
import "../events/pneumaticTubesEvent";
import "../events/starPolygonEvent";
import "../events/voltSpiderEvent";
import "../events/orbitalDecayEvent";
import "../events/sprayAndPrayEvent";
import "../events/shuttleEvent";
import "../events/drillDuelEvent";
import "../events/rule30Event";
import "../events/calvingEvent";
import "../events/phoenixEvent";
import "../events/steamTrainEvent";
import "../events/lightSailEvent";
import "../events/inchwormEvent";
import "../events/criticalMassEvent";
import "../events/knifeThrowerEvent";
import "../events/compactorEvent";
import "../events/coreSampleEvent";
import "../events/foamPartyEvent";
import "../events/langtonsAntEvent";
import "../events/othelloEvent";
import "../events/gloopEvent";
import "../events/escapeVelocityEvent";
import "../events/sungrazerEvent";
import "../events/fractalTreeEvent";
import "../events/switchboardEvent";
import "../events/interferenceEvent";
import "../events/towerDefenseEvent";
import "../events/bounceWaveEvent";
import "../events/moleEvent";
import "../events/carWashEvent";
import "../events/dragonCurveEvent";
import "../events/lightsOutEvent";
import "../events/tumblerEvent";
import "../events/waggleDanceEvent";
import "../events/waterCycleEvent";
import "../events/foldingRuleEvent";
import "../events/arcSwarmEvent";
import "../events/lockstepEvent";
import "../events/hackySackEvent";
import "../events/woodwormEvent";
import "../events/graffitiEvent";
import "../events/voronoiEvent";
import "../events/percolationEvent";
import "../events/duneEvent";
import "../events/stringOfPearlsEvent";
import "../events/riverJugglerEvent";
import "../events/likeChargesEvent";
import "../events/collisionCourseEvent";
import "../events/targetWheelEvent";
import "../events/spinningHexagonEvent";
import "../events/beadDrillEvent";
import "../events/hydroseederEvent";
import "../events/mancalaEvent";
import "../events/archimedesScrewEvent";
import "../events/murmurationEvent";
import "../events/spiritBombEvent";
// the dev test bar's hooks
export { forceGearTrainEvent } from "../events/gearTrainEvent";
export { forceUpstrikeEvent } from "../events/upstrikeEvent";
export { forceCreepingBarrageEvent } from "../events/creepingBarrageEvent";
export { forceBallisticPendulumEvent } from "../events/ballisticPendulumEvent";
export { forceRingTawEvent } from "../events/ringTawEvent";
export { forceRainyWindowEvent } from "../events/rainyWindowEvent";
export { forceInflateEvent } from "../events/inflateEvent";
export { forceDomeFountainsEvent } from "../events/domeFountainsEvent";
export { forceBellRingersEvent } from "../events/bellRingersEvent";
export { forceWetDogEvent } from "../events/wetDogEvent";
export { forceTowerCraneEvent } from "../events/towerCraneEvent";
export { forceBeadLightningEvent } from "../events/beadLightningEvent";
export { forceRockslideEvent } from "../events/rockslideEvent";
export { forceTightGroupEvent } from "../events/tightGroupEvent";
export { forceJacksEvent } from "../events/jacksEvent";
export { forceReflectingPoolEvent } from "../events/reflectingPoolEvent";
export { forcePinArtEvent } from "../events/pinArtEvent";
export { forceTwinWhirlpoolsEvent } from "../events/twinWhirlpoolsEvent";
export { forceHatchlingsEvent } from "../events/hatchlingsEvent";
export { forceButterfingersEvent } from "../events/butterfingersEvent";
export { forceLockPickEvent } from "../events/lockPickEvent";
export { forceBlacksmithEvent } from "../events/blacksmithEvent";
export { forceSeismicChargesEvent } from "../events/seismicChargesEvent";
export { forceSkipShotsEvent } from "../events/skipShotsEvent";
export { forceJumpingBeansEvent } from "../events/jumpingBeansEvent";
export { forceSwissCheeseEvent } from "../events/swissCheeseEvent";
export { forceExplodedViewEvent } from "../events/explodedViewEvent";
export { forceRiptideEvent } from "../events/riptideEvent";
export { forceFencingEvent } from "../events/fencingEvent";
export { forceWaterTowerEvent } from "../events/waterTowerEvent";
export { forceBarberPoleEvent } from "../events/barberPoleEvent";
export { forceIonCannonEvent } from "../events/ionCannonEvent";
export { forceClaymoreEvent } from "../events/claymoreEvent";
export { forcePepperboxEvent } from "../events/pepperboxEvent";
export { forceSquashEvent } from "../events/squashEvent";
export { forceVerticalHoldEvent } from "../events/verticalHoldEvent";
export { forceHalftoneEvent } from "../events/halftoneEvent";
export { forceBlowholeEvent } from "../events/blowholeEvent";
export { forceLamplighterEvent } from "../events/lamplighterEvent";
export { forceFireBrigadeEvent } from "../events/fireBrigadeEvent";
export { forceSpokesEvent } from "../events/spokesEvent";
export { forceThunderRingEvent } from "../events/thunderRingEvent";
export { forceBottleRocketEvent } from "../events/bottleRocketEvent";
export { forceSkeetEvent } from "../events/skeetEvent";
export { forceTennisEvent } from "../events/tennisEvent";
export { forceInterlaceEvent } from "../events/interlaceEvent";
export { forceMirrorMirrorEvent } from "../events/mirrorMirrorEvent";
export { forceCottonCandyEvent } from "../events/cottonCandyEvent";
export { forcePelotonEvent } from "../events/pelotonEvent";
export { forceDrinkingBirdEvent } from "../events/drinkingBirdEvent";
export { forceHairRaiserEvent } from "../events/hairRaiserEvent";
export { forceDetonatorEvent } from "../events/detonatorEvent";
export { forceBulletRainEvent } from "../events/bulletRainEvent";
export { forceBouncyCastleEvent } from "../events/bouncyCastleEvent";
export { forceGameOfLifeEvent } from "../events/gameOfLifeEvent";
export { forceLabyrinthEvent } from "../events/labyrinthEvent";
export { forceTidalBoreEvent } from "../events/tidalBoreEvent";
export { forceScrumEvent } from "../events/scrumEvent";
export { forceGoldRushEvent } from "../events/goldRushEvent";
export { forceSuspensionBridgeEvent } from "../events/suspensionBridgeEvent";
export { forceRedlineEvent } from "../events/redlineEvent";
export { forceWillowEvent } from "../events/willowEvent";
export { forceQuickdrawEvent } from "../events/quickdrawEvent";
export { forceGalileanCannonEvent } from "../events/galileanCannonEvent";
export { forceChaosGameEvent } from "../events/chaosGameEvent";
export { forceSandpileEvent } from "../events/sandpileEvent";
export { forceAugerEvent } from "../events/augerEvent";
export { forceFountainShowEvent } from "../events/fountainShowEvent";
export { forceSpinningPlatesEvent } from "../events/spinningPlatesEvent";
export { forceScoopsEvent } from "../events/scoopsEvent";
export { forceSolarFurnaceEvent } from "../events/solarFurnaceEvent";
export { forceLightningHandsEvent } from "../events/lightningHandsEvent";
export { forceRingOfFireEvent } from "../events/ringOfFireEvent";
export { forceBulletClashEvent } from "../events/bulletClashEvent";
export { forceBouncePassEvent } from "../events/bouncePassEvent";
export { forceOilStrikeEvent } from "../events/oilStrikeEvent";
export { forceHarmonographEvent } from "../events/harmonographEvent";
export { forceQuicksortEvent } from "../events/quicksortEvent";
export { forceCapillaryEvent } from "../events/capillaryEvent";
export { forceBattleTopsEvent } from "../events/battleTopsEvent";
export { forcePneumaticTubesEvent } from "../events/pneumaticTubesEvent";
export { forceStarPolygonEvent } from "../events/starPolygonEvent";
export { forceVoltSpiderEvent } from "../events/voltSpiderEvent";
export { forceOrbitalDecayEvent } from "../events/orbitalDecayEvent";
export { forceSprayAndPrayEvent } from "../events/sprayAndPrayEvent";
export { forceShuttleEvent } from "../events/shuttleEvent";
export { forceDrillDuelEvent } from "../events/drillDuelEvent";
export { forceRule30Event } from "../events/rule30Event";
export { forceCalvingEvent } from "../events/calvingEvent";
export { forcePhoenixEvent } from "../events/phoenixEvent";
export { forceSteamTrainEvent } from "../events/steamTrainEvent";
export { forceLightSailEvent } from "../events/lightSailEvent";
export { forceInchwormEvent } from "../events/inchwormEvent";
export { forceCriticalMassEvent } from "../events/criticalMassEvent";
export { forceKnifeThrowerEvent } from "../events/knifeThrowerEvent";
export { forceCompactorEvent } from "../events/compactorEvent";
export { forceCoreSampleEvent } from "../events/coreSampleEvent";
export { forceFoamPartyEvent } from "../events/foamPartyEvent";
export { forceLangtonsAntEvent } from "../events/langtonsAntEvent";
export { forceOthelloEvent } from "../events/othelloEvent";
export { forceGloopEvent } from "../events/gloopEvent";
export { forceEscapeVelocityEvent } from "../events/escapeVelocityEvent";
export { forceSungrazerEvent } from "../events/sungrazerEvent";
export { forceFractalTreeEvent } from "../events/fractalTreeEvent";
export { forceSwitchboardEvent } from "../events/switchboardEvent";
export { forceInterferenceEvent } from "../events/interferenceEvent";
export { forceTowerDefenseEvent } from "../events/towerDefenseEvent";
export { forceBounceWaveEvent } from "../events/bounceWaveEvent";
export { forceMoleEvent } from "../events/moleEvent";
export { forceCarWashEvent } from "../events/carWashEvent";
export { forceDragonCurveEvent } from "../events/dragonCurveEvent";
export { forceLightsOutEvent } from "../events/lightsOutEvent";
export { forceTumblerEvent } from "../events/tumblerEvent";
export { forceWaggleDanceEvent } from "../events/waggleDanceEvent";
export { forceWaterCycleEvent } from "../events/waterCycleEvent";
export { forceFoldingRuleEvent } from "../events/foldingRuleEvent";
export { forceArcSwarmEvent } from "../events/arcSwarmEvent";
export { forceLockstepEvent } from "../events/lockstepEvent";
export { forceHackySackEvent } from "../events/hackySackEvent";
export { forceWoodwormEvent } from "../events/woodwormEvent";
export { forceGraffitiEvent } from "../events/graffitiEvent";
export { forceVoronoiEvent } from "../events/voronoiEvent";
export { forcePercolationEvent } from "../events/percolationEvent";
export { forceDuneEvent } from "../events/duneEvent";
export { forceStringOfPearlsEvent } from "../events/stringOfPearlsEvent";
export { forceRiverJugglerEvent } from "../events/riverJugglerEvent";
export { forceLikeChargesEvent } from "../events/likeChargesEvent";
export { forceCollisionCourseEvent } from "../events/collisionCourseEvent";
export { forceTargetWheelEvent } from "../events/targetWheelEvent";
export { forceSpinningHexagonEvent } from "../events/spinningHexagonEvent";
export { forceBeadDrillEvent } from "../events/beadDrillEvent";
export { forceHydroseederEvent } from "../events/hydroseederEvent";
export { forceMancalaEvent } from "../events/mancalaEvent";
export { forceArchimedesScrewEvent } from "../events/archimedesScrewEvent";
export { forceMurmurationEvent } from "../events/murmurationEvent";
export { forceSpiritBombEvent } from "../events/spiritBombEvent";
