// event modules, part 9 of 9 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../events/apollonianGasketEvent";
import "../events/droneShowEvent";
import "../events/marxGeneratorEvent";
import "../events/oortCloudEvent";
import "../events/doubleSlitEvent";
import "../events/blastSweepEvent";
import "../events/hydraulicJumpEvent";
import "../events/lightspeedEvent";
import "../events/starfighterEvent";
import "../events/freefallEvent";
import "../events/saloonEvent";
import "../events/doomEvent";
import "../events/roadRaceEvent";
import "../events/skyRaidEvent";
import "../events/lockOnVolleyEvent";
import "../events/rockFieldEvent";
import "../events/mineBeltEvent";
import "../events/ringRunEvent";
import "../events/convoyEvent";
import "../events/fireworksFlightEvent";
import "../events/stormFlightEvent";
import "../events/cometChaseEvent";
import "../events/galaxyFlightEvent";
import "../events/battlecruiserEvent";
import "../events/laserGauntletEvent";
import "../events/wormholeDiveEvent";
import "../events/doublingBounceEvent";
import "../events/airJuggleEvent";
import "../events/novaDiskEvent";
import "../events/blastCoatEvent";
import "../events/cashCoilEvent";
import "../events/threadingEvent";
import "../events/boltBindingEvent";
import "../events/fortressEvent";
import "../events/meteorSplitterEvent";
import "../events/thunderDuelEvent";
import "../events/forkStormEvent";
import "../events/ionHazeEvent";
import "../events/nebulaEvent";
import "../events/survivorsEvent";
import "../events/geometryRunEvent";
import "../events/dysonSphereEvent";
import "../events/seedPodsEvent";
import "../events/rippleFireEvent";
import "../events/sparkChamberEvent";
import "../events/turbineEvent";
import "../events/strangeAttractorEvent";
import "../events/topsyTurvyEvent";
import "../events/goldPlatingEvent";
import "../events/crosswindEvent";
import "../events/hailstoneEvent";
import "../events/hilbertCurveEvent";
import "../events/leMansEvent";
import "../events/tunnelBorerEvent";
import "../events/harpoonEvent";
import "../events/eightQueensEvent";
import "../events/shortestPathEvent";
import "../events/sinkholeEvent";
import "../events/backwashEvent";
import "../events/deflectorEvent";
import "../events/sunflowerEvent";
import "../events/convexHullEvent";
import "../events/slashEvent";
import "../events/jackhammerEvent";
import "../events/pummelEvent";
import "../events/overloadEvent";
import "../events/pressEvent";
import "../events/burrowEvent";
import "../events/pingPongEvent";
import "../events/slamDunkEvent";
import "../events/uppercutEvent";
import "../events/headHopEvent";
import "../events/paparazziEvent";
import "../events/missileBarrageEvent";
import "../events/sonicBoomEvent";
import "../events/mitosisEvent";
import "../events/plinkoEvent";
import "../events/hammerThrowEvent";
import "../events/snakeEvent";
import "../events/breakoutEvent";
import "../events/lineClearEvent";
import "../events/breakShotEvent";
import "../events/vortexEvent";
import "../events/waterfallEvent";
import "../events/conveyorEvent";
import "../events/firefliesEvent";
import "../events/streamEvent";
import "../events/trailsEvent";
import "../events/drawEvent";
import "../events/nightSkyEvent";
import "../events/pitcherEvent";
import "../events/glimmerEvent";
import "../events/renovateEvent";
import "../events/upgradeEvent";
import "../events/unlockEvent";

export { forceApollonianGasketEvent } from "../events/apollonianGasketEvent";
export { forceDroneShowEvent } from "../events/droneShowEvent";
export { forceMarxGeneratorEvent } from "../events/marxGeneratorEvent";
export { forceOortCloudEvent } from "../events/oortCloudEvent";
export { forceDoubleSlitEvent } from "../events/doubleSlitEvent";
export { forceBlastSweepEvent } from "../events/blastSweepEvent";
export { forceHydraulicJumpEvent } from "../events/hydraulicJumpEvent";
export { forceLightspeedEvent } from "../events/lightspeedEvent";
export { forceStarfighterEvent } from "../events/starfighterEvent";
export { forceFreefallEvent } from "../events/freefallEvent";
export { forceSaloonEvent } from "../events/saloonEvent";
export { forceDoomEvent } from "../events/doomEvent";
export { forceRoadRaceEvent } from "../events/roadRaceEvent";
export { forceSkyRaidEvent } from "../events/skyRaidEvent";
export { forceLockOnVolleyEvent } from "../events/lockOnVolleyEvent";
export { forceRockFieldEvent } from "../events/rockFieldEvent";
export { forceMineBeltEvent } from "../events/mineBeltEvent";
export { forceRingRunEvent } from "../events/ringRunEvent";
export { forceConvoyEvent } from "../events/convoyEvent";
export { forceFireworksFlightEvent } from "../events/fireworksFlightEvent";
export { forceStormFlightEvent } from "../events/stormFlightEvent";
export { forceCometChaseEvent } from "../events/cometChaseEvent";
export { forceGalaxyFlightEvent } from "../events/galaxyFlightEvent";
export { forceBattlecruiserEvent } from "../events/battlecruiserEvent";
export { forceLaserGauntletEvent } from "../events/laserGauntletEvent";
export { forceWormholeDiveEvent } from "../events/wormholeDiveEvent";
export { forceDoublingBounceEvent } from "../events/doublingBounceEvent";
export { forceAirJuggleEvent } from "../events/airJuggleEvent";
export { forceNovaDiskEvent } from "../events/novaDiskEvent";
export { forceBlastCoatEvent } from "../events/blastCoatEvent";
export { forceCashCoilEvent } from "../events/cashCoilEvent";
export { forceThreadingEvent } from "../events/threadingEvent";
export { forceBoltBindingEvent } from "../events/boltBindingEvent";
export { forceFortressEvent } from "../events/fortressEvent";
export { forceMeteorSplitterEvent } from "../events/meteorSplitterEvent";
export { forceThunderDuelEvent } from "../events/thunderDuelEvent";
export { forceForkStormEvent } from "../events/forkStormEvent";
export { forceIonHazeEvent } from "../events/ionHazeEvent";
export { forceNebulaEvent } from "../events/nebulaEvent";
export { forceSurvivorsEvent } from "../events/survivorsEvent";
export { forceGeometryRunEvent } from "../events/geometryRunEvent";
export { forceDysonSphereEvent } from "../events/dysonSphereEvent";
export { forceSeedPodsEvent } from "../events/seedPodsEvent";
export { forceRippleFireEvent } from "../events/rippleFireEvent";
export { forceSparkChamberEvent } from "../events/sparkChamberEvent";
export { forceTurbineEvent } from "../events/turbineEvent";
export { forceStrangeAttractorEvent } from "../events/strangeAttractorEvent";
export { forceTopsyTurvyEvent } from "../events/topsyTurvyEvent";
export { forceGoldPlatingEvent } from "../events/goldPlatingEvent";
export { forceCrosswindEvent } from "../events/crosswindEvent";
export { forceHailstoneEvent } from "../events/hailstoneEvent";
export { forceHilbertCurveEvent } from "../events/hilbertCurveEvent";
export { forceLeMansEvent } from "../events/leMansEvent";
export { forceTunnelBorerEvent } from "../events/tunnelBorerEvent";
export { forceHarpoonEvent } from "../events/harpoonEvent";
export { forceEightQueensEvent } from "../events/eightQueensEvent";
export { forceShortestPathEvent } from "../events/shortestPathEvent";
export { forceSinkholeEvent } from "../events/sinkholeEvent";
export { forceBackwashEvent } from "../events/backwashEvent";
export { forceDeflectorEvent } from "../events/deflectorEvent";
export { forceSunflowerEvent } from "../events/sunflowerEvent";
export { forceConvexHullEvent } from "../events/convexHullEvent";
export { forceSlashEvent } from "../events/slashEvent";
export { forceJackhammerEvent } from "../events/jackhammerEvent";
export { forcePummelEvent } from "../events/pummelEvent";
export { forceOverloadEvent } from "../events/overloadEvent";
export { forcePressEvent } from "../events/pressEvent";
export { forceBurrowEvent } from "../events/burrowEvent";
export { forcePingPongEvent } from "../events/pingPongEvent";
export { forceSlamDunkEvent } from "../events/slamDunkEvent";
export { forceUppercutEvent } from "../events/uppercutEvent";
export { forceHeadHopEvent } from "../events/headHopEvent";
export { forcePaparazziEvent } from "../events/paparazziEvent";
export { forceMissileBarrageEvent } from "../events/missileBarrageEvent";
export { forceSonicBoomEvent } from "../events/sonicBoomEvent";
export { forceMitosisEvent } from "../events/mitosisEvent";
export { forcePlinkoEvent } from "../events/plinkoEvent";
export { forceHammerThrowEvent } from "../events/hammerThrowEvent";
export { forceSnakeEvent } from "../events/snakeEvent";
export { forceBreakoutEvent } from "../events/breakoutEvent";
export { forceLineClearEvent } from "../events/lineClearEvent";
export { forceBreakShotEvent } from "../events/breakShotEvent";
export { forceVortexEvent } from "../events/vortexEvent";
export { forceWaterfallEvent } from "../events/waterfallEvent";
export { forceConveyorEvent } from "../events/conveyorEvent";
export { forceFirefliesEvent } from "../events/firefliesEvent";
export { forceStreamEvent } from "../events/streamEvent";
export { forceTrailsEvent } from "../events/trailsEvent";
export { forceDrawEvent } from "../events/drawEvent";
export { forceNightSkyEvent } from "../events/nightSkyEvent";
export { forcePitcherEvent } from "../events/pitcherEvent";
export { forceGlimmerEvent } from "../events/glimmerEvent";
export { forceRenovateEvent } from "../events/renovateEvent";
export { forceUpgradeEvent } from "../events/upgradeEvent";
export { forceUnlockEvent } from "../events/unlockEvent";
