// event modules, part 6 of 9 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../events/moonHopEvent";
import "../events/peekabooEvent";
import "../events/tiltAWhirlEvent";
import "../events/waterStriderEvent";
import "../events/ropeClimbEvent";
import "../events/paddleSteamerEvent";
import "../events/jetWashEvent";
import "../events/bellowsEvent";
import "../events/rainDanceEvent";
import "../events/skiTowEvent";
import "../events/ribbonDancerEvent";
import "../events/laserTurnstileEvent";
import "../events/lightBridgeEvent";
import "../events/laserWebEvent";
import "../events/footlightsEvent";
import "../events/fusionBeamEvent";
import "../events/pinpointEvent";
import "../events/galvanizeEvent";
import "../events/sparkJumpEvent";
import "../events/staticClingEvent";
import "../events/capacitorEvent";
import "../events/sparkTrainEvent";
import "../events/arcBridgeEvent";
import "../events/daisyCutterEvent";
import "../events/rippleMinesEvent";
import "../events/bombYoYoEvent";
import "../events/bombHailEvent";
import "../events/groundPoundEvent";
import "../events/cherryBombEvent";
import "../events/bombCrownEvent";
import "../events/bulletCombEvent";
import "../events/bulletBraidEvent";
import "../events/bulletCageEvent";
import "../events/gunslingerEvent";
import "../events/bulletWheelEvent";
import "../events/bulletLadderEvent";
import "../events/whipZoomEvent";
import "../events/irisOutEvent";
import "../events/screenReelsEvent";
import "../events/goldLeafEvent";
import "../events/pixelStormEvent";
import "../events/gravityFlipEvent";
import "../events/echoEvent";
import "../events/mirrorBoxEvent";
import "../events/pullBackEvent";
import "../events/treadmillEvent";
import "../events/blastOffEvent";
import "../events/popUpEvent";
import "../events/stickerPeelEvent";
import "../events/glissandoEvent";
import "../events/vaultDoorsEvent";
import "../events/champagneTowerEvent";
import "../events/pinballRiverEvent";
import "../events/pressureWasherEvent";
import "../events/irrigationEvent";
import "../events/waterspoutEvent";
import "../events/sidewinderEvent";
import "../events/orbitSwapEvent";
import "../events/cuckooEvent";
import "../events/gyreEvent";
import "../events/barHopEvent";
import "../events/cometPlowEvent";
import "../events/hoseReelEvent";
import "../events/geyserRiderEvent";
import "../events/bubbleBlowerEvent";
import "../events/poolDiveEvent";
import "../events/rubberBandEvent";
import "../events/beamViseEvent";
import "../events/laserRakeEvent";
import "../events/lightDominoesEvent";
import "../events/pryBarEvent";
import "../events/teslaTennisEvent";
import "../events/tuningForkEvent";
import "../events/boltSpiralEvent";
import "../events/groundCurrentEvent";
import "../events/overchargeEvent";
import "../events/bombTornadoEvent";
import "../events/bombBoomerangEvent";
import "../events/multistageEvent";
import "../events/bombPileEvent";
import "../events/bombGarlandEvent";
import "../events/homingRoundsEvent";
import "../events/waveCannonEvent";
import "../events/snapbackEvent";
import "../events/bulletFunnelEvent";
import "../events/crisscrossEvent";
import "../events/chainFountainEvent";
import "../events/smokeRingsEvent";
import "../events/waterSaluteEvent";
import "../events/doublePendulumEvent";
import "../events/trapezeEvent";
import "../events/diaboloEvent";
import "../events/zorbEvent";
import "../events/hoopDiveEvent";
import "../events/spinArtEvent";
import "../events/paperCutterEvent";
import "../events/flippersEvent";
import "../events/drawbridgeEvent";
import "../events/flailEvent";
import "../events/vineSwingEvent";
import "../events/bombSnowballEvent";
import "../events/gerbEvent";
import "../events/recoilEvent";
import "../events/tumbleFireEvent";
import "../events/rollUpEvent";
import "../events/shredderEvent";
import "../events/headOnEvent";
import "../events/pyramidEvent";
import "../events/pizzaTossEvent";
import "../events/compassEvent";
import "../events/skewerEvent";
import "../events/bombCometEvent";
import "../events/kaboomEvent";
import "../events/returnFireEvent";
import "../events/frostedGlassEvent";
import "../events/switchOffEvent";
import "../events/stuntTrackEvent";
import "../events/fleasEvent";
import "../events/handPumpEvent";
import "../events/pickUpSticksEvent";
import "../events/thunderShellEvent";
import "../events/midAirEvent";
import "../events/chainFireEvent";
import "../events/rimShotEvent";
import "../events/tinRoofEvent";
import "../events/crumpleEvent";
import "../events/minimizeEvent";
import "../events/jumpingJetsEvent";
import "../events/bubbleChamberEvent";
import "../events/castNetEvent";
import "../events/hobermanEvent";
import "../events/excaliburEvent";
import "../events/pistonsEvent";
import "../events/williamTellEvent";
import "../events/foosballEvent";
import "../events/rubberSheetEvent";
import "../events/rattleEvent";
import "../events/eddiesEvent";
import "../events/tubeManEvent";
import "../events/deflateEvent";
// the dev test bar's hooks
export { forceMoonHopEvent } from "../events/moonHopEvent";
export { forcePeekabooEvent } from "../events/peekabooEvent";
export { forceTiltAWhirlEvent } from "../events/tiltAWhirlEvent";
export { forceWaterStriderEvent } from "../events/waterStriderEvent";
export { forceRopeClimbEvent } from "../events/ropeClimbEvent";
export { forcePaddleSteamerEvent } from "../events/paddleSteamerEvent";
export { forceJetWashEvent } from "../events/jetWashEvent";
export { forceBellowsEvent } from "../events/bellowsEvent";
export { forceRainDanceEvent } from "../events/rainDanceEvent";
export { forceSkiTowEvent } from "../events/skiTowEvent";
export { forceRibbonDancerEvent } from "../events/ribbonDancerEvent";
export { forceLaserTurnstileEvent } from "../events/laserTurnstileEvent";
export { forceLightBridgeEvent } from "../events/lightBridgeEvent";
export { forceLaserWebEvent } from "../events/laserWebEvent";
export { forceFootlightsEvent } from "../events/footlightsEvent";
export { forceFusionBeamEvent } from "../events/fusionBeamEvent";
export { forcePinpointEvent } from "../events/pinpointEvent";
export { forceGalvanizeEvent } from "../events/galvanizeEvent";
export { forceSparkJumpEvent } from "../events/sparkJumpEvent";
export { forceStaticClingEvent } from "../events/staticClingEvent";
export { forceCapacitorEvent } from "../events/capacitorEvent";
export { forceSparkTrainEvent } from "../events/sparkTrainEvent";
export { forceArcBridgeEvent } from "../events/arcBridgeEvent";
export { forceDaisyCutterEvent } from "../events/daisyCutterEvent";
export { forceRippleMinesEvent } from "../events/rippleMinesEvent";
export { forceBombYoYoEvent } from "../events/bombYoYoEvent";
export { forceBombHailEvent } from "../events/bombHailEvent";
export { forceGroundPoundEvent } from "../events/groundPoundEvent";
export { forceCherryBombEvent } from "../events/cherryBombEvent";
export { forceBombCrownEvent } from "../events/bombCrownEvent";
export { forceBulletCombEvent } from "../events/bulletCombEvent";
export { forceBulletBraidEvent } from "../events/bulletBraidEvent";
export { forceBulletCageEvent } from "../events/bulletCageEvent";
export { forceGunslingerEvent } from "../events/gunslingerEvent";
export { forceBulletWheelEvent } from "../events/bulletWheelEvent";
export { forceBulletLadderEvent } from "../events/bulletLadderEvent";
export { forceWhipZoomEvent } from "../events/whipZoomEvent";
export { forceIrisOutEvent } from "../events/irisOutEvent";
export { forceScreenReelsEvent } from "../events/screenReelsEvent";
export { forceGoldLeafEvent } from "../events/goldLeafEvent";
export { forcePixelStormEvent } from "../events/pixelStormEvent";
export { forceGravityFlipEvent } from "../events/gravityFlipEvent";
export { forceEchoEvent } from "../events/echoEvent";
export { forceMirrorBoxEvent } from "../events/mirrorBoxEvent";
export { forcePullBackEvent } from "../events/pullBackEvent";
export { forceTreadmillEvent } from "../events/treadmillEvent";
export { forceBlastOffEvent } from "../events/blastOffEvent";
export { forcePopUpEvent } from "../events/popUpEvent";
export { forceStickerPeelEvent } from "../events/stickerPeelEvent";
export { forceGlissandoEvent } from "../events/glissandoEvent";
export { forceVaultDoorsEvent } from "../events/vaultDoorsEvent";
export { forceChampagneTowerEvent } from "../events/champagneTowerEvent";
export { forcePinballRiverEvent } from "../events/pinballRiverEvent";
export { forcePressureWasherEvent } from "../events/pressureWasherEvent";
export { forceIrrigationEvent } from "../events/irrigationEvent";
export { forceWaterspoutEvent } from "../events/waterspoutEvent";
export { forceSidewinderEvent } from "../events/sidewinderEvent";
export { forceOrbitSwapEvent } from "../events/orbitSwapEvent";
export { forceCuckooEvent } from "../events/cuckooEvent";
export { forceGyreEvent } from "../events/gyreEvent";
export { forceBarHopEvent } from "../events/barHopEvent";
export { forceCometPlowEvent } from "../events/cometPlowEvent";
export { forceHoseReelEvent } from "../events/hoseReelEvent";
export { forceGeyserRiderEvent } from "../events/geyserRiderEvent";
export { forceBubbleBlowerEvent } from "../events/bubbleBlowerEvent";
export { forcePoolDiveEvent } from "../events/poolDiveEvent";
export { forceRubberBandEvent } from "../events/rubberBandEvent";
export { forceBeamViseEvent } from "../events/beamViseEvent";
export { forceLaserRakeEvent } from "../events/laserRakeEvent";
export { forceLightDominoesEvent } from "../events/lightDominoesEvent";
export { forcePryBarEvent } from "../events/pryBarEvent";
export { forceTeslaTennisEvent } from "../events/teslaTennisEvent";
export { forceTuningForkEvent } from "../events/tuningForkEvent";
export { forceBoltSpiralEvent } from "../events/boltSpiralEvent";
export { forceGroundCurrentEvent } from "../events/groundCurrentEvent";
export { forceOverchargeEvent } from "../events/overchargeEvent";
export { forceBombTornadoEvent } from "../events/bombTornadoEvent";
export { forceBombBoomerangEvent } from "../events/bombBoomerangEvent";
export { forceMultistageEvent } from "../events/multistageEvent";
export { forceBombPileEvent } from "../events/bombPileEvent";
export { forceBombGarlandEvent } from "../events/bombGarlandEvent";
export { forceHomingRoundsEvent } from "../events/homingRoundsEvent";
export { forceWaveCannonEvent } from "../events/waveCannonEvent";
export { forceSnapbackEvent } from "../events/snapbackEvent";
export { forceBulletFunnelEvent } from "../events/bulletFunnelEvent";
export { forceCrisscrossEvent } from "../events/crisscrossEvent";
export { forceChainFountainEvent } from "../events/chainFountainEvent";
export { forceSmokeRingsEvent } from "../events/smokeRingsEvent";
export { forceWaterSaluteEvent } from "../events/waterSaluteEvent";
export { forceDoublePendulumEvent } from "../events/doublePendulumEvent";
export { forceTrapezeEvent } from "../events/trapezeEvent";
export { forceDiaboloEvent } from "../events/diaboloEvent";
export { forceZorbEvent } from "../events/zorbEvent";
export { forceHoopDiveEvent } from "../events/hoopDiveEvent";
export { forceSpinArtEvent } from "../events/spinArtEvent";
export { forcePaperCutterEvent } from "../events/paperCutterEvent";
export { forceFlippersEvent } from "../events/flippersEvent";
export { forceDrawbridgeEvent } from "../events/drawbridgeEvent";
export { forceFlailEvent } from "../events/flailEvent";
export { forceVineSwingEvent } from "../events/vineSwingEvent";
export { forceBombSnowballEvent } from "../events/bombSnowballEvent";
export { forceGerbEvent } from "../events/gerbEvent";
export { forceRecoilEvent } from "../events/recoilEvent";
export { forceTumbleFireEvent } from "../events/tumbleFireEvent";
export { forceRollUpEvent } from "../events/rollUpEvent";
export { forceShredderEvent } from "../events/shredderEvent";
export { forceHeadOnEvent } from "../events/headOnEvent";
export { forcePyramidEvent } from "../events/pyramidEvent";
export { forcePizzaTossEvent } from "../events/pizzaTossEvent";
export { forceCompassEvent } from "../events/compassEvent";
export { forceSkewerEvent } from "../events/skewerEvent";
export { forceBombCometEvent } from "../events/bombCometEvent";
export { forceKaboomEvent } from "../events/kaboomEvent";
export { forceReturnFireEvent } from "../events/returnFireEvent";
export { forceFrostedGlassEvent } from "../events/frostedGlassEvent";
export { forceSwitchOffEvent } from "../events/switchOffEvent";
export { forceStuntTrackEvent } from "../events/stuntTrackEvent";
export { forceFleasEvent } from "../events/fleasEvent";
export { forceHandPumpEvent } from "../events/handPumpEvent";
export { forcePickUpSticksEvent } from "../events/pickUpSticksEvent";
export { forceThunderShellEvent } from "../events/thunderShellEvent";
export { forceMidAirEvent } from "../events/midAirEvent";
export { forceChainFireEvent } from "../events/chainFireEvent";
export { forceRimShotEvent } from "../events/rimShotEvent";
export { forceTinRoofEvent } from "../events/tinRoofEvent";
export { forceCrumpleEvent } from "../events/crumpleEvent";
export { forceMinimizeEvent } from "../events/minimizeEvent";
export { forceJumpingJetsEvent } from "../events/jumpingJetsEvent";
export { forceBubbleChamberEvent } from "../events/bubbleChamberEvent";
export { forceCastNetEvent } from "../events/castNetEvent";
export { forceHobermanEvent } from "../events/hobermanEvent";
export { forceExcaliburEvent } from "../events/excaliburEvent";
export { forcePistonsEvent } from "../events/pistonsEvent";
export { forceWilliamTellEvent } from "../events/williamTellEvent";
export { forceFoosballEvent } from "../events/foosballEvent";
export { forceRubberSheetEvent } from "../events/rubberSheetEvent";
export { forceRattleEvent } from "../events/rattleEvent";
export { forceEddiesEvent } from "../events/eddiesEvent";
export { forceTubeManEvent } from "../events/tubeManEvent";
export { forceDeflateEvent } from "../events/deflateEvent";
