// event modules, part 5 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../events/toasterEvent";
import "../events/xylophoneEvent";
import "../events/birthdayCandlesEvent";
import "../events/dropTowerEvent";
import "../events/arrowVolleyEvent";
import "../events/makeAWishEvent";
import "../events/blunderbussEvent";
import "../events/genieEvent";
import "../events/solarFlareEvent";
import "../events/heatVisionEvent";
import "../events/printHeadEvent";
import "../events/auroraEvent";
import "../events/thunderRingsEvent";
import "../events/arcWeldEvent";
import "../events/stormKiteEvent";
import "../events/volcanicLightningEvent";
import "../events/sculptorEvent";
import "../events/grandFinaleEvent";
import "../events/bombBouquetEvent";
import "../events/cascadeEvent";
import "../events/pinballBombEvent";
import "../events/bombTrainEvent";
import "../events/breachingChargeEvent";
import "../events/confettiCannonEvent";
import "../events/ammoBeltEvent";
import "../events/gauntletEvent";
import "../events/turretTowerEvent";
import "../events/shellCasingsEvent";
import "../events/dartsEvent";
import "../events/battleshipEvent";
import "../events/interceptorsEvent";
import "../events/landGrabEvent";
import "../events/duckDuckGooseEvent";
import "../events/ringerEvent";
import "../events/hurdlesEvent";
import "../events/luckyRollEvent";
import "../events/cashRegisterEvent";
import "../events/horseRaceEvent";
import "../events/dunkTankEvent";
import "../events/halfPipeEvent";
import "../events/knotEvent";
import "../events/tickerTapeEvent";
import "../events/cashBridgeEvent";
import "../events/skippingStoneEvent";
import "../events/woodpeckerEvent";
import "../events/frisbeeEvent";
import "../events/kangarooEvent";
import "../events/badmintonEvent";
import "../events/tumbleweedEvent";
import "../events/shuttleRunEvent";
import "../events/echolocationEvent";
import "../events/lacrosseEvent";
import "../events/jetSkiEvent";
import "../events/drinkingStrawEvent";
import "../events/seaSerpentEvent";
import "../events/magicTrickEvent";
import "../events/fountainPenEvent";
import "../events/spoolEvent";
import "../events/laserRainEvent";
import "../events/crossCutEvent";
import "../events/heliographEvent";
import "../events/starburstEvent";
import "../events/thunderDrumEvent";
import "../events/boltBarrageEvent";
import "../events/coilgunEvent";
import "../events/snowflakeEvent";
import "../events/bombSnakeEvent";
import "../events/spiderMinesEvent";
import "../events/crossetteEvent";
import "../events/spiralChargeEvent";
import "../events/bombBubblesEvent";
import "../events/rocketSledEvent";
import "../events/dynamiteFishingEvent";
import "../events/chargeShotEvent";
import "../events/corkscrewRoundsEvent";
import "../events/orbitalGunsEvent";
import "../events/tracerRoundsEvent";
import "../events/pelletStormEvent";
import "../events/bulletSnakeEvent";
import "../events/rockPaperScissorsEvent";
import "../events/limboEvent";
import "../events/quizShowEvent";
import "../events/sumoEvent";
import "../events/paperTossEvent";
import "../events/armWrestlingEvent";
import "../events/keepyUppyEvent";
import "../events/pinTheTailEvent";
import "../events/trustFallEvent";
import "../events/bubbleGumEvent";
import "../events/canalLocksEvent";
import "../events/bobsledEvent";
import "../events/springLoadedEvent";
import "../events/influxEvent";
import "../events/unevenBarsEvent";
import "../events/bumblebeeEvent";
import "../events/shotPutEvent";
import "../events/humanCannonballEvent";
import "../events/foxAndHoundsEvent";
import "../events/kingfisherEvent";
import "../events/joustEvent";
import "../events/pelicanEvent";
import "../events/dragsterEvent";
import "../events/fireBreatherEvent";
import "../events/bucketSwingEvent";
import "../events/puppeteerEvent";
import "../events/coronaEvent";
import "../events/pillarsEvent";
import "../events/laserLadderEvent";
import "../events/beamSplitterEvent";
import "../events/teleporterEvent";
import "../events/ringLightEvent";
import "../events/taserEvent";
import "../events/arcFurnaceEvent";
import "../events/fiveFingersEvent";
import "../events/cattleProdEvent";
import "../events/boltSlingEvent";
import "../events/collidingStormsEvent";
import "../events/bombJugglerEvent";
import "../events/bombSquadEvent";
import "../events/splitterEvent";
import "../events/bombPendulumEvent";
import "../events/paradropEvent";
import "../events/bombPachinkoEvent";
import "../events/fuseClockEvent";
import "../events/hedgehogEvent";
import "../events/splitShotEvent";
import "../events/bulletLassoEvent";
import "../events/bulletWeaveEvent";
import "../events/bulletFountainEvent";
import "../events/coveringFireEvent";
import "../events/checkersEvent";
import "../events/minesweeperEvent";
import "../events/jackInTheBoxEvent";
import "../events/spillwayEvent";
import "../events/crosscurrentsEvent";
import "../events/oxbowEvent";
import "../events/breakersEvent";
import "../events/rivuletsEvent";
import "../events/torrentEvent";
import "../events/lissajousEvent";
// the dev test bar's hooks
export { forceToasterEvent } from "../events/toasterEvent";
export { forceXylophoneEvent } from "../events/xylophoneEvent";
export { forceBirthdayCandlesEvent } from "../events/birthdayCandlesEvent";
export { forceDropTowerEvent } from "../events/dropTowerEvent";
export { forceArrowVolleyEvent } from "../events/arrowVolleyEvent";
export { forceMakeAWishEvent } from "../events/makeAWishEvent";
export { forceBlunderbussEvent } from "../events/blunderbussEvent";
export { forceGenieEvent } from "../events/genieEvent";
export { forceSolarFlareEvent } from "../events/solarFlareEvent";
export { forceHeatVisionEvent } from "../events/heatVisionEvent";
export { forcePrintHeadEvent } from "../events/printHeadEvent";
export { forceAuroraEvent } from "../events/auroraEvent";
export { forceThunderRingsEvent } from "../events/thunderRingsEvent";
export { forceArcWeldEvent } from "../events/arcWeldEvent";
export { forceStormKiteEvent } from "../events/stormKiteEvent";
export { forceVolcanicLightningEvent } from "../events/volcanicLightningEvent";
export { forceSculptorEvent } from "../events/sculptorEvent";
export { forceGrandFinaleEvent } from "../events/grandFinaleEvent";
export { forceBombBouquetEvent } from "../events/bombBouquetEvent";
export { forceCascadeEvent } from "../events/cascadeEvent";
export { forcePinballBombEvent } from "../events/pinballBombEvent";
export { forceBombTrainEvent } from "../events/bombTrainEvent";
export { forceBreachingChargeEvent } from "../events/breachingChargeEvent";
export { forceConfettiCannonEvent } from "../events/confettiCannonEvent";
export { forceAmmoBeltEvent } from "../events/ammoBeltEvent";
export { forceGauntletEvent } from "../events/gauntletEvent";
export { forceTurretTowerEvent } from "../events/turretTowerEvent";
export { forceShellCasingsEvent } from "../events/shellCasingsEvent";
export { forceDartsEvent } from "../events/dartsEvent";
export { forceBattleshipEvent } from "../events/battleshipEvent";
export { forceInterceptorsEvent } from "../events/interceptorsEvent";
export { forceLandGrabEvent } from "../events/landGrabEvent";
export { forceDuckDuckGooseEvent } from "../events/duckDuckGooseEvent";
export { forceRingerEvent } from "../events/ringerEvent";
export { forceHurdlesEvent } from "../events/hurdlesEvent";
export { forceLuckyRollEvent } from "../events/luckyRollEvent";
export { forceCashRegisterEvent } from "../events/cashRegisterEvent";
export { forceHorseRaceEvent } from "../events/horseRaceEvent";
export { forceDunkTankEvent } from "../events/dunkTankEvent";
export { forceHalfPipeEvent } from "../events/halfPipeEvent";
export { forceKnotEvent } from "../events/knotEvent";
export { forceTickerTapeEvent } from "../events/tickerTapeEvent";
export { forceCashBridgeEvent } from "../events/cashBridgeEvent";
export { forceSkippingStoneEvent } from "../events/skippingStoneEvent";
export { forceWoodpeckerEvent } from "../events/woodpeckerEvent";
export { forceFrisbeeEvent } from "../events/frisbeeEvent";
export { forceKangarooEvent } from "../events/kangarooEvent";
export { forceBadmintonEvent } from "../events/badmintonEvent";
export { forceTumbleweedEvent } from "../events/tumbleweedEvent";
export { forceShuttleRunEvent } from "../events/shuttleRunEvent";
export { forceEcholocationEvent } from "../events/echolocationEvent";
export { forceLacrosseEvent } from "../events/lacrosseEvent";
export { forceJetSkiEvent } from "../events/jetSkiEvent";
export { forceDrinkingStrawEvent } from "../events/drinkingStrawEvent";
export { forceSeaSerpentEvent } from "../events/seaSerpentEvent";
export { forceMagicTrickEvent } from "../events/magicTrickEvent";
export { forceFountainPenEvent } from "../events/fountainPenEvent";
export { forceSpoolEvent } from "../events/spoolEvent";
export { forceLaserRainEvent } from "../events/laserRainEvent";
export { forceCrossCutEvent } from "../events/crossCutEvent";
export { forceHeliographEvent } from "../events/heliographEvent";
export { forceStarburstEvent } from "../events/starburstEvent";
export { forceThunderDrumEvent } from "../events/thunderDrumEvent";
export { forceBoltBarrageEvent } from "../events/boltBarrageEvent";
export { forceCoilgunEvent } from "../events/coilgunEvent";
export { forceSnowflakeEvent } from "../events/snowflakeEvent";
export { forceBombSnakeEvent } from "../events/bombSnakeEvent";
export { forceSpiderMinesEvent } from "../events/spiderMinesEvent";
export { forceCrossetteEvent } from "../events/crossetteEvent";
export { forceSpiralChargeEvent } from "../events/spiralChargeEvent";
export { forceBombBubblesEvent } from "../events/bombBubblesEvent";
export { forceRocketSledEvent } from "../events/rocketSledEvent";
export { forceDynamiteFishingEvent } from "../events/dynamiteFishingEvent";
export { forceChargeShotEvent } from "../events/chargeShotEvent";
export { forceCorkscrewRoundsEvent } from "../events/corkscrewRoundsEvent";
export { forceOrbitalGunsEvent } from "../events/orbitalGunsEvent";
export { forceTracerRoundsEvent } from "../events/tracerRoundsEvent";
export { forcePelletStormEvent } from "../events/pelletStormEvent";
export { forceBulletSnakeEvent } from "../events/bulletSnakeEvent";
export { forceRockPaperScissorsEvent } from "../events/rockPaperScissorsEvent";
export { forceLimboEvent } from "../events/limboEvent";
export { forceQuizShowEvent } from "../events/quizShowEvent";
export { forceSumoEvent } from "../events/sumoEvent";
export { forcePaperTossEvent } from "../events/paperTossEvent";
export { forceArmWrestlingEvent } from "../events/armWrestlingEvent";
export { forceKeepyUppyEvent } from "../events/keepyUppyEvent";
export { forcePinTheTailEvent } from "../events/pinTheTailEvent";
export { forceTrustFallEvent } from "../events/trustFallEvent";
export { forceBubbleGumEvent } from "../events/bubbleGumEvent";
export { forceCanalLocksEvent } from "../events/canalLocksEvent";
export { forceBobsledEvent } from "../events/bobsledEvent";
export { forceSpringLoadedEvent } from "../events/springLoadedEvent";
export { forceInfluxEvent } from "../events/influxEvent";
export { forceUnevenBarsEvent } from "../events/unevenBarsEvent";
export { forceBumblebeeEvent } from "../events/bumblebeeEvent";
export { forceShotPutEvent } from "../events/shotPutEvent";
export { forceHumanCannonballEvent } from "../events/humanCannonballEvent";
export { forceFoxAndHoundsEvent } from "../events/foxAndHoundsEvent";
export { forceKingfisherEvent } from "../events/kingfisherEvent";
export { forceJoustEvent } from "../events/joustEvent";
export { forcePelicanEvent } from "../events/pelicanEvent";
export { forceDragsterEvent } from "../events/dragsterEvent";
export { forceFireBreatherEvent } from "../events/fireBreatherEvent";
export { forceBucketSwingEvent } from "../events/bucketSwingEvent";
export { forcePuppeteerEvent } from "../events/puppeteerEvent";
export { forceCoronaEvent } from "../events/coronaEvent";
export { forcePillarsEvent } from "../events/pillarsEvent";
export { forceLaserLadderEvent } from "../events/laserLadderEvent";
export { forceBeamSplitterEvent } from "../events/beamSplitterEvent";
export { forceTeleporterEvent } from "../events/teleporterEvent";
export { forceRingLightEvent } from "../events/ringLightEvent";
export { forceTaserEvent } from "../events/taserEvent";
export { forceArcFurnaceEvent } from "../events/arcFurnaceEvent";
export { forceFiveFingersEvent } from "../events/fiveFingersEvent";
export { forceCattleProdEvent } from "../events/cattleProdEvent";
export { forceBoltSlingEvent } from "../events/boltSlingEvent";
export { forceCollidingStormsEvent } from "../events/collidingStormsEvent";
export { forceBombJugglerEvent } from "../events/bombJugglerEvent";
export { forceBombSquadEvent } from "../events/bombSquadEvent";
export { forceSplitterEvent } from "../events/splitterEvent";
export { forceBombPendulumEvent } from "../events/bombPendulumEvent";
export { forceParadropEvent } from "../events/paradropEvent";
export { forceBombPachinkoEvent } from "../events/bombPachinkoEvent";
export { forceFuseClockEvent } from "../events/fuseClockEvent";
export { forceHedgehogEvent } from "../events/hedgehogEvent";
export { forceSplitShotEvent } from "../events/splitShotEvent";
export { forceBulletLassoEvent } from "../events/bulletLassoEvent";
export { forceBulletWeaveEvent } from "../events/bulletWeaveEvent";
export { forceBulletFountainEvent } from "../events/bulletFountainEvent";
export { forceCoveringFireEvent } from "../events/coveringFireEvent";
export { forceCheckersEvent } from "../events/checkersEvent";
export { forceMinesweeperEvent } from "../events/minesweeperEvent";
export { forceJackInTheBoxEvent } from "../events/jackInTheBoxEvent";
export { forceSpillwayEvent } from "../events/spillwayEvent";
export { forceCrosscurrentsEvent } from "../events/crosscurrentsEvent";
export { forceOxbowEvent } from "../events/oxbowEvent";
export { forceBreakersEvent } from "../events/breakersEvent";
export { forceRivuletsEvent } from "../events/rivuletsEvent";
export { forceTorrentEvent } from "../events/torrentEvent";
export { forceLissajousEvent } from "../events/lissajousEvent";
