// event modules, part 3 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../events/matryoshkaEvent";
import "../events/salmonRunEvent";
import "../events/moonTideEvent";
import "../events/candyFlossEvent";
import "../events/figureSkaterEvent";
import "../events/tripwireEvent";
import "../events/sunriseEvent";
import "../events/rallyEvent";
import "../events/ignitionEvent";
import "../events/tridentEvent";
import "../events/crawlEvent";
import "../events/carpetBombingEvent";
import "../events/timeBombEvent";
import "../events/bunkerBusterEvent";
import "../events/grenadeTossEvent";
import "../events/depthChargesEvent";
import "../events/firingSquadEvent";
import "../events/akimboEvent";
import "../events/flakBarrageEvent";
import "../events/sniperNestEvent";
import "../events/rewindEvent";
import "../events/morseCodeEvent";
import "../events/stadiumWaveEvent";
import "../events/knightsTourEvent";
import "../events/lavaLampEvent";
import "../events/dominoesEvent";
import "../events/inkblotEvent";
import "../events/softServeEvent";
import "../events/dollarSignEvent";
import "../events/mobiusEvent";
import "../events/swissRollEvent";
import "../events/dodgeballEvent";
import "../events/congaLineEvent";
import "../events/spinningTopEvent";
import "../events/gobblerEvent";
import "../events/majoretteEvent";
import "../events/hulaHoopEvent";
import "../events/calligraphyEvent";
import "../events/snakeCharmerEvent";
import "../events/plateSpinnerEvent";
import "../events/ferrisWheelEvent";
import "../events/bucketBrigadeEvent";
import "../events/skyLanternsEvent";
import "../events/engraverEvent";
import "../events/xRayEvent";
import "../events/laserLassoEvent";
import "../events/hexRingEvent";
import "../events/portcullisEvent";
import "../events/keyholeEvent";
import "../events/defibrillatorEvent";
import "../events/circuitBoardEvent";
import "../events/mjolnirEvent";
import "../events/arcFlashEvent";
import "../events/fourCornersEvent";
import "../events/boltWheelEvent";
import "../events/minefieldEvent";
import "../events/cannonadeEvent";
import "../events/stickyBombsEvent";
import "../events/crossblastEvent";
import "../events/mortarEvent";
import "../events/flashbangEvent";
import "../events/sentryTurretEvent";
import "../events/shotgunEvent";
import "../events/bossFightEvent";
import "../events/gunshipEvent";
import "../events/bulletTimeEvent";
import "../events/flechettesEvent";
import "../events/radarEvent";
import "../events/bingoEvent";
import "../events/laneHopperEvent";
import "../events/simonSaysEvent";
import "../events/equalizerEvent";
import "../events/loadingBarEvent";
import "../events/diceRollEvent";
import "../events/mandalaEvent";
import "../events/zenGardenEvent";
import "../events/accordionEvent";
import "../events/fizzEvent";
import "../events/soundwaveEvent";
import "../events/taffyEvent";
import "../events/dripPaintingEvent";
import "../events/mothsEvent";
import "../events/curlingEvent";
import "../events/clotheslineEvent";
import "../events/balloonPopEvent";
import "../events/spinBottleEvent";
import "../events/skyWriterEvent";
import "../events/goldPanEvent";
import "../events/bulldozerEvent";
import "../events/koiPondEvent";
import "../events/pipeOrganEvent";
import "../events/antTrailEvent";
import "../events/hotAirBalloonEvent";
import "../events/lensFlareEvent";
import "../events/tightropeEvent";
import "../events/neonSignEvent";
import "../events/lightCageEvent";
import "../events/stairwayEvent";
import "../events/beaconsEvent";
import "../events/anvilCrawlerEvent";
import "../events/neuronsEvent";
import "../events/bottledBoltEvent";
import "../events/thunderbirdEvent";
import "../events/sparkGapEvent";
import "../events/staticShockEvent";
import "../events/rocketJumpEvent";
import "../events/torpedoesEvent";
import "../events/airstrikeEvent";
import "../events/dambusterEvent";
import "../events/airburstEvent";
import "../events/bombPinwheelEvent";
import "../events/bulletCurtainEvent";
import "../events/trickShotEvent";
import "../events/railShooterEvent";
import "../events/skeetShootEvent";
import "../events/tripleTapEvent";
import "../events/tommyGunEvent";
import "../events/sweeperEvent";
import "../events/clawMachineEvent";
import "../events/lotteryEvent";
import "../events/wordGuessEvent";
import "../events/memoryMatchEvent";
import "../events/ticTacToeEvent";
import "../events/revCounterEvent";
import "../events/sluiceEvent";
import "../events/foundryEvent";
import "../events/jetStreamEvent";
import "../events/moatEvent";
import "../events/seepEvent";
import "../events/meanderEvent";
import "../events/waltzEvent";
import "../events/gyroscopeEvent";
import "../events/dragonflyEvent";
import "../events/ringTossEvent";
import "../events/slipstreamEvent";
import "../events/sheetMusicEvent";
import "../events/leafBlowerEvent";
import "../events/loomEvent";
import "../events/highDiveEvent";
import "../events/sowerEvent";
// the dev test bar's hooks
export { forceMatryoshkaEvent } from "../events/matryoshkaEvent";
export { forceSalmonRunEvent } from "../events/salmonRunEvent";
export { forceMoonTideEvent } from "../events/moonTideEvent";
export { forceCandyFlossEvent } from "../events/candyFlossEvent";
export { forceFigureSkaterEvent } from "../events/figureSkaterEvent";
export { forceTripwireEvent } from "../events/tripwireEvent";
export { forceSunriseEvent } from "../events/sunriseEvent";
export { forceRallyEvent } from "../events/rallyEvent";
export { forceIgnitionEvent } from "../events/ignitionEvent";
export { forceTridentEvent } from "../events/tridentEvent";
export { forceCrawlEvent } from "../events/crawlEvent";
export { forceCarpetBombingEvent } from "../events/carpetBombingEvent";
export { forceTimeBombEvent } from "../events/timeBombEvent";
export { forceBunkerBusterEvent } from "../events/bunkerBusterEvent";
export { forceGrenadeTossEvent } from "../events/grenadeTossEvent";
export { forceDepthChargesEvent } from "../events/depthChargesEvent";
export { forceFiringSquadEvent } from "../events/firingSquadEvent";
export { forceAkimboEvent } from "../events/akimboEvent";
export { forceFlakBarrageEvent } from "../events/flakBarrageEvent";
export { forceSniperNestEvent } from "../events/sniperNestEvent";
export { forceRewindEvent } from "../events/rewindEvent";
export { forceMorseCodeEvent } from "../events/morseCodeEvent";
export { forceStadiumWaveEvent } from "../events/stadiumWaveEvent";
export { forceKnightsTourEvent } from "../events/knightsTourEvent";
export { forceLavaLampEvent } from "../events/lavaLampEvent";
export { forceDominoesEvent } from "../events/dominoesEvent";
export { forceInkblotEvent } from "../events/inkblotEvent";
export { forceSoftServeEvent } from "../events/softServeEvent";
export { forceDollarSignEvent } from "../events/dollarSignEvent";
export { forceMobiusEvent } from "../events/mobiusEvent";
export { forceSwissRollEvent } from "../events/swissRollEvent";
export { forceDodgeballEvent } from "../events/dodgeballEvent";
export { forceCongaLineEvent } from "../events/congaLineEvent";
export { forceSpinningTopEvent } from "../events/spinningTopEvent";
export { forceGobblerEvent } from "../events/gobblerEvent";
export { forceMajoretteEvent } from "../events/majoretteEvent";
export { forceHulaHoopEvent } from "../events/hulaHoopEvent";
export { forceCalligraphyEvent } from "../events/calligraphyEvent";
export { forceSnakeCharmerEvent } from "../events/snakeCharmerEvent";
export { forcePlateSpinnerEvent } from "../events/plateSpinnerEvent";
export { forceFerrisWheelEvent } from "../events/ferrisWheelEvent";
export { forceBucketBrigadeEvent } from "../events/bucketBrigadeEvent";
export { forceSkyLanternsEvent } from "../events/skyLanternsEvent";
export { forceEngraverEvent } from "../events/engraverEvent";
export { forceXRayEvent } from "../events/xRayEvent";
export { forceLaserLassoEvent } from "../events/laserLassoEvent";
export { forceHexRingEvent } from "../events/hexRingEvent";
export { forcePortcullisEvent } from "../events/portcullisEvent";
export { forceKeyholeEvent } from "../events/keyholeEvent";
export { forceDefibrillatorEvent } from "../events/defibrillatorEvent";
export { forceCircuitBoardEvent } from "../events/circuitBoardEvent";
export { forceMjolnirEvent } from "../events/mjolnirEvent";
export { forceArcFlashEvent } from "../events/arcFlashEvent";
export { forceFourCornersEvent } from "../events/fourCornersEvent";
export { forceBoltWheelEvent } from "../events/boltWheelEvent";
export { forceMinefieldEvent } from "../events/minefieldEvent";
export { forceCannonadeEvent } from "../events/cannonadeEvent";
export { forceStickyBombsEvent } from "../events/stickyBombsEvent";
export { forceCrossblastEvent } from "../events/crossblastEvent";
export { forceMortarEvent } from "../events/mortarEvent";
export { forceFlashbangEvent } from "../events/flashbangEvent";
export { forceSentryTurretEvent } from "../events/sentryTurretEvent";
export { forceShotgunEvent } from "../events/shotgunEvent";
export { forceBossFightEvent } from "../events/bossFightEvent";
export { forceGunshipEvent } from "../events/gunshipEvent";
export { forceBulletTimeEvent } from "../events/bulletTimeEvent";
export { forceFlechettesEvent } from "../events/flechettesEvent";
export { forceRadarEvent } from "../events/radarEvent";
export { forceBingoEvent } from "../events/bingoEvent";
export { forceLaneHopperEvent } from "../events/laneHopperEvent";
export { forceSimonSaysEvent } from "../events/simonSaysEvent";
export { forceEqualizerEvent } from "../events/equalizerEvent";
export { forceLoadingBarEvent } from "../events/loadingBarEvent";
export { forceDiceRollEvent } from "../events/diceRollEvent";
export { forceMandalaEvent } from "../events/mandalaEvent";
export { forceZenGardenEvent } from "../events/zenGardenEvent";
export { forceAccordionEvent } from "../events/accordionEvent";
export { forceFizzEvent } from "../events/fizzEvent";
export { forceSoundwaveEvent } from "../events/soundwaveEvent";
export { forceTaffyEvent } from "../events/taffyEvent";
export { forceDripPaintingEvent } from "../events/dripPaintingEvent";
export { forceMothsEvent } from "../events/mothsEvent";
export { forceCurlingEvent } from "../events/curlingEvent";
export { forceClotheslineEvent } from "../events/clotheslineEvent";
export { forceBalloonPopEvent } from "../events/balloonPopEvent";
export { forceSpinBottleEvent } from "../events/spinBottleEvent";
export { forceSkyWriterEvent } from "../events/skyWriterEvent";
export { forceGoldPanEvent } from "../events/goldPanEvent";
export { forceBulldozerEvent } from "../events/bulldozerEvent";
export { forceKoiPondEvent } from "../events/koiPondEvent";
export { forcePipeOrganEvent } from "../events/pipeOrganEvent";
export { forceAntTrailEvent } from "../events/antTrailEvent";
export { forceHotAirBalloonEvent } from "../events/hotAirBalloonEvent";
export { forceLensFlareEvent } from "../events/lensFlareEvent";
export { forceTightropeEvent } from "../events/tightropeEvent";
export { forceNeonSignEvent } from "../events/neonSignEvent";
export { forceLightCageEvent } from "../events/lightCageEvent";
export { forceStairwayEvent } from "../events/stairwayEvent";
export { forceBeaconsEvent } from "../events/beaconsEvent";
export { forceAnvilCrawlerEvent } from "../events/anvilCrawlerEvent";
export { forceNeuronsEvent } from "../events/neuronsEvent";
export { forceBottledBoltEvent } from "../events/bottledBoltEvent";
export { forceThunderbirdEvent } from "../events/thunderbirdEvent";
export { forceSparkGapEvent } from "../events/sparkGapEvent";
export { forceStaticShockEvent } from "../events/staticShockEvent";
export { forceRocketJumpEvent } from "../events/rocketJumpEvent";
export { forceTorpedoesEvent } from "../events/torpedoesEvent";
export { forceAirstrikeEvent } from "../events/airstrikeEvent";
export { forceDambusterEvent } from "../events/dambusterEvent";
export { forceAirburstEvent } from "../events/airburstEvent";
export { forceBombPinwheelEvent } from "../events/bombPinwheelEvent";
export { forceBulletCurtainEvent } from "../events/bulletCurtainEvent";
export { forceTrickShotEvent } from "../events/trickShotEvent";
export { forceRailShooterEvent } from "../events/railShooterEvent";
export { forceSkeetShootEvent } from "../events/skeetShootEvent";
export { forceTripleTapEvent } from "../events/tripleTapEvent";
export { forceTommyGunEvent } from "../events/tommyGunEvent";
export { forceSweeperEvent } from "../events/sweeperEvent";
export { forceClawMachineEvent } from "../events/clawMachineEvent";
export { forceLotteryEvent } from "../events/lotteryEvent";
export { forceWordGuessEvent } from "../events/wordGuessEvent";
export { forceMemoryMatchEvent } from "../events/memoryMatchEvent";
export { forceTicTacToeEvent } from "../events/ticTacToeEvent";
export { forceRevCounterEvent } from "../events/revCounterEvent";
export { forceSluiceEvent } from "../events/sluiceEvent";
export { forceFoundryEvent } from "../events/foundryEvent";
export { forceJetStreamEvent } from "../events/jetStreamEvent";
export { forceMoatEvent } from "../events/moatEvent";
export { forceSeepEvent } from "../events/seepEvent";
export { forceMeanderEvent } from "../events/meanderEvent";
export { forceWaltzEvent } from "../events/waltzEvent";
export { forceGyroscopeEvent } from "../events/gyroscopeEvent";
export { forceDragonflyEvent } from "../events/dragonflyEvent";
export { forceRingTossEvent } from "../events/ringTossEvent";
export { forceSlipstreamEvent } from "../events/slipstreamEvent";
export { forceSheetMusicEvent } from "../events/sheetMusicEvent";
export { forceLeafBlowerEvent } from "../events/leafBlowerEvent";
export { forceLoomEvent } from "../events/loomEvent";
export { forceHighDiveEvent } from "../events/highDiveEvent";
export { forceSowerEvent } from "../events/sowerEvent";
