// event modules, part 2 of 9 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../events/mercuryEvent";
import "../events/alignmentEvent";
import "../events/dandelionEvent";
import "../events/bobberEvent";
import "../events/fishingEvent";
import "../events/scissorsEvent";
import "../events/pulseRifleEvent";
import "../events/splitEvent";
import "../events/pixelateEvent";
import "../events/damBurstEvent";
import "../events/spiderwebEvent";
import "../events/curtainEvent";
import "../events/jellyfishEvent";
import "../events/polarityEvent";
import "../events/colliderEvent";
import "../events/sheepdogEvent";
import "../events/dragonEvent";
import "../events/reflectorEvent";
import "../events/cookieCutterEvent";
import "../events/cinematicEvent";
import "../events/negativeEvent";
import "../events/lockOnEvent";
import "../events/stitchEvent";
import "../events/stockpileEvent";
import "../events/spotWeldEvent";
import "../events/reelsEvent";
import "../events/cashShowerEvent";
import "../events/catherineWheelEvent";
import "../events/multiballEvent";
import "../events/whipEvent";
import "../events/batteryEvent";
import "../events/teslaCoilEvent";
import "../events/jacobsLadderEvent";
import "../events/comicBookEvent";
import "../events/avalancheEvent";
import "../events/beehiveEvent";
import "../events/pogoEvent";
import "../events/laserHarpEvent";
import "../events/lichtenbergEvent";
import "../events/shatterEvent";
import "../events/funnelEvent";
import "../events/grappleEvent";
import "../events/surfEvent";
import "../events/laserTagEvent";
import "../events/ballLightningEvent";
import "../events/eventHorizonEvent";
import "../events/tileFlipEvent";
import "../events/gusherEvent";
import "../events/pinataEvent";
import "../events/giftWrapEvent";
import "../events/triangulateEvent";
import "../events/sparkOfLifeEvent";
import "../events/glassRainEvent";
import "../events/foldEvent";
import "../events/cocoonEvent";
import "../events/gravityAssistEvent";
import "../events/zipLineEvent";
import "../events/breachEvent";
import "../events/stormSurgeEvent";
import "../events/smashAndGrabEvent";
import "../events/shrinkRayEvent";
import "../events/sandstormEvent";
import "../events/juggernautEvent";
import "../events/fuelLineEvent";
import "../events/checkoutEvent";
import "../events/lightningRodEvent";
import "../events/flagEvent";
import "../events/terracesEvent";
import "../events/batteringRamEvent";
import "../events/tetherballEvent";
import "../events/projectorEvent";
import "../events/clearEvent";
import "../events/infinityMirrorEvent";
import "../events/elevatorEvent";
import "../events/migrationEvent";
import "../events/corkscrewEvent";
import "../events/mirrorBallEvent";
import "../events/plasmaGlobeEvent";
import "../events/jellyEvent";
import "../events/shockwaveEvent";
import "../events/passTheParcelEvent";
import "../events/gardenHoseEvent";
import "../events/burningGlassEvent";
import "../events/stormFrontEvent";
import "../events/slidePuzzleEvent";
import "../events/whirlpoolEvent";
import "../events/satellitesEvent";
import "../events/typewriterEvent";
import "../events/railgunEvent";
import "../events/thunderdomeEvent";
import "../events/meltEvent";
import "../events/floodEvent";
import "../events/piedPiperEvent";
import "../events/tentaclesEvent";
import "../events/laserPendulumEvent";
import "../events/electricEelEvent";
import "../events/doubleVisionEvent";
import "../events/honeyEvent";
import "../events/musicalChairsEvent";
import "../events/bubbleWandEvent";
import "../events/hyperspaceEvent";
import "../events/javelinEvent";
import "../events/shuffleEvent";
import "../events/mushroomCloudEvent";
import "../events/relayEvent";
import "../events/laserPointerEvent";
import "../events/stormChaserEvent";
import "../events/baitBallEvent";
import "../events/videoWallEvent";
import "../events/ferrofluidEvent";
import "../events/hideAndSeekEvent";
import "../events/magicCarpetEvent";
import "../events/spirographEvent";
import "../events/electricNetEvent";
import "../events/demolitionEvent";
import "../events/shootingGalleryEvent";
import "../events/collapseEvent";
import "../events/volcanoEvent";
import "../events/skydiversEvent";
import "../events/speedboatEvent";
import "../events/peacockEvent";
import "../events/stormWingsEvent";
import "../events/clusterBombEvent";
import "../events/strafingRunEvent";
import "../events/stainedGlassEvent";
import "../events/uprisingEvent";
import "../events/swingRideEvent";
import "../events/lawnmowerEvent";
import "../events/lightShowEvent";
import "../events/bugZapperEvent";
import "../events/firecrackersEvent";
import "../events/sixShooterEvent";
import "../events/thermalEvent";
import "../events/stalactitesEvent";
import "../events/kintsugiEvent";
import "../events/galaxyEvent";
import "../events/snowdriftEvent";
import "../events/snowballEvent";
import "../events/cartwheelEvent";
// the dev test bar's hooks
export { forceMercuryEvent } from "../events/mercuryEvent";
export { forceAlignmentEvent } from "../events/alignmentEvent";
export { forceDandelionEvent } from "../events/dandelionEvent";
export { forceBobberEvent } from "../events/bobberEvent";
export { forceFishingEvent } from "../events/fishingEvent";
export { forceScissorsEvent } from "../events/scissorsEvent";
export { forcePulseRifleEvent } from "../events/pulseRifleEvent";
export { forceSplitEvent } from "../events/splitEvent";
export { forcePixelateEvent } from "../events/pixelateEvent";
export { forceDamBurstEvent } from "../events/damBurstEvent";
export { forceSpiderwebEvent } from "../events/spiderwebEvent";
export { forceCurtainEvent } from "../events/curtainEvent";
export { forceJellyfishEvent } from "../events/jellyfishEvent";
export { forcePolarityEvent } from "../events/polarityEvent";
export { forceColliderEvent } from "../events/colliderEvent";
export { forceSheepdogEvent } from "../events/sheepdogEvent";
export { forceDragonEvent } from "../events/dragonEvent";
export { forceReflectorEvent } from "../events/reflectorEvent";
export { forceCookieCutterEvent } from "../events/cookieCutterEvent";
export { forceCinematicEvent } from "../events/cinematicEvent";
export { forceNegativeEvent } from "../events/negativeEvent";
export { forceLockOnEvent } from "../events/lockOnEvent";
export { forceStitchEvent } from "../events/stitchEvent";
export { forceStockpileEvent } from "../events/stockpileEvent";
export { forceSpotWeldEvent } from "../events/spotWeldEvent";
export { forceReelsEvent } from "../events/reelsEvent";
export { forceCashShowerEvent } from "../events/cashShowerEvent";
export { forceCatherineWheelEvent } from "../events/catherineWheelEvent";
export { forceMultiballEvent } from "../events/multiballEvent";
export { forceWhipEvent } from "../events/whipEvent";
export { forceBatteryEvent } from "../events/batteryEvent";
export { forceTeslaCoilEvent } from "../events/teslaCoilEvent";
export { forceJacobsLadderEvent } from "../events/jacobsLadderEvent";
export { forceComicBookEvent } from "../events/comicBookEvent";
export { forceAvalancheEvent } from "../events/avalancheEvent";
export { forceBeehiveEvent } from "../events/beehiveEvent";
export { forcePogoEvent } from "../events/pogoEvent";
export { forceLaserHarpEvent } from "../events/laserHarpEvent";
export { forceLichtenbergEvent } from "../events/lichtenbergEvent";
export { forceShatterEvent } from "../events/shatterEvent";
export { forceFunnelEvent } from "../events/funnelEvent";
export { forceGrappleEvent } from "../events/grappleEvent";
export { forceSurfEvent } from "../events/surfEvent";
export { forceLaserTagEvent } from "../events/laserTagEvent";
export { forceBallLightningEvent } from "../events/ballLightningEvent";
export { forceEventHorizonEvent } from "../events/eventHorizonEvent";
export { forceTileFlipEvent } from "../events/tileFlipEvent";
export { forceGusherEvent } from "../events/gusherEvent";
export { forcePinataEvent } from "../events/pinataEvent";
export { forceGiftWrapEvent } from "../events/giftWrapEvent";
export { forceTriangulateEvent } from "../events/triangulateEvent";
export { forceSparkOfLifeEvent } from "../events/sparkOfLifeEvent";
export { forceGlassRainEvent } from "../events/glassRainEvent";
export { forceFoldEvent } from "../events/foldEvent";
export { forceCocoonEvent } from "../events/cocoonEvent";
export { forceGravityAssistEvent } from "../events/gravityAssistEvent";
export { forceZipLineEvent } from "../events/zipLineEvent";
export { forceBreachEvent } from "../events/breachEvent";
export { forceStormSurgeEvent } from "../events/stormSurgeEvent";
export { forceSmashAndGrabEvent } from "../events/smashAndGrabEvent";
export { forceShrinkRayEvent } from "../events/shrinkRayEvent";
export { forceSandstormEvent } from "../events/sandstormEvent";
export { forceJuggernautEvent } from "../events/juggernautEvent";
export { forceFuelLineEvent } from "../events/fuelLineEvent";
export { forceCheckoutEvent } from "../events/checkoutEvent";
export { forceLightningRodEvent } from "../events/lightningRodEvent";
export { forceFlagEvent } from "../events/flagEvent";
export { forceTerracesEvent } from "../events/terracesEvent";
export { forceBatteringRamEvent } from "../events/batteringRamEvent";
export { forceTetherballEvent } from "../events/tetherballEvent";
export { forceProjectorEvent } from "../events/projectorEvent";
export { forceClearEvent } from "../events/clearEvent";
export { forceInfinityMirrorEvent } from "../events/infinityMirrorEvent";
export { forceElevatorEvent } from "../events/elevatorEvent";
export { forceMigrationEvent } from "../events/migrationEvent";
export { forceCorkscrewEvent } from "../events/corkscrewEvent";
export { forceMirrorBallEvent } from "../events/mirrorBallEvent";
export { forcePlasmaGlobeEvent } from "../events/plasmaGlobeEvent";
export { forceJellyEvent } from "../events/jellyEvent";
export { forceShockwaveEvent } from "../events/shockwaveEvent";
export { forcePassTheParcelEvent } from "../events/passTheParcelEvent";
export { forceGardenHoseEvent } from "../events/gardenHoseEvent";
export { forceBurningGlassEvent } from "../events/burningGlassEvent";
export { forceStormFrontEvent } from "../events/stormFrontEvent";
export { forceSlidePuzzleEvent } from "../events/slidePuzzleEvent";
export { forceWhirlpoolEvent } from "../events/whirlpoolEvent";
export { forceSatellitesEvent } from "../events/satellitesEvent";
export { forceTypewriterEvent } from "../events/typewriterEvent";
export { forceRailgunEvent } from "../events/railgunEvent";
export { forceThunderdomeEvent } from "../events/thunderdomeEvent";
export { forceMeltEvent } from "../events/meltEvent";
export { forceFloodEvent } from "../events/floodEvent";
export { forcePiedPiperEvent } from "../events/piedPiperEvent";
export { forceTentaclesEvent } from "../events/tentaclesEvent";
export { forceLaserPendulumEvent } from "../events/laserPendulumEvent";
export { forceElectricEelEvent } from "../events/electricEelEvent";
export { forceDoubleVisionEvent } from "../events/doubleVisionEvent";
export { forceHoneyEvent } from "../events/honeyEvent";
export { forceMusicalChairsEvent } from "../events/musicalChairsEvent";
export { forceBubbleWandEvent } from "../events/bubbleWandEvent";
export { forceHyperspaceEvent } from "../events/hyperspaceEvent";
export { forceJavelinEvent } from "../events/javelinEvent";
export { forceShuffleEvent } from "../events/shuffleEvent";
export { forceMushroomCloudEvent } from "../events/mushroomCloudEvent";
export { forceRelayEvent } from "../events/relayEvent";
export { forceLaserPointerEvent } from "../events/laserPointerEvent";
export { forceStormChaserEvent } from "../events/stormChaserEvent";
export { forceBaitBallEvent } from "../events/baitBallEvent";
export { forceVideoWallEvent } from "../events/videoWallEvent";
export { forceFerrofluidEvent } from "../events/ferrofluidEvent";
export { forceHideAndSeekEvent } from "../events/hideAndSeekEvent";
export { forceMagicCarpetEvent } from "../events/magicCarpetEvent";
export { forceSpirographEvent } from "../events/spirographEvent";
export { forceElectricNetEvent } from "../events/electricNetEvent";
export { forceDemolitionEvent } from "../events/demolitionEvent";
export { forceShootingGalleryEvent } from "../events/shootingGalleryEvent";
export { forceCollapseEvent } from "../events/collapseEvent";
export { forceVolcanoEvent } from "../events/volcanoEvent";
export { forceSkydiversEvent } from "../events/skydiversEvent";
export { forceSpeedboatEvent } from "../events/speedboatEvent";
export { forcePeacockEvent } from "../events/peacockEvent";
export { forceStormWingsEvent } from "../events/stormWingsEvent";
export { forceClusterBombEvent } from "../events/clusterBombEvent";
export { forceStrafingRunEvent } from "../events/strafingRunEvent";
export { forceStainedGlassEvent } from "../events/stainedGlassEvent";
export { forceUprisingEvent } from "../events/uprisingEvent";
export { forceSwingRideEvent } from "../events/swingRideEvent";
export { forceLawnmowerEvent } from "../events/lawnmowerEvent";
export { forceLightShowEvent } from "../events/lightShowEvent";
export { forceBugZapperEvent } from "../events/bugZapperEvent";
export { forceFirecrackersEvent } from "../events/firecrackersEvent";
export { forceSixShooterEvent } from "../events/sixShooterEvent";
export { forceThermalEvent } from "../events/thermalEvent";
export { forceStalactitesEvent } from "../events/stalactitesEvent";
export { forceKintsugiEvent } from "../events/kintsugiEvent";
export { forceGalaxyEvent } from "../events/galaxyEvent";
export { forceSnowdriftEvent } from "../events/snowdriftEvent";
export { forceSnowballEvent } from "../events/snowballEvent";
export { forceCartwheelEvent } from "../events/cartwheelEvent";
