// event modules, part 1 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../events/swarmEvent";
import "../events/kickbackEvent";
import "../events/paydayEvent";
import "../events/piggyBankEvent";
import "../events/coinTossEvent";
import "../events/hourglassEvent";
import "../events/rocketEvent";
import "../events/revealEvent";
import "../events/jackpotReelsEvent";
import "../events/chainPayEvent";
import "../events/twisterEvent";
import "../events/trickleEvent";
import "../events/magnetEvent";
import "../events/spilloverEvent";
import "../events/constellationEvent";
import "../events/ascendEvent";
import "../events/risingTideEvent";
import "../events/beanstalkEvent";
import "../events/blessingEvent";
import "../events/haloEvent";
import "../events/meteorShowerEvent";
import "../events/mentorEvent";
import "../events/sparkChainEvent";
import "../events/polishEvent";
import "../events/lighthouseEvent";
import "../events/recruitEvent";
import "../events/promotionDayEvent";
import "../events/alchemyEvent";
import "../events/investmentEvent";
import "../events/dividendsEvent";
import "../events/burstEvent";
import "../events/sprayEvent";
import "../events/rippleEvent";
import "../events/wreckingBallEvent";
import "../events/piledriverEvent";
import "../events/bowlingEvent";
import "../events/thunderclapEvent";
import "../events/bullseyeEvent";
import "../events/popcornEvent";
import "../events/newtonsCradleEvent";
import "../events/juggleEvent";
import "../events/boomerangEvent";
import "../events/heartbeatEvent";
import "../events/clashEvent";
import "../events/asteroidsEvent";
import "../events/whackAMoleEvent";
import "../events/drumrollEvent";
import "../events/shellGameEvent";
import "../events/seesawEvent";
import "../events/scratchEvent";
import "../events/tagEvent";
import "../events/bumpersEvent";
import "../events/catcherEvent";
import "../events/implosionEvent";
import "../events/atomEvent";
import "../events/spiralEvent";
import "../events/loopEvent";
import "../events/eternityEvent";
import "../events/helixEvent";
import "../events/yoYoEvent";
import "../events/racetrackEvent";
import "../events/swingEvent";
import "../events/kaleidoscopeEvent";
import "../events/zipperEvent";
import "../events/sprinklerEvent";
import "../events/clockworkEvent";
import "../events/holeInOneEvent";
import "../events/leapfrogEvent";
import "../events/lineupEvent";
import "../events/stampedeEvent";
import "../events/wormholeEvent";
import "../events/splatEvent";
import "../events/rouletteEvent";
import "../events/freeKickEvent";
import "../events/slalomEvent";
import "../events/lightningEvent";
import "../events/fireHoseEvent";
import "../events/confluenceEvent";
import "../events/sloshEvent";
import "../events/siphonEvent";
import "../events/crossfireEvent";
import "../events/gravityWellEvent";
import "../events/splashdownEvent";
import "../events/geysersEvent";
import "../events/cashCannonEvent";
import "../events/hooverEvent";
import "../events/airShowEvent";
import "../events/leakEvent";
import "../events/climbEvent";
import "../events/kiteEvent";
import "../events/rainbowEvent";
import "../events/branchesEvent";
import "../events/tugOfWarEvent";
import "../events/waterwheelEvent";
import "../events/braidEvent";
import "../events/skimEvent";
import "../events/latticeEvent";
import "../events/fireworksEvent";
import "../events/slingshotEvent";
import "../events/marqueeEvent";
import "../events/cropDusterEvent";
import "../events/bolasEvent";
import "../events/countdownEvent";
import "../events/sparklerEvent";
import "../events/slinkyEvent";
import "../events/pipelineEvent";
import "../events/prismEvent";
import "../events/trampolineEvent";
import "../events/hummingbirdEvent";
import "../events/diveBombEvent";
import "../events/skiJumpEvent";
import "../events/jetpackEvent";
import "../events/bassDropEvent";
import "../events/laserGridEvent";
import "../events/etchEvent";
import "../events/searchlightsEvent";
import "../events/tractorBeamEvent";
import "../events/beamClashEvent";
import "../events/butterflyEvent";
import "../events/kelpEvent";
import "../events/pendulumWaveEvent";
import "../events/formationEvent";
import "../events/ouroborosEvent";
import "../events/bowstringEvent";
import "../events/superlaserEvent";
import "../events/ionStormEvent";
import "../events/glitchEvent";
import "../events/magnifierEvent";
import "../events/waterShowEvent";
// the dev test bar's hooks
export { startSwarmEvent } from "../events/swarmEvent";
export { forceKickbackEvent } from "../events/kickbackEvent";
export { forcePaydayEvent } from "../events/paydayEvent";
export { forcePiggyBankEvent } from "../events/piggyBankEvent";
export { forceCoinTossEvent } from "../events/coinTossEvent";
export { forceHourglassEvent } from "../events/hourglassEvent";
export { forceRocketEvent } from "../events/rocketEvent";
export { forceRevealEvent } from "../events/revealEvent";
export { forceJackpotReelsEvent } from "../events/jackpotReelsEvent";
export { forceChainPayEvent } from "../events/chainPayEvent";
export { forceTwisterEvent } from "../events/twisterEvent";
export { forceTrickleEvent } from "../events/trickleEvent";
export { forceMagnetEvent } from "../events/magnetEvent";
export { forceSpilloverEvent } from "../events/spilloverEvent";
export { forceConstellationEvent } from "../events/constellationEvent";
export { forceAscendEvent } from "../events/ascendEvent";
export { forceRisingTideEvent } from "../events/risingTideEvent";
export { forceBeanstalkEvent } from "../events/beanstalkEvent";
export { forceBlessingEvent } from "../events/blessingEvent";
export { forceHaloEvent } from "../events/haloEvent";
export { forceMeteorShowerEvent } from "../events/meteorShowerEvent";
export { forceMentorEvent } from "../events/mentorEvent";
export { forceSparkChainEvent } from "../events/sparkChainEvent";
export { forcePolishEvent } from "../events/polishEvent";
export { forceLighthouseEvent } from "../events/lighthouseEvent";
export { forceRecruitEvent } from "../events/recruitEvent";
export { forcePromotionDayEvent } from "../events/promotionDayEvent";
export { forceAlchemyEvent } from "../events/alchemyEvent";
export { forceInvestmentEvent } from "../events/investmentEvent";
export { forceDividendsEvent } from "../events/dividendsEvent";
export { forceBurstEvent } from "../events/burstEvent";
export { forceSprayEvent } from "../events/sprayEvent";
export { forceRippleEvent } from "../events/rippleEvent";
export { forceWreckingBallEvent } from "../events/wreckingBallEvent";
export { forcePiledriverEvent } from "../events/piledriverEvent";
export { forceBowlingEvent } from "../events/bowlingEvent";
export { forceThunderclapEvent } from "../events/thunderclapEvent";
export { forceBullseyeEvent } from "../events/bullseyeEvent";
export { forcePopcornEvent } from "../events/popcornEvent";
export { forceNewtonsCradleEvent } from "../events/newtonsCradleEvent";
export { forceJuggleEvent } from "../events/juggleEvent";
export { forceBoomerangEvent } from "../events/boomerangEvent";
export { forceHeartbeatEvent } from "../events/heartbeatEvent";
export { forceClashEvent } from "../events/clashEvent";
export { forceAsteroidsEvent } from "../events/asteroidsEvent";
export { forceWhackAMoleEvent } from "../events/whackAMoleEvent";
export { forceDrumrollEvent } from "../events/drumrollEvent";
export { forceShellGameEvent } from "../events/shellGameEvent";
export { forceSeesawEvent } from "../events/seesawEvent";
export { forceScratchEvent } from "../events/scratchEvent";
export { forceTagEvent } from "../events/tagEvent";
export { forceBumpersEvent } from "../events/bumpersEvent";
export { forceCatcherEvent } from "../events/catcherEvent";
export { forceImplosionEvent } from "../events/implosionEvent";
export { forceAtomEvent } from "../events/atomEvent";
export { forceSpiralEvent } from "../events/spiralEvent";
export { forceLoopEvent } from "../events/loopEvent";
export { forceEternityEvent } from "../events/eternityEvent";
export { forceHelixEvent } from "../events/helixEvent";
export { forceYoYoEvent } from "../events/yoYoEvent";
export { forceRacetrackEvent } from "../events/racetrackEvent";
export { forceSwingEvent } from "../events/swingEvent";
export { forceKaleidoscopeEvent } from "../events/kaleidoscopeEvent";
export { forceZipperEvent } from "../events/zipperEvent";
export { forceSprinklerEvent } from "../events/sprinklerEvent";
export { forceClockworkEvent } from "../events/clockworkEvent";
export { forceHoleInOneEvent } from "../events/holeInOneEvent";
export { forceLeapfrogEvent } from "../events/leapfrogEvent";
export { forceLineupEvent } from "../events/lineupEvent";
export { forceStampedeEvent } from "../events/stampedeEvent";
export { forceWormholeEvent } from "../events/wormholeEvent";
export { forceSplatEvent } from "../events/splatEvent";
export { forceRouletteEvent } from "../events/rouletteEvent";
export { forceFreeKickEvent } from "../events/freeKickEvent";
export { forceSlalomEvent } from "../events/slalomEvent";
export { forceLightningEvent } from "../events/lightningEvent";
export { forceFireHoseEvent } from "../events/fireHoseEvent";
export { forceConfluenceEvent } from "../events/confluenceEvent";
export { forceSloshEvent } from "../events/sloshEvent";
export { forceSiphonEvent } from "../events/siphonEvent";
export { forceCrossfireEvent } from "../events/crossfireEvent";
export { forceGravityWellEvent } from "../events/gravityWellEvent";
export { forceSplashdownEvent } from "../events/splashdownEvent";
export { forceGeysersEvent } from "../events/geysersEvent";
export { forceCashCannonEvent } from "../events/cashCannonEvent";
export { forceHooverEvent } from "../events/hooverEvent";
export { forceAirShowEvent } from "../events/airShowEvent";
export { forceLeakEvent } from "../events/leakEvent";
export { forceClimbEvent } from "../events/climbEvent";
export { forceKiteEvent } from "../events/kiteEvent";
export { forceRainbowEvent } from "../events/rainbowEvent";
export { forceBranchesEvent } from "../events/branchesEvent";
export { forceTugOfWarEvent } from "../events/tugOfWarEvent";
export { forceWaterwheelEvent } from "../events/waterwheelEvent";
export { forceBraidEvent } from "../events/braidEvent";
export { forceSkimEvent } from "../events/skimEvent";
export { forceLatticeEvent } from "../events/latticeEvent";
export { forceFireworksEvent } from "../events/fireworksEvent";
export { forceSlingshotEvent } from "../events/slingshotEvent";
export { forceMarqueeEvent } from "../events/marqueeEvent";
export { forceCropDusterEvent } from "../events/cropDusterEvent";
export { forceBolasEvent } from "../events/bolasEvent";
export { forceCountdownEvent } from "../events/countdownEvent";
export { forceSparklerEvent } from "../events/sparklerEvent";
export { forceSlinkyEvent } from "../events/slinkyEvent";
export { forcePipelineEvent } from "../events/pipelineEvent";
export { forcePrismEvent } from "../events/prismEvent";
export { forceTrampolineEvent } from "../events/trampolineEvent";
export { forceHummingbirdEvent } from "../events/hummingbirdEvent";
export { forceDiveBombEvent } from "../events/diveBombEvent";
export { forceSkiJumpEvent } from "../events/skiJumpEvent";
export { forceJetpackEvent } from "../events/jetpackEvent";
export { forceBassDropEvent } from "../events/bassDropEvent";
export { forceLaserGridEvent } from "../events/laserGridEvent";
export { forceEtchEvent } from "../events/etchEvent";
export { forceSearchlightsEvent } from "../events/searchlightsEvent";
export { forceTractorBeamEvent } from "../events/tractorBeamEvent";
export { forceBeamClashEvent } from "../events/beamClashEvent";
export { forceButterflyEvent } from "../events/butterflyEvent";
export { forceKelpEvent } from "../events/kelpEvent";
export { forcePendulumWaveEvent } from "../events/pendulumWaveEvent";
export { forceFormationEvent } from "../events/formationEvent";
export { forceOuroborosEvent } from "../events/ouroborosEvent";
export { forceBowstringEvent } from "../events/bowstringEvent";
export { forceSuperlaserEvent } from "../events/superlaserEvent";
export { forceIonStormEvent } from "../events/ionStormEvent";
export { forceGlitchEvent } from "../events/glitchEvent";
export { forceMagnifierEvent } from "../events/magnifierEvent";
export { forceWaterShowEvent } from "../events/waterShowEvent";
export { forceBoostEvent } from "../events/boostEvent";
export { forceUnionEvent } from "../events/unionEvent";
export { forceHuntEvent } from "../events/huntEvent";
