// event modules, part 4 of 8 (see index.ts): each registers
// itself with the event-proc pool when it loads
import "../events/courierEvent";
import "../events/rodeoEvent";
import "../events/crosshairEvent";
import "../events/irisEvent";
import "../events/bankShotEvent";
import "../events/sunbeamsEvent";
import "../events/stargateEvent";
import "../events/catsCradleEvent";
import "../events/thunderheadEvent";
import "../events/pitchforkEvent";
import "../events/jumperCablesEvent";
import "../events/lashEvent";
import "../events/sparkPlugEvent";
import "../events/liveWireEvent";
import "../events/fuseRaceEvent";
import "../events/bouncingBettyEvent";
import "../events/pressureCookerEvent";
import "../events/hotPotatoEvent";
import "../events/daisyChainEvent";
import "../events/shapedChargeEvent";
import "../events/detcordEvent";
import "../events/bulletBloomEvent";
import "../events/highNoonEvent";
import "../events/hailfireEvent";
import "../events/dervishEvent";
import "../events/invadersEvent";
import "../events/gunKataEvent";
import "../events/lockbusterEvent";
import "../events/connectFourEvent";
import "../events/comboEvent";
import "../events/skeeBallEvent";
import "../events/bubbleShooterEvent";
import "../events/deltaEvent";
import "../events/hydrantEvent";
import "../events/cloverleafEvent";
import "../events/pinstripeEvent";
import "../events/faucetEvent";
import "../events/showerheadEvent";
import "../events/binaryStarEvent";
import "../events/hopscotchEvent";
import "../events/tadpolesEvent";
import "../events/blinkEvent";
import "../events/bumperCarsEvent";
import "../events/pigeonsEvent";
import "../events/squidEvent";
import "../events/waterPistolEvent";
import "../events/poiEvent";
import "../events/bartenderEvent";
import "../events/poleVaultEvent";
import "../events/paintRollerEvent";
import "../events/buzzsawEvent";
import "../events/lightCyclesEvent";
import "../events/fiberOpticEvent";
import "../events/daddyLonglegsEvent";
import "../events/knighthoodEvent";
import "../events/cuttingTorchEvent";
import "../events/stElmosFireEvent";
import "../events/steppedLeaderEvent";
import "../events/trolleyEvent";
import "../events/boltBounceEvent";
import "../events/stormCrownEvent";
import "../events/vanDeGraaffEvent";
import "../events/barrelRollEvent";
import "../events/bombStackEvent";
import "../events/romanCandleEvent";
import "../events/whistlersEvent";
import "../events/trebuchetEvent";
import "../events/dropPodsEvent";
import "../events/bombCarouselEvent";
import "../events/lastStandEvent";
import "../events/tinCanEvent";
import "../events/pointDefenseEvent";
import "../events/targetPracticeEvent";
import "../events/flareGunEvent";
import "../events/rappelEvent";
import "../events/stackerEvent";
import "../events/coinPusherEvent";
import "../events/highStrikerEvent";
import "../events/noteHighwayEvent";
import "../events/safecrackerEvent";
import "../events/gumballMachineEvent";
import "../events/ninjaEvent";
import "../events/bungeeEvent";
import "../events/funnelCakeEvent";
import "../events/chrysanthemumEvent";
import "../events/crossroadsEvent";
import "../events/waterslideEvent";
import "../events/bannerEvent";
import "../events/hauntEvent";
import "../events/mapleSeedsEvent";
import "../events/donutsEvent";
import "../events/hamsterWheelEvent";
import "../events/lunarLanderEvent";
import "../events/dowsingEvent";
import "../events/matadorEvent";
import "../events/flashFloodEvent";
import "../events/dolphinEvent";
import "../events/pufferEvent";
import "../events/hockeyStopEvent";
import "../events/twirlEvent";
import "../events/whaleEvent";
import "../events/lightPaintingEvent";
import "../events/saberThrowEvent";
import "../events/laserMazeEvent";
import "../events/tapeMeasureEvent";
import "../events/pulsarEvent";
import "../events/shortCircuitEvent";
import "../events/conductorEvent";
import "../events/doubleStrikeEvent";
import "../events/lightningFenceEvent";
import "../events/heatLightningEvent";
import "../events/powderKegsEvent";
import "../events/bombFountainEvent";
import "../events/fragOutEvent";
import "../events/faultLineEvent";
import "../events/willowShellsEvent";
import "../events/swarmStrikeEvent";
import "../events/concentricEvent";
import "../events/grazeEvent";
import "../events/hotfootEvent";
import "../events/dogfightEvent";
import "../events/bulletRoseEvent";
import "../events/armorPiercerEvent";
import "../events/spotterEvent";
import "../events/pegSolitaireEvent";
import "../events/marbleDropEvent";
import "../events/statuesEvent";
import "../events/flappyWispEvent";
import "../events/buriedTreasureEvent";
import "../events/airHockeyEvent";
import "../events/boltOfCashEvent";
import "../events/pendulumPourEvent";
import "../events/popTheCorkEvent";
import "../events/wallJumpEvent";
import "../events/spinDashEvent";
import "../events/cupidEvent";
import "../events/storkEvent";
import "../events/paperPlaneEvent";
import "../events/spikeEvent";
// the dev test bar's hooks
export { forceCourierEvent } from "../events/courierEvent";
export { forceRodeoEvent } from "../events/rodeoEvent";
export { forceCrosshairEvent } from "../events/crosshairEvent";
export { forceIrisEvent } from "../events/irisEvent";
export { forceBankShotEvent } from "../events/bankShotEvent";
export { forceSunbeamsEvent } from "../events/sunbeamsEvent";
export { forceStargateEvent } from "../events/stargateEvent";
export { forceCatsCradleEvent } from "../events/catsCradleEvent";
export { forceThunderheadEvent } from "../events/thunderheadEvent";
export { forcePitchforkEvent } from "../events/pitchforkEvent";
export { forceJumperCablesEvent } from "../events/jumperCablesEvent";
export { forceLashEvent } from "../events/lashEvent";
export { forceSparkPlugEvent } from "../events/sparkPlugEvent";
export { forceLiveWireEvent } from "../events/liveWireEvent";
export { forceFuseRaceEvent } from "../events/fuseRaceEvent";
export { forceBouncingBettyEvent } from "../events/bouncingBettyEvent";
export { forcePressureCookerEvent } from "../events/pressureCookerEvent";
export { forceHotPotatoEvent } from "../events/hotPotatoEvent";
export { forceDaisyChainEvent } from "../events/daisyChainEvent";
export { forceShapedChargeEvent } from "../events/shapedChargeEvent";
export { forceDetcordEvent } from "../events/detcordEvent";
export { forceBulletBloomEvent } from "../events/bulletBloomEvent";
export { forceHighNoonEvent } from "../events/highNoonEvent";
export { forceHailfireEvent } from "../events/hailfireEvent";
export { forceDervishEvent } from "../events/dervishEvent";
export { forceInvadersEvent } from "../events/invadersEvent";
export { forceGunKataEvent } from "../events/gunKataEvent";
export { forceLockbusterEvent } from "../events/lockbusterEvent";
export { forceConnectFourEvent } from "../events/connectFourEvent";
export { forceComboEvent } from "../events/comboEvent";
export { forceSkeeBallEvent } from "../events/skeeBallEvent";
export { forceBubbleShooterEvent } from "../events/bubbleShooterEvent";
export { forceDeltaEvent } from "../events/deltaEvent";
export { forceHydrantEvent } from "../events/hydrantEvent";
export { forceCloverleafEvent } from "../events/cloverleafEvent";
export { forcePinstripeEvent } from "../events/pinstripeEvent";
export { forceFaucetEvent } from "../events/faucetEvent";
export { forceShowerheadEvent } from "../events/showerheadEvent";
export { forceBinaryStarEvent } from "../events/binaryStarEvent";
export { forceHopscotchEvent } from "../events/hopscotchEvent";
export { forceTadpolesEvent } from "../events/tadpolesEvent";
export { forceBlinkEvent } from "../events/blinkEvent";
export { forceBumperCarsEvent } from "../events/bumperCarsEvent";
export { forcePigeonsEvent } from "../events/pigeonsEvent";
export { forceSquidEvent } from "../events/squidEvent";
export { forceWaterPistolEvent } from "../events/waterPistolEvent";
export { forcePoiEvent } from "../events/poiEvent";
export { forceBartenderEvent } from "../events/bartenderEvent";
export { forcePoleVaultEvent } from "../events/poleVaultEvent";
export { forcePaintRollerEvent } from "../events/paintRollerEvent";
export { forceBuzzsawEvent } from "../events/buzzsawEvent";
export { forceLightCyclesEvent } from "../events/lightCyclesEvent";
export { forceFiberOpticEvent } from "../events/fiberOpticEvent";
export { forceDaddyLonglegsEvent } from "../events/daddyLonglegsEvent";
export { forceKnighthoodEvent } from "../events/knighthoodEvent";
export { forceCuttingTorchEvent } from "../events/cuttingTorchEvent";
export { forceStElmosFireEvent } from "../events/stElmosFireEvent";
export { forceSteppedLeaderEvent } from "../events/steppedLeaderEvent";
export { forceTrolleyEvent } from "../events/trolleyEvent";
export { forceBoltBounceEvent } from "../events/boltBounceEvent";
export { forceStormCrownEvent } from "../events/stormCrownEvent";
export { forceVanDeGraaffEvent } from "../events/vanDeGraaffEvent";
export { forceBarrelRollEvent } from "../events/barrelRollEvent";
export { forceBombStackEvent } from "../events/bombStackEvent";
export { forceRomanCandleEvent } from "../events/romanCandleEvent";
export { forceWhistlersEvent } from "../events/whistlersEvent";
export { forceTrebuchetEvent } from "../events/trebuchetEvent";
export { forceDropPodsEvent } from "../events/dropPodsEvent";
export { forceBombCarouselEvent } from "../events/bombCarouselEvent";
export { forceLastStandEvent } from "../events/lastStandEvent";
export { forceTinCanEvent } from "../events/tinCanEvent";
export { forcePointDefenseEvent } from "../events/pointDefenseEvent";
export { forceTargetPracticeEvent } from "../events/targetPracticeEvent";
export { forceFlareGunEvent } from "../events/flareGunEvent";
export { forceRappelEvent } from "../events/rappelEvent";
export { forceStackerEvent } from "../events/stackerEvent";
export { forceCoinPusherEvent } from "../events/coinPusherEvent";
export { forceHighStrikerEvent } from "../events/highStrikerEvent";
export { forceNoteHighwayEvent } from "../events/noteHighwayEvent";
export { forceSafecrackerEvent } from "../events/safecrackerEvent";
export { forceGumballMachineEvent } from "../events/gumballMachineEvent";
export { forceNinjaEvent } from "../events/ninjaEvent";
export { forceBungeeEvent } from "../events/bungeeEvent";
export { forceFunnelCakeEvent } from "../events/funnelCakeEvent";
export { forceChrysanthemumEvent } from "../events/chrysanthemumEvent";
export { forceCrossroadsEvent } from "../events/crossroadsEvent";
export { forceWaterslideEvent } from "../events/waterslideEvent";
export { forceBannerEvent } from "../events/bannerEvent";
export { forceHauntEvent } from "../events/hauntEvent";
export { forceMapleSeedsEvent } from "../events/mapleSeedsEvent";
export { forceDonutsEvent } from "../events/donutsEvent";
export { forceHamsterWheelEvent } from "../events/hamsterWheelEvent";
export { forceLunarLanderEvent } from "../events/lunarLanderEvent";
export { forceDowsingEvent } from "../events/dowsingEvent";
export { forceMatadorEvent } from "../events/matadorEvent";
export { forceFlashFloodEvent } from "../events/flashFloodEvent";
export { forceDolphinEvent } from "../events/dolphinEvent";
export { forcePufferEvent } from "../events/pufferEvent";
export { forceHockeyStopEvent } from "../events/hockeyStopEvent";
export { forceTwirlEvent } from "../events/twirlEvent";
export { forceWhaleEvent } from "../events/whaleEvent";
export { forceLightPaintingEvent } from "../events/lightPaintingEvent";
export { forceSaberThrowEvent } from "../events/saberThrowEvent";
export { forceLaserMazeEvent } from "../events/laserMazeEvent";
export { forceTapeMeasureEvent } from "../events/tapeMeasureEvent";
export { forcePulsarEvent } from "../events/pulsarEvent";
export { forceShortCircuitEvent } from "../events/shortCircuitEvent";
export { forceConductorEvent } from "../events/conductorEvent";
export { forceDoubleStrikeEvent } from "../events/doubleStrikeEvent";
export { forceLightningFenceEvent } from "../events/lightningFenceEvent";
export { forceHeatLightningEvent } from "../events/heatLightningEvent";
export { forcePowderKegsEvent } from "../events/powderKegsEvent";
export { forceBombFountainEvent } from "../events/bombFountainEvent";
export { forceFragOutEvent } from "../events/fragOutEvent";
export { forceFaultLineEvent } from "../events/faultLineEvent";
export { forceWillowShellsEvent } from "../events/willowShellsEvent";
export { forceSwarmStrikeEvent } from "../events/swarmStrikeEvent";
export { forceConcentricEvent } from "../events/concentricEvent";
export { forceGrazeEvent } from "../events/grazeEvent";
export { forceHotfootEvent } from "../events/hotfootEvent";
export { forceDogfightEvent } from "../events/dogfightEvent";
export { forceBulletRoseEvent } from "../events/bulletRoseEvent";
export { forceArmorPiercerEvent } from "../events/armorPiercerEvent";
export { forceSpotterEvent } from "../events/spotterEvent";
export { forcePegSolitaireEvent } from "../events/pegSolitaireEvent";
export { forceMarbleDropEvent } from "../events/marbleDropEvent";
export { forceStatuesEvent } from "../events/statuesEvent";
export { forceFlappyWispEvent } from "../events/flappyWispEvent";
export { forceBuriedTreasureEvent } from "../events/buriedTreasureEvent";
export { forceAirHockeyEvent } from "../events/airHockeyEvent";
export { forceBoltOfCashEvent } from "../events/boltOfCashEvent";
export { forcePendulumPourEvent } from "../events/pendulumPourEvent";
export { forcePopTheCorkEvent } from "../events/popTheCorkEvent";
export { forceWallJumpEvent } from "../events/wallJumpEvent";
export { forceSpinDashEvent } from "../events/spinDashEvent";
export { forceCupidEvent } from "../events/cupidEvent";
export { forceStorkEvent } from "../events/storkEvent";
export { forcePaperPlaneEvent } from "../events/paperPlaneEvent";
export { forceSpikeEvent } from "../events/spikeEvent";
