// every crit lives under src/crits, one folder per kind of crit; other
// modules import crit code only from here
import "./critIcons";
export {
  CRIT_PROC_INFO,
  CRIT_PROC_KINDS,
  CRIT_TIER_CONFIG,
  CRIT_TIER_ORDER,
  RATE_LOCK_SPEED_MULTIPLIER,
  RUSH_HOUR_INTERVAL_SECONDS,
  SPECIAL_CRIT_GATEWAY,
  critProcIcon,
  getCritProcIncomeModifierPercent,
  getCritProcNextMilestoneCount,
  getPriceMatchCost,
  getUniformCritTier,
  isFrozenActive,
  isRateLockActive,
  isRushHourActive,
  isSpendingFreezeActive,
  loadFeaturedCatalog,
  nextCritTier,
  pickCritTierByOdds,
  pickHigherCritTier,
  readCritProcs,
  setCritRandom,
  tierOnlyCrit,
  withFeaturedCatalog,
} from "./critTypes";
export type {
  FloorCritKind,
  IncomeCritKind,
  CritProcKind,
  CritRollResult,
  CritTier,
} from "./critTypes";
export {
  createCritTextSprite,
  critFont,
  drawCritFlash,
  drawCritTextSprite,
  drawPoppingCritText,
  isCritFlashActive,
  syncCritFlashPause,
  warmTierFlashes,
} from "./critFlash";
export type { CritTextSprite } from "./critFlash";
export {
  applyBonusTierIncome,
  applyFloorCrit,
  celebrateBonusTier,
  celebrateBuildingCrit,
  consumeCritUpgrade,
  createBuildingCrits,
  critNow,
  eventProcContext,
  forceCashCrit,
  forceFloorCrit,
  forceIncomeCrit,
  forceCritUpDown,
  forceMergeCrit,
  forceTestCrit,
  getFloorCrit,
  getIncomeCrit,
  getCritTier,
  getMergeCrit,
  isCashCrit,
  isCritDown,
  isCritUp,
  isCritUpgrade,
  openBuildingBadgeCapsule,
  promoteTierKeepingLevel,
  rollCritUpgrade,
  rollFloorBuyCrit,
  triggerCritCelebration,
} from "./floorCrits";
export {
  BADGE_GLITTER_AT,
  BADGE_SHIMMER_AT,
  FEATURED_CRIT_KINDS,
  capsuleRevealContent,
  commitCritCounts,
  drawCapsuleIcon,
  getBadgeFoil,
  getCritBadgeOverlay,
  getCritProcCount,
  hasBadgeCapsule,
  loadFeaturedRewards,
  pickFeaturedBadge,
  playCapsuleRevealBeats,
  queueBadgeFoilReveal,
  recordCritProcLanded,
  takeBadgeCapsule,
  withDraftCritCounts,
} from "./badgeCrits";
export type { BadgeFoil } from "./badgeCrits";
export {
  armTakenEventProc,
  disarmBoostEvent,
  disarmHuntEvent,
  disarmSwarmEvent,
  disarmUnionEvent,
  drawRevealStage,
  getClaimedEventCover,
  isBoostEventArmed,
  isHuntEventArmed,
  isSwarmEventArmed,
  isSwarmSaleActive,
  isUnionEventArmed,
  isVisibleOnFloor,
  loadEventCatalog,
  queueEventParts,
  revealStageTotalMs,
  startBoostEvent,
  startHuntEvent,
  startUnionEvent,
  takeClaimedEventProc,
  triggerSwarmSale,
} from "./animatedCrits";
export type {
  EventCatalog,
  OnScreenFloor,
  OnScreenFloors,
  ScreenAreaLocal,
} from "./animatedCrits";
