// every crit lives under src/crits, one folder per kind of crit; other
// modules import crit code only from here
export {
  CHAIN_CRIT_CONTINUE_CHANCE,
  CRIT_PROC_INFO,
  CRIT_PROC_KINDS,
  CRIT_TIER_CONFIG,
  CRIT_TIER_ORDER,
  GRAND_OPENING_CRIT_COLOR,
  GRAND_OPENING_CRIT_LABEL,
  HEAVENLY_CRIT_COLOR,
  HEAVENLY_CRIT_LABEL,
  LUCKY_CLOVER_CRIT_COUNT,
  LUCKY_CLOVER_CRIT_TIER,
  MYSTIC_CRIT_COLOR,
  MYSTIC_CRIT_LABEL,
  MYSTIC_UPGRADE_COUNT,
  POKER_HAND_CRIT_COUNTS,
  RATE_LOCK_SPEED_MULTIPLIER,
  RUSH_HOUR_INTERVAL_SECONDS,
  SPECIAL_CRIT_GATEWAY,
  UPGRADE_CRIT_COLOR,
  UPGRADE_CRIT_LABEL,
  applyCritProcs,
  consumeBonusTierCrit,
  getBonusTierCrit,
  getCritProcIncomeModifierPercent,
  getCritProcNextMilestoneCount,
  getPriceMatchCost,
  getUniformCritTier,
  isFrozenActive,
  isRateLockActive,
  isRushHourActive,
  isSpendingFreezeActive,
  nextCritTier,
  pickCritTierByOdds,
  pickHigherCritTier,
  readCritProcs,
  runFirstCritProc,
  setCritRandom,
  tierOnlyCrit,
} from "./critTypes";
export type {
  CritMoment,
  CritProcKind,
  CritRollResult,
  CritTier,
} from "./critTypes";
export {
  critFont,
  drawCritFlash,
  drawPoppingCritText,
  getScreenShakeOffset,
  isCritFlashActive,
  playSpecialFlash,
  playTierFlash,
  shakeScreen,
  stopScreenShake,
  syncCritFlashPause,
  triggerScreenShake,
  warmTierFlashes,
} from "./critFlash";
export {
  applyBonusTierIncome,
  applyChainCrit,
  applyFloorCrit,
  celebrateBonusTier,
  celebrateBuildingCrit,
  consumeCritUpgrade,
  createBuildingCrits,
  critNow,
  eventProcContext,
  forceCritMoment,
  forceCritUpDown,
  forceMergeCrit,
  forceTestCrit,
  getCritMoment,
  getCritTier,
  getMergeCrit,
  isCritDown,
  isCritUp,
  isCritUpgrade,
  openBuildingBadgeCapsule,
  promoteTierKeepingLevel,
  rollCritUpgrade,
  rollFloorBuyCrit,
  tierColor,
  triggerCritCelebration,
} from "./floorCrits";
export {
  BADGE_GLITTER_AT,
  BADGE_SHIMMER_AT,
  FEATURED_CRIT_KINDS,
  capsuleRevealContent,
  commitCritCounts,
  drawCapsuleIcon,
  getBadgeFoil,
  getCritBadgeOverlay,
  getCritProcCount,
  hasBadgeCapsule,
  loadFeaturedRewards,
  playCapsuleRevealBeats,
  queueBadgeFoilReveal,
  recordCritProcLanded,
  takeBadgeCapsule,
  withDraftCritCounts,
} from "./badgeCrits";
export type { BadgeFoil } from "./badgeCrits";
export {
  armTakenEventProc,
  disarmBoostEvent,
  disarmHuntEvent,
  disarmSwarmEvent,
  disarmUnionEvent,
  drawRevealStage,
  getClaimedEventCover,
  isBoostEventArmed,
  isHuntEventArmed,
  isSwarmEventArmed,
  isSwarmSaleActive,
  isUnionEventArmed,
  loadEventCatalog,
  loadNextEventPart,
  revealStageTotalMs,
  startBoostEvent,
  startHuntEvent,
  startUnionEvent,
  takeClaimedEventProc,
  triggerSwarmSale,
} from "./animatedCrits";
export type {
  EventCatalog,
  OnScreenFloor,
  OnScreenFloors,
  ScreenAreaLocal,
} from "./animatedCrits";
